### ISSUE TITLE
Do Not Check $LastExitCode - Only set exit 1 if script errors or a different exit code when it is specifically set

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1000]
This one is a bit tricky, in 0.9.10 we were trying to be more helpful in determining whether the script was a success, but ran into issues instead. So we need to stop looking at $LASTEXITCODE and only look at whether the PowerShell script that ran was successful and whether `$env:ChocolateyExitCode` has been specifically set.

This is reverting part of #512 - that caused issues - specifically some code that was included in 33b628525ce7f56acd5f9075c08c89a8723fa0d5.

**Comment by ferventcoder** [comment]
@DarwinJS FYI

**Comment by ferventcoder** [comment]
This might be considered a breaking change for a couple folks if they were calling `Exit 1`

**Comment by DarwinJS** [comment]
Maybe along with this do an uselastexitcode  per package switch, and Choco feature and always report last exit code in the log so it is easy to spot even when being ignored?

What would be challenging is if the design of this means that a packager can't make the package pay attention to lastexitcode if they need it to.

**Comment by ferventcoder** [comment]
You can as a packager pay attention and capture the exit code of arbirtrary executables you run. If you are running any of choco's functions that run processes, it already performs this for you. If your script exits with an error, this is already covered. The only thing that doesn't work is `exit 1` in your scripts.

Also, the only reason I did not finish a release last night was due to adding a feature switch to set the older behavior back on b/c I deemed this a possible breaking change for some folks (who might have been doing things in a non-recommended fashion).

**Comment by ferventcoder** [comment]
Nothing prevents a packager from saying, I'm going to pay attention to the exit codes from xcopy - this is why I mentioned it for you because I know you ran into this issue and it was very perplexing to determine what was causing the package to fail (exit 2 from xcopy)

**Comment by DarwinJS** [comment]
Yes, I was going to mention this in my reply - the ability to globally configure the exit code behavior globally is preferable to having to play with each instance individually.  Not only is it easier for the packager, but an admin can turn it on for a package they did not author to gain insight into failure conditions that affect only their environment.  Glad to hear something was already in the works!

**Comment by ferventcoder** [comment]
This will be out in 0.10.3.
