### ISSUE TITLE
Publish Mono files for other CI Servers

### ISSUE THREAD

**Issue by michaelkschmidt** [chocolatey/choco#1002]
Thanks to Travis CI, it is fairly common to cross compile Windows Builds from Linux.  Would it be possible to publish a zip of the mono build?  Right now we have to build choco each time

The magic folder seems to be code_drop/build_artifacts/chocolatey.

This was briefly discussed here:

![image](https://user-images.githubusercontent.com/12760779/141295643-19fd7da4-fbe0-41f0-9fb6-d2c1f7b03559.png)

UPDATE: As Chocolatey Gitter chat is now unavailable, I've added a screenshot of the Gitter chat.

**Comment by ferventcoder** [comment]
#1153 is related.

**Comment by TheCakeIsNaOH** [comment]
The build should be signed. 

Also, I think a tar archive might be more appropriate than a zip, but either would work.

**Comment by TheCakeIsNaOH** [comment]
Signed mono builds are now available started with 0.12.0 in the github releases:
https://github.com/chocolatey/choco/releases

The build is in the `.tar.gz` file

**Comment by gep13** [comment]
Can this be closed do you think?

**Comment by gep13** [comment]
Having given this some thought, I am going to go ahead and close this off, we are now publishing both Docker images https://hub.docker.com/u/chocolatey as well as publishing a tar.gz of the officially compiled application to each GitHub release, so I don't think any more work is required here.
