### ISSUE TITLE
Chocolatey Install: Automatically Switch to 7zip for Machines without Windows GUI

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#1006]
When installing choco on Server 2016 (without desktop experience), I received the error to set the environment variable to use 7zip instead of built-in windows functions for the install.

Would be nice to detect this condition and handle it automatically.  I think it would affect Server Core 2012 as well?

**Comment by ferventcoder** [comment]
Wrong repository.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/chocolatey.org/issues/434
