### ISSUE TITLE
Packages that run Start-ChocolateyProcessAsAdmin seem to fail when components of a package are already present in the system

### ISSUE THREAD

**Issue by cobrabr** [chocolatey/choco#101]
From chocolatey/chocolatey#625: 

I attempted to install iTunes with Chocolatey 0.9.9-rc5, while already having Bonjour (which is one of iTunes' components) already installed in the system, and got the following error:

```
Chocolatey v0.9.9.0
Installing the following packages:
itunes
By installing you accept licenses for the packages.

iTunes v12.0.1.20141019 (forced)
 7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
 Processing archive: C:\TEMP\chocolatey\iTunes\iTunesInstall.exe
 Extracting  iTunes64.msi
 Extracting  AppleSoftwareUpdate.msi
 Extracting  AppleApplicationSupport.msi
 Extracting  AppleMobileDeviceSupport64.msi
 Extracting  Bonjour64.msi
 Extracting  SetupAdmin.exe
 Everything is Ok
 Files: 6
 Size:       131784496
 Compressed: 122418480
 Installing appleapplicationsupport...
 appleapplicationsupport has been installed.
 Installing applemobiledevicesupport...
 applemobiledevicesupport has been installed.
 Installing bonjour...
 WARNING: Write-ChocolateyFailure is deprecated. If you are the package
 maintainer, please use 'throw $_.Exception' instead.
 [ERROR] Running msiexec with /i "C:\TEMP\chocolatey\iTunes\Bonjour64.msi"
 /quiet /norestart  was not successful. Exit code was '1603' Error Message:
 .
 At C:\ProgramData\chocolatey\helpers\functions\Start-ChocolateyProcessAsAdmin.p
 s1:92 char:5
 +     throw $errorMessage
 +     ~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : OperationStopped: ([ERROR] Running...or Message:
 .:String) [], RuntimeException
     + FullyQualifiedErrorId : [ERROR] Running msiexec with /i "C:\TEMP\chocola
    tey\iTunes\Bonjour64.msi" /quiet /norestart  was not successful. Exit code
    was '1603' Error Message:
 .
itunes install not successful.
Error while running 'C:\ProgramData\chocolatey\lib\iTunes\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details.
Failures:
 - itunes
```

Given the error essage (Running msiexec with /i "C:\TEMP\chocolatey\iTunes\Bonjour64.msi" /quiet /norestart  was not successful. Exit code was '1603'), it seems that the Bonjour installer did not return the expected exit code, which caused Start-ChocolateyProcessAsAdmin to interpret it as an error and abort the install. Either that, or the installer did work properly with Bonjour already installed, so it actually failed (hence the error message).

I tried running that msiexec command manually, and did not get any errors, but didn't get any exit codes, either. Uninstalling Bonjour and running the iTunes installation again worked, and it completed successfully.

**Comment by fraenki** [comment]
Is there any workaround for this issue yet?

**Comment by bc3tech** [comment]
FWIW I get this while trying to update `gitextensions` via `cup`:
```
You have gitextensions v2.48.05 installed. Version 2.48.05.20150903 is available based on your source(s).

gitextensions v2.48.05.20150903 [Approved]
Loading 'chocolatey.licensed' extension.
Virus check: 0/54 scan engines flagged this assembly.
 Due to possible false positives we fail at 5 minimum positives.
 Virus scan engines indicate this file is probably safe. For details see
  https://www.virustotal.com/file/f8541f0e5f60c084778322c7d7014e3e78bc15378ad5d31c231c26229a0c9177/analysis/
Installing GitExtensions-2.48.05-Setup.msi...
ERROR: Running ["C:\WINDOWS\System32\msiexec.exe" /i "d:\users\SYSTEM\AppData\Local\Temp\chocolatey\gitextensions\2.48.0
5.20150903\GitExtensions-2.48.05-Setup.msi" /quiet /norestart] was not successful. Exit code was '1603'. See log for pos
sible error messages.
The upgrade of gitextensions was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\gitextensions\tools\chocolateyInstall.ps1'.
 See log for details.
```
this in Choco 05/31, btw.

**Comment by FNolte** [comment]
I get the same error when installing a package I created myself. 

`Installing eci...
[ERROR] Running msiexec with /i "C:\ProgramData\chocolatey\lib\eci\tools\Eci.msi" /qn /norestart   was not successful. Exit code was '1603' Error Message:
.
At C:\ProgramData\chocolatey\helpers\functions\Start-ChocolateyProcessAsAdmin.ps1:92 char:5
+     throw $errorMessage
+     ~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : OperationStopped: ([ERROR] Running...or Message:
.:String) [], RuntimeException
     + FullyQualifiedErrorId : [ERROR] Running msiexec with /i "C:\ProgramData\chocolatey\lib\eci\tools\Eci.msi" /qn /norestart   was not successful. Exit code was '1603' Error Message:
.
The upgrade of eci was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\eci\tools\chocolateyinstall.ps1'.
See log for details.`

This happens even when I uninstall the application completely and try a fresh install. It only happens on one or two of the computers I have tested it on, and works as expected on others. I am trying to figure out what the problem could be, any advice on what I could do to test it further and narrow down the error?

**Comment by ferventcoder** [comment]
Use /l*v c:\existing\folder\msi.log in your silent arguments. Open the log
and search for return value 3. This will get you close to what the error is
on those systems.

On Tuesday, June 14, 2016, FNolte <notifications@github.com> wrote:

> I get the same error when installing a package I created myself.
>
> `Installing eci...
> [ERROR] Running msiexec with /i
> "C:\ProgramData\chocolatey\lib\eci\tools\Eci.msi" /qn /norestart was not
> successful. Exit code was '1603' Error Message:
> .
> At
> C:\ProgramData\chocolatey\helpers\functions\Start-ChocolateyProcessAsAdmin.ps1:92
> char:5
>
>    - throw $errorMessage
>    - ~~~~~~~~~~~~~~~~~~~
>       - CategoryInfo : OperationStopped: ([ERROR] Running...or Message:
>       .:String) [], RuntimeException
>       - FullyQualifiedErrorId : [ERROR] Running msiexec with /i
>       "C:\ProgramData\chocolatey\lib\eci\tools\Eci.msi" /qn /norestart was not
>       successful. Exit code was '1603' Error Message: . The upgrade of eci was
>       NOT successful. Error while running
>       'C:\ProgramData\chocolatey\lib\eci\tools\chocolateyinstall.ps1'. See log
>       for details.`
>
> This happens even when I uninstall the application completely and try a
> fresh install. It only happens on one or two of the computers I have tested
> it on, and works as expected on others. I am trying to figure out what the
> problem could be, any advice on what I could do to test it further and
> narrow down the error?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/chocolatey/choco/issues/101#issuecomment-225835982>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAD4DhGzvE07yWpURxugIa84Pjgy7USbks5qLnv9gaJpZM4DgSbF>
> .
>


-- 

Rob
"Be passionate in all you do"

http://codebetter.com/robreynolds
http://ferventcoder.com
https://twitter.com/ferventcoder

**Comment by FNolte** [comment]
The error is the following:
Error 1925. You do not have sufficient privileges to complete this installation for all users of the machine.  Log on as administrator and then retry this installation.

It seems the powershell script is not run with admin rights. I am not sure exactly how choco handles this, I am assuming since you have to run the commandline with admin privileges that it somehow transfers it from there? But obviously whatever solution they are using it is not working. I did notice that they start the process with the verb set to runas, which should technically start it as admin, but this does not work as expected on all machines. That is where the error comes from I think. I am not very familiar with the code structure of choco, I could add code to the process as admin script that requests UAC to ensure that you have admin rights to run the installer with, but this will require the userinteraction of hitting the yes button, which is not an ideal solution, especially for automated deployment. 

Any suggestions on how to fix this?

**Comment by ferventcoder** [comment]
@FNolte When you are doing automated deployment, you should always run with administrative context. Otherwise you run into UAC. There is no automated way to get around UAC that I am aware of (that is not a hack at best). I can't think of any tool that will allow you to do automated deployment without an administrative context (unless it is doing things that don't require admin rights).

**Comment by ferventcoder** [comment]
@FNolte I'm also not sure what you are running into - could you provide more detail? Also, please ensure you are on the latest available version of Chocolatey to ensure you have the most fixes.

**Comment by FNolte** [comment]
I am running into the same issue as this thread describes, except it is a package I created myself, although I am sure the same issue will persist with other packages.

I open a commandline with admin privileges and run choco install pacakge -y
I then get the error as described in my earlier comment, with the msi not having enough privileges.
It seems that this part of the code in Start-ChocolateyProcessAsAdmin.ps1 does not work as expected on all machines:
if ([Environment]::OSVersion.Version -ge (new-object 'Version' 6,0)){
    $psi.Verb = "runas"
  }

I added code to test if this is run and the Verb is set as runas, and thus it SHOULD run the msi with admin privelages, but somehow it doesnt work on all machines, and on some of them this causes the installation to fail. Is there a better or more foolproof way of running the msi with admin privileges?

**Comment by FNolte** [comment]
I just saw this interesting tidbit that explains it:

> "ProcessStartInfo.Verb will only have an effect if the process is started by ShellExecuteEx(). Which requires UseShellExecute = true. Redirecting I/O and hiding the window can only work if the process is started by CreateProcess(). Which requires UseShellExecute = false.

Well, that's why it doesn't work. Not sure if forbidding to start a hidden process that bypasses UAC was intentional. Probably. Very probably.

Check this thread for the manifest you need to display the UAC elevation prompt."

**Comment by ferventcoder** [comment]
@FNolte if you are truly running with admin rights and using `Install-ChocolateyPackage` or `Install-ChocolateyInstallPackage` correctly, it will always work because the runas verb is not necessary. And it is correct that it doesn't currently do anything (we have another issue to address this - see #434). It was from when we were not using ShellExecute and that got switched.

**Comment by ferventcoder** [comment]
But to clarify, the switch is unnecessary when you are running with admin rights. 

If you want to investigate this further, I suggest opening a new issue (referencing this one, as this is a different issue), and providing both your chocolateyInstall.ps1 and the debug/verbose log output as suggested in the new issue template. HTH

**Comment by dragon788** [comment]
@cobrabr Did you have Bonjour installed via Chocolatey or was it installed as part of something else (AirPrint or something else that uses it for mDNS)?

**Comment by cobrabr** [comment]
Well, given that this was almost 2 years ago, I don't fully remember. ;) I *believe* I hadn't installed anything from Apple externally, but I could be wrong.

**Comment by geglne** [comment]
I, too, am receiving this on a work device. I have installed in an elevated `cmd` shell. Additionally, my workplace employs the https://www.adminbyrequest.com/ which I have activated before attempting to deploy this package. 

I have tried off and on over the years to install this and I get the same results:

Running Start-ChocolateyProcessAsAdmin -validExitCodes '0' -workingDirectory 'C:\Users\XXXXXXXXXX\AppData\Local\Temp\chocolatey\ConEmu\22.8.7.0' -statements '/p:x64 /quiet /norestart ' -exeToRun 'C:\Users\XXXXXXXXXX\AppData\Local\Temp\chocolatey\ConEmu\22.8.7.0\ConEmuSetup.220807.exe' 
Test-ProcessAdminRights: returning True
Elevating permissions and running ["C:\Users\XXXXXXXXXX\AppData\Local\Temp\chocolatey\ConEmu\22.8.7.0\ConEmuSetup.220807.exe" /p:x64 /quiet /norestart ]. This may take a while, depending on the statements.
Command ["C:\Users\XXXXXXXXXX\AppData\Local\Temp\chocolatey\ConEmu\22.8.7.0\ConEmuSetup.220807.exe" /p:x64 /quiet /norestart ] exited with '21'.
ERROR: Running ["C:\Users\XXXXXXXXXX\AppData\Local\Temp\chocolatey\ConEmu\22.8.7.0\ConEmuSetup.220807.exe" /p:x64 /quiet /norestart ] was not successful. Exit code was '21'. See log for possible error messages.
 at Start-ChocolateyProcessAsAdmin, C:\ProgramData\chocolatey\helpers\functions\Start-ChocolateyProcessAsAdmin.ps1: line 326
at Install-ChocolateyInstallPackage, C:\ProgramData\chocolatey\helpers\functions\Install-ChocolateyInstallPackage.ps1: line 360
at Install-ChocolateyPackage, C:\ProgramData\chocolatey\helpers\functions\Install-ChocolateyPackage.ps1: line 418
at <ScriptBlock>, C:\ProgramData\chocolatey\lib\ConEmu\tools\chocolateyInstall.ps1: line 250
at <ScriptBlock>, C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1: line 59
at <ScriptBlock>, <No file>: line 1
Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\ConEmu\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters '' -preRunHookScripts $null -postRunHookScripts $null'] exited with '21'.
Calling command ['"C:\Windows\System32\shutdown.exe" /a']
Command ['"C:\Windows\System32\shutdown.exe" /a'] exited with '1116'
Capturing package files in 'C:\ProgramData\chocolatey\lib\ConEmu'
 Found 'C:\ProgramData\chocolatey\lib\ConEmu\ConEmu.nupkg'
  with checksum '82078B98AAE74C5E36F72D79DDA4D944'
 Found 'C:\ProgramData\chocolatey\lib\ConEmu\ConEmu.nuspec'
  with checksum '4C8B371148D9226F41C1400234E84B44'
 Found 'C:\ProgramData\chocolatey\lib\ConEmu\tools\chocolateyInstall.ps1'
  with checksum '33F68BE3A0F1BB39FD4EAF74CD3AD540'
 Found 'C:\ProgramData\chocolatey\lib\ConEmu\tools\chocolateyUninstall.ps1'
  with checksum '454C07C893B37DF38713C3A1CC49E020'
Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\ConEmu.22.8.7.0\.arguments".
Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\ConEmu.22.8.7.0\.extra".
Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\ConEmu.22.8.7.0\.version".
Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\ConEmu.22.8.7.0\.sxs".
Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\ConEmu.22.8.7.0\.pin".
Attempting to delete directory "C:\ProgramData\chocolatey\lib-bad\ConEmu".
Sending message 'HandlePackageResultCompletedMessage' out if there are subscribers...
The install of conemu was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\ConEmu\tools\chocolateyInstall.ps1'.
 See log for details.
Moving 'C:\ProgramData\chocolatey\lib\ConEmu'
 to 'C:\ProgramData\chocolatey\lib-bad\ConEmu'
Attempting to delete file "C:\Users\XXXXXXXXXX\AppData\Local\NuGet\Cache\ConEmu.22.8.7.0.nupkg".

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - conemu (exited 21) - Error while running 'C:\ProgramData\chocolatey\lib\ConEmu\tools\chocolateyInstall.ps1'.
 See log for details.
Sending message 'PostRunMessage' out if there are subscribers...
Exiting with 21

**Comment by pauby** [comment]
Does it work when you disable https://www.adminbyrequest.com/  ?

**Comment by geglne** [comment]
I will try again, and this is a relatively new addition on our devices. I have been (every once in awhile) trying for 2-3 years to install with choco, to no avail.

Just re-ran with the same results.

Thank you,
G. Gallaher

On Nov 9, 2022, at 2:35 PM, Paul Broadwith ***@***.***> wrote:

﻿

Does it work when you disable https://www.adminbyrequest.com/ ?
