### ISSUE TITLE
Document extensions

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1011]
This needs documented. The documentation will be over at Chocolatey-wiki. 
https://github.com/chocolatey/choco-wiki/issues/38
- [x] Document extensions and how they work
- [x] Document how to create an extension package

**Comment by daj0ker** [comment]
Hi! I'm interested in doing this. Could you provide details?

**Comment by ferventcoder** [comment]
Howdy @daj0ker - Extensions are PowerShell modules that Chocolatey loads at runtime when it loads it's regular PowerShell module. You can see that with several extensions currently available:

* https://chocolatey.org/packages/Devbox-Common.extension (you may want NuGet Package Explorer to explore this one).
* https://chocolatey.org/packages/chocolatey-fosshub.extension
* https://chocolatey.org/packages/chocolatey-uninstall.extension
* https://chocolatey.org/packages/mm-choco.extension

Note the naming scheme - it's a convention that the package id ends in `.extension`. It's also a convention that there is a `.psm1` script in an `extensions` folder in the package.

**Comment by ferventcoder** [comment]
Hope that helps?
Let me know if you are interested and we can mark this in progress.

**Comment by daj0ker** [comment]
@ferventcoder, I'm not completely sure what to do. 

Do I create a `extensions.md` file in the wiki and add relevant documentation there?

Can you provide more details?

**Comment by ferventcoder** [comment]
@daj0ker Follow the link to the [Wiki codebase](https://github.com/chocolatey/choco-wiki/issues/38). This will be a how to kind of document. So `How-To-Create-Extension-Pacakges.md` is closer to the name. Images go in the image folder as I expect you will have some of those to illustrate points. You did catch that it is markdown.

I will say if you are not familiar with extensions, you should get familiar with extensions first. Writing documentation for something unfamiliar to you is never a good idea. Become a subject matter expert first by looking and using the ones I pointed out, then create your own and see how it works. Then the documentation parts of writing that down should come pretty natural. Documentation is always a good place to get involved with projects, but it can also be quite a bit of work because you must be documenting from experience and know how, yet explaining it in a way that is easily understandable by the reader. I will understand if you decide to look for something else that may be a bit easier to contribute on.

**Comment by ferventcoder** [comment]
I also updated the description to show the two subjects that should be addressed with the docs.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/wiki/How-To-Create-Extensions

**Comment by ferventcoder** [comment]
Also https://chocolatey.org/docs/how-to-create-extensions
