### ISSUE TITLE
Possible bug in Install-ChocolateyPath.ps1

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#1015]
This line checks the existing path without qualifying it for "user" or "machine"
https://github.com/darwinjs/choco/blob/master/src/chocolatey.resources/helpers/functions/Install-ChocolateyPath.ps1#L78

However, the path addition statements later in the code are structured so as to add the path only to the requested scope.

If a packager calls the function with the intent of adding to "machine", shouldn't the code add it to machine EVEN IF it already exists in user?

Paths in machine are [a] available when no one is logged in (e.g. group policy processing), [b] are available to system processes and services (that do not login as the current user) and [c] are available to all users - so it differs significantly in functionality. 

It seems if line 78 also qualified the check by user or machine it would seem to properly handle situations where the path exists in user, but the intent is to make the software available to all users or the system and I _think_ it should also accurately handle situations where the intent is to only update the user's path for them to use the software.

**Comment by ferventcoder** [comment]
Agreed. Hacktoberfest it is.

**Comment by DarwinJS** [comment]
Ok - I'll do this one too as well.

**Comment by ferventcoder** [comment]
IIRC, this entire function could use some modernization (or best practices for PowerShell added in). Splitting all values into an array at `;` would be a good start.

**Comment by DarwinJS** [comment]
OK cool - that's exactly the code I had planned for uninstall, but wasn't sure how much to stick to the existing patterns.

**Comment by DarwinJS** [comment]
Instead of https://github.com/darwinjs/choco/blob/master/src/chocolatey.resources/helpers/functions/Install-ChocolateyPath.ps1#L102-L104,

Is it ok just to call Update-SessionEnvironment like earlier in the same code? : https://github.com/darwinjs/choco/blob/master/src/chocolatey.resources/helpers/functions/Install-ChocolateyPath.ps1#L76

**Comment by DarwinJS** [comment]
Adding some more problem data here - the function does not work when the path being requested is a parent of a path that is already on the path (stumbled upon when using 'c:\users' as a test case).

I believe this would be fixed by parsing the path into an array and comparing our path to each array item for an exact, case insensitive match.

However, this will be more changes than the if statement.

**Comment by DarwinJS** [comment]
PR https://github.com/chocolatey/choco/pull/1017

**Comment by brunoyb** [comment]
Another related issue with that line is that it compares what I want to add with $env:Path always expanded, which means it will always add to the Path again if I'm actually trying to add something that is not expanded (e.g. '%ProgramFiles%\example'). It seems this is already covered by the PR, but I thought it would be nice to keep it documented here (I was searching for an issue and found that this already fixes it).

**Comment by vexx32** [comment]
I am no longer able to reproduce this issue as of 2.3.0 with the following steps on Windows:

1. Clone this repository
2. From the repository root, run the following commands in PowerShell:
   ```powershell
   $testpath = "C:\test\path\001"
   choco pack './tests/packages/add-path/add-path.nuspec'

   # set current process PATH
   $env:PATH = $env:PATH + ";$testPath"
   
   choco install add-path -s . -y --params "'/Path=$testpath /Scope=User'"
   ```
3. Monitor the output, which shows that the User-scope path is checked, finds that the PATH value is not present, and adds it at the appropriate scope.
4. Verify the change by checking the output from `[Environment]::GetEnvironmentVariable('PATH', 'User')`
