### ISSUE TITLE
Improve handling for checksum type

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/choco#1018]
### What You Are Seeing?

In the current version of choco (0.10.3) the `Install-ChocolateyPackage` command has two parameters: checksum and checksumType.
While it is possible to provide the checksumType, this version of chocolatey determins the type based on the length of the string.
### What is Expected?

The checksum should always be checked in the provided checksumType. Or checksumType parameter should be removed and the type discovered based on the length of the string.
In any way the Verifier for community packages should always check for the checksumType to avoid broken packages for customers with older versions of Chocolatey.
### How Did You Get This To Happen? (Steps to Reproduce)
- Create a package with checksumType = sha256, but with a checksum of type md5
- This package can be uploaded to the community feed without any validation or verification error
- While it works for newer Chocolatey versions (0.10.3) it fails for older ones.
### Output Log

This happened wth https://chocolatey.org/packages/git-lfs.install. See https://gist.github.com/choco-bot/d26bee1c74948cbbc0af2e18cfc767c7 for testing output

**Comment by ferventcoder** [comment]
Reference to https://github.com/ferventcoder/checksum/issues/3

**Comment by ferventcoder** [comment]
This is a slight reversal of #922, which was introduced in  v0.10.1.

**Comment by ferventcoder** [comment]
Completed for 0.10.4
