### ISSUE TITLE
Search by tags only

### ISSUE THREAD

**Issue by Apteryx0** [chocolatey/choco#1033]
As per https://groups.google.com/forum/#!topic/chocolatey/HYrC9dUhdZ4, the idea here is to enhance the search/list functionality to be able to search on package tags.

Currently search/list is implemented in the execute_package_search method in file src\chocolatey\infrastructure.app\nuget\NugetList.cs - it calls packageRepository.Search() and gets back a list of packages and then filters that list based on things like Id, pre-release, etc. The list of packages returned is a list of IPackage interfaces, which are here: https://github.com/grendello/nuget/blob/master/src/Core/Packages/IPackage.cs

The actual class is (I think) https://github.com/grendello/nuget/blob/master/src/Core/Packages/DataServicePackage.cs and as you can see along with Id and prerelease it exposes a "tags" property. Thus it should be fairly simple to add a filter for tags.

My end use case is that I want to search for all packages that are installed that I have published - I've published them all with a tag 'aboutgolf' so I would like to do this:

#> choco list -l --tags aboutgolf

I had also prefixed all my package names with 'ag', however, using the IdStartsWith option is not reliable (there already exists a package called simply 'ag').

**Comment by Spitzbub** [comment]
Hi Rob,

I've gotten around to implementing this and am just now reviewing your mailing list reply, which was cryptically "By default one of the fields searched is tags, but it doesn't limit itself to that.". Obviously you'd like to add searching for more than just the tags. What did you have in mind? Were you thinking of a generic search operator, e.g. (if I could dream I'd do it with regexs) --search Tags~/aboutgolf/ (which incidentally would like you do limited and/or logic via multiple Tags~// clauses and (x|y) in the regex), or just add multiple search operators, e.g. --tags and --authors and --dependencies, etc.

What I'm implemented so far is a very simple --with-tag operator. Another question - I looked for unit tests to emulate but couldn't really find any - can you recommend any?

**Comment by ferventcoder** [comment]
Something like `--by-tags-only` would be consistent with `--by-id-only` - https://chocolatey.org/docs/commands-list

**Comment by Spitzbub** [comment]
Fair enough - how about that? Should I go ahead and create a pull request? Or can you point me towards a unit test that would be good source to create test from?

**Comment by ferventcoder** [comment]
Going into 0.10.6
