### ISSUE TITLE
Uninstall-ChocolateyPackage errors if the passed file path is surrounded by quotes

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/choco#1039]
### What You Are Seeing?
When using the `Uninstall-ChocolateyPackage` helper with the hard quoted paths,
a warning with the message is printed: `WARNING: May not be able to find '"C:\Program Files (x86)\Inno Setup 5\unins000.exe"'. Please use full path for executables.`

### What is Expected?
No warning is printed

### How Did You Get This To Happen? (Steps to Reproduce)
Uninstall any program with a NSIS or Inno Setup Installer and which
reads the UninstallString (or any hard quoted file path) from registry and passes it to `Uninstall-ChocolateyPackage`

### Output Log
https://gist.github.com/AdmiringWorm/bac515b64b3d4e22f5eba385b07efb5c
Warning occurs on line 280

**Comment by ferventcoder** [comment]
The bigger error is that it fails. Let's update the title.

**Comment by ferventcoder** [comment]
@AdmiringWorm did you also change the title? That is weird that it shows that you changed the title instead of me.

**Comment by AdmiringWorm** [comment]
what the, no I actually didn't

**Comment by AdmiringWorm** [comment]
and I think the error is unrelated to the issue, as I've run this test before and it succeeded.

**Comment by ferventcoder** [comment]
Related to https://github.com/chocolatey/choco/issues/1167.

Fixed for 0.10.4
