### ISSUE TITLE
Join-Path error when installing Chocolatey as SYSTEM

### ISSUE THREAD

**Issue by splatteredbits** [chocolatey/choco#1042]
### What You Are Seeing?

After installing Chocolatey as SYSTEM, $Global:Error has this error:

```
Join-Path : A positional parameter cannot be found that accepts argument 'chocolatey'.
At C:\Windows\TEMP\chocolatey\chocInstall\tools\chocolateysetup.psm1:198 char:27

+     $defaultInstallPath = Join-Path [Environment]::GetFolderPath(""CommonApplicat ...
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

at Ensure-Permissions, C:\Windows\TEMP\chocolatey\chocInstall\tools\chocolateysetup.psm1: line 198
at Initialize-Chocolatey, C:\Windows\TEMP\chocolatey\chocInstall\tools\chocolateysetup.psm1: line 81
at <ScriptBlock>, C:\Windows\TEMP\chocolatey\chocInstall\tools\chocolateyInstall.ps1: line 16
at <ScriptBlock>, <No file>: line 194
at <ScriptBlock>, E:\Build\WhsInit\Initialize-Computer.ps1: line 183
at <ScriptBlock>, <No file>: line 1
    + CategoryInfo          : InvalidArgument: (:) [Join-Path], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.JoinPathCommand
```

Our unattended installer reports this as a failed install because of the error (it looks in $Global:Error).

When I look at the code, I see that this error is handled by a try/catch block. Unfortunately in PowerShell, caught exceptions are still populated in $Global:Error.

### What is Expected?

I expect that handled errors won't appear in $Global:Error. Otherwise, how do I know if the installation failed or not? 

### How Did You Get This To Happen? (Steps to Reproduce)

* Open PowerShell as SYSTEM: `psexec -d -i -s powershell.exe`
* Run `join-path [Environment]::GetFolderPath("CommonApplicationData") 'chocolatey'`
* Note the error.

If you assign the value of `[Environment]::GetFolderPath("CommonApplicationData")` to a variable, and join with that, you avoid the error, e.g.

```
$commonAppDataPath = [Environment]::GetFolderPath("CommonApplicationData")
join-path $commonAppDatPath 'chocolatey'
```

Or, wrap `[Environment]::GetFolderPath("CommonApplicationData")` with parenthesis:

```
join-path ([Environment]::GetFolderPath("CommonApplicationData")) 'chocolatey'
```

**Comment by ferventcoder** [comment]
> I expect that handled errors won't appear in $Global:Error. Otherwise, how do I know if the installation failed or not?

Typically the install exits with non-zero on a failure.

**Comment by ferventcoder** [comment]
> Or, wrap [Environment]::GetFolderPath("CommonApplicationData") with parenthesis

TIL

**Comment by ferventcoder** [comment]
Out of curiosity, what happened to `CommonApplicationData`?

**Comment by splatteredbits** [comment]
What do you mean?

**Comment by splatteredbits** [comment]
Good to know about the non-zero exit code. That can help us determine if the Chocolatey install failed or not.

Unfortunately, that doesn't help our error _reporting_. We have a daily scheduled task that runs as SYSTEM on developer computers to keep them up-to-date. With our latest update, we are installing Chocolatey. We transcript the update/install process and use the number of errors as our flag to determine if something has gone wrong and notify our team when it has. 

I'll put together a pull request to fix this issue.

**Comment by ferventcoder** [comment]
@splatteredbits Do non-terminating errors get logged into `$Global:Error`? Perhaps you could make a determination of whether errors are terminating or not? 

Although fixing these things would be helpful to not error.

**Comment by ferventcoder** [comment]
> What do you mean?

Why does `CommonApplicationData` evaluate to `$null`?

**Comment by teknowledgist** [comment]
Throwing my $.02 in here...

This is not a run-as-system problem.  For whatever reason, `Join-Path` won't accept the special environment variables as a direct argument (i.e. not in ()).  The same is true for split-path, but the error is different:
```
PS > [Environment]::GetFolderPath("desktop")
C:\Users\user\Desktop\

PS > join-path [Environment]::GetFolderPath("desktop") 'test'
Join-Path : A positional parameter cannot be found that accepts argument 'test'.
At line:1 char:10
+ join-path <<<<  [Environment]::GetFolderPath("desktop") 'test'
    + CategoryInfo          : InvalidArgument: (:) [Join-Path], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.JoinPathCommand

PS > split-path [Environment]::GetFolderPath("desktop")
Split-Path : Cannot convert 'System.String' to the type 'System.Management.Automation.SwitchParameter' required by para
meter 'Qualifier'.
At line:1 char:11
+ split-path <<<<  [Environment]::GetFolderPath("desktop")
    + CategoryInfo          : InvalidArgument: (:) [Split-Path], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.PowerShell.Commands.SplitPathCommand

PS > join-path ([Environment]::GetFolderPath("desktop") 'test')
Unexpected token 'test' in expression or statement.
At line:1 char:58
+ join-path ([Environment]::GetFolderPath("desktop") 'test' <<<< )
    + CategoryInfo          : ParserError: (test:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

PS > join-path ([Environment]::GetFolderPath("desktop")) 'test'
C:\Users\user\Desktop\test
```
At least it should be an easy fix.

**Comment by ferventcoder** [comment]
@teknowledgist yes, and it's already completed. #1045.

**Comment by ferventcoder** [comment]
Closed with https://github.com/chocolatey/choco/commit/3571604e19bfbd9d37b8830f6fd568c82a59dbe3
