### ISSUE TITLE
Set-EnvironmentVariable writes an error when installing Chocolatey as SYSTEM

### ISSUE THREAD

**Issue by splatteredbits** [chocolatey/choco#1043]
### What You Are Seeing?

After installing Chocolatey as SYSTEM, the following handled error is left in $Global:Error:

```
At C:\Windows\TEMP\chocolatey\chocInstall\tools\chocolateyInstall\helpers\functions\Set-EnvironmentVariable.ps1:81 char:5
+     $registryType = $win32RegistryKey.GetValueKind($Name)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
at Set-EnvironmentVariable, C:\Windows\TEMP\chocolatey\chocInstall\tools\chocolateyInstall\helpers\functions\Set-EnvironmentVariable.ps1: line 81
at Install-ChocolateyEnvironmentVariable, C:\Windows\TEMP\chocolatey\chocInstall\tools\chocolateyInstall\helpers\functions\Install-ChocolateyEnvironmentVariable.ps1: line 100
at Set-ChocolateyInstallFolder, C:\Windows\TEMP\chocolatey\chocInstall\tools\chocolateysetup.psm1: line 166
at Initialize-Chocolatey, C:\Windows\TEMP\chocolatey\chocInstall\tools\chocolateysetup.psm1: line 78
at <ScriptBlock>, C:\Windows\TEMP\chocolatey\chocInstall\tools\chocolateyInstall.ps1: line 16
at <ScriptBlock>, <No file>: line 194
at <ScriptBlock>, E:\Build\WhsInit\Initialize-Computer.ps1: line 183
at <ScriptBlock>, <No file>: line 1
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IOException
```

### What is Expected?

The code "handles" this exception with a try/catch block with an empty catch block. Unfortunately, PowerShell still puts handled excetpions in $Global:Error. I expect that handled errors should leave no errors in the $Global:Error array. (Our nightly process sends transcripts of its works and we get a report everyday of errors. These errors give use false negatives which lowers the likelihood we'll see real errors.)

### How Did You Get This To Happen? (Steps to Reproduce)

* Open a PowerShell prompt as SYSTEM: `psexec -d -i -s powershell.exe`.
* Delete the ChocolateyInstall environment variable.
* Install chocolatey.
* After the install $Global:Error has the above error in it.

**Comment by ferventcoder** [comment]
@splatteredbits what are you hoping that is done here (as far as code changes)?

**Comment by ferventcoder** [comment]
Simple fix or something more involved?

**Comment by splatteredbits** [comment]
A test for the existence of the key and/or value rather than a try/catch. I'll get a pull request put together.
