### ISSUE TITLE
Have choco push follow source priorities for default source to push to

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#1046]
On 0.10.3 is seems "choco push" tries to push to chocolatey.org even if it is not present in the source list.

It seems like this means "choco push" defaults to chocolatey.org unless overridden.

Would it make sense to have it follow the source list (with priorities) - but only try the top prioritized source and then error out if there is no API key for it?

It makes sense in for me - but not sure if it does for everyone else.

**Comment by ferventcoder** [comment]
Similar to #62, possibly a duplicate

**Comment by ferventcoder** [comment]
Not completely sure on source priorities. Sources are typically for pulling from.

**Comment by DarwinJS** [comment]
Yes, I would say this is a duplicate of #62 - I'm not so much concerned to use the existing source list as just having a little more control as outlined in #62.

**Comment by ferventcoder** [comment]
Cool, closing as dupe.
