### ISSUE TITLE
Update "Docs" link on main site

### ISSUE THREAD

**Issue by anewuser** [chocolatey/choco#105]
https://chocolatey.org/ has a link (Docs*) to the now-deprecated https://github.com/chocolatey/chocolatey/wiki . Update it to point it to https://github.com/chocolatey/choco/wiki

**Comment by gep13** [comment]
@anewuser this is covered here: https://github.com/chocolatey/chocolatey.org/issues/159

And will be updated once 0.9.9 is officially released.

Thanks for pointing this out though.
