### ISSUE TITLE
Chocolatey install with PackageManagement doesn't work properly.

### ISSUE THREAD

**Issue by veleek** [chocolatey/choco#1052]
### What You Are Seeing?
When installing chocolatey using the Window Powershell OneGet module (e.g. PackageManagement), I get some really wierd behavior and chocolatey doesn't get installed where I expect nor does it seem to work properly.

Note that I'm installing chocolatey from the chocolatey package source.  Yes I realize this is weird, but I wanted choco.exe on my path and installing it using Install-Package seemed like it should be the easiest option.

### What is Expected?
Chocolatey should install correctly and I would expect it to install to the same location as when I run the regular chocolatey install script.

### How Did You Get This To Happen? (Steps to Reproduce)
From an powershell prompt on a Windows 10 machine:
> Install-PackageProvider chocolatey
> $DebugPreference = "Continue"
> Install-Package chocolatey -verbose

### Output Log
https://gist.github.com/veleek/fbb7288f6daa258b3df4dfe6961f7a97

**Comment by ferventcoder** [comment]
It's not only weird, the current provider is an unsupported prototype that was written by Microsoft that didn't even cover all the features available at the time (0.9.8.23, 3 yrs old now).

Not only would I expect issues currently, but I'd prolly be worried about security issues with the prototype. That said we have it on our roadmap to publish an official provider, until then either use ChocolateyGet provider or steer clear of the prototype. HTH.

**Comment by ferventcoder** [comment]
There really isn't much we can do here, but we have https://github.com/chocolatey/chocolatey-onget where you can watch the repo to know when we will be ready.

**Comment by ferventcoder** [comment]
Fixed link

**Comment by ferventcoder** [comment]
Since this is outside of this repo (choco.exe) to fix, and because we don't have official support for PackageManagement yet, I'm going to close this for now.

If you feel this is not the right response, let's start a discussion over in the chocolatey-oneget repo where this would be the appropriate place for issues like this in the future.

**Comment by veleek** [comment]
This is a reasonable response.  Honestly, the biggest problem was trying to figure out if the package provider was up to date or supported.

**Comment by ferventcoder** [comment]
@veleek right on. No worries.

**Comment by ferventcoder** [comment]
Update here - still waiting on upgrade support for OneGet... https://github.com/OneGet/oneget/issues/6
