### ISSUE TITLE
Show the entire text to turn on the allowGlobalConfirmation flag

### ISSUE THREAD

**Issue by jkodroff** [chocolatey/choco#1053]
When chocolatey is run, it asks for confirmation before installing.  There's an option to make confirmation happen implicitly, but the prompt to the user does not display the explicit command of the text to do this.

I propose the text of the confirmation show the entire command syntax to turn on automatic confirmation, e.g. 

```
Note: To confirm automatically next time, Run `choco feature enable -n allowGlobalConfirmation`
```

**Comment by ferventcoder** [comment]
Now in backlog and up for grabs.

**Comment by Cubix651** [comment]
Hi, I would like to contribute. I can do this as the first step.

Is it OK to change this note to: `Note: To confirm automatically next time, use '-y' or consider 'choco feature enable -n allowGlobalConfirmation'.`?

**Comment by ferventcoder** [comment]
Yes.

**Comment by RichiCoder1** [comment]
I didn't realize how much I wanted this until now. Yes please.
@Cubix651 @ferventcoder I'd also recommend showing the command on it's own line if possible. Make it easier to C+P.
