### ISSUE TITLE
Chocolatey can't be installed under docker container microsoft/windowsservercore

### ISSUE THREAD

**Issue by mawl** [chocolatey/choco#1055]
Currently it isn't possible to install chocolatey on windowsservercore docker container.

UPDATE: but it works with http://www.hanselman.com/blog/AptGetForWindowsOneGetAndChocolateyOnWindows10.aspx

### How Did You Get This To Happen? (Steps to Reproduce)
Start a docker container in interactive mode
`docker run -ti microsoft/windowsservercore cmd`

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.
C:\> @powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       11/15/2016   2:54 PM                chocInstall
Getting latest version of the Chocolatey package for download.
Downloading https://chocolatey.org/api/v2/package/chocolatey/0.10.3 to C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip
Extracting C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocInstall...
Unable to unzip package using built-in compression. Set $env:chocolateyUseWindowsCompression = 'false' and call install again to use 7zip to unzip. Error:
 Error HRESULT E_FAIL has been returned from a call to a COM component.
At line:185 char:5
+     throw "Unable to unzip package using built-in compression. Set `$ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to unzip... COM component.:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to unzip package using built-in compression. Set $env:chocolateyUseWindowsCompression = 'false' and call install again to use 7zip to unzip. Error:
 Error HRESULT E_FAIL has been returned from a call to a COM component.
```

with chocolateyUseWindowsCompression = 'false'
```
C:\> @powershell -NoProfile -ExecutionPolicy Bypass -Command SET chocolateyUseWindowsCompression=false && "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
The filename, directory name, or volume label syntax is incorrect.
```

**Comment by ferventcoder** [comment]
@mawl That install script lives on Chocolatey.org, which has it's own repo at https://github.com/chocolatey/chocolatey.org.

Before I close this though, You are calling your statements wrong.

~~~sh
SET chocolateyUseWindowsCompression='false' REM No spaces in the equals
@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
~~~

**Comment by ferventcoder** [comment]
The setting of the environment variable must be on its own line as a separate call in your docker script.

**Comment by mawl** [comment]
@ferventcoder it's not in a Dockerfile, I have used it in interactive mode.

**Comment by ferventcoder** [comment]
@mawl Ah. If you're entry point is cmd, you should run each command separately. If it is powerShell, you may need to adjust both scripts to be PowerShell compliant.

**Comment by ferventcoder** [comment]
@mawl If you want to catch everything in one line, try this instead:

~~~sh
@powershell -NoProfile -ExecutionPolicy Bypass -Command "$env:ChocolateyUseWindowsCompression='false'; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
~~~

Also your method could work, but you missed some syntax:

~~~sh
@powershell -NoProfile -ExecutionPolicy Bypass -Command SET "chocolateyUseWindowsCompression=false" && "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
~~~

**Comment by ferventcoder** [comment]
Actually, that still isn't right (the second one).

**Comment by ferventcoder** [comment]
Updated the second with notes.

**Comment by ferventcoder** [comment]
@mawl consider we are looking at setting things back to using 7za.exe so one doesn't need to set the windows compression value.

**Comment by mawl** [comment]
@ferventcoder thanks for your suggestions, it works now.

**Comment by nicolasgaraza** [comment]
Hi, I have the same issue. I couldn't understand how do you fix it?  How was the script really like.

I'm doing:

`SET "chocolateyUseWindowsCompression=false"; powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" ; SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"`

but is falling with the same error

Thanks

**Comment by mawl** [comment]
Hi Nicolas,

Take a look at
http://stackoverflow.com/questions/41138754/docker-pattern-the-build-container-two-approaches-which-fits-better
.

I use docker's ENV for setting the environment variable (and the chocolatey
version)

ENV chocolateyVersion 0.9.9.12
ENV ChocolateyUseWindowsCompression false

So you can leave the chocolatey install comand untouched.

Regards
Marco


2016-12-27 13:51 GMT+01:00 Nicolas <notifications@github.com>:
