### ISSUE TITLE
Choco does not install any packages because it can't connect to the catalog

### ISSUE THREAD

**Issue by jakealves** [chocolatey/choco#1058]
### What You Are Seeing?
choco is not installing any packages because it says that it can't find any packages.

### What is Expected?
choco is expected to install the package.

### How Did You Get This To Happen? (Steps to Reproduce)
This is running on a fresh Windows Server 2012 R2 virtualbox machine. ( Virtualbox Version 5.1.8 r111374 (Qt5.5.1)). 

After installing by using the following command:
~~~sh
iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
~~~
I then run:
~~~sh
choco list
~~~~
or 
~~~sh
choco install 7zip
~~~

And get messages that say that the connection was terminated by the remote host ( see full log output below ) 

### Output Log
~~~sh
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
~~~

Full Logs:
[choco install error](https://gist.github.com/jakealves/4f1e873488c837c03dd2166cfd12b5f8)
[choco list error with chocolatey url](https://gist.github.com/jakealves/000f9c3aafe4e55896190e743e907e3f)
[choco list error with nuget.org url](https://gist.github.com/jakealves/a83868a0c1b018bee26342d309cfd196)

**Comment by jakealves** [comment]
despite searching through the various tickets to see if this issue was already reported, It dawned on me that I should search focusing on "close by remote host" and found this other issue: https://github.com/chocolatey/choco/issues/1029 - I'm closing this one because its a duplicate of that one.

**Comment by ferventcoder** [comment]
@jakealves is your issue similar to what is being reported? Or is it something not with VirtualBox?

**Comment by jakealves** [comment]
@ferventcoder it was a duplicate, downgrading to Virtualbox 5.0.26 resolved the issue.

**Comment by ferventcoder** [comment]
Ah, good.
