### ISSUE TITLE
Add -BeforeInstall ScriptBlock for Install-ChocolateyPackage

### ISSUE THREAD

**Issue by flcdrg** [chocolatey/choco#1060]
I would like to execute some logic between the download and the install.. eg. around here: https://github.com/chocolatey/choco/blob/stable/src/chocolatey.resources/helpers/functions/Install-ChocolateyPackage.ps1#L313

If there was a new optional argument for Install-ChocolateyPackage that was of type [ScriptBlock] that was executed just before the call to Install-ChocolateyInstallPackage, that would do the job.

My particular scenario is needing to configure some firewall rules (to avoid Windows Firewall displaying a dialog about an application requiring access). I'm currently doing this before the call to Install-ChocolateyPackage, but ideally it would be done as late as possible, but before the actual install takes place, such that if there was a problem with the download then the firewall would not have been set.

**Comment by ferventcoder** [comment]
You can do this now though. 

`Install-ChocolateyPackage` is a combination of 
* `Get-ChocolateyWebFile`
* `Install-ChocolateyInstallPackage`. 

Not saying this isn't a good idea, just saying you have more options.

**Comment by flcdrg** [comment]
I take your point. I'd be happy to do a PR for this if you like the idea though.

**Comment by ferventcoder** [comment]
Sure thing! I was thinking of adding a script block for no icons function. :)

**Comment by flcdrg** [comment]
Rebased, just for good measure

**Comment by ferventcoder** [comment]
Just a follow up on this one - how does Write-FunctionCallLogMessage handle the script block? This question is for @flcdrg and @gep13. That function is the call that logs the parameters. Just curious if it handles the script block properly or if an issue should be filed as a followup on this to be fixed in a later Chocolatey release.
