### ISSUE TITLE
Virus Check - Provide more context on options

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/choco#1061]
If a package's files have not been virus checked, the following message displays upon install:

Virus scan engines indicate this file has not been scanned before.
Upload file?
WARNING: Selection yes WILL upload the fille to a PUBLIC website
 and results will be publicly available. Do not select yes for files
 that should be kept internal.
Upload '<filename' for scanning?
[N] No [Y] Yes [S] Skip (default is "N")

PROBLEM: Information supplied only covers the Yes option. No option can be assumed that the file will not be uploaded and the package will install, but the package only installs on the Skip choice.

SUGGESTION:
[Y] Yes - selecting Yes WILL...blah blah
[N] No - do not not upload the file or install the package.
[S] Skip - skip uploading and install package.

**Comment by ferventcoder** [comment]
I like it.

**Comment by ferventcoder** [comment]
The milestone is a misnomer, it will be implemented in a newer version of pro.

**Comment by ferventcoder** [comment]
I linked this up to a feature in the licensed backlog.

**Comment by ferventcoder** [comment]
@bcurran3 The choice options have more context in them. I wonder if they just don't show up.

**Comment by ferventcoder** [comment]
Added more to the output. Expect this in Licensed edition 1.9.7

**Comment by bcurran3** [comment]
Wording appears to be wrong in Licensed edit 1.9.8:

> Virus scan engines indicate this file has not been scanned before.
> Upload file?
> WARNING: Selecting 'Yes' WILL upload the file to a PUBLIC website
>  and results will be publicly available. Do not select Yes for files
>  that should be kept internal. Selecting 'No' will not upload the file, but will
>  fail the package. Selecting 'Skip' will continue without running binaries (not
>  recommended).
> Upload 'win64_154516.4627.exe' for scanning?
> 
> [N] No [Y] Yes [S] Skip (default is "N")
>   Confirmation (`-y`) is set.
>   Respond within 30 seconds or the default selection will be chosen.

Choose Skip will skip uploading the file but will continue the install.

Last sentence should be changed to:
Selecting 'Skip' will continue without **uploading** binaries (not recommended).

**Comment by ferventcoder** [comment]
Fixed. You will see that in the next release.
