### ISSUE TITLE
I ran choco upgrade all -y and got a line that confuses me: "Download of sjrjbnh1.e10 (-1 B) completed.

### ISSUE THREAD

**Issue by Kla3mus** [chocolatey/choco#1071]
I ran `choco upgrade all -y` and got a line that confuses me: `Download of sjrjbnh1.e10 (-1 B) completed.`

Afterwards I ran `chocolatey list -localonly`, and I found no package with that name. What is it? What did it do?

**Comment by AdmiringWorm** [comment]
@Kla3mus This is most likely a package that needed to download a small file to find out the url for the program, or something similiar.
The `Download of sjrbjbnh1.e10` is just a temporary name they used to download that file to disk (and most likely deleted it afterwards).

**Comment by Kla3mus** [comment]
Nothing dangerous then I take it. I must say i got a little worried something bad was going on. :)

**Comment by ferventcoder** [comment]
@Kla3mus nothing dangerous - you have a package that downloads software from the official FossHub location. The way the FossHub extension methods work is to look at a particular url attribute. It is being fixed now.

**Comment by ferventcoder** [comment]
Here is the relevant issue - https://github.com/chocolatey/chocolatey-coreteampackages/pull/436

Try `choco upgrade chocolatey-fosshub.extension -y`, then attempt your upgrade all again. HTH

**Comment by AdmiringWorm** [comment]
@ferventcoder actually that issue you linked to isn't relevant for this,
The line `Download of sjrjbnh1.e10 (-1 B) completed` actually happens in the `Get-WebContent` function in  chocolatey-core.extension.

It creates a temporary file name and calls `Get-WebFile` with that generated name, which results in the confusing download message.

**Comment by ferventcoder** [comment]
@AdmiringWorm AH! Perhaps a better name that isn't scary could be used then?

**Comment by AdmiringWorm** [comment]
Yeah, it definitely should. Or perhaps using the -Passthru parameter instead of passing a filename?

**Comment by ferventcoder** [comment]
that could be better if it is supported all the way back to posh v2.

**Comment by AdmiringWorm** [comment]
I'm thinking of the `-Passthru` function you have in `Get-WebFile`
https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Get-WebFile.ps1#L88
