### ISSUE TITLE
Running `choco` should produce name/version AND further instructions

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1083]
Right now running `choco` produces `Chocolatey v###` and nothing else, leaving folks sometimes wondering what the next thing they should do.

Instead it would be better if it produced a message like this:

~~~sh
Chocolatey v###
Please run 'choco -?' or 'choco <command> -?' for help menu.
~~~

**Comment by ferventcoder** [comment]
FYI @dragon788

**Comment by Isopolito** [comment]
Hi, I want to start contributing. This seems like a good one to start with. I haven't seen a pull request for this item yet so I assume it's still up for grabs ?

**Comment by ferventcoder** [comment]
Yes sir. Just read over CONTRIBUTING in it's entirety. It is very specific even about how to write your commit messages. HTH. Looking forward to your PR.

**Comment by Isopolito** [comment]
That's awesome, will do. Thanks!

**Comment by Isopolito** [comment]
Sorry about the delay, I don't have much time during the work week... I read CONTRIBUTING, reviewed the code, made the changes, tested the changes. Now I'm going to re-read CONTRIBUTING ;) and send that pull request soon
