### ISSUE TITLE
Choco push regularly timeouts and hangs for a long time after a package is pushed

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/choco#1087]
Happens regularly, here is one example from [AV build](https://ci.appveyor.com/project/chocolatey/chocolatey-coreteampackages/build/750):

```
git-lfs ERROR: 
     Push ERROR 
     Failed to process request. 'Origin Time-out'.  The remote server returned an error: (524) Origin Time-out..

flashplayerplugin ERROR: 
     Push ERROR 
     Failed to process request. 'Origin Time-out'.  The remote server returned an error: (524) Origin Time-out..
```

In this case in both cases packages are actually pushed to gallery - [see report](https://gist.github.com/gep13/bd2eaa76f2a9ab739ca0544c502dca6e/9b77fc7f109dd898173e335c6c1082c8b0f4a862#errors).

This is normal behavior, happens every other day.

**Comment by ferventcoder** [comment]
This is probably more of a https://chocolatey.org issue than it is a choco issue. https://github.com/chocolatey/chocolatey.org/issues. 

The hanging aspect could be looked at with this.

**Comment by ferventcoder** [comment]
To see what choco is waiting for from the remote source.

**Comment by ferventcoder** [comment]
@majkinetor assuming this is better now that we have a different url to push through packages?

**Comment by majkinetor** [comment]
Yeah, doesn't happen any more.

**Comment by ferventcoder** [comment]
Related to and fixed by https://github.com/chocolatey/choco/issues/1285
