### ISSUE TITLE
Choco install --noop does not respect the --limit-output flag.

### ISSUE THREAD

**Issue by kkurasz1** [chocolatey/choco#1093]
### What You Are Seeing?
choco install --noop is noisy even if the --limit-output flag is specified.  Specifically, the chocolateyinstall.ps1 scripts for the specified package and all dependencies is dumped to output.

### What is Expected?
I would expect minimal output messages.  Example: for the firefox package I would expect to see something closer to:
```
Chocolatey would have used NuGet to install packages (if they are not already installed):
firefox

chocolatey-core.extension v1.0.4 [Approved]
Firefox v50.1.0 [Approved]
```

It appears to me that the output from a run with --limit-output and without the flag is identical.

### How Did You Get This To Happen? (Steps to Reproduce)
choco install firefox -dv --noop -s=http://chocolatey.org/api/v2/ --limit-output 

### Output Log
Run using chocolatey 0.10.0
https://gist.github.com/kkurasz1/cdeab6fcc0b05112c1f849aefe456799

### Additional Information
The order of the --noop and --limit-output flags does not appear to matter.
I suspect this issue exists for install, upgrade, and uninstall choco commands.

**Comment by ferventcoder** [comment]
This feels like a duplicate of #931

**Comment by ferventcoder** [comment]
Or at least related.

**Comment by kkurasz1** [comment]
Sorry.  got caught up with creating a case that I didn't look for duplicates.  Yes, I claim this is a duplicate.  It can be closed.
