### ISSUE TITLE
Cannot install any packages from chocolatey package manager

### ISSUE THREAD

**Issue by neel132** [chocolatey/choco#1097]
### 1st Attempt to install nodejs
PS C:\Users\ngala> choco install nodejs.install
Chocolatey v0.10.3
Installing the following packages:
nodejs.install
By installing you accept licenses for the packages.
nodejs.install not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but t
he version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - nodejs.install - nodejs.install not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but t
he version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"

### 2nd Attempt to install nodejs with specific version
PS C:\Users\ngala> choco install nodejs.install --version=7.2.1
Chocolatey v0.10.3
Installing the following packages:
nodejs.install
By installing you accept licenses for the packages.
nodejs.install not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but t
he version does not.
 Version: "7.2.1"
 Source(s): "https://chocolatey.org/api/v2/"

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - nodejs.install - nodejs.install not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but t
he version does not.
 Version: "7.2.1"
 Source(s): "https://chocolatey.org/api/v2/"

### This is the output using -d -v

PS C:\Users\ngala> choco install nodejs.install --version=7.2.1 -d -v
Chocolatey v0.10.3
Chocolatey is running on Windows v 6.1.7601.65536
Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
Command line: "C:\ProgramData\chocolatey\choco.exe" install nodejs.install --version=7.2.1 -d -v
Received arguments: install nodejs.install --version=7.2.1 -d -v
RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
Sending message 'PreRunMessage' out if there are subscribers...
[Pending] Removing all pending packages that should not be considered installed...
The source 'https://chocolatey.org/api/v2/' evaluated to a 'normal' source type

NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
Configuration: CommandName='install'|
CacheLocation='C:\Users\ngala\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://chocolatey.org/api/v2/'|SourceType='normal'|
Debug='True'|Verbose='True'|Force='False'|Noop='False'|
HelpRequested='False'|RegularOutput='True'|QuietOutput='False'|
PromptForConfirmation='True'|AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='nodejs.install'|Version='7.2.1'|
AllVersions='False'|SkipPackageInstallProvider='False'|
PackageNames='nodejs.install'|Prerelease='False'|ForceX86='False'|
OverrideArguments='False'|NotSilent='False'|
ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='6.1.7601.65536'|
Information.PlatformName='Windows 7'|
Information.ChocolateyVersion='0.10.3.0'|
Information.ChocolateyProductVersion='0.10.3'|
Information.FullName='choco, Version=0.10.3.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64Bit='True'|Information.IsInteractive='True'|
Information.IsUserAdministrator='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseFipsCompliantChecksums='False'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IncludeRegistryPrograms='False'|ListCommand.PageSize='25'|
ListCommand.Exact='False'|ListCommand.ByIdOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|FeatureCommand.Command='unknown'|
ConfigCommand.Command='unknown'|PinCommand.Command='unknown'|
_ Chocolatey:ChocolateyInstallCommand - Normal Run Mode _
Installing the following packages:
nodejs.install
By installing you accept licenses for the packages.
[NuGet] The remote server returned an error: (403) Forbidden.
nodejs.install not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but t
he version does not.
 Version: "7.2.1"
 Source(s): "https://chocolatey.org/api/v2/"

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - nodejs.install - nodejs.install not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but t
he version does not.
 Version: "7.2.1"
 Source(s): "https://chocolatey.org/api/v2/"
Sending message 'PostRunMessage' out if there are subscribers...
Exiting with 1

**please help me out with this issue**

**Comment by ferventcoder** [comment]
Here is your hint: `[NuGet] The remote server returned an error: (403) Forbidden.`

It's likely you have something in the way like a proxy you need to get through.

**Comment by ferventcoder** [comment]
I'm going to assume you figured it out as I haven't heard back from you. HTH

**Comment by Zedonboy** [comment]
@ferventcoder i have not figured it yet

**Comment by AlekseiStalker** [comment]
Sorry, I don't understand what is worth doing if such a mistake. Can you describe how to deal with this?

**Comment by ferventcoder** [comment]
@AlekseiStalker It appears you are not passing `-y`, but an em-dash `–y` (https://en.oxforddictionaries.com/grammar/dash-and-em-dash).

* http://www.fileformat.info/info/unicode/char/2d/index.htm (hyphen, what you want)
* http://www.fileformat.info/info/unicode/char/2010/index.htm (also hyphen, probably okay)
* http://www.fileformat.info/info/unicode/char/2014/index.htm (emdash, not what you want)

If you are using Windows on a macOS through VMWare or Virtualbox, you will want to turn off automatically converting `--` to `–`. 

This setting shuts it off globally:
![image](https://user-images.githubusercontent.com/63502/29650773-9fe4203c-8862-11e7-9a80-e91bd27f6d54.png)

**Comment by LariWo** [comment]
Hi! In case that no one found a solution yet:
I have just had problems with the same error and since I have not found anywhere a solution to this, we have tried ourselves how to solve this error. ([NuGet] The remote server returned an error: (403) Forbidden.)

The only thing you have to do is to set the configuration 'proxyBypassList'. So the proxy bypasses the url from which the packages are to be obtained. 
Example: choco config set proxyBypassList *(domain)*
After doing this it worked for us!
