### ISSUE TITLE
Get-FtpFile downloads are slow, possibly because of the use of a 1Kb download buffer

### ISSUE THREAD

**Issue by jamestelfer** [chocolatey/choco#1099]
### What You Are Seeing?
The FTP download rate for a large file is slow compared to HTTP, which should not generally be the case.

Looking at the code for `Get-FtpFile`, I speculate that the small buffer size is to blame. For similar functionality I've found that a much larger buffer is more efficient -- 256Kb-512Kb. There are diminishing returns with increasing buffer size that testing will soon show.

### What is Expected?
FTP should be as fast if not faster than HTTP.

### How Did You Get This To Happen? (Steps to Reproduce)
Downloaded a large from from a local FTP server via `Get-FtpFile`

### Output Log
No pertinent information to share

**Comment by ferventcoder** [comment]
Interesting that there is a divergence between the two.
