### ISSUE TITLE
Handle configuration files better for upgrades

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#110]

**Comment by darrelmiller** [comment]
I'm seeing a bit of weird renaming issue on upgrades
![image](https://cloud.githubusercontent.com/assets/447694/6740400/e00c239a-ce55-11e4-94f3-2f0956683713.png)

**Comment by ferventcoder** [comment]
that's no bueno...

**Comment by darrelmiller** [comment]
If the old versions just had a .bak added then I'm assuming that on future upgrades they would not get renamed again.

**Comment by ferventcoder** [comment]
I think you are correct. I'm a bit leary that this one file was renamed so many times. Do you have relevant log files that you can share in a gist?

**Comment by ferventcoder** [comment]
This is closed with #331
