### ISSUE TITLE
Allow sorting package results by relevance

### ISSUE THREAD

**Issue by RichiCoder1** [chocolatey/choco#1101]
Currently Choco only allows sorting search results by "popularity" aka. download count, or Id. There's no options to fallback to Nuget feed's "relevance". Would be great to add a option to do so.

**Comment by ferventcoder** [comment]
I thought the default search result when `choco search` was by relevance?

**Comment by RichiCoder1** [comment]
I'll double check, but unless something changed inbetween this issue and now, choco search doesn't even allow searching by relevance. Only popularity and id. Pretty sure id default.

**Comment by ferventcoder** [comment]
Fix the default search order to return by relevance.
