### ISSUE TITLE
Username and password for `choco apikey` not encrypted in output

### ISSUE THREAD

**Issue by dragon788** [chocolatey/choco#1106]
### What You Are Seeing?
When I call `choco apikey` with a feed that has a username and password associated, I wouldn't expect the password to appear in plaintext.

```
PS C:\vagrant> choco apikey -k myuser:mypass -s "http://chocolatey.org"
Chocolatey v0.10.3
Added ApiKey for http://chocolatey.org

PS C:\vagrant> choco apikey
Chocolatey v0.10.3
http://chocolatey.org - myuser:mypass
```

### What is Expected?
I expect at least the hashed version or the password to be hidden/obfuscated similar to how `choco source` shows (Authenticated) when a feed has been provided credentials. I can always update a key with new credentials if I'm not sure what they were authenticated with, but I currently can't remove one that is leaking credentials without hacking the `chocolatey.config` file.

```
PS C:\vagrant> choco apikey
Chocolatey v0.10.3
http://chocolatey.org - (Authenticated)
```

### How Did You Get This To Happen? (Steps to Reproduce)
```
choco apikey -k myuser:mypass -s "http://chocolatey.org"
choco apikey
```

**Comment by dragon788** [comment]
@ferventcoder This may fall under security?

**Comment by ferventcoder** [comment]
Interesting. Yeah, I think that would definitely not be something you want to return the output.

**Comment by ferventcoder** [comment]
Completed for 0.10.4
