### ISSUE TITLE
[Documentation] Stop cmd from flashing when scheduler is triggered

### ISSUE THREAD

**Issue by aronovgj** [chocolatey/choco#111]
When scheduling Ketarin to auto-update every x hours a cmd window flashes every time the task is triggered. 

To avoid that create a vbs with the following code and replace the path in the code with wherever ketarinupdate.cmd is. Then put the path of the vbs into the scheduler instead of the line mentioned in the documentation. 

```
Set objShell = WScript.CreateObject("WScript.Shell")
objShell.Run("C:\ProgramData\chocolatey\lib\ChocolateyPackageUpdater\tools\chocopkgup\ketarinupdate.cmd"), 0, True
```

Might want to add this here:
https://github.com/chocolatey/choco/wiki/AutomaticPackages

Might also want to rephrase this because my description looks awful.

**Comment by ferventcoder** [comment]
Take a look. If you are happy with it, close this issue.

**Comment by aronovgj** [comment]
yep, looks good. thanks.

**Comment by aronovgj** [comment]
actually no. consistency:

i have chocolateypackageupdater in the lib folder and in the tools folder. is this supposed to be this way?

either way point 5 points to
`C:\ProgramData\chocolatey\lib\ChocolateyPackageUpdater\tools\chocopkgup\ketarinupdate.cmd`
point 4 points to 
`c:\tools\chocolateypackageupdater\ketarinupdate.cmd`

one of them should be changed.

**Comment by ferventcoder** [comment]
Done. Thanks.
