### ISSUE TITLE
"Business messages" adresses users in a somewhat unprofessional manner

### ISSUE THREAD

**Issue by birgersp** [chocolatey/choco#1111]
Business message ([declared here](https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs#L56)) addresses users in an unprofessional manner.

>You use Chocolatey? You are amazing! Are you ready to take the next step and look even smarter with more awesome features?
>https://chocolatey.org/compare

None of us are using Chocolatey to "look smart". Calling me "amazing" for using a CLI is flippant and honestly seems more sarcastic/degrading than complimentary.

I suggest these messages adress users in a more professional manner.

~~I get it you want us to buy your product but please stop "talking" to me like I'm some 9 year-old.~~

**Comment by ferventcoder** [comment]
@birgersp how would you frame the message? I don't see as childish or talking to a 9 year old at all.

**Comment by birgersp** [comment]
I'd rather frame the message in a more professional/"classy" manner. On the top of my head, I suggest:

> "Enjoy using Chocolatey? Select your flavour and explore amazing features at https://chocolatey.org/compare"

**Comment by ferventcoder** [comment]
It was an attempt to provide compliments, but I see your point.

**Comment by ferventcoder** [comment]
@birgersp would you change any of the other messages? https://github.com/chocolatey/choco/blob/946367a6c263cc2d1b3beec5e6b771404d5f0436/src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs#L55-L97

**Comment by ferventcoder** [comment]
@birgersp is that better?

**Comment by birgersp** [comment]
I'd say it certainly is, thank you. I was forking and creating a PR to suggest some changes but you were too quick for me. I have some suggestions for a couple of the other messages aswell, a PR is imminent.

**Comment by ferventcoder** [comment]
This will be fixed in 0.10.4
