### ISSUE TITLE
[Question] The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by Kristinita** [chocolatey/choco#1115]
### 1. Summary

I try to add in Chocolatey [**package for Jumpshare program**](https://chocolatey.org/packages/jumpshare/2.0.9). Package successfully installed for me, but automatic test is failed.

I rerun test, and Jumpshare again successfully installed for me and failed automatic review. I can not find in Google, how I must solved my problem.

### 2. Expected behavior

[**My full installation output in Gist**](https://gist.github.com/choco-bot/895ff400fc8818cbde809a7f7f2ed194#gistcomment-1959100).

For a long time I did the setting for me:

`choco feature enable -n allowEmptyChecksums`

### 3. Actual behavior

> ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://d21hi1or3tbtjm.cloudfront.net/desktop/windows/JumpshareInstaller-2.0.9.exe'. Exception calling "GetResponse" with "0" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."

[**Automatic test full installation output in Gist**](https://gist.github.com/choco-bot/895ff400fc8818cbde809a7f7f2ed194#file-install-txt).

### 4. Settings

[**My chocolateyinstall.ps1 file**](https://github.com/Kristinita/SashaChocolatey/blob/master/packages/Jumpshare/tools/chocolateyinstall.ps1):

```powershell
$ErrorActionPreference = 'Stop';

$packageName= 'Jumpshare'
$toolsDir   = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"
$url        = 'https://d21hi1or3tbtjm.cloudfront.net/desktop/windows/JumpshareInstaller-2.0.9.exe'
$url64      = ''

$packageArgs = @{
  packageName   = $packageName
  unzipLocation = $toolsDir
  fileType      = 'exe'
  url           = $url
  url64bit      = $url64

  softwareName  = 'Jumpshare*'

  checksum      = ''
  checksumType  = 'sha256'
  checksum64    = ''
  checksumType64= 'sha256'

  silentArgs   = '/S'
}

Install-ChocolateyPackage @packageArgs
```

### 5. Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Chocolatey:**
v0.10.3

Thanks.

**Comment by ferventcoder** [comment]
Howdy. Unfortunately the issue template you see when you created the issue mentions this is not the place to file package issues either. When the verifier failed, did you receive an email?

I know there was a lot in that email, so I'll just point out the link to the Chocolatey test environment - https://github.com/chocolatey/chocolatey-test-environment. Take a look, it will let you determine what may be going on with the test environment. And follow up on the package review on the community repository as the email indicated. Thanks!

**Comment by Kristinita** [comment]
@ferventcoder :

> When the verifier failed, did you receive an email?

Yes, I receive e-mail, but I don't see in my e-mail information, how I can solved my problem.

> this is not the place to file package issues either

Where is situated place for similar issues?

> I'll just point out the link to the Chocolatey test environment

System requirements is [**64-bit processor and OS**](https://github.com/chocolatey/chocolatey-test-environment#requirements). I have only Windows 32-bit.

Thanks.

**Comment by gep13** [comment]
@dragon788 have you documented anywhere the process that you use for testing packages on AppVeyor?  Wondering whether this might help in this situation?

**Comment by dragon788** [comment]
@Kristinita If you jump on https://gitter.im/chocolatey/chocolatey.org we can definitely help you get set up with a remote testing alternative since you only have a 32 bit machine available locally.
