### ISSUE TITLE
AutoUninstaller should use Uninstall Arguments and Override Arguments if provided

### ISSUE THREAD

**Issue by OriBenHur** [chocolatey/choco#1133]
i'm trying to delete the firefox esr package (it was installed using the official repo).
but for some reason the auto unistaller won't recognize the silent uninstall switches ("/S")
seems there is a bug with it.

also through puppet manifest
```
package {'firefoxesr':
	ensure => absent,
	provider => chocolatey,
	uninstall_options => ['-uninstallargs', '"', '/S', '"'],
}
```

it deletes the pack but failed to uninstall the program (from the logs i can see it's not passing the uninstall args)

**Comment by ferventcoder** [comment]
You can't pass uninstall arguments if there is no uninstall script that is called. And currently AutoUninstaller doesn't look at what you've passed. However, that would make a lovely enhancement.

**Comment by ferventcoder** [comment]
Great feedback! Look for this maybe in the next version of Chocolatey. That's what I'm initially scheduling it for.

**Comment by OriBenHur** [comment]
Really? 
I've spent over 2 days trying to make it work. 
Any way the auto Uninstaller recognize the common switchs? 
The Uninstall-ChocolateyPackage include the /S switch and still it didn't use it

**Comment by ferventcoder** [comment]
Better to jump onto something like gitter or slack and ask these questions if you've seemingly set it all up correctly and it doesn't work. Or consider customer options.

**Comment by ferventcoder** [comment]
> Uninstall-ChocolateyPackage

It would work if the package itself calls `Uninstall-ChocolateyPackage`, but as you can see from the package page, there isn't even a chocolateyUninstall.ps1 so there is no chance there will be anything passed. https://chocolatey.org/packages/firefoxesr#files

**Comment by ferventcoder** [comment]
> i'm trying to delete the firefox esr package (it was installed using the official repo).

Also, official != community packages repository. I'm assuming https://chocolatey.org/packages and https://chocolatey.org/api/v2 is what you are referring to here. That is known as the Chocolatey Community Packages Repository, and when you go to https://chocolatey.org/packages, there is a nice link to a disclaimer you should read and understand if you are planning to use these packages for organizational use - https://chocolatey.org/docs/community-packages-disclaimer

**Comment by OriBenHur** [comment]
Thank for your response. 
Really appreciate it 🙂
I'll go over all the links you provided later. 
Thank you again

**Comment by ferventcoder** [comment]
This will be in 0.10.8

**Comment by OriBenHur** [comment]
Great i've waited for this feature.
Thank you so much
