### ISSUE TITLE
[Wiki pull request] Update AU requirements

### ISSUE THREAD

**Issue by wget** [chocolatey/choco#1138]
Please merge the branch https://github.com/wget/chocolatey_choco_wiki/tree/au_posh_5_requirement to your wiki repository: https://github.com/chocolatey/choco.wiki.git

**Comment by ferventcoder** [comment]
Please follow the instructions from the main page to create a Pull Request at https://github.com/chocolatey/choco-wiki. 

Thanks!

**Comment by wget** [comment]
@ferventcoder Thanks. Didn't see you had already a repo :) Will PR there.
