### ISSUE TITLE
Feature Request: choco install: verify checksum of entire package (not installer)

### ISSUE THREAD

**Issue by donbecker** [chocolatey/choco#1144]
### What You Are Seeing?

The checksum options in "choco install" validate checksums of external package dependencies downloaded from the internet. 

While this can ensure content of the external dependency, it does not ensure content of the package and it's files/content (and therefore does not ensure content of repackaged packages with all included dependencies). 

### What is Expected?

Suggest new options "packagechecksum" and "packagechecksumType" to validate the checksum of the entire nupkg file after chocolatey downloads it. Suggest supporting all checksum types supported by present external checksum types (md5, sha1, etc etc).

``cinst chefdk --version 1.1.16 -y -packagechecksum 'ca1cbfe819128dbd252d53f31e3cfae7' -packagechecksumType 'md5'``

I searched quite a bit to determine if this was possible in present functionality. Apologies in advance if I've missed something.

**Comment by ferventcoder** [comment]
It already does this.

**Comment by ferventcoder** [comment]
But I get what you mean. Ensuring that the package coming down has an external verification that you can run client side. I like it.

**Comment by ferventcoder** [comment]
> Suggest new options "packagechecksum" and "packagechecksumType" to validate the checksum of the entire nupkg file after chocolatey downloads it. Suggest supporting all checksum types supported by present external checksum types (md5, sha1, etc etc).

You wouldn't need to specify the type. That is determinable based on the value passed through and it's length.

**Comment by ferventcoder** [comment]
> It already does this.

Sorry, what I meant there is that NuGet.Core already gets an expected package checksum and then verifies it received that same size automatically.

Which isn't the same as this request.

**Comment by ferventcoder** [comment]
@donbecker Recently I reviewed how packagehash was being used locally, and it doesn't appear that is it being used for verifying what was received was what was thought to be received (instead it appears to be only used for checking that a cached version of the package is the same as the remote to choose to redownload the file or not). I think this issue stands then as something that should be addressed.

**Comment by ferventcoder** [comment]
This could play right into authenticode signatures we are looking at implementing as well.

**Comment by donbecker** [comment]
@ferventcoder Sounds great. I still think this would be a great feature for Chocolatey to have regarding integrity of packages.

**Comment by TheCakeIsNaOH** [comment]
After the nuget library uplift, this should be able to be implemented for free as a side effect of implementing validating code signatures on packages, #504

**Comment by TheCakeIsNaOH** [comment]
After previous discussion with @gep13, this issue depends on #508, as code signing has been added to newer nuget versions.

**Comment by TheCakeIsNaOH** [comment]
So it seems like there are two interrelated feature requests here. One is to add a `--package-checksum` argument to the install and upgrade commands, so a user can explicitly verify that the correct `.nupkg` is downloaded. The other is to use the server provided checksum to validate that the download of the `.nupkg` happened correctly. 

From my viewpoint, only public repositories (directly used, or cached) would need to have external checksum passed in for verification, as internal repositories should be trusted (if they are not, then something is wrong with the repository set up). Therefore, for the first feature, I don't think it makes sense to add it. For a user to be able to get a "trusted" checksum, they would have to download a package, inspect the contents, and then get the checksum for the package. At that point, why not just upload the package to a trusted internal repository? Given that organizations should be using internal repositories, this feature would be counterproductive to getting organizations to use internal repositories.

I'm completely open to situations where a  `--package-checksum` argument would be useful, if there is something I'm missing.

Additionally, a simple `--package-checksum` argument would not work in the case of a package that has dependencies which need to be installed/upgraded. Either the install/upgrade logic would require a rework to fail if a dependency install/upgrade is detected when `--package-checksum` is passed, or a way to pass in multiple checksums. Either of these appear to potentially cause bugs, or have unexpected edge cases. 

However, I think the second feature makes sense to add, as it is an additional consistency check along the process.

NuGet does have some support for verifying checksums, but it looks like that is not wired up for the APIs we are using from the libraries, given my poking around in the code. I tested this by using Fiddler's auto responder, and modifying the hash in returned metadata response, which did not cause any errors when installing the package.

**Comment by TheCakeIsNaOH** [comment]
Looking into the NuGet code further, the v3 api actually does not seem to include a package hash, so this would apply to only v2 feeds. (as local feeds don't have an api with which to provide a hash). 

It looks like pretty much all repositories are using sha512 for the hashes and the locally saved `.nupkg.metadata` file uses sha512. Unfortunately, the hash type is not exposed in the package dependency info. I'm thinking a simple length check on the hashes could be used, and if they don't match, then just warn that the hash types mismatch.

**Comment by donbecker** [comment]
@TheCakeIsNaOH 
It's been several years since I requested this feature but I thought I would jump back in. 

"only public repositories (directly used, or cached) would need to have external checksum passed in for verification, as internal repositories should be trusted (if they are not, then something is wrong with the repository set up). "

I disagree as validating that the checksum you have/know represents the correct version of the package is valuable whether the repository is public or private. If a private repositories' packages were compromised, you could see this when validating the package. As part of more secure release processes, some environments require the checksums of packages for traceability and to ensure deployments to multiple environments are the same. See the all the recent discussion around SBOM.

"For a user to be able to get a "trusted" checksum, they would have to download a package, inspect the contents, and then get the checksum for the package. At that point, why not just upload the package to a trusted internal repository? Given that organizations should be using internal repositories, this feature would be counterproductive to getting organizations to use internal repositories."

In some organizations, permissions to download packages from the repository is completely different than having permissions to deploy new packages. In many artifact repositories (Artifactory, Nexus), the checksums are calculated automatically on upload. Choco providing checksum validation adds a feature that many package managers already have and would encourage people to use Choco. 

"Additionally, a simple `--package-checksum` argument would not work in the case of a package that has dependencies which need to be installed/upgraded. Either the install/upgrade logic would require a rework to fail if a dependency install/upgrade is detected when `--package-checksum` is passed, or a way to pass in multiple checksums. Either of these appear to potentially cause bugs, or have unexpected edge cases."

An interesting aspect of NuGet and Choco is the concept that sometimes installing a package will trigger it to download something from somewhere else as part of the package (not as a related package). Other package managers might view this as "not a good thing" as the consumer has little to no assurance the package is deterministic. 

If someone needs to verify the contents of multiple packages, they would need multiple checksums. If choco current supports now or in the future the idea that one package can depend on another, a checksum could be used there to validate the package reference is deterministic. 

Even if a current choco package runs a script that downloads other things, a checksum would still work to provide **SOME** confidence that the user knows what they will be installing (or at minimum the script that is running). For the scope of this request, a checksum would still be helpful. 

I **really really** like where you are going here with this: " the install/upgrade logic would require a rework to fail if a dependency install/upgrade is detected". If choco had a way to communicate clearly to consumers which packages included 100% of what would be installed versus those that would make external calls... I would say that could open lots of doors for Choco being more widely used in high security / govt enviroments, many of which are heavy Windows. 

I've worked in several restricted environments in which we were required to take any Choco package that wasn't 100% complete and create a new package that was 100% complete.

**Comment by TheCakeIsNaOH** [comment]
> If a private repositories' packages were compromised, you could see this when validating the package. As part of more secure release processes, some environments require the checksums of packages for traceability and to ensure deployments to multiple environments are the same. See the all the recent discussion around SBOM.

I could definitely be missing context here, but to my understanding, things like the SBOM are intended for and used in software development to record libraries and components used in compilation/building of the software.

So is your use case for these checksums to help ensure a traceable build environment? Or are you wanting a traceable environment on machines that are more generally deployed? 

NuGet is completely focused on package management for libraries and some developer tools, but Chocolatey is mostly focused on deploying general software to all types of Windows environment, which can include build environments.

> In some organizations, permissions to download packages from the repository is completely different than having permissions to deploy new packages. In many artifact repositories (Artifactory, Nexus), the checksums are calculated automatically on upload. Choco providing checksum validation adds a feature that many package managers already have and would encourage people to use Choco.

Right, so I think we are in agreement that validating that the server provides the correct checksum in its metadata about the package is appropriate. 

> An interesting aspect of NuGet and Choco is the concept that sometimes installing a package will trigger it to download something from somewhere else as part of the package (not as a related package). Other package managers might view this as "not a good thing" as the consumer has little to no assurance the package is deterministic.

In Chocolatey parlance, a package is that downloads thing(s) is called non-embedded. While a package that contains everything and does not download anything at install/upgrade time is called embedded. 

Chocolatey already has features called `allowEmptyChecksums` and `allowEmptyChecksumsSecure` which when enabled ensures that anything downloaded using the built-in helpers is being validated by a checksum. 

And users with a private/internal repository can internalize packages, e.g. changing them from non-embedded to embedded (or changing them so the download location is somewhere under the user's control).
https://docs.chocolatey.org/en-us/guides/create/recompile-packages

Although if there is something that could make this area better, I'm all ears at least. 

> If someone needs to verify the contents of multiple packages, they would need multiple checksums. If choco current supports now or in the future the idea that one package can depend on another, a checksum could be used there to validate the package reference is deterministic.

So you are saying that if a package has a dependency on another package, a checksum should be added as part of that dependency element/declaration to ensure that exact package is installed as the dependency?

> If choco had a way to communicate clearly to consumers which packages included 100% of what would be installed versus those that would make external calls... I would say that could open lots of doors for Choco being more widely used in high security / govt enviroments, many of which are heavy Windows.

> I've worked in several restricted environments in which we were required to take any Choco package that wasn't 100% complete and create a new package that was 100% complete.

So you are saying that you want a Chocolatey feature that will prevent installation of packages that are not embedded? I have been kind ruminating on that for a while, although I haven't really come to an elegant solution that *won't* break packages internalized by C4B package internalizer.

**Comment by miketheitguy** [comment]
I'd like to add on to the OP's comments here. There is a valid use case for this even with internal repositories. Particularly when you have systems that span trust boundaries (where you have some environments with higher or lower classification levels) and you don't want to duplicate infrastructure throughout each environment.

In @TheCakeIsNaOH 's comments, you should "trust the infrastructure"--that's not entirely something that is true. Supply chain compromise, even internally, can be a risk in highly secure environments. Utilizing package checksums on the package download provides a really simple way for a critical system to trust packages retrieved from a system seen as less critical, often times because it could be run by an entirely different org within your company.

I could, for example, deploy execution commands on more secure systems that downloads packages from say, a company's singular internal repository for all things repo downloads (think: Artifactory) while simultaneously guaranteeing, that no matter what, under any circumstance, under any compromise of that system, that my higher privileged environments won't execute code from a malicious package by simply providing a command line hash validation argument on the entire nupkg.

Now, an attacker would have to both compromise the target system to modify the integrity check while simultaneously modifying the package--which renders utilizing the package as a privilege escalation or lateral movement scheme pretty much entirely invalid.

There are compensating capabilities here that exist today in Windows--and that's using Windows Defender Application Control to validate code signatures of PowerShell scripts as well as binaries executing on the target system. While this is inarguably the more secure solution, with policies capable of being protected by the TPM and UEFI NVRAM and Hypervisor separation, it's a lot of work to get that capability going on a Windows platform and would require signing all individual scripts and package files (if you don't trust existing authenticode signatures by 3rd party providers).

Implementing such a check in Chocolatey would provide a much lower barrier to entry for simple package validation rather than manually verifying the package prior to execution.
