### ISSUE TITLE
'choco install smplayer' ERROR: Cannot bind argument to parameter 'file' because it is an empty string.

### ISSUE THREAD

**Issue by KonomiKitten** [chocolatey/choco#1149]
### What You Are Seeing?
ERROR: Cannot bind argument to parameter 'file' because it is an empty string.

### What is Expected?
The package to install correctly.

### How Did You Get This To Happen? (Steps to Reproduce)
choco install smplayer

### Output Log
https://gist.github.com/KonomiKitten/b971ecf563dab7cca08f12baeaa5cf33

**Comment by AdmiringWorm** [comment]
@KonomiKitten this is package problem not a choco issue,
the package isn't getting the correct installer on a 32bit system.

**Comment by KonomiKitten** [comment]
@AdmiringWorm okay thanks feel free to close, I wasn't able to tell what the issue is and the package has a green light on the website.

**Comment by AdmiringWorm** [comment]
@KonomiKitten I don't have the power to close issues in this repo.

I think the automated tests only test the 64bit install of a package, which is why it have a green light.

**Comment by KonomiKitten** [comment]
@AdmiringWorm maybe they should be testing both?

**Comment by AdmiringWorm** [comment]
@KonomiKitten I agree, I've added it as an issue in the package verifier.

**Comment by KonomiKitten** [comment]
@AdmiringWorm thanks I just realised I can close this issue myself so doing so.

**Comment by majkinetor** [comment]
Will not push new package, will be fixed on next update.
