### ISSUE TITLE
Option/feature to stop installation when a dependency fails

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1151]
There should be an option to allow Chocolatey to stop the chain of installs if one of the items fails. It should be an opt-in option / feature as most folks would be using Chocolatey where dependencies are app to app (most of the time).

#### Reference
Originally we switched from doing this automatically way back in 0.9.8.25. However in [discussion](https://github.com/chocolatey/chocolatey/issues/192) @rismoney asked for a full stop if there was a failure in the chain - https://github.com/chocolatey/chocolatey/issues/192#issuecomment-27874678.

**Comment by rismoney** [comment]
booya!  fail early FTW!

**Comment by ferventcoder** [comment]
Completed for 0.10.4.
