### ISSUE TITLE
package parameters are unused when calling "install .\somepackage.nupkg"

### ISSUE THREAD

**Issue by teknowledgist** [chocolatey/choco#1155]
### What You Are Seeing?
package parameters work fine for packages called from the Chocolatey repository, but are "lost" when the same package is installed from a local path.  I've confirmed this with several packages on a clean, patched, Win7x64 with the latest (non-beta) Chocolatey release.

### What is Expected?
package parameters work the same regardless of the location of the .nupkg file.

### How Did You Get This To Happen? (Steps to Reproduce)
`choco install <packagepath&name>.nupkg -packageparameters '"/whatever"' -y`
The packages installs as if the -packageparameters was not used.   Both of the following strings appear in the log:
* Configuration: CommandName='install'| [...] PackageParameters='/whatever' |
* No Package Parameters Passed in

**Comment by gep13** [comment]
@teknowledgist what happens if you try:

```
choco install <name> --source <path> --packageparameters '"/whatever"' -y
```

**Comment by teknowledgist** [comment]
I've never called it that way, but it appears to work.

I still think there is an inconsistency though.  If `choco install <path-to-nupkg>` works the same as `choco install <packageName>`, then including the --packageparameters switch shouldn't make it behave differently in only one of the two contexts.  

I think it would be OK if `choco install <name> <path>` were the only way to install local packages (i.e. `choco install <path>` fails).

Thanks.

**Comment by ferventcoder** [comment]
I would recommend never using `.nupkg` anywhere in your install - it overrides source, it's possible that it overrides other components as well. There are a couple of known issues with it that we will be addressing.

**Comment by ferventcoder** [comment]
I am not sure if we will need the full log output, but it couldn't hurt.

**Comment by teknowledgist** [comment]
The only time I used a direct call to a .nupkg is when I am testing my own packages.  When I was learning, it was the first thing I tried and it worked, so I stuck with it.  I'm sure I tested the package parameters the same way in the past, but nevertheless, it ain't working now.  I will be sure to use the more complete syntax from now on.

If you want to see the log for one of the packages that exhibited the problem when I was testing the "wrong" way, [here ya go](https://gist.github.com/teknowledgist/67b94a0921168b33ed91acd77daba7c7)

Thanks.

**Comment by ferventcoder** [comment]
I wouldn't say the "wrong" way, more likely a way that works for simpler packages. The easiest way to test is `choco install pkgname -s .` and then any parameters (as long as the nupkg is in the current directory, and doesn't have dependencies that are not present). It's maybe less characters? 

Thanks for the log file. Will review to fix this.

**Comment by ferventcoder** [comment]
argh, close and comment are right next to each other.

**Comment by ferventcoder** [comment]
I think I found where this issue is occurring - Note this check: https://github.com/chocolatey/choco/blob/1c5e62bedf68b90f17e401df73d70efa40d8e92d/src/chocolatey/infrastructure.app/services/PowershellService.cs#L431

Now note that it compares package.id to the passed in name:

https://github.com/chocolatey/choco/blob/1c5e62bedf68b90f17e401df73d70efa40d8e92d/src/chocolatey/infrastructure.app/services/PowershellService.cs#L333-L341

That name being passed in is a full path to a nupkg or nuspec, triggering it to skip adding these parameters!

**Comment by ferventcoder** [comment]
I have a fix I'm working on here.

**Comment by dviry** [comment]
This still happens to me with 0.10.8. I was able to workaround this by specifying the "-s .\" option, but JFY it seems that this "bug" was not really solved (at least not on my end).

**Comment by ferventcoder** [comment]
@dviry if you are still seeing an issue, please file a new issue pointing to this and then provide a full debug / verbose log so we can review. Thanks!
