### ISSUE TITLE
Set Explicit Proxy Bypass List / Bypass On Local

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1165]
Similar to #605, #262, and #497 

Add a proxy bypass list to the configuration so that proxies are able
to be bypassed for some connections. Without this an explicit proxy
that is set will never bypass settings for downloads.

**Comment by ferventcoder** [comment]
Adding `choco config set proxyBypassList` for 0.10.4.

**Comment by mwallner** [comment]
Is it possible to temporary set a `proxyBypassList` ?
as example:
```
choco download somepkg -source="<internal server>" -proxyBypassList="<internal server>"
```

**Comment by ferventcoder** [comment]
@mwallner sounds cool. I think we should do that.

**Comment by ferventcoder** [comment]
@mwallner moved to #1165.

**Comment by ferventcoder** [comment]
Sorry, #1173
