### ISSUE TITLE
Prevent leading 0 in package version numbers

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/choco#1174]
### What You Are Seeing?
Currently it is possible to have packages containing leading zeros in version numbers (eg. [Totalcommander](https://chocolatey.org/packages/TotalCommander), see https://github.com/chocolatey/chocolatey-coreteampackages/issues/600).

### What is Expected?
While this works using current `choco` client and the chocolatey.org feed, it can break with other tools (eg. ProGet).
NuGet had a breaking change introduced in the 3.4 version of the client to prevent leading zeros. See [here](http://docs.nuget.org/Create/Versioning#Normalized_Version_Numbers). I therefore assume that the `choco` client would also have issues with these packages as soon as is updates to a never NuGet.Core version.

I therefore would suggest to start preventing the packaging of packages containing leading zeros in version numbers and prevent publishing them to chocolatey.org.

**Comment by jberezanski** [comment]
I agree in principle - I believe version numbers should be treated strictly as numbers, not strings, so leading zeros should be meaningless.
The choco client still needs to be able to handle existing packages with leading zeros, however.

**Comment by pascalberger** [comment]
I agree that `choco install`should be able to handle installation of existing packages with leading zeros, but `choco pack` should tread version numbers strictly as numbers.

**Comment by ferventcoder** [comment]
Version numbers are treated strictly as numbers, however handling on the source repository may look at the entire version number with the leading zeros.

**Comment by gep13** [comment]
@AdmiringWorm @TheCakeIsNaOH am I right in saying that this work has been completed?

**Comment by gep13** [comment]
After discussion with @AdmiringWorm we agree that this can be closed.
