### ISSUE TITLE
$env:OS_NAME is 'Windows' for Windows 10

### ISSUE THREAD

**Issue by pauby** [chocolatey/choco#1178]
### What You Are Seeing?

The environment variable OS_NAME is 'Windows' for Windows 10

### What is Expected?

$env:OS_NAME should be 'Windows 10' for Windows 10. Under Windows 7 it reports, correctly, Windows 7.

### How Did You Get This To Happen? (Steps to Reproduce)

Inside ChocolateyInstall.ps1 on a package I am testing I added this code:

`Write-Debug "OS: $($env:OS_NAME)"` 

### Output Log

https://gist.github.com/pauby/8fbf295ecd86d47b24cd554a6d5c08c0

**Comment by gep13** [comment]
Looks like this:

https://github.com/chocolatey/choco/blob/19cdf4b0da51fcb5e12d9b616971e605a3ff7c9a/src/chocolatey/infrastructure/platforms/Platform.cs#L101

Will need extended to include Windows 10.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/blob/19cdf4b0da51fcb5e12d9b616971e605a3ff7c9a/src/chocolatey/infrastructure/platforms/Platform.cs#L122 (has it) - wonder how the version is coming through.

**Comment by ferventcoder** [comment]
Oh... https://msdn.microsoft.com/en-us/library/windows/desktop/ms724832.aspx

**Comment by gep13** [comment]
>@ferventcoder said...
Oh..

Nothing like a bit of consistency :smile:
