### ISSUE TITLE
Installing mingw

### ISSUE THREAD

**Issue by AhmedHamadto** [chocolatey/choco#1179]
I am trying to install mingw to setup geth for ethereum but everytime I run the command line choco install mingw it says extracting for 45 mins and gets timed out, I even tried to manually extract and place the extraction in the C:\tools\ target folder but it still will not install.

**Comment by ferventcoder** [comment]
Hi @AhmedHamadto - note this is likely a package issue and that is not something that comes to this repository. Packaging issues should be filed directly with the maintainers of the package, which if this is a package on the community repository, you can follow up directly on the package page (left menu has "Contact Maintainers"). HTH
