### ISSUE TITLE
Question: installation of 0.9.9

### ISSUE THREAD

**Issue by keradus** [chocolatey/choco#118]
Hi!
Is it possible to install 0.9.9@dev version before it will be released?

**Comment by gep13** [comment]
@keradus have a look at this thread here:

https://groups.google.com/forum/#!topic/chocolatey/1iM61zmX7MA

Hope that helps.

For now, I am going to close this issue.  Either follow up with questions in that thread, or hit us up in our Gitter Chat Room.

**Comment by keradus** [comment]
Thank you @gep13 !
Great feedback!
