### ISSUE TITLE
Upgrade 7Zip to 16.04

### ISSUE THREAD

**Issue by trajano** [chocolatey/choco#1184]
### What You Are Seeing?
Error extracting files from https://mega.nz/MEGAcmdSetup.exe for the `uninst.exe` and `megacmdclient.exe files.

### What is Expected?
I should be able to use `Install-ChocolateyZipPackage` with no issues.

### How Did You Get This To Happen? (Steps to Reproduce)

````
$packageArgs = @{
    packageName   = $env:chocolateyPackageName
    unzipLocation = $env:chocolateyPackageFolder
    url = 'https://mega.nz/MEGAcmdSetup.exe'
    checksum      = '350320ca4a9d2e4ee8be4e6d9f262be91d70e03344baaa1cf5d71dde662a12453262604ee44a0d5e9d29c347f9752424e68c1c4419b2969f9a7294ffea02e5c0'
    checksumType  = 'sha512'
}
Install-ChocolateyZipPackage @packageArgs
````

### Output Log
~~~sh
ERROR: Data Error : MEGAclient.exe
ERROR: Data Error : uninst.exe
~~~

To fix I think you just need to update the 7Zip to 16.04
https://github.com/chocolatey/choco/tree/master/src/chocolatey.resources/tools

For now my workaround is to install `7zip.portable` first then use it to extract as per https://github.com/trajano/choco-packages/blob/master/megacmd/tools/chocolateyinstall.ps1

**Comment by ferventcoder** [comment]
@trajano you making a portable and an installer version of this? I ran Package Builder on this and it generated it as an NSIS

**Comment by ferventcoder** [comment]
![image](https://cloud.githubusercontent.com/assets/63502/24068945/4fb8c5b6-0b69-11e7-8f4f-00243ed420f0.png)

**Comment by ferventcoder** [comment]
![image](https://cloud.githubusercontent.com/assets/63502/24068947/5e4de61a-0b69-11e7-8bb6-b523aefda4aa.png)

**Comment by ferventcoder** [comment]
And by Package Builder, I literally mean `choco new --url https://mega.nz/MEGAcmdSetup.exe --build-package` and within seconds I had a package.

![image](https://cloud.githubusercontent.com/assets/63502/24068977/314fbfd4-0b6a-11e7-931b-83ed8545ed85.png)

**Comment by ferventcoder** [comment]
Ah uninstaller is not completely silent. Fun...

**Comment by ferventcoder** [comment]
Verified failure. Verified fix with latest 7z. This will be released in 0.10.4. Thanks for logging the issue!

**Comment by trajano** [comment]
What's the ETA for 0.10.4?  I'll make the change to the package later.

**Comment by ferventcoder** [comment]
@trajano to save on retyping, take a look at https://github.com/chocolatey/choco/pull/1023#issuecomment-287551113
HTH
