### ISSUE TITLE
choco pack accepts pre-release tags in versions but not choco install

### ISSUE THREAD

**Issue by riedel** [chocolatey/choco#1186]
If I create a package with `<version>1.0-rc3</version>`.
choco pack will succeed but choco install will fail to find the package.

I would expect choco pack to fail with `'1.0-rc3' is not a valid version string.`

Instead I get `The package was not found with the source(s) listed.` upon install.

BTW: I failed to find clear guidelines for chocolatey versions and how they potentially differ from nugets definition (nuget allows socalled pre-release tags)

**Comment by riedel** [comment]
I guess my issue is highly related to #1158 (only that this issue is about the inconsistency in the commands)

**Comment by gep13** [comment]
Can you confirm the installation command you are using?  You will need to include the `--pre` flag, as this will be regarded as a prerelease package.

**Comment by riedel** [comment]
thanks so much! I am so stupid: https://github.com/chocolatey/choco/wiki/CreatePackages even mentions this. 

This did the job! (I actually tried this at one time but then I already had a fixed version installed) Please close this issue.

**Comment by ferventcoder** [comment]
It's all a learning process - the `--pre` bit trips even us up sometimes.
