### ISSUE TITLE
Add File64 to Install-ChocolateyInstallPackage and Get-ChocolateyUnzip

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1187]
To match parity with https://github.com/chocolatey/chocolatey-coreteampackages/pull/612

**Comment by AdmiringWorm** [comment]
I'm thinking this could perhaps also be extended with the same File64 parameter for `Get-ChocolateyUnzip`?

**Comment by ferventcoder** [comment]
Probably a good idea.

**Comment by ferventcoder** [comment]
This will be in 0.10.4
