### ISSUE TITLE
Self mantaining/updating packages

### ISSUE THREAD

**Issue by metinkale38** [chocolatey/choco#1189]
Hey,

to improve update speed of choco and prevent outdated/not updated packages, i have the following idea:

self updating packages: 
instead of only providing installation scripts, url to a specific version etc.. we could add a script, which fetches the project homepage for the latest version, latest executable, changelogs etc.. 
Since websites of most applications do not change often, the mantainer would only to correct the update script rarely and we would always have up to date packages for most applications.

i got the idea from F-Droid, it is itself checking a git repository by given parameters, to get the latest source code. Sure it is not a git repository, but i think, it should be still possible.

**Comment by gep13** [comment]
@metinkale38 if I have understood you correctly, this is essentially what we refer to as automatic packages:

https://chocolatey.org/docs/automatic-packages

Currently there are two options, either ketarin or AU.

For example, almost all the packages in the core team packages repo (https://github.com/chocolatey/chocolatey-coreteampackages) use one of these mechanisms to keep the packages that are maintained there always up to date.

**Comment by metinkale38** [comment]
ok, thank you...
after checking how to create a package i thought, this would not be possible...

**Comment by gep13** [comment]
Going forward, I think the recommendation would be to use AU, as it doesn't require templating of variables, which is required with ketarin.
