### ISSUE TITLE
Save torrent of selected item

### ISSUE THREAD

**Issue by superbonaci** [chocolatey/choco#1199]
I would like an option to save the current torrent of the selected download (if the download was started from magnet check for if torrent is already downloaded).

**Comment by ferventcoder** [comment]
Not following.

**Comment by superbonaci** [comment]
Copy the magnet link of a download to the clipboard or save the torrent to the desktop.

**Comment by gep13** [comment]
>@superbonaci said...
Copy the magnet link of a download to the clipboard or save the torrent to the desktop.

I am not sure if that helps with the question that @ferventcoder was asking.  What does this issue have to do with chocolatey?  Chocolatey doesn't use torrents?

**Comment by ferventcoder** [comment]
I think I might understand. Have something that copies the download link?

**Comment by ferventcoder** [comment]
If that is what you are looking for, please file a request over at https://github.com/chocolatey/chocolatey.org/issues/new. Thanks!

**Comment by superbonaci** [comment]
Sorry posted in wrong project.
