### ISSUE TITLE
ChocolateyPackageFolder environment variable points to incorrect folder

### ISSUE THREAD

**Issue by jberezanski** [chocolatey/choco#120]
In Powershell Choco, the ```chocolateyPackageFolder``` environment variable would point to the directory the package was extracted to, e.g. ```C:\ProgramData\chocolatey\lib\package.1.2.3``` (relevant source lines: [Run-ChocolateyPS1.ps1#L28](https://github.com/chocolatey/chocolatey/blob/2d61a3b0958170ade13d8ad5a09a88af9e46bb65/src/functions/Run-ChocolateyPS1.ps1#L28) and [Chocolatey-NuGet.ps1#L64](https://github.com/chocolatey/chocolatey/blob/2d61a3b0958170ade13d8ad5a09a88af9e46bb65/src/functions/Chocolatey-NuGet.ps1#L64)).

In C# Choco, this variable is set to the path of the lib directory, e.g. ```C:\ProgramData\chocolatey\lib``` ([PowershellService.cs#L161](https://github.com/chocolatey/choco/blob/4b0478fdef378227a6814ffdb164df7942b122e0/src/chocolatey/infrastructure.app/services/PowershellService.cs#L161)).

Is this change intentional? It has the potential of breaking at least a few packages. (It certainly broke one of mine...)

**Comment by ferventcoder** [comment]
Not intentional - I was looking for that, but I think I missed it when I set that variable.

**Comment by ferventcoder** [comment]
This variable was set for the chocolatey functions though. Not necessarily for the packages themselves.

**Comment by jberezanski** [comment]
I believe the variables available to chocolateyInstall.ps1 were never officially documented, were they? However, people had mentioned them on the mailing list and were not explicitly told not to use them, so I guess they need to be treated as public API after all...

By the way, have you given any thought to migrating from environment to real Powershell variables? The ability to pass proper .NET objects to the scripts could be a real killer - not just by avoiding string manipulation and parsing, but also enabling passing structured, typed data (trivial example: package version as System.Version), receiving feedback (e.g. restart requirement - something the packages currently do not even bother reporting to the console) and exposing services/functionality via an object model. Naturally, it will only be possible after #8 is done.

**Comment by ferventcoder** [comment]
> However, people had mentioned them on the mailing list and were not explicitly told not to use them, so I guess they need to be treated as public API after all...

It really depends on who told you about them really. There are a lot of incorrect usages of tools based on mailing lists (not just choco), it doesn't make those things part of a public API. ;)

**Comment by ferventcoder** [comment]
> By the way, have you given any thought to migrating from environment to real Powershell variables? 

Yes.
