### ISSUE TITLE
Uninstallation does not delete files extracted to package directory by chocolateyInstall.ps1

### ISSUE THREAD

**Issue by jberezanski** [chocolatey/choco#121]
When a package is uninstalled, only files contained in the nupkg are removed from the package directory. If the package install script put extra files there (e.g. using the common pattern for zip packages - extract the downloaded zip to package directory), those files are left behind when the package is uninstalled and the package directory is not deleted.

In PS Choco, the package directory was unconditionally deleted.

Is the change intentional? If yes, will the auto uninstaller service eventually handle removing such files or will package maintainers have to explicitly code it in chocolateyUninstall.ps1?

**Comment by ferventcoder** [comment]
choco clean will handle additional cleanup.

**Comment by ferventcoder** [comment]
And there is `choco uninstall --force`

**Comment by ferventcoder** [comment]
If you want, we can call this a documentation issue?

**Comment by dhilgarth** [comment]
Would you encourage adding a uninstall script that removes those files via Uninstall-ChocolateyZipPackage? Or would you discourage it? Or don't you have a preference? Looking for best practices here.

**Comment by ferventcoder** [comment]
I think I misunderstood this issue when I first read it. I think we'll want to automatically look for those unzipped files (based on that file that is created) and remove them as part of uninstall.
And any downloaded files.

**Comment by dhilgarth** [comment]
Great, I totally agree! So, the manual call to Uninstall-ChocolateyZipPackage would be unnecessary?

**Comment by ferventcoder** [comment]
Yes

On Thursday, February 26, 2015, Daniel Hilgarth <notifications@github.com>
wrote:

> Great, I totally agree! So, the manual call to
> Uninstall-ChocolateyZipPackage would be unnecessary?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/121#issuecomment-76267351>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by rismoney** [comment]
love it.

**Comment by jberezanski** [comment]
Great! I was concerned about the increased workload for maintainers of zip-based packages and the need to modify all such existing packages to retain current uninstall behavior. Besides, it seemed contrary to the goal of eliminating the need for chocolateyUninstall.ps1 in common cases.

**Comment by ferventcoder** [comment]
@jberezanski Yeah sorry I misunderstood what you were talking about before...

**Comment by bc3tech** [comment]
I have a pull request prepped that improves `Uninstall-ChocolateyZipPackage` to work more robustly. I found in the case of one package that uses ZIP install, the call to `Uninstall-ChocolateyZipPackage` would hang on specifiers in the .zip.txt file that were directory names and not files. My improvement solves this and successfully deletes all files denoted in the .zip.txt file contained in the package's `lib` directory.

@ferventcoder: You want I should submit the pull request?

**Comment by ferventcoder** [comment]
@bc3tech Yeah we can improve uninstall-chocolateyzippackage for now.

**Comment by bc3tech** [comment]
@ferventcoder pull request submitted. Thanks! hopefully it's not too crazy.

**Comment by AnthonyMastrean** [comment]
To be clear, the `Uninstall-ChocolateyZipPackage` helper doesn't work _at all_, as-is. It hangs waiting for confirmation (I recreated [the relevant chunk](https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/UnInstall-ChocolateyZipPackage.ps1#L53) in my shell)...

```powershell
PS> $zipContentFile = 'C:\ProgramData\chocolatey\lib\tinycc\tinyccInstall.zip.txt'
PS> $zipContents=get-content $zipContentFile
>>> foreach ($fileInZip in $zipContents) {
>>>   remove-item "$fileInZip" -ErrorAction SilentlyContinue
>>> }

Confirm
The item at C:\ProgramData\chocolatey\lib\tinycc\tools\tcc has children and the Recurse parameter was not
specified. If you continue, all children will be removed with the item. Are you sure you want to continue?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
```

You need, at least, the `-Force` and `-Recurse` flags to ignore all prompts.

Then you should consider that the zip contents text file starts with the top-most directory.

```
C:\ProgramData\chocolatey\lib\tinycc\tools\tcc
C:\ProgramData\chocolatey\lib\tinycc\tools\tcc\libtcc
C:\ProgramData\chocolatey\lib\tinycc\tools\tcc\libtcc.dll
C:\ProgramData\chocolatey\lib\tinycc\tools\tcc\tcc.exe
C:\ProgramData\chocolatey\lib\tinycc\tools\tcc\tiny_impdef.exe
C:\ProgramData\chocolatey\lib\tinycc\tools\tcc\tiny_libmaker.exe
```

The `Remove-Item` loop will recursively delete the top-level folder, and fail to delete all the children. For example, without the Error Action specified...

```
Remove-Item : Cannot find path 'C:\ProgramData\chocolatey\lib\tinycc\tools\tcc\libtcc.dll' because it does not exist.
At line:1 char:65
+ Get-Content C:\ProgramData\chocolatey\lib\tinycc\tinyccInstall.zip.txt | Remove-Item -For ...
+                                                                 ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\ProgramData\...libtcc\libtcc.dll:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
```

The `-ErrorAction SilentlyContinue` parameter will suppress that error. Or, you could add a `Test-Path` into the pipeline. I'd rewrite that whole loop in one of two ways

```powershell
Get-Content $zipContentFile | ?{ Test-Path $_ } | Remove-Item -Force -Recurse
```

Or you might still want to silently continue past all other possible errors (which are?)

```powershell
Get-Content $zipContentFile | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
```

In either case, what is the recommendation for package authors until this bug is fixed? Do we allow the zip files and, for packages that unzip into the install directory, the sparsely deleted package directory to stick around?

**Comment by ferventcoder** [comment]
So the fixes from @bc3tech went into 0.9.9.5. So there is that path forward for now.

**Comment by ferventcoder** [comment]
This remains open as the ultimate fix here is to capture what is in the folder and clean it up if it hasn't changed.

**Comment by AnthonyMastrean** [comment]
Awesome :)

In the past, I leaned heavily on Chocolatey removing the entire install directory, especially for locally extracted zip packages.

**Comment by ferventcoder** [comment]
This is fixed in https://github.com/chocolatey/choco/commit/3bb842145c94a0c7df2b1d426fd60819efb708e3
