### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by Zedonboy** [chocolatey/choco#1217]
### What You Are Seeing?
```
By installing you accept licenses for the packages.
chocolately not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but t
he version does not.
 Version: "0.10.3"
 Source(s): "https://chocolatey.org/api/v2/"

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - chocolately - chocolately not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but t
he version does not.
 Version: "0.10.3"
 Source(s): "https://chocolatey.org/api/v2/"
```

### What is Expected?
Of course to install this frustrating piece of shit, chocolately

### How Did You Get This To Happen? (Steps to Reproduce)
I have tried adding proxies like chocolateproxy.eu

### Output Log

GIST LINK - Please create a gist and link to that gist here

OR

~~~sh
PLACE LOG CONTENT HERE
~~~

**Comment by ferventcoder** [comment]
Apologies, your comments violate etiquette rules. If you are frustrated with something, please provide some context. However currently this statement is not acceptable.

**Comment by Zedonboy** [comment]
@ferventcoder am sorry bro......my apologies i just had relationship issues yesterday, everything is resolved now............... general apologies everyone for the kind of comments i made
