### ISSUE TITLE
Extra '|' in choco sources -r in 0.10.4

### ISSUE THREAD

**Issue by marcinbojko** [chocolatey/choco#1218]
### What You Are Seeing?
$ choco sources list -r
chocolatey|https://chocolatey.org/api/v2/|False|||0|False|False
scalepoint|https://www.myget.org/F/public-choco|False|||10|False|False
sp2|https://www.myget.org/F/scalepoint|False|||10|False|False

### What is Expected?
$ choco sources list -r
chocolatey|https://chocolatey.org/api/v2/|False|0|False|False
scalepoint|https://www.myget.org/F/public-choco|False|10|False|False
sp2|https://www.myget.org/F/scalepoint|False|10|False|False

### How Did You Get This To Happen? (Steps to Reproduce)
choco sources list -r

### Output Log

$ choco sources list -r --debug
Chocolatey is running on Windows v 6.2.9200.0
Command line: "C:\ProgramData\chocolatey\choco.exe" sources list -r --debug
Received arguments: sources list -r --debug
The source '' evaluated to a 'normal' source type

NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
Configuration: CommandName='sources'|
CacheLocation='C:\Users\mbo\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
SourceType='normal'|Debug='True'|Verbose='False'|Trace='False'|
Force='False'|Noop='False'|HelpRequested='False'|
UnsuccessfulParsing='False'|RegularOutput='False'|QuietOutput='False'|
PromptForConfirmation='False'|AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='list'|AllVersions='False'|
SkipPackageInstallProvider='False'|Prerelease='False'|ForceX86='False'|
OverrideArguments='False'|NotSilent='False'|
ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='6.2.9200.0'|
Information.PlatformName='Windows Server 2012'|
Information.ChocolateyVersion='0.10.4.0'|
Information.ChocolateyProductVersion='0.10.4'|
Information.FullName='choco, Version=0.10.4.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.IsUserAdministrator='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='True'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IncludeRegistryPrograms='False'|ListCommand.PageSize='25'|
ListCommand.Exact='False'|ListCommand.ByIdOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='list'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
FeatureCommand.Command='unknown'|
ConfigCommand.Command='unknown'|PinCommand.Command='unknown'|
Proxy.BypassOnLocal='True'|
_ Chocolatey:ChocolateySourceCommand - Normal Run Mode _
chocolatey|https://chocolatey.org/api/v2/|False|||0|False|False
scalepoint|https://www.myget.org/F/public-choco|False|||10|False|False
sp2|https://www.myget.org/F/scalepoint|False|||10|False|False
Exiting with 0

**Comment by ferventcoder** [comment]
Yes there is.

**Comment by ferventcoder** [comment]
Thanks for reporting this. Will have a quick turnaround on 0.10.5 due to another high priority issue.

**Comment by marcinbojko** [comment]
Thank you @ferventcoder you gave me a push to rework my pipe filtering ;)

**Comment by ferventcoder** [comment]
We probably need a key. 

It's the following values:

this.Log().Info(() => "{0}|{1}|{2}|{3}|{4}|{5}|{6}|{7}".format_with(
                        source.Id,
                        source.Value,
                        source.Disabled.to_string(),
                        source.UserName,
                        source.Certificate,
                        source.Priority,
                        source.BypassProxy.to_string(),
                        source.AllowSelfService.to_string()));


Username and Certificate account for the empty pipes.

**Comment by ferventcoder** [comment]
This should be documented somewhere though.

**Comment by trolzen** [comment]
What if we convert the output to the following format? Note `<none>` instead of empty string.
```sh
$ choco sources list -r
chocolatey|https://chocolatey.org/api/v2/|False|<none>|<none>|0|False|False
scalepoint|https://www.myget.org/F/public-choco|False|<none>|<none>|10|False|False
sp2|https://www.myget.org/F/scalepoint|False|<none>|<none>|10|False|False
```

**Comment by corbob** [comment]
> What if we convert the output to the following format? Note `<none>` instead of empty string.

Unfortunately this would likely be a breaking change since we're discussing the output that's expected to be used by scripts, and changing it from outputting nothing to outputting a string representation of nothing is likely to break scripts that explicitly look for it to be an empty string.
