### ISSUE TITLE
Remove deprecated functions in PowerShell 

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#122]
- [x] Write-ChocolateyFailure needs removed as it is no longer throwing errors. 
- [x] Write-ChocolateyFailure should still throw an error for compatibility reasons.

**Comment by rismoney** [comment]
what should be done for packages that use it (most of our zipped .net apps) use it.
A common theme in packages is

this is our most common package structure:

```powershell
try {
$packageName='myapp'

$url = 'http://chocopackages.example.com/apps/myapp.zip'
$zpwd = 'D:\chocopkg\myapp\'
  
#------------ UNZIP myapp in D drive-------------#
Install-ChocolateyZipPackage $packageName $url $zpwd

Write-ChocolateySuccess $packageName
} catch {
  Write-ChocolateyFailure $packageName $($_.Exception.Message)
  throw
}
```

**Comment by gep13** [comment]
@rismoney have a look at the guidance here:

https://github.com/chocolatey/choco/wiki/HelpersReference.

i.e. it will be very similar, to what you already have, in terms of structure.

**Comment by rismoney** [comment]
thanks for quick reply!  I realize i can get this down to 1 line since it is an installchocolateyzippackage, (contrived example).   but if iiuic, can i simply remove the write-chocolatey* functions, since this will be handled by choco internally.(in real cases where i have the try/catch/throw

**Comment by gep13** [comment]
@rismoney yes, that is my understanding.

**Comment by ferventcoder** [comment]
@rismoney you can actually drop the try catch throw entirely now unless you want to do any error handling in the package.
