### ISSUE TITLE
feature request: test for presence of 7za.exe prior to download

### ISSUE THREAD

**Issue by kewalaka** [chocolatey/choco#1228]
Would it be possible to add a 'Test-Path' statement to see if 7za.exe already exists in the temp folder, and if so skip the download?

This is helpful in scenarios where there is no internet, but we can use something like chef/DSC to ensure the file is present prior to chocolatey being installed.

At present I work around this by using windows compression, using a chunk of DSC like this:

        Environment chocolateyDownloadUrl
        {
            Name  = "chocolateyDownloadUrl"
            Value = "https://chocolatey.myaddress.co.nz/install.ps1"
        }
        
        Environment chocolateyUseWindowsCompression
        {
            Name  = "chocolateyUseWindowsCompression"
            Value = "true"
        }
        
        cChocoInstaller installChoco
        {
            InstallDir             = "$env:PROGRAMDATA\chocolatey"
            ChocoInstallScriptUrl  = "https://chocolatey.myaddress.co.nz/install.ps1"
            DependsOn = @(  "[Environment]chocolateyDownloadUrl",
                            "[Environment]chocolateyUseWindowsCompression" )
        } 

Obviously, that doesn't work on Nano.

**Comment by ferventcoder** [comment]
Chocolatey doesn't work on Nano yet. Targeting second half of 2017.

**Comment by ferventcoder** [comment]
Puppet already supports full no internet scenarios. If Chef and DSC don't support this yet, they need to add that on their own. Also the bootstrapper you are referring to that uses 7za is not in this codebase, it's in https://github.com/chocolatey/chocolatey.org. It also already has built-in to it what you are asking - see https://chocolatey.org/install.ps1

**Comment by ferventcoder** [comment]
Ah - I see you already noticed setting that environment variable.

**Comment by ferventcoder** [comment]
Please file an issue at https://github.com/chocolatey/chocolatey.org about 7za.

**Comment by ferventcoder** [comment]
I do feel strongly that the infrastructure mgmt tools should have a switch - as I mentioned the Puppet provider already has this. 

Either way, with 7za check or setting the env var, I feel it is a workaround versus ensuring the infra mgmt tools ensure complete offline support. I did think the Chef cookbook had this in it already.

**Comment by ferventcoder** [comment]
Closing here as this is needs to get logged over in the website repo.
