### ISSUE TITLE
FEATURE REQUEST: User accounts on chocolatey.org with default programs

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/choco#1229]
Chocolatey is great. Everyone who uses it would agree.
Chocolatey is for power users and not really amateur friendly. (I don't have access to the demographics but I'm sure all would agree.)

WHAT IF The chocolatey.org website had end user accounts where the end users could  add to their profile a list of default programs that would install automatically when Chocolatey is installed? IMAGINE what that would do to the user experience if implemented! Imagine how it would simplify new computer installs.

I'm going to walk through the scenario;

- I'm about to be a new user of Chocolatey, I create an account on chocolatey.org.
- I type in a few programs that I want on every machine that I ever install Chocolatey on. This list could be entered into the user profile database and displayed like tags. My list would partially include: googlechrome, adblockpluschrome, advanced-codecs, audioshell, autoruns, cmdaliases, dropbox, firefox, etc.
- I then run one of the various methods of installing Chocolatey but with the added switch of /user:bcurran3.
- Choco then installs itself and then kicks off installations of googlechrome, adblockpluschrome, advanced-codecs, audioshell, autoruns, cmdaliases, dropbox, firefox, etc. after looking up my bcurran3 account and my list of desired default programs to install.

Think about it. Wouldn't that be amazing! PLEASE! PLEASE! PLEASE! PLEASE put it on the roadmap!

**Comment by bcurran3** [comment]
There is a Chocolatey software agent on the road map right?

**Comment by ferventcoder** [comment]
> There is a Chocolatey software agent on the roadmap right?

It already exists for business users. That's where a feature like that would make sense. ;)

**Comment by ferventcoder** [comment]
This should go to https://github.com/chocolatey/chocolatey.org/issues.

**Comment by bcurran3** [comment]
So a year and a half later I finally posted this to the right spot: https://github.com/chocolatey/chocolatey.org/issues/608

Implementation would require enhancement to the chocolatey.org website as well as the choco.exe client, so the issue here is relevant as well.
