### ISSUE TITLE
Inconsistent docs for the parameter "-WorkingDirectory" in Install-ChocolateyShortcut

### ISSUE THREAD

**Issue by OlafHaag** [chocolatey/choco#1234]
### What You Are Seeing?
Inconsistent use for the parameter "-WorkingDirectory" in _Install-ChocolateyShortcut_ helper function documentation. In Example 2 it's "-WorkDirectory", in the chocolateyInstall.ps1 that comes with choco new <packagename> it's "-workDirectory".

### What is Expected?
That it's always called "-WorkingDirectory" in order to not confuse me and make errors.
### How Did You Get This To Happen? (Steps to Reproduce)
choco new, and looking at the docs: https://chocolatey.org/docs/helpers-install-chocolatey-shortcut, looking at the source code

**Comment by ferventcoder** [comment]
Documentation bug. Up for grabs.

**Comment by gep13** [comment]
This was merged into stable at https://github.com/chocolatey/choco/commit/26ace8054b2ba50cd3a4dabe086edfa62b79af26

**Comment by gep13** [comment]
Merged into stable to be released with 0.10.12.
