### ISSUE TITLE
Can't install chocolatey on Windows 10 Creators Update with Avira

### ISSUE THREAD

**Issue by dafuki** [chocolatey/choco#1236]
Avira detects choco.exe as TR/AD.PSLoader.xjubs and the set up fails.
Sorry didn't see that it was already opened an hour ago here https://github.com/chocolatey/choco/issues/1235

P.S,
Even after disabling the AV it didn't install, probably issues with the creator update (has many bugs). I'll try to update with the details later.

**Comment by ferventcoder** [comment]
Closing as a duplicate. Will continue conversation at #1235
