### ISSUE TITLE
Add command to list packages only by name

### ISSUE THREAD

**Issue by nvivo** [chocolatey/choco#1237]
This is related to a question on [stackoverflow](http://stackoverflow.com/questions/43167087/how-to-get-a-list-of-packages-from-one-machine-and-install-in-another-with-choco), there should be a simple way to list the packages without package versions.

Analogous to a `dir /b`, there should be a `clist -b` or something that simply lists package names, one per line without versions. This makes things much simpler to automate than dealing with xml files or powershell.

Even if there is a simple way to generate xml files, it's still useful to allow a simple list of packages we can `xargs` into a new command line.

**Comment by ferventcoder** [comment]
Sounds good. I'd assume it won't be `-b`, but maybe something like `--by-name-only`

**Comment by ferventcoder** [comment]
Note that I've opened this for "Up For Grabs" (open for contributions). As there are currently ways to do this, it's also been marked as low priority. However the functionality would be pretty simple to add.

**Comment by torhovland** [comment]
I've submitted a PR for this: https://github.com/chocolatey/choco/pull/1254

**Comment by ferventcoder** [comment]
Going into 0.10.6
