### ISSUE TITLE
log who installed packages (support)

### ISSUE THREAD

**Issue by lukemgriffith** [chocolatey/choco#1238]
- Track what user has installed a self-service package  (Or if a package was installed via self-service)  (This would be great for metrics)

**Comment by ferventcoder** [comment]
Howdy Luke - best to do one request per issue. Let's keep this as the "who"

**Comment by ferventcoder** [comment]
The Chocolatey FOSS side of this is complete.

**Comment by ferventcoder** [comment]
Please follow https://github.com/chocolatey/chocolatey-licensed-issues/issues/1 to learn more about the business side.
