### ISSUE TITLE
avira detect some trojan in choco.exe

### ISSUE THREAD

**Issue by dennyhalim** [chocolatey/choco#1242]
after happily using choco for few weeks, suddenly today avira remove almost everything in c:\programdata\chocolatey including everything in bin folder

then the folder is set as write protected and cannot reinstall choco, cant even mkdir inside c:\programdata\chocolatey

**Comment by ferventcoder** [comment]
Duplicate of #1235. You should contact Avira. It's a false positive.

**Comment by ferventcoder** [comment]
In #1235 I linked, it has more details. Please read and comment there. HTH
