### ISSUE TITLE
Update ShimGen to 0.8.x to address some issues

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1243]
ShimGen needs to use app.manifest to work better with UAC and the shims that are created do as well. It also needs a few additional settings added to optimize the generated files a bit better.

**Comment by vignesh-paramasivam** [comment]
Hi I'm getting the following issue on ShimGen while installing nssm package. The same is working when tried with ShimGen 0.7, can you please advice?

```
PS C:\Users\Administrator> C:\ProgramData\chocolatey\tools\shimgen.exe --path="..\\lib\NSSM\Tools\nssm-2.24\win64\nssm.e
xe" --output="C:\ProgramData\chocolatey\bin\nssm.exe"  --iconpath="C:\ProgramData\chocolatey\lib\NSSM\Tools\nssm-2.24\wi
n64\nssm.exe"
Microsoft (R) Visual C# 2010 Compiler version 4.0.30319.1
Copyright (C) Microsoft Corporation. All rights reserved.

fatal error CS2007: Unrecognized option: '/errorendlocation'


[ERROR] ShimGen had an issue creating 'C:\ProgramData\chocolatey\bin\nssm.exe'. Please check the logs above.
```

**Comment by ferventcoder** [comment]
I wonder if we introduced something in .NET 4.5+? Can you provide a full debug/verbose log please? Thanks!

**Comment by ferventcoder** [comment]
No need for that log - I think we are good to go - please follow https://github.com/chocolatey/choco/issues/1321
