### ISSUE TITLE
chocolatey Install failing

### ISSUE THREAD

**Issue by ddjbollman** [chocolatey/choco#1246]
Vagrant 1.9.2
Chef Development Kit Version: 1.2.22
chef-client version: 12.18.31
kitchen version: 1.15.0
PowerShell 5.1.14393.953 (Microsoft Windows NT 10.0.14393.0)

TEMPLATE FOR BUG REPORTS:
-->

### What You Are Seeing?
       Converging 14 resources
       Recipe: chocolatey::default
         * cookbook_file[C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/chocolatey-install.ps1] action create (up to date)
         * powershell_script[Install Chocolatey] action run

           ================================================================================
           Error executing action `run` on resource 'powershell_script[Install Chocolatey]'
           ================================================================================

           ArgumentError
           -------------
           wrong number of arguments (given 0, expected 1)

           Resource Declaration:
           ---------------------
           # In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/recipes/default.rb

            35: powershell_script 'Install Chocolatey' do
            36:   environment node['chocolatey']['install_vars']
            37:   cwd Chef::Config['file_cache_path']
            38:   code install_ps1
            39:   not_if { chocolatey_installed? && (node['chocolatey']['upgrade'] == false) }
            40: end

### How Did You Get This To Happen? (Steps to Reproduce)
kitchen converge
Cookbook has previously ran successful multiple times with chocolatey (~> 1.1.0)

### Output Log

GIST LINK - Please create a gist and link to that gist here
https://gist.github.com/ddjbollman/9e0974d634750af589f096ee0b01153e
[chef-stacktrace.txt](https://github.com/chocolatey/choco/files/911461/chef-stacktrace.txt)

### Kitchen yml
---
driver:
  name: vagrant

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  
verifier:
  name: inspec

platforms:
  - name: windows-2012r2
    driver_config:
      box: bollman/2012r2

suites:
  - name: default
    run_list:
      - recipe[dd-windows::base]
      - recipe[dd-windows::POSH]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:

**Comment by ddjbollman** [comment]
Update
Added require_chef_omnibus: "12"
into .kitchen.yml

Kitchen is converging as expected now.

**Comment by tiagolo** [comment]
I have the same issue here, running chef on my local machine.

Chef Development Kit Version: 1.3.40
chef-client version: 13.0.118
berks version: 5.6.4
kitchen version: 1.16.0

I'm running it with 
```
chef-client --local-mode --override-runlist 'development_workstation'
```

**Comment by ferventcoder** [comment]
Running this for internal organizational usage? I'm assuming you are using your own internally hosted Chocolatey nupkg and something is wrong with the install script it is running?

**Comment by ferventcoder** [comment]
Actually, I saw this on the community chat the other day - there may be fixes at https://github.com/chocolatey/chocolatey-cookbook/pull/116

**Comment by ferventcoder** [comment]
This looks more like an issue with the chef cookbook though. Correct me if I am wrong here - that repo is over at https://github.com/chocolatey/chocolatey-cookbook. I think you want to file this over there. HTH
