### ISSUE TITLE
chocolatey.lib nuget package has incorrect documentation xml

### ISSUE THREAD

**Issue by sxmanton** [chocolatey/choco#1247]
### What You Are Seeing?
In chocolatey.lib.0.10.5 nuget package (published 3/30/2017):

The documentation xml that was downloaded with the nuget package appears to contain xml documentation for the dependencies and not the chocolatey library itself. It's around 3MB (compared to 172KB when I build the xml from source) and chock full of documentation for the Alphaleonis.Win32.Filesystem namespace as well as some others, but nothing from the chocolatey namespace.

**Comment by ferventcoder** [comment]
Thanks for noting this. Fixing for 0.10.6.
