### ISSUE TITLE
Choco info should provide summary

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/choco#1253]
Choco info should have this so we can quickly show only summery of files available on the system. First line of description is rarely equal to summary line.

```
choco list -l --detail | % { ($_ -split "`n") -match '^\s*Summary'}
```
Currently, the one has to resort to something like this which is not the same:

```
choco list -l --detail | % { ($_ -split "`n") -match '^\s*Description'} | % { $_ -replace '^\s*Description:\s*' } | select -unique 
```

**Comment by ferventcoder** [comment]
Please create another issue against the Chocolatey gallery. It should also link to that maintainers are not also included in the information that comes out either.

**Comment by ferventcoder** [comment]
Related to #1263

**Comment by ferventcoder** [comment]
No need for a second issue against the gallery. The information is already available.

**Comment by ferventcoder** [comment]
This will be in 0.10.6
