### ISSUE TITLE
can show the download progress?

### ISSUE THREAD

**Issue by cjahv** [chocolatey/choco#1255]
![image](https://cloud.githubusercontent.com/assets/15372793/25112155/ee05403e-2421-11e7-8efa-8b065a46e3cc.png)
I waited for a year!

**Comment by ferventcoder** [comment]
That's a package issue - Chocolatey shows download progress if the package uses Chocolatey's built-in methods. You can see that in other packages and here https://github.com/chocolatey/choco#see-chocolatey-in-action

**Comment by ferventcoder** [comment]
And it's been back for over a year now. See https://github.com/chocolatey/choco/issues/56
