### ISSUE TITLE
Stop saying "0 packages failed."

### ISSUE THREAD

**Issue by stibinator** [chocolatey/choco#1259]
When an install is successful it would be better if the report didn't say "0 packages failed" If you're spooling through the terminal history looking for failures this unnecessarily catches your eye.

"0 packages failed does not add any new information to the "choloatey installed 3/3 packages" message that precedes it.

It would be better if it only mentioned failure when the number of packages that failed > 0.  And maybe even consider changing "Chocolatey installed _x_/_y_ packages" to "Chocolatey installed _all_ packages" when x==y

**Comment by ferventcoder** [comment]
I like it. Going to open this to up for grabs.

**Comment by ferventcoder** [comment]
> And maybe even consider changing "Chocolatey installed x/y packages" to "Chocolatey installed all packages" when x==y

This I doubt we'd change at this time though.

**Comment by jaensch11** [comment]
I would like to take this on. I am new to working on FOSS projects, but as a third year University Student I do have programming experience and some experience with c#.

**Comment by ferventcoder** [comment]
@jaensch11 sure thing. It's open for folks currently.

**Comment by stibinator** [comment]
Awesome work!
