### ISSUE TITLE
Install-ChocolateyShortcut uses deprecated Write-ChocolateyFailure

### ISSUE THREAD

**Issue by dhilgarth** [chocolatey/choco#126]
Install-ChocolateyShortcut seems to be using the deprecated Write-ChocolateyFailure internally. When using it with incorrect values, I am only getting

> WARNING: Write-ChocolateyFailure is deprecated. If you are the package maintainer, please use 'throw $_.Exception' instead.

The original message is lost.

**Comment by ferventcoder** [comment]
Would you believe this is a duplicate by a matter of hours? #122

**Comment by dhilgarth** [comment]
I am not sure I agree that this is a duplicate. It's not that I want `Write-ChocolateyFailure` removed from the code base. I don't care about this function. The problem is: You basically crippled it and now all other functions that use it display a warning instead of giving useful information.

**Comment by ferventcoder** [comment]
Perhaps better to update the description of the other issue? Choco receives the errors table. Perhaps it should output the errors (although it should be doing this now)?

**Comment by ferventcoder** [comment]
Its a duplicate in that the code change is exactly the same, possibly why the other description should be better

**Comment by ferventcoder** [comment]
I updated the description of the other to make it better. Also Write-ChocolateyFailure is now throwing the error message again.

**Comment by dhilgarth** [comment]
Nice, thanks! :+1:
