### ISSUE TITLE
FEATURE REQUEST: open maintainership for "abandoned" packages

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/choco#1262]
IF

> chocolatey-ops (reviewer) on xxx
> 
> We've found package version in a submitted status and waiting for your next actions. It has had no updates for 20 or more days since a reviewer has asked for corrections. Please note that if there is no response or fix of the package within 15 days of this message, this package version will automatically be closed (rejected) due to being stale.
> 
> Take action:
> * Log in to the site and respond to the review comments.
> * Resubmit fixes for this version.
> * If the package version is failing automated checks, you can self-reject the package.
> 
> If your package is failing automated testing, you can use the chocolatey test environment to manually run the verification and determine what may need to be fixed.
> 
> Note: We don't like to see packages automatically rejected. It doesn't mean that we don't value your contributions, just that we can not continue to hold packages versions in a waiting status that have possibly been abandoned. If you don't believe you will be able to fix up this version of the package within 15 days, we strongly urge you to log in to the site and respond to the review comments until you are able to.

AND package number of versions submitted =1 #i.e. most likely abandoned or put on the back burner

BEGIN
Remove maintainer and make the package ID available for a new maintainer without having to request via admin.
END

**Comment by ferventcoder** [comment]
Unless I am missing something, this is not a feature request for choco - this is a feature request for the community repository (the community repository is one piece in the bigger Chocolatey framework). Please file an issue at https://github.com/chocolatey/chocolatey.org. HTH

**Comment by bcurran3** [comment]
Thanks - now in the right place.

There really needs to be a complete index with all the multiple places for documentation, support, forums, and bug reports!

**Comment by ferventcoder** [comment]
There are issue templates - meant to help direct you in the right direction.

**Comment by ferventcoder** [comment]
Not that it is always clear cut.
