### ISSUE TITLE
Choco info / choco list detailed should provide release notes

### ISSUE THREAD

**Issue by szachara** [chocolatey/choco#1263]
How can I get Release notes link via choco cli? `choco info` doesn't offer this info.

e.g. for `choco info notepadplusplus`

**Comment by ferventcoder** [comment]
It doesn't yet, and that's something we want to offer. Let's ensure there isn't already an issue created here.

**Comment by ferventcoder** [comment]
This will also need the remote side to support providing this information (which it may already).

**Comment by szachara** [comment]
My reason to ask this was, that i'm using https://github.com/chocolatey/ChocolateyGUI sometimes and it offers this info on a package's detail page. May be his author will share with us, how he obtain this information @gep13

**Comment by ferventcoder** [comment]
It's available. I was working on something else and this was easy enough to pull in.
