### ISSUE TITLE
Support for Admin Only Sources - Limit non-admin list to self service only

### ISSUE THREAD

**Issue by lukemgriffith** [chocolatey/choco#1265]
Currently with feature useBackgroundServiceWithSelfServiceSourcesOnly enabled, a user without admin permissions can do choco list and return items from all configured sources by default, including packages from sources that are not configured for self service.

Would it be possible for non elevated users to only have self service packages returned, as its the only items they can actually install.

**Comment by ferventcoder** [comment]
This is interesting. I like it. By the way, I set this up  - https://github.com/chocolatey/chocolatey-licensed-issues

**Comment by ferventcoder** [comment]
This would probably need to be logged over with ChocolateyGUI as well.

**Comment by lukemgriffith** [comment]
Awesome, I'll take a look. I'll also get it logged there now, I know from previous spelunking I've seen .IsElevated() so i imagine it *should* be possible :P

**Comment by ferventcoder** [comment]
I'd agree.
