### ISSUE TITLE
Uninstall-ChocolateyZipPackage not working together with Install-ChocolateyZipPackage

### ISSUE THREAD

**Issue by dhilgarth** [chocolatey/choco#127]
`Install-ChocolateyZipPackage` creates a file named `<packageName>Install.zip.txt` in the `<packageName>` subfolder of the lib folder.

However, `Uninstall-ChocolateyZipPackage` asks for the name of the original zip file - which is most likely different from the package name - and looks for a file <zipFileName>.txt directly in the lib folder.

**Comment by ferventcoder** [comment]
I may have this fixed as part of something else I'm doing. Was looking at that this morning. Related to #120

**Comment by dhilgarth** [comment]
Can you verify this is fixed?

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/commit/a572a3f10df6667d1330e52634291404ecb52f07

**Comment by ferventcoder** [comment]
Yep, this should be fixed in rc9.

**Comment by berndb84** [comment]
I think i found another issue regarding Install-ChocolateyZipPackage and Uninstall-ChocolateyZipPackage.

In **Install-ChocolateyZipPackage** line 202 the zip file is renamed from _$packageName_ to _($packageName)Install.zip_ 
`$downloadFilePath=Join-Path$tempDir"$($packageName)Install.$fileType"`

**Get-ChocolateyUnzip** adds a new textfile with this _($packageName)Install.zip_ filename in line 121
`$zipExtractLogFullPath= Join-Path $packagelibPath $zipFilename`.txt`

If you now want to uninstall the zip paket, the **Uninstall-ChocolateyZipPackage** function is only looking for _$packageName.txt_ (line 67) to remove all installed files.
` $zipContentFile=(join-path $packagelibPath $zipFileName) + ".txt"`
