### ISSUE TITLE
`cup all` error msg :If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.

### ISSUE THREAD

**Issue by spences10** [chocolatey/choco#1270]
### What You Are Seeing?

This:
![image](https://cloud.githubusercontent.com/assets/234708/25520718/dbc223e4-2bf4-11e7-8ec9-d69ac2c22e35.png)

### What is Expected?

Not that 😕 

### How Did You Get This To Happen? (Steps to Reproduce)

```shell
cup all
```

### Output Log

How to run output log? 

I was doing the command `cup all` so is it `cup all --debug --verbose` ?? it's not clear

I'm guessing it's something to do with me clearing out my temp folder but a temp folder is just that, the packages shouldn't rely on that because it's temp, right?

Any guidance on fixing this?

I'm going to try reinstall the packages in the meantime

I couldn't find clear instructions on how to clear out the temp folder with choco so any pointers appreciated too 👍 

Thanks

**Comment by spences10** [comment]
Ok, did a 'choco upgrade <package>` on all the once I got the error message with all seems fine now :+1:

![image](https://cloud.githubusercontent.com/assets/234708/25521444/76fab130-2bf7-11e7-81f9-937c2677f461.png)

I'd still like to know if there's a away to clear out the temp folder though

**Comment by ferventcoder** [comment]
The temp folder is just that - temporary. Feel free to clean it out - it doesn't cause the issue you are seeing - the source timing out does.

**Comment by ferventcoder** [comment]
Right now there is a bit of that - we are looking into this currently

**Comment by spences10** [comment]
Ok, feel free to close the ticket then, thanks

**Comment by ferventcoder** [comment]
FYI - there is a clean command planned - #1124
