### ISSUE TITLE
Output says "Running auto uninstaller" when explicitly skipping it

### ISSUE THREAD

**Issue by aronovgj** [chocolatey/choco#1277]
### What You Are Seeing?
```
cuninst python2-x86_32 --skipautoininstaller
Chocolatey v0.10.5
Uninstalling the following packages:
python2-x86_32

python2-x86_32 v2.7.11
 Running auto uninstaller...
 Skipping auto uninstaller - The application appears to have been uninstalled already by other means.
 python2-x86_32 has been successfully uninstalled.

Chocolatey uninstalled 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

### What is Expected?

Don't shock the user by saying you run the autouninstaller although the user explicitly says to not do so, just to say then "It's a prank, bro!". Don't show that the auto uninstaller is running when it is not.

### How Did You Get This To Happen? (Steps to Reproduce)
Uninstall a package using `--skipautoininstaller`

**Comment by ferventcoder** [comment]
There is no option with that name in choco. So that is why you are seeing that

**Comment by ferventcoder** [comment]
Can you verify when you pass the right switch that you do not see the message?

**Comment by aronovgj** [comment]
Yep. Was a typo :)

Sorry.
