### ISSUE TITLE
[Question]Before update, any method for the end of the installation/update?

### ISSUE THREAD

**Issue by Outek** [chocolatey/choco#1280]
There is a script, which is executed before an update. Is there a simple way to integrate a script or something, which is executed after the installation of a package? As example, to set a registry value or something like this?

**Comment by ferventcoder** [comment]
Why not use the end of the install script?

Is this a per package or every package kind of thing?

**Comment by Outek** [comment]
It's a every package thing.
So i can append everything at the end of the script without to break it?
If so, the question can be closed.

**Comment by ferventcoder** [comment]
Yes, and you can set up an extension package to manage handling ensuring methods and functions are loaded up as well. Take a look at https://chocolatey.org/docs/how-to-create-extensions HTH
