### ISSUE TITLE
Install-ChocolateyPackage should alias File/File64

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1284]
### Issue
When passing File and FileType to Install-ChocolateyPackage, it can cause the following issue to occur:

`ERROR: Cannot bind parameter because parameter 'fileType' is specified more than once. To provide multiple values to parameters that can accept multiple values, use the array syntax. For example, "-parameter value1,value2,value3".`

This is well documented at https://github.com/chocolatey/choco/wiki/Troubleshooting#error-cannot-bind-parameter-because-parameter-filetype-is-specified-more-than-once :

~~~powershell
$toolsPath      = $(Split-Path -parent $MyInvocation.MyCommand.Definition)

$packageArgs = @{
  packageName   = 'test'
  fileType      = 'MSI'
  file          = "$toolsPath\somefile.msi"
  softwareName  = 'test'
  silentArgs    = '/qn /norestart'
  validExitCodes= @(0)
}

Install-ChocolateyPackage @packageArgs
#Install-ChocolateyInstallPackage @packageArgs # this is likely what was meant to be used in this scenario
~~~

`Install-ChocolateyPackage` doesn't have both a `File` parameter and a `FileType` parameter. PowerShell has a "feature" where it does partial matching of parameters. When you splat the parameters in, it tries to apply both `File` and `FileType` to `FileType` and throws the above error. We've already researched and there is no way to shut it off in PowerShell itself.

### Not For Use With Community Packages Until 2018

**NOTE**: Some features come out, but are not immediately available for use with the community package repository - this is one of them. While this is now available, it will not be recommended for wider use in the community package repository for six months as it will cause errors in earlier versions of Chocolatey.

### References

* Numerous but https://groups.google.com/d/msgid/chocolatey/40736df7-7f3f-4be7-929d-1606be0e3a62%40googlegroups.com

**Comment by ferventcoder** [comment]
**NOTE**: While this is now available, it will not be recommended for wider use (in the community package repository) for six months as it will cause errors in earlier versions of Chocolatey.

**Comment by AdmiringWorm** [comment]
@ferventcoder while it's not recommended, is it allowed?
I'm thinking from a moderators perspective of whether we should push the package back and request them to remove the file/file64 parameter?
