### ISSUE TITLE
Implement a way for batch installing multiple disperate packages

### ISSUE THREAD

**Issue by mrhockeymonkey** [chocolatey/choco#1286]
A feature request

Could we implement a way to allow a user to specify a list of packages they require and feed this to choco install to have chocolatey do each install in series. For instance a simple text file that contains the names and optionally versions of packages required. 

Example much like how pip allows you to install multiple modules using -r 
```
pip help install
...
  -r, --requirement <file>    Install from the given requirements file. This
                              option can be used multiple times.
```

To clarify also I do not mean to install dependencies! packages listed in this requirements file would be separate and unrelated. Its just that we want to install one and then the other quickly, easily and repeatably.

**Comment by AdmiringWorm** [comment]
Actually, you can kind of do this already.
Since choco is built upon nuget you can feed a nuget packages.config list when calling `choco install`.

Here is an example of such a list:
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="7zip" version="16.04" />
  <package id="ccleaner" version="5.29.6033" />
</packages>
```

Not sure if version is required in the xml though.

**Comment by ferventcoder** [comment]
Version is not required

**Comment by ferventcoder** [comment]
https://chocolatey.org/docs/commands-install - currently this is achievable with a packages.config file, by specifying multiple packages to the install command, or by a PowerShell script. Please provide commentary if one of these is not sufficient to meet your needs. Closing as already implemented.
