### ISSUE TITLE
dotnet 4.6.1 installing win8 update in win10

### ISSUE THREAD

**Issue by dennyhalim** [chocolatey/choco#1293]
### What You Are Seeing?
KB2919355 and KB2919442 is installed in my windows 10 system

### What is Expected?
aren't those update should only apply to win8??

### How Did You Get This To Happen? (Steps to Reproduce)
choco upgrade -y all

looks like it's installed as dotnet 4.6.1 dependencies which in turn is chocolatey-core.extension dependencies

**Comment by ferventcoder** [comment]
The packages are installed but not the actual KBs correct? We don't have dependencies limited to particular operatings systems just yet.

FYI - if you noticed in the issue template - package issues should not be created here. Those go back to the package maintainers. HTH
