### ISSUE TITLE
[Request] Existing Software Support

### ISSUE THREAD

**Issue by zero77** [chocolatey/choco#1295]
Can you please add support for detection of existing installed and portable software and the option to update existing installed and portable software.
Thanks

**Comment by ferventcoder** [comment]
Hi @zero77 - This exists already. It's called package synchronization. It's available in licensed versions of Chocolatey (Business currently, but will come down to Pro in 3rd Quarter 2017). Please see https://chocolatey.org/compare (specifically the sync command - https://github.com/chocolatey/choco/wiki/FeaturesSynchronize

Unfortunately, synchronization will not trickle down to the FOSS version. For FOSS-only options, you can take a look at https://github.com/chocolatey/choco/wiki/How-To-Install-Upgrade-Package-Without-Scripts for how you can manually make Chocolatey aware. You can also just install newer versions over the top of existing version of installed software using Chocolatey and it will take over that install.

HTH

**Comment by mphz** [comment]
@ferventcoder i think @zero77 's query is what softwares can be installed via choco, it had better there is a software list
