### ISSUE TITLE
Choco Download works on Self-Service repo

### ISSUE THREAD

**Issue by lukemgriffith** [chocolatey/choco#1299]
### What You Are Seeing?
Ability to use Choco Download, as a business, non-administrative user from a non-selfservice authenticated repository. 

### What is Expected?
Ideally not to be able to download from non-selfservice (potentially authenticated only), as we want to keep our nupkgs away from users - or the ability to disable the download command. 

### How Did You Get This To Happen? (Steps to Reproduce)

Configured an authenticated repository, without allowing self-service and run choco download on a package, and hte source

### Output Log

```
[15:41:57][+2] D:\git\SSLTests
 ? choco source list
Chocolatey v0.10.5 Business
...
...
bob - https://<Redact>/ChocolateyRepo/nuget (Authenticated)| Priority 0|Bypass Proxy - False|Self-Service - False.


[15:39:31][+2] D:\git\SSLTests
 ? choco download Atom -s bob --ignoredependencies
Chocolatey v0.10.5 Business
Downloading existing package(s) to D:\git\SSLTests\download

Progress: Downloading Atom 1.15.0... 82%
Progress: Downloading Atom 1.15.0... 100%

Atom v1.15.0

Package downloaded to 'D:\git\SSLTests\download\Atom'
```

**Comment by ferventcoder** [comment]
@lukemgriffith I think we can do this. I've moved this over to https://github.com/chocolatey/chocolatey-licensed-issues/issues/4 and will continue comments there.
