### ISSUE TITLE
Enable removal of API key via CLI

### ISSUE THREAD

**Issue by bc3tech** [chocolatey/choco#1301]
Choco v0.10.5 allows you to `choco setapikey` or `choco apikey` but once you've set an api key, there's no way to **remove** it.
Instead, you have to open `chocolatey.config` and delete the XML block to make this happen.

Let's add a CLI command for removing API keys.

**Comment by ferventcoder** [comment]
👍

**Comment by tiget** [comment]
I would like to take this on. It'd be my first PR.

**Comment by ferventcoder** [comment]
@tiget sounds great! Make sure you read through [CONTRIBUTING](https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md). It may be a slightly long read, but it has very specific information and is a good guide for knowing if your contribution will be accepted or need quite a bit of rework. 

https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md

**Comment by ferventcoder** [comment]
This has been completed and will be released with 0.10.12. The corresponding merge commit is at https://github.com/chocolatey/choco/commit/3540b3c4aca45cde0459a237639242dbf5030c37.
