### ISSUE TITLE
choco new generates uninstall template with wrong use of a variables

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/choco#1304]
### What You Are Seeing?
In the last `elseif` statement of the generated chocolateyuninstall.ps1 script it generates the following:
```powershell
} elseif ($key.Count -gt 1) {
  Write-Warning "$key.Count matches found!"
  Write-Warning "To prevent accidental data loss, no programs will be uninstalled."
  Write-Warning "Please alert package maintainer the following keys were matched:"
  $key | % {Write-Warning "- $_.DisplayName"}
}
```
Which will output the the full keys and append `.Count`/`.DisplayName` instead of outputting the Count, or the display name of the key.
This can be seen from the following appveyor build:
https://ci.appveyor.com/project/chocolatey/chocolatey-coreteampackages/build/1778-yqtgkmnh#L197

### What is Expected?
Expected the template to be generated with wrapping the calls to `$key.Count` and `$_.DisplayName` within parenthesis like this:
```powershell
} elseif ($key.Count -gt 1) {
  Write-Warning "$($key.Count) matches found!"
  Write-Warning "To prevent accidental data loss, no programs will be uninstalled."
  Write-Warning "Please alert package maintainer the following keys were matched:"
  $key | % {Write-Warning "- $($_.DisplayName)"}
}
```

### How Did You Get This To Happen? (Steps to Reproduce)
Run `choco new temporary` and look inside the `chocolateyuninstall.ps1` file.

### Output Log
No log available for this.

**Comment by ferventcoder** [comment]
This will be in 0.10.6
