### ISSUE TITLE
Feature Request - Add a command similar to 'pip freeze' to automatically create a packages.config from currently installed packages

### ISSUE THREAD

**Issue by admsteck** [chocolatey/choco#1316]
I think the title says it all.  It would make it much easier to keep multiple machines in-sync.

**Comment by ferventcoder** [comment]
Duplicate of https://github.com/chocolatey/choco/issues/357. Please follow along there.

**Comment by ferventcoder** [comment]
Let us know if this is different than that feature request.

**Comment by admsteck** [comment]
That's it.  I searched for "freeze" and I thought I searched for "packages.config" (must have mistakenly searched for "package.config" without the "s") and didn't find any existing issues.  Thanks.
