### ISSUE TITLE
[API] Expose Package Results through the API

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#132]

**Comment by Jaykul** [comment]
Do you want to change or overload the "Run()" method so it can return output? 
Maybe a generic `List<T> Run<T>()` overload? 

I mean this is going to need to include most of the commands where the user expects to see output, at least:
list, search, source list, ...

**Comment by ferventcoder** [comment]
Actually it's more about adding other methods like List, Install, etc instead of just Run(). Run is fire and forget.

**Comment by ferventcoder** [comment]
Unfortunately this one just broke almost every configuration manager that uses choco - https://github.com/chocolatey/choco/commit/5782a217fb576cbc01caa9d1edc7d134e5019ca9#commitcomment-13577152
