### ISSUE TITLE
search /list - page/page-size not honored for exact in 0.10.6

### ISSUE THREAD

**Issue by steve6375** [chocolatey/choco#1322]
choco list chocolatey -r --not-broken --approved-only -a -e -by-id-only --page=0 --page-size=3

This worked in 0.10.5, but 0.10.6 shows many more than 3 items

**Comment by ferventcoder** [comment]
Howdy - some switches are incompatible with others. In this case, there were some fixes to `--exact`/`-e` to make it work in all instances, so it may not be compatible with other switches like page/page size.

I would recommend if you are using this with any scripting (the `-r` makes it look like you are), be very leary of using `-a` as all versions has some known drain on the community repo - it should be avoided in tools provided to the community.

**Comment by steve6375** [comment]
If I don't use -e then I get boxstarter.chocolatey listed and not chocolatey.

chocolatey is just an example. The command is used in a script to list to the user the most recent versions available in case they want an earlier version.

How do you suggest I list the latest 10 versions of any application?

**Comment by ferventcoder** [comment]
I'd say it is fine to use `-e`, but with `exact` you don't need `--by-id-only`.

**Comment by ferventcoder** [comment]
Maybe by default list the current version and let the user decide to see older versions, then go back and run with `-a` and take only the first ten results.

**Comment by steve6375** [comment]
yes, that is what I do, but  i need to use -a and -e and page size does not work...

**Comment by ferventcoder** [comment]
I'm not sure `GetPackageById` supports paging. Let's leave this issue open until we know for sure.

**Comment by ferventcoder** [comment]
You can filter the results to first ten before you present to the user. What are you using to script this? PowerShell?

**Comment by steve6375** [comment]
no, cmd. I could use | more to get first n lines maybe

**Comment by steve6375** [comment]
choco list chocolatey -r --not-broken --approved-only -a -e  --page=0 --page-size=3

does not work, so it's not --by-id that is the problem...

**Comment by steve6375** [comment]
choco list chocolatey --approved-only -e -a --page=0 --page-size=3

also does not work. So it is -e -a that is the problem.

**Comment by steve6375** [comment]
choco list chocolatey --approved-only  -a --page=0 --page-size=3

strangely - this lists three 7zip packages!!!

**Comment by ferventcoder** [comment]
See above - I confirmed immediately that it was `-e`. There was no question on that. The rest has been giving you helpful suggestions on your script.

**Comment by ferventcoder** [comment]
And here is more info on why - https://github.com/chocolatey/choco/issues/1322#issuecomment-306009336

**Comment by ferventcoder** [comment]
This issue is in triage until we determine if paging can be used with the new way of returning packages for `-e` that works with without error - at that time we either call the switches incompatible or switch this to a bug to fix. Make sense? :)

**Comment by ferventcoder** [comment]
#1004 was the issue.

**Comment by ferventcoder** [comment]
For us, having info and search/list `-e` work 100% of the time is going to be most desirable.

**Comment by ferventcoder** [comment]
Good news, page size is supported! This is fixed for 0.10.6.2.
