### ISSUE TITLE
RegisterContainerComponents throws an exception since the constructor has already called GetInstance on the container

### ISSUE THREAD

**Issue by mwrock** [chocolatey/choco#133]
We should defer container lookups until `Run` is called to give callers the opportunity to register components.

**Comment by mwrock** [comment]
fixed by PR #130

**Comment by ferventcoder** [comment]
These will automatically close when the PR is merged.

**Comment by ferventcoder** [comment]
Of course it only closes if the merge is done in a way that github can use.
