### ISSUE TITLE
Document how to pass multiple sources on CLI

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/choco#1331]
### What You Are Seeing?
The help for the `-s` option only mentions how to pass one single source:

```
 -s, --source=VALUE
     Source - The source to find the package(s) to install. Special sources
       include: ruby, webpi, cygwin, windowsfeatures, and python. Defaults to
       default feeds.
```

### What is Expected?
It should also mention how to pass multiple sources.

### How Did You Get This To Happen? (Steps to Reproduce)
`choco install /?`

**Comment by ferventcoder** [comment]
This is in for 0.10.8, it will find its way to documentation at some point later.
