### ISSUE TITLE
Install-ChocolateyPackage / Get-ChocolateyUnzip - switch to not log the files during unzip for zips with many files

### ISSUE THREAD

**Issue by njlr** [chocolatey/choco#1332]
Choco times-out for large zip files (`9, 500+` files). 

Perhaps an option to disable the logging of each file would speed-up the process?

(**Admin edit** - notes):
* Reference - [June 12, 2017 11:18 AM](https://gitter.im/chocolatey/choco?at=593ebec3c59bd9c4640bc4de)

**Admin edit** - Gitter screenshots
The above link to Gitter may disappear as we have transitioned to Discord for chat, so capturing some screenshots of the conversation:

<img width="745" alt="2021-11-13_21-10-51" src="https://user-images.githubusercontent.com/1271146/141659289-832134e8-ceb0-4121-ae35-5034d70d7062.png">

<img width="1029" alt="2021-11-13_21-12-34" src="https://user-images.githubusercontent.com/1271146/141659220-aba6e688-cc4a-40da-8ebb-2b806ad51884.png">

<img width="983" alt="2021-11-13_21-13-06" src="https://user-images.githubusercontent.com/1271146/141659235-6be62f80-42bd-41b8-be94-ea68045abe35.png">

<img width="529" alt="2021-11-13_21-13-32" src="https://user-images.githubusercontent.com/1271146/141659247-0c40ab4d-aab4-4e8c-b3e2-b1e4bd7bc9c1.png">

<img width="971" alt="2021-11-13_21-14-03" src="https://user-images.githubusercontent.com/1271146/141659263-50f3e11f-8ad9-4b15-9b8b-f1dbaa695dd2.png">

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/blob/e96fb159e0957d9e2fee1e738d42dcc414957c91/src/chocolatey.resources/helpers/functions/Get-ChocolateyUnzip.ps1#L151 is where it sets the log level (currently `-bb1`). This switch would allow for the log detail to be missing.

This would also remove chocolatey's ability to use `Uninstall-ChocolateyZipPackage` as it would not be capturing the file list for removal, but if you are just unpacking into the package directory, this is okay anyway as that function is not necessary.

**Comment by ferventcoder** [comment]
Reference - [June 12, 2017 11:18 AM](https://gitter.im/chocolatey/choco?at=593ebec3c59bd9c4640bc4de)

**Comment by gep13** [comment]
In order to make this work, there would need to be some upstream changes in the chocolatey.extension, so that the same logic could be applied there, when required.

**Comment by pauby** [comment]
In the release notes, we should call out that this will not be available in licensed versions until a release of the Licensed extension.

**Comment by gep13** [comment]
A follow up issue for Chocolatey Licensed Extension has been created so that this work can be tracked.
