### ISSUE TITLE
Implement Read-Host -AsSecureString

### ISSUE THREAD

**Issue by niralatuladhar** [chocolatey/choco#1335]
I have read-host to input the password in secure string in chocolateyinstalls.ps1. However, when I do choco install it doesn't pop up for secure string. Instead it just take the insecure string and show all the password I type. 

This is the code I have,
   $response = Read-host "Please enter password for postgres user." -AsSecureString

**Comment by ferventcoder** [comment]
@niralatuladhar version of Chocolatey?

**Comment by ferventcoder** [comment]
We definitely read in passwords typically without showing what is typed in. 

However this is likely an enhancement to Chocolatey as I'm not sure we do it for this. By the way, Chocolatey's first use case is not for interactive input (but it can be used in that way).

**Comment by ferventcoder** [comment]
If you can use Prompt for Credential, that will be read in securely.

**Comment by niralatuladhar** [comment]
The chocolatey version is 0.10.4.

**Comment by ferventcoder** [comment]
Thanks - added this as an enhancement for the next version of Chocolatey.

**Comment by ferventcoder** [comment]
This will be in 0.10.8.
