### ISSUE TITLE
I can't reach programs that i installed with choco

### ISSUE THREAD

**Issue by MuhammedKpln** [chocolatey/choco#1337]
### How Did You Get This To Happen? (Steps to Reproduce)
1.Install any program, Chocolateygui example.
2.Then i can't reach it anymore, i can reach it only from start menu ( latest added section)
### Output Log

GIST LINK - Please create a gist and link to that gist here

OR

~~~sh
PLACE LOG CONTENT HERE
~~~

**Comment by ferventcoder** [comment]
Hi @MuhammedKpln what do you mean can't reach, but can get to it from the start menu?

**Comment by MuhammedKpln** [comment]
Nope i can't. It seems to be not installed correctly, i can't access programs that i installed with chocolatey. An example i have installed ext2fsd via chocolatey and now i can't reach it. Not even in start menu

**Comment by ferventcoder** [comment]
Hi @MuhammedKpln, what does closed mean? Were you able to figure out what was going on?
