### ISSUE TITLE
Get-Toolslocation / neovim installation problem

### ISSUE THREAD

**Issue by jchidley** [chocolatey/choco#1338]
### What You Are Seeing?
Neovim was installed in a set of directories under C:\tools\Get-ToolsLocation\neovim and I now have an extra, empty, directory C:\Windows\System32\Get-ToolsLocation and an installation under C:\Windows\SysWOW64\Get-ToolsLocation\neovim

### What is Expected?
not the above!
### How Did You Get This To Happen? (Steps to Reproduce)
choco install neovim
choco install neovim -y --force

**Comment by ferventcoder** [comment]
@jchidley this is a package issue - in the creation of your issue you may have noticed this statement? 

> DO NOT CREATE ISSUES FOR PACKAGES. Read over Submitting Issues.

https://github.com/chocolatey/choco#submitting-issues is where that is at. 

I know the maintainer was working on getting it fixed, which I believe he/she did. You may wish to follow up directly with them. Thanks.

**Comment by ferventcoder** [comment]
To give you a better indication of where to go, head to https://chocolatey.org/docs/package-triage-process (although it doesn't mention the first step, use the disqus thread or contact the maintainer using the links on the left side (Contact Maintainers). Packages on the community package repository are provided and maintained by the community. This repository is for issues with the Choco tool itself. If you go through the submitting issues bit, it will lead you in the right direction to get things fixed. Definitely let us know if there is something confusing or missing though!

**Comment by jchidley** [comment]
Despite my efforts, it was unclear to me where the problem lay hence why I raised an issue with chocolatey.  From my point of view, that was the right thing to do as I know where the problem is.  The complexity of problem identification, and the length of the submission form for chocolatey are daunting - and I am an IT professional who specialises in systems delivery.

**Comment by ferventcoder** [comment]
@jchidley no worries. We're working on better deciphering if it is a package issue or a choco issue.

Most of the time it is a package issue.
