### ISSUE TITLE
cannot uninstall package with .config in the name

### ISSUE THREAD

**Issue by peter172sp** [chocolatey/choco#134]
C:\>choco uninstall eos.configurationtool
Chocolatey v0.9.9-rc9
Uninstalling the following packages:
eos.configurationtool
A packages.config file is only used with installs.

It seems my choice of package name is causing chocolatey to mistakenly believe I want to use a packages.config file to do the uninstall.

**Comment by ferventcoder** [comment]
Interesting. Perhaps it would be best to ensure that config is is how it ends.

**Comment by talcloudshare** [comment]
Unfortunately this still happens when a package name ends with .config

**Comment by ferventcoder** [comment]
@talcloudshare yes - that is what I wrote in my last comment:  

> Perhaps it would be best to ensure that config is is how it ends.

Meaning, having ".config" in the name is fine, ending with ".config" is bad.

**Comment by ferventcoder** [comment]
If you are needing this to be addressed for the ending with .config - then that means a new issue. Please file it. However we still need a way to know if this is a packages.config versus a package with that name. I don't like the using packages that end with .config.
