### ISSUE TITLE
[API] GetConfiguration() sets the configuration for other calls

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1347]
https://github.com/chocolatey/choco/blob/e96fb159e0957d9e2fee1e738d42dcc414957c91/src/chocolatey/GetChocolatey.cs#L368-L373 doesn't call out possible side effects efficiently enough.

**Comment by ferventcoder** [comment]
Hopefully the changes made for 0.10.8 fix issues with repeated values making it through. 

Just ensure that you never access `ChocolateyConfiguration` through the container or `Config.get_configuration_settings()` and make changes directly to it as it has unforeseen side effects. FYI, @mwrock - can you make sure that this is the case in boxstarter? All configuration should be passed in through `GetChocolatey.Set()` and nowhere else. 

Added this to GetChocolatey summary:
~~~
/// NOTE: When using the API, this is the only means of accessing the ChocolateyConfiguration without side effects.
/// DO NOT call `Config.get_configuration_settings()` or access the container to pull out the ChocolateyConfiguration.
/// Doing so can set configuration items that are retained on next use.
~~~

**Comment by batzen** [comment]
Wouldn't it be better to return a cloned config in the mentioned methods to prevent this issue? Or would that cause more harm?

**Comment by ferventcoder** [comment]
@batzen that is exactly what the API does. If those mentioned methods did it would cause more harm than good.

**Comment by ferventcoder** [comment]
The one thing I think may still be an issue is that with Boxstarter there may be some nesting, so when one Configuration is returned, that gets used with the nested packages as well instead of finishing the use, then allowing the config to return to the default setting for use with the next command.

**Comment by batzen** [comment]
I guess every package in boxstarter is nested and that's the problem.

**Comment by ferventcoder** [comment]
The problem comes down to a base configuration that is set early on that needs to be maintained across multiple calls. #1394 may have a good explanation of that.

**Comment by ferventcoder** [comment]
Sorry, that was #1296

**Comment by batzen** [comment]
I guess the only one really knowing what has to be changed in boxstarter is @mwrock.
I currently got no time to get familiar with the boxstarter sources to give educated comments.
