### ISSUE TITLE
Non-Admin User install location not overidden by %ChocolateyInstall%

### ISSUE THREAD

**Issue by tmwsiy2012** [chocolatey/choco#1348]
### What You Are Seeing?
I am following the instructions for non-admin install which show setting the ENV Var "ChocolateyInstall" on the User  with a location in AppData and then calling the normal iex install.
### What is Expected?
I am expecting there to be a copy of chocolatey installed in the AppData of the currently logged in non-admin user.
### How Did You Get This To Happen? (Steps to Reproduce)
Run the Following as a non-admin user
$ChocolateyInstall = "C:\Users\$env:UserName\AppData\Local\Programs\chocolatey"
New-Item $ChocolateyInstall -Type Directory -Force
[Environment]::SetEnvironmentVariable("ChocolateyInstall", $ChocolateyInstall, "User")
iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
### Output Log

https://gist.github.com/tmwsiy2012/81099324026205be0f524eeb874b26d0

**Comment by ferventcoder** [comment]
@tmwsiy2012 what happens instead when you run the script like this:

~~~powershell
$env:ChocolateyInstall = "C:\Users$env:UserName\AppData\Local\Programs\chocolatey"
iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
~~~

**Comment by ferventcoder** [comment]
Note, this is like it is shown at https://chocolatey.org/install#non-administrative-install

**Comment by tmwsiy2012** [comment]
I get different output but it is still fails trying to write stuff to programdata install.

https://gist.github.com/tmwsiy2012/8ab7cee6c12dce75634569dde30c6ee2

**Comment by tmwsiy2012** [comment]
Unless I am missing something (which is likely) It looks like chocolateyInstall.ps1 is calling Initialize-Chocolatey with no parameter which will make it default to programdata.

function Initialize-Chocolatey {
<#
  .DESCRIPTION
    This will initialize the Chocolatey tool by
      a) setting up the "chocolateyPath" (the location where all chocolatey nuget packages will be installed)
      b) Installs chocolatey into the "chocolateyPath"
            c) Instals .net 4.0 if needed
      d) Adds Chocolatey to the PATH environment variable so you have access to the choco commands.
  .PARAMETER  ChocolateyPath
    Allows you to override the default path of (C:\ProgramData\chocolatey\) by specifying a directory chocolatey will install nuget packages.
  .EXAMPLE
    C:\PS> Initialize-Chocolatey
    Installs chocolatey into the default C:\ProgramData\Chocolatey\ directory.
  .EXAMPLE
    C:\PS> Initialize-Chocolatey -chocolateyPath "D:\ChocolateyInstalledNuGets\"
    Installs chocolatey into the custom directory D:\ChocolateyInstalledNuGets\
#>

**Comment by tmwsiy2012** [comment]
I think I figured it out. It wants the env var ChocolateyAllowInsecureRootDirectory set to true. It works then!

**Comment by ferventcoder** [comment]
That's for `c:\chocolatey`.

**Comment by tmwsiy2012** [comment]
I think that this issue is a lack of understanding on my part about when environment variables are applied. I created this test that works with current stable so this can be closed. I was so concerned about persistence and I forgot to take care of the current.
```
function Remove-PathFromPath{
Param(
  [string]$pathToRemove='C:\ProgramData\chocolatey\bin',
  [string]$MachineOrUser='Machine'
)
<#
Remove a path from %PATH%
#>
$path = [System.Environment]::GetEnvironmentVariable('PATH',$MachineOrUser)
$pathNow = $env:path
# Remove unwanted elements
$path =    ($path.Split(';') | Where-Object { $_ -ne $pathToRemove }) -join ';'
$pathNow = ($pathNow.Split(';') | Where-Object { $_ -ne $pathToRemove }) -join ';'
# Set it
$env:path = $pathNow
[System.Environment]::SetEnvironmentVariable('PATH',$path,$MachineOrUser)


}

Remove-PathFromPath
$ChocolateyInstallLoc = "C:\Users\$env:UserName\AppData\Local\Programs\chocolatey"
[Environment]::SetEnvironmentVariable("ChocolateyInstall", $ChocolateyInstallLoc, "User")
$env:ChocolateyInstall="$ChocolateyInstallLoc"
$env:ChocolateyAllowInsecureRootDirectory=$true
iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
```
