### ISSUE TITLE
[Question] Publication of incorrect versions of the package, above than the actual

### ISSUE THREAD

**Issue by Kristinita** [chocolatey/choco#1351]
### 1. Problem

I publish wrong version of [**Vale Chocolatey package**](https://chocolatey.org/packages/vale). Correct version — 0.4.1, I publish 1.4.1. I'm sorry, that I make an error and I want fix it.

At day [**0.8.1 is the newest Vale version**](https://github.com/ValeLint/vale/releases). If user wrote `choco install vale` in terminal, he installs 0.4.1 (1.4.1 in Chocolatey) version, not newest. User will download old 0.4.1 version, but not newest 0.8.2, 0.9.0, 0.9.5 and so on.

### 2. Question

How I can fix this problem? Can I remove wrong version? It would be nice, if would be possible remove separate “1.4.1” version from package, not another versions.

### 3. Do not offer

1. I can't create another package with same content, but another name. The program Vale doesn't have another names.
1. Leave everything as is — is a not good idea, because It may take a lot of time, that **real** 1.4.1 or above version of Vale program will release.

Thanks.

**Comment by ferventcoder** [comment]
Unlist the 1.4.1 version.

**Comment by Kristinita** [comment]
> Unlist the 1.4.1 version.

Can you tell in more details or show me a link, how I can do it? I didn't find any relevant results by Google query `chocolatey unlist`.

Thanks.

**Comment by ferventcoder** [comment]
1. Go to https://chocolatey.org 
1. Sign in
1. Go to your package page - https://chocolatey.org/packages/vale
1. Scroll down to versions
1. Click on "yes" link under listed
   ![image](https://user-images.githubusercontent.com/63502/27591779-64037c60-5b18-11e7-8d53-c629c7f63ce9.png)
1. Uncheck the box. 
1. Click save
  ![image](https://user-images.githubusercontent.com/63502/27591816-77f7a8ea-5b18-11e7-8984-f8361ca809c8.png)

**Comment by ferventcoder** [comment]
You may wish to push up the 0.4.1 package actual, but maybe just the newer version.
