### ISSUE TITLE
List sub-command should not require admin access (and not prompt)

### ISSUE THREAD

**Issue by Skons** [chocolatey/choco#1353]
When not providing -y the command does not continue but waits for input. When i provide -y i get a 20 second warning. When confirming with -y on the cli, i already confirmed the fact that i do not run an elevated prompt, and thus i should not get a 20 seconds timeout.

Also, it is not a function that really would require elevation.

![image](https://user-images.githubusercontent.com/13225002/27862745-2a480318-6187-11e7-907b-e675914f7ad1.png)

**Comment by ferventcoder** [comment]
@Skons I see what you mean - it could require elevation, if you are running anything but list. We should be able to handle this though.

**Comment by ferventcoder** [comment]
I was thinking there was a similar request for this enhancement (making listing not require admin)

**Comment by ferventcoder** [comment]
This will be in 0.10.8

**Comment by Skons** [comment]
When researching this problem I came across issue #893
