### ISSUE TITLE
Undeprecate the version command

### ISSUE THREAD

**Issue by mcandre** [chocolatey/choco#1357]
Please don't remove the version command, it's tremendously helpful for debugging. `choco upgrade <package> --noop` is a poor replacement.

**Comment by ferventcoder** [comment]
What's wrong with `choco outdated`?

Version is a poor name for a command .

`choco upgrade --whatif` or `--noop` makes sense for most folks who didn't know about the previous command

**Comment by gep13** [comment]
The `choco version` command was removed in Chocolatey CLI 1.0.0 (https://github.com/chocolatey/choco/issues/2468) and there are no plans to bring it back.  As such, I am going to close this issue.
