### ISSUE TITLE
Chocolatey sh.exe fails to launch

### ISSUE THREAD

**Issue by mcandre** [chocolatey/choco#1358]
### What You Are Seeing?

When the sh.exe shell that comes with Chocolatey is launched from most contexts, an error popup appears:

```
sh.exe - Application error

The application was unable to start correctly (0xc000007b). Click OK to close the application.
```

This includes when Chocolatey sh.exe is launched from the Start menu, from explorer.exe, from a shortcut, from a Command Prompt session, or from a bash on Ubuntu on Windows session.

When C:\ProgramData\chocolatey\bin\sh.exe is launched via Powershell, Git bash, or MSYS, the error is silent.

### What is Expected?

`sh.exe -c "echo howdy"` displays `howdy`.

### How Did You Get This To Happen? (Steps to Reproduce)

Try to launch Chocolatey sh.exe.

Using Chocolatey v0.10.7 on Windows 10 Pro x64.

**Comment by ferventcoder** [comment]
There is no sh.exe. Probably a shim created for something installed.

**Comment by ferventcoder** [comment]
Hi @mcandre - didn't hear back on this one. What was it?

**Comment by ferventcoder** [comment]
@mcandre if you ever do figure out what this was, please comment here.
