### ISSUE TITLE
MSYS2 - Alternative Source

### ISSUE THREAD

**Issue by jbenden** [chocolatey/choco#1359]
### What You Are Seeing?

A number of sources are presently available, but none is available for MSYS2.

### What is Expected?

I would love to see MSYS2 as a working source for installation of PACMAN packages within the MSYS2 environment; all from within Chocolatey.

**Comment by pauby** [comment]
There are no plans to add this alternative source at this stage. 

I'm going to go ahead and close this, but we can reopen it if necessary.
