### ISSUE TITLE
The commandline giving to me "Missing Root"

### ISSUE THREAD

**Issue by MuhammedKpln** [chocolatey/choco#1362]
TEMPLATE FOR BUG REPORTS:
### What You Are Seeing?
"Missing Root" text with red color.
### What is Expected?
To upgarde all my programs and remove etc. 
### How Did You Get This To Happen? (Steps to Reproduce)
1.When im trying to update my programs by "choco upgrade all"
2. Then im getting an errorr with red colors "Missing root"

Here is a screenshot of it, i tried to reinstall choco but it didn't work.

http://prntscr.com/fwheee

**Comment by ferventcoder** [comment]
Hi @MuhammedKpln - never saw that one before. Try `choco upgrade all -dv` and submit a full log please.

**Comment by MuhammedKpln** [comment]
`Chocolatey v0.10.7
Chocolatey is running on Windows v 10.0.15063.0
Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
Command line: "C:\ProgramData\chocolatey\choco.exe" upgrade all -dv
Received arguments: upgrade all -dv
RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
Sending message 'PreRunMessage' out if there are subscribers...
[Pending] Removing all pending packages that should not be considered in
The source 'https://chocolatey.org/api/v2/' evaluated to a 'normal' sour

NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
Configuration: CommandName='upgrade'|
CacheLocation='C:\Users\Chemo\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://chocolatey.org/api/v2/'|SourceType='normal'|
Debug='True'|Verbose='True'|Trace='False'|Force='False'|Noop='False'|
HelpRequested='False'|UnsuccessfulParsing='False'|RegularOutput='True'|
QuietOutput='False'|PromptForConfirmation='True'|AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='all'|AllVersions='False'|
SkipPackageInstallProvider='False'|PackageNames='all'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.15063.0'|
Information.PlatformName='Windows 10'|
Information.ChocolateyVersion='0.10.7.0'|
Information.ChocolateyProductVersion='0.10.7'|
Information.FullName='choco, Version=0.10.7.0, Culture=neutral, PublicKe

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='Chemo'|
Information.UserDomainName='DESKTOP-RE2FSEP'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='False'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
FeatureCommand.Command='unknown'|
ConfigCommand.Command='unknown'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|Proxy.BypassOnLocal='True'|
_ Chocolatey:ChocolateyUpgradeCommand - Normal Run Mode _
Upgrading the following packages:
all
By upgrading you accept licenses for the packages.
Running list with the following filter = ''
--- Start of List ---
chocolatey 0.10.7
chocolatey-core.extension 1.3.1
chocolatey-windowsupdate.extension 1.0.2
DotNet4.5.2 4.5.2.20140902
ext2fsd 0.68.0.20161111
filezilla 3.26.2
jre8 8.0.131
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20170509
KB3033929 1.0.3
KB3035131 1.0.1
minecraft 1.9
php 7.1.7
PowerShell 5.1.14409.20170510
putty 0.69
spotify 1.0.58.573
teamspeak 3.1.4
vcredist140 14.10.25017.0
vcredist2015 14.0.24215.20170201
--- End of List ---
Kök öğesi eksik. -- (Basically says Missing Root in english.)
Exiting with 1
PS C:\Windows\system32>
`
Here.

**Comment by ferventcoder** [comment]
What happens if you move to a different directory than system32? Aka `cd c:\`

**Comment by MuhammedKpln** [comment]
@ferventcoder same problem.

**Comment by ferventcoder** [comment]
I'd love to get to the bottom of what causes this - so once you figure out what you have in your environment that causes this to happen, let's get this ticket set up to fix that.

**Comment by ferventcoder** [comment]
Let's try this

* Rename the config file for a second and see if that fixes things.
* Rename the .chocolatey folder at `c:\ProgramData\chocolatey` (hidden) for a moment to see if that fixes things.
* Is vcredist the last package you have alphabetically? Look in `c:\ProgramData\chocolatey\lib`

**Comment by MuhammedKpln** [comment]
Rename the config file for a second and see if that fixes things.
- It didn't work - Same problem
Rename the .chocolatey folder at c:\ProgramData\chocolatey (hidden) for a moment to see if that fixes things.
- It didn't work - Same problem
Is vcredist the last package you have alphabetically? Look in c:\ProgramData\chocolatey\lib
- Yes i have alphabetically, and it is last package.

**Comment by ferventcoder** [comment]
Unfortunately it means you may need to do some more exploratory work to try to determine the issue. Keep in mind that choco is used on many, many machines. Let us know what you determine and if there is any changes we need to make within choco to support this.

**Comment by MuhammedKpln** [comment]
I think i solved this issue by deleting "chocolatey-core.extension, ChocolateyGUI and chocolatey-windowsupdate.extension" files from lib folder. (C:\ProgramData\chocolatey\lib)
