### ISSUE TITLE
Choco new should output a .nuspec in UTF-8 without a byte order mark

### ISSUE THREAD

**Issue by jnm2** [chocolatey/choco#1364]
I'm totally on board with this:

> Do not save your *.nuspec files with a Byte Order Mark (BOM). A BOM is neither required nor recommended for UTF-8, because it can lead to several issues.

https://chocolatey.org/docs/create-packages#character-encoding

But choco new is not. It's currently creating UTF-8-BOM nuspecs.

<sub>Moved from https://github.com/chocolatey/chocolatey.org/issues/527</sub>

**Comment by ferventcoder** [comment]
This one is open for up for grabs.

**Comment by Ben-Shirley** [comment]
I would like to have a go if I may?

**Comment by Ben-Shirley** [comment]
anyone have time to show me where im going wrong?

**Comment by bcurran3** [comment]
I found a bunch of my nuspec files with BOM. I later made https://chocolatey.org/packages/choco-nuspec-checker to fix them automatically... and then got a little ADHD with it. :)
