### ISSUE TITLE
Ability to install from /tools/x64 and /tools/x86 without PowerShell

### ISSUE THREAD

**Issue by jnm2** [chocolatey/choco#1365]
In the NuGet world it's a common convention to put platform-specific things in platform-specific folders, both for native resources and managed resources.

I think it would be cool if Chocolatey adopted the convention of ignoring `/tools/x64` unless you're doing a 64-bit install, in which case it treats the contents of `/tools/x64` as though they were in `/tools`. Likewise for `/tools/x86` and 32-bit installs.

This would remove the need for PowerShell and I could simply distribute:
```
/tools/x64/my-exe-to-shim.exe
/tools/x86/my-exe-to-shim.exe
```

<sub>Moved from https://github.com/chocolatey/chocolatey.org/issues/526</sub>

**Comment by ferventcoder** [comment]
Merged into stable at https://github.com/chocolatey/choco/commit/cd8ef687b7e8c234c4fc989f7bae8da2d515b439

**Comment by gep13** [comment]
@jnm2 This should be pushed out in 0.10.9 of Chocolatey, would love to hear any feedback that you have on it's usage.
