### ISSUE TITLE
More edit "friendly" choco new nuspec template creation for non-beginners

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/choco#1366]
In the spirit of https://github.com/chocolatey/choco/issues/1303...

The default nuspec template created by choco new is a big pet peeve of mine. It consists of very useful information for new packagers stepping through it, but it's a big pain in the keister to edit/remove so much of the tutorial info and replace it with the actual package's needed info.

I brought this topic up and provided a submission for a different format [here](https://groups.google.com/forum/#!topic/chocolatey/QECp33y4mDk).  Unfortunately it didn't gain much traction. So now it's a feature request! :)

I don't care if my [example](https://groups.google.com/group/chocolatey/attach/20d81a049cc4e/test.nuspec?part=0.1&authuser=0&view=1) gets used or not. What I'd like to see is the default template created by choco new become "edit friendly." By this I mean that all instructions and help get commented above or below the element tag and the element tag is left alone to be filled in without having having to hit the backspace 50 times and then retyping in the ">." :)
 
**As a new alternative, and I'm starting to like this idea even better, is have the top of the file be a blank template ready to fill in. This top part has nothing that needs to be edited out or changed at all. (No damn select and cut! No damn backspacing!) The template would be ready to start accepting pasted in information. Below that, could be one big huge commented out section which has a general overview followed by specific elemental tag details and possibly an example for each.**

In my [first suggestion](https://groups.google.com/group/chocolatey/attach/20d81a049cc4e/test.nuspec?part=0.1&authuser=0&view=1), the pro is that it's easier to edit and the reference information is where you need it. The con is that the packager needs to edit out multiple portions to clean up the file (but MUCH easier than the amount of editing out as it's presented now).

In the latter suggestion, the pro is that it's faster for packagers that remember what the elements are to enter the information quickly and it's only one quick select and cut to clean up the file. The con is that packagers less familiar with the  information they need to enter will be scrolling up and down a lot.

Either way. --->IMHO<--- the generated file really needs to be more "edit friendly."

**Comment by bcurran3** [comment]
No Enhancement tag yet? :)

**Comment by ferventcoder** [comment]
You know you can create your own templates right? 👍

**Comment by ferventcoder** [comment]
> I'm a Pro user, does this qualify for a Customer tag? :)

It could, but those are typically found with bugs or high priority things. This has a fantastic documented way of doing this now, that let's folks customize new package creation just for them. Everyone is going to have a different preference so we optimize the default template for new packagers.

**Comment by ferventcoder** [comment]
@bcurran3 you can also replace the default template so you don't need to pass template name, just put one into the templates folder named "default".

**Comment by bcurran3** [comment]
> @bcurran3 you can also replace the default template so you don't need to pass template name, just put one into the templates folder named "default".

> I do! 👍 I have a custom default for generation and at least 8 specific ones, BUT this is still a big pet peeve for me even though I don't use the default one any more. :)

I'm still a big fan of the concept of having an easily editable base choco new template with no comments anywhere near the actual edit fields and then having a completely separate "tutorial" section at the bottom.

I'm not sure what is actually set as the milestone, but people who like my concept (or not) please VOTE!

**Comment by TheCakeIsNaOH** [comment]
I've been playing around with ideas for this. I'm thinking it might be better to have two built in templates. The current default one, and the one suggested in this issue. Perhaps they could be called `standard` and `slim`? Then the one that is selected as default could be copied to the `default` folder?

**Comment by TheCakeIsNaOH** [comment]
After discussion with @gep13, this is something that should be added to the community templates instead of directly into choco.
https://github.com/chocolatey-community/chocolatey-templates/issues/15

**Comment by TheCakeIsNaOH** [comment]
As mentioned in the comment above, it will be added as an installable template.
