### ISSUE TITLE
Support pinned options per package

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/choco#1372]
PROBLEM:
There are a number of programs that vendors make available via a static download link so that end users can always get the latest version when they go to the website and download the program, i.e. http://softwaresite.com/program.exe. Chocolatey package maintainers then use this link when no version specific download link is available for the program. Examples of some of my packages include: drivermax, resilio-home, resilio-business, utorrent, and a few others. Many times a package maintainer can update their package for a new release of the software only to not know the very next day the vendor has updated the program and thus invalidated the Chocolatey package while sitting in moderation and the package fails installation for Chocolatey end users due to the checksums being wrong for the latest version of the program. This comes up prominently when Chocolatey users don't "cup all" frequently. Some Chocolatey users may only "cup all" once a week or even once a month to find that many packages have been updated and available only to find that many won't install because the program has been updated to a newer version than the package.

(Chocolatey Pro) I run "cup all" frequently. Every time I "cup all" and there is a new version of a package such as sysinternals that fails the virus check, I have to manually run "cup all --skip-virus-check" or "cup sysinternals --skip-virus-check" to get the updated program/s installed.

Basically I need to run cup 3 times to get all my packages/programs updated at times. Sysinternals just failed me twice due to needing --skip-virus-check and --ignore-checksums to install.

SOLUTION:
Have choco store and use "pinned options" for specified packages.

In the case of drivermax, the resilio packages, and utorrent, users could pin the option "--skip-virus-check" and it would update every time even if they have 1.1 installed, 1.2 is the latest package, and 1.3 is the current version. (All assuming that that the packages get updated at some sort of normal rate even if they lag behind the current version.) 

In the case of sysinternals I could pin "--skip-virus-check" and "--ignore-checksums" and, like the situation above, can install the latest version of the program released by the developer without problems in the situation of I have a version installed, the package has been updated since my installation but the package is still not up to date and ignore all the virus warnings and refusal to install based on the believed virus count to be higher than the choco default threshold.

END RESULT:
Joy under specific conditions.

p..s I understand this could be done globally, but package specific granularity would be nice.

**Comment by ferventcoder** [comment]
This is quite similar to https://github.com/chocolatey/chocolatey-licensed-issues/issues/11

**Comment by bcurran3** [comment]
> This is quite similar to chocolatey/chocolatey-licensed-issues#11

I don't see the relationship, but if it's on the roadmap to solve the problem, I'm a happy camper.

**Comment by TheCakeIsNaOH** [comment]
I think this should be solved by enabling remembered arguments once #1547 is implemented?

**Comment by gep13** [comment]
I agree with @TheCakeIsNaOH assessment here. Going to go ahead and close this out.

If more discussion is needed, feel free to comment.
