### ISSUE TITLE
"Value cannot be null" running choco outdated

### ISSUE THREAD

**Issue by SaintGimp** [chocolatey/choco#1383]
### What You Are Seeing?
When I run "choco outdated", it always lists the first outdated package then exits with a "value cannot be null" error.

### What is Expected?
It should list all of my outdated packages.

### How Did You Get This To Happen? (Steps to Reproduce)
The command was working fine, then I removed and reinstalled a particular package (notepadplusplus with the -x86 option, if I recall correctly) and then this error began happening.  Note that it always errors out after listing the **first** outdated package.  It was erroring out after listing the "fiddler4" package, then I upgraded that one and now still it's erroring after listing the "lastpass" package.

### Output Log
This is with Chocolatey v0.10.7
https://gist.github.com/SaintGimp/4387a3415e40f36ced6118c8f3b9bb60

**Comment by SaintGimp** [comment]
The error is actually caused by enabling useRememberedArgumentsForUpgrades.  When I disable that feature the error goes away.  At a guess, I think it's because I have packages that were installed with Chocolatey 0.10.3 and don't have a .arguments file.

**Comment by ferventcoder** [comment]
@SaintGimp thanks for that - I think we have a good place to look for this issue.

**Comment by ferventcoder** [comment]
This will be fixed in 0.10.8.
