### ISSUE TITLE
choco push fails when running under Mono

### ISSUE THREAD

**Issue by agc93** [chocolatey/choco#1388]
### What You Are Seeing?

When running `choco.exe` under Mono 3.12.1, `push` fails to push a built package.

```
Attempting to push [...].nupkg to https://push.chocolatey.org
Error: SendFailure (Error writing headers)
```

Judging by the log output (below), this is most likely caused by the ancient version of Mono used by Chocolatey. 

That being said, since `choco.exe` (rightly) refuses to let you use a `http` URL to push to the community feed, this totally breaks package push on Mono.

### What is Expected?

The package should be pushed.

### How Did You Get This To Happen? (Steps to Reproduce)

1. Build and run `choco` under Mono 3.12.1 
2. Use `choco` to pack a new `nupkg` file
3. Run `choco push` (i.e `choco push -y -f --source https://push.chocolatey.org -k <key-here>`)

> You can use the [agc93/mono-choco](https://hub.docker.com/r/agc93/mono-choco/) Docker image ([Dockerfile](https://hub.docker.com/r/agc93/mono-choco/~/dockerfile/)) to quickly test

### Output Log

[Gist of output](https://gist.github.com/agc93/738ec951eb8892108ad608598efb25aa)

**Comment by ferventcoder** [comment]
Thanks for logging that.

**Comment by agc93** [comment]
@ferventcoder As a workaround, is it possible to just use `nuget push` with the same source and key?

Given `choco` doesn't run on Mono 4.x or 5.x and I can't push by `http`, this blocks package push on Linux platforms :confused:

**Comment by ferventcoder** [comment]
You can just use nuget push (not sure on versions greater than 3.5 but it may just work).

With choco, you can do `choco push --force -source http://chocolatey.org/ -k <apikey>`

**Comment by agc93** [comment]
Tried `nuget push` and got the same problem (with NuGet 2.8.3) so still looks likely to be Mono-specific. Are there any plans to update to a vaguely recent Mono version?

**Comment by ferventcoder** [comment]
@agc93 yes... it's up for grabs to determine why it errors and send in those PRs. 👍

**Comment by petemounce** [comment]
Linking #1020, #1388, #1002, #369 as relating to building for newer mono versions than 3x.

**Comment by rekire** [comment]
This issue is caused by https://github.com/chocolatey/chocolatey.org/issues/584

**Comment by ferventcoder** [comment]
This should be resolved by the changes made for https://github.com/chocolatey/chocolatey.org/issues/584
