### ISSUE TITLE
Get-WebFile throws errors when it doesn't have write permission

### ISSUE THREAD

**Issue by thigg** [chocolatey/choco#139]
0.9.9-rc9
Chocolatey is trapped in a loop. Didn't analyze so far what is the issue with the packet.
Example: eclipse-java-luna

	 At C:\ProgramData\chocolatey\helpers\functions\Get-WebFile.ps1:105 char:11
	 +           $writer.Write($buffer, 0, $count);
	 +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		 + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
		 + FullyQualifiedErrorId : InvokeMethodOnNull
	 You cannot call a method on a null-valued expression.
	 At C:\ProgramData\chocolatey\helpers\functions\Get-WebFile.ps1:105 char:11
	 +           $writer.Write($buffer, 0, $count);
	 +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		 + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
		 + FullyQualifiedErrorId : InvokeMethodOnNull
	 You cannot call a method on a null-valued expression.
	 At C:\ProgramData\chocolatey\helpers\functions\Get-WebFile.ps1:105 char:11
	 +           $writer.Write($buffer, 0, $count);
	 +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		 + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
		 + FullyQualifiedErrorId : InvokeMethodOnNull
	 You cannot call a method on a null-valued expression.
	 At C:\ProgramData\chocolatey\helpers\functions\Get-WebFile.ps1:105 char:11
	 +           $writer.Write($buffer, 0, $count);

**Workaround:**  if you specify a different location for cache other than temp, make sure it exists and you have permission to write to the directory.

**Comment by thigg** [comment]
Had it yesterday with an other packet too, reported it to the packet owner, but forgot which.
This time it was mine, got a report, that there is an issue with forwards to ftp downloads

**Comment by ferventcoder** [comment]
Weird - how big is the package download? Large?

**Comment by thigg** [comment]
it is eclipse, so... 250mb or smth?

Am 02.03.2015 um 16:26 schrieb Rob Reynolds:

**Comment by thigg** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/7593137/6442700/577edeb8-c0fa-11e4-9808-7accdd6a5826.PNG)

**Comment by thigg** [comment]
According to my network adapter I would say it downloads

**Comment by ferventcoder** [comment]
What rc?

On Monday, March 2, 2015, thigg <notifications@github.com> wrote:

> According to my network adapter I would say it downloads
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/139#issuecomment-76722467>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by thigg** [comment]
0.9.9-rc9

**Comment by ferventcoder** [comment]
downloads the whole thing if you let it continue or it just errors?

**Comment by thigg** [comment]
![image](https://cloud.githubusercontent.com/assets/7593137/6446928/2af3d034-c117-11e4-9a60-22743669d094.png)
looks like something is messed up with the pathes

**Comment by ferventcoder** [comment]
It appears $writer is null.

**Comment by thigg** [comment]
tries to write do C:\bin, I guess there is something wrong with the path prefix. Then it gets no access to write to the dir.
I suppose it should check if it has write access to the dir once before downloading the file and throw an error if not

**Comment by ferventcoder** [comment]
Ah this is helpful.

On Tuesday, March 3, 2015, thigg <notifications@github.com> wrote:

> tries to write do C:\bin, I guess there is something wrong with the path
> prefix. Then it gets no access to write to the dir.
> I suppose it should check if it has write access to the dir once before
> downloading the file and throw an error if not
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/139#issuecomment-76901547>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
Once you grant the correct permissions all is good?

**Comment by thigg** [comment]
don't know how (and why) I should  give permission to c:\bin. Actually it would be interesting to investigate why it wants to write there.

**Comment by ferventcoder** [comment]
@thigg did you not set the cachedirectory there?

**Comment by ferventcoder** [comment]
Perhaps the package is trying to write there? Something would have told it c:\bin

**Comment by thigg** [comment]
okay, that is weird. Package is probably one of my first:

 	  $binRoot = "$env:systemdrive\"
	  ### Using an environment variable to to define the bin root until we implement configuration ###
	  if($env:chocolatey_bin_root -ne $null){$binRoot = join-path $env:systemdrive $env:chocolatey_bin_root}
	  $installDir = Join-Path $binRoot $package
	  $zipUrl = 'http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/luna/R/eclipse-java-luna-R-win32.zip&r=1'
	  $zip64Url = 'http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/luna/R/eclipse-java-luna-R-win32-x86_64.zip&r=1'

	  Get-ChocolateyWebFile "$cname" "${binRoot}\eclipse.zip" "$zipUrl" "$zip64Url"

**Comment by ferventcoder** [comment]
Well, it could technically be a bug as well. I just pushed a commit to be sure the directory is available.

**Comment by thigg** [comment]
But a bug in the package, not in chocolatey?

**Comment by ferventcoder** [comment]
Well possibly an enhancement to Chocolatey then?

**Comment by ferventcoder** [comment]
unexpected result == bug?

**Comment by thigg** [comment]
do you mean the check-path thing, or the thing that the package actually wants to write to c:\bin?

**Comment by thigg** [comment]
Ah sorry, wasn't able to follow you. I meant by "its not a bug its a feature", the skript, not chocolatey.
I was confused why the skript wants to write to c:\bin and thought it's a problem with some env vars, maybe caused by a bug. But it wants to write there, so its a feature ;)

**Comment by ferventcoder** [comment]
I corrected the looping problem. So it will fail immediately.
