### ISSUE TITLE
Network share source with version arg does not work 

### ISSUE THREAD

**Issue by oj87** [chocolatey/choco#1391]
### What You Are Seeing?
Command: install  Testpackage  -y --version 14.0.0 -source p:\

Result:
Testpackage not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: "14.0.0"
 Source(s): "p:\"

Choco version: v0.10.7

### What is Expected?
Installation. Package exist. This command gives me the correct result: choco list testpackage --allversions -source p:\
Result: 
Testpackage 14.0.0
1 packages found.

### How Did You Get This To Happen? (Steps to Reproduce)
choco install Testpackage  -y --version 14.0.0 -source p:\
### Output Log
Easy to reproduce, no log needed.

**Comment by ferventcoder** [comment]
> Easy to reproduce, no log needed.

Easy to reproduce for you does not equate to easy to reproduce for us. So please provide the log when you get a chance. Thanks!

**Comment by ferventcoder** [comment]
And this is going to sound weird, what do you get with `choco list testpackage -s p:\` (the trailing slash here may be important).

**Comment by oj87** [comment]
Yes, sorry.. I later realized that I didn’t even leave all the necessary information at all. The source is a network share with a simple copy from chocolateys lib:s folder. P:\ is a mapped network drive, but I also tested this locally, and it doesn’t work either.

choco list testpackage -s p:\ gives me all packages from that source correctly.

I’ve seen though that some packages paths in libs are the package name, and others are stored with the package name and also the version. The version command doesn’t work with packages when the path (in libs) is only the package name.

Maybe this shouldn’t work at all, I don’t know.

**Comment by ferventcoder** [comment]
@oj87 When it comes to network shares, you also can't use them with services that run under LocalSystem by default. 

* Puppet / Chef - change the service to another username that has network access
* DSC - impersonate, you can't change away from LocalSystem

**Comment by oj87** [comment]
I understand, this was not the case. I am using the cmd.

**Comment by ferventcoder** [comment]
So the layout of the nupkgs is that they should all be in the same folder, then things will work appropriately. No subfolders, only nupkg files.

**Comment by oj87** [comment]
I see, that's sad. Wish that I could just use a copy of chocolateys libs.

**Comment by ferventcoder** [comment]
Not sad, that's how it works. We should probably be sure that is mentioned at https://chocolatey.org/docs/how-to-host-feed#local-folder-unc-share-cifs

**Comment by oj87** [comment]
Well I understand your point, but why wouldn’t it work? Chocolatey already handle that stuff, but in its own lib. So that’s not so super strange to assume.

**Comment by ferventcoder** [comment]
If you look in the "$env:ChocolateyInstall\lib" folder, you will notice none of the packages there have the version as part of the name (e.g. `pkgname.1.0.0.nupkg`). However, that is the file format you get with `choco pack` and what is expected on remote sources. 

It's likely that with the version number removed, you can inspect to find out what version is there, but you can't specify `--version` as part of attempting to use that package for install/upgrade.

If you use nupkgs with full names (version included, required), then it should work appropriately.

**Comment by oj87** [comment]
Sorry, not following you. I have multiple packages in my lib folder with both path and nupkg with version specified. If the path is including the version number, the nupkg does too.

**Comment by ferventcoder** [comment]
@oj87 older choco installation? What was the first version of choco that you had installed here?
Or did you install some packages with `-m`?

**Comment by oj87** [comment]
Yes, i have some packages installed with -m arg. Newest stable release.

**Comment by ferventcoder** [comment]
Either way, only packages in a very particular format will work here for subfolders, and otherwise without. We suggest using the non-subfolder format until we publish another way.

**Comment by oj87** [comment]
Yes, will do. Just saying that it should not be too hard to implement since choco already does this. With its own lib.

**Comment by ferventcoder** [comment]
@oj87 it's unlikely that we will support the lib folder format - the local lib is a special folder treated differently than "remote" sources.
