### ISSUE TITLE
Get-PackageParameters command

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1393]
Bring Get-PackageParameters into Chocolatey itself. All of the other elements are already in Chocolatey, so this should be supported in Chocolatey as well.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/wiki/HelpersGetPackageParameters

**Comment by AdmiringWorm** [comment]
@ferventcoder just noticed the labels now (`Pro/Business`), will the package parameters only be available for the licensed edition of choco?

**Comment by ferventcoder** [comment]
@AdmiringWorm no, it's supporting a pro/business feature. Sorry for confusion.

**Comment by ferventcoder** [comment]
I should probably remove it since it is more of an indirect support.
