### ISSUE TITLE
[API] Please make log4net dependency less restrictive

### ISSUE THREAD

**Issue by sxmanton** [chocolatey/choco#1395]
The dependency is currently set as a strict requirement of = v2.0.3.

I'm blocked on some work trying to use the API in conjunction with other package with higher version dependencies of log4net. If there's no reason for it to be specifically v2.0.3, please change the dependency to a >= v2.0.3 instead.

Thanks!

**Comment by ferventcoder** [comment]
Thanks for logging this. There used to be a strict reasoning behind these things with log4net, but with newer versions using the same signing key it should no longer be an issue.

**Comment by ferventcoder** [comment]
This is completed for 0.10.8.
