### ISSUE TITLE
Space in uninstallation script breaks it

### ISSUE THREAD

**Issue by Borkason** [chocolatey/choco#1404]
In the wiki under [Uninstallation](https://github.com/chocolatey/choco/wiki/Uninstallation) there is a space character that breaks the script. Last space on the second line that begins like. Just after the `

```powershell
Remove-Item -Recurse -Force "$env:ChocolateyInstall" -WhatIf
[System.Text.RegularExpressions.Regex]::Replace( ` 
```

**Comment by ferventcoder** [comment]
Please file at https://github.com/chocolatey/choco-wiki. Thanks!
