### ISSUE TITLE
Attempt to work with different quoting styles that worked in previous client

### ISSUE THREAD

**Issue by thigg** [chocolatey/choco#141]
The currently working method to use the current path is "%cd".
At least here:
https://github.com/chocolatey/choco/wiki/CreatePackages#testing-your-package
The documentation suggestes '%cd%'

**From Rob: ** Some of the documentation was plain wrong and leaned towards cmd.exe - single tick marks have probably never worked in powershell.exe that I'm aware of. That's why the `'"stuff"'` (apostrophe followed by a double quote) in some parts of the documentation.

**Comment by RyanRoundhouse** [comment]
I almost went out the door with scripts that are now broken due to this.
Was the breaking of backwards compatibility on purpose?

**Comment by thigg** [comment]
I am not sure if it is broken or still a bug in chocolatey.
I think the best is if you talk to Rob about this:

https://gitter.im/chocolatey/choco


Am 03.03.2015 um 18:48 schrieb RyanRoundhouse:

**Comment by thigg** [comment]
I think this was not intentional, as far as I understand this is just the way Windows deals with cmd inputs. It seems to be different if the target is a posh-script

**Comment by ferventcoder** [comment]
@RyanRoundhouse this is a breaking change, not necessarily intentional. What did you have before? We can attempt to bring about something that will allow this to work with new choco.

**Comment by ferventcoder** [comment]
The problem here is we removed a bunch of layers. Before it was shim -> cmd -> powershell (jumping through hoops to ensure quotes made it all the way down). Now it is just shim -> exe.

**Comment by RyanRoundhouse** [comment]
I was using the same thing as thigg.  The documentation he linked to suggested using apostrophes around paths (ie: 'c:\program files (x86)\path\to local\store;http://chocolatey.org/api/v2/').

It now complains that the package cannot be found and it is checking:
Source(s): "'c:\program"

**Comment by thigg** [comment]
Would be nice to be backward compatible, also for scripts which are using chocolatey.

**Comment by ferventcoder** [comment]
agreed. Adjusted. this should be 0.9.9.1

**Comment by thigg** [comment]
So it should allow "test" 'test' and '"test'" (single, double and combined)

**Comment by ferventcoder** [comment]
Also keep in mind that we can only do so much here. There is a difference between how powershell handles and how cmd handles it.

**Comment by ferventcoder** [comment]
In some places we've already tried to cover that - powershell may have never handled single quotes.

**Comment by thigg** [comment]
But if the target is an exe file, we should be able to do the whole formatting as we like it, right?

**Comment by ferventcoder** [comment]
It should work as much the same way as before - I think the single tick marks would have only worked on cmd.exe - powershell would have stripped it right off.

**Comment by RyanRoundhouse** [comment]
I was using apostrophe, not a tick.

**Comment by ferventcoder** [comment]
> I was using apostrophe, not a tick.
Yeah sorry, I use those terms interchangeably (and technically incorrectly) meaning apostrophe. Backtick being something different.

**Comment by ferventcoder** [comment]
So chocolatey will properly handle apostrophes again.
