### ISSUE TITLE
Uninstall leaves empty folder behind

### ISSUE THREAD

**Issue by thdoan** [chocolatey/choco#1410]
### What You Are Seeing?
I thought one of the benefits of managing apps through Chocolatey is that it would ensure clean uninstallations. However, the first app I installed via Chocolatey left behind an empty folder when I uninstalled it. I wonder how many other apps will also leave behind empty folders when you uinstall them.

### What is Expected?
I expect uninstalls to be clean, leaving no visible traces of the uninstalled app behind.

### How Did You Get This To Happen? (Steps to Reproduce)
1. open cmd console (with admin rights)
2. enter `choco install paint.net`
3. enter `choco uninstall paint.net`

Empty folder left behind:
![image](https://user-images.githubusercontent.com/4110567/31001125-45b91e1e-a496-11e7-90d8-6c5caf3fdac3.png)

**Comment by ferventcoder** [comment]
It really depends on the package itself. If it is an installer package and the package does nothing additional over what the installer/uninstaller does, then it is going to be similar experience to manually managing the uninstall. In this case, I'm guessing that package is just an installer package that doesn't add additional logic over the installer itself.

**Comment by ferventcoder** [comment]
For a package that has the runtime binaries, you will see a much smoother experience with respect to cleanup automatically.

**Comment by thdoan** [comment]
Ah, so Chocolatey would go really well with portable apps :-). It would be awesome if the entire PortableApps.com library can be managed through Chocolatey.

**Comment by ferventcoder** [comment]
Chocolatey has a concept of portables that is slightly different than "portable apps". In effect yes, it would go quite nicely with those as well.
