### ISSUE TITLE
File renaming in Install-ChocolateyZipPackage

### ISSUE THREAD

**Issue by berndb84** [chocolatey/choco#1415]
### What You Are Seeing?
In **Install-ChocolateyZipPackage** line 202 the zip file is renamed from _$packageName_ to _($packageName)Install.zip_ 
`$downloadFilePath=Join-Path$tempDir"$($packageName)Install.$fileType"`

**Get-ChocolateyUnzip** adds a new textfile with this _($packageName)Install.zip_ filename in line 121
`$zipExtractLogFullPath= Join-Path $packagelibPath $zipFilename`.txt`

If you now want to uninstall the zip paket, the **Uninstall-ChocolateyZipPackage** function is only looking for _$packageName.txt_ (line 67) to remove all installed files.
` $zipContentFile=(join-path $packagelibPath $zipFileName) + ".txt"`

That doesn't work, because there is no Textfile with this name

**Comment by ferventcoder** [comment]
Looks like a bug.

**Comment by ferventcoder** [comment]
Merged into stable and will be released in 0.10.9.

**Comment by pradeeps** [comment]
I am not sure if the issue we are seeing is same, but we seems to be similar issue and we cannot upgrade to this version (0.10.9) as we don't have the password for proget website we have installed as the guy who did this left. Is there any possibility we can add this as a patch?

**Comment by ferventcoder** [comment]
@pradeeps it seems you have bigger issues. I'd suggest maybe setting up a new proget site or contacting Inedo for support on how you can get into a site when you run into issues like this - I am sure they will have something for you, even if it is just set up another ProGet repo. HTH
