### ISSUE TITLE
Incorrect documentation for Install-ChocolateyInstallPackage

### ISSUE THREAD

**Issue by tcase** [chocolatey/choco#1416]
Documentation for Install-ChocolateyInstallPackage is incorrect.  It contains the following example:

.EXAMPLE
>
Install-ChocolateyInstallPackage -PackageName 'bob' -FileType 'exe' `
  -SilentArgs '/S' `
  -File "$(Split-Path -Parent $MyInvocation.MyCommand.Definition)\bob.exe" `
  -ValidExitCodes = @(0)

The -ValidExitCodes should not have the "=" in it

**Comment by danyelcampbell** [comment]
Looking to get into helping in open source! This seems like an easy fix, mind if I fix this?

**Comment by ferventcoder** [comment]
@danyelcampbell not at all, the code is at https://github.com/chocolatey/choco/blob/9c0a77d0cec04a38c2be7c8a74ab337dc1353ceb/src/chocolatey.resources/helpers/functions/Install-ChocolateyInstallPackage.ps1#L141-L144.

Please make sure you read over all of https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md first. There are some important details in there, especially surrounding how to form your commit messages.

**Comment by danyelcampbell** [comment]
I've changed it and did my commit, however, I'm having issues pushing it. I'm getting "unable to access 'https://github.com/chocolatey/choco.git/': The requested URL returned error: 403" I've googled it with no successful results.... ):

**Comment by tiget** [comment]
@danyelcampbell be sure to read over https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md. You'll need to create a fork

**Comment by danyelcampbell** [comment]
I've already created my fork and made the commit. I'm trying to push but when I do I get a permissions issue...working through that now..
