### ISSUE TITLE
how-to-deprecate-a-chocolatey-package page missing exclude files step

### ISSUE THREAD

**Issue by dhoer** [chocolatey/choco#1418]
Page https://chocolatey.org/docs/how-to-deprecate-a-chocolatey-package is missing a step to ignore all files after removing them.  Leaving files alone will result in package error.  Removing the files section will pull in .git files.  

Updating files section to the following will NOT fix the issue either:
```
<files>
    <file src="*\**" target="\" exclude=".git\**\*.*"/>
</files>
```

**Comment by dhoer** [comment]
Maybe you can't exclude in nuspec? https://github.com/NuGet/Home/issues/2847

If that is the case, then leave a file under tools folder?

**Comment by ferventcoder** [comment]
Think leave a file under the tools folder. Empty text file called deprecated?

Another option, remove the files section, but store the nuspec in a subfolder of your git repo. Then you won't run into it grabbing other files.

Also, once settled, file this at https://github.com/chocolatey/choco-wiki

**Comment by dhoer** [comment]
Opened https://github.com/chocolatey/choco-wiki/issues/69

**Comment by AdmiringWorm** [comment]
A third option that could be used, is to have an empty files element.

```
<files>
</files>
```
That will prevent any file to be included with the package. That is what I usually use when creating meta packages, so the package doesn't include the AU update.ps1 file.

**Comment by dhoer** [comment]
@AdmiringWorm that worked! Thanks.  Also tested to see if `<files />` worked, and it did.  Updating wiki issue.
