### ISSUE TITLE
[shimgen] no error written to standard error on error

### ISSUE THREAD

**Issue by RyanRoundhouse** [chocolatey/choco#142]
new with 0.9.9, when you launch a process to install a chocolatey package and an error occurs (my example is 'elasticsearch not installed. The package was not found with the source(s) listed.'), it no longer writes anything to standard error.

It used to do this properly before 0.9.8.  Is it on purpose that in 0.9.9 you need to parse standard output in order to detect an error?

**Comment by ferventcoder** [comment]
Interesting. I would think log4net would do that properly.

**Comment by ferventcoder** [comment]
Can you expand on this a bit more?

**Comment by ferventcoder** [comment]
So the exit code should be non-zero. That's a start. The other side of this is that it should be writing to stderr for things that are logged as errors.

**Comment by RyanRoundhouse** [comment]
In a C# application, I launch a new process that uses chocolatey to install a package and capture StandardOutput and StandardError.  
If anything was written to StandardError, it would detect and log an error, blocking the program from continuing.
Previous to 0.9.9, this was working.  Now with 0.9.9, this no longer works.

**Comment by ferventcoder** [comment]
Dumb question, are you calling the shim?

**Comment by RyanRoundhouse** [comment]
hrm.  I might be.  I'm calling cinst.exe

**Comment by ferventcoder** [comment]
This isn't new to choco 0.9.9 then :)

**Comment by ferventcoder** [comment]
What version of choco did you have in place before?

**Comment by RyanRoundhouse** [comment]
0.9.8.33.

**Comment by ferventcoder** [comment]
the shims there would have been wrong as well though.

**Comment by RyanRoundhouse** [comment]
let me double check this.  I hope I haven't been wasting your time....

**Comment by ferventcoder** [comment]
I wonder if there was something else in the path then...

**Comment by ferventcoder** [comment]
No it's good. The shims should properly output stderr to stderr.
