### ISSUE TITLE
Chocolatey parsing package versions incorrectly

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/choco#1420]
### What You Are Seeing?

Chocolatey parses https://chocolatey.org/packages/ammyy-admin/3.5.20161203 as a newer version than https://chocolatey.org/packages/ammyy-admin/3.5.6.

i.e. 3.5.6 > 3.5.20161203

### What is Expected?

3.6 should be the latest available and default package for install, not 3.5.20161203

### How Did You Get This To Happen? (Steps to Reproduce)

Look at the https://chocolatey.org/packages/ammyy-admin/ page or do choco install ammyy-admin.

I have de-listed the 3.5.20161203 package which solves new installs, but Chocolatey won't upgrade previous 3.5.20161203 installs. The delisting solves upgrades from 3.5 but not 3.5.20161203.

### Output Log

C:\WINDOWS\system32>cinst ammyy-admin --version 3.5.20161203
Chocolatey v0.10.8 Professional
Installing the following packages:
ammyy-admin
By installing you accept licenses for the packages.
Progress: Downloading ammyy-admin 3.5.20161203... 100%

ammyy-admin v3.5.20161203 [Approved]
ammyy-admin package files install completed. Performing other installation steps.
 ShimGen has successfully created a shim for AA_v3.exe
 The install of ammyy-admin was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

C:\WINDOWS\system32>cup ammyy-admin
Chocolatey v0.10.8 Professional
Upgrading the following packages:
ammyy-admin
By upgrading you accept licenses for the packages.
ammyy-admin v3.5.20161203 is newer than the most recent.
 You must be smarter than the average bear...

Chocolatey upgraded 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

C:\WINDOWS\system32>cinst ammyy-admin -version 3.5.6
Parsing -version resulted in error (converted to warning):
 Cannot bundle unregistered option '-e'.
Chocolatey v0.10.8 Professional
Installing the following packages:
ammyy-admin
By installing you accept licenses for the packages.
A newer version of ammyy-admin (v3.5.20161203) is already installed.
 Use --allow-downgrade or --force to attempt to install older versions, or use side by side to allow multiple versions.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - ammyy-admin - A newer version of ammyy-admin (v3.5.20161203) is already installed.
 Use --allow-downgrade or --force to attempt to install older versions, or use side by side to allow multiple versions.

(I relisted 3.5.20161203 temporarily for this)

### Suggested Fix

Chocolatey should append .0 or .0.0 as necessary when parsing versions.

**Comment by ferventcoder** [comment]
It's actually doing it correctly. Split the version segments by the dots and look at the numbers. Bigger numbers win. 

It's not decimal based - `6` is MUCH smaller than `20161203`.

**Comment by ferventcoder** [comment]
You must be very careful with versioning. What you are seeing is why we suggest you would use the fourth segment ONLY for package fix version notation. It should have been set as `3.5.0.20161203`, where it was like a correction for `3.5`. Then `3.5.6` would have just worked appropriately as 0 is less than 6. 

We don't have epochs to fix these kinds of situations, I wonder why this was not picked up by moderators before.

**Comment by bcurran3** [comment]
NOW I know! Danke.
