### ISSUE TITLE
Getting While Installing Git

### ISSUE THREAD

**Issue by Mugesh-Rajaram** [chocolatey/choco#1421]
Hi,

 I have installed git using the command **choco install git** in powershell, after the installation i gave yes 
to install the script and i got error. Can anyone one help on this.
![capture](https://user-images.githubusercontent.com/16976667/31319121-590aa464-ac7b-11e7-8eab-e489543df36f.PNG)

**Comment by ferventcoder** [comment]
@Mugesh-Rajaram likely it is an issue with the package itself. You should also look at the detailed log file like the output states ("c:\ProgramData\chocolatey\logs\chocolatey.log"), that is where the most answers are going to be. 

Apologies on not responding sooner, hopefully the template for the issue when you went to create this gave you more information on where to go when you are running into a package issue (the community repository and to the group that makes that package specifically).
