### ISSUE TITLE
Chocolately integration with SCCM 1702

### ISSUE THREAD

**Issue by IvoAps** [chocolatey/choco#1424]
Good day! I tryed  integrate Chocolately in SCCM ( Win 2016 server & SCCM 1702 on VMWARE virtual machine 6.5 ) with PS module,found on https://github.com/kubasiatkowski/SCCMChoco  

Followed step by step to manual,but,unfortunately ,when trying to download applications  with  Add-SCCMChocoApplication -chocourl  ,
I got warning message 
"Checking Chocolatey installer: Adding Chocolatey installer to SCCM
WARNING: The specified file is not a valid image file." 

(please also found screenshot attached bellow) 

Tell me ,please, any ideas ,what can be  wrong also,where I can found some log files related to that situation ?? Thanks to everybody in advance!

![chocolately](https://user-images.githubusercontent.com/32680121/31450042-19911290-aeb1-11e7-8f30-14a446b94618.jpg)

**Comment by ferventcoder** [comment]
It may be a great idea to start by asking at that repo. @kubasiatkowski might have some details for help as well.

**Comment by kubasiatkowski** [comment]
Definitely it should be asked in my repo. 
There is already issue open: https://github.com/kubasiatkowski/SCCMChoco/issues/1#issuecomment-335750186
