### ISSUE TITLE
Print contents of chocolatey.log to end of log of automated validation.

### ISSUE THREAD

**Issue by monty241** [chocolatey/choco#1430]
Split off from #1413.

The automated validation when a new package is uploaded raises an MSI 1603 error as shown at the end. 

Since the automated validation is done on a server to which I have no access, I can not check the real cause. It might be a reboot pending due to dotnet47 dependency.

When the package is installed from the unlisted location or from a file in a folder as source, it installs without problems.

I've understood that the current recommendation is to ask the moderator to ignore the failed validation. However, that increases processing time considerably (at least two weeks).

### Suggested Change

Print the contents of `C:\ProgramData\chocolatey\logs\chocolatey.log` to the logging of the automatic validation.

### Output Log
````
/norestart /l*v "C:\Users\Administrator\AppData\Local\Temp\chocolatey\invantive-estate-for-outlook-17.10.7-msi-install.log" ] exited with '1603'.
2017-10-11 17:57:56,300 2716 [ERROR] - ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "C:\Users\Administrator\AppData\Local\Temp\chocolatey\invantive-estate-for-outlook\17.10.7\Invantive Estate for Outlook-17.10.7.msi" /qn /norestart /l*v "C:\Users\Administrator\AppData\Local\Temp\chocolatey\invantive-estate-for-outlook-17.10.7-msi-install.log" ] was not successful. Exit code was '1603'. See log for possible error messages.
 at Start-ChocolateyProcessAsAdmin, C:\ProgramData\chocolatey\helpers\functions\Start-ChocolateyProcessAsAdmin.ps1: line 276
at Install-ChocolateyInstallPackage, C:\ProgramData\chocolatey\helpers\functions\Install-ChocolateyInstallPackage.ps1: line 271
at Install-ChocolateyPackage, C:\ProgramData\chocolatey\helpers\functions\Install-ChocolateyPackage.ps1: line 336
at <ScriptBlock>, C:\ProgramData\chocolatey\lib\invantive-estate-for-outlook\tools\chocolateyinstall.ps1: line 19
at <ScriptBlock>, C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1: line 48
at <ScriptBlock>, <No file>: line 1
````
After that it reports:
````
Chocolatey installed 4/6 packages. 2 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
````

**Comment by ferventcoder** [comment]
@monty241 I like this - you should file this at https://github.com/chocolatey/package-verifier.

**Comment by monty241** [comment]
Thanks, created there as https://github.com/chocolatey/package-verifier/issues/60.
