### ISSUE TITLE
choco and cup throw error about "suitable location for change.exe"

### ISSUE THREAD

**Issue by Godeke** [chocolatey/choco#1432]
### What You Are Seeing?
choco and cup throw error about suitable location for change.exe after upgrade to Fall update for Windows 10. Searching for change.exe I can only find references to a RDP management command.

### How Did You Get This To Happen? (Steps to Reproduce)
Enter either "choco" or "cup" command at admin powershell. Only "choco -h" works as expected (produces help output).

### Output Log
> choco
Chocolatey v0.10.8 Professional
Please run 'choco -?' or 'choco <command> -?' for help menu.
The registered delegate for type IEnumerable<ITask> threw an exception. Unable to find suitable location for change.exe. Searched the following locations: 'C:\WINDOWS\SysNative\change.exe; C:\WINDOWS\System32\change.exe'

**Comment by ferventcoder** [comment]
@Godeke I take it you have joined the mailing list at https://groups.google.com/forum/#!forum/chocolatey-announce and have upgraded to 1.12.6. That's interesting it is throwing that error, that should only be run when you are using Remote Desktop, but also it shouldn't throw an error (should error silently).

This is actually a licensed extension bug, so let's move it over to https://github.com/chocolatey/chocolatey-licensed-issues

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/chocolatey-licensed-issues/issues/30

**Comment by ferventcoder** [comment]
Managing this over in the licensed repository.

**Comment by ferventcoder** [comment]
A fix for this has been released.
