### ISSUE TITLE
Config: Setting to exempt packages from upgrade all

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1433]
Instead of needing to pass an exemption list, it may be a good idea to opt out packages entirely from the upgrade all (like the chocolatey-agent).

* config setting name: upgradeAllExceptions
* Config Setting Description: Upgrade All Exceptions - A comma-separated list of package names that should not be upgraded when running 'choco upgrade all'. Defaults to empty. Available in 0.10.13+.

On the other setting for Except  in ChocolateyUpgradeCommand, that should mention the items passed here will be appended to the default list based on config setting `upgradeAllExceptions`.

**Comment by ferventcoder** [comment]
Then those can be upgraded on a different schedule.

**Comment by mkevenaar** [comment]
@ferventcoder with `choco pin [mypackage]` you would have the same effect, I think.

**Comment by ferventcoder** [comment]
@mkevenaar this could also work, but those should not upgrade unless the pin is removed.

**Comment by ferventcoder** [comment]
This likely suffers from the same issue as a dependency that was noted - #1821

**Comment by ferventcoder** [comment]
This is completed for 0.10.14.
