### ISSUE TITLE
Allow multiple sources of dependences

### ISSUE THREAD

**Issue by dimqua** [chocolatey/choco#1434]
Please add support for multiple sources of the same dependency. I can provide an example if you wish.

**Comment by ferventcoder** [comment]
An example would be great. I think I'm starting to understand what this might mean but not fully sure so the more info the better.

**Comment by dimqua** [comment]
Something like this:
```
<dependencies>
    <dependency name="mypackage" id="package1" version="1.1" priority="1" />
    <dependency name="mypackage" id="package2" version="1.0" priority="0" />
</dependencies>
```
Both package1 and package2 are provide the same dependency (mypackage), and both can be used. If user doesn't have any "mypackage" source installed, "package1" will be used, since it has bigger priority number.

**Comment by ferventcoder** [comment]
This is similar to the concept of virtual packages:

Two packages provide pdf_reader capabilities (or ***provides*** it). That would be like foxit and adobe reader. Your package says depend on something that provides a pdf_reader and the package manager sees you have a pkg installed already that provides it or it will install one of them. The nice thing about keeping what provides outside of the package mentioning the dependency is that preferences would be able to be set globally and per client and could change without requiring repackaging.

**Comment by ferventcoder** [comment]
#858

**Comment by ferventcoder** [comment]
Also, once you explained this, it was completely different than where I thought this request was going.
