### ISSUE TITLE
[Feature Request] Remove From Chocolatey Without Uninstalling

### ISSUE THREAD

**Issue by zero77** [chocolatey/choco#1437]
Can you please add the option to remove a package from Chocolatey but, without uninstalling it from the OS.

Thanks

So you can switch to different builds like, stable to a beta build.

**Comment by AdmiringWorm** [comment]
something like this for instance:
`choco uninstall -n --skipautouninstaller` (that is actually something that's working right now).

the `-n` switch disables the running of the uninstall script, and the `--skipautouninstaller` as it implies skips the running of the auto uninstaller.

**Comment by ferventcoder** [comment]
As Kim mentioned, this already exists, so I am going to preemptively close this. 

If you have other ideas in how this would show up for the user as an interface, explain them here and we can reopen this issue for more discussion.

**Comment by zero77** [comment]
@AdmiringWorm 
Thanks I will give that a try.

@ferventcoder 
I wasn’t thinking of the GUI although, adding a graphical option for this, I imagine would be much appreciated by users of the GUI.

Perhaps, just something simple like an option on the right click menu.
That then runs the `choco uninstall -n –skipautouninstaller` command against the selected package.
