### ISSUE TITLE
Auto uninstall skipped (No registry snapshot)

### ISSUE THREAD

**Issue by dnx4015** [chocolatey/choco#1440]
### What You Are Seeing?
A succesful uninstall of a zip package that leaves all the unziped files at the Destination directory

### What is Expected?
Auntomatic Uninstall that deletes these files from Destination directory

### How Did You Get This To Happen? (Steps to Reproduce)

Create a 1.0.0 package that contains a zip file and a `chocoinstall.ps1` that unzips it to a specified directory. 
Use `choco uninstall`, which returns a successful message that contains the following line:
`Skipping auto uninstall - No registry snapshot` 
I have looked for the .registry file and indeed it does not exist.
I am using chocolatey 0.10.8

[Install log](https://gist.github.com/dnx4015/c21dad134d9413c07a6ae53f59a97469)
[Uninstall log](https://gist.github.com/dnx4015/3c155c1f48d34c82647d82c0594b072e)

**Comment by ferventcoder** [comment]
@dnx4015 Just a couple of notes and then let's talk about a possible future state.

### Current State

* AutoUninstaller does not apply to things that don't use native installers - AutoUninstaller only applies to Installer Packages (packages that manage natively installed software into Programs and Features). They don't apply to Zip packages. 
* If you unzip into the packaging directories (for reference, `$env:ChocolateyInstall\lib\<package_id>`), it will automatically remove the files on uninstall. 
* If you are unzipping outside of the packaging directory (looks like Program Files from the logs), you need to include a "chocolateyUninstall.ps1" with `Uninstall-ChocolateyZipPackage` (https://chocolatey.org/docs/helpers-uninstall-chocolatey-zip-package). 

Once you are using `Uninstall-ChocolateyZipPackage`, you are likely to run into #1415 tho, so be aware.

### Future State

* The auto uninstaller will still only apply to the natively installed software in Programs and Features.
* We are looking to capture more information about what a package installs, like in locations outside of the packaging directories
* We could expand the uninstallation of packages to look at all files it is managing, including those outside of the packaging directories and give the option of cleaning them up as well.

This is a ways off, so please look to address current state in your packaging.
