### ISSUE TITLE
access choco from python

### ISSUE THREAD

**Issue by pradeeps** [chocolatey/choco#1449]
Is there a way to access choco and all related commands from python? 

I mean is there any extension for this ?

**Comment by ferventcoder** [comment]
@pradeeps typically folks are doing this now by calling the process and parsing the output. A good place to see this is in Ansible.

**Comment by ferventcoder** [comment]
By the way, questions are best asked in a different avenue as indicated in the issue template:

DO NOT CREATE AN ISSUE FOR A QUESTION - questions are better served as email or chat.
- email - http://groups.google.com/group/chocolatey
-  chat - https://gitter.im/chocolatey/choco
