### ISSUE TITLE
Add Generate-BinFile as it was widely used

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#145]
Even though it was never part of the API at all.

https://github.com/chocolatey/chocolatey/issues/202

**Comment by gep13** [comment]
Seems that there was some additional work around this area as well, namely:

https://github.com/chocolatey/chocolatey/pull/287
https://github.com/chocolatey/chocolatey/pull/449

With regard to 287, the function was actually going to be renamed.  I am guessing that this isn't required, right?

And with regard to 449, there was also a Remove-BinFile.  Should this be brought into Chocolatey vNext as well?
