### ISSUE TITLE
Links for Chocolatey teams in CREDITS.txt need updating

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/choco#1450]
Some links in \ProgramData\chocolatey\CREDITS.txt are outdated:

https://github.com/orgs/chocolatey/teams/developers
https://github.com/orgs/chocolatey/teams/community-moderators
https://github.com/orgs/chocolatey/teams/community-maintainers

The above result in a 404 error.

**Comment by ferventcoder** [comment]
I take it you can't see these?

**Comment by gep13** [comment]
@ferventcoder those links work for me, but when using incognito mode, I am prompted for GitHub permissions.

**Comment by bcurran3** [comment]
Very weird. I still get 404's.
I'm logged in to Github in Chrome and get 404's.
I just ran Firefox and tried a link, it prompted to login, did, then 404.

Does github.com resolve to 192.30.255.112 for you?

**Comment by gep13** [comment]
@bcurran3 I think the issue here is that your user doesn't have the access rights to view the team members.

**Comment by ferventcoder** [comment]
I think that is correct, which is actually not that awesome. It means we will need to update this to contain names or find a link that works.

**Comment by bcurran3** [comment]
I'm guessing @gep13 is right. It makes sense now since GitHub requires login before attempting to show the links, thus they need to point somewhere public. Logout of GitHub and you will (not) see....

**Comment by gep13** [comment]
@ferventcoder I think this is why you see people creating there own, for example https://reactiveui.net/about/ (scroll down a bit).

**Comment by pauby** [comment]
I'm going to go ahead and close this, but we can reopen it if necessary.
