### ISSUE TITLE
Log backups are not clearing out after 50 backups

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1453]
It appears that the settings for the appender are ignoring the maximum number of backups, which is set to 50 in the code. Let's determine why it is not clearing them up and then make sure it starts. 

This is also related to #890

**Comment by mrhockeymonkey** [comment]
having a closer look i do see chocolateyx.log where x is 1-50 so perhaps this is working correctly. There is also choco.summary.x.log which goes from 1-30 on my machine. Id be happy to query some other boxes for more information if its helpful. 

But yes controlling this size (#890) would be ideal.

**Comment by ferventcoder** [comment]
@mrhockeymonkey ah good. Controlling the retention size might be doable. It's all in when configuration is applied, but I think we can retroactively apply the configuration changes to the log settings.

Converting this to not an issue and updating #890.
