### ISSUE TITLE
Package install path for non-admin

### ISSUE THREAD

**Issue by brucejo75** [chocolatey/choco#1454]
### Environment
- Windows 10 1703 (OS Build 15063.674)
- account: `admin` account type: administrator
- account: `bruce` account type: standard user

### Repro
1. log in as `bruce` a "standard user" account.
2. open a powershell window "as administrator"
3. `choco install meteor`

**Result:** meteor is installed to `C:\Users\admin\AppData\Local\.meteor`

**Expected:** meteor is installed to `C:\Users\Bruce\AppData\Local\.meteor`

### Issue

The meteor install looks up `%LOCALAPPDATA%` to determine where to install their package.  But `%LOCALAPPDATA%` is set by elevated powershell window to base off the `admin` user.

e.g.
```
PS C:\WINDOWS\system32> $env:LOCALAPPDATA
C:\Users\admin\AppData\Local
```

### Workaround
1. log in as `bruce` a "standard user" account.
2. open a powershell window "as administrator"
3. at command prompt `$env:LOCALAPPDATA = "C:\Users\Bruce\AppData\Local"`
4. `choco install meteor`

**Result:** meteor is installed to `C:\Users\Bruce\AppData\Local\.meteor`

### Recommendation
Update [Creating Chocolatey Packages](https://chocolatey.org/docs/create-packages#creating-chocolatey-packages) to warn about complications with using environment variables based on the user's name.  Because elevated permissions will set the name to base off the admin account.

Relevant environment variables:
- `USERNAME`
- `USERPROFILE`
- `APPDATA`
- `LOCALAPPDATA`

Let me know if this is appropriate, I can submit a PR with some words.

**Comment by ferventcoder** [comment]
This makes sense. Please submit.

**Comment by ferventcoder** [comment]
That will be at https://github.com/chocolatey/choco-wiki

**Comment by brucejo75** [comment]
merged.
