### ISSUE TITLE
Choco uninstall does not delete mypackage-0.5.2-py2.7.egg-info directory sometimes

### ISSUE THREAD

**Issue by pradeeps** [chocolatey/choco#1455]
### What You Are Seeing?
When we install mypackage 0.5.2 , it seems to have left the mypackage-0.5.1-py2.7.egg-info folder as in site-packages and also added mypackage-0.5.2-py2.7.egg-info to site-packages folder. Becuase of this, testcases added to 0.5.2 are not being identified. 

This is on 0.10.0 choco version. 

### What is Expected?
When I install choco install mypackage --version 0.5.2 , it should have uninstalled and deleted the folder 0.5.1` as well. But does not seem to do so. Uninstall happens but old folder does not get deleted

### How Did You Get This To Happen? (Steps to Reproduce)
This is on our client machines. Not sure if its something someone can reproduce.

But I can look at the logs... But is there any way it can delete any of the previous mypackage old folders ?

I just tried it again , but cannot reproduce this anymore

**Comment by ferventcoder** [comment]
This is on 0.10.8? or an older version?

**Comment by ferventcoder** [comment]
If you still want to work on this @pradeeps, we'd be happy to help you address this. Feel free to comment and we can reopen this. In the meantime, this looks like a package issue so I am going to close it as such.

**Comment by pradeeps** [comment]
@ferventcoder , hi, the issue is still present. We are using choco 0.10.0

**Comment by ferventcoder** [comment]
We'll need you to upgrade to the latest to verify if it is still an issue.

**Comment by pradeeps** [comment]
Thanks @ferventcoder the guy who installed this has left the company and we dont have the password for ProGet website. Is it still possible to upload the nup package of 0.10.9 and upgrade choco? is there any other way to  recover the password ? we have access to the server physically.

**Comment by ferventcoder** [comment]
As mentioned by others on Gitter, you should reach out to Inedo (ProGet) support and ask them how you would do that. They are likely the only folks who are going to be able to help with that. Your last resort is to stand up a new repository and migrate all of the packages from ProGet to that. HTH.
