### ISSUE TITLE
Install-ChocolateyEnvironmentVariable does't create expandable variables properly

### ISSUE THREAD

**Issue by jmusek** [chocolatey/choco#1457]
Create machine wide environment variables 'A' and 'B' using Install-ChocolateyEnvironmentVariable with values 'A' = "some_value" and 'B' = "%A%" the variable B is not expanded.

To create B variable: "Install-ChocolateyEnvironmentVariable -VariableName 'B' -VariableValue '%A%' -VariableType Machine"

In registry ('Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment' both values are created as type 'REG_SZ', but correctly type of 'B' should be 'REG_EXPAND_SZ' to ensure system loads variables in correct order.
As a workaround SETX could be called which creates proper type.

**Comment by ferventcoder** [comment]
I thought we exposed the type as a parameter to the function. I could be thinking of maybe another issue where we had fixed this with the path updates but maybe had not ported it over to this function

**Comment by jmusek** [comment]
There is 'VariableType {Process | User | Machine}' parameter, but that is to define scope parameter.

**Comment by ferventcoder** [comment]
@jmusek I took a look as well when I mentioned this and noticed that we didn't open up the actual type in that command. 

https://github.com/chocolatey/choco/commit/c3d4ff3aec9d5e939f373577c2529be624bfccc7

And related to #303 / #699
