### ISSUE TITLE
RefreshEnv cannot find files

### ISSUE THREAD

**Issue by HASJ** [chocolatey/choco#1458]
### What You Are Seeing?
The script finishes without doing anything.
### What is Expected?
For it to work.
### How Did You Get This To Happen? (Steps to Reproduce)
I have no idea, the command just isn't working.
### Output Log
~~~sh
refreshenv
Refreshing environment variables from registry for cmd.exe. Please wait...The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
Finished..

~~~

This is possibly a local configuration problem and not related to Choco or RefreshEnv but I need some pointers because I have no idea what caused this. Are my environment vars broken? I don't get it.

Thanks in advance.

**Comment by AdmiringWorm** [comment]
Just a small question, are you calling `refreshenv` from cmd, or from powershell?

If it is from powershell, you'll need have the chocolatey profile loaded on each session so the correct `refreshenv` function is used.

**Comment by ferventcoder** [comment]
Take a look at refreshenv.cmd (or bat), it is in $env:ChocolateyInstall\bin. You may want to add some logging there to see what file it is having trouble finding.

**Comment by HASJ** [comment]
Sorry but how would I do that (turn logging on)?

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/redirects/RefreshEnv.cmd

First line is `@echo off`, change to `@echo on`.

**Comment by HASJ** [comment]
![notepad _2017-11-25_19-00-31](https://user-images.githubusercontent.com/9345660/33234762-2075a49c-d213-11e7-9f66-0efcbdb1fc59.png)

```
$ refreshenv
Refreshing environment variables from registry for cmd.exe. Please wait...The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
Finished..
```
Same output.

**Comment by ferventcoder** [comment]
May need more invasive logging.

**Comment by thomasvdb** [comment]
@HASJ Did you find the issue? If so, can you give some description what the problem was? Or can this issue be closed?

**Comment by HASJ** [comment]
Ultimately, I don't think it had anything to do with chocolatey. I don't remember very well, but I believe it was some environmental variable conflict. Can't be sure.

But the issue was resolved so I will close it.
