### ISSUE TITLE
Cannot install Chocolatey on a newly formatted Windows 10

### ISSUE THREAD

**Issue by tatoo236** [chocolatey/choco#1462]
### What You Are Seeing?
Error in installing choco. I have tried to google the error but i don't understand coding so I cannot really troubleshoot it.

### What is Expected?
Installed Chocolatey on my newly formatted Windows 10 PC.

### How Did You Get This To Happen? (Steps to Reproduce)
Pasted and ran the install code from the "Install" section of the website, using both CMD and PowerShell.
Same error
### Output Log

`Getting latest version of the Chocolatey package for download.
Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.8.
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden."
At line:165 char:3
+   $downloader.DownloadFile($url, $file)
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Extracting C:\Users\tarun\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\tarun\AppData\Local\Temp\chocolatey\chocInstall...
Unable to unzip package using 7zip. Perhaps try setting $env:chocolateyUseWindowsCompression = 'true' and call install
again. Error: 7-Zip encountered a fatal error while extracting the files
At line:221 char:9
+     2 { throw "$errorMessage 7-Zip encountered a fatal error while ex ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to unzip...cting the files:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to unzip package using 7zip. Perhaps try setting $env:chocolateyUseWindowsCompres
   sion = 'true' and call install again. Error: 7-Zip encountered a fatal error while extracting the files`

**Comment by ferventcoder** [comment]
Howdy,
 `(403) Forbidden` typically means one of a few things. Note that now you see it is a 403 issue, which is addressed on the install page in the FAQs - see https://chocolatey.org/install#faqs for further troubleshooting.

**Comment by ferventcoder** [comment]
If you do find you are being blocked/soft banned by Cloudflare, reach out through those instructions so we can help.

**Comment by ahmadzakiarozi** [comment]
C:\Windows\system32>@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
Getting latest version of the Chocolatey package for download.
Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.15.
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (503) Server Unavailable."
At line:167 char:3
+   $downloader.DownloadFile($url, $file)
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Extracting C:\Users\AHMADZ~1\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\AHMADZ~1\AppData\Local\Temp\chocolatey\chocInstall...

ERROR: The system cannot find the file specified.
C:\Users\AHMADZ~1\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip



System ERROR:
The system cannot find the file specified.
Unable to unzip package using 7zip. Perhaps try setting $env:chocolateyUseWindowsCompression = 'true' and call install
again. Error: 7-Zip encountered a fatal error while extracting the files
At line:216 char:9
+     2 { throw "$errorMessage 7-Zip encountered a fatal error while ex ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to unzip...cting the files:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to unzip package using 7zip. Perhaps try setting $env:chocolateyUseWindowsCompres
   sion = 'true' and call install again. Error: 7-Zip encountered a fatal error while extracting the files


HOW ABOUT THIS ?

**Comment by mdrijwan** [comment]
I'm having the same issue!

<img width="575" alt="choco" src="https://user-images.githubusercontent.com/22044931/126667105-11206e52-13c2-4ee2-946d-cde812a20130.png">

**Comment by pauby** [comment]
@mdrijwan What troubleshooting have you done on this?
