### ISSUE TITLE
Install-ChocolateyZipPackage for zip file is stuck at 'extracting'

### ISSUE THREAD

**Issue by gitawego** [chocolatey/choco#1463]
### What You Are Seeing?
when using ``Install-ChocolateyZipPackage @packageArgs``, it's stuck at extracting file.  it seems chocolatey can't determine the exit code of 7zip.
```cmd
Extracting C:\path\to\chocolatey\node-portable\9.2.0\node-v9.2.0-win-x64.zip to C:\path\to\AppData\Local\node-portable...
7zip found at 'C:\ProgramData\chocolatey\tools\7z.exe'
Executing command ['C:\ProgramData\chocolatey\tools\7z.exe' x -aoa -bd -bb1 -o"C:\path\to\AppData\Local\node-portable" -y "C:\path\to\AppData\Local\Temp\chocolatey\node-portable\9.2.0\node-v9.2.0-win-x64.zip"]
```
it works when executing directly the 7zip command

### What is Expected?
once files are extracted, it should continue the package installation.

### How Did You Get This To Happen? (Steps to Reproduce)
create a package using ``choco new pkg-name``, and add a config to use ``Install-ChocolateyZipPackage ``
repo link: https://github.com/gitawego/work-note/blob/master/choco/node-portable/tools/chocolateyinstall.ps1

**Comment by gitawego** [comment]
after rebooted windows, it works again. but it takes a long time (around 10 minutes) to finish the extraction.

**Comment by ferventcoder** [comment]
This sounds like an anti-virus program or something slowing things down. Unsure what is slowing it down for you.
