### ISSUE TITLE
Not able to install meteor . 

### ISSUE THREAD

**Issue by ramintagizade** [chocolatey/choco#1467]
Microsoft Windows [Version 6.3.9600]
         (c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>choco install meteor
Chocolatey v0.10.8
[Pending] Removing incomplete install for 'meteor'
Installing the following packages:
meteor
By installing you accept licenses for the packages.

meteor v0.0.2 [Approved]
meteor package files install completed. Performing other installation steps.
The package meteor wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[N]o/[P]rint): y

Downloading meteor 64 bit
  from 'https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_64'
Progress: 95% - Saving 136.86 MB of 143.58 MB                                  E
RROR: The remote file either doesn't exist, is unauthorized, or is forbidden for
 url 'https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_64'. Except
ion calling "Read" with "3" argument(s): "Received an unexpected EOF or 0 bytes
from the transport stream."
This package is likely not broken for licensed users - see https://chocolatey.or
g/docs/features-private-cdn.
The install of meteor was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\meteor\tools\chocolateyinstal
l.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - meteor (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\mete
or\tools\chocolateyinstall.ps1'.
 See log for details.

C:\Windows\system32>

**Comment by ferventcoder** [comment]
This looks like a package issue and not one with Chocolatey itself. Can you confirm?

**Comment by ferventcoder** [comment]
Preemptively closing as a Package Issue. Please respond if you believe it is an issue with Chocolatey itself. Otherwise if you are attempting to install the package from the community repository (the default one set up on install), you should head out to the package page and let the maintainers know of your issue as they will need to fix the package. HTH
