### ISSUE TITLE
XDT transform causes xml file to have extra data in it (unusable until manually fixed)

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/choco#1482]
Moving bug report to correct area (cross post).
Originally from: https://github.com/chocolatey/simple-server/issues/19

Error occurs during install of [Chocolatey Server (Simple)](https://chocolatey.org/packages/chocolatey.server)

> It looks like a bug in Chocolatey actually - a double transform, where the first corrupts the file and the second can't make changes:
> 
> Preparing transform for 'C:\ProgramData\chocolatey\lib\chocolatey.server\tools\chocolatey.server\Web.config.install.xdt'
> Transforming 'Web.config' with the data from 'Web.config.install.xdt'
> Transform applied successfully for 'C:\ProgramData\chocolatey\lib\chocolatey.server\tools\chocolatey.server\Web.config'
> 
> Preparing transform for 'C:\ProgramData\chocolatey\lib\chocolatey.server\tools\chocolatey.server\bin\Web.config.install.xdt'
> Transforming 'Web.config' with the data from 'Web.config.install.xdt'
> [ERROR] - Error transforming config file:
>  Data at the root level is invalid. Line 230, position 17.

**Comment by ferventcoder** [comment]
Thank you for logging this. Let's rewrite this a bit. Happens with all XDT Transforms.

**Comment by ferventcoder** [comment]
Merged into stable at https://github.com/chocolatey/choco/commit/4f5b9650abd0343f2c042aec0af254ca45b7dcc5
