### ISSUE TITLE
FEATURE REQUEST: display source URL on package dl when multiple sources detected

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/choco#1485]
(from https://github.com/chocolatey/simple-server/issues/26)

### What You Are Seeing?

Nothing :)

### What is Expected?

In the case of multiple source feeds in chocolatey.config, i.e. packages installed via Chocolatey community feed and possibly a local Chocolatey Simple Server/MyGet/etc. ... 

Chocolatey v0.10.8 Professional
Installing the following packages:
vlc **- from https://chocolatey.org/api/v2/** <- requested new information
By installing you accept licenses for the packages.

In the instance of a sole source, no additional information needs to be displayed.

**Comment by TheCakeIsNaOH** [comment]
The install counterpart to #1486 

Should be super easy to implement once the the NuGet library exposes this information.
