### ISSUE TITLE
--Allowdowngrade option does not work

### ISSUE THREAD

**Issue by mayu111** [chocolatey/choco#1487]
When I run the install cmd for an application that is already installed but with a later version, I get the error that it is already installed, and with the force option it tries to re-install the version that is already installed instead of installing the version held at the source.

cmd:
choco install app --allowdowngrade -y --force --source http://source/nuget/source

Output:
Chocolatey v0.10.8
Installing the following packages: app
By installing you accept licenses for the packages.
app v2.0 already installed. Forcing reinstall of version '2.0'.
 Please use upgrade if you meant to upgrade to a new version.
app not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "http://source/nuget/source/"

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - app not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "http://dmproget.prds.qldpol/nuget/QCAD-PROD/"

**Comment by ferventcoder** [comment]
Use the upgrade command. Install with force (without specifying a version) will reinstall current version always. This is by design.

choco upgrade (no need for force) sounds like what you are looking for. HTH

**Comment by ferventcoder** [comment]
Allow downgrade is only an option with `upgrade`, that is part of why it is not working like you want it to.

To install an earlier version, you need both `--version` and `--allow-downgrade`. Let me know if you have additional questions.
