### ISSUE TITLE
Resolve differences between chocolatey.core-extension's Get-PackageParameters and built in method

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1490]
In https://github.com/chocolatey/chocolatey-coreteampackages/issues/950 it was noted that the built-in `Get-PackageParameters` has some incompatibilities with the original chocolatey.core-extension's `Get-PackageParameters`. We've already made enhancements with #1459 (due out with v0.10.9), but we needed more to work in the same way that `Get-PackageParameters` (core extension) does. 

To expand on this, the built-in `Get-PackageParameters` should do **at least** what core extension does and then enhance on that with more. 

One of the discrepancies was how it handles quotes and apostrophes as it loads items into the hash table. The original removes the quotes/apostrophes surrounding the items, so the built-in should mimic that behavior. If folks want to put them back, that is fine.

**Comment by majkinetor** [comment]
The removal is intentional as the resulting path always works unlike quoted path.
