### ISSUE TITLE
Troubleshooting Missing documentation/link

### ISSUE THREAD

**Issue by ebelew** [chocolatey/choco#1491]
### What You Are Seeing?
On the troubleshooting page, in the [refreshenv section](https://github.com/chocolatey/choco/wiki/Troubleshooting#refreshenv-has-no-effect), it says

> In PowerShell, you need to install the Chocolatey PowerShell profile first for the command to work.

### What is Expected?
A link to directions on how to install the Chocolatey Powershell Profile

### How Did You Get This To Happen? (Steps to Reproduce)
Read the docs

**Comment by AdmiringWorm** [comment]
@ebelew did you check the link mentioned in the same section?
If you follow that link it tells you exactly what you need to do to get it working:

https://github.com/chocolatey/choco/wiki/Troubleshooting#why-does-choco-intab-not-work-for-me

basically you need to make sure that the following is in the file located under the `$Profile` variable:

```powershell
# Chocolatey profile
$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
if (Test-Path($ChocolateyProfile)) {
  Import-Module "$ChocolateyProfile"
}
```
