### ISSUE TITLE
Feature flag autouninstaller

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#15]
Since it is still experimental, turn it off for now and allow explicit opt-in.

**Comment by ferventcoder** [comment]
Turn it on by enabling the feature in the config fil.

**Comment by dhilgarth** [comment]
Do I see this correctly, that this flag in the config does not affect the packages I *create* as a maintainer, but merely what happens when I uninstall a package *on my machine* as a normal chocolatey user?

**Comment by ferventcoder** [comment]
Just as a user

On Thursday, February 26, 2015, Daniel Hilgarth <notifications@github.com>
wrote:

> Do I see this correctly, that this flag in the config does not affect the
> packages I *create* as a maintainer, but merely what happens when I
> uninstall a package *on my machine* as a normal chocolatey user?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/15#issuecomment-76191487>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder
