### ISSUE TITLE
Expired License should not fail Chocolatey

### ISSUE THREAD

**Issue by gep13** [chocolatey/choco#1500]
If there is an expired Chocolatey license file present in the `license` folder, Chocolatey will correctly validate this, and handle it based on feature, however, by default, the licensing system we are using will attempt to re-validate the license every 5 minutes.  This can cause problems on longer running Chocolatey processes.

This re-validation is not required.

**Comment by ferventcoder** [comment]
Merged into stable at https://github.com/chocolatey/choco/commit/7e58483f482409e8c8ae2ece319f11a98610e1c5

**Comment by ferventcoder** [comment]
This also requires at least Chocolatey Licensed Extension 1.12.12 for it to work properly. This is whether or not the license loads the binaries, it will trigger the recheck.
