### ISSUE TITLE
Allow packages to depend on other packages

### ISSUE THREAD

**Issue by mcandre** [chocolatey/choco#1510]
Example: visualstudio2017-workload-vctools should automatically install visualstudio2017buildtools.

**Comment by ferventcoder** [comment]
@mcandre functionality exists. It's called dependencies. If there is a missing dependency, it should be addressed with the package maintainers directly.

**Comment by ferventcoder** [comment]
Being able to define dependencies in nupkgs has existed since before Chocolatey existed. HTH
