### ISSUE TITLE
chocolatey.lib Integrated PowerShell host issue 

### ISSUE THREAD

**Issue by chriszuercher** [chocolatey/choco#1513]
### What You Are Seeing?
In one of our self-made packages I need to check a registry key for it's value. I do this in chocolateyinstall.ps1.

Using choco.exe (v0.10.8) with choco feature enable -n=powershellHost the installation runs fine. If i want to install the same package by our own application using chocolatey.lib (also v.0.10.8) or Chocolatey GUI the installation fails because the regsitry key cannot be found (or accessed).

if I disable the powershellHost feature it works in choco.exe, our own application using the library and Chocolatey GUI.

### What is Expected?
chocolatey.lib and choco.exe should work the same and support the same PowerShell functionality.

### How Did You Get This To Happen? (Steps to Reproduce)
Create a package which accesses a registry key under HKLM:\Software\Microsoft\ in chocolateyinstall.ps1. We a re reading HKLM:\Software\Microsoft\Deployment 4\ but this key only exists in customized windows OSes.

choco feature enable -n=powershellHost
Install the package using choco.exe
Uninstall the package
Install the package using Chocolatey GUI => this fails in our case

choco feature disable -n=powershellHost
Uninstall the package
Install the package using choco.exe
Uninstall the package
Install the package using Chocolatey GUI => this works as expected

Chocolateyinstall.ps1 extract (relevant section):
~~~posh
$ErrorActionPreference = 'Stop'; # stop on all errors

$RegistryPath = "HKLM:\Software\Microsoft\Deployment 4\"
$VersionRegistryName = "Task Sequence Version"
$NameRegistryName = "Task Sequence ID"

$TSVersion = New-Object -TypeName System.Version -ArgumentList((Get-ItemProperty  $RegistryPath -name $VersionRegistryName).$VersionRegistryName) 
$TSName = (Get-ItemProperty  $RegistryPath -name $NameRegistryName).$NameRegistryName
~~~

I tried to track down the issue and landed in PowershellService.cs but got stuck there.  I found something pointing into a directtion but it was not the issue: https://stackoverflow.com/questions/9095803/mvc-controller-with-runspace-impersonation

### Output Log
Gist with internal PowerShell Host (and error):
https://gist.github.com/chriszuercher/67abdabca13b532955f8c4a9d0e60174

Gist with external PowerShell Host (working):
https://gist.github.com/chriszuercher/cf2ed1782fdc6d7befa6e3771277f5be

~~~sh
ERROR: The running command stopped because the preference variable \"ErrorActionPreference\" or common parameter is set to Stop: Cannot find path 'HKLM:\Software\Microsoft\Deployment 4\' because it does not exist.", "The install of p1 was NOT successful.", "Error while running 'C:\ProgramData\chocolatey\lib\p1\tools\chocolateyinstall.ps1'.
 See log for details.", "
~~~

**Comment by ferventcoder** [comment]
Can you use a different key and see if there is an issue? Please use something other than `HKLM:\Software` as that will evaluate differently with 32-bit based programs (and likely what you might actually be hitting)

**Comment by ferventcoder** [comment]
> Install the package using Chocolatey GUI => this fails in our case

I can see that, Chocolatey GUI is 32-bit, so it is subjected to SysWOW64, which means when it tries `HKLM:\Software\Microsoft\Deployment 4`, it is getting redirected to `HKLM:\Software\Wow6432Node\Microsoft\Deployment 4`. I think one might file an issue at https://github.com/chocolatey/chocolateygui/issues to get that fixed. 

So Chocolatey itself already handles that redirection, but in the PowerShell engine, it is unlikely to see that. The good news is you can (and likely should) handle that redirection. You can turn it off when you query the registry with a flag, although I'm not sure it is available.

**Comment by ferventcoder** [comment]
> although I'm not sure it is available.

Although I'm not sure it is available in a simple query through the PowerShell methods. You would need to fall back to the .NET methods to resolve that.

**Comment by chriszuercher** [comment]
Sorry I forgot to mention this. Other keys are working. But thanks to point me to the 32/64 Bit issue. It is really the case for this key. I updated my script to debug it.

~~~PowerShell
$RegistryPath = "HKLM:\Software\Microsoft\Deployment 4\"
$VersionRegistryName = "Task Sequence Version"

if ([System.Environment]::Is64BitOperatingSystem){Write-Error "Running in 64 Bit OS"}else{Write-Error "Running in 32 Bit OS"}
if ([System.Environment]::Is64BitProcess){Write-Error "Running in 64 Bit Process"}else{Write-Error "Running in 32 Bit Process"}
try
{
	$TSVersion = New-Object -TypeName System.Version -ArgumentList((Get-ItemProperty  $RegistryPath -name $VersionRegistryName).$VersionRegistryName) 
	Write-Error "TSVersion PS: $TSVersion"
}Catch{	Write-Error "Error PS"}

try
{
	$reg = [Microsoft.Win32.RegistryKey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::LocalMachine, [Microsoft.Win32.RegistryView]::Registry32)
	$regkey = $reg.OpenSubkey("Software\Microsoft\Deployment 4")
	$TSVersion = $regkey.GetValue($VersionRegistryName)
	Write-Error "TSVersion CS32: $TSVersion"
}
Catch{Write-Error "Error CS32"}
try
{
	$reg = [Microsoft.Win32.RegistryKey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::LocalMachine, [Microsoft.Win32.RegistryView]::Registry64)
	$regkey = $reg.OpenSubkey("Software\Microsoft\Deployment 4")
	$TSVersion = $regkey.GetValue($VersionRegistryName)
	Write-Error "TSVersion CS64: $TSVersion"
}
Catch{Write-Error "Error CS64"}
~~~

Using Internal PS Host:
~~~
2018-03-01 11:41:37.166 +01:00 [Error] Running in 64 Bit OS
2018-03-01 11:41:37.166 +01:00 [Error] Running in 32 Bit Process
2018-03-01 11:41:37.182 +01:00 [Error] Cannot find path 'HKLM:\Software\Microsoft\Deployment 4\' because it does not exist.
2018-03-01 11:41:37.182 +01:00 [Error] TSVersion PS: 0.0
2018-03-01 11:41:37.198 +01:00 [Error] Error CS32
2018-03-01 11:41:37.198 +01:00 [Error] TSVersion CS64: 1.7.0
2018-03-01 11:41:37.198 +01:00 [Error] ERROR: Stop here
~~~

Using External PS Host:
~~~
2018-03-01 11:41:56.588 +01:00 [Error]  C:\ProgramData\chocolatey\lib\p1\tools\chocolateyinstall.ps1 : Running in 64 Bit OS
2018-03-01 11:41:56.588 +01:00 [Error]  C:\ProgramData\chocolatey\lib\p1\tools\chocolateyinstall.ps1 : Running in 64 Bit Process
2018-03-01 11:41:56.604 +01:00 [Error]  C:\ProgramData\chocolatey\lib\p1\tools\chocolateyinstall.ps1 : TSVersion PS: 1.7.0
2018-03-01 11:41:56.620 +01:00 [Error]  C:\ProgramData\chocolatey\lib\p1\tools\chocolateyinstall.ps1 : Error CS32
2018-03-01 11:41:56.620 +01:00 [Error]  C:\ProgramData\chocolatey\lib\p1\tools\chocolateyinstall.ps1 : TSVersion CS64: 1.7.0
2018-03-01 11:41:56.635 +01:00 [Error]  Stop here
~~~

Using this information I can handle the case by checking "Is64BitProcess". The strange thing is only, that internal and external host are not running in the same environment. Compiling the application as "x64" instead "Any CPU" configuration doesn't change this. Not sure if this is an issue of the library or not, but it is definitely confusing if you are not aware of this issue.

Are there any disadvantages of using the external PowerShell host? I couldn't finde any documentation on this.

**Comment by chriszuercher** [comment]
Upps. I just noticed that I copied the wrong version of my application for my test. I took the one compiled with "Any CPU" instead of "x64". Compiled for "x64" and internal host is looks like this:

~~~
2018-03-01 13:51:30.413 +01:00 [Error] Running in 64 Bit OS
2018-03-01 13:51:30.413 +01:00 [Error] Running in 64 Bit Process
2018-03-01 13:51:30.429 +01:00 [Error] TSVersion PS: 1.7.0
2018-03-01 13:51:30.444 +01:00 [Error] Error CS32
2018-03-01 13:51:30.444 +01:00 [Error] TSVersion CS64: 1.7.0
2018-03-01 13:51:30.444 +01:00 [Error] ERROR: Stop here
~~~

But as the code below works in all configurations for me I just use this one.
~~~PowerShell
$reg = [Microsoft.Win32.RegistryKey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::LocalMachine, [Microsoft.Win32.RegistryView]::Registry64)
$regkey = $reg.OpenSubkey("Software\Microsoft\Deployment 4")
$TSVersion = $regkey.GetValue($VersionRegistryName)
~~~

**Comment by chriszuercher** [comment]
And by setting "<Prefer32Bit>false</Prefer32Bit>" in VisualStudio build options my application runs as 64Bit process. This way it works too.

ChocolateyGUI is set "x68" platform target and therefore has the same issue. Even it shows "Any CPU" in the build there is no "Any CPU" configuration to build. Shall I open an other issue there?

This issue can be closed in my opinion.

**Comment by gep13** [comment]
@chriszuercher yes, if you could raise an issue there, I would appreciate it.  A PR to correct the issue would be even more appreciated 😄

**Comment by ferventcoder** [comment]
> Are there any disadvantages of using the external PowerShell host?

Yes, there could be. One is that licensed editions of Chocolatey may not load correctly. It may be using different .NET versions than choco (older hosts where PowerShell v2/3 use .NET 2 and 3.5), among other issues.
