### ISSUE TITLE
Install.ps1 reference to switch to built-in compression in Dec 2016, but still uses 7zip

### ISSUE THREAD

**Issue by boktai1000** [chocolatey/choco#1516]
Per review of https://chocolatey.org/install.ps1 it references a switch to built-in compression being used by Windows, yet still uses 7-zip as the method as of this date. If the use-case has changed, you should probably update the description on reasons why you're sticking with that package (compatibility issues or some edge case?) otherwise it's probably worth pushing that date forward.

Upon review of first install before running on a machine it's just something that raises an eyebrow or makes you wonder why this switch never occurred.

**Comment by ferventcoder** [comment]
Howdy - this should maybe be filed over at https://github.com/chocolatey/chocolatey.org? That way we can tag an issue with the fix.
