### ISSUE TITLE
Installing chocolatey 0.10.9 results in an exit code of 1

### ISSUE THREAD

**Issue by matt-richardson** [chocolatey/choco#1529]
### What You Are Seeing?

Installing chocolatey is returning an exit code of 1.

### What is Expected?

It should exit with `0`, rather than `1`.

### How Did You Get This To Happen? (Steps to Reproduce)

```
write-output "Installing Chocolatey"
iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
if ($LASTEXITCODE -ne 0) { exit 1 }
```

### Output Log
https://gist.github.com/matt-richardson/0003caf7b04bd4b684138bb994ea48fc

### Further info

Raised in gitter - https://gitter.im/chocolatey/choco?at=5ab9f00fe3d0b1ff2c704ffe

> Rob Reynolds @ferventcoder 05:51
> I think I know what it is!
> @matt-richardson @stopthatastronaut - we converted to running choco one time to ensure the config file was generated. However if you run choco with no arguments, it exits with -1

Looks like we need to change over to `choco -v` instead.

### Choco Admin notes

This was caused by https://github.com/chocolatey/choco/issues/1401 for 0.10.9.

**Comment by ferventcoder** [comment]
@matt-richardson thanks!

**Comment by bigbearzhu** [comment]
@ferventcoder or any one please check the merge to stable branch failure? Waiting for 0.10.10 for the fix of this issue. Many thanks.

**Comment by ferventcoder** [comment]
@bigbearzhu merge failure?

**Comment by bigbearzhu** [comment]
Yes, it is the commit 3fa08ca above. It failed on the coverage/coveralls check. Not sure whether that would stop the merge though.

**Comment by bigbearzhu** [comment]
@ferventcoder any idea when the chocolatey package would be updated on chocolatey.org? It is still 0.10.9 at the moment.
