### ISSUE TITLE
Proxy bypass list with "*" will return regex quantifier parsing errors

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1532]
Say you add "*.localenvironment.com" to the proxy bypass list. Instead of configuring it properly, it will return an error with "parsing "*.localhost.com" - Quantifier {x,y} following nothing."

**Comment by spkyghost** [comment]
I also still get this error and this causes me a lot of problems.
Hope this will be fixed soon

**Comment by ferventcoder** [comment]
@johlandabee interesting - I'll follow up on the issue you created as a followup.

This was definitely fixed and verified for 0.10.10 - no merge failed here.

**Comment by spkyghost** [comment]
I'm running Chocolatey v0.10.11
It is definitely not working.

![grafik](https://user-images.githubusercontent.com/11074890/46079137-8aa31980-c196-11e8-9de1-59a1671dd611.png)

**Comment by t0r0X** [comment]
The documentation is very clear on this:
`     --proxy-bypass-list=VALUE
     ProxyBypassList - Comma separated list of regex locations to bypass on
       proxy. Requires explicity proxy (`--proxy` or config setting). Overrides
       the default proxy bypass list of ''. Available in 0.10.4+.`

`separated list of regex locations`(!) Therefore the bypass expression `--proxy-bypass-list='*.mycompany.tld'` is wrong, and it should be `--proxy-bypass-list='.*.mycompany.tld'` (note the dot character before the asterisk).

So, in my opinion, this should not be fixed.

**Comment by johlandabee** [comment]
@t0r0X Actually, most implementations do use globbing and not regex to match no_proxy entries. Infact, your example does not work for such, as it will match `.xxx.mycompany.tld` but not `xxx.mycompany.tld`. Changing the entries would probably work for chocolatey, but break other apps. Furthermore, `.*.mycompany.tld` means, the dots match *any* character. To make this technically correct, you'd have to escape them (`.*\.mycompany\.tld`) which would - yet again - not work for other applications.

**Comment by ferventcoder** [comment]
@johlandabee please open a new issue related to this. Can I ask that if you set the proxy bypass list INSIDE of chocolatey configuration whether it works with the regex described? And yes, `.` would match any character, including the literal `.`.  Here's the link to the configuration setting - https://chocolatey.org/docs/chocolatey-configuration#proxy (`proxyBypassList`). Setting it here should not break other applications as they would not be using explicit Chocolatey settings.

**Comment by johlandabee** [comment]
@ferventcoder That works. Thanks. Seems like the choco config weights more than the environment variable after all. 

I've set the following:
````
choco config set --name proxyBypassList --value ".*\.tld,.*\.company.com"
````

**Comment by tremblaysimon** [comment]
It's a bit of pain that chocolatey doesn't properly use no_proxy environment variable and that we need a custom "no_proxy" setting for chocolatey...

**Comment by zhililab** [comment]
> > @ferventcoder That works. Thanks. Seems like the choco config weights more than the environment variable after all.
> > I've set the following:
> > ```
> > choco config set --name proxyBypassList --value ".*\.tld,.*\.company.com"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @johlandabee this works for me as well.

thxs, it solved my problem
