### ISSUE TITLE
choco 0.10.9 refuses to install program when there are unrelated package access problems

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/choco#1535]
### What You Are Seeing?

choco ignores my installation attempt based on a problem with an unrelated package.

### What is Expected?

Install the package I tell it to with no care about other packages.

### How Did You Get This To Happen? (Steps to Reproduce)

Was doing a cup all

### Output Log

You have tor-browser v7.5 installed. Version 7.5.3 is available based on your source(s).
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 (5) Access is denied: [\\?\C:\ProgramData\chocolatey\lib-bkp\tor-browser]
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 (5) Access is denied: [\\?\C:\ProgramData\chocolatey\lib-bkp\tor-browser]
Maximum tries of 3 reached. Throwing error.
Chocolatey had an error formatting string:
 Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
Chocolatey had an error formatting string:
 Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
Chocolatey had an error formatting string:
 Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 (5) Access is denied: [\\?\C:\ProgramData\chocolatey\lib\tor-browser\tools\tor-browser\Browser\*]
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 Access to the path 'C:\ProgramData\chocolatey\lib\tor-browser\tools\tor-browser\Browser' is denied.
Maximum tries of 3 reached. Throwing error.
Error during backup (move phase):
 Access to the path 'C:\ProgramData\chocolatey\lib\tor-browser\tools\tor-browser\Browser' is denied.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 Access to the path 'C:\ProgramData\chocolatey\lib\tor-browser\tools\tor-browser\Browser\Accessible.tlb' is denied.
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 Access to the path 'C:\ProgramData\chocolatey\lib\tor-browser\tools\tor-browser\Browser\Accessible.tlb' is denied.
Maximum tries of 3 reached. Throwing error.
Error during backup (reset phase):
 Access to the path 'C:\ProgramData\chocolatey\lib\tor-browser\tools\tor-browser\Browser\Accessible.tlb' is denied.
tor-browser not upgraded. An error occurred during installation:
 Access to the path 'C:\ProgramData\chocolatey\lib\tor-browser\tools\tor-browser\Browser' is denied.
tor-browser package files upgrade completed. Performing other installation steps.
The upgrade of tor-browser was NOT successful.
tor-browser not upgraded. An error occurred during installation:
 Access to the path 'C:\ProgramData\chocolatey\lib\tor-browser\tools\tor-browser\Browser' is denied.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 (5) Access is denied: [\\?\C:\ProgramData\chocolatey\lib-bad\tor-browser]
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 (5) Access is denied: [\\?\C:\ProgramData\chocolatey\lib-bad\tor-browser]
Maximum tries of 3 reached. Throwing error.
Could not move bad package to failure directory It will show as installed.
 C:\ProgramData\chocolatey\lib\tor-browser
 The error:
 Access to the path 'C:\ProgramData\chocolatey\lib\tor-browser\tools\tor-browser\Browser' is denied.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 (183) Cannot create a file when that file already exists: [\\?\C:\ProgramData\chocolatey\lib\tor-browser]
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 (183) Cannot create a file when that file already exists: [\\?\C:\ProgramData\chocolatey\lib\tor-browser]
Maximum tries of 3 reached. Throwing error.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 Access to the path is denied.
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 Access to the path is denied.
Maximum tries of 3 reached. Throwing error.
Access to the path is denied.

**C:\Windows\system32>cinst dell-update
Chocolatey v0.10.9 Professional
Access to the path 'C:\ProgramData\chocolatey\lib\tor-browser\tools\tor-browser\Browser' is denied.

C:\Windows\system32>cinst dell-update
Chocolatey v0.10.9 Professional
Access to the path 'C:\ProgramData\chocolatey\lib\tor-browser\tools\tor-browser\Browser' is denied.

C:\Windows\system32>cinst dell-update
Chocolatey v0.10.9 Professional
Access to the path 'C:\ProgramData\chocolatey\lib\tor-browser\tools\tor-browser\Browser' is denied.

C:\Windows\system32>cinst dell-update
Chocolatey v0.10.9 Professional
Access to the path 'C:\ProgramData\chocolatey\lib\tor-browser\tools\tor-browser\Browser' is denied.

C:\Windows\system32>cinst dell-update
Chocolatey v0.10.9 Professional
Access to the path 'C:\ProgramData\chocolatey\lib\tor-browser\tools\tor-browser\Browser' is denied.

C:\Windows\system32>cinst dell-update
Chocolatey v0.10.9 Professional
Access to the path 'C:\ProgramData\chocolatey\lib\tor-browser\tools\tor-browser\Browser' is denied.**

**Comment by ColinT-wdm** [comment]
Just run powershell as admin

**Comment by uravi409** [comment]
i am also getting error in power shell like : Access to the path 'C:\ProgramData\chocolatey\config' is denied

after i tried to power shell as administrator it was done

**Comment by Devopnugs** [comment]
That is great running Powershell as admin will fix any error

**Comment by pauby** [comment]
Chocolatey needs to be run in an elevated session.

**Comment by pauby** [comment]
As this is referring to Chocolatey 0.10.9 and we're at 0.10.15 I'm going to go ahead and close this. If the same issues are appearing in the latest stable release, please raise a new issue.
