### ISSUE TITLE
choco pack doesnt support replacement tokens with quotes

### ISSUE THREAD

**Issue by mwallner** [chocolatey/choco#1536]
... it should be possible to add replacement tokens with quotes

### How Did You Get This To Happen? (Steps to Reproduce)
Content of nuspec
~~~sh
<files>
    <file src=$srcdir$ target="tools" />
</files>
~~~

doesn't work when called this way
~~~sh
PS E:\tmp\chocotest> choco pack .\chocotest.nuspec --version 1.2.3 --srcdir="release"
Chocolatey v0.10.8 Business
The replacement token 'srcdir' has no value.
~~~
(see quotes in cmdline)

it works when the quotes are added in the nuspec but left out in the call
~~~sh
<files>
    <file src="$srcdir$" target="tools" />
</files>
~~~
~~~sh
PS E:\tmp\chocotest> choco pack .\chocotest.nuspec --version 1.2.3 srcdir=release/
Chocolatey v0.10.8 Business
Attempting to build package from 'chocotest.nuspec'.
...
~~~

**Comment by ferventcoder** [comment]
It appears there is something else at play here. It should work to pass that through like that.

**Comment by ferventcoder** [comment]
Can you try this on 0.10.9 and tell me if it works?

**Comment by ferventcoder** [comment]
Also, you need to be calling `srcdir="release"` and not `--srcdir="release"`. It works when I run it.

**Comment by mwallner** [comment]
can confirm it's still the same with 0.10.9 - you definitely need the quotes around the replacement token in nuspec.

i.e.
```
<files>
    <file src="$srcdir$" target="tools" />
</files>
```
works fine

```
<files>
    <file src=$srcdir$ target="tools" />
</files>
```
does not.

- not a big issue, maybe even by design?

**Comment by ferventcoder** [comment]
Quotes are by design, it's required by the XML.

**Comment by ferventcoder** [comment]
Sounds like this is good then?
