### ISSUE TITLE
It's do full disk scan after install mongodb, that's annoy 

### ISSUE THREAD

**Issue by lygstate** [chocolatey/choco#154]
C:\Windows\system32>cinst mongodb
!!ATTENTION!!
The next version of Chocolatey (v0.9.9) will require -y to perform
  behaviors that change state without prompting for confirmation. Start
  using it now in your automated scripts.

  For details on the all new Chocolatey, visit http://bit.ly/new_choco
Chocolatey (v0.9.8.33) is installing 'mongodb' and dependencies. By installing you accept the license for 'mongodb' and each dependency you are instal
ling.

mongodb v2.4.7.1
Extracting C:\Users\LUOYON~1\AppData\Local\Temp\chocolatey\MongoDB\MongoDBInstall.zip to C:\...
Get-ChildItem : Access to the path 'C:\Windows\CSC' is denied.
At C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-FileUpdateLog.ps1:11 char:23
+   $originalContents = Get-ChildItem -Recurse $locationToMonitor | Select-Object  ...
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Windows\CSC:String) [Get-ChildItem], UnauthorizedAccessException
    + FullyQualifiedErrorId : DirUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetChildItemCommand

Get-ChildItem : Access to the path 'C:\Windows\System32\LogFiles\WMI\RtBackup' is denied.
At C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-FileUpdateLog.ps1:11 char:23
+   $originalContents = Get-ChildItem -Recurse $locationToMonitor | Select-Object  ...
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Windows\Syst...es\WMI\RtBackup:String) [Get-ChildItem], UnauthorizedAccessException
    + FullyQualifiedErrorId : DirUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetChildItemCommand

Get-ChildItem : Access to the path 'C:\Windows\CSC' is denied.
At C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-FileUpdateLog.ps1:15 char:18
+   $newContents = Get-ChildItem -Recurse $locationToMonitor | Select-Object LastW ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Windows\CSC:String) [Get-ChildItem], UnauthorizedAccessException
    + FullyQualifiedErrorId : DirUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetChildItemCommand

Get-ChildItem : Access to the path 'C:\Windows\System32\LogFiles\WMI\RtBackup' is denied.
At C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-FileUpdateLog.ps1:15 char:18
+   $newContents = Get-ChildItem -Recurse $locationToMonitor | Select-Object LastW ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Windows\Syst...es\WMI\RtBackup:String) [Get-ChildItem], UnauthorizedAccessException
    + FullyQualifiedErrorId : DirUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetChildItemCommand

**Comment by lygstate** [comment]
Get-ChildItem : The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the director
y name must be less than 248 characters.
At C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-FileUpdateLog.ps1:12 char:23
+   $originalContents = Get-ChildItem -Recurse $locationToMonitor | Select-Object  ...
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (C:\CI-Cor\kexin...modules\bl\test:String) [Get-ChildItem], PathTooLongException
    + FullyQualifiedErrorId : DirIOError,Microsoft.PowerShell.Commands.GetChildItemCommand

**Comment by lygstate** [comment]
Get-ChildItem : The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the director
y name must be less than 248 characters.
At C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-FileUpdateLog.ps1:12 char:23
+   $originalContents = Get-ChildItem -Recurse $locationToMonitor | Select-Object  ...
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (C:\CI-Cor\kexin...modules\bl\test:String) [Get-ChildItem], PathTooLongException
    + FullyQualifiedErrorId : DirIOError,Microsoft.PowerShell.Commands.GetChildItemCommand

**Comment by ferventcoder** [comment]
Hello - I see you are using 0.9.8.33 - This repository represents the rewrite of 0.9.9+. Perhaps you should upgrade and try again

**Comment by lygstate** [comment]
..... What do you mean? I am using the newest stable version!

**Comment by ferventcoder** [comment]
> What do you mean? I am using the newest stable version!

Not according to your logs:

> Chocolatey (v0.9.8.33) is installing 'mongodb' and dependencies. By installing you accept the license for 'mongodb' and each dependency you are installing.


Right now the website installs the last POSH version (0.9.8.33) - from there you need to call cup chocolatey to upgrade to the latest client.

**Comment by lygstate** [comment]
choco/src/chocolatey.resources/helpers/functions/Write-FileUpdateLog.ps1

**Comment by ferventcoder** [comment]
This is done so automation tools have a chance to play catch up, there are quite a few changes.

**Comment by lygstate** [comment]
The code doesn't changed, so the problem will appear again!

**Comment by lygstate** [comment]
Please re-open this issue.

**Comment by lygstate** [comment]
C:\Users\luoyonggang>cup chocolatey
Chocolatey detected you are not running from an elevated command shell
  (cmd/powershell). You may experience errors - many functions/packages
  require admin rights. Only advanced users should run choco w/out an
  elevated shell (and very advanced users as non-admin). When you open
  the command shell, you should ensure "Run as Administrator".
!!ATTENTION!!
The next version of Chocolatey (v0.9.9) will require -y to perform
  behaviors that change state without prompting for confirmation. Start
  using it now in your automated scripts.

  For details on the all new Chocolatey, visit http://bit.ly/new_choco
Nothing to update.

**Comment by ferventcoder** [comment]
> The code doesn't changed, so the problem will appear again

So - 2 things. 

1. You logged an issue about 0.9.8.33 on the new repository. Not as important.

2. You are logging an issue about a package install. The package should be using Get-BinRoot. It's a gray area sure, but it's actually an issue with the mongo db package itself.

**Comment by ferventcoder** [comment]
> Nothing to update.

Perhaps try choco install chocolatey

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/blob/master/README.md#submitting-issues - when you are not certain if you should log an issue, we have a gitter chat room that you can come in and ask.

**Comment by ferventcoder** [comment]
Let's do this. Let's log a proper issue, reference this and close it.

**Comment by lygstate** [comment]
You didn't even read the error report

Get-ChildItem : The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the director
This function doesn't support for path more than 260 chars!

**Comment by lygstate** [comment]
The issue is the function Write-FileUpdateLog is not robust, 
1. for very long path, is can not hanlded.
2. and second for very large directory, it's very time costing, but this issue may not need to be resolved, this is the issue #155 need to be handled.

**Comment by ferventcoder** [comment]
So are you adding multiple issues?

**Comment by ferventcoder** [comment]
We should log each of them separately as each could be prioritized and worked on separately.

**Comment by lygstate** [comment]
It's caused these two problems when I trying to 
choco install -y mongodb

**Comment by lygstate** [comment]
OK, I'll modify this issue to resolve the long path issue.

**Comment by ferventcoder** [comment]
Honestly I've never been a fan of that function - but it will become more important once we move to automatically tracking where things are installed to and removing them on uninstall. But it will be implemented a different way. :)

**Comment by ferventcoder** [comment]
Let's create a new issue for that and reference this.
