### ISSUE TITLE
Refreshenv script leaves temporary file behind

### ISSUE THREAD

**Issue by grv87** [chocolatey/choco#1549]
### What You Are Seeing?
During  `Refreshenv` run `%TEMP%\_env.cmd` file is created and not deleted.

### What is Expected?
No files left in `%TEMP%` directory.

### How Did You Get This To Happen? (Steps to Reproduce)
```
Refreshenv
dir %TEMP%\_env.cmd
```

**Comment by ferventcoder** [comment]
We could consider this a security issue if that file has any environment variables in it that we don't want known.

**Comment by ferventcoder** [comment]
This has been merged at https://github.com/chocolatey/choco/commit/db8bf5a77d3103e97bcd05b317a6f55cb2cf5918 and will be released with 0.10.12. Thanks for your help!
