### ISSUE TITLE
Use "new" Curl/Tar feature in Spring Creator's Update to install Chocolatey

### ISSUE THREAD

**Issue by DarthSpock** [chocolatey/choco#1554]
**TEMPLATE FOR FEATURE REQUESTS:**

Microsoft ported BSD Tar and Curl to Windows 10. See [here](https://blogs.technet.microsoft.com/virtualization/2017/12/19/tar-and-curl-come-to-windows/) for more details. With these BSD tools now available for PS/CMD, can there be an installation option for installing Chocolately using these tools like we would on Linux? 

Aside: Technically anything installed through Chocolately could be installed now using these tools as well, makes one wonder what the future of Chocolately will look like.

**Comment by ferventcoder** [comment]
I'm not worried - install isn't the most important - it's management over time. https://github.com/chocolatey/choco/wiki/GettingStarted#what-is-chocolatey

**Comment by ferventcoder** [comment]
For installing Chocolatey itself, sounds like this is a docs request. Would you say that is correct?

**Comment by DarthSpock** [comment]
I think we can close this and call it collaboration with Microsoft on https://github.com/Microsoft/windows-dev-box-setup-scripts. Since that provides a method of installing chocolately. As far as docs go, I'd link to the github page I linked. Since you guys are becoming buddies and all, it might be a good idea to update the readme anyways and link the MS blog:https://blogs.msdn.microsoft.com/commandline/2018/05/08/join-us-for-a-hot-cup-o-chocolatey/ as well.

**Comment by DarthSpock** [comment]
Yes I realized I jumped the gun, the only difference is the powershell scripts include choco commands. I automatically assumed that meant downloading the project would install Chocolately. I can reopen if you like.

**Comment by bcurran3** [comment]
@DarthSpock - makes sense. I'm against prompting because I want to keep it completely scriptable, but I'm for adding an argument for it. Since we're off topic here, please open an issue for it there and I'll add the option for you. :)
