### ISSUE TITLE
What about a Login and Auto-Restore packages?

### ISSUE THREAD

**Issue by InsomniumBR** [chocolatey/choco#1555]
Hello guys,

First of all, thanks for the great work you have been doing!
And second, sorry in advance for any english mistakes.

I am an old "choco user", and I was thinking about something that could improve the adoption of chocolatey through tech community.

Sometimes when I erase my computer I usually do a get on my old packages using a batch file to download all the old packages that I used to have.  But sometimes (like today that I am on a new work) I found myself without this batch file and with a new computer.

Chocolatey if the first App I install a computer. For sure. Always.

So my proposal is to aggregate value to this great tool adding a feature that allow us to login on Chocolatey, list the package we already used (or used on the last year or two), and then select the desired packages (according to the computer objectives, sometimes for home, sometimes for work) and then restore all of them.

Wouldn't be great to have such features?

choco login
choco restore
   -> List recent packages (two years is my suggestion)
   -> Select packages
   -> Install

And looking for some more advanced...

choco save "Designer"
choco save "Home"
choco save "Dev"

and..
choco restore "Dev"
 -> Restore all the packages on my Dev (previously saved) list.

Please let me know what you think.

Regards,

**Comment by ferventcoder** [comment]
Howdy folks - this repo is about Chocolatey CLI, which exists on its own. This sounds like a feature for the community package repository, which is has a GitHub repo at https://github.com/chocolatey/chocolatey.org/issues.

**Comment by ferventcoder** [comment]
@InsomniumBR would you mind recreating this issue over there, referring to this url link and then closing this issue here? Thanks!

**Comment by ferventcoder** [comment]
> So my proposal is to aggregate value to this great tool adding a feature that allow us to login on Chocolatey, list the package we already used (or used on the last year or two), and then select the desired packages (according to the computer objectives, sometimes for home, sometimes for work) and then restore all of them.

I will say right off this is a no go, we don't track telemetry. The community repository does not associate anything about a chocolatey.org community account to a local choco install. Doing so would present potential privacy issues, plus added work for GDPR. So it's unlikely we'd want to approach it in this way.

However there may be other options that could be explored.

NOTE: The only thing that is tracked is IP address and that is to monitor potential excessive use.

**Comment by InsomniumBR** [comment]
@ferventcoder I am not talking about tracking or something that is happening on behalf of user. I am talking about a saving feature and retreving the packages list back. I think its a huge thing. I posted it on chocolatey.org, and I am closing this one.
