### ISSUE TITLE
Save downloaded installers for use on other computers

### ISSUE THREAD

**Issue by vertigo220** [chocolatey/choco#1567]
For those of use with slower internet, one major disadvantage to package managers vs manually downloading and installing programs is that with package managers, every computer has to download all the programs for itself, which takes a long time, whereas downloading the installers requires doing so just once then sharing them over the network or via flash drive. If Chocolatey was able to save the latest version of each downloaded package and share it over the network, so other computers on the network would check to see if anyone else has a package before downloadin it, that would speed things up immensely. Basically, it would function like Windows updates are supposed to in Win10 (I say supposed to because, big surprise, it doesn't seem to work).

**Comment by gep13** [comment]
@vertigo220 what you are describing is what we refer to a package internalization, and it is something that exists in the Business Editions of Chocolatey.  You can read more about it here:

https://chocolatey.org/docs/features-automatically-recompile-packages

This process creates a fully offline installable version of a Chocolatey package, that can then be used on other machines in your network.

**Comment by vertigo220** [comment]
Thanks. Just an idea, maybe that functionality could be added to the regular version but limited to only work between a limited number of computer, maybe three. Not sure how feasible that would be, but home users often have limited bandwidth, more so than businesses, and this feature would probably go a long way for some of them. Probably even more complicated, but maybe it could even be a separate purchasable module. Anyways, you can close the issue, unless you want to keep it open for discussion about the possibility of doing that.

**Comment by ferventcoder** [comment]
@vertigo220 You can explore setting the cacheLocation and see how that works for cross machine, just make sure you are not running two choco instances against the same files at the same time.

**Comment by ferventcoder** [comment]
For folks coming to this issue that represent organizations - the community repository isn't really recommended for organizational use. 

Note the following guide - https://chocolatey.org/docs/how-to-setup-offline-installation (organizational use and deployment) and the following disclaimer about the community repository - https://chocolatey.org/docs/community-packages-disclaimer (this is particularly important)
