### ISSUE TITLE
Show install location in package info

### ISSUE THREAD

**Issue by vertigo220** [chocolatey/choco#1568]
The info page for installed packages should show where the application is installed (its path) and, ideally, display it as a link that opens file manager to that location.

**Comment by ferventcoder** [comment]
Duplicate of #681

**Comment by ferventcoder** [comment]
Howdy @vertigo220, I've marked this as a duplicate of #681. Please subscribe/comment on that issue. Thanks!

**Comment by vertigo220** [comment]
Done. Should I submit this as an issue in the GUI repo?
