### ISSUE TITLE
Make search results include similar/related apps and "category" apps

### ISSUE THREAD

**Issue by vertigo220** [chocolatey/choco#1570]
For example, instead of searching for Firefox and then having to search Waterfox separately, searching for either one should result in the other being toward the top of the results, as well as other browsers. Searching for "browser" should also result in those two and others being toward the top of the results, instead of scattered with only a few on the first page (with the first result not even being a browser, and a couple being toward the bottom) and others even being pushed past the first paage. Similarly, you shouldn't have to search for multiple PDF apps separately just to find them; searching for one should show other PDf apps as well. There are, of course, many other examples, but that should illustrate the point.

**Comment by ferventcoder** [comment]
Is this a choco.exe issue, website issue, or GUI issue?

**Comment by vertigo220** [comment]
GUI. I'll submit an issue there in a couple days.

**Comment by gep13** [comment]
@vertigo220 I am closing to close this off.
