### ISSUE TITLE
Chocolately doesn't recognize when apps are updated externally

### ISSUE THREAD

**Issue by vertigo220** [chocolatey/choco#1573]
If an app is updated outside of Chocolatey, it's not reflected in Chocolatey. For example, Signal self-updates, so I installed version 1.7.1, it updated to 1.8.0, and _days_ later, after refreshing apps in Chocolatey it showed the current version as 1.7.1 and the latest version as 1.8.0.

**Comment by gep13** [comment]
Well, actually, it does.  This is one of the features of the licensed editions of Chocolatey.  You can read more about this here:

https://chocolatey.org/docs/features-synchronize

From an open source perspective the recommendation for applications that have a built in update mechanism is to use the `choco pin` command.  i.e. do the initial installation of the application with Chocolatey, and then allow the application to update itself.

**Comment by ferventcoder** [comment]
@vertigo220 more specifically, it's the auto-sync part of Package Synchronizer. It's also not going to see if someone uninstalls the software/app directly.

The open source edition is strictly a package manager and a package is in Chocolatey terminology is a nupkg. Chocolatey manages packages, packages manage software (installations, config, binaries, etc). When things are updated outside of Chocolatey, it's not going to see that if the package hasn't changed. We understand that is not always sufficient and so for licensed editions, we allow Chocolatey to do more with full system software management. We allow it to look at changes that have happened outside of Chocolatey and adjust the packaging to account for that. HTH

**Comment by ferventcoder** [comment]
Clarification to my last comment -  "It's also not going to see if someone uninstalls the software/app directly" is about Chocolatey open source not recognizing updates.

**Comment by gep13** [comment]
@vertigo220 we do try to provide information about the commands that are availalbe:

https://chocolatey.org/docs/commands-pin

Hmm, that would require the community package maintainers to provide this information.  I am not saying that this is impossible, but it would require buy-in, and also a modification to the nuspec file.

@ferventcoder what are your thoughts here?  Would this be a sensible addition to the meta data in the nuspec?  Worth creating a feature request issue?

**Comment by ferventcoder** [comment]
That could be interesting - what happens if someone internalizes the package and adds the settings/code to ensure it doesn't self-update? Or does the same using the community repo? 

Like what if there was a package parameter added to the package that allowed the self-update to be disabled (only this direction, not the reverse - auto-update is typically more secure by default)? Would it not have a file to enable a pin?

**Comment by gep13** [comment]
Hmmm, definitely some food for thought there.  @vertigo220 I think opening a new feature request issue around this topic would be a good idea.
