### ISSUE TITLE
Trivial change to document removal of 'cinst' wrapper in CHANGELOG.md, diff is attached.

### ISSUE THREAD

**Issue by ericsampson** [chocolatey/choco#1576]
Please consider adding text stating that the 'cinstm' wrapper was removed at the same time that 'installmissing' was, to help people upgrading from older versions and/or finding this page via search engine when querying 'cinstm'.

[diff.txt](https://github.com/chocolatey/choco/files/2013929/diff.txt)

**Comment by ferventcoder** [comment]
Hi @ericsampson - are you able to provide a PR? That would be easier and we do agree that this would be a trivial change.

**Comment by ericsampson** [comment]
Done: https://github.com/chocolatey/choco/pull/1577
