### ISSUE TITLE
Choco source add allows empty url

### ISSUE THREAD

**Issue by jirkapok** [chocolatey/choco#1582]
Steps to reproduce on version 0.10.11:
`choco source add -n="sourcename"`
results in source without url address
`sourcename - | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False`

Expected result:
Creation of source without an address should be prohibited, since it doesn't make sense.

**Comment by SeanKilleen** [comment]
Was checking this out as an `up-for-grabs` issue and noticed that there appear to be commits referencing it  that seem like it may be resolved now.

Can this issue be closed now?

**Comment by jirkapok** [comment]
No, there issue isnt fixed, since its pull request isnt merged yet more than five moths. I already asked on Gitter discussion, what i can do more for this to be resolved, but no progress yet.

**Comment by ferventcoder** [comment]
This looks good and now has a milestone attached to it. Apologies, typically things don't close that are valid until the work has been completed in the repository. You'll also see a milestone (version) that will indicate where this released.

**Comment by gep13** [comment]
This was merged into stable at https://github.com/chocolatey/choco/commit/548196a74de1d24b63e6f2bd6d959fbe77bb8cfd

**Comment by gep13** [comment]
Merged into stable to be released with 0.10.12.
