### ISSUE TITLE
Object reference exception when there are no sources

### ISSUE THREAD

**Issue by jirkapok** [chocolatey/choco#1584]
Steps to reproduce on 0.10.11:
* configure default chocolatey source if not present
* install git package (package is not relevant, applies to any package)
* remove all package sources
* call ```choco uninstall git -y```

Actual result:
Following error message is returned: ```Object reference not set to an instance of an object.```

Expected result:
No message is shown and package is successfully uninstalled, since you dont need package sources for uninstall.

Note:
* The same issue applies also for other commands (but i didnt note which one was the second).
* Exception is thrown from NugetCommon.GetRemoteRepository line 80, where split method fails null sources property.

**Comment by ferventcoder** [comment]
I think there was an age old issue this is related to. We didn't find it because we didn't know what it was related to. This is helpful.

**Comment by ferventcoder** [comment]
Thanks for your contribution! This has been merged and will be released in 0.10.12.
