### ISSUE TITLE
Overhaul the moderation guidelines

### ISSUE THREAD

**Issue by pauby** [chocolatey/choco#1588]
The moderation guidelines are a good start but are not clear on many aspects. I feel the documentation should be overhauled to provide clear guidance on package moderation while still leaving the moderator with freedom to use their judgement.

**Comment by ferventcoder** [comment]
Hi Paul, Let's open this at https://github.com/chocolatey/chocolatey.org.

**Comment by ferventcoder** [comment]
Moved to https://github.com/chocolatey/chocolatey.org/issues/575
