### ISSUE TITLE
RefreshEnv.cmd and WM_SETTINGCHANGE

### ISSUE THREAD

**Issue by runxctry** [chocolatey/choco#1589]
Hello,

RefreshEnv.cmd has been a godsend!  Thank you!  

This works well in a *currently open* command window.

However, I've learned that the WM_SETTINGCHANGE signal needs to be broadcasted to the system for the Path change to take effect for *all command windows* .  

Anecdotally, I've found I've had to close all command windows and reopen a new one for the Path change to take effect.  (Because... Windows).

Recommending that you broadcast WM_SETTINGCHANGE when you set the PATH.   As an idea, keeping the broadcast message in a different script might help with reusability and maintain separation-of-duties.

**Comment by ferventcoder** [comment]
WM_SETTINGCHANGE has no effect on conmmand windows.

**Comment by ferventcoder** [comment]
Ask me how I know ;)

https://github.com/chocolatey/choco/blob/2f588e755e33e4476f5170494c097932a23e1554/src/chocolatey.resources/helpers/functions/Set-EnvironmentVariable.ps1#L99-L126

**Comment by ferventcoder** [comment]
This is why refreshenv is required to be run in every command shell, so they update as well.

**Comment by ferventcoder** [comment]
Heck, this is why refreshenv exists in the first place 👍
