### ISSUE TITLE
PHP 7.2.7 package ignores /InstallDir param

### ISSUE THREAD

**Issue by SharakPL** [chocolatey/choco#1597]
`--params '"/ThreadSafe ""/InstallDir:C:\PHP"""'` doesn't work with current release (7.2.7). You need to use all params in the same " ":
`choco install php --params '"/ThreadSafe /InstallDir:c:\PHP"'`

**Comment by SharakPL** [comment]
@bcurran3 honestly I can't say if params handling is a problem with chocolatey or with this specific package. Another one would be this: when updating php with simple `choco upgrade php` or `choco upgrade all` package settings (params used during install) are completely ignored so instead of updating php I get another fresh copy with default settings (NTS version in default locations c:/tools/php). Again I'm not sure if it's package related problem or if it's something that needs to be fixed inside chocolatey.

Maybe I clicked wrong link or something but I tried to report this specific package and it just kept sending mi here, to this issue tracker, where there was information to not use it for specific package reporting and that's another thing rather confusing. Maybe it would be better if each package had its own repository here.

**Comment by bcurran3** [comment]
Do you have useRememberedArgumentsForUpgrades set? If not, take a look at:
https://chocolatey.org/docs/chocolatey-configuration

As for where to report and links, the package page is where you'd want to start:
https://chocolatey.org/packages/php

On that there is a Contact Maintainers link:
https://chocolatey.org/packages/php/ContactOwners

If there is a package problem, clicking the Package Source link:
https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/php

... will get you to the Issues area for the package:
https://github.com/chocolatey/chocolatey-coreteampackages/issues

So if you feel it's a choco.exe problem, you're in the right place. If you feel it's a package problem, you're in the wrong place... but I drew you a map. :)

**Comment by SharakPL** [comment]
Thanks very much. This was really helpful. Just one more thing...
I used `choco feature enable -n=useRememberedArgumentsForUpgrades`. Will `choco upgrade` use params for packages installed earlier or do I need to install packages again to have their params rememberd?

**Comment by bcurran3** [comment]
YW. You're going to have to re-install if the arguments weren't captured previously.
