### ISSUE TITLE
FLASH ISSUE

### ISSUE THREAD

**Issue by RevanHD** [chocolatey/choco#1599]
So when i try to enter my client, it comes up with plug-in blocked. Ive enabled flash in the browser and tried both chrome and internet explorer. The same issue. For some reason it just wont load. Ive tried it on my vps and on my laptop. The emu is open, and working fine. There are no console errors either so.

**Comment by ferventcoder** [comment]
We don't have any flash to my knowledge in choco.

**Comment by ferventcoder** [comment]
Not sure what this request is in reference to, but if it is with the website, the new issue triage process should have led you to log an issue over there. If it is with a package, it should have referenced you to the right place to request support. HTH
