### ISSUE TITLE
Logging - Choco --log-file parameter does not create log files relative to current directory

### ISSUE THREAD

**Issue by pauby** [chocolatey/choco#1603]
This was checked using FOSS and all licensed versions of v0.10.11 with the same results.

### What You Are Seeing?

When using the `--log-file` parameter I see the following:

* If you specify a relative filename (ie. `--log-file=test.log`) the file is created under the Chocolatey ProgramData folder rather than in the current folder;
* If you specify a relative path (ie. `--log-file=temp\test.log`) an empty folder `temp` is created under the current folder and the full path (`temp\test.log`) is created under the Chocolatey ProgramData folder;
* If you specify a full path (ie. `--log-file=c:\temp\test.log`) the log file is created correctly at `c:\temp\test.log`;

### What is Expected?

I'd expect relative paths to be create under the current folder and not under Chocolatey ProgramData.

### How Did You Get This To Happen? (Steps to Reproduce)

`choco new test <LOG FILE PARAMS FROM ABOVE>`

**Comment by ferventcoder** [comment]
Added to the backlog!

**Comment by ferventcoder** [comment]
This will be released with 0.10.12.
