### ISSUE TITLE
ChocolateyLastPathUpdate stores date as locale-specific 

### ISSUE THREAD

**Issue by fredrikaverpil** [chocolatey/choco#1604]
### What You Are Seeing?

On my Windows 10 box, the `ChocolateyLastPathUpdate` environment variable's value contains Swedish, non-Ascii characters (such as `å` or `ö`) for certain timestamps because my date and currencies settings in Windows are set to Swedish. This has caused several third-party applications which read the environment to crash or malfunction.

Indeed, this problem lies more with the third-party applications than with choco. However, I'd argue it's bad form to store the date like this if this isn't necessary.

Example value when date and currency format is set to English: `Tue Apr 24 11:17:15 2018`.
Unfortunately, I don't have an existing example string in Swedish anymore, as I had to change this. But as an example, Saturday is "Lördag" in Swedish and abbreviated into `Lör`.

**Comment by ferventcoder** [comment]
@fredrikaverpil So we should probably store it as non-locale specific it sounds.

**Comment by SneWs** [comment]
So we've hit this on a 300+ large dev team and it brought down parts of our core infra. We've worked around it for now, but it seems that this has been open for quite some time... Any plans on fixing this soon? If not, I'll spend some time fixing this up and submitting a PR if that's OK?

**Comment by SneWs** [comment]
Any update on this? Would be quite useful to get this merged and pushed in a new release.

**Comment by ferventcoder** [comment]
@SneWs this should go in with 0.10.12.

**Comment by ferventcoder** [comment]
This has been merged into stable at https://github.com/chocolatey/choco/commit/7e1143a248b8c4e99a9edc85db579e1566f8c5b3 and will be released with 0.10.12.

**Comment by SneWs** [comment]
Thank you. And sorry for not being active the last few weeks, we've been moving to a new house and well, it's been quite time consuming.

Great news that it finally goes into a release 👍

**Comment by ferventcoder** [comment]
@SneWs I fully understand the moving aspect. Did that this summer and it was very time consuming.
