### ISSUE TITLE
CallDepthOverflow on every operation

### ISSUE THREAD

**Issue by thebetteridiot** [chocolatey/choco#1611]
For no apparent reason, Chocolatey started giving me _CallDepthOverflow_ error on every single command I try. I'm using Windows 10 Pro 64-bit. I have made no major changes to my system recently. I get _CallDepthOverflow_ even entering _choco_ without any parameters.

Here's the complete output:
`The script failed due to call depth overflow.
    + CategoryInfo          : InvalidOperation: (0:Int32) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CallDepthOverflow` 

Right now, Chocolatey is completely unusable to me. I already tried reinstalling Chocolatey with no success. Any ideas how to rectify this?

**Comment by thebetteridiot** [comment]
Well, I'm an idiot. I placed a script by the name 'choco' in a folder I forgot was in my system path. The script called certain routine in Chocolatey.

**Comment by ferventcoder** [comment]
It happens.
