### ISSUE TITLE
Add ability to get consistent hash of ConfigFileSettings class

### ISSUE THREAD

**Issue by gep13** [chocolatey/choco#1612]
We need the ability to be able to quickly determine whether something has changed with the chocolatey.config file.  This would allow us to make informed decisions about whether something has changed in the configuration since the last time it was inspected.  This is typically done through the `GetHashCode` code of an object, however, in order for this to be reliable, some modifications are required to ensure that the results are consistent.

**Comment by ferventcoder** [comment]
I want to say this fixes a bug as well?

**Comment by ferventcoder** [comment]
With grabbing the config file and thinking there may be some changes?

**Comment by gep13** [comment]
@ferventcoder possibly.  A comparison of the hash would still need to be done in order to see if a change had occurred.
