### ISSUE TITLE
source list - running with -r fails to escape pipe (|) char

### ISSUE THREAD

**Issue by jborean93** [chocolatey/choco#1614]
### What You Are Seeing?
When using `choco source list -r`, values the already contain a pipe `|` character are not escaped making it impossible to reliably parse the output programmatically. An example output where the source name and username contain a pipe is

`test|pipe|https://chocolatey.org/api/v2/|False|user|pipe||0|False|False|False`

When you compare it to the default API

`Chocolatey|https://chocolatey.org/api/v2/|False|||0|False|False|False`

You can see there are 2 more "columns" because both the name and user column contain the pipe char.

### What is Expected?
Not sure, usual psv practices are to either quote all the values or just quote the values that contain the delimiter char, e.g.

`"test|pipe"|https://chocolatey.org/api/v2/|False|"user|pipe"||0|False|False|False`

### How Did You Get This To Happen? (Steps to Reproduce)
Create the source with

`choco source add --name "test|pipe" --source https://chocolatey.org/api/v2/ --user "user|pipe" --password password`

List the sources with

`choco source list -r`

and you get

`test|pipe|https://chocolatey.org/api/v2/|False|user|pipe||0|False|False|False`

**Comment by ferventcoder** [comment]
@jborean93 interesting - that's definitely unexpected. Something we should look to fix.

**Comment by ferventcoder** [comment]
This has been completed for Chocolatey v0.10.12.

**Comment by ferventcoder** [comment]
This was implemented on stable at https://github.com/chocolatey/choco/commit/7f15fb0a14a71cfba340647f5b23828eef054790

**Comment by jborean93** [comment]
@ferventcoder thanks for the update. I haven't tested to see if it's possible but wouldn't the changes in https://github.com/chocolatey/choco/commit/7f15fb0a14a71cfba340647f5b23828eef054790 mean that if the field already has a double quote the parsing would now be broken? There is a .net class you can potentially use called [TextFieldParser](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.fileio.textfieldparser?view=netframework-4.7.2) but it looks like it's not in .NET core which may be an issue in the future.

**Comment by ferventcoder** [comment]
@jborean93 how would the field have a double quote? Perhaps there is a bit more we should do here. I could see an apostrophe, but a quote in the middle of the username would be really weird. However, so would a pipe, and here we are. Thoughts?

**Comment by jborean93** [comment]
Oh looking at the commit it is only quoting the username field but the repo name itself can also contain pipe characters. I'm just trying to think of a way that makes this generic to anything creating a PSV and not just a field within source.

However as for why the username would contain a quote, I would have no idea. People seem to want to do really weird things and being defensive about it is probably best.

**Comment by ferventcoder** [comment]
@jborean93 added for names as well.

**Comment by jborean93** [comment]
@ferventcoder I take back what I said about not being able to use `"`. We actually test out both `|` and `"` as the source name, as well as some other non alphanumeric chars in our `win_chocolatey_source` test because of this issue. We parse the XML directly because we couldn't parse the command output reliably and this makes sure we don't regress in our feature offering for the future.

This means that the simple quote the value with `"` if it contains `|` still won't work in these cases.

**Comment by ferventcoder** [comment]
@jborean93 perhaps open a new issue on this?

**Comment by jborean93** [comment]
Honestly I'll probably give up on the `-r` output in favour of https://github.com/chocolatey/choco/issues/1252. Having the output in JSON is a lot easier to parse for many libraries and is built into .NET.
