### ISSUE TITLE
How to install downloaded packages?

### ISSUE THREAD

**Issue by hitaspdotnet** [chocolatey/choco#1617]
Hi,
I want to install Meteor using Choco. This package has ~180 MB, I can see the downloaded package in temp but Choco starts downloading every time.

**Comment by hitaspdotnet** [comment]
```
PS D:\> choco install meteor
Chocolatey v0.10.11
[Pending] Removing incomplete install for 'meteor'
Installing the following packages:
meteor
By installing you accept licenses for the packages.
Progress: Downloading meteor 0.0.2... 100%

meteor v0.0.2 [Approved]
meteor package files install completed. Performing other installation steps.
The package meteor wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[N]o/[P]rint): Y

Downloading meteor 64 bit
  from 'https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_64'
Progress: 100% - Completed download of C:\Users\Forouji\AppData\Local\Temp\chocolatey\meteor\0.0.2\meteor-bootstrap-os.windows.x86_64.tar.gz (177.2 MB).
Download of meteor-bootstrap-os.windows.x86_64.tar.gz (177.2 MB) completed.
```

This is my last try, meteor and meteor bootstrap downloaded again

> how you are seeing the file get downloaded each time?

I can see status bar of download with speed/s and download bytes!!

**Comment by gep13** [comment]
Right, so now that this is downloaded, and installed, do what I did in step 4 above, and then try installing again?

Does it still attempt to download the file again?

**Comment by hitaspdotnet** [comment]
@gep13 meteor not downloaded again but meteor-bootstrap (that biggest lib) downloaded again. Both exist in `C:\Users\User\AppData\Local\Temp\chocolatey\meteor\0.0.2`

**Comment by hitaspdotnet** [comment]
```
PS C:\Windows\system32> choco install meteor
Chocolatey v0.10.11
Installing the following packages:
meteor
By installing you accept licenses for the packages.

meteor v0.0.2 [Approved]
meteor package files install completed. Performing other installation steps.
The package meteor wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[N]o/[P]rint): Y

Downloading meteor 64 bit
  from 'https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_64'
Progress: 100% - Completed download of C:\Users\Forouji\AppData\Local\Temp\chocolatey\meteor\0.0.2\meteor-bootstrap-os.windows.x86_64.tar.gz (177.2 MB).
Download of meteor-bootstrap-os.windows.x86_64.tar.gz (177.2 MB) completed.
Extracting C:\Users\Forouji\AppData\Local\Temp\chocolatey\meteor\0.0.2\meteor-bootstrap-os.windows.x86_64.tar.gz to C:\Users\Forouji\AppData\Local\Temp\chocolatey\meteor\0.0.2...
C:\Users\Forouji\AppData\Local\Temp\chocolatey\meteor\0.0.2
Extracting C:\Users\Forouji\AppData\Local\Temp\chocolatey\meteor\0.0.2\meteor-bootstrap-os.windows.x86_64.tar to C:\Users\Forouji\AppData\Local...
C:\Users\Forouji\AppData\Local
PATH environment variable does not have C:\Users\Forouji\AppData\Local\.meteor in it. Adding...
***************************************

Meteor has been installed!

To get started fast:

  $ meteor create ~/my_cool_app
  $ cd ~/my_cool_app
  $ meteor

Or see the docs at:

  https://docs.meteor.com

***************************************
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of meteor was successful.
  Software installed to 'C:\Users\Forouji\AppData\Local'

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

**Comment by gep13** [comment]
I am sorry, but I am simply unable to replicate what you are saying.

A subsequent execution of `choco install meteor` is not resulting in the file being downloaded again.  Chocolatey is using the tar.gz file that is already in the temp folder:

![image](https://user-images.githubusercontent.com/1271146/42935960-d614daf0-8b42-11e8-8a03-28cb92c00041.png)

If I remove the file and install meteor again, I see this:

![image](https://user-images.githubusercontent.com/1271146/42936177-5605d71e-8b43-11e8-80f8-b6ac1952a908.png)

i.e. the download occured

**Comment by gep13** [comment]
Also, I only see one file in the `0.0.2` folder:

![image](https://user-images.githubusercontent.com/1271146/42936362-c794354c-8b43-11e8-97ac-6c403db4d0b4.png)

**Comment by hitaspdotnet** [comment]
I think you used the wrong image because in the second image you have downloading meteor. I lost +500 MB of my limited network usage, I don't know how to reproduce the problem. Hover thanks for fast replies.

**Comment by hitaspdotnet** [comment]
![image](https://user-images.githubusercontent.com/23167047/42936777-4b43a65c-8b62-11e8-9bdd-381663c518e7.png)

**Comment by gep13** [comment]
Nope, I don't think I have used the wrong images.

The first image shows that meteor is not downloaded on the second execution of `choco install meteor`.  However, if I remove the file from the temp folder, and again re-run `choco install meteor` the file is downloaded.

**Comment by gep13** [comment]
I am sorry, I don't know how to explain what is going on, in your environment.  This simply isn't happening for me on a fresh Virtual Machine.  I would suggest looking through the chocolateyInstall.ps1 to see if there is something specific in there that would cause something in your environment to force a re-download of the file.  I don't believe that this is an issue with Chocolatey.  The temp folder that you are using appears to be different from the one I am using.  Have you altered the chocolatey config on your machine in any way?

**Comment by hitaspdotnet** [comment]
I'm using [Choco Docs](https://chocolatey.org/docs/installation#install-with-powershellexe). I haven't any change configuration. 

>  The temp folder that you are using appears to be different from the one I am using.

And as you can see, the last modified time is now (local time), so previous files are rewritten by newly downloaded files.

**Comment by gep13** [comment]
Random question...  Are you using a 64bit version of Windows?

**Comment by hitaspdotnet** [comment]
@gep13 Yes

**Comment by ferventcoder** [comment]
Sometimes depending on what Choco detects for an installation and the cached files versus what it sees as a download, it may attempt to re-download the files - that's normal behavior and by design to pick up on files that have changed or an erroneous download versus what is expected. It's possible that what is being advertised as the content length from the distribution location is different than what you have locally, triggering a re-download. If you are using `--force` or `-f`, that will always trigger a re-download (also force is not actually recommended). 

After reading through this and the original question, I'm not sure what is being requested - it appears to have installed meteor correctly. If there is more that you would like to follow up on, let's clarify expected behavior by creating a new issue and filling out the template. Thanks!
