### ISSUE TITLE
Files missing after choco extracts .nupkg

### ISSUE THREAD

**Issue by Gridluck** [chocolatey/choco#1618]
After downloading .nupkg, choco fails to extract all of the files missing some, however manual run of below does manage to extract all files with no issue
[choco/tools]/7z.exe x -aoa -bd -bb1 -o'[folderout]' -y '[file.nupkg]'

**Comment by bcurran3** [comment]
Since this hasn't been officially addressed, I'll unofficially address it.

_rels (folder)
package (folder)
[Content_Types].xml

...aren't used by Chocolatey.

**Comment by ferventcoder** [comment]
@Gridluck which files?

**Comment by ferventcoder** [comment]
Please make sure you are using the report issues template when creating a bug report - https://github.com/chocolatey/choco/issues/new?template=zChocoReportIssue.md

**Comment by mtis88** [comment]
I'm having an issue where files without a file extension are not being extracted from the nuget.

**Comment by TheCakeIsNaOH** [comment]
Closing as no response.

@martin8801 if you are still having that problem, please open a new issue with more information, so we have a better chance of figuring out what is going on.
