### ISSUE TITLE
Automatic package updated: ketarin log doesn't contain date with German date format

### ISSUE THREAD

**Issue by dhilgarth** [chocolatey/choco#162]
My Windows machine is configured to use German date format. This seems to cause problems with the `ketarinupdate.cmd` script.

The log file it creates is named `ketarin._1200.log`.

`date /t` is local dependent, so it is a bad idea to use it in the way it is used in the script.
Consider using `date.exe` from UnxUtils as described [here](http://stackoverflow.com/a/1951681/572644).

Quick fix for German users: Replace the existing line with this one:
```
For /f "tokens=1-3 delims=/. " %%a in ('date /t') do (set mydate=%%c%%b%%a)
```

**Comment by norbert6** [comment]
Already mentioned in the Package-Updater Repo:
https://github.com/chocolatey/chocolatey-package-updater/issues/14

**Comment by dhilgarth** [comment]
Thanks for noting
