### ISSUE TITLE
Unable to Install Git

### ISSUE THREAD

**Issue by jpsantosdeveloper7** [chocolatey/choco#1622]
PS C:\WINDOWS\system32> choco upgrade git
Chocolatey v0.10.11
Upgrading the following packages:
git
By upgrading you accept licenses for the packages.
git v2.18.0 is the latest version available based on your source(s).

Chocolatey upgraded 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
PS C:\WINDOWS\system32> choco install git --force
Chocolatey v0.10.11
Installing the following packages:
git
By installing you accept licenses for the packages.
git v2.18.0 already installed. Forcing reinstall of version '2.18.0'.
 Please use upgrade if you meant to upgrade to a new version.
Progress: Downloading git 2.18.0... 100%

git v2.18.0 (forced) [Approved]
git package files install completed. Performing other installation steps.
 The install of git was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
PS C:\WINDOWS\system32> git --version
git : The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ git --version
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by gep13** [comment]
@jpsantosdeveloper7 thanks for reaching out, however, this is not the place to ask questions about issue with a particular package.

As you would have hopefully seen when creating this issue, when asking about a package, our advice is the following:

> STOP RIGHT HERE - DO NOT CREATE A TICKET FOR PACKAGES ON THIS REPOSITORY

> This is the repository for choco.exe, the command line interface for Chocolatey, and issues/feature suggestions should be limited to only choco. For a package failure, typically you would be reporting an issue with a package on the community package repository, which is not what this repository represents. In fact, the community repository and all of its packages represents about 5% of the packages in existence and less than half of the usage of choco itself. 

>  In other words Chocolatey != Chocolatey.org Packages.

> For all things packages, you have two routes:

> 1. If you are having issue with a package or you want to see an enhancement, please see https://chocolatey.org/docs/package-triage-process (Package Triage Process / Becoming a maintainer of existing packages).
> 2. If you are looking for packages to be added to the community package repository (aka https://chocolatey.org/packages), please see https://chocolatey.org/docs/package-triage-process#package-request-package-missing (Package Requests).

**Comment by ferventcoder** [comment]
To follow up, it's likely git.install that was needing to be forced to be reinstalled. But like @gep13 mentioned, that should be asked elsewhere.
