### ISSUE TITLE
'choco install' command shows 'How do you want to open this file'

### ISSUE THREAD

**Issue by jawn** [chocolatey/choco#1625]
### What You Are Seeing?

Windows shows this:
![image](https://user-images.githubusercontent.com/1705112/43830192-09d327d4-9b01-11e8-92d9-ebb5e92d7d11.png)

### What is Expected?

Package is installed.

### How Did You Get This To Happen? (Steps to Reproduce)

1. Start admin powershell
1. Run command: `choco install package` where the package name is any valid package name. Same results when adding --debug --verbose, so no log output is available.

### Workaround:

Using the `cinst package` alias works as expected.

### Version info

Chocolatey v0.10.11
PowerShell version : 5.1.17134.112
Windows 10 version 1803

**Comment by bcurran3** [comment]
Try re-installing Chocolatey. I bet your chocolatey\bin\choco.exe file is corrupt.

**Comment by pauby** [comment]
@ferventcoder I added this [here](https://github.com/chocolatey/choco-wiki/issues/92)

**Comment by jawn** [comment]
Deleting the `C:\Windows\System32\choco` as instructed fixes it for me!

However, the troubleshooting steps required using a `cmd `prompt instead of `powershell`:

Test results for `where choco` :
* From Powershell non-admin: returns without output.
* From Powershell admin: returns without output.
* from cmd non-admin: 
> C:\Windows\System32\choco
> C:\ProgramData\chocolatey\bin\choco.exe

**Comment by pauby** [comment]
@jawn You've not done what was suggested by @ferventcoder.

`where choco` will give you no output as `where` in PowerShell is an alias for `where-object`. The command to use is:

```
where.EXE choco.exe
```

(my emphasis) Very important distinction.

**Comment by ferventcoder** [comment]
We'll be sure to include that distinction in the notes, as most would believe that you can drop the `.exe` and get the same result. Even including the word "exactly" as I did above was not enough. This will be handled by the issue @pauby linked.

**Comment by jawn** [comment]
@ferventcoder Thanks for pointing out exactly why where didn't work. Old habits die hard.
