### ISSUE TITLE
Windows 10 Install error - An exception occurred during a WebClient request

### ISSUE THREAD

**Issue by FrankGlez** [chocolatey/choco#1626]
### What You Are Seeing?
Error in installing choco.
I have tried to google the error and arrived at issue #1462 'Cannot install Chocolatey on a newly formatted Windows 10'
This issue is similar, but not exactly the same since there is no 403 error.

### What is Expected?
Installed Chocolatey on Windows 10.

### How Did You Get This To Happen? (Steps to Reproduce)
Pasted the following into an admin shell in Windows 10:
@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"

### Output Log

C:\windows\system32>@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
Getting latest version of the Chocolatey package for download.
Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.11.
Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
At line:167 char:3
+   $downloader.DownloadFile($url, $file)
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Extracting C:\Users\gonzaf03.SJM\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\gonzaf03.SJM\AppData\Local\Temp\chocolatey\chocInstall...

ERROR: The system cannot find the file specified.
C:\Users\gonzaf03.SJM\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip

System ERROR:
The system cannot find the file specified.
Unable to unzip package using 7zip. Perhaps try setting $env:chocolateyUseWindowsCompression = 'true' and call install again. Error: 7-Zip encountered a fatal error while extracting the files
At line:216 char:9
+     2 { throw "$errorMessage 7-Zip encountered a fatal error while ex ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to unzip...cting the files:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to unzip package using 7zip. Perhaps try setting $env:chocolateyUseWindowsCompression = 'true' and call install again. Error: 7-Zip encountered a fatal error while extracting the files

C:\windows\system32>

**Comment by ferventcoder** [comment]
Filed over at https://github.com/chocolatey/chocolatey.org/issues/591
