### ISSUE TITLE
Severe reliability issue on API endpoint https://chocolatey.org/api/v2/

### ISSUE THREAD

**Issue by HouzuoGuo** [chocolatey/choco#1629]
### What You Are Seeing?

Since earlier today (2018-08-21), choco installation of a large group of packages is taking a lot longer, upon closer investigation it appears that https://chocolatey.org/api/v2/ does not respond in time - while it normally responds in less than two seconds, today the API endpoint is timing out sporadically (~30% of all requests).

The host is an idle windows server 2016 on AWS and does not shown any other anomaly throughout its operation in the past several weeks.

### How Did You Get This To Happen? (Steps to Reproduce)
- Repeatedly run `choco install` on any existent or non-existent package name.

### Output Log
https://gist.github.com/HouzuoGuo/9c004b856d5409c7286127cd1903c7ab

Observe that:
- The first installation attempt of non-existent package (bzip2) took 2 seconds to receive a response from https://chocolatey.org/api/v2/: https://gist.github.com/HouzuoGuo/9c004b856d5409c7286127cd1903c7ab#file-gistfile1-txt-L90
- The second attempt that took place immediately after the first time reported timed out HTTP request after 100 seconds of delay: https://gist.github.com/HouzuoGuo/9c004b856d5409c7286127cd1903c7ab#file-gistfile1-txt-L200

**Comment by yevmel** [comment]
searching for packages on https://chocolatey.org is very slow too.

**Comment by ajh0912** [comment]
I'm getting a lot of 

> The remote server returned an error: (503) Server Unavailable. Service Unavailable

When trying choco install

Earlier searching on the website for packages was timing out or very slow

Trying to install chocolately was getting errors due to 503ing https://chocolatey.org/install.ps1, retried it and it did download

**Comment by sonjz** [comment]
I noticed an issue with api/v2/ not responding Aug 14th as well, it started working after about an hour after noticing the issue...

https://twitter.com/sonjz/status/1029426681524543488

**Comment by pauby** [comment]
See [this issue](https://github.com/chocolatey/chocolatey.org/issues/290#issuecomment-414740134)

**Comment by HouzuoGuo** [comment]
The issue appears to have been resolved.

**Comment by brandonhawbaker** [comment]
No, it's not resolved.  It's still very unreliable....

**Comment by nissant** [comment]
I am getting many errors when trying to install packages:
2019-11-30 16:08:20,761 13956 [ERROR] - cmder not installed. An error occurred during installation:
 The remote server returned an error: (503) Server Unavailable. Service Unavailable

**Comment by brandonhawbaker** [comment]
@nissant I'm getting the same errors over and over again.  When I try to access specific packages to download them locally I regularly get errors on chocolatey.org.  Virtually every package is not downloading properly from chocolatey.org.  I'm just downloading all of them locally at this point.

**Comment by AdmiringWorm** [comment]
@nissant @brandonhawbaker 
please follow the chocolatey status page, there are some slow and intermittent connection issues happening to the community repository: https://status.chocolatey.org/issues/2019-11-29-slow-and-intermittent-connection-issues/

**Comment by brandonhawbaker** [comment]
Thanks Kim, this is a cool website in the future for status updates.

https://status.chocolatey.org/

**Comment by AdmiringWorm** [comment]
@brandonhawbaker be aware that site is manually updated by the chocolatey staff, as such it may take some time when problems occur until the status page is updated.

**Comment by jpluimers** [comment]
I just learned there has been #37 (currently titled "Receive messages (like maintenance messages) from servers") for a while.

Please all upvote the first comment there so it gets more traction.


> See [this issue](https://github.com/chocolatey/chocolatey.org/issues/290#issuecomment-414740134)

That is a 404-error by now. @pauby, did you mean <https://github.com/chocolatey/choco/issues/290#issuecomment-414740134>?

If not, which issue did you mean?
