### ISSUE TITLE
package installation fails with .chocolateyPending not being accessible

### ISSUE THREAD

**Issue by laur89** [chocolatey/choco#1633]
### What You Are Seeing?
vcxsrv package installing oddly. Not sure if issue with choco.exe or the package.

### What is Expected?
Package to be installed _and_ recognized by choco.

### How Did You Get This To Happen? (Steps to Reproduce)
    choco install vcxsrv

Failed with the good 'ol 

    Installing 64-bit vcxsrv...
    vcxsrv has been installed.
    vcxsrv not installed. An error occurred during installation:
     Access to the path 'C:\ProgramData\chocolatey\lib\vcxsrv\tools\vcxsrv-64.1.20.1.1.installer_x64.exe' is denied.
    The process cannot access the file 'C:\ProgramData\chocolatey\lib\vcxsrv\.chocolateyPending' because it is being used by another process.

Refer to [console output](https://gist.github.com/laur89/90e5f8e42c3ab70bc92e2aa6ab402d66) of an installation attempt (this was already nth try, not first).

Seems like the installer tried to restart system and failed? Not sure.

It's noteworthy that trying to uninstall it, choco returns

    Failures
     - vcxsrv - vcxsrv is not installed. Cannot uninstall a non-existent package. 

Yet the application is installed under `C:\Program Files\VcXsrv` and is runnable.
### Output Log

Log from the very first installation attempt (ie no -vd flags provided): [log](https://gist.github.com/laur89/57cd9bb06c8850924bb85675d4463516)
Log of an installation attempt (with -vd): [log](https://gist.github.com/laur89/c4cfb599ee20255c41c18ff41b5af224)

Log (not console output) seems not to be affected by the -vd options, but included both versions just in case.

-----------------------
Note another package, autohotkey.portable, installed just fine.

    PS C:\ProgramData\chocolatey\lib> ls

        Directory: C:\ProgramData\chocolatey\lib

    Mode                LastWriteTime         Length Name
    ----                -------------         ------ ----
    d-----       25/08/2018     18:29                autohotkey.portable
    d-----       25/08/2018     17:54                chocolatey
    d-----       25/08/2018     19:51                vcxsrv

    PS C:\ProgramData\chocolatey\lib\vcxsrv> ls

        Directory: C:\ProgramData\chocolatey\lib\vcxsrv

    Mode                LastWriteTime         Length Name
    ----                -------------         ------ ----
    d-----       25/08/2018     19:51                legal
    d-----       25/08/2018     19:52                tools
    -a----       25/08/2018     19:51              9 .chocolateyPending
    -a----       25/08/2018     19:51       81909240 vcxsrv.nupkg
    -a----       25/08/2018     19:51           1502 vcxsrv.nuspec

    PS C:\ProgramData\chocolatey\bin> ls

        Directory: C:\ProgramData\chocolatey\bin

    Mode                LastWriteTime         Length Name
    ----                -------------         ------ ----
    -a----       25/08/2018     18:29          37888 Ahk2Exe.exe
    -a----       25/08/2018     18:29          36352 AutoHotkey.exe
    -a----       04/05/2018     18:09         143496 choco.exe
    -a----       04/05/2018     18:09         143496 chocolatey.exe
    -a----       04/05/2018     18:09         143496 cinst.exe
    -a----       04/05/2018     18:09         143496 clist.exe
    -a----       04/05/2018     18:09         143496 cpack.exe
    -a----       04/05/2018     18:09         143496 cpush.exe
    -a----       04/05/2018     18:09         143496 cuninst.exe
    -a----       04/05/2018     18:09         143496 cup.exe
    -a----       04/05/2018     18:09         143496 cver.exe
    -a----       04/05/2018     18:09           2283 RefreshEnv.cmd
    -a----       25/08/2018     17:54             21 _processed.txt

**Comment by bcurran3** [comment]
I'm guessing you're AV interfered. Try with your AV disabled.

**Comment by bcurran3** [comment]
@laur89 Your AV CAN interfere with just a specific package (or more appropriately the program in the package). I saw it happen a few months ago with AutoHotKey where a specific version of AutoHotKey was flagged by Windows Defender and Windows Defender prevented access to the file; i.e. Access denied. You should still check your AV logs for reference to the program. You could also just click the download URL in the chocolateyInstall.ps1 file, download the file, and see if your AV flags it again after manual download.

**Comment by ferventcoder** [comment]
My guess is that it's an issue with the package - https://gist.github.com/laur89/c4cfb599ee20255c41c18ff41b5af224#file-log-sh_verbose_debug-L119 is the line where the packaging attempts to delete the exe file after the installation is complete. It doesn't account for the fact that windows sometimes holds onto file locks a tiny bit longer and it should probably have a tiny bit of sleep time to let Windows let go of that file. For some reason it ignores the `-EA 0` (which means silently ignore errors). Probably due to something with the version of PowerShell and the fact that it's calling something strange here.

As far as chocolateyPending being held, look for another choco.exe process running at the same time - only one at a time should be running.
