### ISSUE TITLE
cpack nuspec results in "The path is not of a legal form"

### ISSUE THREAD

**Issue by chevdor** [chocolatey/choco#164]
Running ```cpack``` and getting the following error:
```
λ cpack -v test.nuspec
Chocolatey v0.9.9.2
The path is not of a legal form.
```

The verbose switch does not tell me more. it would be good to know WHICH path is not ok.

I figured out this happens only when I specify the nuspec file.

```cpack myfile.nuspec``` gives the error
```cpack``` works fine

I am using  v0.9.9.2

**Comment by ferventcoder** [comment]
Use .\myfile.nuspec

Out of curiosity, are you using powershell?

On Wednesday, March 11, 2015, Chevdor <notifications@github.com> wrote:

> Running cpack and getting the following error:
> ```λ cpack -v test.nuspec
> Chocolatey v0.9.9.2
> The path is not of a legal form.
>
>
> The verbose switch does not tell me more. it would be good to know WHICH path is not ok.
>
> I figured out this happens only when I specify the nuspec file.
>
> ```cpack myfile.nuspec``` gives the error
> ```cpack``` works fine
>
> I am using  v0.9.9.2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/164>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by chevdor** [comment]
thanks for the answer @ferventcoder 

nop. I ran cpack in a command prompt (not powershell).

So ```cpack myfile.nuspec``` is expected to fail but not ```cpack .\myfile.nuspec``` ?
Odd, isn´t it :confused:  ?

**Comment by ferventcoder** [comment]
Kind of weird yes. Prolly something we should fix.

On Wednesday, March 11, 2015, Chevdor <notifications@github.com> wrote:

> thanks for the answer @ferventcoder <https://github.com/ferventcoder>
>
> nop. I ran cpack in a command prompt (not powershell).
>
> So cpack myfile.nuspec is expected to fail but not cpack .\myfile.nuspec ?
> Odd, isn´t it [image: :confused:] ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/164#issuecomment-78270309>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder
