### ISSUE TITLE
Hide the 7z CMD window create by Get-ChocolateyUnzip

### ISSUE THREAD

**Issue by JurjenBiewenga** [chocolatey/choco#1642]
Currently the Get-ChocolateyUnzip helper function starts a new 7z process, this creates a new CMD window that very briefly popups that happens even when you are not using chocolatey over the command line. I'd suggest adding a 'silent' parameter to suppress this window.

**Comment by ferventcoder** [comment]
That's interesting, I didn't know there was a pop up that happened. Wonder why you see it? No worries either way, we should probably always suppress a Window.

**Comment by ferventcoder** [comment]
@JurjenBiewenga I'm going to comment on the PR, can you make the suggested change for me?

**Comment by ferventcoder** [comment]
Merged into stable at https://github.com/chocolatey/choco/commit/9d5a6d5c8eebab7cf0e4897e67c04e4010b0b379 to be released with 0.10.12. Thanks!
