### ISSUE TITLE
upgrade - switch for not installing if not installed

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1646]
If something is not installed, there should be an option to ignore installations for upgrades.
Something like `--skip-if-not-installed` or `--only-upgrade-installed` (or something like that).

#Release Notes
Provide a feature switch `skipPackageUpgradesWhenNotInstalled` that can
be overridden in the upgrade command with either
`--skip-if-not-installed` or `--install-if-not-installed` (the
later only being necessary when the feature switch has been flipped on).

**Comment by tjfryan** [comment]
How similar is this to the feature added in https://github.com/chocolatey/choco/issues/300

**Comment by ferventcoder** [comment]
The commit you linked, similar to that, but doesn't error.

**Comment by ferventcoder** [comment]
So successful exit code instead of a failing exit code.
