### ISSUE TITLE
Logging - self-service errors attempting to write to the config when using Chocolatey GUI

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1649]
### What You Are Seeing?
Seeing what looks like an error when it is attempting to write to the log file. This was thought to be fixed in #1445, but it still shows as errors for the actual attempts to write.

### What is Expected?
No output.

### How Did You Get This To Happen? (Steps to Reproduce)
Use Self-Service and Chocolatey GUI to run an installation.

**Comment by gep13** [comment]
@ferventcoder the 0.16.0 release of Chocolatey GUI was using 0.10.8, and #1445 was released on 0.10.9, so there is still a chance that was is fixed.

https://github.com/chocolatey/ChocolateyGUI/blob/0.16.0/Source/ChocolateyGui/packages.config

**Comment by gep13** [comment]
@ferventcoder I have just tested this with the latest version of Chocolatey GUI, and I can confirm that I am no longer seeing any warnings/errors when installing a package.

Steps taken to test...

1. Install latest pre-release version of Chocolatey GUI (`choco install chocolateygui --source https://www.myget.org/F/chocolateygui/ --pre`).  This is targeting 0.10.11 of Chocolatey.Lib
1. Install chocolatey.extension
1. Install chocolatey-agent
1. Enable self service (`choco feature enable --name="'useBackgroundService'"`)
1. Disable warnings (`choco feature disable --name="'showNonElevatedWarnings'"`) 
1. Enable chocolatey.org as available for self service
1. Log in as non admin user
1. Switch to chocolatey source
1. Right click and install on a package
1. Install succeeds correctly, and no warnings/errors are displayed, and application is installed correctly

**Comment by gep13** [comment]
@ferventcoder so I am fairly sure that this issue can be closed.

**Comment by ferventcoder** [comment]
Awesome, so this will go live in Chocolatey GUI 0.17.0.
