### ISSUE TITLE
Fix documentation on setting api key

### ISSUE THREAD

**Issue by dhilgarth** [chocolatey/choco#165]
On https://github.com/chocolatey/choco/wiki/CreatePackagesQuickStart there is a small error in the documentation on how to set the API key. It is missing the `-k` switch before the API key.

Current version:
```
choco SetApiKey [API_KEY_HERE] -source https://chocolatey.org/
```
Correct:
```
choco SetApiKey -k [API_KEY_HERE] -source https://chocolatey.org/
```

Even better (this would be consistent with the version on the profile page):
```
choco apiKey -k [API_KEY_HERE] -source https://chocolatey.
```

**Comment by gep13** [comment]
Further, the example on chocolatey.org should be --source, or -s.

@ferventcoder right?

**Comment by ferventcoder** [comment]
`-source` works as well. :)

@dhilgarth fixed.

**Comment by ferventcoder** [comment]
Thanks for catching that.

**Comment by dhilgarth** [comment]
Thanks for providing choco :-)

**Comment by gep13** [comment]
> @ferventcoder said...
-source works as well. :)

So all switches work with say `-s`, `-source` and `--source`?

**Comment by ferventcoder** [comment]
> So all switches work with say -s, -source and --source?

And `/s /source`
