### ISSUE TITLE
Why am I seeing Windows Update stuff within Choco?

### ISSUE THREAD

**Issue by Jimmy03** [chocolatey/choco#1657]
Slightly concerning, I never installed any package relating to windows update in Chocolatey

I hope chocolatey doesn't try to interact with Windows Update as some default behavior

So why am I seeing entries for the following? in `choco outdated`

KB3033929
chocolatey-windowsupdate.extension

**Comment by bcurran3** [comment]
If you look at the packages you've installed (clist -l), one or more of them declared those two packages as dependencies.

Chocolatey itself doesn't do anything with Windows Update, but a package can do anything it's scripted to do.

If you're concerned about that .extension, you can look at the package page for it and check it all out:
https://chocolatey.org/packages/chocolatey-windowsupdate.extension

You'll see it's a collection of helper functions to help get KB's installed. Thus, in short, some package that you installed (aka program package) REQUIRED KB3033929 as a prerequisite to work/function/install. The packager/maintainer of that package knew it, and listed KB3033929 as a dependency. That KB3033929 dependency then had chocolatey-windowsupdate.extension as a dependency to help get it installed.

Kinda like Dominoes...

**Comment by ferventcoder** [comment]
@Jimmy03 following on what @bcurran3 mentioned - if you already had the Windows Update installed or it wasn't necessary for your OS, that KB package basically noops. But in cases where the software you are installing needs those Windows Updates, the software isn't going to work until that is there, so it's an actual dependency that is required.

It's a package see https://chocolatey.org/packages/kb3033929
