### ISSUE TITLE
Package info

### ISSUE THREAD

**Issue by chevdor** [chocolatey/choco#166]
Unless I missed an option, there is no way to get the infos of a package from the command line.

It would be a nice feature to be able to use:
`choco info <packageName>`

to get a little summary of the package:
- author
- size
- version
- deps
- wether there is a -pre version
- release notes for all versions

Additionnally,
`choco info <packageName> -version 1.2.3`
would do the same but limit to the given version

**Comment by gep13** [comment]
No, not currently from the command line.  You can get all of this information from the oData feed, but I agree, this could be a good helper function added into chocolatey.

**Comment by ferventcoder** [comment]
Choco list pkgname -verbose

On Wednesday, March 11, 2015, Gary Ewan Park <notifications@github.com>
wrote:

> No, not currently from the command line. You can get all of this
> information from the oData feed, but I agree, this could be a good helper
> function added into chocolatey.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/166#issuecomment-78392538>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
For all versions -all

On Wednesday, March 11, 2015, Gary Ewan Park <notifications@github.com>
wrote:

> No, not currently from the command line. You can get all of this
> information from the oData feed, but I agree, this could be a good helper
> function added into chocolatey.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/166#issuecomment-78392538>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
And add -pre to also get those

On Wednesday, March 11, 2015, Rob Reynolds <ferventcoder@gmail.com> wrote:

> For all versions -all
>
> On Wednesday, March 11, 2015, Gary Ewan Park <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> No, not currently from the command line. You can get all of this
>> information from the oData feed, but I agree, this could be a good helper
>> function added into chocolatey.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/chocolatey/choco/issues/166#issuecomment-78392538>.
>>
>
>
> --
>
> Rob
> "Be passionate in all you do"
>
> http://devlicio.us/blogs/rob_reynolds
> http://ferventcoder.com
> http://twitter.com/ferventcoder
>
>

-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by gep13** [comment]
Damnit, I still have lots to learn/remember about what Chocolatey vNext can do :-)

So looking at this command output, I can get some of what @chevdor asked for, i.e. 

![image](https://cloud.githubusercontent.com/assets/1271146/6613620/8243afd6-c887-11e4-96b3-6ac82a94c0ef.png)

Do you think it is worth extending the output to include some of the other suggestions?

**Comment by ferventcoder** [comment]
I think we need to match exactly on search and then add a fuzzy search in

**Comment by ferventcoder** [comment]
Then we can put more information in the verbose

**Comment by ferventcoder** [comment]
Deps would be good

**Comment by alexchandel** [comment]
:+1: `choco info foo` should show info for a package. I'm used to `brew info gcc`, which works exactly as expected.

**Comment by TheCakeIsNaOH** [comment]
@ferventcoder 
Can this be closed? As far as I can tell, choco info has been added.

**Comment by vexx32** [comment]
This has been in the released versions of choco for some time now. Closing.
