### ISSUE TITLE
A lot of packages was not found with the source listed

### ISSUE THREAD

**Issue by xenogew** [chocolatey/choco#1674]
Today I called `choco upgrade all` command, but today is first time I encountered lot of errors like these.

Here are the full of console output from command called till the end.

    C:\WINDOWS\system32>choco upgrade all
    Chocolatey v0.10.11
    Upgrading the following packages:
    all
    By upgrading you accept licenses for the packages.
    [NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

    bazel was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""; Source(s): "https://chocolatey.org/api/v2/"
    chocolatey v0.10.11 is the latest version available based on your source(s).
    chocolatey-core.extension v1.3.3 is the latest version available based on your source(s).
    [NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

    chocolatey-windowsupdate.extension was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""; Source(s): "https://chocolatey.org/api/v2/"
    [NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

    chromedriver was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""; Source(s): "https://chocolatey.org/api/v2/"
    [NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

    dbforge-sql-studio-exp was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""; Source(s): "https://chocolatey.org/api/v2/"
    [NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

    dotnet4.5.2 was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""; Source(s): "https://chocolatey.org/api/v2/"
    foobar2000 v1.4 is the latest version available based on your source(s).
    gimp v2.10.6 is the latest version available based on your source(s).
    [NuGet] Exception has been thrown by the target of an invocation.

    git was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""; Source(s): "https://chocolatey.org/api/v2/"
    git.install v2.19.1 is the latest version available based on your source(s).
    golang v1.11.1 is the latest version available based on your source(s).
    google-backup-and-sync v3.42.9858.3671 is the latest version available based on your source(s).
    [NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

    gradle was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""; Source(s): "https://chocolatey.org/api/v2/"
    [NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

    intellijidea-community was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""; Source(s): "https://chocolatey.org/api/v2/"
    javaruntime v8.0.181 is the latest version available based on your source(s).
    jdk10 v10.0.2 is newer than the most recent.
     You must be smarter than the average bear...
    [NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

    jdk8 was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""; Source(s): "https://chocolatey.org/api/v2/"
    jre8 v8.0.181 is the latest version available based on your source(s).
    KB2919355 v1.0.20160915 is the latest version available based on your source(s).
    KB2919442 v1.0.20160915 is the latest version available based on your source(s).
    KB2999226 v1.0.20181019 is the latest version available based on your source(s).
    KB3033929 v1.0.4 is the latest version available based on your source(s).
    KB3035131 v1.0.2 is the latest version available based on your source(s).
    lockhunter v3.2 is the latest version available based on your source(s).
    maven v3.5.4 is the latest version available based on your source(s).
    [NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

    msys2 was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""; Source(s): "https://chocolatey.org/api/v2/"
    [NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

    neovim was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""; Source(s): "https://chocolatey.org/api/v2/"
    nginx v1.12.2 is the latest version available based on your source(s).
    [NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

    nodejs was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""; Source(s): "https://chocolatey.org/api/v2/"
    nodejs.install v10.13.0 is the latest version available based on your source(s).
    [NuGet] Exception has been thrown by the target of an invocation.

    notepadplusplus was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""; Source(s): "https://chocolatey.org/api/v2/"
    notepadplusplus.install v7.5.9 is the latest version available based on your source(s).

    You have Opera v56.0.3051.88 installed. Version 56.0.3051.99 is available based on your source(s).
    Progress: Downloading Opera 56.0.3051.99... 100%

    Opera v56.0.3051.99 [Approved]
    opera package files upgrade completed. Performing other installation steps.
    Downloading Opera 64 bit
      from 'https://get.geo.opera.com/pub/opera/desktop/56.0.3051.99/win/Opera_56.0.3051.99_Setup_x64.exe'
    Progress: 100% - Completed download of C:\Users\w_nattasan\AppData\Local\Temp\chocolatey\Opera\56.0.3051.99\Opera_56.0.3051.99_Setup_x64.exe (48.37 MB).
    Download of Opera_56.0.3051.99_Setup_x64.exe (48.37 MB) completed.
    Hashes match.
    Installing Opera...
    [1107/133336.311:ERROR:ipc_sender.cc(104)] Cannot write to mailslot: Reached the end of the file. (0x26)
    [1107/133336.312:ERROR:ipc_sender.cc(104)] Cannot write to mailslot: Reached the end of the file. (0x26)
    Opera has been installed.
    Only an exit code of non-zero will fail the package by default. Set
     `--failonstderr` if you want error messages to also fail a script. See
     `choco -h` for details.
      opera may be able to be automatically uninstalled.
     The upgrade of opera was successful.
      Software installed to 'C:\Users\w_nattasan\AppData\Local\Programs\Opera'
    [NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

    php was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""; Source(s): "https://chocolatey.org/api/v2/"
    [NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

    pycharm-community was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""; Source(s): "https://chocolatey.org/api/v2/"
    python2 v2.7.15 is the latest version available based on your source(s).
    python3 v3.7.1 is the latest version available based on your source(s).
    [NuGet] Exception has been thrown by the target of an invocation.

    ruby was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""; Source(s): "https://chocolatey.org/api/v2/"
    [NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

    rufus was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""; Source(s): "https://chocolatey.org/api/v2/"
    [NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

    tomcat was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""; Source(s): "https://chocolatey.org/api/v2/"
    vcredist140 v14.15.26706 is the latest version available based on your source(s).
    vcredist2015 v14.0.24215.20170201 is the latest version available based on your source(s).
    winmerge v2.14.0.20170224 is the latest version available based on your source(s).
    winscp v5.13.4 is the latest version available based on your source(s).
    winscp.install v5.13.4 is the latest version available based on your source(s).
    yarn v1.12.1 is the latest version available based on your source(s).

    Chocolatey upgraded 1/47 packages.
     See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

    Upgraded:
     - opera v56.0.3051.99

    Warnings:
     - intellijidea-community - intellijidea-community was not found with the source(s) listed.
     - neovim - neovim was not found with the source(s) listed.
     - bazel - bazel was not found with the source(s) listed.
     - pycharm-community - pycharm-community was not found with the source(s) listed.
     - gradle - gradle was not found with the source(s) listed.
     - jdk8 - jdk8 was not found with the source(s) listed.
     - rufus - rufus was not found with the source(s) listed.
     - notepadplusplus - notepadplusplus was not found with the source(s) listed.
     - tomcat - tomcat was not found with the source(s) listed.
     - ruby - ruby was not found with the source(s) listed.
     - php - php was not found with the source(s) listed.
     - nodejs - nodejs was not found with the source(s) listed.
     - dotnet4.5.2 - dotnet4.5.2 was not found with the source(s) listed.
     - chromedriver - chromedriver was not found with the source(s) listed.
     - msys2 - msys2 was not found with the source(s) listed.
     - chocolatey-windowsupdate.extension - chocolatey-windowsupdate.extension was not found with the source(s) listed.
     - git - git was not found with the source(s) listed.
     - dbforge-sql-studio-exp - dbforge-sql-studio-exp was not found with the source(s) listed.

My environment
- Windows 10 Pro version 1809 (build no. 17763.55) OS 64 bits
- Chocolatey v0.10.11

**Comment by bcurran3** [comment]
chocolatey.org has been going down due to problems and maintenance a lot more in the last six months then the last two years. When it's down, you're going to see what you just say.

The way to check if it's working: 
https://status.chocolatey.org/
and
https://groups.google.com/forum/#!forum/chocolatey

**Comment by xenogew** [comment]
So, should return message be something like, "Chocolatey service is under maintenance..." ?

**Comment by gep13** [comment]
>@bcurran3 said...
Sometimes status updates are also posted at https://twitter.com/chocolateynuget but there have been no tweets for 2+ months.

We always post updates during site problems and maintenance issues to the Chocolatey Twitter account.  I am not seeing where you say that there haven't been updates in over 2 months...

![image](https://user-images.githubusercontent.com/1271146/48184881-3d849c80-e32b-11e8-8a76-2fdfe2bf004d.png)

If you are referring to the first tweet, then notice that this is a pinned tweet.

**Comment by bcurran3** [comment]
Pinned Tweet threw me off.

I hate and don't use Twitter, just dug up the link for thoroughness.

**Comment by AffanIndo** [comment]
I'm having this problem. https://status.chocolatey.org/ shows that everything is operational. Even `choco upgrade chocolatey` doesn't work

```
PS C:\WINDOWS\system32> choco upgrade chocolatey
Chocolatey v0.10.15
Upgrading the following packages:
chocolatey
By upgrading you accept licenses for the packages.
Error retrieving packages from source 'https://chocolatey.org/api/v2/':
 Unable to connect to the remote server

chocolatey was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""; Source(s): "https://chocolatey.org/api/v2/"

Chocolatey upgraded 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Warnings:
 - chocolatey - chocolatey was not found with the source(s) listed.
```

**Comment by kabirnayeem99** [comment]
Faced the same issue today. The chocolatey is down now, just checked their status here https://status.chocolatey.org/ and there is this update-
**

> Updates - we are performing updates and changes to the Chocolatey Website on Wednesday 31 March 2021 between 06:00 and 11:00 UTC

**

**Comment by gep13** [comment]
@kabirnayeem99 the Chocolatey website isn't currently down.  The status page is providing an update to the scheduled maintenance that is slated to happen on the 31st March 2021, i.e. 5 days from now.

**Comment by kabirnayeem99** [comment]
The problem has been solved 10 minutes after posting this. Thank you for your response.
