### ISSUE TITLE
Stop recommending rawgit on wiki

### ISSUE THREAD

**Issue by activescott** [chocolatey/choco#1682]
At https://github.com/chocolatey/choco/wiki/CreatePackages#package-icon-guidelines, you recommend using rawgit: _For the icon URLs it is recommended to use https://cdn.rawgit.com/ (production links)_, but rawgit has posted on their page that they're shutting down.

> RawGit is now in a sunset phase and will soon shut down. It's been a fun five years, but all things must end.
> GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served.
> If you're currently using RawGit, please stop using it as soon as you can.
- https://rawgit.com/

**Comment by AdmiringWorm** [comment]
This issue would be better suited over here: https://github.com/chocolatey/choco-wiki
Which is the repository where the docs are available

**Comment by AdmiringWorm** [comment]
Issue opened over at the wikie page: https://github.com/chocolatey/choco-wiki/issues/106
