### ISSUE TITLE
Choco doesn't seem to work behind NordVPN

### ISSUE THREAD

**Issue by charmarkk** [chocolatey/choco#1683]
### What You Are Seeing?
Once I connect my VPN, it seems like chocolatey isn't able to connect to download anything (instchoco as an example here). Once disconnected, it's fine (Spotify, in this case). I checked the IPs against the Cloudfare blacklists, and that seems to not be an issue.

Even weirder is that on my other HDD/windows install (the exact same setup - I just migrated SSDs), it's consistently fine. 

Not something that can be worked around, but a pain to have to disconnect and reconnect the VPN. Perhaps worth noting somewhere? I didn't see anything else like this in my Google Fu.
### How Did You Get This To Happen? (Steps to Reproduce)
1. COnnect to NordVPN US servers.
2. Try to install something.
3. ??? (Like I said, it's completely fine on my other install)

### Output Log

See attached,
[outpit.txt](https://github.com/chocolatey/choco/files/2611780/outpit.txt). I didn't want a HUGE block of text for ya'll without an editor. :)

**Comment by charmarkk** [comment]
Appears to have been a bug to do with something buried in Windows' network management. Something went wonky, it refreshed all network items, and things seem fine now.

**Comment by charmarkk** [comment]
Seems to have come back; the flukey fix must've been a fluke. Looking through all the help docs etc. though, I'm wondering if it's something else to do with how Choco is configed...

**Comment by bcurran3** [comment]
Hi Mark,

This really doesn't look like a Chocolatey issue but a network issue (caused by the VPN software).

I looked at the log file you sent. It shows Spotify installed OK, so I'm going to run with the assumption that was with the VPN off as you mentioned.

Looking at the part about InstChoco... here's the issue:

> 2018-11-23 15:49:12,436 1700 [ERROR] - instchoco not installed. An error occurred during installation:
>  Unable to connect to the remote server

For some reason you couldn't connect to chocolatey.org for the package file to download.

With the VPN running, try pinging chocolatey.org and see if you get a response from 104.20.73.28. (Of course you could browse the site too and it would verify you can get to the server.)

You could also try downloading some files from other sites to see if you have any problems and do a speed test to see if anything weird happens then or if things work as expected.

There's the odd chance the VPN addresses are blocked, but again if you can browse the server that wouldn't be the case.

There could be coincidental connectivity issue with the server (there are problems at times) and everything might be fine in an hour or two. You can check https://status.chocolatey.org/ for problems, but it's not always accurate as it's currently manually updated.

Keep us informed of what you find out.

**Comment by charmarkk** [comment]
Thanks @bcurran3! You're right, Spotify was with it off.

Funny thing is that I can browse to .org without a problem, as if the connection was (and likely is) unhindered. 
```
Pinging chocolatey.org [104.20.73.28] with 32 bytes of data:
Reply from 104.20.73.28: bytes=32 time=24ms TTL=56
Reply from 104.20.73.28: bytes=32 time=24ms TTL=56
Reply from 104.20.73.28: bytes=32 time=24ms TTL=56
Reply from 104.20.73.28: bytes=32 time=24ms TTL=56
```
Nothing unusual there. Tried a couple other servers provided from Nord also; same results in both cases. 

I will check it later on/tomorrow and see if things are better! Maybe it's a perfect storm of flukes.

**Comment by bcurran3** [comment]
Mark - sorry for any confusion as I edited that message about 10 times.

> a perfect storm of flukes.

Fingers crossed!

**Comment by bcurran3** [comment]
> Even weirder is that on my other HDD/windows install (the exact same setup - I just migrated SSDs), it's consistently fine.

I'm trying to picture this. So it's the same computer but if you boot from the old SSD there's no problem yet if you boot from the new SSD with migrated Windows (assumed cloned) it has problems? From that I get that there's something different that is not expected to be different; i.e. the clone didn't process successfully or some change has been made to your setup on the new SSD post cloning.

Have you tried uninstall the VPN software, rebooting, and reinstalling it? Under the conditions you've stated (and if I read and comprehended them correctly), that's the next thing that **I** would do.

**Comment by charmarkk** [comment]
No worries, I was keeping up! 

Let us try! Will post updates after refreshing Nord. And yes - it's migrated. Not cloned, but reinstalled fresh and all applications also reinstalled fresh. Was downsizing so that was easier. Plus that avoids cloning/copying issues.

**Comment by pauby** [comment]
@charmarkk I think you need to rule out the issues you have on your system before we can conclude that Chocolatey is at fault. If it works on the old SSD and not the new one it's not Chocolatey at fault, it's your system.

**Comment by charmarkk** [comment]
Hey folks! @bcurran3, I -think- reinstalling the VPN May have sorted things. Or it was a fluke with the website. It seemed to behave alright yesterday when I tried again. 

I’m going to check again tomorrow and see how things do. I’m fairly certain it was something to do with that, and apologize for the trouble. Just hadn’t quite guessed it’d have been, based on the weirdness of it all. 

Updates soon!

**Comment by bcurran3** [comment]
![](https://thebsreport.files.wordpress.com/2013/05/hooray.png?w=400)

**Comment by charmarkk** [comment]
An update (since I wasn't quite ready to close til now): final checks seem to indicate that reinstalling the VPN software solved things. What a weird, oddly specific problem! Thanks for spending some time brainstorming @bcurran3!

**Comment by bcurran3** [comment]
YW. NP. Now you can enjoy the Chocolatey goodness from behind your VPN (again). :)

**Comment by petervandivier** [comment]
Oh dear... just landed on this thread... looks like I've got some rolling reinstalls ahead of me this morning... 🤕

**Comment by petervandivier** [comment]
hmm... "fixed itself" without reinstalling anything. just by disconnecting/re-connecting to a different server. will try to snag some better networking metrics if it re-occurs 😕

**Comment by petervandivier** [comment]
Issue recurred just now when I was ostensibly connected to a server in the UK but Google saw me in Indonesia. Disconnect/reconnect (to a UK server) saw me detected in the Netherlands. I have to suspect NordVPN is experiencing load in the UK and perhaps fibbing a bit about the server I'm routing through.

In a new incognito session: 
https://www.google.com/search?q=where+am+i

**Comment by AdmiringWorm** [comment]
@petervandivier are you able to browse the chocolatey.org/packages when this issue occurs?

I know that when I had these same issues, it turned out that cloudflare(which the website, and probably the API as well uses) had blacklisted the NordVPN server I was using.

**Comment by petervandivier** [comment]
@AdmiringWorm the issue hasn't recurred yet, but I'll try it out if/when it happens again. All I thought to do last time was just grabbing `ipconfig /all` info and running `tracert` to google & choco - not sure what (if any) value that might have though 😕

**Comment by TeaDrivenDev** [comment]
I have this all the time with NordVPN, on several different machines and through different ISPs. `choco list` or `outdated` work without any issue, but `install` or `upgrade` fail with

> procexp not installed. An error occurred during installation:
>  Unable to connect to the remote server
> procexp package files install completed. Performing other installation steps.
> The install of procexp was NOT successful.
> procexp not installed. An error occurred during installation:
>  Unable to connect to the remote server

Because I know that it usually doesn't work, I don't try all the time, but _very_ occasionally it does actually work, likely depending on the specific server I'm connected to. Unfortunately those servers and their names don't appear to stay the same, so I can't just stick with one that I know works.

**Comment by Reyhn3** [comment]
For future reference, I just found this issue because I had the same symptoms:

> Unable to connect to the remote server

Also behind NordVPN.
Simply disconnecting NordVPN and running choco upgrade/install solved the problem.

**Comment by tinjaw** [comment]
+1 for NordVPN
