### ISSUE TITLE
Request to have install path retrievable

### ISSUE THREAD

**Issue by unacceptable** [chocolatey/choco#1685]
Foreword
=======
Firstly, I understand that this feature request would likely take years to implement because install package developers would have to get on board with this idea and update their choco packages.

Proposal
=======
Have an attribute (preferable), or a simple text value for installation path in `choco list -lv`.

Use Case
=======
I am currently installing Ruby on a CI build agent so that one of My Team's Developers could use it for unit tests.  After installing ruby I can easily extrapolate (as a human) based on output of `choco list -lv` that the installation directory is ` c:\tools\Ruby25`, because it is stated that I can pass an `/InstallDir` package parameter and the default path is "`c:\tools\RubyXY` where XY are major and minor version parts".  That's great, but what about when I am trying to get this information programmatically.

Suppose for a second that I have the following PowerShell function:

```
function Verify-SoftwareInstallation {
    param(
        [Parameter(Mandatory=$true)][string]$PackageName
    )
    $command_check = @(Get-Command $PackageName -ErrorAction SilentlyContinue)

    if ($command_check.count -ge 1) {
        return $command_check[0].Source
    } else {
        choco install -y $PackageName
        # Need additional code to return choco installation path here
    }
}
```

and I have to pass the package path to another function so that the executable path can be used: 

```
    $RubyPath   = Verify-SoftwareInstallation "ruby"
    Push-UnitTestResult "$RubyPath"
```

There doesn't appear to be a way to go about doing this currently via chocolatey.  Granted to overcome my current issue in PowerShell I could just do a `Get-ChildItem` with a `-Recurse` flag and `-Filter` for the exe name in popular installation paths, but that is a serious misuse of compute power in my opinion.

Thank you for taking the time to read this.

**Comment by pauby** [comment]
@ScriptMyJob You could do this with one line of PowerShell at the moment:

```
(Get-Command -Name 'hugo.exe' -ErrorAction SilentlyContinue).Source
```

The `Source` property will be empty if the command is not found so you just need to check for that. However this will only work for commands (or whatever you are using to check) is on the path.

Remember that Chocolatey manages packages and packages manage installers. Chocolatey doesn't manage the installer (and therefore where it will install to).
