### ISSUE TITLE
Don't create the folder if variable detected

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey/choco#1687]
### What You Are Seeing?
New folder `%MyVar%` appears in current directory when installing package with `Install-ChocolateyShortcut`.

### What is Expected?
This folder does not appear, because in runtime the folder will be expanded with value of environment variable `MyVar` instead of verbatim `%MyVar%`.

### How Did You Get This To Happen? (Steps to Reproduce)
 1. Create a package with `choco new`.
 2. In `chocolateyInstall.ps1`, add following statement:

    ```powershell
    $args = @{
        shortcutFilePath = $shortcut
        targetPath = $exe
        WorkingDirectory = '%MyVar%'
    }
    Install-ChocolateyShortcut -ShortcutFilePath @args
    ```

 3. Pack the package with `choco pack`.
 4. Install the package.

### Possible Cause
`Install-ChocolateyShortcut` automatically created the folder for working directory is the folder is missing. This is an (undocumented) feature.

When there is variable in it (such as `%AppData%`), Windows will not set the working directory to a folder named `%AppData%` in current directory. Instead, it will try to expand the variable, and set the result as working directory, *at runtime*. User can change the working directory by changing the environment variable, *without changing the shortcut file itself*. This is useful in multi-user environment, where each user has different `%AppData%`. Current helper creates the shortcut just well, so a small modification will be sufficient to support this pattern.

### Output Log
(Omitted.)

**Comment by pauby** [comment]
I'm not really sure I understand this one so forgive me if I've missed something.

> This folder does not appear, because in runtime the folder will be expanded with value of environment variable MyVar instead of verbatim %MyVar%.

This won't happen. `%MyVar%` is not a PowerShell variable. `$env:MyVar` is. So if you pass `%MyVar%` to the code it will interpret it literally as it's supposed to do.

Why can't you use `$env:MyVar`?

**Comment by FranklinYu** [comment]
@pauby I exactly *don't* want it to understand. I want `%MyVar%` to be in the shortcut verbatim.

**Comment by ferventcoder** [comment]
@pauby This is what gets saved verbatim in the shortcut link, then Windows expands it when you access the .lnk file. It can't be a PowerShell variable because it uses COM.

**Comment by FranklinYu** [comment]
@ferventcoder “Up For Grabs”? I thought we already have #1686?

**Comment by ferventcoder** [comment]
This will be released with 0.10.12.

**Comment by ferventcoder** [comment]
> “Up For Grabs”? I thought we already have #1686?

@FranklinYu yes we do, the up for grabs allows you to have a PR on this. 👍

**Comment by ferventcoder** [comment]
corrected the previous statement - the wording didn't come across as I would have liked.
