### ISSUE TITLE
choco tried to resolve disable repo

### ISSUE THREAD

**Issue by chevdor** [chocolatey/choco#169]
choco 0.9.9.2

I am using the local repo in addition to the official chocolatey repo:
```choco sources add -name local -source http://idontexist:4444/nuget```

Obviously, this repo will not resolve...

When my local repo is unavailable, clist fails:
```
λ clist notepadplusplus
Chocolatey v0.9.9.2
The remote name could not be resolved: 'idontexist'
```
and I don´t even get the results from the other repos.

Since my local repo is the issue, I try disabling it:
```choco sources disable -name local``` 

even disabled, the repos is tested:
```
clist notepadplusplus
Chocolatey v0.9.9.2
The remote name could not be resolved: 'idontexist'
```

First of all, I think clist should still return the results from the other repos even if one cannot resolve.
Also, if a repo is disabled, the issue must definitely not occure.

**Comment by ferventcoder** [comment]
Sounds like a bug. Also ugh.

**Comment by ferventcoder** [comment]
Thanks for reporting. This will be out in 0.9.9.5
