### ISSUE TITLE
PackageParameters set incorrectly if value contains space and ends with backslash

### ISSUE THREAD

**Issue by eirikatdips** [chocolatey/choco#1690]
### What You Are Seeing?
`choco install mypackage -params "/InstallLocation:C:\Program Files(x86)\Company\"`
`$Env:ChocolateypackageParameters` : `/InstallLocation:C:\Program Files(x86)\Company"`

I.e. The environment variable value ends with an quotation mark instead of a backslash

### What is Expected?
`$Env:ChocolateypackageParameters` : `/InstallLocation:C:\Program Files(x86)\Company\`

**Comment by andmos** [comment]
@ferventcoder seems like the code that parses the arguments escapes the last quotation mark when path ends with `\`. This kind of regex parsing seems prone to errors, so not surprised 😄

**Comment by eirikatdips** [comment]
yes, it works as expected if i pass the parameters as `"'value'"`

This is the logfile when passing params just as "value"

[choco.summary.log](https://github.com/chocolatey/choco/files/2772016/choco.summary.log)

**Comment by vii33** [comment]
There is also a different behaviour in the Chocolatey parser when you inject `--params` via a PowerShell variable. 

#### This does not work: 
```
$ParVar = '--params "/NoDesktopIcon /NoQuicklaunchIcon"'
choco install vscode $ParVar
```
![](https://i.stack.imgur.com/Did62.png)
(The double quotes will be deleted by the parser)

#### This does:
```
$ParVar = '--params="/NoDesktopIcon /NoQuicklaunchIcon"'    (equal sign after params)
choco install vscode $ParVar
```
![grafik](https://i.stack.imgur.com/U95EB.png)

*Most* package documentation state it *without* equal sign (example: [VS Code](https://chocolatey.org/packages/vscode)), though. One positive example is [miniconda](https://chocolatey.org/packages/miniconda3).

**Comment by gep13** [comment]
>@vii33 said...
Most package documentation state it without equal sign (example: VS Code), though. One positive example is miniconda.

Package documentation is outside the scope of this issue, and would need to be followed up with the package maintainers directly.

Our own documentation makes it clear about best practices for quoting of parameters, as can be see here:

https://docs.chocolatey.org/en-us/choco/commands/#how-to-pass-options-switches

I am going to go ahead and close this issue.
