### ISSUE TITLE
Replace RawGit in package template with other CDN

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey/choco#1693]
https://github.com/chocolatey/choco/blob/ea4b155ad4f6911c003fcf30792f85abca480f05/src/chocolatey/infrastructure.app/templates/NuspecTemplate.cs#L62

We should replace the RawGit with other CDN.

Related to chocolatey/choco-wiki#106.

**Comment by TheCakeIsNaOH** [comment]
This was fixed as part of this PR: https://github.com/chocolatey/choco/pull/1884
