### ISSUE TITLE
Add command to list outdated packages.

### ISSUE THREAD

**Issue by alexchandel** [chocolatey/choco#170]
The ubiquitous OS X package manager [Homebrew](https://github.com/Homebrew/homebrew) has `brew outdated`, which works exactly as expected.

**Comment by ferventcoder** [comment]
`choco upgrade all --noop`

**Comment by RichiCoder1** [comment]
I'd say just because you can do it through a `--noop`, doesn't mean that it's necessary the best way. I'd like this too, both for the ability to do `choco outdated`, but also so I can also have an `IListCommand` in the API for quickly retrieving dated packages.

**Comment by alexchandel** [comment]
`choco upgrade all --noop` isn't intuitive. An alias like `choco outdated` would be a good thing.

On a related note, striving for command similarity between choco and something as ancient and cantankerous as apt-get, aptitude, or yum is a recipe for bad design. There are plenty of modern package managers like [Homebrew](https://github.com/Homebrew/homebrew) and [Nix](https://nixos.org/nix/) that have learned from history and have much better UIs as a result.

**Comment by ferventcoder** [comment]
Homebrew isn't exactly intuitive when you want to install a specific version. So there's that.

**Comment by ferventcoder** [comment]
I don't mind adding an alias called outdated. :)

**Comment by ferventcoder** [comment]
Opening up for the community.

**Comment by alexchandel** [comment]
:P yeah, old versions of formulae, `homebrew/versions`, and even installing `stable` and `devel` side-by-side could be much easier.

**Comment by aronovgj** [comment]
would be nicer to only list the outdated instead of giving you the status of all your packages. i don't want to know whats up to date, i want to know whats not. or is this a different issue?

**Comment by ferventcoder** [comment]
That's fair, and what i started with on the limited output, but it turned out that automation tools needed to know the current state as well so they needed the information.

**Comment by aronovgj** [comment]
from a users point of view i don't care if this checks all the packages for their state. why not just hide the unnecessary output?

**Comment by gep13** [comment]
If it helps any, this was a recent addition to ChocolateyGUI:

![image](https://cloud.githubusercontent.com/assets/1271146/6698038/fb2eddc6-ccec-11e4-9546-6c31392f3e17.png)

It will show you all the packages that you have installed locally, that have updates available on your configured sources.

Hope this helps!

**Comment by alexchandel** [comment]
I'm interested in the command line utility, not a GUI. I suppose it makes sense that `choco outdated` is an alias for some fundamental command with options, but having things like `choco outdated` and `choco list` still make the command line interface much better to use for humans.

**Comment by gep13** [comment]
> @alexchandel said...
I'm interested in the command line utility, not a GUI.

Yes, I understand that, I was simply putting this option out there as an alternative, in the interim.

**Comment by ferventcoder** [comment]
This was added in https://github.com/chocolatey/choco/commit/6b0461132bf13ba5d4bab8561c815c70364938c1 and will be released in 0.9.9.6. Thanks!
