### ISSUE TITLE
Choco update doesn't remember installation parameters

### ISSUE THREAD

**Issue by musm** [chocolatey/choco#1707]
This is a very annoying issue.

For example suppose I install a package and upon installation request that NO desktop icons or context menu items are created.

Upon performing an upgrade of the package. These installation parameters are forgotten and the upgrade proceeds by using the default parameters.

This is wrong and defeats the purpose of using installation parameters if a subsequent upgrade will wipe out the information.

**Comment by AdmiringWorm** [comment]
There is a feature already for this (although it's still in the preview phase).
> useRememberedArgumentsForUpgrades - Use Remembered Arguments For Upgrades - When running upgrades, use arguments for upgrade that were used for installation ('remembered'). This is helpful when running upgrade for all packages. Available in 0.10.4+. This is considered in preview for 0.10.4 and will be flipped to on by default in a future release.

You'll need to explicitly enable it yourself with the command `choco feature enable --name=useRememberedArgumentsForUpgrades`

**Comment by pauby** [comment]
Related to #1443

**Comment by musm** [comment]
@AdmiringWorm do I then need to re-add all my packages for choco to store the install parameters or will subsequent upgrade remember the initial install parameters?

**Comment by AdmiringWorm** [comment]
I'm not completely sure TBH.
I do believe it will use the stored arguments from even before the feature was enabled.

But @pauby or @gep13 will probably correct me in if this isn't the case.

**Comment by ferventcoder** [comment]
If you did an upgrade, yes, you will need to.

**Comment by ferventcoder** [comment]
@musm have a look at #797 for the important notes about the feature. I would also wait until 0.10.12 to turn it on. We found #1443 and it's important that you may not want to hit that.
