### ISSUE TITLE
tmpf27a.tmp was not found with the source(s) listed.

### ISSUE THREAD

**Issue by abdulkareemnalband** [chocolatey/choco#1710]
I'm getting following output every time I `choco update all -y`

```
tmpf27a.tmp was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""; Source(s): "https://chocolatey.org/api/v2/"
```

[chocolatey.log](https://github.com/chocolatey/choco/files/2749495/chocolatey.log)

**Comment by gep13** [comment]
@abdulkareemnalband from looking at the log, it looks as those you have a package called `tmpF27A.tmp` with version 1.0.0 installed on your machine.  You can confirm this by looking at the `C:/ProgramData/chocolatey/lib` folder.  These is no package with this name on chocolatey.org, and that is why you are seeing the error that you are.  Do you have any idea on how this package came to be installed?

**Comment by abdulkareemnalband** [comment]
@gep13 
I executed following command before checking your comment
```sh
choco uninstall tmpF27A.tmp 
```
now i cannot reproduce

**Comment by AdmiringWorm** [comment]
@abdulkareemnalband I'm guessing that at some point you had boxstarter installed and ran a script through it? (or maybe you installed a version of nodejs that used boxstarter).
Boxstarter usually creates a tmp package when it runs a package from script.
