### ISSUE TITLE
search/list - when one of the sources is empty, no results are returned

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1712]
When you have an empty source, and you run choco search/list, no results are returned. It seems to fail on that source.

**Comment by ferventcoder** [comment]
Not sure on this, I'm not seeing this. I've reproed by creating an empty folder and pointing to that as a source. It still returned results. I am going to follow up with a package source that is empty.

**Comment by ferventcoder** [comment]
I'm not able to reproduce, I'm going to chalk this up to something else that we don't know about that is causing this issue.

**Comment by TheCakeIsNaOH** [comment]
Since no one has reproduced this, I'll assume this can be closed. 

Also, once NuGet is upgraded, #508, this issue should have no chance of appearing, as `AggragateRepository` is no longer a thing, so sources are iterated through manually.
