### ISSUE TITLE
Chocolatey does not override NuGet proxy with its own

### ISSUE THREAD

**Issue by IanKemp** [chocolatey/choco#1720]
### What You Are Seeing?

* System proxy: configured but disabled

![image](https://user-images.githubusercontent.com/1726434/52111101-5d1a2100-260b-11e9-80d6-52dac5b37b75.png)

* NuGet proxy: configured in `%appdata%\NuGet\NuGet.config`

![image](https://user-images.githubusercontent.com/1726434/52112568-8c329180-260f-11e9-8f23-d6759cdf8ff3.png)

Scenario:

My employer recently decommissioned their proxy server (it no longer accepts HTTP requests, but its DNS record still exists). Due to various issues with tools and proxies in the past, I have hardcoded the proxy for various tools, one of these being NuGet.

The end result is that when I run any Cholatey command that invokes NuGet to fetch package sources, it fails with `<package-name> was not found with the source(s) listed`:

```sh
> choco upgrade chocolatey
Chocolatey v0.10.11
Upgrading the following packages:
chocolatey
By upgrading you accept licenses for the packages.
[NuGet] An error occurred while loading packages from 'https://chocolatey.org/api/v2/': Unable to connect to the remote server

chocolatey was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""; Source(s): "https://chocolatey.org/api/v2/"

Chocolatey upgraded 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Warnings:
 - chocolatey - chocolatey was not found with the source(s) listed.
```

If I run choco with the `-dv` option, the only line about proxy is `Proxy.BypassOnLocal='True'`. Due to this, I assumed that choco (and hence NuGet) was using no proxy, and hence looked elsewhere. Additionally, if I run `choco upgrade chocolatey --proxy=""` (i.e. force no proxy), the same issue occurs.

Removing the proxy in NuGet.config makes everything work, but it took me a while to figure this out, and as a result I suggest the following:

1. Always force NuGet to use the proxy that Chocolatey is using. This is problematic because apparently NuGet is stupid and doesn't allow the proxy to be specified per invocation (i.e. via the command-line), only via system-wide `HTTP_PROXY` etc. environment variables. Possible solution is to save the current `HTTP_PROXY` before invoking NuGet, set it to the choco value, then restore it after the NuGet invocation completes.
2. Output more information about the proxy NuGet (and not choco) is using in the diagnostic log. (This would be unnecessary if they were always using the same proxy as suggested in the previous point.)

**Comment by ferventcoder** [comment]
@IanKemp Interesting that Chocolatey would be using anything from NuGet configuration - it should not be. They should be using different settings (unless you've configured them the same).

**Comment by IanKemp** [comment]
@ferventcoder Chocolatey is calling NuGet and NuGet is using its own config - so yes, they are using different settings. I'm proposing this be changed so that **when NuGet is invoked by Chocolatey, it uses Chocolatey's settings**.

**Comment by ferventcoder** [comment]
@IanKemp Chocolatey doesn't invoke NuGet.exe - it contains NuGet.Core.dll. Invoked is not the right word choice here.  Chocolatey will use whatever HTTP_PROXY and HTTPS_PROXY is set to, like most apps will. Maybe this is where you might be seeing the overlap?

**Comment by ferventcoder** [comment]
Following up from https://github.com/NuGet/Home/issues/7757, Chocolatey doesn't use NuGet.config (or rather, it should not use it). If it is using it for anything, that is a bug and should be fixed on the Chocolatey side.

**Comment by ferventcoder** [comment]
@IanKemp can you submit a detailed log (the full output log requested) so we can take a closer look? We request that as we see things in there that you may not see and it typically clues us into your environmental settings and what the issue might be. Thanks in advance!

**Comment by corbob** [comment]
I have confirmed that this is an issue with 1.3.1:

![2023-04-05_17-55-36](https://user-images.githubusercontent.com/30301021/230246074-f04779fa-00a3-458f-85ef-f348e75a1bba.png)

Using the build from PR #3099, this is not an issue:

![image](https://user-images.githubusercontent.com/30301021/230246107-d5ed2885-c90a-4b91-9cba-5d4cff267823.png)

Confirmed also with the most recent beta.
