### ISSUE TITLE
chocolate issue

### ISSUE THREAD

**Issue by Mbegu180** [chocolatey/choco#1723]
STOP RIGHT HERE - DO NOT CREATE A TICKET FOR A QUESTION ON THIS REPOSITORY

1. Start with https://chocolatey.org/docs/troubleshooting (Troubleshooting) and https://chocolatey.org/docs/chocolatey-faqs (FAQs) to see if your question or issue already has an answer. You can also explore https://chocolatey.org/docs (which are pretty comprehensive, but not always the most searchable).
2. If not found or resolved, please see https://chocolatey.org/support to see what avenues are available to you based on whether you are an open source user or a licensed customer (have a commercial edition).

The best routes for getting questions answered when the documentation doesn't serve what you need is the mailing list or in chat:
- email - http://groups.google.com/group/chocolatey
- chat - https://gitter.im/chocolatey/choco

NOTE: Keep in mind we have an etiquette regarding communication that we expect folks to observe when they are looking for support in the Chocolatey community. https://github.com/chocolatey/choco/blob/master/README.md#etiquette-regarding-communication

**Comment by pauby** [comment]
@Mbegu180 You haven't added any detail to this issue. Did you open it by mistake?

**Comment by ferventcoder** [comment]
No response - closing as invalid.
