### ISSUE TITLE
search/list/info - exit 1 when no results are returned

### ISSUE THREAD

**Issue by rjjacobs200** [chocolatey/choco#1724]
Queries of packages using "list" or "info" which return no results could return an error code of 1 (or something other than 0). Managers like scoop do this, and it makes scripting or integration into other systems much easier.

**Comment by ferventcoder** [comment]
@rjjacobs200 I agree that there should be a different exit code if nothing is found. 

This was added at https://github.com/chocolatey/choco/commit/47cbdd8fddc9653be52a8bd37540f0810c68634a and will be released in 0.10.12.

**Comment by ferventcoder** [comment]
Moved this to a 2 so that it is deterministic that is what caused the exit. Added documentation about exit codes that will be in `choco search -?`
