### ISSUE TITLE
PHP Windows

### ISSUE THREAD

**Issue by karencho777** [chocolatey/choco#1729]
Hello, I have installed PHP package but I don't know how to use it? I want to run PHP file is there possible?

**Comment by karencho777** [comment]
no one can help?

**Comment by mkevenaar** [comment]
Hi @karencho777 
if you have an issue with a package, I would suggest to use the "contact maintainers" link on the package page.

**Comment by karencho777** [comment]
i don't have any issue with the package ... i have installed it successfully ... now with what command i need to execute php file or script?

**Comment by mkevenaar** [comment]
Hi @karencho777,
You are creating a ticket with an question about PHP on the github repo for the choco command. I think you should ask the maintainer of the PHP by using the "contact maintainers" on the package page.

**Comment by karencho777** [comment]
can you please explain to me how i have to contact maintainers?

**Comment by karencho777** [comment]
ohh i found it thank you

**Comment by gep13** [comment]
@karencho777 glad to hear that you got this sorted.  I am closing this issue for now.
