### ISSUE TITLE
chocolately.org installs the wrong version!

### ISSUE THREAD

**Issue by alexchandel** [chocolatey/choco#174]
The suggested installation routine, 

```
 @powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin
```

installs the old, incompatible version 0.9.8.33. And upgrading from a vanilla 0.9.8.33 to 0.9.9 idiosyncratically fails. I literally can't tell people to install choco.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/chocolatey.org/issues/162 and https://github.com/chocolatey/chocolatey.org/issues/163

**Comment by ferventcoder** [comment]
>  And upgrading from a vanilla 0.9.8.33 to 0.9.9 idiosyncratically fails.

Can you expand on this?

**Comment by alexchandel** [comment]
Whoops, I seem to be a dupe.

@ferventcoder in 2 out of 3 upgrades, I've had strange errors where old packages weren't found. Fixed by fresh installs of 0.9.9.

**Comment by ferventcoder** [comment]
Weird. I had no issues with most of my testing, of course all from similar machines though.

**Comment by alexchandel** [comment]
Yeah these were very dissimilar machines. One Windows 10 TP2 with lots of dev tools installed, one Windows 7 with Honeywell customizations, and one Windows Vista with years of dev tools installed.

**Comment by ferventcoder** [comment]
Can we work on the install issues you've run into? I'd like to get them solved.

**Comment by alexchandel** [comment]
Sure. I'm not sure how to replicate them though. They were all from upgrading 0.9.8 to 0.9.9, which is why it terrifies me that the Chocolatey homepage's install instructions still install an old version (0.9.8.33).

**Comment by ferventcoder** [comment]
Do you remember what the errors might have been related to?

**Comment by alexchandel** [comment]
One of them had to do with the fact that the package directories' names changed (no more version number). Another made it impossible to uninstall Winstaller packages; it would report a successful uninstall, yet the files were all still there, and Programs&Features reported it as still installed.

**Comment by ferventcoder** [comment]
The first one strikes me as interesting - that's precisely how I'm running
on my primary Windows machine.

On Thursday, March 19, 2015, Alex <notifications@github.com> wrote:

> One of them had to do with the fact that the package directories' names
> changed (no more version number). Another made it impossible to uninstall
> Winstaller packages; it would report a successful uninstall, yet the files
> were all still there, and Programs&Features reported it as still installed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/174#issuecomment-83772817>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
I'm not sure this is an issue any longer. I'm closing for now. If you run into this in the future or anyone else has comments related to this, please comment.
