### ISSUE TITLE
Validate config / system state across everything

### ISSUE THREAD

**Issue by gep13** [chocolatey/choco#1746]
In addition to the ability for individual commands to validate that everything is correct before proceeding, for example here:

https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/commands/ChocolateyInstallCommand.cs#L169-L201

with the install command, it should also be possible to validate at a higher level, and not tidied specifically to an individual command.

This would allow the opportunity to valid on things like:

- system state, prior to execution
- global Chocolatey configuration
- anything else that is deemed necessary

This should be implemented in an extensible way, so that new validations can be easily added.

**Comment by ferventcoder** [comment]
This is completed and will be in 0.10.12.
