### ISSUE TITLE
Passing `--execution-timeout=0` doesn't override the default execution timeout in the configuration

### ISSUE THREAD

**Issue by icnocop** [chocolatey/choco#1747]
Hi.

Passing `--execution-timeout=0` doesn't override the default execution timeout in the configuration.

Chocolatey v0.10.11

### What You Are Seeing?
`Chocolatey timed out waiting for the command to finish. The timeout specified (or the default value) was '2700' seconds.`

### What is Expected?
No timeout

### How Did You Get This To Happen? (Steps to Reproduce)

Run `choco.exe install --execution-timeout=0 -y VisualStudio2015Enterprise` on a machine that takes longer than 45 minutes to install.
For example, it usually takes longer than 45 minutes in a Microsoft-hosted Azure build pipeline agent using the `VS2017-Win2016` image.

Scripts: https://github.com/icnocop/ChocolateyTimeout
Results: https://dev.azure.com/rami/ChocolateyTimeout/_build/results?buildId=171

### Output Log

Published as build artifact: https://dev.azure.com/rami/ChocolateyTimeout/_build/results?buildId=171

### Work-around

Run `choco config set commandExecutionTimeoutSeconds 0` before `choco install`

### Related Issue

https://github.com/chocolatey/choco/issues/1059

Thank you.

**Comment by ferventcoder** [comment]
Related to #1224 and #1059

**Comment by ferventcoder** [comment]
@icnocop I've verified this issue. I believe this is similar to what a customer was running into as well. It appears that passing the setting isn't taking an effect, where having the config setting set works fine (#1059) and it does apply the infinite wait if the setting is zero (#1224).

**Comment by ferventcoder** [comment]
This has been fixed and will be released in 0.10.12. Thanks for the notes!

**Comment by icnocop** [comment]
Awesome!

Thank you for the quick response and quick fix! 😄
