### ISSUE TITLE
Add additional examples to PowerShell helpers documentation 

### ISSUE THREAD

**Issue by thigg** [chocolatey/choco#175]
The examples are often not very useful.

For example here: https://github.com/chocolatey/choco/wiki/HelpersInstallChocolateyShortcut

I would expect at least one example which links from an installed package to the desktop, but the examples are all with absolute pathes and are not covering the most common cases.

**Comment by gep13** [comment]
@thigg if you have an example that you think would be useful, let us know, and we can get them added.

**Comment by thigg** [comment]
Just have an example for the old one:

    $target = Join-Path $toolsDir "eclipse\eclipse.exe"
    Install-ChocolateyDesktopLink $target

But you got the general idea what I mean?
That the examples should cover the most general usecase.

I will look through my scripts and check if  there are some good examples for several functions.

**Comment by gep13** [comment]
Yes, I agree that we need to expand on the use cases, and this is definitely something we can add.  If you come up with other use cases for as helper functions, feel free to shout, and we can get them added as well.

**Comment by pauby** [comment]
Just looking at this [comment](https://github.com/chocolatey/choco/issues/175#issuecomment-83399984), the example is not valid:

* [`Install-ChocolateyShortcut` requires both a `ShortcutFilePath` and a `TargetPath` parameter](https://docs.chocolatey.org/en-us/create/functions/install-chocolateyshortcut/).
* In this example, the executable is already in the tools folder and therefore would be shimmed. So there would be no need for a shortcut.

As this is over 9 years old, and there has been no update, I'm going to go ahead and close it.
