### ISSUE TITLE
List all versions of a package including unlisted

### ISSUE THREAD

**Issue by doggy8088** [chocolatey/choco#1754]
I'm trying to automatic my package publishing process.  I have to check the latest chocolatey package version by PowerShell. I try to use `choco list gitea --all -r` to get all the version. But the problem is that this command doesn't including **unlisted** versions.  If I already published to the chocolatey gallery and not approved yet for few days, I shouldn't publish it again.  I can't get the latest version including unlisted now. So I can't do the version comparsion in my PowerShell script.

I'd like to suggest Chocolatey to offer a argument to get versions including unlisted versions. Such as:

```sh
choco list gitea --all -r --including-unlisted
```

**Comment by bcurran3** [comment]
Will,

Trying to be helpful...

Until such time as this request gets done...

You could try checking the versions via your PS script scraping the package page. i.e.
$PackagePageInfo = Invoke-WebRequest -DisableKeepAlive -Uri "https://chocolatey.org/packages/gitea"

A new unlisted package waiting for moderation should show as submitted. A little parsing for "submitted" in the version history and you can find out what version is still pending approval and not try to re-process the same update.

**Comment by ferventcoder** [comment]
@doggy8088 unlisted is the same as soft-deleted. If it is unlisted there is likely a reason. Unfortunately this is not a direction we are considering for choco. As @bcurran3 suggested, there are perhaps other ways to get that information.

As far as pushing, am I understanding you are using something like AU to determine what version has been published? it does have some checks and balances to work with the moderation queue if I recall correctly.
