### ISSUE TITLE
choco install hang when msys & ruby present as dependencies

### ISSUE THREAD

**Issue by CAMOBAP795** [chocolatey/choco#1756]
### What You Are Seeing?

`choco install metanorma --version 1.1.4` hang. Test log available here  https://gist.github.com/choco-bot/5edc9ecc043f53735d90a6c22e40c72d or on our CI here https://ci.appveyor.com/project/ribose/chocolatey-metanorma/builds/23065526

During troubleshooting I have found that this happens because of `msys2` & `ruby` dependencies if they wasn't installed before

### What is Expected?

 - `choco install` should be finished

### How Did You Get This To Happen? (Steps to Reproduce)

 - make sure that `msys2` & `ruby` don't installed via `chocolatey`
 - run `choco new bob`
 - modify `tools/chocolateyinstall.ps1` to contain only `Write-Host Hello world`
 - modify `bob.nuspec` to contains dependencies:
    ```
    <package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
      <metadata>
        ....
        <dependencies>
          ....
          <dependency id="ruby" version="(,2.6.0)" />
          <dependency id="msys2" version="20180531.0.0" />
          ....
        </dependencies>
      </metadata>
      ....
    </package>
    ```
 - run `choco pack .`
 - run `choco install bob -dv -y -s "'.;https://chocolatey.org/api/v2/'"`
 - **PROBLEM**: it will never ends

### Output Log

 - Chocolatey test log https://gist.github.com/choco-bot/5edc9ecc043f53735d90a6c22e40c72d 
 - Our CI here https://ci.appveyor.com/project/ribose/chocolatey-metanorma/builds/23065526

**Comment by gep13** [comment]
@CAMOBAP795 I have just tested your steps, and they work as expected for me...

![image](https://user-images.githubusercontent.com/1271146/54358351-12eb7d00-4658-11e9-95f3-9ef8cfe5625e.png)

Can you confirm what operating system you are running on, and what version of Chocolatey you are using for your test?

**Comment by CAMOBAP795** [comment]
@gep13 could you please attach full `chocolatey.log` ?

**Comment by gep13** [comment]
@CAMOBAP795 sure thing.  You can find the complete log here:

https://gist.github.com/gep13/3776116c26d8aefd4763f71eb1769152

**Comment by gep13** [comment]
@CAMOBAP795 could this be related to the issue that you are seeing:

https://github.com/Microsoft/azure-pipelines-image-generation/issues/742#issuecomment-472852611

**Comment by CAMOBAP795** [comment]
@gep13 highly likely because if I will put `choco install msys2 --params "/NoUpdate"` before `choco install bob` it works without hang

Is there a way to define install params for dependency in `nuspec` ?

**Comment by pauby** [comment]
@CAMOBAP795 There is no way to define parameters in the `.nupsec` file itself and you should never run `choco` inside of `choco`. Bad things will likely happen!

**Comment by CAMOBAP795** [comment]
Thanks @pauby @gep13 

I think it this case issue can be closed
