### ISSUE TITLE
choco outdated doesn't check chocolatey

### ISSUE THREAD

**Issue by bc3tech** [chocolatey/choco#1766]
I ran `choco outdated` to see what packages I need to update.

When I was done updating those packages, on a whim I ran `cup chocolatey` and lo and behold there was an update. However, `outdated` didn't show me that chocolatey was actually outdated; I would expect it to do so.

This was on v 0.10.11 of choco, which then updated 0.10.12.

**Comment by bc3tech** [comment]
ah yeah that definitely is what i would've expected. not sure why I never saw that on my install ¯\_(ツ)_/¯

**Comment by gep13** [comment]
@bc3tech thanks for getting back about this.  I am going to go ahead and close this issue, as I think this is working as expected, and "something", likely a caching issue, was causing this for you.

**Comment by bc3tech** [comment]
sounds good and i'll let you know if it pops again in the future, then maybe we can debug further to help out in solving it
