### ISSUE TITLE
Enhance "Access to path is denied" message on no admin rights

### ISSUE THREAD

**Issue by thigg** [chocolatey/choco#177]
It is actually good, that chocolatey doesn't spam you with warnings if you don't have admin rights. Very useful if you intend to use it without.

But if there are no admin rights the message that a path wasn't accesable should be enhanced with something like:

    You started chocolatey without admin rights, please try again from an elevated shell.

I am not to happy with this text but something like that should be pretty useful. Needed yesterday 10 minutes until I saw that my shell wasn't elevated.

**Comment by ferventcoder** [comment]
Are you using choco 0.9.9? It does actually say this if you are an administrative user in a non-elevated shell. However the detection is not 100%. I'd be interested to know where you may fall with this.

**Comment by thigg** [comment]
Ehm... Wait, I see, its printed there in green. I am used to just read red error messages :D

**Comment by ferventcoder** [comment]
Any color you would prefer there? Perhaps magenta for the warnings?

**Comment by thigg** [comment]
I am used to red for errors but there are a lot of colors... ;)
I think the most useful change would be to have it as first line... but I am not sure...

**Comment by ferventcoder** [comment]
Let's go warning ?
