### ISSUE TITLE
Chocolatey remembers --forceX86 value

### ISSUE THREAD

**Issue by flcdrg** [chocolatey/choco#1772]
### What You Are Seeing?

Boxstarter calling Chocolatey where the first package specifies --x86 then causes all subsequent packages to be installed as though --x86 was specified

### What is Expected?
Only install x86 packages when explicitly requested

### How Did You Get This To Happen? (Steps to Reproduce)

This relates to https://github.com/chocolatey/boxstarter/issues/240

Looking at [prepare_powershell_environment](https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/services/PowershellService.cs#L364), there's a bunch of environment variables that are nulled out at the start, but not `chocolateyForceX86`.

I'm thinking this should be nulled out as well

**Comment by ferventcoder** [comment]
This is fixed for 0.10.14. There is a beta that will be available soon for testing.

**Comment by ferventcoder** [comment]
Hi @flcdrg - totally missed your PR. 😢

**Comment by ferventcoder** [comment]
This is pushed up as a beta. This one is for chocolatey.lib.
