### ISSUE TITLE
template - Explain that license URL has to be in license file

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey/choco#1779]
According to @pauby, the source URL of `LICENSE.txt` has to be in `LICENSE.txt` itself. Currently most (if not all) packages have it in `VERIFICATIOn.txt` which doesn’t meet the requirement. This issue affects all the embedded packages in core-team repository. Many user (or even some moderators) use core-team packages as example for new-comers, which would then be very misleading.

I propose that we change https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/templates/ChocolateyLicenseFileTemplate.cs to emphasize this policy.

Note that “having URL in this exact file” is a *compulsary requirement*, not just a recommendation. It can be the reason of rejecting a package submission, even if it’s the only issue.

**Comment by bcurran3** [comment]
COMMENT: Sometimes their is no license URL and it is only found via display by the program installer or alongside the installed program files.

"having URL in this exact file" should be a recommendation since it's not always possible. It would be better stated as "If a license URL is available, include it at the top of the LICENSE.txt file."

**Comment by bcurran3** [comment]
Hey Franklin, I just noticed... shouldn't this be at https://github.com/chocolatey/chocolatey.org/issues instead?

**Comment by FranklinYu** [comment]
@bcurran3 I had a hard time choosing. If this were a future requirement to be discussed, then I should have put it in chocolatey.org repository. However, according to Paul:

1. This is already an established rule (although some moderators are unaware of it).
2. There is no documentation required (the package template says it all).

Based on the confirmation, I decided to create an issue here.

**Comment by pauby** [comment]
Just to be clear, and it's all I'll add here, I never said either of these:

> * This is already an established rule (although some moderators are unaware of it).
* There is no documentation required (the package template says it all).

Relevant to https://github.com/chocolatey/chocolatey.org/issues/575

**Comment by ferventcoder** [comment]
@FranklinYu @bcurran3 since this is an enhancement to a template file, this is the right place.

**Comment by ferventcoder** [comment]
I'm not sure what work there is to be done here. The template already has this:

https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/templates/ChocolateyLicenseFileTemplate.cs#L28

**Comment by ferventcoder** [comment]
If you are not seeing this with whatever template you are using (like if you use AU to generate the package docs), you should look to file an issue there. HTH
