### ISSUE TITLE
Track what account installed a package

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/choco#1783]
It would be useful if Chocolatey kept a record of what user account installed a package. The information could then be displayed by CHOCO LIST with output similar to:

7zip 19.0 (administrator)
7zip.commandline 16.02.0.20170209 (administrator)
7zip.install 19.0 (administrator)
7zip.portable 19.0 (administrator)
adblockplus-firefox 2.7.1 (bcurran)
adblockpluschrome 1.12.4 (bcurran)
adblockplusie 1.4 (bcurran)
addtoany-chrome 3.0.4 (bcurran)
AdobeAIR 32.0.0.89 (SYSTEM)

I'm sure it could easily be captured and saved in C:\ProgramData\chocolatey\.chocolatey as a .installuser file.

**Comment by ferventcoder** [comment]
That sounds like a great feature request, and in fact this already exists with Package Audit. https://chocolatey.org/docs/features-package-audit
