### ISSUE TITLE
What if the command "cinst geth-latest or cinst geth-stable" returns the pachage was not found? Even 

### ISSUE THREAD

**Issue by sasori943** [chocolatey/choco#1787]
Even if I have downloaded these packages to local.
![image](https://user-images.githubusercontent.com/32769584/55482255-b546c100-5656-11e9-806a-d18ce86e2616.png)

**Comment by gep13** [comment]
You are referring to these packages:

https://chocolatey.org/packages/geth-latest
https://chocolatey.org/packages/geth-stable

Both of which are in a state of rejected, meaning that Chocolatey will not install them.  Rejected packages are the same as the package not existing at all.

**Comment by gep13** [comment]
@sasori943 why have you edited this issue to remove the content that you posted?

**Comment by sasori943** [comment]
@gep13 Thank you, I thought that no one would reply to me, so I just closed it, I

**Comment by gep13** [comment]
@sasori943 as per the output from the command above, currently, Chocolatey is only looking at one place for a package called `geth-latest` and `geth-stable`.  It is looking at chocolatey.org.  Just because you have downloaded the nupkgs into that folder, Chocolatey hasn't been told to look at that location for them.

If you indeed want to continue with installing these rejected packages, then you would need to do something like the following:

`choco install geth-latest --source <path_to_folder_where_nupkgs_are>`

**NOTE:** These packages have been rejected for a reason, so please bear in mind that directly downloading and installing them could cause you problems.

**Comment by sasori943** [comment]
@gep13 I have written
`cinst geth-latest --source C:\Install\chocolatey -y`
![image](https://user-images.githubusercontent.com/32769584/55488362-859db600-5662-11e9-9f47-8e7676bee8da.png)
But it shows the visit to “C:\ProgramData\chocolatey\lib-bad” have been rejected.

**Comment by gep13** [comment]
@sasori943 are you running Chocolatey from an administrative console/powershell window?

**Comment by bcurran3** [comment]
@sasori943 - I'd really recommend you do experimenting on working packages.

**Comment by sasori943** [comment]
@gep13 Thanks a lot. 
 The installation of geth-latest failed with the error while running'C:\ProgramData\chocolatey\lib\geth-latest\tools\chocolateyInstall.ps1'
![image](https://user-images.githubusercontent.com/32769584/55521336-fa98dc00-56b2-11e9-8959-4bdf7a1081f6.png)
while the installation of geth-stable is successful,
![image](https://user-images.githubusercontent.com/32769584/55521116-eb655e80-56b1-11e9-8e6f-8d78e73aaab3.png)

I am not sure whether or not it's due to the master branch,
![image](https://user-images.githubusercontent.com/32769584/55521462-6da25280-56b3-11e9-9bc9-fb04c0634c8c.png)

**Comment by sasori943** [comment]
@bcurran3 Thank you.

**Comment by gep13** [comment]
@sasori943 where are you getting that second screenshot from?  It would appear that this information is out of date.

The error message that Chocolatey is providing pretty much says it all.  The URL that it has been instructed to download from doesn't exist, and as such, there is nothing Chocolatey can do.

This is not an issue with Chocolatey, but rather with the package that you are trying to use.  I would suggest that you reach out to the geth developers to update their documentation, or to the package maintainer of the geth packages to see if they can correct the issue.
