### ISSUE TITLE
Get-UninstallRegistryKey doesn't work with keys that have bracket characters(`[]`)

### ISSUE THREAD

**Issue by alFReD-NSH** [chocolatey/choco#1788]
### What You Are Seeing?

Get-UninstallRegistryKey showing registry keys contains some characters(eg `[` or `]`) as bad keys because where `Get-ItemProperty -Path` wouldn't accept that in the path.

### What is Expected?

It should work even if the registry keys contain `[]` characters

### How Did You Get This To Happen? (Steps to Reproduce)

Call `Get-UninstallRegistryKey $softwareName` when you have a $softwareName that represents your software which contains `[]`.

**Comment by ferventcoder** [comment]
Thanks for adding the issue.

**Comment by ferventcoder** [comment]
This is completed for 0.10.14 release. Thanks again for the contribution!
