### ISSUE TITLE
Unexpected errors for uninstalling old packages

### ISSUE THREAD

**Issue by kuroshi555** [chocolatey/choco#1789]
Going to give back story so I can get better assistance.

My original install was powershell then python2.7 with Microsoft visual studio test suits using chocolaatey as the source and running through docker in order to setup a fakeroot and boot linux from within Microsoft back in 2016 using any downloadable docker images. This works but I got left with a big hiccup. I created a shim using choco and npm to automate the packages back in late 2016 and then in Jan 2017 setup full automation tying in Atom/Sublime to auto-push source code into github which was tied to an SSL cert using nginx and guincorn. This was tied back to tripwire and I slated in a swap disk locally to speed up the creation time which allowed creating extra memory. This resulted in available of 5k+ independent docker images running simultaneously on a 2.6ghz processor and using nvram. Then I used docker to automate the build process and store a backup of source code on bitbucket. This it would auto deploy back to a VPS server I was using which was supposed to directly reflect my local machine/server as a raid mirror repository. This was then set as the base upper level and I setup my local machine as the lower level so I could keep my source code from accidentally interfering with any games or local software I might want to run or God knows have some random Microsoft software screw it up. In theory I should've been able to just boot back into Microsoft. Kill off my old partition and efi key/modules and the linux partition was supposed to be completely wrapped inside a container. So I'm currently getting left with a ton of packages that keep reflecting back to my local machine and just won't go away. My current problem has been trying to fully clean up the process and undo/remove a lot of the packages that come back no matter what and seem to be linked back to some internal component I never had access to on my machine. New HDD/SDD's or resets of the cmos along with full resets/scrubs don't do anything as it just auto-updates and redownloads each of these packages. My old licenses for anything I used will redownload the product and give me full access but this isn't a good thing as some products I don't want on my machine or the source code was bad/buggy. EX: old google/yahoo api's. I would be very grateful for the assistance as I need to finalize some cleanup in order to realize a package which allows instantly swapping from Microsoft > Linux > Android > any OS at the push of a button without a reboot and automatically connects to a users mbr/gpt/hybrid allowing full control over the device. I was going to use a different package manager but I don't really mind which one I use as long as it does the trick to remove these old packages as I have clean backups of what I need already but these are linked back to my machine. 

choco installed -> 403 packages found.
choco uninstall all -> 1 package removed
choco installed -> 0 packages found.

The below remain:

choco list -> 6372 packages found.
choco list --local -> 251 packages found.
choco list --local --all -> 135 packages found
choco list --local --all-versions -> 135 packages found.

choco list --remote -> 257 packages found.
choco list --remote -> 0 packages found.
choco list --remote --all-versions -> 0 packages found.
choco list --all-versions -> 4752 packages found.

**Comment by gep13** [comment]
@kuroshi555 thanks for reaching out.

I am really not sure I follow the issue that you are having, but just to break down a few things...

`choco list` - this command is going to enumerate the sources that you have configured for Chocolatey.  By default, this is the Chocolatey Community Repository, so the number of packages that are being returned are the number of packages hosted there, this has nothing to do with your local machine.

`choco list --local` - this is not a valid command.  See here for more information: https://chocolatey.org/docs/commands-list  I think what you are after is `choco list --local-only`

`choco list --local --all` - this is not a valid command.
`choco list --local --all-versions` - this is not a valid command.
`choco list --remote` - this is not a valid command.
`choco list --remote` - this is not a valid command.
`choco list --remote` - this is not a valid command.

`choco list --all-versions` - this is a valid command, but again, this will be enumerating your configured sources, not your local machine.

**Comment by kuroshi555** [comment]
Well I’m at awe because whoever setup this knockoff of your version
modified the commands to show others. I’ll put my files on GitHub later and
you can see as well

**Comment by gep13** [comment]
>@kuroshi555 said...
Well I’m at awe because whoever setup this knockoff of your version modified the commands to show others

I am not sure I follow what you mean here, but perhaps with more information it will become clear.

**Comment by bcurran3** [comment]
@gep13 

> choco list --local --all 
> choco list --local --all-versions

Valid or not, these do give results, the same results:

![image](https://user-images.githubusercontent.com/14026600/55571729-eb1d9100-56ba-11e9-8fff-e056925dd0bc.png)

------------------

@kuroshi555 

What version of Chocolatey are you using?

By chance are you using BoxStarter? https://chocolatey.org/packages/boxstarter

To be clear, you want to remove all the installed Chocolatey packages? If so, try this in PowerShell:

`Get-ChildItem -Path "$ENV:ChocolateyInstall\lib" -Exclude chocolatey | ?{if ($_.PSIsContainer){choco uninstall $_.name}}`

That should remove each package and leave you just with just Chocolatey installed. You may need to do it more than once as some packages won't uninstall due to dependencies and after the dependent packages are removed the dependencies should uninstall on the second pass.

**Comment by kuroshi555** [comment]
Yeah but the problem was I had a lower number before installing a few
visual studio programs and then it bumped the number up. I’m connected to
your source and it just automatically updates from the looks of it.

**Comment by bcurran3** [comment]
There's nothing in Chocolatey that auto updates. You have to manually run updates (or do so in a scheduled task). 

You might be noticing the DEPENDENCIES that install along with the various Visual Studio packages. Those would be extra packages you might not have expected but are needed for VS.

**Comment by gep13** [comment]
>@bcurran3 said...
Valid or not, these do give results, the same results

I don't think I said that they didn't return results, did I?  I said that they there were invalid since they are not doing what I believe they are intended to do.  My suspicion is that the original poster is attempting to list the locally installed packages, i.e. the output from `choco list --local-only`.  Using one of the invalid commands that are being used will cause the request to go to the currently configured sources, likely chocolatey.org, with potentially those options being passed as part of the search string.

**Comment by bcurran3** [comment]
@gep13 
Completely understood. My (not pointed out) point is there might be a bug there in the fact that if an invalid command switch is given, it should error out and not process results. There is no "--remote" switch, IMHO Chocolatey should fail with that passed.

**Comment by kuroshi555** [comment]
Just seeing if this replicates on other os or different windows version. I
will get back on this

**Comment by ferventcoder** [comment]
> My (not pointed out) point is there might be a bug there in the fact that if an invalid command switch is given, it should error out and not process results.
> IMHO Chocolatey should fail with that passed.

@bcurran3  You can absolutely make choco behave that way, but it's not the default for a variety of reasons -  `choco feature disable --name="'ignoreInvalidOptionsSwitches'"` (Ignore Invalid Options/Switches - If a switch or option is passed that is not recognized, should choco fail? Available in 0.9.10+.)

**Comment by ferventcoder** [comment]
@kuroshi555 

I believe you are looking for `choco list -lo` or `choco list --local-only`. There is no `--remote` or `--local` as of yet.
