### ISSUE TITLE
Allow setting no confirmation on each source

### ISSUE THREAD

**Issue by chevdor** [chocolatey/choco#179]
It would be nice to be able to define a default per repo. For instance, using my local repo would imply -y by default while using a public repo would require the -y.

**Comment by gep13** [comment]
That's a very interesting idea! :+1:

**Comment by TheCakeIsNaOH** [comment]
I have been playing around with this, and it looks like this will require chocolatey/nuget-chocolatey#6 to be implemented first.
If there are sources with and without the auto confirmation, then there is not a good way to figure out which source the nuget package is coming from.

**Comment by pauby** [comment]
The client should specify whether the package is to be installed without prompting, not the source. Then we are being very deliberate about where the control is for that.

If the source specifies no confirmation, we need to add something to the client to override that. This is a lot of work and changes to workaround not having to add a `-y` to the command line.

I'm not persuaded we need this.
