### ISSUE TITLE
choco.exe should error on invalid switches

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/choco#1790]
![image](https://user-images.githubusercontent.com/14026600/55574250-d04e1b00-56c0-11e9-8f8d-85ce0d82f6da.png)

![image](https://user-images.githubusercontent.com/14026600/55574708-e3adb600-56c1-11e9-965d-4c078184274c.png)

If an invalid switch is passed to Chocolatey, Chocolatey should report the invalid switch and error out.

**Comment by ferventcoder** [comment]
You can absolutely switch this behavior on, but it is not the default.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/wiki/ChocolateyConfiguration#flow-control

`ignoreInvalidOptionsSwitches` - Ignore Invalid Options/Switches - If a switch or option is passed that is not recognized, should choco fail? Available in 0.9.10+.

**Comment by ferventcoder** [comment]
That issue with setting labels is back again... argh

**Comment by ferventcoder** [comment]
Not an issue - the ability to set this exists currently. It's off by default for reasons that have to do with folks running switches from the commercial edition and having invalid licenses where the switches would not work. It's also set this way to allow undocumented switches to be passed through.
