### ISSUE TITLE
refreshenv doesn't update $env correctly

### ISSUE THREAD

**Issue by Ma3yTa** [chocolatey/choco#1791]
to reproduce:
```poweshell
choco install nvm -y
refreshenv
nvm on
```
![](https://i.gyazo.com/82413bd1677ae34c3b1730783471b63f.png)
![](https://i.gyazo.com/73563224c3d582b34fdc0f31febcee97.png)

**Comment by ferventcoder** [comment]
@Ma3yTa note you haven't installed the powershell profile. That's why it states "refreshing for ***cmd.exe***". Please see https://chocolatey.org/docs/troubleshooting#i-cant-get-the-powershell-tab-completion-working and once you add the profile it will work for powershell as well. HTH
