### ISSUE TITLE
I can't find Haskell stack binary that I installed with choco

### ISSUE THREAD

**Issue by NDelt** [chocolatey/choco#1793]
### What You Are Seeing?
Haskell stack binary is not installed correctly

### What is Expected?
`C:\Users\(USER)\AppData\Roaming\local\bin` doesn't exist

### How Did You Get This To Happen? (Steps to Reproduce)
choco install haskell-stack

### Output Log
https://gist.github.com/NDelt/01d6ea6d0cf113baf64a02ff02a37fb7

**Comment by pauby** [comment]
@NDelt This isn't a Chocolatey issue. The logs you provided don't show any installation of `haskell-stack` unfortunately. 

As this is a package issue, my suggestion would be to reach out to the [maintainer](https://chocolatey.org/packages/haskell-stack) if you are having issues with the package or use the [Gitter](https://gitter.im/chocolatey/choco) to reach out to the community.
