### ISSUE TITLE
Chocolatey GUI

### ISSUE THREAD

**Issue by nizzle10** [chocolatey/choco#1794]
STOP RIGHT HERE - DO NOT CREATE A TICKET FOR Chocolatey GUI ON THIS REPOSITORY

This is the repository for choco.exe, the command line interface for Chocolatey, and issues/feature suggestions should be limited to only choco. 

For Chocolatey GUI, you will need to head over to https://github.com/chocolatey/ChocolateyGUI and file a ticket there.

NOTE: Keep in mind we have an etiquette regarding communication that we expect folks to observe when they are looking for support in the Chocolatey community. https://github.com/chocolatey/choco/blob/master/README.md#etiquette-regarding-communication

**Comment by gep13** [comment]
@nizzle10 looks like you haven’t actually added any content here. As such, I am going to close this issue.
