### ISSUE TITLE
Issue: command not set on installing mongodb

### ISSUE THREAD

**Issue by subodhpareek18** [chocolatey/choco#1799]
I installed `node`, `yarn`, `redis` through chocolatey and I was able to use `node`, `yarn` `redis-cli` in the console. But after installing `mongodb` no such commands were set for `mongo`, `mongod` 

Also checked the folder `/c/ProgramData/chocolatey/bin` and there is no `.exe` for mongo there. 

What am I missing here? Would need the command to run my setup on the CLI.

**Comment by ferventcoder** [comment]
> But after installing `mongodb` no such commands were set for `mongo`, `mongod`

Hi @subodhpareek18 it's likely that if you inspect the log output, it would have mentioned that the PATH was updated and you should run `refreshenv` (cmd.exe by default, in powershell.exe if you have the Chocolatey profile set up) or restart your command shell to see those commands. 

This is a Windows limitation in that shells do not automatically receive updates from environment variables being adjusted outside of a process, even in subprocesses. 

> Also checked the folder `/c/ProgramData/chocolatey/bin` and there is no .exe for mongo there.

I'm going to say it's safe to assume that the MongoDB package is an installer package, thus it is working with the software installer and so there are no shims created.

Also based on your path, I'm going to guess you are in a bash shell of some sort, so all you need to do is restart it and you will see those items if they are added to the PATH by the installer. If that shell is in something like Clink, Cmder, or ConEmu, you have to shut down the entire thing and reopen it for the shells/tabs (or subprocesses if you will) to get the updated environment information.

Alternatively, that's where refreshenv comes in. However it is not available to bash-based shells on Windows. One could try to update your profile and see if that catches the environment changes.

**Comment by ferventcoder** [comment]
By the way @subodhpareek18 - questions are best served by reaching out on Gitter chat or through one of the other methods.
