### ISSUE TITLE
Unable to install Windows Feature 'FS-FileServer' on Windows Server 2016 DataCenter

### ISSUE THREAD

**Issue by ansariwn** [chocolatey/choco#1811]
### What You Are Seeing?
I am trying to install a windows feature 'FS-FileServer' on Windows Server 2016 DataCenter
### What is Expected?
I expect the feature to be installed when I run the Chocolatey command

### How Did You Get This To Happen? (Steps to Reproduce)
Run the following chocolatey command:
PS C:\Windows\system32> choco install FS-FileServer -source windowsFeatures

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
Chocolatey v0.10.8
Installing the following packages:
FS-FileServer
By installing you accept licenses for the packages.
[Windows Features] Deployment Image Servicing and Management tool
[Windows Features] Version: 10.0.14393.0
[Windows Features] Image Version: 10.0.14393.2457
[Windows Features] Error: 0x800f080c
[Windows Features] Feature name FS-FileServer is unknown.
[Windows Features] A Windows feature name was not recognized.
[Windows Features] Use the /Get-Features option to find the name of the feature in the image and try the command again.
[Windows Features] The DISM log file can be found at C:\Windows\Logs\DISM\dism.log

Chocolatey installed 0/1 packages. 1 packages failed.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures

FS-FileServer - FS-FileServer
~~~

</p>
Running the `choco list --source windowsFeatures` command produces the following output

Chocolatey v0.10.8
Deployment Image Servicing and Management tool
Version: 10.0.14393.0
Image Version: 10.0.14393.2457
Features listing for package : Microsoft-Windows-Foundation-Package~31bf3856ad364e35~amd64~~10.0.14393.0
----------------------------------------------------------- | -----------------------------
Feature Name                                                | State                        
----------------------------------------------------------- | -----------------------------
NetFx4ServerFeatures                                        | Enabled                      
NetFx4                                                      | Enabled                      
NetFx4Extended-ASPNET45                                     | Disabled                     
MicrosoftWindowsPowerShellRoot                              | Enabled                      
MicrosoftWindowsPowerShell                                  | Enabled                      
iSCSITargetServer-PowerShell                                | Disabled                     
PKIClient-PSH-Cmdlets                                       | Disabled                     
KeyDistributionService-PSH-Cmdlets                          | Enabled                      
TlsSessionTicketKey-PSH-Cmdlets                             | Enabled                      
Tpm-PSH-Cmdlets                                             | Enabled                      
MicrosoftWindowsPowerShellV2                                | Enabled                      
WindowsPowerShellWebAccess                                  | Disabled                     
DataCenterBridging-LLDP-Tools                               | Disabled                     
Server-Psh-Cmdlets                                          | Enabled                      
MicrosoftWindowsPowerShellISE                               | Enabled                      
RemoteAccessMgmtTools                                       | Disabled                     
RemoteAccessPowerShell                                      | Disabled                     
RasServerAdminTools                                         | Disabled                     
DamgmtTools                                                 | Disabled                     
WSS-Product-Package                                         | Disabled                     
ActiveDirectory-PowerShell                                  | Disabled                     
DirectoryServices-DomainController                          | Disabled                     
DirectoryServices-ISM-Smtp                                  | Disabled                     
HostGuardianService-Package                                 | Disabled                     
DirectoryServices-AdministrativeCenter                      | Disabled                     
RemoteAccess                                                | Disabled                     
RemoteAccessServer                                          | Disabled                     
RasRoutingProtocols                                         | Disabled                     
Web-Application-Proxy                                       | Disabled                     
RightsManagementServices-Role                               | Disabled                     
RightsManagementServices                                    | Disabled                     
RMS-Federation                                              | Disabled                     
RightsManagementServices-AdminTools                         | Disabled                     
NetworkController                                           | Disabled                     
NetworkControllerTools                                      | Disabled                     
IIS-WebServerRole                                           | Disabled                     
IIS-WebServer                                               | Disabled                     
IIS-CommonHttpFeatures                                      | Disabled                     
IIS-Security                                                | Disabled                     
IIS-RequestFiltering                                        | Disabled                     
IIS-StaticContent                                           | Disabled                     
IIS-DefaultDocument                                         | Disabled                     
IIS-DirectoryBrowsing                                       | Disabled                     
IIS-HttpErrors                                              | Disabled                     
IIS-HttpRedirect                                            | Disabled                     
IIS-WebDAV                                                  | Disabled                     
IIS-ApplicationDevelopment                                  | Disabled                     
IIS-WebSockets                                              | Disabled                     
IIS-ApplicationInit                                         | Disabled                     
IIS-NetFxExtensibility                                      | Disabled                     
IIS-NetFxExtensibility45                                    | Disabled                     
IIS-ISAPIExtensions                                         | Disabled                     
IIS-ISAPIFilter                                             | Disabled                     
IIS-ASPNET                                                  | Disabled                     
IIS-ASPNET45                                                | Disabled                     
IIS-ASP                                                     | Disabled                     
IIS-CGI                                                     | Disabled                     
IIS-ServerSideIncludes                                      | Disabled                     
IIS-HealthAndDiagnostics                                    | Disabled                     
IIS-HttpLogging                                             | Disabled                     
IIS-LoggingLibraries                                        | Disabled                     
IIS-RequestMonitor                                          | Disabled                     
IIS-HttpTracing                                             | Disabled                     
IIS-CustomLogging                                           | Disabled                     
IIS-ODBCLogging                                             | Disabled                     
IIS-CertProvider                                            | Disabled                     
IIS-BasicAuthentication                                     | Disabled                     
IIS-WindowsAuthentication                                   | Disabled                     
IIS-DigestAuthentication                                    | Disabled                     
IIS-ClientCertificateMappingAuthentication                  | Disabled                     
IIS-IISCertificateMappingAuthentication                     | Disabled                     
IIS-URLAuthorization                                        | Disabled                     
IIS-IPSecurity                                              | Disabled                     
IIS-Performance                                             | Disabled                     
IIS-HttpCompressionStatic                                   | Disabled                     
IIS-HttpCompressionDynamic                                  | Disabled                     
IIS-WebServerManagementTools                                | Disabled                     
IIS-ManagementConsole                                       | Disabled                     
IIS-LegacySnapIn                                            | Disabled                     
IIS-ManagementScriptingTools                                | Disabled                     
IIS-ManagementService                                       | Disabled                     
IIS-IIS6ManagementCompatibility                             | Disabled                     
IIS-Metabase                                                | Disabled                     
IIS-WMICompatibility                                        | Disabled                     
IIS-LegacyScripts                                           | Disabled                     
IIS-FTPServer                                               | Disabled                     
IIS-FTPSvc                                                  | Disabled                     
IIS-FTPExtensibility                                        | Disabled                     
WAS-WindowsActivationService                                | Disabled                     
WAS-ProcessModel                                            | Disabled                     
WAS-NetFxEnvironment                                        | Disabled                     
WAS-ConfigurationAPI                                        | Disabled                     
IIS-HostableWebCore                                         | Disabled                     
MSMQ                                                        | Disabled                     
MSMQ-Services                                               | Disabled                     
MSMQ-Server                                                 | Disabled                     
MSMQ-Triggers                                               | Disabled                     
MSMQ-ADIntegration                                          | Disabled                     
MSMQ-HTTP                                                   | Disabled                     
MSMQ-Multicast                                              | Disabled                     
MSMQ-DCOMProxy                                              | Disabled                     
MSMQ-RoutingServer                                          | Disabled                     
WCF-Services45                                              | Enabled                      
WCF-HTTP-Activation45                                       | Disabled                     
WCF-TCP-Activation45                                        | Disabled                     
WCF-Pipe-Activation45                                       | Disabled                     
WCF-MSMQ-Activation45                                       | Disabled                     
WCF-TCP-PortSharing45                                       | Enabled                      
IdentityServer-SecurityTokenService                         | Disabled                     
ManagementOdata                                             | Disabled                     
DSC-Service                                                 | Disabled                     
ADCertificateServicesRole                                   | Disabled                     
CertificateServices                                         | Disabled                     
OnlineRevocationServices                                    | Disabled                     
WebEnrollmentServices                                       | Disabled                     
NetworkDeviceEnrollmentServices                             | Disabled                     
CertificateEnrollmentPolicyServer                           | Disabled                     
CertificateEnrollmentServer                                 | Disabled                     
IPAMServerFeature                                           | Disabled                     
DeviceHealthAttestationService                              | Disabled                     
BITSExtensions-AdminPack                                    | Disabled                     
Gateway-UI                                                  | Disabled                     
BITSExtensions-Upload                                       | Disabled                     
WCF-HTTP-Activation                                         | Disabled                     
WCF-NonHTTP-Activation                                      | Disabled                     
Smtpsvc-Admin-Update-Name                                   | Disabled                     
Smtpsvc-Service-Update-Name                                 | Disabled                     
WebAccess                                                   | Disabled                     
Microsoft-Windows-Web-Services-for-Management-IIS-Extension | Disabled                     
BusScan-ScanServer                                          | Disabled                     
Printing-InternetPrinting-Server                            | Disabled                     
RPC-HTTP_Proxy                                              | Disabled                     
Gateway                                                     | Disabled                     
UpdateServices                                              | Disabled                     
UpdateServices-Services                                     | Disabled                     
UpdateServices-Database                                     | Disabled                     
UpdateServices-WidDatabase                                  | Disabled                     
WorkFolders-Server                                          | Disabled                     
FSRM-Infrastructure                                         | Disabled                     
Microsoft-Windows-FCI-Client-Package                        | Disabled                     
UpdateServices-RSAT                                         | Disabled                     
UpdateServices-API                                          | Disabled                     
UpdateServices-UI                                           | Disabled                     
FSRM-Infrastructure-Services                                | Disabled                     
DirectoryServices-ADAM                                      | Disabled                     
IPAMClientFeature                                           | Disabled                     
Microsoft-Windows-ServerEssentials-ServerSetup              | Disabled                     
AuthManager                                                 | Disabled                     
ServerCore-WOW64                                            | Enabled                      
Printing-Server-Foundation-Features                         | Disabled                     
Printing-Server-Role                                        | Disabled                     
Printing-LPDPrintService                                    | Disabled                     
Printing-Client                                             | Enabled                      
Printing-Client-Gui                                         | Enabled                      
ServerCore-EA-IME-WOW64                                     | Enabled                      
NetFx3ServerFeatures                                        | Disabled                     
NetFx3                                                      | Disabled with Payload Removed
Server-Shell                                                | Enabled                      
Internet-Explorer-Optional-amd64                            | Enabled                      
Server-Gui-Mgmt                                             | Enabled                      
Server-Gui-Mgmt_onecore                                     | Disabled                     
RSAT                                                        | Enabled                      
Storage-Replica-AdminPack                                   | Disabled                     
Server-Manager-RSAT-File-Services                           | Disabled                     
Server-RSAT-SNMP                                            | Disabled                     
DNS-Server-Tools                                            | Disabled                     
WINS-Server-Tools                                           | Disabled                     
DfsMgmt                                                     | Disabled                     
ADCertificateServicesManagementTools                        | Disabled                     
CertificateServicesManagementTools                          | Disabled                     
OnlineRevocationServicesManagementTools                     | Disabled                     
RSAT-AD-Tools-Feature                                       | Disabled                     
RSAT-ADDS-Tools-Feature                                     | Disabled                     
DirectoryServices-DomainController-Tools                    | Disabled                     
DirectoryServices-ADAM-Tools                                | Disabled                     
BitLocker-RemoteAdminTool                                   | Disabled                     
BdeAducExtTool                                              | Disabled                     
NPSMMC                                                      | Disabled                     
Licensing-UI                                                | Disabled                     
Licensing-Diagnosis-UI                                      | Disabled                     
Microsoft-Windows-Deployment-Services-Admin-Pack            | Disabled                     
DHCPServer-Tools                                            | Disabled                     
FailoverCluster-Mgmt                                        | Disabled                     
NetworkLoadBalancingManagementClient                        | Disabled                     
NFS-Administration                                          | Disabled                     
WindowsServerBackupSnapin                                   | Enabled                      
FaxServiceConfigRole                                        | Disabled                     
NPSManagementTools                                          | Disabled                     
RightsManagementServicesManagementTools                     | Disabled                     
Security-SPP-Vmw                                            | Disabled                     
FSRM-Management                                             | Disabled                     
Windows-Defender-Gui                                        | Enabled                      
Microsoft-Hyper-V                                           | Disabled                     
Microsoft-Hyper-V-Offline                                   | Disabled                     
Microsoft-Hyper-V-Online                                    | Disabled                     
RSAT-Hyper-V-Tools-Feature                                  | Disabled                     
Microsoft-Hyper-V-Management-Clients                        | Disabled                     
Microsoft-Hyper-V-Management-PowerShell                     | Disabled                     
VmHostAgent                                                 | Disabled                     
HostGuardian                                                | Disabled                     
AppServer                                                   | Disabled                     
Microsoft-Windows-Deployment-Services                       | Disabled                     
Microsoft-Windows-Deployment-Services-Deployment-Server     | Disabled                     
Microsoft-Windows-Deployment-Services-Transport-Server      | Disabled                     
BitLocker                                                   | Disabled                     
Bitlocker-Utilities                                         | Disabled                     
ShieldedVMToolsAdminPack                                    | Disabled                     
BitLocker-NetworkUnlock                                     | Disabled                     
SearchEngine-Server-Package                                 | Disabled                     
File-Services-Search-Service                                | Disabled                     
FaxServiceRole                                              | Disabled                     
NPAS-Role                                                   | Disabled                     
OEM-Appliance-OOBE                                          | Disabled                     
ServerMediaFoundation                                       | Disabled                     
MediaPlayback                                               | Enabled                      
WindowsMediaPlayer                                          | Enabled                      
WebDAV-Redirector                                           | Disabled                     
LegacyComponents                                            | Disabled                     
DirectPlay                                                  | Disabled                     
Printing-LPRPortMonitor                                     | Disabled                     
Printing-InternetPrinting-Client                            | Disabled                     
Printing-AdminTools-Collection                              | Disabled                     
Windows-Identity-Foundation                                 | Disabled                     
Microsoft-Hyper-V-Common-Drivers-Package                    | Enabled                      
Microsoft-Hyper-V-Guest-Integration-Drivers-Package         | Enabled                      
Microsoft-Windows-NetFx-VCRedist-Package                    | Enabled                      
Microsoft-Windows-Printing-PrintToPDFServices-Package       | Enabled                      
Microsoft-Windows-Printing-XPSServices-Package              | Enabled                      
Microsoft-Windows-Client-EmbeddedExp-Package                | Enabled                      
Printing-PrintToPDFServices-Features                        | Enabled                      
Printing-XPSServices-Features                               | Enabled                      
MSRDC-Infrastructure                                        | Disabled                     
TelnetClient                                                | Disabled                     
TFTP                                                        | Disabled                     
TIFFIFilter                                                 | Disabled                     
SMB1Protocol                                                | Enabled                      
MultiPoint-Connector                                        | Disabled                     
MultiPoint-Connector-Services                               | Disabled                     
MultiPoint-Tools                                            | Disabled                     
ServerManager-Core-RSAT                                     | Disabled                     
ServerManager-Core-RSAT-Role-Tools                          | Disabled                     
ServerManager-Core-RSAT-Feature-Tools                       | Disabled                     
FailoverCluster-AdminPak                                    | Disabled                     
FailoverCluster-PowerShell                                  | Disabled                     
HardenedFabricEncryptionTask                                | Disabled                     
ServicesForNFS-ServerAndClient                              | Disabled                     
ServerForNFS-Infrastructure                                 | Disabled                     
ClientForNFS-Infrastructure                                 | Disabled                     
SimpleTCP                                                   | Disabled                     
SmbDirect                                                   | Enabled                      
Windows-Defender-Features                                   | Enabled                      
Windows-Defender                                            | Enabled                      
EnhancedStorage                                             | Disabled                     
Microsoft-Windows-GroupPolicy-ServerAdminTools-Update       | Disabled                     
RSAT-RDS-Tools-Feature                                      | Disabled                     
BiometricFramework                                          | Disabled                     
WindowsServerBackup                                         | Disabled                     
DFSR-Infrastructure-ServerEdition                           | Disabled                     
DNS-Server-Full-Role                                        | Disabled                     
Windows-Internal-Database                                   | Disabled                     
iSCSITargetStorageProviders                                 | Disabled                     
BITS                                                        | Disabled                     
LightweightServer                                           | Disabled                     
MultipathIo                                                 | Disabled                     
NetworkLoadBalancingFullServer                              | Disabled                     
Containers                                                  | Disabled                     
PeerDist                                                    | Disabled                     
RemoteAssistance                                            | Disabled                     
ServerCore-EA-IME                                           | Enabled                      
DataCenterBridging                                          | Disabled                     
DiskIo-QoS                                                  | Disabled                     
Server-Drivers-General                                      | Enabled                      
Server-Drivers-Printers                                     | Enabled                      
SNMP                                                        | Disabled                     
WMISnmpProvider                                             | Disabled                     
WindowsStorageManagementService                             | Disabled                     
Remote-Desktop-Services                                     | Disabled                     
SessionDirectory                                            | Disabled                     
SBMgr-UI                                                    | Disabled                     
VolumeActivation-Full-Role                                  | Disabled                     
WirelessNetworking                                          | Disabled                     
Xps-Foundation-Xps-Viewer                                   | Disabled                     
SMBBW                                                       | Disabled                     
SetupAndBootEventCollection                                 | Disabled                     
RasCMAK                                                     | Disabled                     
DFSN-Server                                                 | Disabled                     
DHCPServer                                                  | Disabled                     
FailoverCluster-AutomationServer                            | Disabled                     
FailoverCluster-CmdInterface                                | Disabled                     
FRS-Infrastructure                                          | Disabled                     
FileServerVSSAgent                                          | Disabled                     
WINSRuntime                                                 | Disabled                     
iSCSITargetServer                                           | Disabled                     
iSNS_Service                                                | Disabled                     
P2P-PnrpOnly                                                | Disabled                     
QWAVE                                                       | Disabled                     
ServerMigration                                             | Disabled                     
SMBHashGeneration                                           | Disabled                     
Licensing                                                   | Disabled                     
FailoverCluster-FullServer                                  | Disabled                     
CCFFilter                                                   | Disabled                     
Dedup-Core                                                  | Disabled                     
MultiPoint-Role                                             | Disabled                     
ResumeKeyFilter                                             | Disabled                     
SmbWitness                                                  | Disabled                     
FabricShieldedTools                                         | Disabled                     
Storage-Replica                                             | Disabled                     
SoftwareLoadBalancer                                        | Disabled                     
RasRip                                                      | Disabled                     
SearchEngine-Client-Package                                 | Enabled                      
Client-DeviceLockdown                                       | Disabled                     
Client-EmbeddedShellLauncher                                | Disabled                     
Client-EmbeddedBootExp                                      | Disabled                     
Client-EmbeddedLogon                                        | Disabled                     
Client-KeyboardFilter                                       | Disabled                     
Client-UnifiedWriteFilter                                   | Disabled                     
FileAndStorage-Services                                     | Enabled                      
Storage-Services                                            | Enabled                      
File-Services                                               | Disabled                     
CoreFileServer                                              | Disabled                     
ServerCore-Drivers-General                                  | Enabled                      
ServerCore-Drivers-General-WOW64                            | Enabled                      
The operation completed successfully.

</details>

**Comment by pauby** [comment]
Chocolatey uses dism.exe for the features name. As there is no FS-FileServer feature (thorugh DISM) this is why you're getting the error.

To find the equivalent feature from DISM use `dism.exe /online /get-features`.
