### ISSUE TITLE
Update NuGet.exe to current recommended stable version 4.9.4

### ISSUE THREAD

**Issue by daviburg** [chocolatey/choco#1815]
NuGet.exe current stable version is 4.9.4 per:

https://www.nuget.org/downloads

Available as package here: https://www.nuget.org/packages/NuGet.CommandLine/

The NuGet.exe in Chocolatey hasn't been updated in a while.

I happen to have specific issue with the older version of NuGet but the details of are beyond the scope of this - simply the latest recommended version of NuGet should be used and installed by Chocolatey.

**Comment by gep13** [comment]
@daviburg this is not the place to raise issues about packages on chocolatey.org.  This should have been mentioned in the Issue Template that would have been shown when you created this issue.

There is an open PR here:

https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1259

For addressing the issue that you mention.  I would suggest that you subscribe to that for notifications on when this is merged.
