### ISSUE TITLE
Choco project NuGet.config does not specify any package source so build fails unless dev has local configuration

### ISSUE THREAD

**Issue by daviburg** [chocolatey/choco#1816]
### What You Are Seeing?
            restore_packages:
            
                 [echo] Finding and restoring all packages (c:\src\choco\lib\NuGet\NuGet.exe restore 'c:\src\choco\src\chocolatey.sln')
...
                 [exec] Unable to find version '1.1.86' of package 'coveralls.io'.
                 [exec] Unable to find version '2.6.4' of package 'NUnit.Runners'.
                 [exec] c:\src\choco\.build\compile.step(66,6):
                 [exec] External Program Failed: c:\src\choco\lib\NuGet\NuGet.exe (return code was 1)

This is also what caused the initial issue for https://github.com/chocolatey/choco/issues/700

### What is Expected?
The project should define the source(s) it depends on.

This is as simple as adding the three lines:

```
  <packageSources>
    <add key="NuGet official package source" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
```

To existing nuget.config

Then you well get successful package restore that doesn't depend on the dev machine config of NuGet:

            restore_packages:
            
                 [echo] Finding and restoring all packages (c:\src\choco\lib\NuGet\NuGet.exe restore 'c:\src\choco\src\chocolatey.sln')
                 [exec] MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin'.
                 [exec] Restoring NuGet package NUnit.Runners.2.6.4.
                 [exec] Restoring NuGet package coveralls.io.1.1.86.
                 [exec]   GET https://api.nuget.org/v3-flatcontainer/nunit.runners/2.6.4/nunit.runners.2.6.4.nupkg
                 [exec]   OK https://api.nuget.org/v3-flatcontainer/nunit.runners/2.6.4/nunit.runners.2.6.4.nupkg 31ms
                 [exec] Installing NUnit.Runners 2.6.4.
                 [exec] Adding package 'NUnit.Runners.2.6.4' to folder 'C:\CxCache'
                 [exec] Added package 'NUnit.Runners.2.6.4' to folder 'C:\CxCache'

### How Did You Get This To Happen? (Steps to Reproduce)

Run build.bat after fresh repo cloning, don't have a machine specific definition of the nuget source.

**Comment by gep13** [comment]
@daviburg the issue here is actually due to the fact that the default NuGet.config file in the ApplicationData folder changed to no longer include the v2 source.  i.e. the only entries in that file are now:

```
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />
```

Adding an additional source there of:

```
    <add key="nuget2" value="https://www.nuget.org/api/v2/" />
```

corrects the problem that you are seeing.  I agree that an entry in the project NuGet.config file to include this source would also work though.

**Comment by ferventcoder** [comment]
@gep13 since this is straight code change, I don't see a need to put a milestone on it. So whenever it comes in for a PR, we can merge it into stable and then up to master.

**Comment by ferventcoder** [comment]
Whoops, did not mean to close this one.

**Comment by ferventcoder** [comment]
This has been merged into stable at https://github.com/chocolatey/choco/commit/d01b58bab7b354eca3c4be3d16728e96fde22882 and master at https://github.com/chocolatey/choco/commit/e9e5bc98ccca5bbea31d68f2c47779e9db5d1a52. Let us know if you run into any additional issues.

**Comment by aks2161989** [comment]
I am still facing the same issue. All I did was clone this repo and build it. The messages I get after building are as follows:

>                  [echo] Finding and restoring all packages (F:\cSharpProgramming\choco\lib\NuGet\NuGet.exe restore 'F:\c
> SharpProgramming\choco\src\chocolatey.sln')
>                  [exec] Unable to find version '1.1.86' of package 'coveralls.io'.
>                  [exec] Unable to find version '2.6.4' of package 'NUnit.Runners'.
>                  [exec] F:\cSharpProgramming\choco\.build\compile.step(66,6):
>                  [exec] External Program Failed: F:\cSharpProgramming\choco\lib\NuGet\NuGet.exe (return code was 1)
>                  [echo] Compiling F:\cSharpProgramming\choco\src\chocolatey.sln.
>                  [echo] Building on 4.0
> 
> 
>             F:\cSharpProgramming\choco\.build\compile.step(173,14):
>             Failed to start MSBuild.
>                 F:\cSharpProgramming\choco\.build\compile.step(173,14):
>                 External Program Failed: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe (return code was 1)
> 
> 
> 
> 
> Nested build failed.  Refer to build log for exact reason.
