### ISSUE TITLE
Choco install from your own choco server

### ISSUE THREAD

**Issue by domugtong** [chocolatey/choco#1820]
Hello Everyone

I just created my own choco server that can be accessed globally
How do i install a specific package from my own server and not on the default choco package repository?

Thanks,

**Comment by bcurran3** [comment]
You're answers are here; https://chocolatey.org/docs/commands-source

I'm a little confused by your wording if you are trying to push packages to your server or install from the server, either way, it's all about letting your Chocolatey client know about your server (source).

**Comment by ferventcoder** [comment]
Also take a look at the organizational deployment guide at https://chocolatey.org/docs/how-to-setup-offline-installation
