### ISSUE TITLE
upgrade - pins appear to be ignored if the pinned package is a dependency (same for except)

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1821]
### What You Are Seeing?

https://chocolatey.org/packages/ccenhancer#comment-4455530181

### What is Expected?

Not to upgrade the package

### How Did You Get This To Happen? (Steps to Reproduce)

https://chocolatey.org/packages/ccenhancer#comment-4455530181

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
Adding later
~~~

</p>

</details>

**Comment by TheCakeIsNaOH** [comment]
Appears to be a duplicate of #2749, but that one has more information, so closing this one in favor of that one.
