### ISSUE TITLE
Install for all users

### ISSUE THREAD

**Issue by therepo90** [chocolatey/choco#1830]
How to install one package for all users?

**Comment by bcurran3** [comment]
This really depends on the package. i.e. if you install Office365 it will be available to all users.

Since you raise this question, obviously you've got a program (or possibly some configuration script) that installs to the current users's APPDATA dir. In such case you probably need to force re-install the package under the "other user's" account for it to work. 

Sometimes a program might install, be available globally, but only have icons locally under the default installation account.

As you can see, there are a bunch of scenarios.

Not sure if it's been done, but theoretically you could have Chocolatey installed under multiple user accounts by changing the default install location. Then each of those user accounts would hold different information as to what packages are installed. 
REF: https://chocolatey.org/docs/installation#installing-to-a-different-location

@ferventcoder will end up chiming in soon with why or more likely why not to do this.

Force re-installing under the different user account is most likely your best option.

**Comment by therepo90** [comment]
Forcing re-installing means multiple instances on same pc ? Also I need to do same installation for every user? Thats can get messy I guess

**Comment by bcurran3** [comment]
No.

Most programs overwrite themselves in the case of a forced re-install.

I think the point I didn't get across well enough is that **it all depends on the payload of the package**. MOST programs install "globally."

**Comment by therepo90** [comment]
very well then , thanks ;)

**Comment by ferventcoder** [comment]
@therepo90 by default Chocolatey is meant for global system-wide installations. If there is an MSI that is going to a particular user, one needs to add `ALLUSERS=1` (or 2, it's always confusing reading the docs - I have it noted somewhere) to the silent arguments if it is not defaulted to that.

**Comment by unix-bomber** [comment]
Saving others some time, and adding to ferventcoder, here's an example

choco install atom -y --force --params "'ALLUSERS=1"

I was not able to find the above example in documentation

**Comment by suntong** [comment]
`choco install fiddler -y --force --params "ALLUSERS=1"`

But it still installs to the current users's APPDATA dir. 

```
 The install of fiddler was successful.
  Software installed to 'C:\Users\me\AppData\Local\Programs\Fiddler'
```

Shall I open another issue instead?

**Comment by unix-bomber** [comment]
@suntong 
I am not trying to be snarky, or come off as rude, just verifying

Have you checked the AppData for the users you're trying to get fiddler to install with?
Fiddler should be installed for all users after that command

**Comment by suntong** [comment]
Oh, I shall be asking a different question then, 

How can I have `choco install` to install programs to under `C:\Program Files\`, instead of into somebody's personal private folder?

**Comment by unix-bomber** [comment]
¯\_(ツ)_/¯ information here seems like your best bet

> This really depends on the package. i.e. if you install Office365 it will be available to all users.
> 
> Since you raise this question, obviously you've got a program (or possibly some configuration script) that installs to the current users's APPDATA dir. In such case you probably need to force re-install the package under the "other user's" account for it to work.
> 
> Sometimes a program might install, be available globally, but only have icons locally under the default installation account.
> 
> As you can see, there are a bunch of scenarios.
> 
> Not sure if it's been done, but theoretically you could have Chocolatey installed under multiple user accounts by changing the default install location. Then each of those user accounts would hold different information as to what packages are installed.
> REF: https://chocolatey.org/docs/installation#installing-to-a-different-location
> 
> @ferventcoder will end up chiming in soon with why, or more likely why not, to do this.
> 
> Force re-installing under the different user account is most likely your best option.

**Comment by suntong** [comment]
> Force re-installing under the different user account is most likely your best option

So, in other words,  having `choco install` to install programs to under `C:\Program Files\` will be less likely. 

OK. If that's the reason why this issue is closed.

**Comment by ferventcoder** [comment]
> How can I have choco install to install programs to under C:\Program Files\, instead of into somebody's personal private folder?

Depending on the package and the underlying software (most of the time software installers), that's where software gets installed. If Fiddler is going into AppData, then I would investigate Fiddler installer itself. Once you've determined how to get it to work to your liking, you will know how to adjust install arguments given to the Chocolatey package itself. HTH

**Comment by drowhunter** [comment]
I installed cmder under account 1

`choco install cmder`

install goes well, icons are created program works

Then I went to account 2 and cmder wasn't showing

so I run `choco install cmder` on account 2 and it tells me that it's already installed,  wtf?

**Comment by pauby** [comment]
@drowhunter This is explained above.
