### ISSUE TITLE
Add fork me on github badge

### ISSUE THREAD

**Issue by TomasRoj** [chocolatey/choco#1845]
I would add a badge "fork me on github" or "view on github" so anybody can see its open-source. When I firstly visited your websites I thought its proprietary, only after searching on github I found its open-source. I think it would be quite usefull.

**Comment by AdmiringWorm** [comment]
There is a github icon on the front page of chocolatey.
Personally I would think that this would suggest that there is at least some code available on github.

![image](https://user-images.githubusercontent.com/1474648/59161176-97c32700-8adf-11e9-8bd1-62a6891b40fa.png)

**Comment by TomasRoj** [comment]
Normal person (like me back than) cannot find it. I still think this is not good solution

**Comment by pauby** [comment]
This is not something we plan to add at the moment.

I'm going to go ahead and close this, but we can reopen it if necessary.
