### ISSUE TITLE
Do not offer a default option when prompting for a user choice

### ISSUE THREAD

**Issue by christianrondeau** [chocolatey/choco#185]
I suggest not offering a default option when offering choices to the end user. This will avoid cases when typing too fast ends up with <kbd>Enter</kbd> is not being preceeded by the desired number. It also shortens the output and makes less stuff to read.

There are currently at least two cases where a default option is offered.

``` bash
Which version of vagrant would you like to uninstall?
 1) None [Default - Press Enter]
 2) 1.6.5
 3) All versions
```

Also:

``` bash
Do you want to run the script?
 NOTE: If you choose not to run the script, the installation will
 fail.
 Skip is an advanced option and most likely will never be wanted.

 1) yes
 2) no [Default - Press Enter]
 3) skip
```

For more details: https://groups.google.com/forum/#!topic/chocolatey/UVncL7PxXRg

(Moved from https://github.com/chocolatey/chocolatey/issues/693)

**Comment by ferventcoder** [comment]
Merged into stable at https://github.com/chocolatey/choco/commit/e992c4f5ad489330561cbe3127e8fd8f1c133142 and will be released in 0.9.9.5.
