### ISSUE TITLE
FEATURE REQUEST: Add installed packages binary to the system path

### ISSUE THREAD

**Issue by AresS31** [chocolatey/choco#1858]
Adding an extra switch to automatically add newly installed packages to the system path (`$Env:Path`) would be a very usefull feature. For instance, when installing `Java`, `Python` or other packages with a CLI if chocolatey could automatically add their binaries to the system path that would be a signifcant time saver.

**Comment by vexx32** [comment]
Shouldn't this be done by the packages themselves during their install scripts?

**Comment by bcurran3** [comment]
Most of the time this is done via shims:
https://chocolatey.org/docs/features-shim

**Comment by AresS31** [comment]
@bcurran3 thanks for redirecting me to the right link.
