### ISSUE TITLE
install - install w/forcex86 without 32 bit url errors with "This package does not support 64 bit architecture" error

### ISSUE THREAD

**Issue by easybe** [chocolatey/choco#1859]
Hi,

I am trying to package a 64 bit only program using AU. Therefore, as described in the documentation, omitting `url` (and related fields) in `$packageArgs` used in `Install-ChocolateyZipPackage @packageArgs`. When running `update.ps1` I get:
```
This package does not support 64 bit architecture.                                                  
At C:\Users\user\AppData\Local\Temp\chocolatey\au\chocolatey\helpers\functions\Get-ChocolateyWebFil 
e.ps1:265 char:5
 ```
Looking at https://github.com/chocolatey/choco/blob/c57829c325e95c99b553a0e26e7d7aac8e233725/src/chocolatey.resources/helpers/functions/Get-ChocolateyWebFile.ps1#L264
it does not seem to me that this is only executed on 32 bit systems, even though the comment reads:
```
# If we're on 32 bit or attempting to force 32 bit and there is no
# 32 bit url, we need to throw an error.
```
Or, am I missing something here?

I'll be happy to provide more information if I am really on to something here. Otherwise, I apologize for wasting your time in advance.

Cheers,
Ezra.

**Comment by vexx32** [comment]
Depends on the surrounding code, I'd have to have a thorough look, I suppose.

Though, just that one line is a bit problematic. _That_ should really be `[string]::IsNullOrEmpty($url)` heh.

**Comment by easybe** [comment]
Yes, you are right. At second glance, I see that on a 64 bit system `$url` should be set here: https://github.com/chocolatey/choco/blob/c57829c325e95c99b553a0e26e7d7aac8e233725/src/chocolatey.resources/helpers/functions/Get-ChocolateyWebFile.ps1#L243
I'll check again what is going on...

**Comment by easybe** [comment]
OK, the error seems to be expected. For some reason AU sets `$Env:chocolateyForceX86` on my 64 bit system. Still, the error message is somewhat misleading. I think we should change it to read:
```
This package does not support 32 bit architecture.
```
`[string]::IsNullOrEmpty()` should be used all over the place, I guess:
```
$ git grep -l "\-ne \$null.\+-ne ''"
chocolatey.resources/helpers/ChocolateyTabExpansion.ps1
chocolatey.resources/helpers/chocolateyScriptRunner.ps1
chocolatey.resources/helpers/functions/Get-CheckSumValid.ps1
chocolatey.resources/helpers/functions/Get-ChocolateyWebFile.ps1
chocolatey.resources/helpers/functions/Get-FtpFile.ps1
chocolatey.resources/helpers/functions/Get-WebFile.ps1
chocolatey.resources/helpers/functions/Get-WebFileName.ps1
chocolatey.resources/helpers/functions/Get-WebHeaders.ps1
chocolatey.resources/helpers/functions/Install-BinFile.ps1
chocolatey.resources/helpers/functions/Install-ChocolateyPackage.ps1
chocolatey.resources/helpers/functions/Start-ChocolateyProcessAsAdmin.ps1
chocolatey.resources/helpers/functions/UnInstall-ChocolateyZipPackage.ps1
```

**Comment by chtof** [comment]
At the end of your update.ps1 file, you should have something like:
`Update -ChecksumFor 64`
Is it the case?

**Comment by easybe** [comment]
Yes, I figured that out now and all works. The only issue I see here is the misleading error message when `$Env:chocolateyForceX86` is set...

**Comment by gep13** [comment]
@easybe I am glad to hear that you got this working.  Based on what I am seeing here, I feel that this is a modification/feature request for AU itself, and not for Chocolatey.  Is that correct?

If so, can I request that you create an issue here:

https://github.com/majkinetor/au

and we can close out this issue.

**Comment by easybe** [comment]
No, the error is in this repos. I've created a PR: https://github.com/chocolatey/choco/pull/1867

**Comment by ferventcoder** [comment]
I see it, it's a bug. The PR looks good, so this is going to go into 0.10.16.
