### ISSUE TITLE
Terminology improvements in choco.exe help output

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/choco#1861]
The following are produced by choco.exe, thus this isn't in documentation issues. All referenced output is via Chocolatey v0.10.15

```
Commands
 * install - installs packages from various sources
```
ENHANCEMENT: "various sources" just seems misleading. What percentage of free or commercial users actually install packages from multiple sources? I'd guess most use one source or two sources; i.e. internal repository and possibly the community repo as a 2nd. Maybe "installs packages" would be be better, simpler, cover the broader base.

```
* outdated - retrieves packages that are outdated. Similar to upgrade all --noop
```
BUG: It doesn't retrieve packages, the command retrieves package information about outdated packages/lists

````
* pack - packages up a nuspec to a compiled nupkg
````

ENHANCEMENT: Could say "packages nuspec, scripts, and other Chocolatey package resources into a nupkg file

````
* push - pushes a compiled nupkg
````

ENHANCEMENT: Could say "pushes a compiled nupkg to a repository (or maybe source)"

````
* new - generates files necessary for a chocolatey package from a template
````

ENHANCEMENT: new actually creates multiple template files as a package template. It could say "creates template files for creating a new Chocolatey package"

```
 * unpackself - have chocolatey set itself up
```

SUBJECTIVE: Might be be better stated as "Re-installs Chocolatey" or "Re-installs Chocolatey base files"

**Comment by ferventcoder** [comment]
I like it - Would you like to try your hand at a pull request on this one?
