### ISSUE TITLE
All binaries are not scanned by VirusTotal

### ISSUE THREAD

**Issue by chtof** [chocolatey/choco#1865]
2 examples between others one:

1/ [spacedesk-server](https://chocolatey.org/packages/spacedesk-server) installs spacedesk_driver_Win_10_64_v0918_BETA.msi if OS is Windows 10 and spacedesk_driver_Win_7_32_v0918_BETA.msi for others OS.
  => Only the second one has been scanned by Virus Total.

2/ [jtalert](https://chocolatey.org/packages/jtalert) installs HamApps_JTAlert_AL_2.13.8_Setup.exe if OS is Windows 10 and HamApps_JTAlert_2.13.8_Setup.exe for others OS.
  => Only the second one has been scanned by Virus Total.

So, all Chocolatey packages where the binary depends on the OS version should be concerned.

Expected result: All binaries who can be installed by a Chocolatey script should be scanned by Virus Total.

**Comment by ferventcoder** [comment]
This needs to be transferred over to chocolatey.org. However as this could be a security issue, I think there is a more responsible way to disclose this information. https://chocolatey.org/security#report-issue
