### ISSUE TITLE
remove pending packages task - search only top level level package folders to clean up

### ISSUE THREAD

**Issue by phasemaster** [chocolatey/choco#1866]
I have the problem that any choco command I issue takes quite a bit (multiple seconds) of time. This is even the case for something simple like "choco list --local-only".

Investigating this, I found that it is due to a combination of these factors: 
- The RemovePendingPackagesTask performs a full-depth file search of the PackagesLocation searching for pending package files.
- In some of my packages, I have directory symlinks that point to the actual location of the package data in the tools directory or that point to the source location of the package data on a network share.
- Some of my packages have large amount of package data (close to 1GB) and the network is not always extremely fast. This causes the full search to take up to few tens of seconds. 
- There is no way to prevent choco from searching full-depth, e.g. by marking the large or remote package data subdirectory somehow.

I wonder if it is really necessary to search a symlinked subdirectory for pending package files (since they are never copied around anyway). But in any case, I would be really happy if I could at least have the possibility to tell choco to not search a subdirectory (taking the responsibility myself if anything bad happens due to not searching, of course).

**Comment by ferventcoder** [comment]
@phasemaster interesting set up - glad to know what it is as that provides context. I think we can definitely accommodate this aspect.

**Comment by jimis** [comment]
I found this issue while trying to skip `RemovePendingPackagesTask`. On Github Actions, the first execution of `choco` takes minutes, and the debug log indicates that task is the reason.
```
Tue, 19 Jan 2021 11:21:36 GMT Received arguments: install ccache --version 3.7.12 --yes --no-progress --not-silent --verbose --debug
Tue, 19 Jan 2021 11:21:36 GMT RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
Tue, 19 Jan 2021 11:21:36 GMT Sending message 'PreRunMessage' out if there are subscribers...
Tue, 19 Jan 2021 11:21:36 GMT [Pending] Removing all pending packages that should not be considered installed...
Tue, 19 Jan 2021 11:23:17 GMT Performing validation checks.
```

See the timestamps in the last two lines. I assume it takes that long because the runner has pre-installed a ton of packages.

Is it possible to somehow skip this step?

**Comment by mojojoseph** [comment]
> I found this issue while trying to skip `RemovePendingPackagesTask`. On Github Actions, the first execution of `choco` takes minutes, and the debug log indicates that task is the reason.
> 
> Is it possible to somehow skip this step?

I've run into the same situation - `RemovePendingPackagesTask` is following symlinks in installed package directories (notably `rsync` which has a `C -> C:\` link).  Hopefully PR #2218 can get on the train.
