### ISSUE TITLE
Add warning when run under non elevated PS ISE

### ISSUE THREAD

**Issue by RussKie** [chocolatey/choco#1868]
Copying from https://github.com/chocolatey/chocolatey.org/issues/679

If choco is run from non-elevated PS ISE "_Do you want to continue? ([Y]es/[N]o)_" line is not shown:
* ISE
![image](https://user-images.githubusercontent.com/4403806/59964823-51db7980-9549-11e9-87b0-912be4a077aa.png)

However if the same is run from cmd or PS cli, everything is displayed correctly:
* cmd: 
![image](https://user-images.githubusercontent.com/4403806/59964808-f1e4d300-9548-11e9-9acb-ce8485c296e8.png)
* Console2 cmd: 
![image](https://user-images.githubusercontent.com/4403806/59964795-d5489b00-9548-11e9-862c-472c88db2e44.png)
* Console2 PSx64
![image](https://user-images.githubusercontent.com/4403806/59964818-23f63500-9549-11e9-99b9-39a2d70324d5.png)

## Desired:
Consider adding a warning when the choco is run from under PS ISE (if possible).

**Comment by vexx32** [comment]
This may just be a bug in the ISE. The ISE provides its own weird implementation of a faux-console host. I'm not sure there's really anything Chocolatey can realistically do here if the ISE doesn't provide a basic prompting API for chocolatey's calls to hit. :/

**Comment by ferventcoder** [comment]
Yeah, there is not much we can do, we provide the warning like the others, but nothing comes through as you have noticed.

**Comment by RussKie** [comment]
My suggestion was to add a warning not to run choco from PS ISE due to the above issue.

**Comment by gep13** [comment]
@RussKie how, and where, do you suggest this warning be shown?

**Comment by RussKie** [comment]
```
PS C:\Development\gitextensions> choco install notepad++
Chocolatey v0.10.11
Chocolatey detected you are not running from an elevated command shell
 (cmd/powershell).

You're running from under ISE and it is known to have issue.
Please restart the operation from a command prompt instead.

Good bye!
```

**Comment by ferventcoder** [comment]
@RussKie I'm all for it, but how do we detect that we are running from ISE in a reliable way?

**Comment by ferventcoder** [comment]
You mentioned "(if possible)", that's where @vexx32 and my comments were based on.

**Comment by bcurran3** [comment]
> @RussKie I'm all for it, but how do we detect that we are running from ISE in a reliable way?

$psISE
