### ISSUE TITLE
Error when i test my package : ERROR: Exception calling "Start" with "0" argument(s): "The specified executable is not a valid application for this OS platform."

### ISSUE THREAD

**Issue by deckbsd** [chocolatey/choco#1869]
### What You Are Seeing?
ERROR: Exception calling "Start" with "0" argument(s): "The specified executable is not a valid application for this OS platform."

### What is Expected?
My package fully installed

### How Did You Get This To Happen? (Steps to Reproduce)
Here is my install sciprt :
`
$ErrorActionPreference = 'Stop';
$toolsDir   = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"
$url        = 'https://dckapps.azurewebsites.net/Sources/DckReboot.zip'
$url64      = 'https://dckapps.azurewebsites.net/Sources/DckReboot.zip'

$packageArgs = @{
  packageName   = $env:ChocolateyPackageName
  unzipLocation = $toolsDir
  fileType      = 'exe'
  url           = $url
  url64bit      = $url64

  softwareName  = 'dck-reboot*'

  checksum      = '7c5f3dc88eb17c31bed80edf72c0c5e0be6457e6fc6761369f790ad773ed3052'
  checksumType  = 'sha256'
  checksum64    = '7c5f3dc88eb17c31bed80edf72c0c5e0be6457e6fc6761369f790ad773ed3052'
  checksumType64= 'sha256'

  silentArgs    = "/qn /norestart /l*v `"$($env:TEMP)\$($packageName).$($env:chocolateyPackageVersion).MsiInstall.log`""
  validExitCodes= @(0, 3010, 1641)
}

Install-ChocolateyPackage @packageArgs

Install-ChocolateyZipPackage $packageName $url $toolsDir [$url64 -checksum $checksum -checksumType $checksumType -checksum64 $checksum64 -checksumType64 $checksumType64]`

Then i do a "choco pack". Everything fine, the package is created. Then i do :
choco install dckreboot.4.0.0.nupkg -dv -s .

and i end up with :
ERROR: Exception calling "Start" with "0" argument(s): "The specified executable is not a valid application for this OS platform."

I tried to install a program from a zip file. The exe is 32 bits, i'm on a 64 bits. it shoud works anyway but it doesn't. I can't figured out why.

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
Installing dckreboot...
Ensuring 'C:\Users\myuser\AppData\Local\Temp\chocolatey' exists
Running Start-ChocolateyProcessAsAdmin -validExitCodes '0 3010 1641' -workingDirectory 'C:\Users\myuser\AppData\Local\Temp\chocolatey\dckreboot\4.0.0' -statements '/qn /norestart /l*v "C:\Users\myuser\AppData\Local\Temp\chocolatey\dckreboot.4.0.0.MsiInstall.log" ' -exeToRun 'C:\Users\myuser\AppData\Local\Temp\chocolatey\dckreboot\4.0.0\DckReboot.zip'
Test-ProcessAdminRights: returning True
Elevating permissions and running ["C:\Users\myuser\AppData\Local\Temp\chocolatey\dckreboot\4.0.0\DckReboot.zip" /qn /norestart /l*v "C:\Users\myuser\AppData\Local\Temp\chocolatey\dckreboot.4.0.0.MsiInstall.log" ]. This may take a while, depending on the statements.
ERROR: Exception calling "Start" with "0" argument(s): "The specified executable is not a valid application for this OS platform."
 at Start-ChocolateyProcessAsAdmin, C:\ProgramData\chocolatey\helpers\functions\Start-ChocolateyProcessAsAdmin.ps1: line 253
at Install-ChocolateyInstallPackage, C:\ProgramData\chocolatey\helpers\functions\Install-ChocolateyInstallPackage.ps1: line 334
at Install-ChocolateyPackage, C:\ProgramData\chocolatey\helpers\functions\Install-ChocolateyPackage.ps1: line 408
at <ScriptBlock>, C:\ProgramData\chocolatey\lib\dckreboot\tools\chocolateyinstall.ps1: line 25
at <ScriptBlock>, C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1: line 48
at <ScriptBlock>, <No file>: line 1
~~~

</p>

</details>

**Comment by ferventcoder** [comment]
You are calling `Install-ChocolateyPackage`, I think you want to be calling `Install-ChocolateyZipPackage` instead.

**Comment by deckbsd** [comment]
Hello, 

i was only calling Install-ChocolateyZipPackage at the beginning but if i do that, no file is downloaded and i'm still ending with error.

**Comment by deckbsd** [comment]
Actually , there is something wrong with choco, the 64 bits url always start with [ . 

From the log if i live the $url64 parameter with empty string : " -url64bit '['"

**Comment by gep13** [comment]
@deckbsd can you show the exact script that you are currently trying to use?  There currently are `[` and `]` in the script that you have shown in your first post, and I want to make sure that they are not typos.

In the call to `Install-ChocolateyPackage` you are using the splatted arguments variable `packageArgs` but in the call to `Install-ChocolateyZipPackage` you aren't.  Is there a reason for this?

**Comment by ferventcoder** [comment]
@deckbsd nothing wrong with Chocolatey in this regard as we would have a LOT of broken packages out there. Most likely there is something wrong with the way the script has been written.

We ask for the full log output for a reason, it is helpful for us to determine what the issue is. If you would like help determining what you are doing wrong, please provide that. Thanks in advance!
