### ISSUE TITLE
Pyhon/Python3 not installing

### ISSUE THREAD

**Issue by KrisJanssen** [chocolatey/choco#1872]
Choco installs every package I require just fine _except_ python/python3:

It tells me Python was installed to C:\Python37 but clearly nothing is there.

![2019-07-04 09_41_47-Windows (C_)](https://user-images.githubusercontent.com/1765614/60649234-ef845200-9e41-11e9-9956-25b210e95b40.png)

However, manually removing the /Quiet option revealed that, as a user who also had VS2019 deployed to his machine, Python is already installed elsewhere but not added to path:

![2019-07-04 09_53_52-tools](https://user-images.githubusercontent.com/1765614/60649355-2195b400-9e42-11e9-9f26-6facd431cdb3.png)

This might not be an issue solely with Chocolatey but I can imagine this being a somewhat confusing UX: 

choco should not report installation to a path if it didn't actually verify installation actually occurred...

**Comment by pauby** [comment]
@KrisJanssen This looks mainly to be a package issue. Have you reached out to the maintainers of the packages to let them know about this? You can use the 'Contact Maintainers' link on the package page to do that.

**Comment by KrisJanssen** [comment]
@pauby I will propagate this to them. Thx for the feedback!

**Comment by KrisJanssen** [comment]
In fact, ownership of this package seems to sit with chocolatey... the referenced Github account for user 'Purity' (@TomOne on Github) no longer holds a ref to the actual package it seems. ...

![2019-07-04 15_09_47-Chocolatey Gallery _ Python 3 7 3](https://user-images.githubusercontent.com/1765614/60669295-4b64d000-9e6e-11e9-9022-3075cc8a4852.png)

**Comment by pauby** [comment]
That is the Chocolatey Core Team packages repository which is not Chocolatey Software (I know, it's confusing!).

You can find them at https://github.com/chocolatey-community/chocolatey-coreteampackages - you should be able to raise an issue over there in the first instance. If we need to re-open this issue for any reason then we can do so.
