### ISSUE TITLE
Chocolatey not using correct package source

### ISSUE THREAD

**Issue by syntaxman** [chocolatey/choco#1876]
I installed the Vivaldi browser approximately 7/3/19 using chocolatey.exe. The installation seemed fine, except that the feature allowing changing the default search provider didn't work. This wasn't just a bug. This was an intentional change. I assumed this was a problem with the browser software, but the solution was to install directly from vivaldi.net. Chocolatey documentation says that is what it is doing, but it clearly installed from a different package.

**Comment by pauby** [comment]
@syntaxman I've just downloaded the x64 and x86 binaries from Vivaldi directly and the checksums for both of those match the ones listed in the Vivaldi Chocolatey package so they are the installers from the official site.

Can I ask that if you have issues with the package you contact the package maintainers using the 'Contact Maintainers' link on the package page?

In the meantime, I'm going to close this issue but we can reopen should it be needed.

**Comment by pauby** [comment]
Related to #1875
