### ISSUE TITLE
Installation script fails on PowerShell Core 7 preview 1

### ISSUE THREAD

**Issue by IanKemp** [chocolatey/choco#1880]
### What You Are Seeing?

Installation fails because PowerShell Core currently does not support the [`IWebProxy.IsBypassed`](https://docs.microsoft.com/en-us/dotnet/api/system.net.iwebproxy.isbypassed) method. The problematic line is `install.ps1:130`.

If you know you don't have a proxy, a workaround is to set `$env:chocolateyIgnoreProxy = "true"` before running the install to skip the problematic code entirely, so this is a minor issue. It might be useful to add this workaround to the official installation page until PS Core does support the aforementioned method.

### What is Expected?

Installation succeeds.

### How Did You Get This To Happen? (Steps to Reproduce)

Under PowerShell Core, download and run the installation script using the official steps from the Chocolately installation web page at https://chocolatey.org/install#install-with-powershellexe

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
C:\> Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
Unable to set PowerShell to use TLS 1.2 and TLS 1.1 due to old .NET Framework installed. If you see underlying connection closed or trust errors, you may need to do one or more of the following: (1) upgrade to .NET Framework 4.5+ and PowerShell v3, (2) specify internal Chocolatey package location (set $env:chocolateyDownloadUrl prior to install or host the package internally), (3) use the Download + PowerShell method of install. See https://chocolatey.org/install for all install options.
Getting latest version of the Chocolatey package for download.
iex : Exception calling "IsBypassed" with "1" argument(s): "Operation is not supported on this platform."
At line:1 char:51
+ ... ess -Force; iex ((New-Object System.Net.WebClient).DownloadString('ht ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
+ FullyQualifiedErrorId : PlatformNotSupportedException,Microsoft.PowerShell.Commands.InvokeExpressionCommand
~~~

</p>

</details>

**Comment by pauby** [comment]
The install script doesn't support PowerShell Core installation (see the top of the [installation page](https://chocolatey.org/packages/install) which says that Core is not supported).

I'm sure this was brought up previously but I cannot seem to find it!

**Comment by AdmiringWorm** [comment]
> @pauby said...
> I'm sure this was brought up previously but I cannot seem to find it!

The only issue I have seen that I can remember is related to PowerShell Core is the following issue https://github.com/chocolatey/chocolatey.org/issues/655

But that is more for the SecurityProtocol used when downloading, rather than the Web proxy.

**Comment by pauby** [comment]
@AdmiringWorm It may have been a conversation I had. Perhaps on [Gitter](https://gitter.im/chocolatey/chocolatey.org). But it's niggling at me to find it! 😄

**Comment by IanKemp** [comment]
> The install script doesn't currently support PowerShell Core (see the **Requirements** section at the top of the [installation page](https://chocolatey.org/packages/install) which says that Core is not yet supported).

Somehow I managed to miss that...

**Comment by nathan-alden-hp** [comment]
Are there plans to support PowerShell Core? Seems like it should be an easy win.

**Comment by ferventcoder** [comment]
> Are there plans to support PowerShell Core? Seems like it should be an easy win.

There are plans to support it at some point for sure. It's a long road from here to there though.

**Comment by ferventcoder** [comment]
> The only issue I have seen that I can remember is related to PowerShell Core is the following issue chocolatey/chocolatey.org#655

@AdmiringWorm that issue is now resolved

**Comment by ferventcoder** [comment]
Moving this over to chocolatey.org repo as it is an issue with the installation script there, not with choco.exe itself.
