### ISSUE TITLE
Chocolatey does not resolve dotnet4.7 dependency unless it is installed

### ISSUE THREAD

**Issue by facorread** [chocolatey/choco#1883]
I am trying to contribute an updated version of [keybase](https://chocolatey.org/packages/keybase/4.0.0.20190507) where I add the recommended dependency on [dotnet4.7](https://chocolatey.org/packages/dotnet4.7). My fork of that code is on [github](https://github.com/facorread/chocolatey-packages/tree/c623def20df2c84af17f49ff107ec24039de0887/manual/keybase). I noticed the following problem:

### What You Are Seeing?

When dotnet4.7 is not installed, chocolatey refuses to install keybase:

```
keybase not installed. An error occurred during installation:
 Unable to resolve dependency 'dotnet4.7'.
```

When dotnet4.7 is installed, keybase installs just fine.

### What is Expected?

Chocolatey should resolve the dependency.

Maybe, if for some reason the dotnet4.7 dependency needs installation followed by reboot, Chocolatey should describe this requirement rather than just fail.

### How Did You Get This To Happen? (Steps to Reproduce)

```
# dotnet4.7 is not installed at the outset
choco install -s 'C:\Users\dirac\Downloads\chocolatey-packages\manual\keybase' keybase # Fail
choco install dotnet4.7 # Success
choco install -s 'C:\Users\dirac\Downloads\chocolatey-packages\manual\keybase' keybase  # Success

```
### Output Log

Find the output log [here](https://gist.github.com/facorread/b5eb278e527fb1a96f659bbc2c5eca10).

**Comment by bcurran3** [comment]
> Maybe, if for some reason the dotnet4.7 dependency needs installation followed by reboot, Chocolatey should describe this requirement rather than just fail.

From https://chocolatey.org/packages/dotnet4.7

> This package skips automatic verification:
> 
> Requires a reboot after KB2919355

------------------------

> keybase not installed. An error occurred during installation:
>  Unable to resolve dependency 'dotnet4.7'.

I'm guessing that you're manually installing using the local .nupkg file. When you do that, the dependency isn't resolved. You need to install it first from the community repository or elsewhere. Chocolatey will find and install the dependency when it downloads and installs it from chocolatey.org.

choco v0.10.15+ will warn on pending reboots by default when checking and reporting state.

My suggestion: push the package up to the CCR and test, chances are all will be good unless the keybase installer warns/aborts/does something unexpected when dotnet4.7 was just installed and the system hasn't rebooted yet. Then you'll probably need a testing exemption to pass the program through moderation.

**Comment by facorread** [comment]
I think you are right. Thanks for helping clarifying the issue. I will continue contributing the fix to the maintainers.
