### ISSUE TITLE
"Unable to find type [ordered]" when trying to install nvm.portable

### ISSUE THREAD

**Issue by peter-sabath** [chocolatey/choco#1893]
I have tried to install nvm.portable on different windows 10 machines. All of them have PS 5.1 and Powershell-Core (6.2.2) installed.
```
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
On some of them there is an `Error while running 'C:\ProgramData\chocolatey\lib\nvm.portable\tools\chocolateyinstall.ps1'` from using the `[ordered]` keyword to create an ordered dictionary.

The `[ordered]` keyword was introduced with PS 3.0 so the installed versions support it. Using `$dict = [ordered}@{} ` works fine when manually entered in the PS.

Since Choco does not spawn a powershell but use an internal host it seems that something goes wrong there.

Any suggestions / registry keys to check?

**Comment by ferventcoder** [comment]
@peter-sabath Chocolatey uses SMA, which in this case should use PowerShell 5.1. If you are seeing an error with a package, it would be worth seeing the actual error that is produced. Now this is likely not a choco issue but more likely something with PowerShell that is installed on those machines. 

To get to the bottom of it, it's best to start off by running that installation again with `-dv --log-file="'c:\install.log'"` and then putting that log output into a gist. That will help us see what's going on. You likely ignored all of what was requested here when filing this issue, but that is all helpful and helps us determine what's going on.

**Comment by peter-sabath** [comment]
Hi fervent,
find the [Install log here.](https://gist.github.com/peter-sabath/551eff08622c98628f1c980d2dc3d637)

As you (and I) assumed the log confirms that there is a problem with the SMA on the affected machine(s).

The OS on that machine is a Windows 10 Pro (1803)
The Choco process loads the SMA from the GAC. The Version is 6.1.7600.16385 dated 2018-04-12.

```
2019-08-05 11:12:08,748 1536 [ERROR] - ERROR: Unable to find type [ordered]: make sure that the assembly containing this type is loaded.
    at System.Management.Automation.TypeLiteral.resolveType()
   at System.Management.Automation.UnaryPrefixPostFixNode.ExecuteConversion(Object operand, Token op)
   at System.Management.Automation.UnaryPrefixPostFixNode.ExecuteUnary(Object operand, Token op, ExecutionContext context)
   at System.Management.Automation.UnaryPrefixPostFixNode.Execute(Array input, Pipe outputPipe, ExecutionContext context)
   at System.Management.Automation.AssignmentStatementNode.Execute(Array input, Pipe outputPipe, ExecutionContext context)
   at System.Management.Automation.StatementListNode.ExecuteStatement(ParseTreeNode statement, Array input, Pipe outputPipe, ArrayList& resultList, ExecutionContext context)
```

I have absolutely no clue why this parsing problem of the SMA is happening.
The version on my machine is exactly the same. Just the date is different and matches the date where I upgraded my machine to W10 1903. Others on 1803 also work well.

**Comment by pauby** [comment]
Due to this issue being stale, I'm going to go ahead and close it. We can always re-open it again if needed.
