### ISSUE TITLE
Remote Installation from Network Share

### ISSUE THREAD

**Issue by bscherrerspvg** [chocolatey/choco#1894]
I'm attempting to do the following: 

Invoke-Command -Endpoint "" -ScriptBlock { choco install notepadplusplus -y }

In this scenario, I've removed the the chocolatey site source and added a simple server I've set up in our environment.

The package downloads, but then fails with an Access Denial failure:

notepadplusplus v7.1.1
notepadplusplus package files install completed. Performing other installation steps.
Installing notepadplusplus...
WARNING: May not be able to find '\\spvgapp6\software\Admin Tools\npp.7.7.1.Installer.exe'. Please use full path for executables.
ERROR: Exception calling "Start" with "0" argument(s): "Access is denied"
The install of notepadplusplus was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\notepadplusplus\tools\chocolateyinstall.ps1'.
 See log for details.

Here is the Install Script:

$ErrorActionPreference = 'Stop';
$packageName= 'notepadplusplus'

$packageArgs = @{
  packageName   = $packageName
  fileType      = 'exe'
  file          = '\\spvgapp6\software\Admin Tools\npp.7.7.1.Installer.exe'
  silentArgs    = "/S"
  validExitCodes= @(0)
  softwareName = 'Notepadplusplus*'
}

Install-ChocolateyInstallPackage @packageArgs

I think it's a double hop issue.  What is the recommended practice to get this to work?  The package installs fine from local command, but when trying to install on a remote machine, I'm not having much luck.  Any pointers?

**Comment by pauby** [comment]
You've missed the double slash on the server name `file = '\spvgapp6\software\Admin Tools\npp.7.7.1.Installer.exe'`. it should be `file = '\\spvgapp6\software\Admin Tools\npp.7.7.1.Installer.exe'`.

**Comment by bscherrerspvg** [comment]
Thanks.  I noticed that too, however, I'm not sure why. I might have accidentally mistyped above.

$ErrorActionPreference = 'Stop';
$packageName= 'notepadplusplus'

$packageArgs = @{
  packageName   = $packageName
  fileType      = 'exe'
  file          = '\\spvgapp6\software\Admin Tools\npp.7.7.1.Installer.exe'
  silentArgs    = "/S"
  validExitCodes= @(0)
  softwareName = 'Notepadplusplus*'
}

Install-ChocolateyInstallPackage @packageArgs

**Comment by ferventcoder** [comment]
It's a double hop issue. This also tends to affect local machine accounts and permissions. You could attempt to follow the settings you find at https://github.com/chocolatey/choco/wiki/How-To-Host-Feed#local-folder-permissions (for the folder path) and see if that works. 

Note this is not a Chocolatey issue but rather a remote execution issue, so I'll need to close this as Not an Issue.
