### ISSUE TITLE
outdated - calling --ignore-pinned still counts pinned packages in exit code

### ISSUE THREAD

**Issue by kintrupf** [chocolatey/choco#1896]
When I use the command "choco outdated --ignore-pinned" to get a list of available, non-pinned upgrades I'll still get the exit code 2 when only pinned packages have upgrades available.

This is unexpected, since the command does not list the pinned packages (as I asked it not to do).
"choco outdated --ignore-pinned" should only return 2 when a non-pinned packages have  upgrades available, otherwise it should return 0.

The output on my console to demonstrate the problem:

[C:\]choco outdated --ignore-pinned
Chocolatey v0.10.15
Outdated Packages
 Output is package name | current version | available version | pinned?

Chocolatey has determined 0 package(s) are outdated.

[C:\]echo %errorlevel%
2

[C:\]

**Comment by ferventcoder** [comment]
This looks like a bug - thanks for pointing that out.

**Comment by styleah** [comment]
Do you know when this bug will be fixed ?
