### ISSUE TITLE
(doc) Install-ChocolateyPackage - example 3 seems to be incorrect or incomplete, not calling the .msi variables

### ISSUE THREAD

**Issue by captainjs** [chocolatey/choco#1899]
Hi,
On this page:
https://chocolatey.org/docs/helpers-install-chocolatey-package

Look the example 3:

$url        = 'https://somewhere.com/file.msi'
$url64      = 'https://somewhere.com/file-x64.msi'

It's never calling these variables.

Maybe:
A: a step is missing in the example
B: there's a copy paste error in the example

Can you please have a look and fix it?

Cheers,

**Comment by amok0815** [comment]
Duplicate of #
