### ISSUE TITLE
choco install should not ask if it should run the install script

### ISSUE THREAD

**Issue by DanAtkinson** [chocolatey/choco#190]
Hi!

If I give chocolatey a command to install something, say `choco install chocolateygui`, then I shouldn't have to confirm that I want to run the scripts as my consent has already been given to install by running the `install` command.

Whilst running an update should generate this prompt, installing a package shouldn't, in my opinion.

Many thanks

**Comment by gep13** [comment]
You have the option to turn this off, if you so wish:

https://github.com/chocolatey/choco/issues/178

This feature was added in order to improve the overall security of using Chocolatey.

**Comment by DanAtkinson** [comment]
Thanks!
