### ISSUE TITLE
Install specific package version like package@1.2.3

### ISSUE THREAD

**Issue by doublemcz** [chocolatey/choco#1909]
It would be more convinient to set package version after @ to install specific version of a package like 
`choco install nodejs@10.2.13` instead of specifing longer `choco install nodejs --version 10.2.13`.

**Comment by ExE-Boss** [comment]
This might be a duplicate of #1278.

**Comment by wbreza** [comment]
You can specify the version through the `--version` flag.  

Example `choco install nodejs --version=10.2.13`
