### ISSUE TITLE
unknown option " --version"

### ISSUE THREAD

**Issue by chrisdostert** [chocolatey/choco#191]
per : https://github.com/chocolatey/choco/wiki/CommandsPack#options-and-switches

choco pack --version '0.0.1' should work but it throws "unknown option "--version""

however, 
choco pack -version '0.0.1' works. (only one - preceding version vs two)

**Comment by ferventcoder** [comment]
You are probably not using version 0.9.9+

**Comment by ferventcoder** [comment]
@chrisdostert can you let me know if this was the issue?

**Comment by chrisdostert** [comment]
Yep that was it, thanks. Sorry for no reply but it was on my work computer so couldn't check till this AM.

**Comment by ferventcoder** [comment]
Cool, glad it wasn't an issue with choco.
