### ISSUE TITLE
BUG: choco install with force to re-install a package states "not installed" and "already installed"

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/choco#1916]
(very trivial bug)

![image](https://user-images.githubusercontent.com/14026600/64913744-a9c5ee80-d6fa-11e9-88b1-9b7f07b91711.png)

There is some confusing and unnecessary statements issued by choco.exe when force reinstalling a package.

> **siv.5.41.nupkg is not installed**. Installing...
> **siv v5.41 already installed**. Forcing reinstall of version '5.41'.

I propose the logic for checking if a package is already or not installed should be cleaned up somewhat.

> cup siv.5.41.nupkg -f
> (...)
>  Please use upgrade if you meant to upgrade to a new version.

I propose the "please upgrade" statement be removed when cup or choco upgrade commands are used.

**Comment by ferventcoder** [comment]
Please note the very first warning. Call `cup siv -s . -f` and let me know if you get the weird messaging still.

**Comment by bcurran3** [comment]
OK, seems it's just another one of those Nuget things related to installing a local package. Up until now I only experienced problems with provided package parameters. Sorry for the confusion.

![image](https://user-images.githubusercontent.com/14026600/64934690-52f70c80-d801-11e9-9731-21b2dcadf621.png)
