### ISSUE TITLE
Document chocolateyPackageFolder, chocolateyPackageName and chocolateyPackageVersion variables

### ISSUE THREAD

**Issue by mjiderhamn** [chocolatey/choco#192]
Apparently it is possible to access some nuspec information from within `chocolateyInstall.ps1` and `chocolateyUninstall.ps1` using `$env:chocolateyPackageFolder`, `$env:chocolateyPackageName` and **`$env:chocolateyPackageVersion`** (duplicated in `$env:packageFolder`, `$env:packageName` and `$env:packageVersion`).

This should be documented somewhere.

**Comment by mjiderhamn** [comment]
Indeed, it seems only the documentation needs updating. The following variables are available `chocolateyPackageFolder`, `chocolateyPackageName`, **`chocolateyPackageVersion`** (duplicated in `packageFolder`, `packageName`, `packageVersion`)

**Comment by gep13** [comment]
For changes to the documentation, we are happy to accept Pull Requests to this repository:

https://github.com/chocolatey/choco-wiki

:+1: 

Thanks!

**Comment by mjiderhamn** [comment]
Alrighty, https://github.com/chocolatey/choco-wiki/pull/2

**Comment by gep13** [comment]
Thanks for helping out! :smile_cat:
