### ISSUE TITLE
Typo on Non-Admin installation link

### ISSUE THREAD

**Issue by raviriley** [chocolatey/choco#1923]
### What You Are Seeing?

Incorrect link to non-admin install. 
Links to
https://chocolatey.org/install#non-administrative-install

### What is Expected?

Should link to 
https://chocolatey.org/docs/installation#non-administrative-install

### How Did You Get This To Happen? (Steps to Reproduce)
`choco install` 

### Output
```
choco install ruby -y
Chocolatey v0.10.11
Chocolatey detected you are not running from an elevated command shell
 (cmd/powershell).

 You may experience errors - many functions/packages
 require admin rights. Only advanced users should run choco w/out an
 elevated shell. When you open the command shell, you should ensure
 that you do so with "Run as Administrator" selected. If you are
 attempting to use Chocolatey in a non-administrator setting, you
 must select a different location other than the default install
 location. See
https://chocolatey.org/install#non-administrative-install for details.
```

**Comment by suparnasnair** [comment]
Hi @raviriley, may I take this up. I am able to locate the file where this typo has occured.

**Comment by vexx32** [comment]
@suparnasnair see the reference note pointing to #1924 — looks like @widberg has already started working on it. 🙂

**Comment by suparnasnair** [comment]
Oh okay, thanks for the info! :-) Let me know in case I can help with it.

**Comment by Alekhya059** [comment]
I'm getting this warning even though I am running from an elevated command shell(powershell - "Run as administrator").. Can you please help me.. I'm having problem installing the virtual box(Error -"Unable to open certificates store: 5" , "Failed to construct install certificate") and I guess its because of this problem. Please advise

**Comment by raviriley** [comment]
@Alekhya059 this is probably not the right place to ask that, try opening an issue?

**Comment by vnwonah** [comment]
@ferventcoder can I take this?

**Comment by gep13** [comment]
This issue was actually addressed as part of this issue: https://github.com/chocolatey/choco/issues/2205

This is now ready to be closed out.
