### ISSUE TITLE
[Documentation] User docs about security

### ISSUE THREAD

**Issue by dtgm** [chocolatey/choco#193]
Maybe I missed it, but I didn't see anything in the wiki regarding how chocolatey works from a user's point of view.  

Including topics like the moderation process and types of packages e.g. [Trusted packages](https://github.com/chocolatey/chocolatey.org/issues/121)

I would write something for the wiki, but it still appears to be closed.  Anyone know if/when it will re-open for contributing?

**Comment by gep13** [comment]
Please see the "Edit me" note at the top of the wiki:

https://github.com/chocolatey/choco/wiki

:+1:

**Comment by dtgm** [comment]
Wow, not sure how I missed that link...  :flushed:

For future inepts: 
To contribute to the choco wiki at https://github.com/chocolatey/choco/wiki
Repo is https://github.com/chocolatey/choco-wiki

**Comment by gep13** [comment]
It has only recently been added, so no worries on not seeing it :-D

**Comment by ferventcoder** [comment]
Is this still an issue?

**Comment by TheCakeIsNaOH** [comment]
This exists here: https://docs.chocolatey.org/en-us/information/security
And here: https://docs.chocolatey.org/en-us/community-repository/moderation/

**Comment by gep13** [comment]
Agreed. I think we can close this.
