### ISSUE TITLE
How to reinstall choco or fix choco?

### ISSUE THREAD

**Issue by ztj1993** [chocolatey/choco#1936]
I lost the environment variable.

The software exists. How can I fix it?

**Comment by bcurran3** [comment]
If it's as simple as the environment variable, just add ChocolateyInstall=C:\ProgramData\chocolatey.

BUT I'm guessing you really need to add C:\ProgramData\chocolatey\bin back into your path.

With that said, should really be as easy as choco unpackself

> Commands
> 
>  * list - lists remote or local packages
>  * find - searches remote or local packages (alias for search)
>  * search - searches remote or local packages (alias for list)
>  * info - retrieves package information. Shorthand for choco search pkgname --exact --verbose
>  * install - installs packages from various sources
>  * pin - suppress upgrades for a package
>  * outdated - retrieves packages that are outdated. Similar to upgrade all --noop
>  * upgrade - upgrades packages from various sources
>  * uninstall - uninstalls a package
>  * pack - packages up a nuspec to a compiled nupkg
>  * push - pushes a compiled nupkg
>  * new - generates files necessary for a chocolatey package from a template
>  * sources - view and configure default sources (alias for source)
>  * source - view and configure default sources
>  * config - Retrieve and configure config file settings
>  * feature - view and configure choco features
>  * features - view and configure choco features (alias for feature)
>  * setapikey - retrieves, saves or deletes an apikey for a particular source (alias for apikey)
>  * apikey - retrieves, saves or deletes an apikey for a particular source
>  *** unpackself - have chocolatey set itself up**
>  * version - [DEPRECATED] will be removed in v1 - use `choco outdated` or `cup <pkg|all> -whatif` instead
>  * update - [DEPRECATED] RESERVED for future use (you are looking for upgrade, these are not the droids you are looking for)

**Comment by ztj1993** [comment]
OK, I hope I can fix myself through choco. I added environment variables manually.

---

I was thinking, you can install choco on the U disk, so that to a new computer, you can quickly mirror the environment.

---

Thank you!
