### ISSUE TITLE
Problem with installing virtualbox using chocolatey from elevated commandshell

### ISSUE THREAD

**Issue by Alekhya059** [chocolatey/choco#1938]
Firstly when I try to install virtualbox from powershell("Run as administator") using chocolatey by running this command "choco install virtualbox", I'm getting this unexpected warning : 

Chocolatey detected you are not running from an elevated command shell
 (cmd/powershell).

 You may experience errors - many functions/packages
 require admin rights. Only advanced users should run choco w/out an
 elevated shell. When you open the command shell, you should ensure
 that you do so with "Run as Administrator" selected. If you are
 attempting to use Chocolatey in a non-administrator setting, you
 must select a different location other than the default install
 location. See
 https://chocolatey.org/install#non-administrative-install for details.

 Do you want to continue?([Y]es/[N]o):

Later my installation of virtualbox fails with these errors.

Errors

VirtualBox-6.0.14-133895-Win.exe: error: Unable to open certificates store: 5
VirtualBox-6.0.14-133895-Win.exe: error: Failed to construct install certificate.

Can you please let me know if these both issues are connected and help me solve them. 

Please advise

**Comment by Alekhya059** [comment]
It seems I have this problem only when using windows powershell but not with command prompt

**Comment by collins73** [comment]
I am having the same issue: 
Failures
 - virtualbox (exited 1) - Error while running 'C:\ProgramData\chocolatey\lib\virtualbox\tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by pauby** [comment]
@collins73 that isn't the same issue. Please raise an issue with the package maintainer for package issues. Thanks.
