### ISSUE TITLE
Chocolatey's choco command does not accept "*" wildcard

### ISSUE THREAD

**Issue by StewAlexanderACC** [chocolatey/choco#1940]
When attempting to install packages it would be nice if we could use the ```*``` wildcard to download software.

Half the time the package exists but there is no way to know it without checking on your package index, because of the spelling choice of the package.

Otherwise, if you cannot do a wildcard, tab completion would be a wondrous added feature.

**Comment by StewAlexanderACC** [comment]
@maxsu  / @cori  / @torhovland / @bdukes  - Can anyone take a moment and at least respond to my request?

Doesn't seem like it is that outlandish a request, considering the sometimes funky way people name the packages they upload.

**Comment by bdukes** [comment]
There is support for tab completion, see [I can't get the PowerShell tab completion working.](https://github.com/chocolatey/choco/wiki/Troubleshooting#i-cant-get-the-powershell-tab-completion-working)

Also, see the [search](https://github.com/chocolatey/choco/wiki/CommandsList#listsearch-command-choco-list) command for a way to find the package you're looking for from the CLI.

Hope it helps!

**Comment by StewAlexanderACC** [comment]
@bdukes 
Hmm, I don't use powershell (I know), but the search command answers my request (more or less) thanks!
