### ISSUE TITLE
Chocolatey download URL is DOWN

### ISSUE THREAD

**Issue by tapvirvirk** [chocolatey/choco#1944]
Hi,

I'm trying to install the chocolatey package and getting below url is not working

https://packages.chocolatey.org/chocolatey.0.10.15.nupkg

It is throwing DNS Error
You've requested a page on a website (packages.chocolatey.org) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (packages.chocolatey.org).

**Comment by gep13** [comment]
@tapvirvirk an issue was created for this here: https://github.com/chocolatey/chocolatey.org/issues/721

This was an issue with AWS.
