### ISSUE TITLE
Allow blocking upgrades for specific programs.

### ISSUE THREAD

**Issue by dustojnikhummer** [chocolatey/choco#1948]
My best example is Amazon Kindle. With version 1.23, you can remove DRM from your purchased books and use Calibre etc. While I can install that version, I often forget about it when upgrading all of my packages. I'm aware I can say NO when installing an update.

Any way to exclude a package from upgrading?

**Comment by vexx32** [comment]
I think you're looking for `pin`: https://github.com/chocolatey/choco/wiki/CommandsPin 🙂 

Example from the article:
```
choco pin add -n=git --version 1.2.3
```

**Comment by dustojnikhummer** [comment]
Oh, I totally missed that. Thanks!

**Comment by AdmiringWorm** [comment]
while `choco pin` is most likely the one you really want, you also have the option to use the `--except` argument when calling `choco upgrade`.

ie:

```
choco upgrade all --except=calibre
```

**Comment by ferventcoder** [comment]
Thanks folks!
