### ISSUE TITLE
Mismatch ChocolateyPackageName and id field in nuspec

### ISSUE THREAD

**Issue by rvdginste** [chocolatey/choco#1959]
### What You Are Seeing?

In previous versions, during installation the environment variable ChocolateyPackageName contained the exact contents of the "id" field in the nuspec file. In the current version 0.10.15, it seems to contain a lower-case version of what is provided in the "id" field.

### What is Expected?

I expect the variable ChocolateyPackageName to contain the id field, as documented on https://chocolatey.org/docs/helpers-reference

### How Did You Get This To Happen? (Steps to Reproduce)

Installation of a package with an install script that interprets the package id.

**Comment by rvdginste** [comment]
Sorry, mis-diagnosed.

**Comment by ferventcoder** [comment]
No worries, I'll add a label.
