### ISSUE TITLE
When there is an error getting a package, do not report the package files upgrade aspect has completed

### ISSUE THREAD

**Issue by Xalaxis** [chocolatey/choco#1962]
Hi all, it looks like the Chocolatey servers are (partially) down right now.  That's not the point of this enhancement request though.  Currently if the servers are (partially) down, you get the message shown below:
![image](https://user-images.githubusercontent.com/12937964/69916915-9f450680-1458-11ea-9c6a-5cde9a853f75.png)

It doesn't really seem to make sense to report that an error has occurred and a package upgrade was not successful, before then saying the upgrade is complete and trying the same thing again.  Perhaps the whole process could fall over if the first network access fails?

**Comment by ferventcoder** [comment]
This is definitely a weird place to report that the package files upgrade is completed (not the software installation or any of the scripts running) - note this is not a message saying the upgrade is complete - "package files upgraded" is not "upgrade is complete". Still we shouldn't have that message show if there is an error.
