### ISSUE TITLE
Choco outdated strange behaviour

### ISSUE THREAD

**Issue by srzelic** [chocolatey/choco#1963]
# What You Are Seeing?

Choco outdated takes long to execute and there is an error retrieving packages from choco. We got this error since this AM and it happens across all our clients that are on different locations.

### How Did You Get This To Happen? (Steps to Reproduce)
Via running CHOCO OUTDATED

### Output Log

C:\Users\CCC>choco outdated
Chocolatey v0.10.15
Outdated Packages
 Output is package name | current version | available version | pinned?

Error retrieving packages from source 'https://chocolatey.org/api/v2/':
 Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.
chocolatey-core.extension|1.3.5|1.3.5|false
GoogleChrome|78.0.3904.97|78.0.3904.108|false

Chocolatey has determined 1 package(s) are outdated.
 1 package(s) had warnings.
Warnings:
 - chocolatey-core.extension

<details>
<summary>Full Log Output</summary>

<p>
NO log generated for this command. We deleted log files before execution but nothing generated.
![ScreenConnect WindowsClient_a4ItQROYYw](https://user-images.githubusercontent.com/32106850/69917044-fc1fcd00-1416-11ea-8fc0-988f0e44d2b2.png)
![ScreenConnect WindowsClient_a4ItQROYYw](https://user-images.githubusercontent.com/32106850/69917049-0641cb80-1417-11ea-9bb1-dd4c5ad785ee.png)
![ScreenConnect WindowsClient_ICD5vdu2T2](https://user-images.githubusercontent.com/32106850/69917051-06da6200-1417-11ea-8373-34a1ce5d8c38.png)

</p>

</details>

**Comment by gep13** [comment]
@srzelic I suspect that this is related to some ongoing issues which are being tracked/updated here:

status.chocolatey.org

Sounds like you might be using Chocolatey in an Organisational context, and if you are, we recommend that you follow the suggestions here:

https://chocolatey.org/docs/how-to-setup-offline-installation

As this will isolate you from any upstream problems with the main chocolatey site.

**Comment by srzelic** [comment]
@gep13  Thank you for this info. Didn't know this status URL exist. We would like to avoid setup offline installations as we have many small clients. Thank anyway.

**Comment by ferventcoder** [comment]
@srzelic To follow up a bit more, you should at least implement a caching strategy for your clients, as this is an issue that could be avoided altogether if you had something in place.
