### ISSUE TITLE
[BUG] Chocolatey some repository Fails and I don't know WHY ?

### ISSUE THREAD

**Issue by Olvidados** [chocolatey/choco#1964]
Hi,

Here is the video of the bug I have:
[https://youtu.be/4ykmHKQXS8E](url)

I have a bug with your app since like 6-7 days and before the app working but now, this is cancer... Can you help me ?

Snapshot speccy config:
[http://speccy.piriform.com/results/SWUndksdqeKMHyAkpzbS0Gi](url)

thanks you
william

**Comment by gep13** [comment]
Please refer to status.chocolatey.org. There is currently an open incident that explains the problem that you are seeing.

**Comment by JeroMe9496** [comment]
If I refer to status.chocolatey.org, all systems are operational. But I have the same problem since 2 days.

**Comment by blenderman-de** [comment]
Same issue here on multiple computers  (Win10 Pro and Win7 Pro 64) on powershell and cmd.

**Comment by arvinatwork** [comment]
Same here, can't proceed

**Comment by JeroMe9496** [comment]
it works again. But for how long...

**Comment by blenderman-de** [comment]
wow that was quick solved... Thanks!

**Comment by gep13** [comment]
@JeroMe9496 the status page currently isn't automatically updated, so it isn't realtime.  There are ongoing issues with the Chocolatey Community Repository that we are working to resolve, so please bear with us.

For now, I am going to close this issue, as any issues with the site should be addressed on the chocolatey/chocolatey.org repository.
