### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by richardgavel** [chocolatey/choco#1968]
I am having an issue where when I try to install various root packages, it has trouble installing dependent packages. However, I can directly install the dependent package without issues (and then the root package). This is occurring with different root packages and different dependent packages.

choco install --confirm dotnetcore-sdk --version 2.2.300 --no-progress

2019-12-08 21:57:40,041 5292 [ERROR] - The install of dotnetcore-sdk was NOT successful.
2019-12-08 21:57:40,043 5292 [ERROR] - dotnetcore-sdk not installed. An error occurred during installation:
 Unable to resolve dependency 'chocolatey-core.extension (= 1.3.3)'.

**Comment by gep13** [comment]
@richardgavel the issue that you are seeing is being tracked here:

https://github.com/chocolatey/chocolatey.org/issues/765

You can follow along there and also on the [status page](https://status.chocolatey.org/) for more information.

This this is being tracked elsewhere, I am going to close out this issue.
