### ISSUE TITLE
Pycharm installed using choco but its not showing in windows 10

### ISSUE THREAD

**Issue by csetarun2** [chocolatey/choco#1969]
Hi Team, 

I have installed pycharm-community-edition using choco, its showing pycharm-installed successfully, but where I search pycharm program its not present in my windows 10.

`
C:\Users\Administrator>choco install pycharm-community -y
Chocolatey v0.10.15
Installing the following packages:
pycharm-community
By installing you accept licenses for the packages.
pycharm-community v2019.3 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

Chocolatey installed 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Warnings:
 - pycharm-community - pycharm-community v2019.3 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
`

![image](https://user-images.githubusercontent.com/21236859/70411794-2c034c00-1a79-11ea-8710-57df6b510d48.png)

STOP RIGHT HERE - DO NOT CREATE A TICKET FOR PACKAGES ON THIS REPOSITORY

This is the repository for choco.exe, the command line interface for Chocolatey, and issues/feature suggestions should be limited to only choco. For a package failure, typically you would be reporting an issue with a package on the community package repository, which is not what this repository represents. In fact, the community repository and all of its packages represents about 5% of the packages in existence and less than half of the usage of choco itself. 

  In other words Chocolatey != Chocolatey.org Packages.

For all things packages, you have two routes:

1. If you are having issue with a package or you want to see an enhancement, please see https://chocolatey.org/docs/package-triage-process (Package Triage Process / Becoming a maintainer of existing packages).
2. If you are looking for packages to be added to the community package repository (aka https://chocolatey.org/packages), please see https://chocolatey.org/docs/package-triage-process#package-request-package-missing (Package Requests).

NOTE: Keep in mind we have an etiquette regarding communication that we expect folks to observe when they are looking for support in the Chocolatey community. https://github.com/chocolatey/choco/blob/master/README.md#etiquette-regarding-communication

**Comment by gep13** [comment]
@csetarun2 I have just done the same test, and from what I can see, this works as expected:

![image](https://user-images.githubusercontent.com/1271146/70416147-42e47700-1a56-11ea-8a53-8750bef53aba.png)

Having said that, if it isn't working for you, this is a packaging issue and unlikely an issue with Chocolatey directly.  As mentioned in the issue description which you would have read before posting the issue:

> STOP RIGHT HERE - DO NOT CREATE A TICKET FOR PACKAGES ON THIS REPOSITORY

As such, I am going to close this issue and suggest that you follow up with the package maintainer if you continue to see issues with this package.
