### ISSUE TITLE
Tab complete in choco Powershell window not working

### ISSUE THREAD

**Issue by mariobrostech** [chocolatey/choco#1971]
### What You Are Seeing?

choco commands in PowerShell windows don't autocomplete.

### What is Expected?

choco commands in PowerShell windows should autocomplete.

### How Did You Get This To Happen? (Steps to Reproduce)

I installed Chocolatey in a PowerShell administrator prompt. I noted the error saying:
`Not setting tab completion: Profile file does not exist at 'C:\Users\MyName\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1`

I quickly found out that the error was important to autocomplete not working, and tried looking for a solution on your FAQ. I followed the instructions [here](https://chocolatey.org/docs/troubleshooting#why-does-choco-intab-not-work-for-me), but nothing worked. Below, I have attached a log of everything logged in the PowerShell window at the time of the incident, showing that I went through all of the steps on the FAQ.

Once I did so, I realized that no `.ps1` file was created in the directory outputted. Is there any way to generate this file?

### Output Log
<p>

~~~sh
PS C:\Windows\system32> . $profile
The term 'C:\Users\MyName\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:3
+ . $profile
+   ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\MyName\Doc...ell_profile.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Windows\system32> Set-ExecutionPolicy Bypass -Scope Process                                                       
Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
PS C:\Windows\system32> type $profile
type : Cannot find path 'C:\Users\MyName\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1' because it does not exist.
At line:1 char:1
+ type $profile
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\MyName\Doc...ell_profile.ps1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

PS C:\Windows\system32> Write-Host $profile                                                                             C:\Users\MyName\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1

PS C:\Windows\system32> . $profile
The term 'C:\Users\MyName\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:3
+ . $profile
+   ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\MyName\Doc...ell_profile.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Windows\system32>                                                                                                 
~~~

</p>

</details>

**Comment by vexx32** [comment]
The documentation indicates you're expected to create the file using a text editor (Notepad works fine, just make sure you save the file with a `ps1` extension and not as a text file).

The quick and dirty way to do it is to pull the code listed on the docs page you referenced and tell PowerShell to create the file for you:

```powershell
@'
# Chocolatey profile
$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
if (Test-Path($ChocolateyProfile)) {
  Import-Module "$ChocolateyProfile"
}
'@ | Add-Content -Path $profile
```

**Comment by mariobrostech** [comment]
> The documentation indicates you're expected to create the file using a text editor (Notepad works fine, just make sure you save the file with a ps1 extension and not as a text file).
> The quick and dirty way to do it is to pull the code listed on the docs page you referenced and tell PowerShell to create the file for you:
> @'
> # Chocolatey profile
> $ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
> if (Test-Path($ChocolateyProfile)) {
>   Import-Module "$ChocolateyProfile"
> }
> '@ | Add-Content -Path $profile
> Then you can use . $profile to reload the profile, or just reload the powershell session to have it load it in. 🙂

Oh, ok, I didn't pick up on the fact that we were supposed to manually create the `.ps1` file because of the wording used in the documentation. That makes a lot more sense. I'll test this when I get back in front of my PC tomorrow morning, but I'm expecting your solution to work.

Thank you again for your help!

**Comment by mariobrostech** [comment]
@vexx32 Your solution worked. Thank you very much!

To recap, for anyone facing this issue afterwards:
1) If you have issues with PowerShell autocompletion using `choco`, make sure to follow the documentation linked [here](https://chocolatey.org/docs/troubleshooting#why-does-choco-intab-not-work-for-me).
2) When you get to the part of the documentation containing the code snippet, create the `.ps1` file in the `WindowsPowerShell` directory yourself. PowerShell will not do this for you, and the documentation doesn't make this clear, in my opinion.
3) After you have created the file manually and pasted the code provided in the documentation snippet, save it, and run `. $profile` in PowerShell. If you've done this correctly, you won't see any error messages.

**Comment by vexx32** [comment]
Might be worth changing that doc a bit to make it more clear. I might submit a PR for it after Christmas/new year, or you're welcome to as well. 🙂

**Comment by mariobrostech** [comment]
Ok, great! I'll definitely look into it.

**Comment by ferventcoder** [comment]
@vexx32 or @mariobrostech I reopened this for now to see if there is documentation to submit.

**Comment by mariobrostech** [comment]
> Might be worth changing that doc a bit to make it more clear. I might submit a PR for it after Christmas/new year, or you're welcome to as well. 🙂

@vexx32 Hey, I know it's been quite some time since there's been any activity on this issue, but I just wanted to check in. Did you ever getting around to looking into this more or submitting feedback to improve the documentation?

**Comment by vexx32** [comment]
I don't think I did, but thanks for the reminder! I have some downtime so I'll probably just go make those additions now.

**Comment by mariobrostech** [comment]
Fantastic, let me know how it goes!

**Comment by mariobrostech** [comment]
It looks like this was fixed in the issue you referenced, so I'm closing this for now. If anyone else feels that the current documentation needs more clarification, please leave a comment here, and I'll re-open it.
