### ISSUE TITLE
Can the newer version be downloaded first before uninstalling older during upgrading?

### ISSUE THREAD

**Issue by bpmf** [chocolatey/choco#1972]
Tried to upgrade a package using cup command, it first deleted the one version then started downloading. Since the network is very slow then, and I cancelled via Ctrl-C. However, due to the old version was uninstalled in half, it cannot be used any more!

Is there a switch or configuration which can make choco download first and then start uninstall when the package is downloaded and  fully ready, or some feature that can recover old version when upgrading failed, which can make upgrading more robust?

**Comment by ferventcoder** [comment]
Guessing you might have meant not the package, but maybe the software installation media that might have needed to be downloaded? 

The package does download first before upgrading itself on top of the other.
