### ISSUE TITLE
Install/Upgrade/Remove multiple packages in one command 

### ISSUE THREAD

**Issue by nutterthanos** [chocolatey/choco#1975]
I was thinking of implementing it like how apt/yum does it eg apt install/remove/upgrade apt apt-utils nano etc or yum install yum yum-utils nano etc.

**Comment by nutterthanos** [comment]
sorry put this in wrong repo

**Comment by ferventcoder** [comment]
As you determined, it already does this.

**Comment by nutterthanos** [comment]
i closed it because i found out this already has it.
