### ISSUE TITLE
How to reinstall to a different user?

### ISSUE THREAD

**Issue by suntong** [chocolatey/choco#1976]
How to forget the previous location and have `choco install` to install to a different user?

Following up with #1830, which concludes that having `choco install` to install programs to under `C:\Program Files\` will be less likely, but to somebody's personal private folder instead, 

So I uninstall fiddler from my personal private folder:

```
PS C:\Windows\system32> choco uninstall fiddler -y
Chocolatey v0.10.15
Uninstalling the following packages:
fiddler

fiddler v5.0.20194.41348
 Running auto uninstaller...
 Skipping auto uninstaller - 'Progress Telerik Fiddler' appears to have been uninstalled already by other means.
 fiddler has been successfully uninstalled.

Chocolatey uninstalled 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
PS C:\Windows\system32>
PS C:\Windows\system32> choco uninstall fiddler -y
Chocolatey v0.10.15
Uninstalling the following packages:
fiddler
fiddler is not installed. Cannot uninstall a non-existent package.

Chocolatey uninstalled 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - fiddler - fiddler is not installed. Cannot uninstall a non-existent package.

If a package uninstall is failing and/or you've already uninstalled the
 software outside of Chocolatey, you can attempt to run the command
 with `-n` to skip running a chocolateyUninstall script, additionally
 adding `--skip-autouninstaller` to skip an attempt to automatically
 remove system-installed software. This will only remove the packaging
 files and not things like software installed to Programs and Features.

If a package is failing because it is a dependency of another package
 or packages, then you may first need to consider if it needs removed
 as it is typically installed as a dependency for a reason. If you
 decide that you still want to remove it, head into
 `$env:ChocolateyInstall\lib` and find the package folder you want
 removed. Then delete the folder for the package. This option should
 only be used as a last resort.
```

Then I tried redo installation from another account, but the problem is it still goes to *my* personal private folder again, instead of the new account that I'm using. (the install result is exactly the same as posted in #1830).

How can I make `choco install` forget its previous installation location and to install to current user's place instead? 

Thanks for your help.

**Comment by ferventcoder** [comment]
So to reiterate what I wrote on #1830: 

Depending on the package and the underlying software (most of the time software installers), that's where software gets installed. If Fiddler is going into AppData, then I would investigate Fiddler installer itself. Once you've determined how to get it to work to your liking, you will know how to adjust install arguments given to the Chocolatey package itself. 

As far as where it might be installing to the wrong location, uninstall the software itself. Not just the Chocolatey package. Go into Programs and Features and remove Fiddler from there. 

> `Skipping auto uninstaller - 'Progress Telerik Fiddler' appears to have been uninstalled already by other means.`

This means the software wasn't uninstalled by automatic uninstaller, and it doesn't appear from the log that their was a chocolateyUninstall.ps1 script to uninstall the software itself. That means when you run your installation the next time, it's likely going to keep the software where it already was, thus why you are seeing that message you posted in the image at https://github.com/chocolatey/choco/issues/1830#issuecomment-569982886.

Also consider that message about where things were installed is best guess and you should verify its accuracy by looking on the file system. If two folks are using the system at the same time, things can get a bit off on that aspect.

**Comment by ferventcoder** [comment]
Also from https://gist.github.com/choco-bot/30c405791a4e1cfca1c88d80c4f3b442 (which I got to by going to https://chocolatey.org/packages/fiddler#testingResults), you'll note that it's installing to [AppData](https://gist.github.com/choco-bot/30c405791a4e1cfca1c88d80c4f3b442#file-1-registrysnapshot-xml-L9). I'm not sure it always performed those installations that way, so it's best to go back to Progress Telerik (the software vendor) and request it go to Program Files by default or how you can override that setting. HTH

**Comment by ferventcoder** [comment]
Also note, that there is some really helpful information at https://chocolatey.org/packages/fiddler#description. I'm going to close this as it tells you there EXACTLY how to get the installation to go to Program Files.

**Comment by suntong** [comment]
Thanks a lot for your help -- it was overwhelming to me, now after your explanation, everything makes perfect sense. THX!
