### ISSUE TITLE
uninstall -  package parameters aliases are not consistent with other commands like install

### ISSUE THREAD

**Issue by hs-hub-world** [chocolatey/choco#1981]
Hello,
 using choco version 0.10.14. trying to integrate choc with ansible with "--package-params".  the install part works great. But when I execute the uninstall the same param "--package-params" does not work with the uninstall. But when I use "choco uninstall **--params**" that works similar to --package-params.  
So I was wondering if this is a bug in choco.exe -? Otherwise, the ansible module would need to be updated which would use --params during uninstall and then to use --package-params during install. 

For consistency, I would imagine choco.exe  install and uninstall should be similar when using "Get-PackageParameters" ($OptionalParams = Get-PackageParameters) this should return identical results no matter if it's installed or uninstall.

Thank you

**Comment by ferventcoder** [comment]
This is likely a bug - I've marked this up for grabs if you want to give it a shot.

**Comment by vexx32** [comment]
I don't see this `--package-params` alias anywhere in this codebase after a few searches.

I'm inclined to think this might be a misunderstanding that arises from how the [Ansible modules](/chocolatey/chocolatey-ansible) handle passing this information.

There appears to be a bug in the Ansible module where it references `--package-parameters` when you pass `package_params` in the installation configuration, but it **mistakenly** references `--package-params` in the _un_installation configuration when passing the same option in from Ansible.

https://github.com/chocolatey/chocolatey-ansible/blob/9972f6824131b4f8e3163b6014de8ba6979f03bd/chocolatey/plugins/modules/win_chocolatey.ps1#L156-L158

vs

https://github.com/chocolatey/chocolatey-ansible/blob/9972f6824131b4f8e3163b6014de8ba6979f03bd/chocolatey/plugins/modules/win_chocolatey.ps1#L634-L636
