### ISSUE TITLE
Environment: Add ChocolateyExitOnRebootDetected feature setting to environment variables for packages to inspect

### ISSUE THREAD

**Issue by mkevenaar** [chocolatey/choco#1983]
Inside a package I want to verify if the user uses the exit-on-reboot-detected flag / setting. Currently there is no env variable for it. Is there a way to detect if a user has enabled that feature?

**Comment by ferventcoder** [comment]
This is completed for 0.10.16.

**Comment by ferventcoder** [comment]
Thank you @mkevenaar!!
