### ISSUE TITLE
ask some questions about use, thanks!

### ISSUE THREAD

**Issue by ztj1993** [chocolatey/choco#1988]
> Accelerated Download

Can I use download tools such as aria2c to resume and speed up the download?

Download speed is slow in China.

> Software cache problems

Whether the cache directory setting can be placed in the environment variable?

If the software has been downloaded, will it be downloaded from the new? 

After I reset my computer, I want to use the previous cache.

**Comment by ferventcoder** [comment]
@ztj1993 questions go to chat functions or google group. When you went to create an issue, it should have pointed you that way. https://chocolatey.org/support#foss. HTH
