### ISSUE TITLE
Feature Req - choco upgrade all --noop as json

### ISSUE THREAD

**Issue by fenchu** [chocolatey/choco#1991]
I do unattended browser tests, and the only way I've found installing all the browsers without interaction is to use choco.exe, but currently there is no easy version check of what is installed.

I install webdrivers directly from github based on the versioning returned by the below command, but it currently requires regex to find the version number.

Would be nice if output could be json
```
choco.exe upgrade all --noop
Chocolatey v0.10.15
_ Chocolatey:ChocolateyUpgradeCommand - Noop Mode _
chocolatey v0.10.15 is the latest version available based on your source(s).

You have chocolatey-core.extension v1.3.3 installed. Version 1.3.5.1 is available based on your source(s).
Firefox v72.0.2 is the latest version available based on your source(s).
GoogleChrome v79.0.3945.130 is the latest version available based on your source(s).
microsoft-edge-insider v79.0.309.65 is the latest version available based on your source(s).
Opera v66.0.3515.44 is the latest version available based on your source(s).
```

**Comment by gep13** [comment]
@fenchu have you tried using:

`choco outdated -r`

You should be able to split the output from that based on the | character, and have all the information that you need.

**Comment by ferventcoder** [comment]
@fenchu as @gep13 mentioned, `choco outdated -r` will be what you are looking for to do programmatic access and parsing. As such, I'm going to close this out.
