### ISSUE TITLE
Ask Question: Creating a Chocolatey Package

### ISSUE THREAD

**Issue by xmha97** [chocolatey/choco#1992]
I will create a chocolatey package from a single EXE file.
All packages downloading a zip file (not an EXE file)
![Chocolatey](https://cdn.discordapp.com/attachments/447475999681282078/672553208375148564/unknown.png "Chocolatey")
My executable file downloadable from below link:
https://github.com/xmha97/jcal/releases/download/1.0.0.0/jcal.exe
I created a Persian calendar:
![Chocolatey](https://cdn.discordapp.com/attachments/447475999681282078/672553395852410891/73131008-acc1db80-4018-11ea-80ff-f9835cfdf4c9.png "Chocolatey")

**Comment by ferventcoder** [comment]
@xmha97 I'm not sure how this ended up here, but this is not the proper question for this. I'm not quite sure what you are asking.

What are you asking?

**Comment by xmha97** [comment]
I created a [tiny app](https://github.com/xmha97/jcal/releases/download/1.0.0.0/jcal.exe) and want to submit it on Chocolatey.
