### ISSUE TITLE
uninstall - receive access denied to choco.exe path

### ISSUE THREAD

**Issue by cslycord** [chocolatey/choco#1993]
This is happening both run in elevated powershell and cmd prompts.

Steps to reproduce:
1) choco install mkvtoolnix
2) choco uninstall mkvtoolnix -x

Note: I get the same error on uninstall if I run choco via its path 'C:\ProgramData\chocolatey\bin\choco.exe'

mkvtoolnix v43.0.0
 Running auto uninstaller...
 Auto uninstaller has successfully uninstalled mkvtoolnix or detected previous uninstall.
 mkvtoolnix has been successfully uninstalled.

chocolatey v0.10.15
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 Access to the path 'C:\ProgramData\chocolatey\bin\choco.exe' is denied.
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 Access to the path 'C:\ProgramData\chocolatey\bin\choco.exe' is denied.
Maximum tries of 3 reached. Throwing error.
mkvtoolnix not uninstalled. An error occurred during uninstall:
 Access to the path 'C:\ProgramData\chocolatey\bin\choco.exe' is denied.

**Comment by cslycord** [comment]
Strange. When I instead ran "C:\ProgramData\chocolatey\choco.exe uninstall mkvtoolnix -x" everything uninstalled perfectly, but now I can't run "choco" directly in the shell because C:\ProgramData\chocolatey wasn't added to PATH when choco initially got installed.

**Comment by ferventcoder** [comment]
@cslycord not sure what is causing this - but we'll need the full log to do any debugging here. I'm guessing there is something else that is going on where that is coming up - trying to rename the file for some reason but not having permissions to do so as another process has the file locked.

**Comment by ferventcoder** [comment]
When you created the issue following the choose - it should have provided a template that shows how to set up the log information.

**Comment by gep13** [comment]
Given the lack of response here, I am going to go ahead and close out this issue.
