### ISSUE TITLE
Change from minimum install of .NET 4.0 to .NET 4.5+

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1994]
We moved chocolatey.org to a minimum of TLS 1.2. On the .NET side, that means at least 4.5.x is needed at a minimum. Currently Chocolatey will install .NET 4.0 if it detects you don't have a minimum version installed. Move that to .NET 4.5 at the very least

**Comment by gep13** [comment]
I am going to go ahead and close this issue, as this will be superseded by this issue: https://github.com/chocolatey/choco/pull/2739
