### ISSUE TITLE
Get-WebFile does not handle authorization headers

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/choco#1998]
Passing authorization headers through `Install-ChocolateyPackage` does not attach them to `Get-WebFile` downstream properly.

**Comment by eocern** [comment]
Hi there busy bees :-) I am hitting that issue now. Any chance you can check on the failed PR build due to a package dependency issue ?

**Comment by gep13** [comment]
@eocern this has been merged in, and will go out with the next release.

**Comment by gep13** [comment]
@steviecoaster @eocern I have just been back to fully test this, and it looks like this was working correctly within 0.10.15, before the change was made in 0.11.0 to attempt to add the Authorization header to the HttpWebRequest.

As you will see in this screenshot:

![2021-09-21_13-51-33](https://user-images.githubusercontent.com/1271146/134173858-46e99f4e-158c-4762-9e17-3a57f70c119b.png)

The four headers, `Accept`, `Cookie`, `Referer`, and `Authorization` all make their way into the request that Chocolatey emits when fetching the file.

The change that was introduced in 0.11.0 actually introduces a bug, which I am planning on backing out, and shipping a new v0.11.2 of Chocolatey.
