### ISSUE TITLE
Support switching shims between multiple installed versions

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#2]
Say you have two ruby portables installed. You want to switch back and forth on the shims. 

This is similar to [regenerating shims](#3)

**Comment by ferventcoder** [comment]
This is similar to the regenerating shims.

**Comment by TheCakeIsNaOH** [comment]
As side by side installations have been deprecated, this feature request is no longer relevant: 
https://github.com/chocolatey/choco/issues/2787
