### ISSUE TITLE
Set up TC codebetter build

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#20]

**Comment by gep13** [comment]
Can you give me access to TC?  Happy to take a look at this.

**Comment by ferventcoder** [comment]
That would be Hadi or Maarten that could give you access.

On Sunday, January 18, 2015, Gary Ewan Park <notifications@github.com>
wrote:

> Can you give me access to TC? Happy to take a look at this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/20#issuecomment-70406124>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by gep13** [comment]
@hhariri or @maartenba can you hook me up with access to the Chocolatey Project on the TeamCity Codebetter instance?  My username is the same as it is for GitHub.  Thanks!

**Comment by maartenba** [comment]
@gep13 made you a project admin for Chocolatey.

**Comment by gep13** [comment]
@maartenba nice one, thank you very much! :smile_cat:

**Comment by ferventcoder** [comment]
Thank you @maartenba !

**Comment by ferventcoder** [comment]
If you can look at http://teamcity.codebetter.com/project.html?projectId=ChuckNorris&tab=projectOverview (roundhouse), it will give you an idea of how I want it. :)

**Comment by gep13** [comment]
Have started to implement this.  Just dropped you an email with some questions.  Will follow up based on your responses.

**Comment by ferventcoder** [comment]
Not sure if I set it completely up correctly. Still waiting to see it update the status on a PR I synchronized.

**Comment by gep13** [comment]
Yeah, still doesn't seem to be working :-(
What permissions did you give to the token that you assigned?
Can I get a screenshot?  I will put it past Maarten to see if it has everything that is required.
Gary

Date: Mon, 19 Jan 2015 19:06:28 -0800

**Comment by maartenba** [comment]
I did notice some AppVeyor status info. Not sure if GitHub allows overwriting it?

**Comment by gep13** [comment]
@maartenba I was going by this:

https://github.com/blog/1935-see-results-from-all-pull-request-status-checks

Could it be that there is something in either the AppVeyor or TeamCity side of things needs to change so that they are live in harmony?  Or am I missing the intent of the multiple build status API?

**Comment by ferventcoder** [comment]
So appveyor supports and uses the multiple build status, so it wouldn't overwrite anything. Take a look at https://github.com/puppetlabs/cfacter/pull/224 for an example of the multiple status.

![image](https://cloud.githubusercontent.com/assets/63502/5817066/42042a5a-a06d-11e4-9170-8cca0b8b5e61.png)

**Comment by ferventcoder** [comment]
### Github Auth Token
I put in the same permissions that were requested, however I noticed that when you select `repo` it removes `repo_status` and `public_repo`. 
![image](https://cloud.githubusercontent.com/assets/63502/5817079/77b77558-a06d-11e4-963a-03b581623cc0.png)

I removed `repo` and specifically selected `repo_status` and `public_repo` and it is working. I should note that the account that is set up for this is https://github.com/choco-bot which has read access to the repository.

![image](https://cloud.githubusercontent.com/assets/63502/5817146/4a9c28ba-a06e-11e4-9889-9551cda3feac.png)


### Team City Settings
Since the last time I checked, I noticed the url has changed (to remove`api/v3`):

![image](https://cloud.githubusercontent.com/assets/63502/5817106/c6a17e8e-a06d-11e4-8a25-709a2b388cbf.png)

**Comment by gep13** [comment]
@ferventcoder I didn't change the URL, but I did change the Context to be:

```continuousintegration/teamcity```

But I see that this has changed to teamcity.  Was that by you?

**Comment by maartenba** [comment]
I changes the URL and context to see if it helped.

**Comment by ferventcoder** [comment]
sweet! I will push up some changes and see if it picks it up.

**Comment by ferventcoder** [comment]
Pushed, nothing yet https://github.com/chocolatey/choco/pull/30#issuecomment-70512813

**Comment by ferventcoder** [comment]
But already picked up as pending by TC.

**Comment by maartenba** [comment]
Seeing a 404 in the server log, which according to GitHub means that auth failed. Just as a test, could you try with your full credentials configured?

**Comment by ferventcoder** [comment]
Weird part is appveyor is not reporting status now either. 
![image](https://cloud.githubusercontent.com/assets/63502/5817435/79f543e6-a071-11e4-9896-456643b35a4c.png)

**Comment by ferventcoder** [comment]
@maartenba keys updated. That user is set to full access to the token. This is how it allows items (I removed `repo` and `user`):
![image](https://cloud.githubusercontent.com/assets/63502/5817479/e4628a9a-a071-11e4-9dc6-988939aa186d.png)

**Comment by ferventcoder** [comment]
What i think you need is a webhook created. 
![image](https://cloud.githubusercontent.com/assets/63502/5817498/13df64f0-a072-11e4-8adb-6ba8cfa2a05e.png)

**Comment by maartenba** [comment]
Nope, TeamCity should be able to do it without the webhook. On the TC side, could you try your credentials instead of a token? (just for testing)

**Comment by ferventcoder** [comment]
Changed and pushed.

**Comment by ferventcoder** [comment]
It doesn't know about it yet. Have you thought about adding the push from github webhooks to kick off builds?

**Comment by gep13** [comment]
In a separate conversation I asked @maartenba if this;

http://tcplugins.sourceforge.net/info/tcWebHooks 

Could be added to the CodeBetter TeamCity instance.  This was to allow integration into Gitter Chat, but sounds like it could be used for other things as well.

**Comment by ferventcoder** [comment]
Okay, so it has noticed the pending changes, but still no status update.

**Comment by gep13** [comment]
> Okay, so it has noticed the pending changes, but still no status update.

Strangely again though, the AppVeyor status is working again.

**Comment by ferventcoder** [comment]
![image](https://cloud.githubusercontent.com/assets/63502/5817644/97f4f7d6-a073-11e4-9213-bb39d7d4c22e.png)
It works, it should probably update the status when it goes PENDING, not when it kicks of the build.

**Comment by ferventcoder** [comment]
So now that we've determined it is a permissions issue, I think we need to have @maartenba tell us what those permissions should be. ;)

**Comment by gep13** [comment]
Woot! :smile_cat: 

For the sake of consistency, otherwise it will bug the crap out of me, can we make the context `continuous-integation/teamcity` ?

**Comment by ferventcoder** [comment]
Done. Switched to the choco-bot user. I'll do another push and see if that works.

**Comment by maartenba** [comment]
Perhaps @jonnyzzz knows which permissions should be given to the token?

**Comment by ferventcoder** [comment]
@maartenba @jonnyzzz Would you agree that something can sit in pending status for awhile? TravisCI and AppVeyor are both subject to this - so they push a status update of pending until they are ready to kick off.

**Comment by ferventcoder** [comment]
When I switched over to the `choco-bot` user (not back to the auth token yet) that has read access to the repository (and has read status on commits), there was no status update on that PR.

**Comment by ferventcoder** [comment]
I think there is a missing permission here somewhere - we'll need it locked down so we are happy to try out a few things with you guys. Now that we've determined it is a permissions issue, can we start determining what it is that is necessary? Perhaps there is something in the plugin that is attempting to requesting too much permission?

**Comment by ferventcoder** [comment]
I'm guessing the code for this is at https://github.com/JetBrains/commit-status-publisher but I haven't looked too deeply into it.

**Comment by maartenba** [comment]
https://github.com/jonnyzzz/TeamCity.GitHub

**Comment by ferventcoder** [comment]
Sweet, I created https://github.com/jonnyzzz/TeamCity.GitHub/issues/73

**Comment by ferventcoder** [comment]
As a reference, this is what AppVeyor asks for:

![image](https://cloud.githubusercontent.com/assets/63502/5818179/d474f990-a078-11e4-922c-2a02153d4d10.png)

**Comment by ferventcoder** [comment]
Actually this may just be an issue with that user. I'm going to set up an access token under my account.

**Comment by ferventcoder** [comment]
I put this comment on https://github.com/jonnyzzz/TeamCity.GitHub/issues/73#issuecomment-70657149, but I thought I would share here as well:

>It comes down to permissions, but not permissions you can change. GitHub doesn't have the ability to give a github user permission to write status updates but nothing else. You can choose whether to document that the user is going to need write access to the repo for a user account / token to work.

Once you switch over to a user with write access (and in this case add an authorization token), it works appropriately:

![image](https://cloud.githubusercontent.com/assets/63502/5818466/73a5063e-a07b-11e4-9b55-6d970bd10141.png)

**Comment by ferventcoder** [comment]
I'm good with considering this closed for now.

**Comment by gep13** [comment]
Cool.  I have just corrected the TeamCity settings to put a `c` at the start on continuous, as per screen shot above :smile_cat:

**Comment by ferventcoder** [comment]
@gep13 thanks, copy pasta error.

**Comment by gep13** [comment]
> @gep13 thanks, copy pasta error.

No worries, things like that just sort of jump out at me :-D
