### ISSUE TITLE
``choco list`` does not list all packages

### ISSUE THREAD

**Issue by notklaatu** [chocolatey/choco#2001]
### What You Are Seeing?

``choco list`` returns 1075 packages, but chocolatey.org lists over 8000 packages available.

### What is Expected?

``choco list`` with no arg should list all packages in source, I think (unless I'm misunderstanding the docs). If not, then according to ``choco list --help``, the command ``choco list --all`` should.

### How Did You Get This To Happen? (Steps to Reproduce)

1. Install chocolatey from https://chocolatey.org/install.ps1 (v0.10.15)
2. Run ``choco list``

### Output Log

https://gist.github.com/notklaatu/a0054e82da4e10664dc9f2369dc5c108

**Comment by bc3tech** [comment]
I don't think `choco list` is good for listing **all** packages. For example when _I_ run it, I got back 2667 packages. 

When I run `choco list --order-by-popularity -pre` I get 49, but running `choco list -pre` gives me 31. Note the only diff is adding an "order by popularity" flag. 🤷🏻‍♂️

**Comment by notklaatu** [comment]
Maybe I'm misunderstanding the documentation. It seems to me that either ``choco list`` or ``choco list --all`` (or both) should return all packages available.

**Comment by bc3tech** [comment]
oh I completely agree it _should_, just saying in most example usages that you see - and the fact that `list` has a `search` alias - says to me that getting _all_ really isn't its intended usage.

**Comment by sukucorp** [comment]
choco list returns different results for different invocations. In One invocation, I got around 6000+ packages, while in another only 4000+. The output is not consistent.

**Comment by gep13** [comment]
This is as a result of the current infrastructure that the site is built with. It's a long story. This is something that we are working on improving though.

**Comment by sukucorp** [comment]
> choco list returns different results for different invocations. In One invocation, I got around 6000+ packages, while in another only 4000+. The output is not consistent.

I have even tried using --timeout=0 to rule out network connectivity issues. But did not affect the output.

**Comment by gep13** [comment]
That is unlikely to help. If it is what I suspect it is, and what we are working to fix, there is nothing that can be done currently to work around it.

**Comment by sukucorp** [comment]
One way to solve this is to have a cache of available packages downloaded to the local machine and then query the local cache for each invocation.

Most of the package managers do something similar and use intelligent/manual ways of keeping the cache updated with minimal data downloaded.

**Comment by TheCakeIsNaOH** [comment]
@sukucorp A local package index is planned, follow #820

**Comment by pauby** [comment]
I'm going to go ahead and close this based on the resolution being in #820. If we need to reopen it again we can.
