### ISSUE TITLE
Logging: Show details of errors on repository operations

### ISSUE THREAD

**Issue by kylebaker** [chocolatey/choco#2007]
Recently I tried to push a package to the public repository. I changed the .nuspec file to be more detailed when updating the package this last update. When I went to push the package, I received the following error:

`An error has occurred. It's possible the package version already exists on the repository.`

The package I'm pushing is differently a newer version. I thought it was a chocolatey problem so I submitted a ticket and heard a response from Gary Ewan Park. By the time he replied, I resolved the issue. He requested that I submit an issue here on github.

The actual error in the logs reads:

`More Details: System.ApplicationException: An error has occurred. It's possible the package version already exists on the repository. ---> System.InvalidOperationException: Failed to process request. 'This package had an issue pushing: A nuget package's Description property may not be more than 4000 characters long.'.`

I reduced the description down under 4000 characters and tried to push the package again. It worked. I've resolved the issue but the error I got wasn't clear until I checked the log. Can we update this so it's more clear for others who might run into a similar problem?

Thanks
-Kyle

**Comment by n3rd4i** [comment]
I have the same issue:
```
❯ choco --version
0.10.15
```

**Comment by medikoo** [comment]
> The actual error in the logs reads:

@kylebaker where did you access logs?

I have same error, but description on my side is definitely shorter than 4000 characters. I've attempted to run `choco push` with `-v` to possibly receive a more detailed error information, but then package got published successfully.

**Comment by vexx32** [comment]
Logs should be in `$env:ChocolateyInstall/logs` 🙂

**Comment by flcdrg** [comment]
This appears to have caught me out too. Didn't even occur to me to look in the logs seeing as I'd already tried `-verbose` and that didn't show anything useful.

I had resorted to running Fiddler to capture the push and it was actually the response there that showed the message.

The fact that choco.exe isn't displaying the actual error message feels like a bug to me.

**Comment by ukd1** [comment]
This just caught me out, assuming it's this causing it.
