### ISSUE TITLE
Force install of package failing Validation Testing

### ISSUE THREAD

**Issue by superbonaci** [chocolatey/choco#2019]
Would like to know how to force install package version with ``Validation Testing Failed``.

Want to upgrade qbittorrent from v4.2.1 to v4.2.2 because i think fixes a critical bug.

[qBittorrent 4.2.2 @ choco](https://chocolatey.org/packages/qbittorrent/4.2.2)

Something like: `choco upgrade --force-failing qbittorrent=4.2.2`

**Comment by superbonaci** [comment]
Ok done, had to install it using nupkg:

Go to [qBittorrent 4.2.2 chocolatey package](https://chocolatey.org/packages/qbittorrent/4.2.2), then click on [Download | Download the raw nupkg file.](https://chocolatey.org/api/v2/package/qbittorrent/4.2.2)

Then install it from Command Prompt or Powershell

```choco install .\qbittorrent.4.2.2.nupkg```

**Comment by superbonaci** [comment]
The you can check it's installed:
```
choco list --local-only -e qbittorrent
Chocolatey v0.10.15
qbittorrent 4.2.2
1 packages installed.
```

**Comment by pauby** [comment]
You can do this by giving it specifying the version `choco install qbittorrent --version=4.2.2`.

I'm going to go ahead and close this just now as you've already resolved it.

**Comment by superbonaci** [comment]
More info:
[CommandsInstall](https://github.com/chocolatey/choco/wiki/CommandsInstall)
