### ISSUE TITLE
"Get-Command choco" displays incorrect version

### ISSUE THREAD

**Issue by 0xdavew** [chocolatey/choco#2031]
**What do I see?**
- "choco -v" gives correct version: [0.10.15]
- "Get-Command choco" gives incorrect version: [0.10.5.0]

**What is Expected?**
I expect these two to be consistent.
In a script, "gcm choco" a lot quicker than invoking choco.exe

**Steps to Reproduce**

```
PS C:\> choco -v
0.10.15
PS C:\> (Get-Command choco).FileVersionInfo.FileVersion
0.10.5.0
PS C:\> (choco -v) -eq ((Get-Command choco).FileVersionInfo.FileVersion)
False
PS C:\> Get-Command choco

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     choco.exe                                          0.10.5.0   C:\ProgramData\chocolatey\bin\choco.exe

```
### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
PS C:\> choco -v
0.10.15
PS C:\> (Get-Command choco).FileVersionInfo.FileVersion
0.10.5.0
PS C:\> (choco -v) -eq ((Get-Command choco).FileVersionInfo.FileVersion)
False
PS C:\> Get-Command choco

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     choco.exe                                          0.10.5.0   C:\ProgramData\chocolatey\bin\choco.exe
~~~

</p>

</details>

**Comment by 0xdavew** [comment]
More detailed version info:

```
PS C:\> Get-Command choco | Select-Object *

HelpUri            :
FileVersionInfo    : File:             C:\ProgramData\chocolatey\bin\choco.exe
                     InternalName:     choco.exe
                     OriginalFilename: choco.exe
                     FileVersion:      0.10.5.0
                     FileDescription:  chocolatey - shim
                     Product:          chocolatey
                     ProductVersion:   0.10.5 - shim 0.8.1
                     Debug:            False
                     Patched:          False
                     PreRelease:       False
                     PrivateBuild:     False
                     SpecialBuild:     False
                     Language:         Language Neutral

Path               : C:\ProgramData\chocolatey\bin\choco.exe
Extension          : .exe
Definition         : C:\ProgramData\chocolatey\bin\choco.exe
Source             : C:\ProgramData\chocolatey\bin\choco.exe
Version            : 0.10.5.0
Visibility         : Public
OutputType         : {System.String}
Name               : choco.exe
CommandType        : Application
ModuleName         :
Module             :
RemotingCapability : PowerShell
Parameters         :
ParameterSets      :

```

**Comment by mkevenaar** [comment]
@0xdavew I think this is due to the fact that you are referencing [shims](https://chocolatey.org/docs/features-shim). 

I think they are not updated anymore after v0.10.5. https://github.com/chocolatey/choco/tree/master/src/chocolatey.resources/redirects 

I am not saying that this is ok, but it should not impact your usage of Chocolatey.

To check if the `choco.exe` is updated correctly you could run `Get-Command C:\ProgramData\chocolatey\choco.exe`

**Comment by gep13** [comment]
@0xdavew @mkevenaar also, using:

```
choco --version
```

Will get your the version number of Chocolatey as well.

**Comment by 0xdavew** [comment]
Thanks. 
That makes sense.
Just read up on the interesting world of shims!
(Be nice if there was a separate command to update the shim exe version numbers to match the exe they point to.)

I wanted to find a way to determine the correct version - without having to know where the real binary was.

This is what works for me (for now - assuming output of `--shimgen-nop` doesn't change)

```
PS C:\> (gcm (choco --shimgen-noop)[1].Split(": ")[1]).FileVersionInfo.ProductVersion
0.10.15
```

This runs a helluva lot quicker than `choco -v` and gives me the right answer.
I'm happy and can move on with my life.
