### ISSUE TITLE
Could not find hub.exe installed by choco

### ISSUE THREAD

**Issue by zyh425285360** [chocolatey/choco#2032]
### What You Are Seeing?
choco install hub
C:\WINDOWS\system32>hub
Cannot find file at '..\\lib\hub\tools\bin\hub.exe' (C:\ProgramData\chocolatey\lib\hub\tools\bin\hub.exe). This usually indicates a missing or moved file.

### What is Expected?
After installed, the exe location is under C:\ProgramData\chocolatey\bin and after error occurs, I moved it into C:\ProgramData\chocolatey\lib\hub\tools\bin\hub.exe but still not found.

May I ask some help from you , thank you so much
Best Regards,
Michelle

**Comment by pauby** [comment]
@zyh425285360 This is a package issue and not a Chocolatey one. Can I ask that you contact the maintainers of the hub package using the 'Contact Maintainers' link on the package page?

I will go ahead and close this ticket now but we can reopen it in future if need be.
