### ISSUE TITLE
Chocolaty installation is not working using Powershell, not able to downlaod and unzip

### ISSUE THREAD

**Issue by akn9050** [chocolatey/choco#2035]
Function InstallChocolatey
    {   [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Write-host "installing chocolatety $time" 
        #Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')) -Verbose
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        choco feature enable -n allowGlobalConfirmation

    }

    InstallChocolatey 
installing chocolatety 202004151148
Getting latest version of the Chocolatey package for download.
Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.15.
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (503) Server Unavailable."
At line:167 char:3
+   $downloader.DownloadFile($url, $file)
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Extracting C:\Users\AMITKU~1\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\AMITKU~1\AppData\Local\Temp\chocolatey\chocInstall...
Unable to unzip package using 7zip. Perhaps try setting $env:chocolateyUseWindowsCompression = 'true' and call install again. Error: 7-Zip encountered 
a fatal error while extracting the files
At line:216 char:9
+     2 { throw "$errorMessage 7-Zip encountered a fatal error while ex ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to unzip...cting the files:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to unzip package using 7zip. Perhaps try setting $env:chocolateyUseWindowsCompression = 'true' and call install a 
   gain. Error: 7-Zip encountered a fatal error while extracting the files

**Comment by santhiya-v** [comment]
Facing same issue. Looks like chocolatey is under maintenance now, so packages are not getting downloaded.

**Comment by akn9050** [comment]
Thansk @santhiya-v, is there any offline installer url, from where i can get it installed.

**Comment by gep13** [comment]
@akn9050 @santhiya-v as communicated via several different channels, there was a period of scheduled maintenance on the site today:

https://status.chocolatey.org/issues/2020-04-15-scheduled-maintenance/

This is likely what caused your issue.  Can you please confirm that things are now working again?

**Comment by akn9050** [comment]
Hi @gep13 , 

Thanks for the update, everything is up and working again.

Thanks,
Amit
