### ISSUE TITLE
CLAHub is down

### ISSUE THREAD

**Issue by JurjenBiewenga** [chocolatey/choco#2036]
### What You Are Seeing?
CLAHub is down, making it impossible to sign the CLA.

### What is Expected?
The ability to sign the CLA through the link in [CONTRIBUTING.md](https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md#prerequisites)

### How Did You Get This To Happen? (Steps to Reproduce)
See https://www.clahub.com/agreements/chocolatey/choco

**Comment by ferventcoder** [comment]
I've filed https://github.com/clahub/clahub/issues/174 and am awaiting an answer there.

**Comment by vexx32** [comment]
I don't like our chances. That repo is looking a bit like a ghost town. We could be waiting quite a while. 😬

**Comment by JurjenBiewenga** [comment]
I agree with @vexx32, perhaps it would be a good idea to start looking at alternatives or contact the Berkman Klein center as they supposedly maintain CLAHub.

**Comment by JurjenBiewenga** [comment]
Would it be time to start looking for alternatives as no one seems to be maintaining CLAHub?

**Comment by gep13** [comment]
@JurjenBiewenga I am following up with some folks to see if we can get an answer on how best to proceed here.  I will update this issue if/when I know more.

**Comment by JurjenBiewenga** [comment]
@gep13 Did you manage to figure out how to proceed?

**Comment by ferventcoder** [comment]
I don't believe this is resolved? I prefer to keep things open until a resolution has been determined.

**Comment by ferventcoder** [comment]
Looks like from the issue I posted, we'll need to find an alternative.

**Comment by gep13** [comment]
I have tried reaching out several times via email addresses that I was able to find for some folks on the project, but I haven’t heard anything back from anyone, so looking for an alternative is likely the best course of action.

**Comment by gep13** [comment]
Another project that I know some folks are using is this one:

https://cla-assistant.io/

**Comment by ferventcoder** [comment]
Howdy folks! We've moved over to CLA Assistant, which other folks have been using and recommend. Unfortunately that means if you've signed the previous CLA, it won't have a record of that and you'll need to sign the new one for this. Apologies, but you will find that the CLA has been updated as well to Chocolatey Software, Inc.
