### ISSUE TITLE
Detecting Python

### ISSUE THREAD

**Issue by debjan** [chocolatey/choco#2045]
I opted to install Chocolatey through Node.js setup on Windows 10.

Although I have Python 3.8.2 in my PATH which is also defined as default Python interpreter in Windows registry, Chocolatey cannot detect it and tries to install it again and fails:

![image](https://user-images.githubusercontent.com/1919296/81242497-9828b280-900d-11ea-8454-0cd05104c6a8.png)

**Comment by pauby** [comment]
The 'python` package (that is upgraded, second from top) and the 'python3' package are two separate packages. If it's told to, Chocolatey will try to install / upgrade both of them.

**Comment by pauby** [comment]
I've closed this issue just now be we can reopen again if needed.
