### ISSUE TITLE
Package installed with `--allowmultiple` don't show up in `choco list -lo`

### ISSUE THREAD

**Issue by andmos** [chocolatey/choco#2046]
👋 Hi guys, first of all, thanks for a great product and a nice user experience 🙏 

### What You Are Seeing?
I had to install an older version of the [dotnetcore-sdk package](https://chocolatey.org/packages/dotnetcore-sdk/2.1.802) side-by-side with the latest one, so I installed it using 
```
 choco install dotnetcore-sdk --version=2.1.802 --allowmultiple=true 
```
The installation goes well and I can see the package both on disk (`C:\ProgramData\chocolatey\lib\dotnetcore-sdk.2.1.802` and `C:\ProgramData\chocolatey\lib\dotnetcore-sdk`) and in the Installed Programs overview from windows, but when running `choco list -lo` only the latest version shows in the lits:

```
$ choco list -lo
dotnetcore-sdk 3.1.201
```

### What is Expected?

Would like both versions to show when running `choco list -lo`.

### How Did You Get This To Happen? (Steps to Reproduce)

Install some package, like latest `dotnetcore-sdk`, then install an older version with `--allowmultiple=true` and run ``choco list -lo`.

### Output Log
Log of reproducing with `wget` package:
https://gist.github.com/andmos/98e7f8cedc493e245c43d41632a11bd5

**Comment by ferventcoder** [comment]
Side by side installs don't really have a good experience - we need to either spend time on that or state that they are not really a supported use - they came in to maintain compat with old chocolatey (0.9.8.33 and below), and our recommendations for software that multiple versions can be installed should have separate package names with something in the version in the name - that way the upgrade experience is much better. 
 

Thoughts?

**Comment by andmos** [comment]
Not quite sure how widespread the need is, but for packages like SDK's, .NET Frameworks etc, most of the packages out there follow a versioning scheme where the pacakge ID is generic and the version is reflected in the version of the package. In those cases side-by-side is needed. With that said, having the version number in the Id solves that problem, but will not give the same upgrade-experience (in my old gig we used Ansible and `state=latest` on a lot of packages to grab the newest version automatically) and will give the package authors more responsibility for providing "new" packages for older versions. It's a classic case of "pick your poison" I would say.

**Comment by TheCakeIsNaOH** [comment]
As side by side installations have been deprecated, this issue is no longer relevant: https://github.com/chocolatey/choco/issues/2787
