### ISSUE TITLE
Include information about --version option in choco help documentation

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#2049]
Ensure when running the top level help that `--version` is mentioned as an option for outputting the version information.

Reference: https://twitter.com/hunterz0/status/1261487482006315018?s=21

**Comment by gep13** [comment]
@ferventcoder it looks like @entvex is interested in helping with this issue.  Can you please provide a little bit more information about exactly what you were thinking here?

Is it an additional option here:

https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/builders/ConfigurationBuilder.cs#L422-L424

Or were you thinking of something else?

**Comment by ferventcoder** [comment]
No, unfortunately it is not something that would go top level, it would literally be added after the fact of those items.

**Comment by ferventcoder** [comment]
So basically something that would be noted in the help menu, but not part of adding it to options.

**Comment by GankousKhan** [comment]
@ferventcoder I am having some trouble understanding what you mean here at first you say
>Ensure when running the top level help that --version is mentioned as an option for outputting the version information

but then later 

>No, unfortunately it is not something that would go top level, it would literally be added after the fact of those items.

Do you mean to say it would be an entry that would appear after the last switch/option after using the command `choco -?`  which would be 

```bash
 choco -?
This is a listing of all of the different things you can pass to choco.

Commands
...

Default Options and Switches
...
--log-file=VALUE
     Log File to output to in addition to regular loggers. Available in 0.1-
       0.8+.

The --version switch can be used to determine the current version of your choco installation.

Chocolatey v0.10.15
```
Where the second from last line `The --version switch can be used to determine the current version of your choco installation.` was an example addition that:

> would literally be added after the fact of those items.

Or if there is preferred verbiage and or formatting other than what I have noted please mention.

**Comment by entvex** [comment]
As we talked about on gitter.im, I would like to help solve this issue.
@ferventcoder said in this issue that it should not be part of the options, but that is exactly what the PR one submitted do.
So i wonder if you have any plan on how you like this implemented ?

**Comment by gep13** [comment]
@ferventcoder as mentioned, I think more guidance is required here on exactly where this change should be made.  I don't believe that the current open PR addresses it in the correct location.  Thoughts?

**Comment by ferventcoder** [comment]
I think originally I just wanted it to be added as a note in `choco -?`, not something that would actually be added to the options, for the reason I mentioned on PR #2029.

**Comment by gep13** [comment]
This has been added, and now show this in the output of the help command:

![image](https://user-images.githubusercontent.com/1271146/117943867-7c34ac80-b304-11eb-818e-f43fd05cac8a.png)
