### ISSUE TITLE
install with nodejs can not Identify python correctly

### ISSUE THREAD

**Issue by darkgirl** [chocolatey/choco#2059]
hi,
today , when I was installing nodejs , I also chosen to install choco tool.
but when I was install choco, I found it can not found my pre installed python3, 
and It wanted to install another python3, this is no big deal.

but after installing succeed, I Surprising discovery my old python was been delete.

what?

why?

how?

Didn’t he say he didn’t find it?

and I reinstalled several times, all the same.

This is the first time I have encountered a situation where the installation will delete other people's software

nodejs version: v12.7-v12.8
python version: 3.8.3
system: windows 10

**Comment by pauby** [comment]
@darkgirl Can you confirm the package(s) you installed, what the command you use to install and provide the Chocolatey logs as a gist?

**Comment by pauby** [comment]
This issue _may_ help https://github.com/chocolatey/choco/issues/1525

**Comment by darkgirl** [comment]
> This issue _may_ help #1525

hi, thanks 
actually I do not know what command wase used by nodejs installer,  but I know when nodejs install choco, there is a powershell window, It said like 'choco is upgrading...' then installed python.

does choco need to install python,? if not, may be this is nodejs install's problem.

**Comment by pauby** [comment]
Can you confirm how you installed nodejs? Did you download the installer from their website, double-click it and go through the installer / setup screens?

**Comment by darkgirl** [comment]
> Can you confirm how you installed nodejs? Did you download the installer from their website, double-click it and go through the installer / setup screens?

yes, this is where I download the installer: https://nodejs.org/en/
and this is which installer I downloaded: https://nodejs.org/dist/v12.18.0/node-v12.18.0-x64.msi

![捕获2](https://user-images.githubusercontent.com/28688741/83700867-9f59d500-a63a-11ea-8f4a-57ff27e3adc6.PNG)

**Comment by ferventcoder** [comment]
I believe that the python package might find an existing installation and upgrade it. 

Run `where.exe python` (exactly like that with the .exe) and provide the results.

**Comment by darkgirl** [comment]
> I believe that the python package might find an existing installation and upgrade it.
> 
> Run `where.exe python` (exactly like that with the .exe) and provide the results.

hi, thanks for your patient.
so, I decide to reproduce this issue.
this is the whole message came from the powershell window started by nodejs installer,
and there is some message I think might help.
`Getting latest version of the Chocolatey package for download.
Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.15.
Extracting D:\ObjAlpha\TEMP\chocolatey\chocInstall\chocolatey.zip to D:\ObjAlpha\TEMP\chocolatey\chocInstall...
Installing chocolatey on this machine
Creating ChocolateyInstall as an environment variable (targeting 'Machine')
  Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
WARNING: It's very likely you will need to close and reopen your shell
  before you can use choco.
Restricting write permissions to Administrators
We are setting up the Chocolatey package repository.
The packages themselves go to 'C:\ProgramData\chocolatey\lib'
  (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin'
  and points to an executable in 'C:\ProgramData\chocolatey\lib\yourPackageName'.

Creating Chocolatey folders if they do not already exist.

WARNING: You can safely ignore errors related to missing log files when
  upgrading from a version of Chocolatey less than 0.9.9.
  'Batch file could not be found' is also safe to ignore.
  'The system cannot find the file specified' - also safe.
chocolatey.nupkg file not installed in lib.
 Attempting to locate it from bootstrapper.
警告: Not setting tab completion: Profile file does not exist at
'D:\ObjAlpha\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'.
Chocolatey (choco.exe) is now ready.
You can call choco from anywhere, command line or powershell by typing choco.
Run choco /? for a list of functions.
You may need to shut down and restart powershell and/or consoles
 first prior to using choco.
Ensuring chocolatey commands are on the path
Ensuring chocolatey.nupkg is in the lib folder
Chocolatey v0.10.15
Upgrading the following packages:
python;visualstudio2017-workload-vctools
By upgrading you accept licenses for the packages.
python is not installed. Installing...
Progress: Downloading python 3.8.3... 100%
Progress: Downloading python 3.8.3... 100%

chocolatey-core.extension v1.3.5.1 [Approved]
chocolatey-core.extension package files upgrade completed. Performing other installation steps.
 Installed/updated chocolatey-core extensions.
 The upgrade of chocolatey-core.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolatey-core'

chocolatey-windowsupdate.extension v1.0.4 [Approved]
chocolatey-windowsupdate.extension package files upgrade completed. Performing other installation steps.
 Installed/updated chocolatey-windowsupdate extensions.
 The upgrade of chocolatey-windowsupdate.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolatey-windowsupdate'

KB3035131 v1.0.3 [Approved]
kb3035131 package files upgrade completed. Performing other installation steps.
Skipping installation because update KB3035131 does not apply to this operating system (Microsoft Windows 10 专业版).
 The upgrade of kb3035131 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

KB3033929 v1.0.5 [Approved]
kb3033929 package files upgrade completed. Performing other installation steps.
Skipping installation because update KB3033929 does not apply to this operating system (Microsoft Windows 10 专业版).
 The upgrade of kb3033929 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

KB2919442 v1.0.20160915 [Approved]
kb2919442 package files upgrade completed. Performing other installation steps.
Skipping installation because this hotfix only applies to Windows 8.1 and Windows Server 2012 R2.
 The upgrade of kb2919442 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

KB2919355 v1.0.20160915 [Approved]
kb2919355 package files upgrade completed. Performing other installation steps.
Skipping installation because this hotfix only applies to Windows 8.1 and Windows Server 2012 R2.
 The upgrade of kb2919355 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

KB2999226 v1.0.20181019 [Approved]
kb2999226 package files upgrade completed. Performing other installation steps.
Skipping installation because update KB2999226 does not apply to this operating system (Microsoft Windows 10 专业版).
 The upgrade of kb2999226 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

vcredist140 v14.26.28720.3 [Approved]
vcredist140 package files upgrade completed. Performing other installation steps.
Runtime for architecture x86 version 14.26.28720 is already installed.
Runtime for architecture x64 version 14.26.28720 is already installed.
 The upgrade of vcredist140 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

vcredist2015 v14.0.24215.20170201 [Approved]
vcredist2015 package files upgrade completed. Performing other installation steps.
 The upgrade of vcredist2015 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

python3 v3.8.3 [Approved]
python3 package files upgrade completed. Performing other installation steps.
Installing 64-bit python3...
WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could
mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Plea
se see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\python3_msi_install.log'"'. Then se
arch the MSI Log for "Return Value 3" and look above that for the error.
ERROR: Running ["C:\ProgramData\chocolatey\lib\python3\tools\python-3.8.3-amd64.exe" /quiet InstallAllUsers=1 PrependPat
h=1 TargetDir="C:\Python38" ] was not successful. Exit code was '1603'. Exit code indicates the following: Generic MSI E
rror. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot
is necessary prior to install or something else (like the same version is already installed). Please see MSI log if avai
lable. If not, try again adding '--install-arguments="'/l*v c:\python3_msi_install.log'"'. Then search the MSI Log for "
Return Value 3" and look above that for the error..
The upgrade of python3 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\python3\tools\chocolateyInstall.ps1'.
 See log for details.

python v3.8.3 [Approved]
python package files upgrade completed. Performing other installation steps.
 The upgrade of python was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.
visualstudio2017-workload-vctools is not installed. Installing...
Progress: Downloading visualstudio2017-workload-vctools 1.3.2... 100%
Progress: Downloading visualstudio2017-workload-vctools 1.3.2... 100%
Progress: Downloading visualstudio2017-workload-vctools 1.3.2... 100%

chocolatey-visualstudio.extension v1.8.1 [Approved]
chocolatey-visualstudio.extension package files upgrade completed. Performing other installation steps.
 Installed/updated chocolatey-visualstudio extensions.
 The upgrade of chocolatey-visualstudio.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolatey-visualstudio'

visualstudio-installer v2.0.1 [Approved]
visualstudio-installer package files upgrade completed. Performing other installation steps.
 The upgrade of visualstudio-installer was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

chocolatey-dotnetfx.extension v1.0.1 [Approved]
chocolatey-dotnetfx.extension package files upgrade completed. Performing other installation steps.
 Installed/updated chocolatey-dotnetfx extensions.
 The upgrade of chocolatey-dotnetfx.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolatey-dotnetfx'

dotnetfx v4.8.0.20190930 [Approved]
dotnetfx package files upgrade completed. Performing other installation steps.
Microsoft .NET Framework 4.8 or later is already installed.
 The upgrade of dotnetfx was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

visualstudio2017buildtools v15.9.23.0 [Approved]
visualstudio2017buildtools package files upgrade completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Hashes match.
Hashes match.
Installing visualstudio2017buildtools...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\HelpFile\1028\help.html...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\HelpFile\2052\help.html...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\HelpFile\1055\help.html...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\HelpFile\1046\help.html...
Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\HelpFile\1042\help.html...
Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\HelpFile\1029\help.html...



Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\HelpFile\1036\help.html...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\HelpFile\3082\help.html...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\HelpFile\1040\help.html...


Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\HelpFile\1045\help.html...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\HelpFile\1041\help.html...
Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\HelpFile\1049\help.html...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\HelpFile\1031\help.html...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\HelpFile\1033\help.html...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\vs_setup_bootstrapper.exe...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\Microsoft.Diagnostics.Tracin
g.EventSource.dll...



Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\Microsoft.VisualStudio.Remot
eControl.dll...
Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\Microsoft.VisualStudio.Setup
.Common.dll...
Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\Microsoft.VisualStudio.Setup
.Configuration.Interop.dll...


Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\Microsoft.VisualStudio.Setup
.dll...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\Microsoft.VisualStudio.Setup
.Download.dll...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\Microsoft.VisualStudio.Setup
.Engine.dll...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\Microsoft.VisualStudio.Telem
etry.dll...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\Microsoft.VisualStudio.Utili
ties.Internal.dll...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\Newtonsoft.Json.dll...
Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\zh-Hans\vs_setup_bootstrappe
r.resources.dll...


Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\zh-Hant\vs_setup_bootstrappe
r.resources.dll...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\cs\vs_setup_bootstrapper.res
ources.dll...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\es\vs_setup_bootstrapper.res
ources.dll...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\pt-BR\vs_setup_bootstrapper.
resources.dll...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\tr\vs_setup_bootstrapper.res
ources.dll...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\de\vs_setup_bootstrapper.res
ources.dll...
Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\fr\vs_setup_bootstrapper.res
ources.dll...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\it\vs_setup_bootstrapper.res
ources.dll...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\pl\vs_setup_bootstrapper.res
ources.dll...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\ko\vs_setup_bootstrapper.res
ources.dll...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\ja\vs_setup_bootstrapper.res
ources.dll...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\ru\vs_setup_bootstrapper.res
ources.dll...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\vs_setup_bootstrapper.config
...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\vs_setup_bootstrapper.exe.co
nfig...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\detection.json...

Preparing: D:\ObjAlpha\TEMP\chocolatey\b711ed7603c6e634708cb36a467564d6\vs_bootstrapper_d15\vs_setup_bootstrapper.json..
.


visualstudio2017buildtools has been installed.
 The upgrade of visualstudio2017buildtools was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

visualstudio2017-workload-vctools v1.3.2 [Approved]
visualstudio2017-workload-vctools package files upgrade completed. Performing other installation steps.
 The upgrade of visualstudio2017-workload-vctools was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey upgraded 16/17 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Upgraded:
 - visualstudio2017buildtools v15.9.23.0
 - kb2919355 v1.0.20160915
 - python v3.8.3
 - kb3033929 v1.0.5
 - chocolatey-core.extension v1.3.5.1
 - kb2999226 v1.0.20181019
 - dotnetfx v4.8.0.20190930
 - chocolatey-visualstudio.extension v1.8.1
 - vcredist2015 v14.0.24215.20170201
 - visualstudio2017-workload-vctools v1.3.2
 - kb2919442 v1.0.20160915
 - visualstudio-installer v2.0.1
 - vcredist140 v14.26.28720.3
 - chocolatey-dotnetfx.extension v1.0.1
 - kb3035131 v1.0.3
 - chocolatey-windowsupdate.extension v1.0.4

Failures
 - python3 (exited 1603) - Error while running 'C:\ProgramData\chocolatey\lib\python3\tools\chocolateyInstall.ps1'.
 See log for details.
Type ENTER to exit:
`
and, we are in different time zone, there maybe a long time before my next replying.

**Comment by ferventcoder** [comment]
Looks like there was an issue installing python based on what you provided. 

I'm guessing that the system needs a reboot (generic MSI error 1603 includes reboots necessary). However you can try the following:

* Open an administrative command shell
* Type the following: `choco install python3 -y --install-arguments="'/lv c:\python3_msi_install.log'"`
* If things fail, open up `c:\python3_msi_install.log` in an editor and search for "Return Value 3". The actual error is somewhere around there.

This is based on what the error message was telling us: 

> WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/lv c:\python3_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error.

**Comment by darkgirl** [comment]
> Looks like there was an issue installing python based on what you provided.
> 
> I'm guessing that the system needs a reboot (generic MSI error 1603 includes reboots necessary). However you can try the following:
> 
> * Open an administrative command shell
> * Type the following: `choco install python3 -y --install-arguments="'/lv c:\python3_msi_install.log'"`
> * If things fail, open up `c:\python3_msi_install.log` in an editor and search for "Return Value 3". The actual error is somewhere around there.
> 
> This is based on what the error message was telling us:
> 
> > WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/lv c:\python3_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error.

hi, 
I have tried your suggest, but it did not work.
there even no log file has been generated.
![捕获](https://user-images.githubusercontent.com/28688741/83829962-ad7d2380-a716-11ea-93cd-c4ed59681c42.PNG)

I tried several times and there is no log file no matter where I set to save it in the command.
and my old python is gone, there is a new python in C:/python38

there is some log from "C:\ProgramData\chocolatey\logs\chocolatey.log":
[chocolatey.log](https://github.com/chocolatey/choco/files/4733579/chocolatey.log)

**Comment by ferventcoder** [comment]
Unfortunately that MSI log is what is needed to tell us what is going wrong with the python installer. 1603 being generic could mean a reboot, could mean the same version is already installed, could be any number of things. I see it was passed to the installer properly and it appears it may not have made it to a log file.

One can attempt to uninstall anything that is there and then rerun installation of whatever python you would like.

**Comment by AdmiringWorm** [comment]
@darkgirl @ferventcoder 

the python 3 installer is not an MSI installer, so using the MSI log arguments do not work for it.

To get the logs from the installer you will need to pass in `/log {filepath}` (replace `{filepath}` to the path you want the logs to be stored).

![image](https://user-images.githubusercontent.com/1474648/85884646-3dc4fa80-b7e3-11ea-97c7-67a30800cc06.png)

**Comment by pauby** [comment]
There's been no update to this in over a year now so I'm going to go ahead and close it.

**Comment by pixelartchemist** [comment]
Hi, i have the same problem with the OP, but i did not have the **"WARNING: Generic MSI Error."** in my prompt.

I installed node via running node-v13.14.0-x64.msi and just kept on hitting next.

Install log:
[chocolatey.log](https://github.com/chocolatey/choco/files/7611167/chocolatey.log)
