### ISSUE TITLE
How to install Chocolatey for just the current user?

### ISSUE THREAD

**Issue by xmha97** [chocolatey/choco#2060]
Hello,
How to install Chocolatey for just the current user?

**Comment by pauby** [comment]
Like the majority of software on a Windows computer, Chocolatey installs system wide. There is no 'portable' version.

**Comment by ferventcoder** [comment]
@xmha97 you can put it in just for the current user, but it is going to track things at a higher level (machine installs) in most cases. If you are just going with non-admin, there are some advanced instructions for how to set this up - https://chocolatey.org/docs/installation#non-administrative-install. This will set almost everything to current user, but again if you install anything that is machine level software installations, it will be installed per machine.

**Comment by vexx32** [comment]
@ferventcoder the link in that doc `https://chocolatey.org/packages?q=id%3Aportable+tag%3Aportable` doesn't work; did something change in the filter processing in the website? Or is it just wrong? `id:portable` looks wrong to me tbh, unless it's supposed to be a partial match on the ID

**Comment by ferventcoder** [comment]
Yeah, the link is likely wrong there.
