### ISSUE TITLE
I cannot install Chocolatey Packages for Meteor.js

### ISSUE THREAD

**Issue by vidyasrineeharika** [chocolatey/choco#2061]
can you please help me

 with this issue? why can't I install the other package..Please help me..
![chocolatey](https://user-images.githubusercontent.com/56533257/83652250-08f4c780-a5d8-11ea-885c-42abe2d60751.PNG)

Thank you.

**Comment by vexx32** [comment]
From the logs, it looks like the file the package is designed to download no longer exists. Have you tried to contact the package maintainers?

**Comment by vidyasrineeharika** [comment]
> From the logs, it looks like the file the package is designed to download no longer exists. Have you tried to contact the package maintainers?

yeah..I've fixed the issue. I tried "choco install meteor --params="'/RELEASE:1.6.0.1'"" this command.  It was successfully installed..Thank you.
