### ISSUE TITLE
Some packages use non-API variables like $installArguments

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#207]
Packages that incorrectly use variables that were never part of the api.

I won't call this a bug because it is most definitely a bug in the packages, not in Choco

**Comment by ferventcoder** [comment]
This could sort of be related to #150

**Comment by ferventcoder** [comment]
Like firefox being one of the big ones

**Comment by gep13** [comment]
@ferventcoder which variables in particular are being used which shouldn't be?

**Comment by ferventcoder** [comment]
`$installArguments` is passed to choco - but it is not given to the packages.

**Comment by BradKnowles** [comment]
I sent the Firefox maintainers a fix (basic null check set to empty string).  It worked in my testing.  May not be the long term fix, but can get the Firefox package back up and running in the meantime.

Here's the [gist] (https://gist.github.com/BradKnowles/27aab9583fe60d494e7e) with log and fix info.

**Comment by gep13** [comment]
@ferventcoder right, that is what I thought you were referring to, just wanted to make sure that we are on the same page.

**Comment by ferventcoder** [comment]
I think I have this fixed.

**Comment by ferventcoder** [comment]
Yes, this is fixed. Going to start getting the documentation together to ship a new version today.
