### ISSUE TITLE
Unable to upgrade chocolatey and installed packages due to python3 not being compatible with chocolatey core essentials

### ISSUE THREAD

**Issue by stephenajulu** [chocolatey/choco#2077]
Hi, How are you?

I can't seem to update chocolatey and installed packages through using "choco upgrade all" or "choco upgrade <package-name> 
I keep getting this issue.
Tried unistalling python 3 but it failed. tried upgrading choco core extensions also failed.
Kindly help me.
I am using Powershell 7 Preview, also tried with Powershell and CMD, still couldn't upgrade.

Issue:
Updating 'chocolatey-core.extension 1.3.5.1' to 'chocolatey-core.extension 1.3.3' failed. Unable to find a version of 'python3' that is compatible with 'chocolatey-core.extension 1.3.3'.

**Comment by ferventcoder** [comment]
Hi @stephenajulu,
I'm sorry you are running into issues - this appears to be an issue with a package and not with Chocolatey itself. It could be that the package python3 is taking a minimum dependency that is not able to be found. It's hard to know what might be causing that (could be a cache that has not cleared), but then that would be an issue at the community repository. 

I would say to give it another shot and see if it was just a caching issue. If you are still having issues, we can move this over to the chocolatey.org repository.

**Comment by stephenajulu** [comment]
Still getting the issue.

**Comment by AdmiringWorm** [comment]
@ferventcoder @stephenajulu the python3 package takes a minimum dependency version of `1.3.5` which exists.

I know there is/was a related issue with the same message, but I am currently unable to find it again.

From previously this was mentioned, it typically was due to a stray package of `chocolatey-core.extension` (two package folders for that package, one with a version, and one without one).

**Comment by stephenajulu** [comment]
Okay, so what can i do to fix it or there's still no fix?
What about reinstallation?

**Comment by stephenajulu** [comment]
Found a fix

> yes! by explicitly removing chocolatey\lib\chocolatey-core.extension.1.1.0 folder with contents, all packages are installing well again. Big thanks! :)   [http://disq.us/p/1l0y6vz)](http://disq.us/p/1l0y6vz)

**Comment by stephenajulu** [comment]
then choco install chocolatey-core.extension
