### ISSUE TITLE
choco improperly attempts to load a DLL when Licensed ChocolateyGUI extension is installed

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/choco#2078]
### What You Are Seeing?

The following is logged as a warning when attempting to perform a choco install/upgrade/uninstall command:

```
WARNING: Import failed for 'C:\ProgramData\chocolatey\extensions\chocolateygui\chocolateygui.licensed.dll'.  Error: 'Could not load file or assembly 'Autofac, Version=4.6.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The system cannot find the file specified.'
```

### What is Expected?

That the ChocolateyGui extension DLL is skipped when choco imports all of the extension modules it currently has installed on the system, as it is not actually a PowerShell Module that needs to be imported into the session

### How Did You Get This To Happen? (Steps to Reproduce)

1. Install ChocolateyGUI 0.17+
2. Installed licensed package chocolateygui.extension
3. Perform any install/upgrade/uninstall operation

### Output Log

See 'What Are You Seeing' section

**Comment by ferventcoder** [comment]
Yes it does. @gep13 knows about this as well.

**Comment by ferventcoder** [comment]
Chocolatey is doing exactly what it was designed to do here, load extensions. We either need to move the gui extension to some other mechanism, have it work by finding the assemblies it needs, or add an exclusion specifically for this in choco. It seems we were leaning towards the latter when we last discussed this

**Comment by steviecoaster** [comment]
> or add an exclusion specifically for this in choco

This was the conclusion I got when I discussed it with @gep13 earlier today.

**Comment by ferventcoder** [comment]
Related to #1041
