### ISSUE TITLE
"choco install" ignores install arguments when specifying direct path to nupkg

### ISSUE THREAD

**Issue by the-ress** [chocolatey/choco#2089]
This is related to #1155, but its fix doesn't cover this case.

`PackageUtility.package_is_a_dependency` still incorrectly returns the package is a dependency. (I observed the `packageName` argument is `my-package` and `config.PackageNames` is the full path to nupkg - `c:\packages\my-package.1.2.3.nupkg`.)

It seems the original #1155 fix got the variables mixed up and the condition should look more like this:
```csharp
                if (packageName.is_equal_to(package)
                    || packageName.contains(package + ".")
                    || (package.contains(packageName)
                        && (package.contains(".nupkg")
                            || package.contains(".nuspec")
                            || package.contains("\\")
                        )
                    )
                )
```

### What You Are Seeing?
The install arguments are empty.

### What is Expected?
The install arguments should get passed to the installer.

### How Did You Get This To Happen? (Steps to Reproduce)
1. Have `my-package.1.2.3.nupkg` in `c:\packages`
2. Run `choco install -y --install-arguments="/my-arg" "c:\packages\my-package.1.2.3.nupkg"`

### Environment
Chocolatey 0.10.15
Windows 10 (1607 LTSB)

**Comment by ferventcoder** [comment]
Thanks for noting that. Are you in a position to provide a PR on this? Target stable if you do.
