### ISSUE TITLE
Make Chocolatey Information Banners a Color Other than Red

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#209]
I build automation scripts for others who are less familiar to run.  Red always means error to them - it would be great if chocolatey "upcoming" messages (like the one about "-y") were not red.  I have to admit, it frequently catches my eye too as I scan for red to review for problems.  Orange maybe?

**Comment by ferventcoder** [comment]
That was on old powershell version of chocolatey - this c# version doesn't do that.

**Comment by ferventcoder** [comment]
If you are not on 0.9.9+ then you should upgrade

**Comment by ferventcoder** [comment]
Closing as invalid - we only use red for errors in new choco.
