### ISSUE TITLE
When reporting installed applications, not all currently installed packages are correctly removed from list

### ISSUE THREAD

**Issue by gep13** [chocolatey/choco#2092]
It is possible that a package, which installs an application into Add/Remove programs, is installed, however, when running `choco list -li` the installed application is still listed.

When a Chocolatey package is installed, the associated installation application, should _not_ be included in this output.  This is an indication that this application is under the management of Chocolatey.

**Comment by ferventcoder** [comment]
I thought we already had an issue on this, but guessing we did not. Thanks for working that up. I'll put 0.10.16 milestone on this.
