### ISSUE TITLE
Set up appveyor.yaml and build

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#21]

**Comment by gep13** [comment]
If you wanted to add me to the team in AppVeyor, I would happily take a look at this.

**Comment by ferventcoder** [comment]
Yes, just be sure to Self assign the task and move it to working.

On Sunday, January 18, 2015, Gary Ewan Park <notifications@github.com>
wrote:

> If you wanted to add me to the team in AppVeyor, I would happily take a
> look at this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/21#issuecomment-70406103>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
Actually I might grab this so it falls under my account.

**Comment by ferventcoder** [comment]
Trying to determine a good notification list - think we'll want to set up a mailing list for build status. That way we don't diverge emails and people can self-subscribe.

**Comment by ferventcoder** [comment]
Actually added that. That way any build/integration tool can email build status changes to a mailing list.

**Comment by ferventcoder** [comment]
This is probably good enough now to close this issue. Any followup AppVeyor items should get a new ticket.

**Comment by gep13** [comment]
> Actually I might grab this so it falls under my account.

Yip, that is fine, what I was getting at was assigning a GitHub Team to the project that you set up in AppVeyor:

![image](https://cloud.githubusercontent.com/assets/1271146/5793811/d6b62592-9f49-11e4-8713-cd06b8992824.png)

![image](https://cloud.githubusercontent.com/assets/1271146/5793813/e4abfcda-9f49-11e4-844b-1d155c79947b.png)

That way, you still own the Project, but other team members can edit stuff if required.  This won't be as much of a big deal since we are driving everything through the appveyor.yml file, but still worth doing, IMO.

**Comment by ferventcoder** [comment]
I would love that.

On Sunday, January 18, 2015, Gary Ewan Park <notifications@github.com>
wrote:

> Actually I might grab this so it falls under my account.
>
> Yip, that is fine, what I was getting at was assigning a GitHub Team to
> the project that you set up in AppVeyor:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1271146/5793811/d6b62592-9f49-11e4-8713-cd06b8992824.png>
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1271146/5793813/e4abfcda-9f49-11e4-844b-1d155c79947b.png>
>
> That way, you still own the Project, but other team members can edit stuff
> if required. This won't be as much of a big deal since we are driving
> everything through the appveyor.yml file, but still worth doing, IMO.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/21#issuecomment-70422256>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder
