### ISSUE TITLE
choco uninstall --version $X --allow-multiple appends version to package name twice

### ISSUE THREAD

**Issue by vexx32** [chocolatey/choco#2101]
### What You Are Seeing?

Uninstalling a specific version of a package with `--allow-multiple` appends the version name twice and fails the uninstall.

### What is Expected?

The requested version is uninstalled -- OR an error is reported (e.g., `--allow-multiple is not a valid option for "uninstall" command`).

### How Did You Get This To Happen? (Steps to Reproduce)

1. Install/upgrade any package normally (optional; you can just pick an already-installed package)
2. Check what version was installed.
3. Attempt to uninstall that version with `choco uninstall $packageName -y --version $packageVersion --allow-multiple`

### Output Log

https://gist.github.com/vexx32/29d6de6fabad5f1b0337aba597e4a380

### Notes

This issue was originally reported in https://github.com/chocolatey/chocolatey-ansible/issues/21. The default behaviour there is to always use `--allow-multiple` (because there isn't a specific flag for it in the Ansible module) though conceivably we might be able to omit that flag for `uninstall` / `state: absent` requests.

**Comment by vexx32** [comment]
Was doing some testing around this today and found this behaviour _changes_ if multiple versions are currently installed.

If there are multiple versions installed side by side, use of `--allow-multiple` works just fine. However, if there is only a single version of the targeted package installed, this bug surfaces.

This... _complicates_ workarounds quite a bit; there is no one workaround that works here. If `--allow-multiple` _isn't_ specified on the uninstall command, _all_ installed package versions will be removed, if there is more than one. In other words, `--version` is completely ignored if `--allow-multiple` isn't specified. But if there's only one current version of the package installed, `--allow-multiple` exhibits this bugged behaviour.

**Comment by TheCakeIsNaOH** [comment]
As side by side installations have been deprecated, this issue is no longer relevant: https://github.com/chocolatey/choco/issues/2787
