### ISSUE TITLE
Add support to Extract tar files

### ISSUE THREAD

**Issue by naveen521kk** [chocolatey/choco#2102]
This is a request to add a helper function for extracting a `tar.xz` or a `tar.gz` files directly.

Currently, the function `Get-ChocolateyUnzip` but it isn't very helpful, as it first extracts it to `.tar` and then, it needs to call the same function again, so that, it is extracted. The function `Get-ChocolateyUnzip` should be handling this instead of making the user call the same function twice. 

Cheers.

**Comment by AdmiringWorm** [comment]
this looks to be a duplicate of #386

**Comment by vexx32** [comment]
Closing this for now, then. Thanks for reporting it @naveen521kk! We'll track this with the original issue. 🙂
