### ISSUE TITLE
Add support for reading powershell scripts in powershell

### ISSUE THREAD

**Issue by IJR222** [chocolatey/choco#2103]
is it possible to add a feature that allows users to read the powershell scripts during installation? like something similar to what yay does on arch linux.

**Comment by gep13** [comment]
@IJR222 this is already possible today. Assuming that you haven’t run a command with the -y option, and haven’t set the allowGlobalConfirmation feature flag, you will be presented with an option to review the scripts that are going to be executed. 

Can you confirm if this is what you would like?

**Comment by ferventcoder** [comment]
@IJR222 ping

**Comment by IJR222** [comment]
seems correct, closing
