### ISSUE TITLE
Installation of Chocolatey has been blocked by McAfee

### ISSUE THREAD

**Issue by m-tmatma** [chocolatey/choco#2109]
Installation of Chocolatey has been blocked by McAfee

https://chocolatey.org/install

```
PS C:\Windows\system32> Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
発生場所 行:1 文字:1
+ Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.Service ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
このスクリプトには、悪質なコンテンツが含まれているため、ウイルス対策ソフトウェアによりブロックされています。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent
```

The message says that this script has malicious contents, was blocked by Antivirus software.
McAfee is installed on the PC.

Please provide a standalone installer of Chocolatey without relying on remote powershell script.

**Comment by m-tmatma** [comment]
I'm using Windows 10 Pro 1909 and McAfee 16.0 R26.

```
Microsoft Windows [Version 10.0.18363.1016]
(c) 2019 Microsoft Corporation. All rights reserved.

```

**Comment by ferventcoder** [comment]
Hi @m-tmatma - please see https://chocolatey.org/install and scroll on down to Advanced section where you can read the installation docs. Then that should take you to https://chocolatey.org/docs/installation#more-install-options. I'll go ahead and close this off.
