### ISSUE TITLE
unused variable in chocolateyuninstall.ps1 template

### ISSUE THREAD

**Issue by DdOtzen** [chocolatey/choco#2114]
### What You Are Seeing?
An unused variable, with no obvious purpose.
### What is Expected?
Nu unused variable, or a comment telling me the purpose of having it there.
### How Did You Get This To Happen? (Steps to Reproduce)
choco new test
open tools\chocolateyuninstall.ps1 in editor
 
### Output Log

<details>
<summary>Output of new command</summary>
In here you see choco version
<p>

~~~sh
choco new test
Chocolatey v0.10.15
Creating a new package specification at C:\dock\choco_test\test
Generating template to a file
 at 'C:\dock\choco_test\test\test.nuspec'
Generating template to a file
 at 'C:\dock\choco_test\test\tools\chocolateyinstall.ps1'
Generating template to a file
 at 'C:\dock\choco_test\test\tools\chocolateybeforemodify.ps1'
Generating template to a file
 at 'C:\dock\choco_test\test\tools\chocolateyuninstall.ps1'
Generating template to a file
 at 'C:\dock\choco_test\test\tools\LICENSE.txt'
Generating template to a file
 at 'C:\dock\choco_test\test\tools\VERIFICATION.txt'
Generating template to a file
 at 'C:\dock\choco_test\test\ReadMe.md'
Generating template to a file
 at 'C:\dock\choco_test\test\_TODO.txt'
Successfully generated test package specification files
 at 'C:\dock\choco_test\test'
~~~

</p>

</details>
### Suggested fix
https://github.com/DdOtzen/choco/commit/4a27313a5f16053b8deb5e5ed0bd944dbe47353f#diff-28d68910eb8b4dca570c58ee95dc733e

**Comment by ferventcoder** [comment]
This was removed in commit https://github.com/chocolatey/choco/commit/804458c838872f6f4b4d5c9130c852aff1643a77.  Had to research that one. If you have a PR, target stable and we can get that in pretty quickly. Thanks in advance!

**Comment by DdOtzen** [comment]
Created PR https://github.com/chocolatey/choco/pull/2117
