### ISSUE TITLE
Feature - Add Uninstall-ChocolateyPath funtion

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/choco#2115]
`Install-ChocolateyPath` function exists to _add_ items to a system path, but we currently don't support the _removal_ via a native function

**Comment by vexx32** [comment]
FWIW I don't think Install/Uninstall are _at all_ great verbs for this. `Add`/`Remove` would be much more appropriate IMO.

**Comment by gep13** [comment]
There is a PR for this here:

https://github.com/chocolatey/choco/pull/1663

**Comment by TheCakeIsNaOH** [comment]
This already exists, see #310 for the issue, and #1019 + #1663 for PRs.

It would be nice if #1663 was reviewed.

**Comment by gep13** [comment]
So I would say this is a duplicate issue.
