### ISSUE TITLE
search/list - limiting results by page and page size is ignored

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#2120]
### What You Are Seeing?

When you call `choco list --page=0 --page-size=30` or `choco search chocolatey --page=0 --page-size=30`, the request to limit results returned is completely ignored.

In the first request there, you get about 250+ calls to a repository, effectively the same as simply running `choco list`, in the second you get several requests, which are the same as running `choco search chocolatey`. 

### What is Expected?

The page and skip tokens should be respected.

### How Did You Get This To Happen? (Steps to Reproduce)
* Open Fiddler
* Run the request `choco search chocolatey`
* Note the results
* Now run the request `choco search chocolatey --page=0 --page-size=30`
* Note the results (which are the same)

This also affects API usage, and this is seen most definitely when using something like Chocolatey GUI.

**Comment by ferventcoder** [comment]
Note this was discovered recently with https://github.com/chocolatey/ChocolateyGUI/issues/791.

**Comment by BElluu** [comment]
Hi @ferventcoder 
Can you retest, because I do not repeat it, so maybe it's fixed :)
![image](https://user-images.githubusercontent.com/11333925/173251178-aa7b9537-bf5d-405a-b2d4-f0dd7be661af.png)

**Comment by pauby** [comment]
This has been fixed in current versions of Chocolatey CLI.
