### ISSUE TITLE
CHOCO verification testing failed > "powershell to the minimum required version and run the command again"

### ISSUE THREAD

**Issue by adriens** [chocolatey/choco#2123]
### What You Are Seeing?

During validatoin phasis on [package upgrade](https://chocolatey.org/packages/schemacrawler/16.10.1), I got this message

https://gist.github.com/choco-bot/0a932dc883321aa4742756ced3c559db

```
[ERROR] Vagrant failed to initialize at a very early stage:
[ERROR] The version of powershell currently installed on this host is less than
[ERROR] the required minimum version. Please upgrade the installed version of
[ERROR] powershell to the minimum required version and run the command again.
[ERROR]   Installed version: N/A
[ERROR]   Minimum required version: 3
```
Looks like there is something on the travis side about powershell and choco ? I really don't see what to fix on my side.

### What is Expected?

The build should have passed ;-(

### How Did You Get This To Happen? (Steps to Reproduce)

Just resubmit the package to choco automated release process, details https://gist.github.com/choco-bot/0a932dc883321aa4742756ced3c559db

### Output Log

Everything is in the ghist

https://gist.github.com/choco-bot/0a932dc883321aa4742756ced3c559db

**Comment by bcurran3** [comment]
@adriens See https://github.com/chocolatey/package-verifier/issues/103

**Comment by adriens** [comment]
Thank you @bcurran3 for pointing it to me 👍

**Comment by gep13** [comment]
Thanks for moving this to the correct location.  I will go ahead and close this issue out.
