### ISSUE TITLE
Package chocolatey functionality as nuget package

### ISSUE THREAD

**Issue by tapika** [chocolatey/choco#2137]
Chocolatey could be used by normal applications to perform software update on their own 
application / sub-system.

It would be useful to package chocolatey as nuget package, so it would be easy to integrate and embed into any application.

Sample API's could be provided to demo how overall functionality works.

**Comment by tapika** [comment]
The application, which reuse choco functionality should be able to override 

`ApplicationParameters.InstallLocation`

and other locations as well.

**Comment by tapika** [comment]
Allow easy override on server URL, if want to use company specific nuget server.

**Comment by TheCakeIsNaOH** [comment]
I think this already exists if I understand what you want:
https://www.nuget.org/packages/chocolatey.lib/0.10.15

The documentation is REALLY lacking, but it exists.

**Comment by tapika** [comment]
I think I will need all features listed in here: https://github.com/chocolatey/choco/issues/2135
in other to start using it as a library. So I guess this could be very last step is to publish chocolatey.lib after all these changes.

Is chocolatey.lib compilation comes from https://github.com/chocolatey/choco, or is it another git ?

**Comment by ferventcoder** [comment]
Chocolatey.lib is in this code base. I'm going to close this as invalid since we already have a DLL that we publish that satisfies the intent of this issue.
