### ISSUE TITLE
Download only choco package, no extraction

### ISSUE THREAD

**Issue by tapika** [chocolatey/choco#2139]
At the moment `-n` option downloads and extracts nuget package.

I would propose to have `-skipunzip` to only download package without unpacking nuget package.

Then later on that can be installed by using `-s <folder to where download happened>`.

Also using `-packagedir` would override `ApplicationParameters.PackagesLocation`.

**Comment by TheCakeIsNaOH** [comment]
This has some overlap with the download command in the paid editions. 
https://chocolatey.org/docs/commands-download

I would be surprised this would be implemented, or if the chocolatey team would be willing to merge a PR.

Equivalent issue for the licensed edition: 
https://github.com/chocolatey/chocolatey-licensed-issues/issues/101

**Comment by tapika** [comment]
Please orchestrate in which order I will merge my changes, start from this ticket:

https://github.com/chocolatey/choco/issues/2135

I've put now automatic process elevation as a pull request in, but you do understand that it's expensive for me to create for each pull request separate branch, so changes are not clued one on another. Easier would be that you tell me what to merge, I'll start from that one.

**Comment by TheCakeIsNaOH** [comment]
> Easier would be that you tell me what to merge, I'll start from that one.

I'm just a community member, so I don't know, but @ferventcoder would be able to give you more information/make a decision.

**Comment by ferventcoder** [comment]
`choco download` is in Pro. We are unlikely to accept a change that would bring this to open source. If we decide for it to be there, we would bring down the code from Pro to FOSS.

**Comment by ferventcoder** [comment]
And remember, commercial options are what help us offer the great free options and community service that we have. So while we appreciate you want to bring this to open source, we have to weigh that with keeping Chocolatey around long term and not competing with the commercial offerings.
