### ISSUE TITLE
Allow easy switch of `choco` to something else

### ISSUE THREAD

**Issue by tapika** [chocolatey/choco#2141]
`choco` is pretty much hardcoded in quite many placed - that is help, documentation, etc.

But if developer want to just pick it up and experiment / upgrade it - better to change name `choco` to something else, just to avoid confusion with original tool.

**Comment by tapika** [comment]
It would be also useful to actually pinpoint if it's original choco application - then it would have licensing warnings, compatibility with old choco version, other things.

**Comment by ferventcoder** [comment]
Unfortunately, this is not one we are willing to explore at this time.
