### ISSUE TITLE
Comparing Versions

### ISSUE THREAD

**Issue by naveen521kk** [chocolatey/choco#2145]
This is simple. There needs to be a command to check which version is higher using choco. For example, In Debian/Ubuntu we can use 
```sh
dpkg --compare-version versA REL versB
```
and get a true/false return value. I want a same thing with chocolatey also.

**Comment by mastacheata** [comment]
Why do you need a choco command for that? It's already built into your shell by default:

```ps
$verA = '1.2.3.4'
$verB = '4.3.2.1'
[version]$verA -gt [version]$verB // returns: $FALSE
```

This is built-in with PowerShell and will tell you if verA is higher than verB

Version numbers can have up to 4 integer components, non-numeric strings are casted to integer for the sake of comparison. Check the .NET specification for more on how that conversion works.

**Comment by naveen521kk** [comment]
> Why do you need a choco command for that? It's already built into your shell by default:

Simply because other package managers also have this. I don't really know that PowerShell can be used for this. But would be lot helpful if it has a command in choco itself.
