### ISSUE TITLE
Add support for more compression methods

### ISSUE THREAD

**Issue by jansohn** [chocolatey/choco#2158]
With https://github.com/mcmilk/7-Zip-zstd we can easily add support for more compression methods like brotli and zstandard which offer fast (de-)compression (see benchmark on https://facebook.github.io/zstd/).

I can open a PR for this if desired.

**Comment by jansohn** [comment]
anyone? @ferventcoder @gep13 @pauby

**Comment by pauby** [comment]
What I can see here is that this is to allow support for faster compression methods. I've never heard anybody here complain that decompression of large packages is slow enough to complain about.

So my question is really, what are we trying to solve with this?

**Comment by jansohn** [comment]
> 
> 
> So my question is really, what are we trying to solve with this?

Well, installation speed of course. If we can use compression algorithms which have a better decompression performance then packages install quicker.
Below you can find an example we use in our company where the software has a large installation size of ~ 9GB. For comparison I used the highest compression levels for LZMA (level 9) and ZST (level 22) which results in roughly the same archive size.

    PS C:\> dir C:\app\creo | select name, length

    Name                        Length
    ----                        ------
    creo40_060_lzma_lvl9.7z 2189689731
    creo40_060_zst_lvl22.7z 2238568689

    PS C:\> Measure-Command { Get-ChocolateyUnzip C:\app\creo\creo40_060_lzma_lvl9.7z C:\app\creo\creo40_060_lzma | Out-Default }
    Extracting C:\app\creo\creo40_060_lzma_lvl9.7z to C:\app\creo\creo40_060_lzma...
    C:\app\creo\creo40_060_lzma

    Minutes           : 5
    Seconds           : 11
    Milliseconds      : 48
    TotalMinutes      : 5.18413566666667

    PS C:\> Measure-Command { Get-ChocolateyUnzip C:\app\creo\creo40_060_zst_lvl22.7z C:\app\creo\creo40_060_zst | Out-Default }
    Extracting C:\app\creo\creo40_060_zst_lvl22.7z to C:\app\creo\creo40_060_zst...
    C:\app\creo\creo40_060_zst

    Minutes           : 3
    Seconds           : 54
    Milliseconds      : 981
    TotalMinutes      : 3.91635749166667

Adding more compression algorithms does not break any existing functionality so my question would be why you wouldn't want to add support for them?

Zstandard is getting more and more traction (https://en.wikipedia.org/wiki/Zstandard#Usage) so I think it is just a matter of time until more people will ask about supporting it...

**Comment by pauby** [comment]
> Well, installation speed of course. If we can use compression algorithms which have a better decompression performance then packages install quicker.

I get that. But your example focuses on a 9GB package. That's not a normal package size. The majority of packages on the Chocolatey Community Repository are a few kb. And I'd suggest that even a package of 1GB is unusual.

What would the times be for those package sizes?

**Comment by jansohn** [comment]
OK, lot's of wrong assumptions here, so I will try to clear them up.

> 
> 
> > Well, installation speed of course. If we can use compression algorithms which have a better decompression performance then packages install quicker.
> 
> I get that. But your example focuses on a 9GB package. That's not a normal package size and anything above 2GB is not recommended. The majority of packages on the Chocolatey Community Repository are a few kb. And I'd suggest that even a package of 1GB is unusual. Up to 500MB I'd say is more common. That is based on nothing more than experience.

I'm not talking about the size of the nupkg files but about the installation files themselves which get downloaded during the installation process. Those can very well be any size (depends on the software which is being installed), right?

> > Adding more compression algorithms does not break any existing functionality so my question would be why you wouldn't want to add support for them?
> 
> Adding support for anything is not just a matter of PR into the repository. There are a lot more things that need to be done. It's not as simple as replacing one tool for another.
> 
> 7Zip has a tested and proven track record as a standalone product and as a tool used with Chocolatey. The algorithm that is used for compression also has a tested and proven track record. Switching that tool and the algorithm to something else is a massive undertaking in terms of support, time, planning and thought. What I'm thinking about is 'is the amount of time the vast majority of people will save worth the amount of work and effort that goes into making that change'.

7zip is not being replaced! It uses the already existing version (by the way still 32bit) and simply adds more compression algorithms via an additional sub-directory `Codecs`. Existing tools are not touched or replaced...

> 
> One thing I would take issue with is this:
> 
> > does not break any existing functionality
> 
> You don't know that.

I've extensively tested this in my environment. You will never know for sure that a change doesn't break anything if there are no automated tests. If it's so much work to test such a simple change then there is something fundamentally wrong with the project I would say.

So I assume Chocolatey is not interested in being improved so I will close this issue.

**Comment by AdmiringWorm** [comment]
If I understand everything correctly.

You are talking from a maintainer or package creator perspective, to basically add support for zstd and other compression algorithms in the `Install-ChocolateyZipPackage` and `Get-ChocolateyUnzip` helpers?

If so, I personally think that is a valid suggestion, and could perhaps be added easier with a few minor changes to the helpers.
If the helpers respected the system installed 7zip executable (by checking the PATH environment variable for instance), a package maintainer/creator could simply take a dependency on the correct package that installs a system executable and get support for those *extra* compression algorithms provided there.

And eventually falling back to chocolatey own 7zip executable if the system executable fails or is not available.

**Comment by pauby** [comment]
> I'm not talking about the size of the nupkg files but about the installation files themselves which get downloaded during the installation process. Those can very well be any size (depends on the software which is being installed), right?

Taking Sysinternals as an example (as it's the first zipped 'installer' I could think of) you're suggesting that the Sysinternals software use new algorithms to compress them? If that is the case that's outside Chocolatey's control. Whatever the installer uses as its compression method is down to whoever makes that package available. And if an installer uses a different compression algorithm then, [as @AdmiringWorm said](https://github.com/chocolatey/choco/issues/2158#issuecomment-785813289), you can just take a dependency on the compression software you want to use. 

> 7zip is not being replaced! It uses the already existing version (by the way still 32bit) and simply adds more compression algorithms via an additional sub-directory Codecs. Existing tools are not touched or replaced...

Bad choice of  words. New algorithms are being added. However, the points about the your codecs not being tested and having a proven track record still stands. And that's no reflection on you. That's just a fact, as I see it. There is a difference of trust between users adding those algorithms themselves to a product shipping with them. If Chocolatey ships with them we are telling people they are being trusted by the product. 

I'm trying to understand what the use case is, how it benefits users, explain how those benefits need to be weighed against the time involved in testing and implementation and explain that changing a fundamental part of Chocolatey is complicated as there are many things to consider. I'm just asking questions. Comments such as:

> So I assume Chocolatey is not interested in being improved so I will close this issue.

... don't help.

**Comment by AdmiringWorm** [comment]
> And if an installer uses a different compression algorithm then, as @AdmiringWorm said, you can just take a dependency on the compression software you want to use. I'm not even sure you'd need to amend the helpers (and to be fair I haven't looked).

That wasn't really my full point, at least not without a modification to the helpers I mentioned.
If the helpers was updated to first use the global 7zip installation (if available), then yes just taking a dependency would help to get the additional algorithms wanted in the issue.

As @jansohn mentioned here:

> 7zip is not being replaced! It uses the already existing version (by the way still 32bit) and simply adds more compression algorithms via an additional sub-directory Codecs. Existing tools are not touched or replaced...

One of the community packages makes use of this, by adding support for `zstd` when using `7zip`, but that is only available for the system installed `7zip` as far I understand.
This is why I mentioned a modification to the helpers to make use of the system installed `7zip` if it is available. Otherwise, to get that support one would either need to call the extractor manually or modify chocolatey's own tools folder (which of course shouldn't be done).

**Comment by jansohn** [comment]
> 
> 
> If I understand everything correctly.
> 
> You are talking from a maintainer or package creator perspective, to basically add support for zstd and other compression algorithms in the `Install-ChocolateyZipPackage` and `Get-ChocolateyUnzip` helpers?

Yes, that's what I was talking about.

> 
> If so, I personally think that is a valid suggestion, and could perhaps be added easier with a few minor changes to the helpers.
> If the helpers respected the system installed 7zip executable (by checking the PATH environment variable for instance), a package maintainer/creator could simply take a dependency on the correct package that installs a system executable and get support for those _extra_ compression algorithms provided there.
> 
> And eventually falling back to chocolatey own 7zip executable if the system executable fails or is not available.

It doesn't even need to be so complicated. I added an example of how I would have added support for zstd:
https://github.com/jansohn/choco/pull/1

With this change we can use the `Get-ChocolateyUnzip` helper for installation and when the team over at Sysinternals ever decides to only offer their software as an zstd archive (not that I think this will happen anytime soon) Chocolatey would still work. 

The more important point is that it is generally even possible to use a newer compression algorithm like zstd with Chocolatey if a package maintainer chooses so without going through hoops to get it done (like installing zstd package as a dependency and calling it from the Powershell explicitly).

In my opinion this change has a very low risk of breaking anything but it seems you guys have a different opinion on this.
