### ISSUE TITLE
choco list incomplete

### ISSUE THREAD

**Issue by DominikGeimer** [chocolatey/choco#2159]
### What You Are Seeing?
When running command **choco **list**** I get back about 5000 packages, but on the website, there are over 8000 packages listed.

### What is Expected?
I expect to see the same number of packages when running **choco list** or visiting the website.

**Comment by gliptak** [comment]
I also observe this discrepancy

```
PS > choco source
Chocolatey v0.10.15
chocolatey - https://chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
PS > choco list
...
jetbrains-youtrack 2020.6.4750 [Approved]
lastpass 4.64.0 [Approved]
5713 packages found.
```


![image](https://user-images.githubusercontent.com/50109/106627402-c6103880-6546-11eb-816b-57edae4cf43d.png)

**Comment by sukucorp** [comment]
Duplicate of #2001

**Comment by TheCakeIsNaOH** [comment]
Agreed @sukucorp 

As noted in #2001, this is a limitation with how the community repository infrastructure works, and #820 is the planned resolution.
