### ISSUE TITLE
Installed specific (earlier) version, can't pin

### ISSUE THREAD

**Issue by black-snow** [chocolatey/choco#2169]
### What You Are Seeing?

```
Chocolatey v0.10.15
Trying to add a pin for python
Unable to find package named 'python' (version '3.8.6') to pin. Please check to ensure it is installed.
```

### What is Expected?

```
Successfully added a pin ...
```

### How Did You Get This To Happen? (Steps to Reproduce)

I installed an earlier version of Python: `choco install python --version=3.8.6`. Everything's fine with that.
Now I'd like to pin that version:

```
choco pin add -n python
Chocolatey v0.10.15
Trying to add a pin for python
Successfully added a pin for python v3.9.1.
```

It pinned the latest version, but I installed 3.8.6: 

```
python --version
Python 3.8.6
```

So let's try the `--version` flag:

```
choco pin add -n python --version 3.8.6
Chocolatey v0.10.15
Trying to add a pin for python
Unable to find package named 'python' (version '3.8.6') to pin. Please check to ensure it is installed.
```

:|

Also Choco GUI shows that 3.9.1 is installed, which is not correct. So I guess that there's an issue with remembering the actual version. I also pinned some early firefox some months ago and that worked as expected. But at that time, I installed the current version and pinned that one.

**Comment by pauby** [comment]
I'm a little confused by this one. Which version of the `python` package is installed? What does `choco list python -lo` show?

**Comment by black-snow** [comment]
`3.8.6` is installed but choco thinks it's `3.9,1`:

```
PS C:\WINDOWS\system32> python --version
Python 3.8.6
PS C:\WINDOWS\system32> choco list python -lo
Chocolatey v0.10.15
chocolatey 0.10.15
python 3.9.1
2 packages installed.
PS C:\WINDOWS\system32>
```

**Comment by pauby** [comment]
Can you run `where.exe python` (note that the `.exe` after `where` is crucial otherwise it won't work).

For example, when I run it, I get:

```
> where.exe python
C:\Python39\python.exe
C:\Python38\python.exe
C:\Python37\python.exe
C:\Python36\python.exe
C:\Users\Paul\AppData\Local\Microsoft\WindowsApps\python.exe
```

**Comment by black-snow** [comment]
@pauby 
```
where.exe python
C:\Python38\python.exe
C:\Python39\python.exe
C:\Users\xxx\AppData\Local\Microsoft\WindowsApps\python.exe
```

**Comment by pauby** [comment]
Okay that explains the problem.

```
Chocolatey v0.10.15
Trying to add a pin for python
Unable to find package named 'python' (version '3.8.6') to pin. Please check to ensure it is installed.
```

You can't pin the python package, version 3.8.6 as Chocolatey doesn't manage that.

```
choco pin add -n python
Chocolatey v0.10.15
Trying to add a pin for python
Successfully added a pin for python v3.9.1.
```

You can add a tag for `python` 3.9.1 as Chocolatey does manage that.

**Comment by vexx32** [comment]
In the original post @black-snow mentions they did use choco to install 3.8.6 specifically:

> ...
> I installed an earlier version of Python: `choco install python --version=3.8.6`
> ...

Unless they're misremembering how that version was installed.

**Comment by black-snow** [comment]
@vexx32 true. As I mentioned, pinning current versions seems to work just fine, even if they become outdated. But installing and pinning versions that are already outdated is buggy.

**Comment by pauby** [comment]
@black-snow I'd just like to reiterate a point I made previously - you can't pin version `3.8.6` when Chocolatey isn't managing that version. It's managing `3.9.1`. 

Just to answer what you had said, you can't pin 'versions that are outdated' (or as I would put it, versions that 'Chocolatey isn't managing').

I think there is some misunderstanding of the terminology used. The Chocolatey pin command help shows:

```
     --version=VALUE
     Version - Used when multiple versions of a package are installed.
       Defaults to empty.
```

The important part of that is 'Used when multiple versions of a **package** are installed'. You don't have multiple versions of a **package** installed. You only have version 3.9.1 of the **package** installed (shown by the output you gave above). You may  have multiple versions of the Python **software** installed but Chocolatey doesn't manage **software**, it manages **packages**.

If I try and reproduce the issue you had above:

```
PS> choco install python --version=3.8.6
Chocolatey v0.10.15
Installing the following packages:
python
By installing you accept licenses for the packages.
<REMOVED LOTS OF INSTALL STUFF>
Chocolatey installed 11/11 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
<REMOVED LOTS OF INSTALL STUFF>

PS> choco pin add -n python
Chocolatey v0.10.15
Trying to add a pin for python
Successfully added a pin for python v3.8.6.

PS> python --version
Python 3.8.6
```

I know you didn't do the command below, but I wanted to show this:

```
PS> choco pin add -n python --version 3.9.1
Chocolatey v0.10.15
Trying to add a pin for python
Unable to find package named 'python' (version '3.9.1') to pin. Please check to ensure it is installed.
```

The data you provided above shows that python version 3.9.1 is installed and not 3.8.6 which is where the 'issue' lies.

Does that make sense?

**Comment by black-snow** [comment]
@pauby thanks for your reply!

```
python --version
Python 3.8.6
```

I neither installed 3.8.6 nor 3.9.1 any other way than via choco.

**Comment by vexx32** [comment]
I have attempted to reproduce this with the following:

```ps1
choco install python --version 3.9.1 -y

choco install python --version 3.8.6 --allow-multiple -y

choco pin add -n=python --version 3.8.6
```

This sequence of commands does work. I'm not sure exactly what you're running into, but perhaps this might be helpful? 😕

**Comment by black-snow** [comment]
I first installed `python` without any version number (which came out as 3.9.x). Then uninstalled again and installed 3.8.6. Well, doesn't matter, I'll just *nope-away* the prompt whenever I `cup all`.
Thanks for your efforts!

**Comment by pauby** [comment]
There is a lot of information that keeps coming out on this one so I'm left a little confused. However you did say you'd uninstalled version 3.8.6. Python (3.8.6 but I suspect other versions) don't uninstall themselves properly. I have this in my C: drive:

![image](https://user-images.githubusercontent.com/12760779/104915414-82370400-5988-11eb-8eca-037741a5fdbc.png)

I also tried this in a sandbox:

```
PS C:\Users\WDAGUtilityAccount> choco install python --version 3.8.6
Chocolatey v0.10.15
Installing the following packages:
python
By installing you accept licenses for the packages.
Progress: Downloading python3 3.8.6... 100%
Progress: Downloading python 3.8.6... 100%

<REMOVED IRRELEVANT LOGS>

python v3.8.6 [Approved]
python package files install completed. Performing other installation steps.
 The install of python was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 11/11 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

```
PS C:\Users\WDAGUtilityAccount> refreshenv
Refreshing environment variables from the registry for powershell.exe. Please wait...
Finished
PS C:\Users\WDAGUtilityAccount> python --version
Python 3.8.6
PS C:\Users\WDAGUtilityAccount> choco uninstall python --version 3.8.6
PS C:\Users\WDAGUtilityAccount> choco uninstall python
Chocolatey v0.10.15
Uninstalling the following packages:
python

python v3.8.6
 Skipping auto uninstaller - No registry snapshot.
 python has been successfully uninstalled.

Chocolatey uninstalled 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
PS C:\Users\WDAGUtilityAccount> python --version
Python 3.8.6
```

So even though it was uninstalled, it was still there.

**Comment by vexx32** [comment]
Yeah I've noticed that installing `python` packages pulls in `python3` packages of the same version which I think are the ones that actually contain the installers, so you have to uninstall those dependency packages too.

**Comment by black-snow** [comment]
@pauby thanks for investigating. I indeed unintentionally left out the prior bits ó.Ò
