### ISSUE TITLE
Allow skipping a broken update without skipping further updates

### ISSUE THREAD

**Issue by 0xallie** [chocolatey/choco#217]
I can pin a package with `choco pin`, but I would like to have an option to skip a specific (broken) version.

**Comment by ferventcoder** [comment]
Can you expand on what you mean?

**Comment by ferventcoder** [comment]
I mean I think I understand, but this doesn't seem that trivial to implement.

**Comment by ferventcoder** [comment]
`choco skip -n git -v 1.9.5.20150329` 
So it skips that version if that is the latest, but will go on to a later version.

**Comment by thomasvdb** [comment]
@nyuszika7h Is this still a feature request you want to see implemented?
I think we need some more requirements for this as well.

- If the pinned package is broken, what's the next version to take? The latest? The next available one compared to the pinned version?
- A warning message should be shown when your pinned packaged is broken or maybe a confirmation about what action to take?
