### ISSUE TITLE
Installation hangs on Windows 10

### ISSUE THREAD

**Issue by Bilge** [chocolatey/choco#2170]
### What You Are Seeing?
>Installing chocolatey on this machine

No more output, command prompt never returns. 

### What is Expected?
Command prompt should return after some time. 

### How Did You Get This To Happen? (Steps to Reproduce)
1. `Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))`

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Windows\system32> Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
Getting latest version of the Chocolatey package for download.
Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.15.
Extracting Temp\chocolatey\chocInstall\chocolatey.zip to Temp\chocolatey\chocInstall...
Installing chocolatey on this machine
~~~

</p>

</details>

**Comment by Bilge** [comment]
Actually it eventually did complete, it just took a lot longer than "a few seconds" described in the installation instructions. More like a few minutes (wasn't actually timing it or paying attention when it finally did conclude).

**Comment by mercertom** [comment]
This still seems like a bug. Chocolatey isn't 60GB, and these minutes are alarmingly long. I'm curious if my install will ever conclude. I definitely aborted it once because it was unresponsive.

**Comment by pauby** [comment]
@mercertom This issue is closed. If it's still a problem, please raise a new issue.
