### ISSUE TITLE
Many packages won't upgrade - error with chocolatey.extension

### ISSUE THREAD

**Issue by brennanfee** [chocolatey/choco#2176]
### What You Are Seeing?

For numerous packages, when I try and upgrade them wtih `choco upgrade -y <package>`, I get the following error:

<package> not upgraded. An error occurred during installation:
 Updating 'chocolatey 0.10.15' to 'chocolatey 0.10.13' failed. Unable to find a version of 'chocolatey.extension' that is compatible with 'chocolatey 0.10.13'.

### What is Expected?

That the package successfully upgrades.

### Output Log

Below sample for the ruby package:

> choco upgrade -y ruby --debug --verbose
Chocolatey v0.10.15 Professional
Chocolatey is running on Windows v 10.0.19042.0
Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
Command line: "C:\ProgramData\chocolatey\choco.exe" upgrade -y ruby --debug --verbose
Received arguments: upgrade -y ruby --debug --verbose
RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
CountdownTask is now ready and waiting for PostRunMessage.
Terminal services setup not necessary for this session.
SynchronizeTask is now ready and waiting for PreRunMessage.
Sending message 'PreRunMessage' out if there are subscribers...
[Pending] Removing all pending packages that should not be considered installed...
[Synchronize] Updating packages with Programs and Features
[Synchronize] Currently only supports removals. Soon will handle updates.
7zip 19.0
7zip.install 19.0
AdoptOpenJDK14 14.0.2.1200
alacritty 0.7.1
alacritty.install 0.7.1
autohotkey 1.1.33.02
autohotkey.install 1.1.33.02
awscli 2.1.19
beyondcompare 4.3.7.25118
bind-toolsonly 9.14.2
bitwarden 1.23.1
bitwarden-cli 1.13.3
carnac 2.3.13
chocolatey 0.10.15
chocolatey-core.extension 1.3.5.1
chocolatey-dotnetfx.extension 1.0.1
chocolatey-fastanswers.extension 0.0.2
chocolatey-misc-helpers.extension 0.0.4
chocolatey-windowsupdate.extension 1.0.4
chocolatey.extension 2.1.1
cloc 1.82
cmake 3.19.2
cmake.install 3.19.2
colortool 19.04.29002
corretto11jdk 11.0.9.121
curl 7.73.0
devdocs-app 0.7.1
diffutils 2.8.7
directoryopus 12.23
docker-cli 19.03.3
docker-desktop 3.0.0
dos2unix 7.4.2
DotNet4.5.2 4.5.2.20140902
DotNet4.6.1 4.6.01055.20170308
dotnetcore-sdk 3.1.405
dotnetfx 4.8.0.20190930
drawio 14.1.8
editorconfig.core 0.12.1
element-desktop 1.7.16
emacs 27.1.0.20200909
etcher 1.5.112
evernote 10.6.9
fd 8.2.1
ffmpeg 4.3.1.20201122
findutils 4.2.30.5
Firefox 84.0.2
gawk 5.1.0
Ghostscript 9.53.3
Ghostscript.app 9.53.3
git 2.30.0
git.install 2.30.0
gnupg 2.2.27
gnuwin32-coreutils.install 5.3.0
golang 1.15.6
GoogleChrome 87.0.4280.88
grep 2.1032
gzip 1.3.12
hashcheck 2.4.0.20181230
imagemagick 7.0.10.55
insomnia-rest-api-client 2020.5.2
jetbrainstoolbox 1.19.7784
jiracli 1.1.0
jq 1.6
KB2533623 2.0.0
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
KB3063858 1.0.0
KB3118401 1.0.5
kindle 1.30.59056
less 5.63
loc 1.0.0
megasync 4.3.9.0
megatools 1.11.0
microsoft-teams 1.3.00.28779
microsoft-windows-terminal 1.4.3243.0
miktex 20.12
miktex.install 20.12
neovim 0.4.4
netfx-4.8 4.8.0.20190930
netfx-4.8-devpack 4.8.0.20190930
nodejs-lts 14.15.4
nssm 2.24.101.20180116
okular 20.04.0
packer 1.6.6
pandoc 2.11.3.2
patch 2.5.9
pencil 3.1.0
php 8.0.0.20201221
plex 1.26.0.1531
powershell-core 7.1.0
python 3.9.1
python3 3.9.1
riot-web 1.5.15.20200728
ripgrep 12.1.1.20200727
ruby 2.7.2.1
rufus 3.13
rust-ms 1.49.0
scribus 1.4.8
sed 4.8
serve 0.3.0
serve.portable 0.3.0
shellcheck 0.7.1
signal 1.39.4
skype 8.67.0.99
slack 4.12.2
speedcrunch 0.12.20190615
speedcrunch.install 0.12
spotify 1.1.48.625
sysinternals 2021.1.15
terraform 0.14.4
texmaker 5.0.4
tflint 0.22.0
ubuntuhere 0.0.5.20200501
universal-ctags 2021.01.12
unzip 6.0
vagrant 2.2.14
vcredist-all 1.0.0
vcredist140 14.28.29325.2
vcredist2005 8.1.0.20160118
vcredist2008 9.0.30729.6163
vcredist2010 10.0.40219.2
vcredist2012 11.0.61031
vcredist2013 12.0.40660.20180427
vcredist2015 14.0.24215.20170201
vcredist2017 14.16.27033
vcxsrv 1.20.9.0
vim-tux 8.2.2129
vim-tux.install 8.2.2129
virtualbox 6.1.16
vlc 3.0.11
vscode 1.52.1
vscode.install 1.52.1
wavebox 10.0.393
Wget 1.20.3.20190531
which 1.11
windirstat 1.1.2.20161210
wsl 1.0.1
wsl-archlinux 1.0.3.0
wsl-debiangnulinux 9.0.0.020180923
yq 3.4.1
zerotier-one 1.6.2
zip 3.0
zoom 5.4.59931.0110
Performing validation checks.
Global Configuration Validation Checks:
 - Package Exit Code / Exit On Reboot = Checked
System State Validation Checks:
 Reboot Requirement Checks:
 - Pending Computer Rename = Checked
 - Pending Component Based Servicing = Checked
 - Pending Windows Auto Update = Checked
 - Pending File Rename Operations = Ignored
 - Pending Windows Package Installer = Checked
 - Pending Windows Package Installer SysWow64 = Checked
The source 'https://licensedpackages.chocolatey.org/api/v2/;https://chocolatey.org/api/v2/' evaluated to a 'normal' source type

NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
Configuration: MaximumDownloadRateBitsPerSecond='0'|
MaximumDownloadRateBitsPerSecondAutoSet='False'|
LicensedInformation.LicenseType='Professional'|
LicensedInformation.LicenseIsValid='True'|
LicensedInformation.LicenseIsTrial='False'|
LicensedInformation.PauseInTrial='False'|
LicensedInformation.LicenseUserName='xxxxxxxx(I removed this for privacy)'|

LicensedInformation.LicenseExpirationDate='3/6/2021 12:00:00 AM'|
LicensedInformation.LicensedVersion='2.1.1.0'|
ChocolateyVersion.Version='0.10.15.0'|
ChocolateyVersion.PackageReleaseVersion='0'|
LicensedFeatures.UseDownloadCache='True'|
LicensedFeatures.AllowSynchronization='True'|
LicensedFeatures.UseBackgroundService='False'|
LicensedFeatures.UseBackgroundServiceWithSelfServiceSourcesOnly='False'|

LicensedFeatures.UseBackgroundServiceWithNonAdministratorsOnly='False'|
LicensedFeatures.UseBackgroundServiceInteractively='False'|
LicensedFeatures.UseBackgroundServiceWithEmptySessions='False'|
LicensedFeatures.AllowBackgroundServiceUninstallsFromUserInstallsOnly='False'|

LicensedFeatures.AllowPreviewFeatures='False'|
LicensedFeatures.ShowAllPackagesInProgramsAndFeatures='False'|
LicensedFeatures.AdminOnlyExecutionForAllChocolateyCommands='False'|
LicensedFeatures.AdminOnlyExecutionForNewCommand='False'|
LicensedFeatures.AdminOnlyExecutionForDownloadCommand='False'|
LicensedFeatures.ReduceInstalledPackageSize='True'|
LicensedFeatures.ReduceOnlyNupkgSize='False'|
LicensedFeatures.UseLocalSystemForServiceInstalls='False'|
LicensedFeatures.WarnOnUpcomingLicenseExpiration='False'|
LicensedFeatures.UseChocolateyCentralManagement='False'|
LicensedFeatures.UseChocolateyCentralManagementDeployments='False'|
LicensedNewCommand.UseOriginalFilesLocation='False'|
LicensedNewCommand.PauseOnError='False'|
LicensedNewCommand.BuildPackage='False'|
LicensedNewCommand.GeneratePackagesFromSoftwareInstalls='False'|
LicensedNewCommand.IncludeArchitectureInPackageId='False'|
LicensedNewCommand.GenerateForCommunityUse='False'|
LicensedDownloadCommand.Internalize='False'|
LicensedDownloadCommand.AppendUseOriginalLocation='False'|
LicensedDownloadCommand.InternalizeAnyUrlFound='False'|
LicensedDownloadCommand.DownloadInstalledPackages='False'|
LicensedDownloadCommand.IgnoreUnfoundPackages='False'|
LicensedListCommand.ShowAuditInformation='False'|
LicensedListCommand.ShowDisplayVersion='False'|
LicensedUninstallCommand.FromProgramsAndFeatures='False'|
VirusConfiguration.VirusCheckMinimumPositives='4'|
VirusConfiguration.VirusScannerType='VirusTotal'|
VirusConfiguration.GenericVirusScannerArgs='[[File]]'|
VirusConfiguration.GenericVirusScannerValidExitCodes='0'|
VirusConfiguration.GenericVirusScannerTimeoutInSeconds='120'|
CommandName='upgrade'|
CacheLocation='C:\Users\xxxxxxxx(I removed this for privacy)\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://licensedpackages.chocolatey.org/api/v2/;https://chocolatey.org/api/v2/'|

SourceType='normal'|Debug='True'|Verbose='True'|Trace='False'|
Force='False'|Noop='False'|HelpRequested='False'|
UnsuccessfulParsing='False'|RegularOutput='True'|QuietOutput='False'|
PromptForConfirmation='False'|AcceptLicense='True'|
AllowUnofficialBuild='False'|Input='ruby'|AllVersions='False'|
SkipPackageInstallProvider='False'|PackageNames='ruby'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.19042.0'|
Information.PlatformName='Windows 10'|
Information.ChocolateyVersion='0.10.15.0'|
Information.ChocolateyProductVersion='0.10.15'|
Information.FullName='choco, Version=0.10.15.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='febrenna'|Information.UserDomainName='ANT'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='True'|
Information.LicenseType='Professional'|
Information.CurrentDirectory='C:\Windows\System32'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='True'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='True'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='True'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='False'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
ApiKeyCommand.Remove='False'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|Proxy.BypassOnLocal='True'|
_ Chocolatey:ProChocolateyUpgradeCommand - Normal Run Mode _
Upgrading the following packages:
ruby
By upgrading you accept licenses for the packages.
Resolving reference to chocolatey.licensed...
Using 'https://licensedpackages.chocolatey.org/api/v2/'.
- Supports prereleases? 'False'.
- Is ServiceBased? 'True'.
Using 'https://chocolatey.org/api/v2/'.
- Supports prereleases? 'True'.
- Is ServiceBased? 'True'.
Package 'ruby' found on source 'https://chocolatey.org/api/v2/'

You have ruby v2.7.2.1 installed. Version 3.0.0.1 is available based on your source(s).
ruby - Adding remembered arguments for upgrade:  --cache-location="'C:\Users\xxxxxxxx(I removed this for privacy)\AppData\Local\Temp\chocolatey'"
Backing up existing ruby prior to operation.
Moving 'C:\ProgramData\chocolatey\lib\ruby'
 to 'C:\ProgramData\chocolatey\lib-bkp\ruby'
Attempting to create directory "C:\ProgramData\chocolatey\lib\ruby".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ruby\ruby.nupkg"
 to "C:\ProgramData\chocolatey\lib\ruby\ruby.nupkg".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ruby\ruby.nuspec"
 to "C:\ProgramData\chocolatey\lib\ruby\ruby.nuspec".
Attempting to create directory "C:\ProgramData\chocolatey\lib\ruby\legal".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ruby\legal\LICENSE.txt"
 to "C:\ProgramData\chocolatey\lib\ruby\legal\LICENSE.txt".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ruby\legal\VERIFICATION.txt"
 to "C:\ProgramData\chocolatey\lib\ruby\legal\VERIFICATION.txt".
Attempting to create directory "C:\ProgramData\chocolatey\lib\ruby\tools".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ruby\tools\chocolateyInstall.ps1"
 to "C:\ProgramData\chocolatey\lib\ruby\tools\chocolateyInstall.ps1".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ruby\tools\rubyinstaller-2.7.2-1-x64_x64.exe.ignore"
 to "C:\ProgramData\chocolatey\lib\ruby\tools\rubyinstaller-2.7.2-1-x64_x64.exe.ignore".
Deleting file C:\ProgramData\chocolatey\lib\ruby\tools\chocolateyInstall.ps1
Attempting to delete file "C:\ProgramData\chocolatey\lib\ruby\tools\chocolateyInstall.ps1".
Capturing package files in 'C:\ProgramData\chocolatey\lib\ruby'
 Found 'C:\ProgramData\chocolatey\lib\ruby\ruby.nupkg'
  with checksum '638F8B17A12994FDC519B98B5D8BF891'
 Found 'C:\ProgramData\chocolatey\lib\ruby\ruby.nuspec'
  with checksum '1A8E7FB352437BFFB90644A7807BD325'
 Found 'C:\ProgramData\chocolatey\lib\ruby\legal\LICENSE.txt'
  with checksum 'DAFD6B74A417987376F810C3AA5C69C3'
 Found 'C:\ProgramData\chocolatey\lib\ruby\legal\VERIFICATION.txt'
  with checksum '2D4EC07D2CED75C143B49F70406A7171'
 Found 'C:\ProgramData\chocolatey\lib\ruby\tools\rubyinstaller-2.7.2-1-x64_x64.exe.ignore'
  with checksum 'ECAA88F7FA0BF610A5A26CF545DCD3AA'
Attempting to delete file "C:\ProgramData\chocolatey\lib\ruby\tools\rubyinstaller-2.7.2-1-x64_x64.exe.ignore".
[NuGet] Attempting to resolve dependency 'chocolatey-core.extension (≥ 1.3.3)'.
[NuGet] Attempting to resolve dependency 'chocolatey (≥ 0.10.5)'.
ruby not upgraded. An error occurred during installation:
 Updating 'chocolatey 0.10.15' to 'chocolatey 0.10.13' failed. Unable to find a version of 'chocolatey.extension' that is compatible with 'chocolatey 0.10.13'.
ruby package files upgrade completed. Performing other installation steps.
Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\ruby.3.0.0.1\.arguments".
Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\ruby.3.0.0.1\.extra".
Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\ruby.3.0.0.1\.version".
Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\ruby.3.0.0.1\.sxs".
Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\ruby.3.0.0.1\.pin".
Attempting to delete directory "C:\ProgramData\chocolatey\lib-bad\ruby".
Sending message 'HandlePackageResultCompletedMessage' out if there are subscribers...
The upgrade of ruby was NOT successful.
ruby not upgraded. An error occurred during installation:
 Updating 'chocolatey 0.10.15' to 'chocolatey 0.10.13' failed. Unable to find a version of 'chocolatey.extension' that is compatible with 'chocolatey 0.10.13'.
Moving 'C:\ProgramData\chocolatey\lib\ruby'
 to 'C:\ProgramData\chocolatey\lib-bad\ruby'
Attempting rollback
Moving 'C:\ProgramData\chocolatey\lib-bkp\ruby'
 to 'C:\ProgramData\chocolatey\lib\ruby'

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - ruby (exited 1) - ruby not upgraded. An error occurred during installation:
 Updating 'chocolatey 0.10.15' to 'chocolatey 0.10.13' failed. Unable to find a version of 'chocolatey.extension' that is compatible with 'chocolatey 0.10.13'.
Sending message 'PostRunMessage' out if there are subscribers...
[Countdown] Determining how long until license expires
Exiting with 1

**Comment by pauby** [comment]
The issue here is that `chocolatey.extension` requires Chocolatey version 0.10.5. If you downgrade to Chocolatey 0.10.3 then it stops you as that would break the dependency for `chocolatey.extension`.

Since you are a customer, my suggestion would be to reach out to support who can help understand why you need to downgrade and help you with the dependency issue. To find out your support options run `choco support`.

**Comment by gep13** [comment]
Since there hasn't been any response on this issue, I am going to go ahead and close it out.  If you are still having issues, please feel free to reach out.
