### ISSUE TITLE
Upgrade of keepass failed but registered new version

### ISSUE THREAD

**Issue by mwisnicki** [chocolatey/choco#2177]
### What You Are Seeing?
Short version is that keepass failed to upgrade yet the new version was registered in choco database and I had to force upgrade.

```
PS C:\WINDOWS\system32> choco outdated
Chocolatey v0.10.15
Outdated Packages
 Output is package name | current version | available version | pinned?

adobereader|2020.013.20066|2020.013.20074|false
crystaldiskmark|7.0.0.104|8.0.0.97|false
doublecmd|0.9.9|0.9.10|false
git|2.29.2.2|2.30.0.2|false
git.install|2.29.2.2|2.30.0.2|false
keepass|2.46|2.47|false
keepass.install|2.46|2.47|false
magicsplat-tcl-tk|1.10.1.20201009|1.11.0|false
notepadplusplus.install|7.9.1|7.9.2|false
procexp|16.32.0.20200919|16.32.0.20210111|false
procmon|3.60|3.61|false
sqlitebrowser|3.12.0|3.12.0.20201129|false
sqlitebrowser.install|3.12.0|3.12.0.20201129|false
zoom|5.4.58891.1115|5.4.59931.0110|false

Chocolatey has determined 14 package(s) are outdated.
```

```
PS C:\WINDOWS\system32> choco upgrade all
# skip irrelevant logs
You have keepass v2.46 installed. Version 2.47 is available based on your source(s).
Progress: Downloading keepass.install 2.47... 100%
Progress: Downloading keepass 2.47... 100%

keepass.install v2.47 [Approved]
keepass.install package files upgrade completed. Performing other installation steps.
Installing keepass.install...
ERROR: Running ["C:\ProgramData\chocolatey\lib\keepass.install\tools\KeePass-Setup.exe" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- ] was not successful. Exit code was '1'. See log for possible error messages.
The upgrade of keepass.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyInstall.ps1'.
 See log for details.

keepass v2.47 [Approved]
keepass package files upgrade completed. Performing other installation steps.
 The upgrade of keepass was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.
keepass-kpentrytemplates v1.8.0.20190608 is the latest version available based on your source(s).
keepass-plugin-keeautoexec v2.4.0.20200422 is the latest version available based on your source(s).
keepass-plugin-winkee v2.39.1 is the latest version available based on your source(s).
keepass.install is not installed. Installing...

keepass.install v2.47 [Approved]
keepass.install package files upgrade completed. Performing other installation steps.
Installing keepass.install...
ERROR: Running ["C:\ProgramData\chocolatey\lib\keepass.install\tools\KeePass-Setup.exe" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- ] was not successful. Exit code was '1'. See log for possible error messages.
The upgrade of keepass.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyInstall.ps1'.
 See log for details.
```

The installed version is still 2.46 at this point yet Choco thinks otherwise

```
PS C:\WINDOWS\system32> choco upgrade keepass
Chocolatey v0.10.15
Upgrading the following packages:
keepass
By upgrading you accept licenses for the packages.
keepass v2.47 is the latest version available based on your source(s).

Chocolatey upgraded 0/1 packages.
```

```
PS C:\WINDOWS\system32> choco upgrade all
Chocolatey v0.10.15
Upgrading the following packages:
all
#...
KB3035131 v1.0.3 is the latest version available based on your source(s).
keepass v2.47 is the latest version available based on your source(s).
keepass-kpentrytemplates v1.8.0.20190608 is the latest version available based on your source(s).
keepass-plugin-keeautoexec v2.4.0.20200422 is the latest version available based on your source(s).
keepass-plugin-winkee v2.39.1 is the latest version available based on your source(s).
magicsplat-tcl-tk v1.11.0 is the latest version available based on your source(s).
#...

Chocolatey upgraded 0/48 packages.
```

### What is Expected?
If package installation fails then package should stay at old version.

### How Did You Get This To Happen? (Steps to Reproduce)
```
choco upgrade all
```

### Output Log

https://gist.github.com/mwisnicki/284aa0a5168dc120c03b4ef88d7a9bdf

**Comment by pauby** [comment]
@mwisnicki This could simply be a package issue. The installer is exiting with code 1, which to it may mean it's installed successfully but Chocolatey sees it as an error (as it's not an error code that usually means success and it hasn't been told otherwise).

I maintain that package so can I ask you to raise an issue at the [GitHub repository](https://github.com/pauby/chocopackages/issues) and I can take a look at it in the first instance?

**Comment by mwisnicki** [comment]
@pauby but since Chocolatey sees the error wouldn't that make it an issue in Chocolatey itself?

**Comment by pauby** [comment]
There are two packages for keepass - `keepass` and `keepass.install`. `keepass` looks like it upgraded successfully. `keepass.install` failed. 

`keepass.install` isn't listed in your last output, but that may have been missed - is it there as version 2.47?

**Comment by mwisnicki** [comment]
You're right, it's possible that keepass.install stayed at 2.46 although too late to check.
I can see keepass.install in the output of `choco list -lo` now but it wasn't picked up by `choco upgrade all` when I ran it back then.
I had to invoke `choco upgrade keepass --force` so there's definitely something very user unfriendly going on still.

**Comment by mwisnicki** [comment]
> > something very user unfriendly going on still.
> 
> Can you elaborate on that?

As a user I expect `choco upgrade` to upgrade all my software.

**Comment by pauby** [comment]
Just to clear up the terminology, and I know it's nitpicking but important. Chocolatey doesn't upgrade your _software_. Chocolatey upgrades _packages_.

And in this case it tried to but failed. This is likely the packages fault but hasn't yet been determined.

**Comment by pauby** [comment]
Nothing will overwrite files that are in use so Chocolatey would be the same. 

There was an issue with Keepass a few package versions ago that it would fail to upgarde if Keepass was running. Later versions closed Keepass before the upgrade.

**Comment by ferventcoder** [comment]
I'm going to close this as a package issue, not something with Chocolatey itself. We already have things on the backlog about shutting down applications that are running as a core thing that Chocolatey should do. For now we've left it to the package itself to handle and the package doesn't seem to be handling this.
