### ISSUE TITLE
Add feature of "Manual install by user" if auto install fails for any reason.

### ISSUE THREAD

**Issue by umarabdullahmansoori** [chocolatey/choco#2183]
Chocolatey packages fails many times due to different reasons, therefor anyone cannot fully rely on them. If package installation fails, user downloads same program from google and install it manually.

So, my suggestion is:  if chocolatey fails to install package, it run the downloaded exe file itself so user will manually install it easily (instead of going to web and download it).

**Comment by pauby** [comment]
Chocolatey is meant to allow package installation silently and reliably. The failure of the packages to install, as you said can be for many different reasons, two of the most common are:

* Invalid checksums - the checksum in the package no long matches the installer checksum (the installer may have been updated but the version hasn't (happens _a lot_) or here is only one installer and each package uses the same one);
* Installer not available - the installer download location may have been moved, that particular version removed or it may be down;

In those cases you're right that a package may fail to install.

However, prompting the user to do install manually is no different from them downloading and installing the software themselves. It seems counterintuitive for a package manager to then prompt the user to download and install the software manually and no other package manager (that I'm aware of) has this feature.

**Comment by umarabdullahmansoori** [comment]
> Chocolatey is meant to allow package installation silently and reliably. The failure of the packages to install, as you said can be for many different reasons, two of the most common are:
> 
> * Invalid checksums - the checksum in the package no long matches the installer checksum (the installer may have been updated but the version hasn't (happens _a lot_) or here is only one installer and each package uses the same one);
> * Installer not available - the installer download location may have been moved, that particular version removed or it may be down;
> 
> In those cases you're right that a package may fail to install.
> 
> However, prompting the user to do install manually is no different from them downloading and installing the software themselves. It seems counterintuitive for a package manager to then prompt the user to download and install the software manually and no other package manager (that I'm aware of) has this feature.

My point is that user will have to:
1. Check that program is installed or not
2. If not then take extra time to go to google, then to download website, then download and open installer

Instead chocolatey open installer itself if failed

**Comment by pauby** [comment]
@umarabdullahmansoori I'm not sure I understand your response.

Are you suggesting that if the install fails via Chocolatey that Chocolatey then runs the installer non-silently for the user to interact with?

**Comment by vexx32** [comment]
Chocolatey is used in a lot of automated task contexts, where such a feature would very much break the automation. Failures can be handled automatically, tasks rerun, etc., but if Chocolatey were to start invoking installers in interactive mode, there's a good chance it would just stall the tasks indefinitely instead.

At the very least, Chocolatey would never be able to do this by default IMO.

**Comment by umarabdullahmansoori** [comment]
> @umarabdullahmansoori I'm not sure I understand your response.
> 
> Are you suggesting that if the install fails via Chocolatey that Chocolatey then runs the installer non-silently for the user to interact with?

yes

**Comment by pauby** [comment]
@umarabdullahmansoori As Chocolatey silently installs the software intentionally, it is used not only for home users but also for organizations updating hundreds to thousands of computers, in CI / CD pipelines and many other areas that cannot have interaction.

Installing software interactively for the user can be done by the user manually downloading and installing it.

See [How Chocolatey Works](https://chocolatey.org/how-chocolatey-works).

**Comment by AdmiringWorm** [comment]
> Installing software interactively for the user can be done by the user manually downloading and installing it.

and it can also be done through chocolatey by passing in the `--notsilent` argument (just for information).

**Comment by pauby** [comment]
I'm going to go ahead and close this, but we can reopen it if necessary.
