### ISSUE TITLE
Read-Host halts scripts rather than prompt for input

### ISSUE THREAD

**Issue by ShaneIsrael** [chocolatey/choco#219]
What I have noticed happens when trying to add a Read-Host to my chocolateyInstall.ps1 is that it just stops the script on the Read-Host line and in the console displays the blinking underscore. However if you go to type, nothing shows up and you have to force exit the script.

For example, I had something like this:
$createShortcuts = Read-Host "Would you like shortcuts to be created? y/n"

This was just an added configuration step I was going to provide to the user as some people with my tool may or may not want shortcuts created. When testing that line in PowerShell it works like it should, but when running it through a script in Chocolatey it would seem output is being re-directed.

**Comment by ferventcoder** [comment]
Did this work on older choco versions? if so I will tag this with Feature Parity

**Comment by ferventcoder** [comment]
This is related to #8

**Comment by ShaneIsrael** [comment]
I am unsure if it worked on older versions. I have only ever had the latest release v0.9.9.2 I believe? This is also my first package I have been working at getting approved so my experience with choco has only been with v0.9.9.2.

**Comment by ferventcoder** [comment]
Ah right on. I think it did. I have packages that would sort of prompt (they had a default choice with a timeout) and I think they worked

**Comment by ferventcoder** [comment]
Or not, they did read-host - https://github.com/ferventcoder/chocolatey-packages/blob/master/manual/dropkick.dev/tools/chocolateyInstall.ps1

**Comment by ferventcoder** [comment]
Think I got all of it right.

**Comment by ShaneIsrael** [comment]
So then this is a bug? or was I just not going about it correctly?

**Comment by ferventcoder** [comment]
Bug, Feature parity issue - is it high need or can it wait until I can implement with #8? I was working on that this morning and should have a beta coming out in the next couple of weeks that will have that in it.

**Comment by ShaneIsrael** [comment]
It's not a high need at all. It's something that could be added in my next release which will probably be a couple weeks to a month after this first package gets through moderation.

**Comment by The1nternet** [comment]
This is an extremely urgent issue for me.  All of our current private packages are broken until this is resolved.

**Comment by donaldr** [comment]
For me as well. Is it possible to install concurrent versions of chocolatey? I have included a dependencies in the nuspec for my package that points to a specific version of chocolatey, but since I already have chocolatey installed it doesn't seem to work.

**Comment by ferventcoder** [comment]
@donaldr no, but it is possible to install the older version of choco if you need that. See https://github.com/chocolatey/chocolatey.org/issues/162

**Comment by The1nternet** [comment]
Is there like an update on this issue and such as?

**Comment by ferventcoder** [comment]
Posh hosting is what I'm working on currently. Once that is done we should have beta builds of 0.9.10 with this in it. Once those are available, We can start testing what else is needed to make sure this works.

**Comment by ferventcoder** [comment]
Looks like this is going to be fixed in 0.9.9.8.

**Comment by ferventcoder** [comment]
I'm seeing other fun possible issues but this is now working for me.

**Comment by ferventcoder** [comment]
Bonus #56 is also working again.
