### ISSUE TITLE
For the color challanged

### ISSUE THREAD

**Issue by theking2** [chocolatey/choco#2199]
I have a eye defictiency and cannot read the Failure messages, as what I believe they are. Please add a gray scale color scheme to the CLI

**Comment by ferventcoder** [comment]
@theking2 There are some options already available. 

- You change the background, it changes the color output (this is automatic)
- You can provide your own color scheme. Takes some work but there is an example at #100 
- Turn off colors - see #100

**Comment by theking2** [comment]
turning off colors is not really the solution. Please observe the colors set by the user.

**Comment by pauby** [comment]
This may come out of #2773 (or something similar).

We wouldn't be looking to implement this separately.

> turning off colors is not really the solution.

That wasn't the only option suggested above.

I'm going to go ahead and close this again. We can always reopen it again if necessary.
