### ISSUE TITLE
Set up Travis CI yaml

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#22]
Official docs http://docs.travis-ci.com/user/languages/csharp/

Some references that are likely outdated (but might prove helpful):

 *  http://stackoverflow.com/a/16751773/18475 
 * http://pseudomuto.com/development/walkthroughs/2013/08/13/continuous-integration-for-net-with-travis-ci-and-xunit/
 * https://danlimerick.wordpress.com/2013/02/03/build-your-open-source-net-project-on-travis-ci/

**Comment by gep13** [comment]
For this one, do you already have a Travis account that you want the build to run under?  If so, can you make others in the team have access?  I have never looked at Travis, but more than happy to look at this.

**Comment by ferventcoder** [comment]
I do have a travis account. This would use mono to build. There are some examples of doing this out there.

**Comment by ferventcoder** [comment]
Just turned it on https://travis-ci.org/chocolatey/choco/

**Comment by gep13** [comment]
Nice one!  I will take a look.  Will have some reading to do for this one :smile_cat:

**Comment by gep13** [comment]
Have you given me any sort of permissions to the Travis site?  I don't see anything immediately that says to create a new build configuration?

**Comment by ferventcoder** [comment]
Here's a pretty comprehensive answer http://stackoverflow.com/a/16751773/18475 - note we already have `./build.sh` so we don't need to call xbuild directly.

**Comment by ferventcoder** [comment]
You create a `.travis.yml` file. It's that simple. Travis-CI is considered the first zero configuration build server.

**Comment by gep13** [comment]
ooo, interesting, didn't realise that. Cool, I will let you know if I have any questions.

**Comment by ferventcoder** [comment]
And another nice found story - http://pseudomuto.com/development/walkthroughs/2013/08/13/continuous-integration-for-net-with-travis-ci-and-xunit/

**Comment by ferventcoder** [comment]
Even an example to get started with https://github.com/pseudomuto/travis-ci-demo/blob/master/.travis.yml

**Comment by ferventcoder** [comment]
Official docs http://docs.travis-ci.com/user/languages/csharp/

**Comment by ferventcoder** [comment]
The last is preferred, it's the most recent and likely the easiest to test.

**Comment by gep13** [comment]
@ferventcoder I have added a VERY basic travis.yml file into chocolatey/choco and issued it as a pull request, thinking that this would kick off a build in travis.  However, nothing seems to be happening.  Am I right in thinking that the file will need to exist on the master branch, before travis knows what to do with it, or rather, than it "should" be doing something?

**Comment by ferventcoder** [comment]
I left a comment over there for you. The name of the file must start with a dot.`
