### ISSUE TITLE
Feature Request - Selfupdate Flag in Package Properties

### ISSUE THREAD

**Issue by kevinholtkamp** [chocolatey/choco#2202]
It would be really helpful if a package creator could set a flag if the program updates itself, which would "pin" the package by default.
Example: Google Chrome updates itself, so i don't want it to be updated with `choco upgrade all`

**Comment by TheCakeIsNaOH** [comment]
This seems to be a duplicate of https://github.com/chocolatey/choco/issues/1607

**Comment by kevinholtkamp** [comment]
You're right, thank you!
