### ISSUE TITLE
config - Set Minimum Security Protocol

### ISSUE THREAD

**Issue by karthik6402** [chocolatey/choco#2206]
It would be great if there is an option to set what protocol the choco client tool should use when doing an install or update.
Currently the server rejects any TLS1.2 connection but there is a connection that is already sent out from the choco client tool which could lead to some Man in the middle attack. The following line shows the configuration supports TLS1.1 and TLS1.2
https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure/registration/SecurityProtocol.cs#L39
It could help resolve some security issues.
Thank you

**Comment by ferventcoder** [comment]
Thanks for adding this. I've added it to the backlog targeting a 0.10.x release. I've also marked it up for grabs for folks that would like to create a PR that goes along these lines - if you are reading this and are interested in providing something, please comment on the ticket first so we can talk about best implementation before you move to create a pull request.

**Comment by karthik6402** [comment]
Hi, I will work on this change and create a PR. Thank you

**Comment by karthik6402** [comment]
Hi, I will work on this change.

I am planning on adding an extra configuration in the config file as below.

key="allowedSecurityProtocols" 
value="ssl3,tls,tls11,tls12" 
description="A comma-separated list of security protocols to be allowed in the communication to the package manager server ex. tls11,tls12,ssl3"



based on the value the protocols will be assigned at runtime. If the list is empty it is will set to default value as how it is now, which is "tls12,tls11,tls,ssl3"

please let me know, if you think of any other options.
Thank you

**Comment by karthik6402** [comment]
I have updated the changes as mentioned in the comments.

**Comment by gep13** [comment]
@karthik6402 as I mentioned in the PR that you created for this issue, the decision has been taken to not move forward with this suggested change.  Instead, Chocolatey CLI is switching to make use of the Default setting that has been set at the Operating System level.  More information can be found on the comment on this [PR](https://github.com/chocolatey/choco/pull/2730#issuecomment-1552847946).
