### ISSUE TITLE
Pinning/unpinning should also disable/enable autoupdate functionality in installed packages

### ISSUE THREAD

**Issue by legowerewolf** [chocolatey/choco#2213]
Lots of software nowadays comes with autoupdate functionality. Chocolatey should provide a way for pinning/unpinning to run a package-defined script to disable and enable autoupdating, thus allowing users to pin versions and be *sure* that the software won't try to update itself.

**Comment by SlugFiller** [comment]
I would argue that auto-update on the software's side should be disabled whenever possible, regardless of whether it's pinned or not. At the very least, if a software updates on its own, there's a risk Chocolatey may not detect the update, and later have trouble installing its own update. As a rule of thumb, most packages strive to be like that, but this is not always possible to achieve.
