### ISSUE TITLE
CUDA 11.2 installation fails

### ISSUE THREAD

**Issue by eyalroz** [chocolatey/choco#2214]
I'm using choco 0.10.15 and ChocolateyGUI 0.16.0.

I have repeatedly tried and failed to upgrade the CUDA package on my (Windows 10) system, from v10.2 to v11.2.

The installation starts with the following console lines:
```
Using system proxy server 'pitc-zscaler-global-zen.proxy.corporate.ge.com'.
Downloading cuda 
  from 'https://developer.download.nvidia.com/compute/cuda/11.2.2/local_installers/cuda_11.2.2_461.33_win10.exe'
Using system proxy server 'pitc-zscaler-global-zen.proxy.corporate.ge.com'.

Download of cuda_11.2.2_461.33_win10.exe (2.71 GB) completed.
WARNING: Ignoring checksums due to feature checksumFiles turned off or option --ignore-checksums set.
Installing cuda...
```
so far so good; but then it fails. The message box tells me:

> **Failed to update package.**
> 
> Failed to update package "cuda".
> 
> Error:
> 
> You have cuda v10.2.89.20191206 installed. Version 11.2.2.46133 is available based on your source(s).
> WARNING: Ignoring checksums due to feature checksumFiles turned off or option --ignore-checksums set.
> ERROR: Running ["C:\Users\503156516\AppData\Local\Temp\chocolatey\cuda\11.2.2.46133\cuda_11.2.2_461.33_win10.exe" /s ] was not
> successful. Exit code was '-522190759". See log for possible error messages.
> 
> Environment Vars (like PATH) have changed. Close/reopen your shell to
> see the changes (or in powershell/cmd.exe just type ‘refreshenv).
> The upgrade of cuda was NOT successful.
> 
> Error while running 'C:\ProgramData\chocolatey\lib\cuda\tools\chocolateyinstall.ps1'.
> 
> See log for details.
> 
> Chocolatey upgraded 0/1 packages. 1 packages failed.
> 
> See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> 
> Failures
> 
> - cuda (exited -522190759) - Error while running 'C:\ProgramData\chocolatey\lib\cuda\tools\chocolateyinstall.ps1'.
> See log for details.
> 
> Did you know the proceeds of Pro (and some proceeds from other
> licensed editions) go into bettering the community infrastructure?
> Your support ensures an active community, keeps Chocolatey tip top,
> plus it nets you some awesome features!
> 
> https://chocolatey.org/compare

I don't know that there's anything that should cause this failure; nor do I understand the exit code. The two log files mentioned don't contain anything regarding CUDA installation, so no help there.

Now, it's possible that this issue should not be reported here, if the problem is with the package itself. But I'm not even sure it's the package that's the problem, or something else. So feel free to close.

**Comment by eyalroz** [comment]
I should also mention that manually downloading and installing the CUDA executable listed on the console - succeeds (though that is an interactive install).

**Comment by morphogencc** [comment]
I've run into the exact same error; I've tried everything and haven't figured out a solution yet.

**Comment by pauby** [comment]
@eyalroz as mentioned in the issue template, this looks to be an issue with the package, and not with Chocolatey itself. In a Windows 10 sandbox I installed version 10.2.89.20191206 of `cuda`:

```
PS C:\Users\WDAGUtilityAccount> choco install cuda --version 10.2.89.20191206
Chocolatey v0.10.15
Installing the following packages:
cuda
By installing you accept licenses for the packages.
Progress: Downloading cuda 10.2.89.20191206... 100%

cuda v10.2.89.20191206 [Approved]
cuda package files install completed. Performing other installation steps.
Downloading cuda
  from 'https://developer.download.nvidia.com/compute/cuda/10.2/Prod/local_installers/cuda_10.2.89_441.22_win10.exe'
Progress: 100% - Completed download of C:\Users\WDAGUtilityAccount\AppData\Local\Temp\chocolatey\cuda\10.2.89.20191206\cuda_10.2.89_441.22_win10.exe (2.44 GB).
Download of cuda_10.2.89_441.22_win10.exe (2.44 GB) completed.
Hashes match.
Installing cuda...
cuda has been installed.
  cuda may be able to be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of cuda was successful.
  Software installed to 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2'

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

I then upgraded to version 11.2.2.46133:

```
PS C:\Users\WDAGUtilityAccount> choco upgrade cuda --version 11.2.2.46133
Chocolatey v0.10.15
Upgrading the following packages:
cuda
By upgrading you accept licenses for the packages.

You have cuda v10.2.89.20191206 installed. Version 11.2.2.46133 is available based on your source(s).
Progress: Downloading cuda 11.2.2.46133... 100%

cuda v11.2.2.46133 [Approved]
cuda package files upgrade completed. Performing other installation steps.
Downloading cuda
  from 'https://developer.download.nvidia.com/compute/cuda/11.2.2/local_installers/cuda_11.2.2_461.33_win10.exe'
Progress: 100% - Completed download of C:\Users\WDAGUtilityAccount\AppData\Local\Temp\chocolatey\cuda\11.2.2.46133\cuda_11.2.2_461.33_win10.exe (2.71 GB).
Download of cuda_11.2.2_461.33_win10.exe (2.71 GB) completed.
Installing cuda...
cuda has been installed.
  cuda may be able to be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The upgrade of cuda was successful.
  Software installed to 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2'

Chocolatey upgraded 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

Without any issue.

Best suggestion would be to reach out to the package maintainer via the links on the [package page](https://community.chocolatey.org/packages/cuda).

I will go ahead and close this off.

**Comment by eyalroz** [comment]
I put up a comment on [the package page](https://community.chocolatey.org/packages/cuda), let's see what happens.
