### ISSUE TITLE
Allow -source of `choco push` to use source names as Input

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/choco#2219]
## Description

Allow the `-source` switch of the `choco push` command to accept source names as input. Currently the source switch only accepts URLs as input.

**Comment by TheCakeIsNaOH** [comment]
Isn't this a duplicate of #63?

**Comment by ryanrichter94** [comment]
@TheCakeIsNaOH This is indeed a duplicate of #63. Thanks for reaching out i'll close this issue.

**Comment by gep13** [comment]
Duplicate of #63

**Comment by gep13** [comment]
The commits that are tagged against this issue will ultimately be related to the duplicate issue linked above.
