### ISSUE TITLE
Test install package docs wrong for powershell

### ISSUE THREAD

**Issue by togakangaroo** [chocolatey/choco#222]
In the [Create Package](https://github.com/chocolatey/choco/wiki/CreatePackages) instructions under "Testing your package" it gives the powershell example

     choco install packageName -fdv -s '$pwd'

This is incorrect as `$pwd` will not be interpolated. It should not be quoted.

**Comment by ferventcoder** [comment]
Thanks, fixed!

**Comment by togakangaroo** [comment]
You actually don't need quotes at all do you?

     choco install packageName -fdv -s "$pwd"

should be identical to

     choco install packageName -fdv -s $pwd

**Comment by ferventcoder** [comment]
Quotes are not necessary, but if you add more, they would be.
