### ISSUE TITLE
Better integration with Apps & features control panel

### ISSUE THREAD

**Issue by mcandre** [chocolatey/choco#2251]
Not sure if this a problem with the Chocolatey package manager, or perhaps a specific package. But I uninstalled Visual Studio 2017 via the `Apps & features` control panel, and now `choco uninstall visualstudio2017buildtools` is broken.

As a workaround, I had to re-install the package as far as Chocolatey was concerned, and only then would `choco uninstall visualstudio2017buildtools` finally succeed.

**Comment by steviecoaster** [comment]
This is a licensed feature. In Chocolatey For Business AutoSync tracks things removed via Programs and Features, and automatically removes the Chocolatey Package for the application. In FOSS Chocoaltey you can pass `--skipautouninstaller` to the `choco uninstall` command to remove a package after removing from Programs and Features manually.

**Comment by TheCakeIsNaOH** [comment]
Closing as an answered question.
