### ISSUE TITLE
Add shortcut "i" for install

### ISSUE THREAD

**Issue by CodingSpiderFox** [chocolatey/choco#2256]
Typing a lot annoys me.

Instead of "choco install -y openhardwaremonitor" I want to be able to use "choco i -y openhardwaremonitor"

**Comment by TheCakeIsNaOH** [comment]
I would suggest using `cinst` which translates to `choco install` and is available as a shim on the path.

Also, this is a duplicate of #1921

**Comment by CodingSpiderFox** [comment]
thx for the hint

**Comment by gep13** [comment]
@TheCakeIsNaOH thanks for spotting that.  I have marked this as a duplicate, and will go ahead and close this out.
