### ISSUE TITLE
Implement DefaultPushSource like nuget

### ISSUE THREAD

**Issue by bc3tech** [chocolatey/choco#228]
To save choco from removing packages on request and also save many users a lot of stress, it'd be great to have `DefaultPushSource` implemented like nuget does so users (corporate in particular) can set up the source that's pushed to when `-source` isn't given to `choco push`

http://docs.nuget.org/Consume/NuGet-Config-Defaults#sample-nugetdefaults.config

eg: `nuget config -set DefaultPushSource=http://mynuget.company.com`

**Comment by ferventcoder** [comment]
This is a duplicate of either a conversation or an issue, but I'm not finding the issue. So I'm going to likely edit this a bit.

**Comment by ferventcoder** [comment]
#62

**Comment by ferventcoder** [comment]
Let's move the conversation over there. :)

**Comment by bc3tech** [comment]
roger!
