### ISSUE TITLE
Cannot deserialize response type chocolatey.infrastructure.app.domain.Registry

### ISSUE THREAD

**Issue by telee2** [chocolatey/choco#2292]
I get  this error: Cannot deserialize response type chocolatey.infrastructure.app.domain.Registry whenever i type choco (anything) . It will list or install any package but it always display the above output. Can you please help me resolve this issue. 

Thanks

### What You Are Seeing?
 Cannot deserialize response type chocolatey.infrastructure.app.domain.Registry 
### What is Expected?
 a list of packages
### How Did You Get This To Happen? (Steps to Reproduce)
choco list -lo
### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
PLACE LOG CONTENT HERE - WE NEED _ALL_ DETAILED OUTPUT BASED ON THE ABOVE TO BE ABLE TO PROVIDE SUPPORT (YOU WILL FIND THAT IN THE $env:ChocolateyInstall\logs\chocolatey.log between the `=====`)
~~~

</p>

</details>

**Comment by vexx32** [comment]
Thanks for the report! Can you please follow the instructions from the issue template and add the information from the chocolatey.log file, if one is created?

Some details of what OS you're running and Chocolatey version would be appreciated as well. 🙂

**Comment by telee2** [comment]
Unfortunately i don't have the log file to share but basically it list the packages that are installed and then has [WARN ] Cannot deserialize response type chocolatey.infrastructure.app.domain.Registry

**Comment by telee2** [comment]
Ok I found the issue. It was the .registry files in found  located in the  ProgramData\chocolatey\.chocolatey\{appName}

**Comment by telee2** [comment]
I apologize. Im new that this.
________________________________

**Comment by ferventcoder** [comment]
Similar to #1333
