### ISSUE TITLE
How to change install location for packages?

### ISSUE THREAD

**Issue by FiftyFour7250** [chocolatey/choco#2297]
Hey guys. I'm new to Chocolatey, and I'm using Chocolatey GUI. Could you tell me please how to change the installation location of programs? For now everything is installing in C:\ I would like to change the installation path to D:\ChocolateyPrograms\

**Comment by Toadfield** [comment]
I would also like to know the same thing.

**Comment by pauby** [comment]
If this is inside Chocolatey GUI can you post the issue over [there](https://github.com/chocolatey/chocolateygui/)?

**Comment by Toadfield** [comment]
@pauby Is there a way to change the installation path where all packages get installed via the cli chocolatey?

**Comment by gep13** [comment]
It would appear that an issue has already been created with the same question:

https://github.com/chocolatey/ChocolateyGUI/issues/863

**Comment by ryanrichter94** [comment]
Closing this issue as linked issue has been solved.
