### ISSUE TITLE
Stuck at downloading

### ISSUE THREAD

**Issue by wechselgeld** [chocolatey/choco#2301]
Good morning!

I have a small problem with Chocolatey. When I type "choco install iCUE" everything goes well. After a few seconds, when Choco has downloaded about 300MB from 750, the download stops. Everything else works smoothly. I'm not sure if it's only the case with "big" packages, but small ones definitely work comparatively.

Any ideas?

**Comment by pauby** [comment]
Thanks for raising the issue. Can you go back and amend your initial comment using the template?

**Comment by gep13** [comment]
@wechselgeld since there hasn't been a response on this issue, I am going to go ahead and close it out.
