### ISSUE TITLE
[Feature Request] Being able to specify where all packages get installed

### ISSUE THREAD

**Issue by Toadfield** [chocolatey/choco#2306]
It is so dumb that all the packages get installed in program files or program files (x86) cause many programs need admin priviliges then which they normally don't need.
I just want to be able to set that every package gets installed somewhere else instead.

**Comment by ryanrichter94** [comment]
Hi @Toadfield You are able to change the install directory for most packages via using the `--install-directory` switch. This is however a licensed feature for Chocolatey Pro+. [Link to feature documentation](https://docs.chocolatey.org/en-us/features/install-directory-override).
