### ISSUE TITLE
Please release chocolatey with updated nuget-chocolatey

### ISSUE THREAD

**Issue by zivkan** [chocolatey/choco#2315]
Customers using both of our products are still experiencing problems, which was reported in https://github.com/chocolatey/choco/issues/2233. That issue was closed 3 months ago (from this fix https://github.com/chocolatey/nuget-chocolatey/pull/24), but customers setting up new machines are still encountering the problem.

Looking at the release history, 0.10.15 was released in June 2019, and a beta of 0.10.16 was released in August 2020. If 0.10.16 isn't ready for a GA release, is it feasible to bump its version to 0.10.17-beta, and then release 0.10.15 + updated nuget-chcolatey as 0.10.16?

**Comment by zivkan** [comment]
Here's the latest example of a customer affected: https://github.com/NuGet/Home/issues/11141

**Comment by pauby** [comment]
@zivkan Chocolatey 0.10.16 will be released soon with this fix. I'm going to go ahead and close this but in the meantime, please use the issues template for any issues you create.
