### ISSUE TITLE
The windows 11 intellisense does not work

### ISSUE THREAD

**Issue by rifaterdemsahin** [chocolatey/choco#2320]
Assuming it was a ale to configure itself on installation, there should be tab completion for the available chocolatey commands and options. What happens if you type "choco in" and then hit tab?

^^^ this does not work and I do not get intellisense

Here is all the details with screenshots
https://twitter.com/gep13/status/1428938712726056960

**Comment by corbob** [comment]
I'm not seeing tab completion issues on Windows 11 once I've ensured that I've imported the Profile (or just Tab completion) module with: `Import-Module C:\ProgramData\Chocolatey\helpers\chocolateyProfile.psm1`. Are you importing the module? Is your profile configured already to import the module?

**Comment by gep13** [comment]
@rifaterdemsahin I recently personally verified that this is working as expected, and I recorded this as two short videos.  The first:

https://youtu.be/jdZrigvxwws

walks through the complete process of setting up tab completion. 

The second, shows the same thing (including the installation) on Windows 11:

https://youtu.be/lBN1Rn15L2A

As such, I am going to go ahead and close this issue.  Feel free to reach out if you are still having problems.
