### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by imatchick** [chocolatey/choco#2321]
I am trying to install mingw but failed.
With the error message:
"ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/ray_linn/GCC-10.X-with-ada/GCC-10.2.0-crt-8.0.0-with-ada-20201019.7z/download'. Exception calling "GetResponse" with "0" argument(s): "The operation has timed out"
The install of mingw was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\mingw\tools\chocolateyinstall.ps1'.
 See log for details."
Failures
 - mingw (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\mingw\tools\chocolateyinstall.ps1'.
 See log for details.

Thanks.

**Comment by corbob** [comment]
This looks like it might be an issue with the mingw package, or perhaps an issue with SourceForge serving up the file. I'm not getting a 404 when I try to install mingw on my test systems.

**Comment by gep13** [comment]
Closing due to lack of response.
