### ISSUE TITLE
Nuspec should use PNG Chocolatey Icon

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#2322]
Instead of using the file at https://github.com/chocolatey/choco/raw/master/docs/logo/chocolateyicon.gif, we should use https://github.com/chocolatey/choco/raw/master/docs/logo/chocolateyicon.png - both files have been there for 5 years. This will help with systems that don't recognize GIF files.

**Comment by ferventcoder** [comment]
It's worth noting I did not cover the lib nuspec as it wasn't directly related to the issue.

**Comment by gep13** [comment]
> @ferventcoder said...
It's worth noting I did not cover the lib nuspec as it wasn't directly related to the issue.

This is no longer the case, and the associated PR updates both the nuspec files in this project.
