### ISSUE TITLE
Dependency Packages Being Saved in Nuget Cache After Install/Upgrade

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/choco#2325]
### What You Are Seeing?
Dependent packages are being written to the `C:\Users\<YourWindowsUser>\AppData\Local\NuGet\Cache` directory and not being cleared. Even when a cacheLocation is configured on the machine. 
### What is Expected?
These packages should be getting cleared from the NuGet Cache directory after package install/upgrade. 
### How Did You Get This To Happen? (Steps to Reproduce)
1. Run `choco install 7zip -s https://community.chocolateyorg/api/v2/ -y` as the local administrator user.
1. Check your C:\Users\Administrator\AppData\Local\NuGet\Cache` directory and you'll have a 7zip.install.nupkg file. 

#### References
* [ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/11284)
This issue is a regression followup to #479.

**Comment by TheCakeIsNaOH** [comment]
Duplicate of https://github.com/chocolatey/choco/issues/1592

Note that the unofficial `choco-cleaner` does handle cleaning these up.

**Comment by ryanrichter94** [comment]
Closing sue to being duplicate of #1592
