### ISSUE TITLE
Upgrade of package results in ERROR: The given path's format is not supported.

### ISSUE THREAD

**Issue by FibreFoX** [chocolatey/choco#2328]
Upgrade of package results in ERROR: The given path's format is not supported.

### What You Are Seeing?

Upgrade of package `godot-mono` results in error regarding unsupported format for shim creation/replacement. Maybe related to #1517 ... not sure

### What is Expected?

Upgrade working without problems

### How Did You Get This To Happen? (Steps to Reproduce)

1) choco install godot-mono --version 3.3.2
2) choco outdated
3) choco upgrade godot-mono

### Output Log

<details>
<summary>Full Logfile Output (chocolatey.log for step 1)</summary>

<p>
Please see this gist https://gist.github.com/FibreFoX/ab054a83cd169daf015d5d630736c652#file-1_chocolatey-log
</p>

</details>

<details>
<summary>Full Logfile Output (chocolatey.log for step 2)</summary>

<p>
Please see this gist https://gist.github.com/FibreFoX/ab054a83cd169daf015d5d630736c652#file-2_chocolatey-log
</p>

</details>

<details>
<summary>Full Logfile Output (chocolatey.log for step 3)</summary>

<p>
Please see this gist https://gist.github.com/FibreFoX/ab054a83cd169daf015d5d630736c652#file-3_chocolatey-log
</p>

</details>

**Comment by FibreFoX** [comment]
Install works normal when uninstalling the old version first and installing the new version.

**Comment by FibreFoX** [comment]
Closed as being a problem of the godot-mono package itself (as stated by the maintainer).

**Comment by gep13** [comment]
@FibreFoX thanks for confirming!
