### ISSUE TITLE
Cannot execute cpack agains a nuspec in the current directory

### ISSUE THREAD

**Issue by alanstevens** [chocolatey/choco#233]
Current behavior:
If I am in a directory PackageName, and I execute cpack PackageName.nuspec, I receive the error "The path is not of legal form."

ExpectedBehavior:
The nupkg file is created in the current directory.

Note;
The previous behavior matched the expected behavior

Workaround:
execute cpack .\PackageName.nuspec

**Comment by ferventcoder** [comment]
This is already logged

**Comment by ferventcoder** [comment]
Duplicate of #164
