### ISSUE TITLE
Disable importing / loading of DLL in the extension folder

### ISSUE THREAD

**Issue by pauby** [chocolatey/choco#2333]
### What You Are Seeing?
Chocolatey will load DLL's it finds in the PowerShell extensions folder. 

### What is Expected?
Chocolatey should not load any DLL's it finds in the PowerShell extensions folder.

### How Did You Get This To Happen? (Steps to Reproduce)
N/A

Related to #2078 #1041

**Comment by vexx32** [comment]
As there isn't a way to determine whether a DLL is a usable PowerShell module without loading it into memory, we're likely better off simply not loading DLLs directly as it has caused issues several times in the past (see: #2333, #2078, #1041) which has required us to create an ever-expanding list of exceptions to the loading behaviour.

Instead, if folks want to load DLLs as powershell modules, they can package them alongside a PSM1 file that handles the loading itself (see below). This avoids the need for Chocolatey to guess which dlls are powershell modules and which should not be loaded.

### Example PSM1 for loading a DLL module

```powershell
Import-Module $PSScriptRoot/myModule.dll
```
