### ISSUE TITLE
Choco not pushing with stored api key for source

### ISSUE THREAD

**Issue by bc3tech** [chocolatey/choco#234]
Trying to push to choco.org:
```
> choco apikey https://chocolatey.org

Chocolatey v0.9.9.4
https://chocolatey.org - 0a00....
```
Now trying to push a pkg out to choco (w/o specifying api key cuz I shouldn't have to now)
```
> choco push .\mypkg.nupkg
Chocolatey v0.9.9.4
An ApiKey was not found for 'https://chocolatey.org/'. You must either set an api key in the configuration or specify one with --api-key.
```

**Comment by ferventcoder** [comment]
Note the `/`

**Comment by ferventcoder** [comment]
As in the difference between `https://chocolatey.org` and `https://chocolatey.org/`

**Comment by bc3tech** [comment]
oof. yup that did it.
any way we could make this a non-issue?

**Comment by ferventcoder** [comment]
Shall we file a new issue?

**Comment by bc3tech** [comment]
I could just rename this one if that's acceptable.

**Comment by ferventcoder** [comment]
Yeah, the problem is the conversation would need to be deleted...

**Comment by ferventcoder** [comment]
Open a new one and reference this. Then we will close this one.
