### ISSUE TITLE
Chocolatey Licensed Extension is not loaded into PowerShell process when using v0.11.0

### ISSUE THREAD

**Issue by vexx32** [chocolatey/choco#2340]
### What You Are Seeing?

When attempting to use version v0.11.0 of Chocolatey alongside the Chocolatey Licensed Extension, the chocolatey.licensed.dll is not loaded as when Chocolatey PowerShell host is instantiated.

This is related to this [change](https://github.com/chocolatey/choco/pull/2341) where we moved away from loading assemblies which are placed into the extensions folder.  However, by doing this, we prevent the loading of the Licensed PowerShell cmdlets (for example `Stop-ChocolateyWindowsServiceCmdlet` which is used within the chocolatey-agent package).

It's likely this will also break Central Management installations, and anything else that relies on cmdlets that are only present in the chocolatey.licensed.dll.

On further testing, due to the fact that Chocolatey Licensed overrides some of the OSS cmdlets, without the chocolatey.licensed.dll in process, other OSS cmdlets also fail when something attempts to access them.

### What is Expected?

The chocolatey.licensed.dll extension should be loaded during package installations in the PowerShell host, so that installers can utilise the licensed extension's cmdlets, as well as the overridden OSS cmdlets.

### How Did You Get This To Happen? (Steps to Reproduce)

1. Install Chocolatey v0.11.0
2. Install chocolatey.extension v2.2.0
3. Attempt to install chocolatey-agent v0.12.0

**Comment by shmuelie** [comment]
Having installed 0.11.0 I'm now "stuck". How do I fix this state?

**Comment by TheCakeIsNaOH** [comment]
@shmuelie You should be able to do `choco upgrade chocolatey` again to get to `0.11.1`. Unless you are using C4B and have a broken `chocolatey-agent` install due to this, in which case contacting support might be best.

**Comment by gep13** [comment]
@shmuelie as @TheCakeIsNaOH mentioned, you should be able to upgrade to chocolatey 0.11.1.  If that isn't working, then could you please grab the log file from the attempt and send that through in a support ticket (assuming you are a C4B customer).

**Comment by shmuelie** [comment]
I have a pro license. After staring the problem for a bit, I removed my license file, was able to upgrade, and then reinstalled the license

**Comment by gep13** [comment]
@shmuelie that is a surprise to know that this was required, as it wasn't necessary in the testing that I did before releasing 0.11.1. Would you mind sharing the log file for the installation attempt where it was failing for you? Thanks!

**Comment by shmuelie** [comment]
I copied what I think are the relevant parts to [Gist](https://gist.github.com/shmuelie/6bcff2f814049877e93bc8e28ac827e5) but if needed here's the whole log file: [chocolatey.zip](https://github.com/chocolatey/choco/files/7107347/chocolatey.zip)
