### ISSUE TITLE
Upgrade command installs a package, instead of showing error message

### ISSUE THREAD

**Issue by comiluv** [chocolatey/choco#2342]
### What You Are Seeing?
Following message: ```"package name" is not installed. Installing...```is shown and choco installs the package of the given name

### What is Expected?
choco prints out an error message that the package is not installed therefore cannot be upgraded, and exit.

### How Did You Get This To Happen? (Steps to Reproduce)
1. choco upgrade ```a package that is not installed```

### Notes
 I encountered this issue when I saw there's an upgrade for vim-tux package I have today. I mistakenly typed ```choco upgrade vim``` and instead of upgrading vim-tux package, choco installed a new vim package which was not what I wanted, so I had to ```choco uninstall vim``` and then ```choco upgrade vim-tux``` again to get the originally desired result.
 Current behavior of chocolatey is
1. Not complying to the user and making a second guess of the command it was given.
2. Confuses the user unless the user is paying a very close attention to choco's output messages.
3. Relies on unwanted program's installer and uninstaller to fully clean up what's left of the unwanted app.
4. Makes the user to do unnecessary extra typing and work to correct the mistake.

**Comment by TheCakeIsNaOH** [comment]
Try this:
`choco feature enable -n skipPackageUpgradesWhenNotInstalled`

It will simply print a message and skip any packages that are not already installed if the user trys to upgrade them.

> Not complying to the user and making a second guess of the command it was given.
> Confuses the user unless the user is paying a very close attention to choco's output messages.

Personally, it would be more confusing to me if `choco upgrade` by default did not install packages that were not previously installed. Every other package manager which I use regularly (`apt`,`pacman`,`pip`,etc) will just go ahead and install the latest version of a package if it is not installed and the upgrade command for it is run.

> Makes the user to do unnecessary extra typing and work to correct the mistake.

IMHO it is always better to double check what you typed before running it than running whatever and having to try to fix the results later. Goes for anything command line, and doubly so for anything admin/root level.

**Comment by vexx32** [comment]
This is the default behaviour by design. If you'd rather choco not install packages automatically when calling `choco upgrade` if they're not already installed, you can either:

- Pass the `--skip-if-not-installed` / `--only-upgrade-installed`  flag to the `choco upgrade` command when calling it.
- Enable the `skipPackageUpgradesWhenNotInstalled` feature, as @TheCakeIsNaOH mentioned.

**Comment by comiluv** [comment]
I enabled skipPackageUpgradesWhenNotInstalled, thanks for the tip!
