### ISSUE TITLE
Can't upgrade from chocolatey 11.0 to 11.1 "You must be smarter than average bear"

### ISSUE THREAD

**Issue by nascentt** [chocolatey/choco#2343]
### What You Are Seeing?
After building a new host after v11 released, it failed due to the bug that was introduced with that version.
However I cannot upgrade to chocolatey v11.1 as if I do `chocolatey upgrade -y` I get 
`2021-09-03 09:26:41,991 7084 [DEBUG] - Package 'chocolatey' found on source 'https://licensedpackages.chocolatey.org/api/v2/'
2021-09-03 09:26:41,991 7084 [INFO ] - chocolatey v0.11.0 is newer than the most recent.
 You must be smarter than the average bear...`
 
### What is Expected?
update to v11.1
### How Did You Get This To Happen? (Steps to Reproduce)
`chocolatey upgrade -y`
### Output Log
2021-09-03 09:26:41,991 7084 [DEBUG] - Package 'chocolatey' found on source 'https://licensedpackages.chocolatey.org/api/v2/'
2021-09-03 09:26:41,991 7084 [INFO ] - chocolatey v0.11.0 is newer than the most recent.
 You must be smarter than the average bear...

<details>

<p>

</p>

</details>

**Comment by nascentt** [comment]
gah, it's because only v10 is being served?
```
choco list chocolatey --limitoutput --source=chocolatey.licensed
chocolatey|0.10.15
```
despite the fact 11.1 was served to a host building half an hour prior

**Comment by gep13** [comment]
@nascentt do you have the Chocolatey Community Repository disabled on the machine that you are attempting the upgrade on?

If so, can I get you to try...

```
choco upgrade chocolatey -y --source https://community.chocolatey.org/api/v2
```

**Comment by gep13** [comment]
Looks like there is an issue with the cached results coming back from the licensed feed.

Installing from the community repository should work for now, and I will get that cache cleared later today.

**Comment by pauby** [comment]
This has been resolved now. @nascentt can you check this again?

**Comment by nascentt** [comment]
yeah I see 11.1 in the repo now

```
choco list chocolatey --limitoutput --source=chocolatey.licensed
chocolatey|0.11.1
```
