### ISSUE TITLE
Install-ChocolateyInstallPackage.ps1 adds trailing space to silent args

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/choco#2345]
In powershell function `Install-ChocolateyInstallPackage` trailing space is added to silentArgs:

https://github.com/chocolatey/choco/blob/f68a242245defa7f9dc9189f1350f5ca6e6e922b/src/chocolatey.resources/helpers/functions/Install-ChocolateyInstallPackage.ps1#L359

The problematic part is `statement` parameter of function `Start-ChocolateyProcessAsAdmin` which gets into it as `"$silentArgs $additionalInstallArgs"`.

With Total Commander for example, passing silentArgs as `'/AHDU c:\totalcmd'` gets executed as `'/AHDU c:\totalcmd '` (notice the trailing space). Then TC tries to create folder `'c:\totalcmd '` with space at the end and it fails. 

To prove it is the problem and after looking into source code I used workaround solution for that package:

- https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/0a7332f2ad972850d197d5f7b706eb904c45b314/automatic/totalcommander/tools/chocolateyInstall.ps1#L8-L9 

With that code package installation works which proves that statement parameter handling is problematic and can not be set in this case. This solution is however flagged by gallery validator. 

To fix it, something like this will work:

```powershell
$statements = $silentArgs 
if ($additionalInstallArgs) { $statements += " $additionalInstallArgs" } 
$env:ChocolateyExitCode = Start-ChocolateyProcessAsAdmin $statements $fileFullPath -validExitCodes $validExitCodes -workingDirectory $workingDirectory 
```

**Comment by gep13** [comment]
@majkinetor I am not sure if I follow the problem that you are seeing here.

Can you please go back and update this issue using the issue template for reporting a bug? This includes a steps to reproduce section, which will help in understanding the problem that you are seeing.

Thanks

**Comment by majkinetor** [comment]
Its fairly obvious:

- Powershell function uses: `"$silentArgs $additionalInstallArgs"`
- With TC example, passing silentArgs as `'/AHDU c:\totalcmd'` gets executed as `'/AHDU c:\totalcmd '` (notice the trailing space. Then TC tries to create folder `'c:\totalcmd '` with space at the end and it fails. 

To reproduce it, use TC package:

https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/0a7332f2ad972850d197d5f7b706eb904c45b314/automatic/totalcommander/tools/chocolateyInstall.ps1#L8-L9

Remove `env:chocolateyInstallArguments` and set `SilentArgs = Get-TCInstallArgs` and install the package in Windows Sandbox. It will fail due to above problem

**Comment by majkinetor** [comment]
The fix is 

```powershell
if ($additionalInstallArgs) { $silentArgs += " " } 
$env:ChocolateyExitCode = Start-ChocolateyProcessAsAdmin "${silentArgs}${additionalInstallArgs}" $fileFullPath -validExitCodes $validExitCodes -workingDirectory $workingDirectory 
```

**Comment by gep13** [comment]
@majkinetor thank you for the additional information, that helps to understand the problem.

Are you able to update the original issue with all that information so that it is in one place?

Thanks

**Comment by majkinetor** [comment]
Sure. Should I PR this change, since its obviously buggy for some class of tools ?

**Comment by gep13** [comment]
Yip, happy to accept a PR which addresses this problem.

If we can put some tests around this as well, that would be great, but I don't think that would be possible.

**Comment by majkinetor** [comment]
Would testing the change by patching my local system be good enough ? I would change the `Install-ChocolateyInstallPackage.ps1` and force install TC package with silentArgs set in the Windows Sandbox and if it doesn't fail, I will call it a day. I can provide videos or logs of pre/post installations.

**Comment by gep13** [comment]
In terms of "developer" testing, what you have suggested would be great, yes.

What I was thinking about is how to introduce automated tests, to ensure that this isn't regressed in future releases.

We don't have any infrastructure in this repository to add those style of tests, but we do have some internally, so we may have to look to getting a test(s) added there to cover this bug.

**Comment by majkinetor** [comment]
In the meantime, since package is highly used, should  I trick the validator or can you (or somebody else) "promote" the TC package ?

- https://community.chocolatey.org/packages/TotalCommander/10.0.0.20210903

**Comment by gep13** [comment]
It is possible to provide an exemption (at the package version level) from package-validation, so if you reply to the moderation thread with a request for exemption, pointing at this issue, one of the moderators should be able to pick it up.

**Comment by majkinetor** [comment]
I will do that. Thanks.

**Comment by majkinetor** [comment]
Actually, I can't do that, since its chocolatey-community user behind the scenes.

**Comment by gobalius** [comment]
@majkinetor did you ever create a PR of your proposed changed to choco/src/chocolatey.resources/helpers/functions/Install-ChocolateyInstallPackage.ps1?

**Comment by majkinetor** [comment]
@gobalius, No.

**Comment by gobalius** [comment]
@majkinetor would you consider creating the PR? I think it's a low risk (unaffected packages will still work) and high gain (packages like totalcommander will not need the workaround and will pass the automatic check) situation.

**Comment by blami** [comment]
Hi, I am interested in fixing this (already raised a PR which I believe addresses the issue) as it blocks me from using Chocolatey internally with our installers (that behave similarly to Total Commander). 

I looked at previous two PRs and they seem inactive and I feel that solution one of them proposes (simply merging arguments without space in between) would break some other installers while my solution (not adding an empty string after space) should work in those cases (same as draft above).

**Comment by blami** [comment]
@gep13 I'm sorry to tag, not really sure what is process here to get the PR reviewed and eventually merged.

**Comment by blami** [comment]
@majkinetor I am sorry to tag, but is there anything I can do to have this PR reviewed and eventually merged? Is it just there's not enough reviewer bandwidth or is anything else missing on my side?

**Comment by majkinetor** [comment]
@blami , sorry, I am just a regular guy, not a choco employee. I don't think the outcome deserves the effort that is requested here.

**Comment by blami** [comment]
@gep13 is there anything from my side I can do to have this fix merged?

**Comment by pauby** [comment]
@blami We'll review the PR when we're ready to pull it in. The issue ha snot been assigned to a milestone as yet so it's not something we are currently working on.
