### ISSUE TITLE
refreshenv - refreshenv not installed. The package was not found with the source(s) listed.

### ISSUE THREAD

**Issue by hack3rcon** [chocolatey/choco#2349]
Hello,
I want to install the refreshenv on Windows 10, but I got below error:
https://0bin.net/paste/oNosS0og#aCYXKC4yIY3areX0kdlJpVZ57AeqxWtSi7s1kZdqFiV

How to solve it?

Thank you.

**Comment by pauby** [comment]
`refreshenv` is not a package that you install. It's a command that is installed with Chocolatey and available on the path. If you are running it after you install Chocolatey you may to close and reopen your session again, or even reboot, before it's available (due to the PATH changing).

**Comment by pauby** [comment]
No response to this one so I'm going to go ahead and close it. We can always reopen it later.
