### ISSUE TITLE
Cmake Package version 2.8.12 has NewItem issue

### ISSUE THREAD

**Issue by gyxtcgyxtc** [chocolatey/choco#236]
I am trying to install Cmake v2.8.12 using chocolatey, which I have done a couple of weeks before, without any issue. Now today, when I try to do it, all the sudden I get this error: 

PS C:\Windows\system32>  choco install -y cmake -version 2.8.12
Chocolatey v0.9.9.4
Installing the following packages:
cmake
By installing you accept licenses for the packages.

cmake v2.8.12
 WARNING: Some imported command names include unapproved verbs which might make
 them less discoverable.  Use the Verbose parameter for more detail or type
 Get-Verb to see the list of approved verbs.
 Downloading cmake 64 bit
   from 'http://www.cmake.org/files/v2.8/cmake-2.8.12.2-win32-x86.zip'
 Extracting C:\Users\clean\AppData\Local\Temp\chocolatey\cmake\cmakeInstall.zip to C:\ProgramData\chocolatey\lib\cmake\c
ontent...
 C:\ProgramData\chocolatey\lib\cmake\content
 New-Item : Could not find a part of the path 'C:\ProgramData\chocolatey\lib\cma
 ke\content\cmake-2.8.12-win32-x86\bin\cmw9xcom.exe.ignore'.
 At C:\ProgramData\chocolatey\lib\cmake\tools\chocolateyInstall.ps1:18 char:26
 +     @($com) | %{ New-Item <<<<  "$_.ignore" -type file }
     + CategoryInfo          : WriteError: (C:\ProgramData\...xcom.exe.ignore:S
    tring) [New-Item], DirectoryNotFoundException
     + FullyQualifiedErrorId : NewItemIOError,Microsoft.PowerShell.Commands.New
    ItemCommand
 New-Item : Could not find a part of the path 'C:\ProgramData\chocolatey\lib\cma
 ke\content\cmake-2.8.12-win32-x86\bin\cmake-gui.exe.gui'.
 At C:\ProgramData\chocolatey\lib\cmake\tools\chocolateyInstall.ps1:21 char:26
 +     @($gui) | %{ New-Item <<<<  "$_.gui" -type file }
     + CategoryInfo          : WriteError: (C:\ProgramData\...ake-gui.exe.gui:S
    tring) [New-Item], DirectoryNotFoundException
     + FullyQualifiedErrorId : NewItemIOError,Microsoft.PowerShell.Commands.New
    ItemCommand
cmake install not successful.
Error while running 'C:\ProgramData\chocolatey\lib\cmake\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details.
Failures:
 - cmake

When I run "choco install -y cmake" without specifying the version, it successfully install the latest version of cmake for me. But when I include the version, the error occurs. I searched online and found someone had similar issue but was not picked up by anyone: https://gist.github.com/nathanaeljones/804304be2e8189125f06

I don't know if this is an issue with chocolatey or with the package itself. Any idea would be much appreciated.

**Comment by ferventcoder** [comment]
Likely the package if a newer version of the package doesn't have issues.

**Comment by gyxtcgyxtc** [comment]
Thanks for the fast response. Though my thought is, the older version of the package should not have been touched in months, given that this older version was able to be installed successfully a few weeks back, I'm just wondering if it could be anything with the chocolatey updates.

**Comment by ferventcoder** [comment]
@gyxtcgyxtc The most likely issue is that the older version was depending on some chocolatey internals that were taken away as part of the rewrite (0.9.9). We've already had to put back some internals see #145 and #207.

**Comment by gyxtcgyxtc** [comment]
Thank you for the information. As far as I understand a package is created with a nuspec file and chocolateyInstall.ps1. The way I see it, the only place that can involve using the internals is in chocolateyInstall.ps1, where it does the call to "Install-ChocolateyZipPackage" or similar. I've compared the chocolateyInstall.ps1 scripts from both old and new package, the only difference is the binary url and the path to put the binary: 
Old: $url     = 'http://www.cmake.org/files/v2.8/cmake-2.8.12.2-win32-x86.zip'
New: $url     = 'http://www.cmake.org/files/v3.0/cmake-3.0.2-win32-x86.zip'

Old: $bin  = Join-Path $content 'cmake-2.8.12-win32-x86\bin'
New: $bin  = Join-Path $content 'cmake-3.0.2-win32-x86\bin'
These doesn't seem to be the problem. 

Although, both scripts use $MyInvocation.MyCommand.Definition. Could that be an issue? 

Thanks again for your time.

**Comment by ferventcoder** [comment]
> Although, both scripts use $MyInvocation.MyCommand.Definition. Could that be an issue?

Unlikely.

It's more likely there is a powershell variable they are taking advantage of that they didn't define, that was formerly defined in the POSH (powershell) client.

**Comment by gyxtcgyxtc** [comment]
Hello. Thanks for the information. I have asked the package maintainer if they can fix this. However, looking from another direction, I wonder if there is a way for me to choose an earlier release when installing chocolatey via powershell? So that I can make it to work with the current package. Thanks a lot.

**Comment by ferventcoder** [comment]
Yes you can - Take a look at https://github.com/chocolatey/chocolatey.org/issues/162 for details.
