### ISSUE TITLE
Add config option to select default template

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#2377]
It would be a nice feature to be able to select the default template to use with a config option.

That way, a user can `choco install` a template, and then `choco config` set the default template, no need to go in and overwrite the files in the `default` folder manually.

If the specified default template name is missing/not installed, then a warning should be shown, and a build in template should be used instead.

This would allow #1366 to be implemented more easily, or at least the way I envision it being implemented. Choco could just include the current default template, and the new "edit friendly" template, then users could switch between using them as the default with a simple command.

**Comment by TheCakeIsNaOH** [comment]
It may make sense to revert back to the built-in default template and display a warning if the template specified as the default is not found.

**Comment by gep13** [comment]
@TheCakeIsNaOH yes, this sounds like a sensible warning to display when this happens!
