### ISSUE TITLE
Api Key & Source matching could be more intuitive

### ISSUE THREAD

**Issue by bc3tech** [chocolatey/choco#238]
See #234. Ran in to a bit of confusion as I added an apikey for `https://chocolatey.org` but it wasn't being used because choco was looking for one for `https://chocolatey.org/` (note the trailing slash)
Seems to me some logic could be put in place for looking up stored api keys for sources that perhaps ignores a trailing slash? Not sure what else PowerShell might have in its bag of tricks for URL parsing/equality.

I believe I've encountered a similar issue in NuGet, but the choco team's just a *tad* bit more responsive ;)

**Comment by gep13** [comment]
>@bc3tech said...
I believe I've encountered a similar issue in NuGet, but the choco team's just a tad bit more responsive ;)

That is good to hear :+1:
