### ISSUE TITLE
Documentation updates for v0.12.0

### ISSUE THREAD

**Issue by gep13** [chocolatey/choco#2391]
This is a tracking issue, to ensure that any required documentation changes are completed ahead of the release of v0.12.0.

- [x] Add information about new defaultTemplateName configuration value - added in #2377
- [x] Blog post about running Chocolatey in a supported container - https://github.com/chocolatey/blog/pull/112
- [x] Add information about running on a non-Windows system - https://github.com/chocolatey/docs/pull/280
- [x] Remove information about ScriptsCheckLastExitCode feature - partially completed here: https://github.com/chocolatey/choco/pull/2524/commits/4ead203d44b68f88361609acba685ae50685ba42
- [x] Execute GenerateDocs and move changes over to docs.chocolatey.org

**Comment by TheCakeIsNaOH** [comment]
https://github.com/chocolatey/docs/pull/280

**Comment by gep13** [comment]
@pauby will keep this issue open as a reminder that we need to publish the blog post.  Once this is done, this issue can be closed and also the milestone can be closed.

**Comment by gep13** [comment]
The blog post has been published, so this issue can be closed out:

https://blog.chocolatey.org/2022/01/announcing-docker-images/
