### ISSUE TITLE
Chocolateys PowerShell Installer Module uses non PowerShell 2 compatible syntax

### ISSUE THREAD

**Issue by beatstick** [chocolatey/choco#2398]
Expected behaviour:
I expect a package being updated

How Did You Get This To Happen? (Steps to Reproduce):
I issuecd the command: choco upgrade all -y 

What are you seeing:

You must provide a value expression on the right-hand side of the '-' operator.
The specified module 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1
' was not loaded because no valid module file was found in any module directory.

ERROR: The term 'Install-ChocolateyPackage' is not recognized as the name of a c
mdlet, function, script file, or operable program. Check the spelling of the nam
e, or if a path was included, verify that the path is correct and try again.
The upgrade of gimp was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\gimp\tools\chocolateyInstall.
ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - gimp (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\gimp\to
ols\chocolateyInstall.ps1'.
 See log for details.

**Comment by corbob** [comment]
Could you provide the chocolatey log to assist with troubleshooting?

**Comment by pauby** [comment]
> It appears this log is from multiple runs (which is fine, it's just a bunch more to parse through).

Could you go back and edit that comment to remove what is not needed. It is HUGE so would help!

**Comment by beatstick** [comment]
Well firstly, thanks for doing all this work for the one user still running windows 7.
I couldn't find the the installer for powershell4 online, so I downgraded chocolatey and tried to install powershell4 via choco. Unfortunately Microsoft seems to have taken the upgrade file off their servers. Choco failed to download the exact same file called "Windows6.1-KB2819745-x64-MultiPkg.msu". 
May I ask how did you install it on the vm?

**Comment by campanellaf** [comment]
Hi there, we have started getting this issue on our VMs running Windows Server 2016.

In our case, the error is happening when trying to install AWSPowershellTools using the following command:

Install-Module -Name AWSPowerShell -Force

This is the error we are getting:

```
ERROR: The term 'Write-ChocolateyFailure' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

The install of awstools.powershell was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\AWSTools.Powershell\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 1/2 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - awstools.powershell (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\AWSTools.Powershell\tools\chocolateyInstall.ps1'.
```
This is the content of C:\ProgramData\chocolatey\lib\AWSTools.Powershell\tools\chocolateyInstall.ps1:

```
$package = 'AWSTools.Powershell'

try {
  $params = @{
    packageName = $package;
    fileType = 'msi';
    silentArgs = '/quiet';
    url = 'http://sdk-for-net.amazonwebservices.com/latest/AWSToolsAndSDKForNet.msi';
  }

  Install-ChocolateyPackage @params

  Write-ChocolateySuccess $package
} catch {
  Write-ChocolateyFailure $package "$($_.Exception.Message)"
  throw
}
```
Here is the log (C:\ProgramData\chocolatey\logs\chocolatey.log): [chocolatey.log](https://github.com/chocolatey/choco/files/8661753/chocolatey.log)

**Comment by campanellaf** [comment]
@vexx32 Thanks a lot for the reply. 
Just to see if I am following - according to what you mentioned, shouldn't this have been broken for years? We were able to run the `Install-Module -Name AWSPowerShell -Force` command without running into this issue two months ago.

**Comment by TheCakeIsNaOH** [comment]
> Just to see if I am following - according to what you mentioned, shouldn't this have been broken for years? We were able to run the Install-Module -Name AWSPowerShell -Force command without running into this issue two months ago.

The commands were deprecated for a number of years, so a warning was shown when they were used. But they still were available until Chocolatey version 1.0.0, where they were removed completely. So the AWS package would not have broken for you until you upgraded to Chocolatey v1.0.0 or newer.

**Comment by campanellaf** [comment]
@pauby sounds great, I'm going to give this a try and report back. Thanks a lot for the tip!

**Comment by campanellaf** [comment]
@pauby that did the trick! Thanks a lot, we can now resume our patching process! :)
Strangely enough, AWS says that `choco` shouldn't be involved at all in their install process and said that the `choco` package that exist is not supported by them.
However, we are just running the command AWS suggests on their docs (`Install-Module -Name AWSPowerShell -Force`) and that results in the following, which clearly indicates `choco` is being used behind the scenes:
```
amazon-ebs: Chocolatey v1.1.0
amazon-ebs: Installing the following packages:
amazon-ebs: awstools.powershell
amazon-ebs: By installing, you accept licenses for the packages.
amazon-ebs: Progress: Downloading PowerShell 5.1.14409.20180811... 100%
amazon-ebs: Progress: Downloading AWSTools.Powershell 1.1.1120.20130916... 100%
amazon-ebs:
amazon-ebs: PowerShell v5.1.14409.20180811 [Approved]
amazon-ebs: powershell package files install completed. Performing other installation steps.
amazon-ebs: Running on: Windows Server 2016 Datacenter, (ServerDatacenter), Windows Kernel: 10.0.14393
amazon-ebs: Installing for OS: Windows 10/Server 2016
amazon-ebs: WARNING: Windows 10 / Server 2016 has WMF/PowerShell 5 pre-installed which is maintained by Windows Updates.
amazon-ebs:  The install of powershell was successful.
amazon-ebs:   Software install location not explicitly set, it could be in package or
amazon-ebs:   default install location of installer.
amazon-ebs:
amazon-ebs: AWSTools.Powershell v1.1.1120.20130916 [Approved]
amazon-ebs: awstools.powershell package files install completed. Performing other installation steps.
amazon-ebs: WARNING: Url has SSL/TLS available, switching to HTTPS for download
amazon-ebs: Downloading AWSTools.Powershell
amazon-ebs:   from 'https://sdk-for-net.amazonwebservices.com/latest/AWSToolsAndSDKForNet.msi'
amazon-ebs: Progress: 100% - Completed download of C:\Users\Administrator\AppData\Local\Temp\chocolatey\AWSTools.Powershell\1.1.1120.20130916\AWSToolsAndSDKForNet_sdk-3.7.270.0_ps-4.1.80.0_tk-1.14.5.1.msi (159.19 MB).
amazon-ebs: Download of AWSToolsAndSDKForNet_sdk-3.7.270.0_ps-4.1.80.0_tk-1.14.5.1.msi (159.19 MB) completed.
amazon-ebs: Installing AWSTools.Powershell...
amazon-ebs: AWSTools.Powershell has been installed.
amazon-ebs: WARNING: Write-ChocolateySuccess was removed in Chocolatey CLI v1, and have no functionality any more. If you are the maintainer, please remove it from from your package file.
amazon-ebs: WARNING: If you are not the maintainer, please contact the maintainer to update the AWSTools.Powershell package.
amazon-ebs:   awstools.powershell may be able to be automatically uninstalled.
amazon-ebs:  The install of awstools.powershell was successful.
amazon-ebs:   Software installed as 'msi', install location is likely default.
amazon-ebs:
amazon-ebs: Chocolatey installed 2/2 packages.
amazon-ebs:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

any idea what's going on there?

**Comment by campanellaf** [comment]
Mistery solved - the script we are using to instal the tool is actually not the one I reported above. The script we are using is explicitly using `choco` to install the tool, which explains the above.

Thank you very much for replying and providing the explanation you gave above!
