### ISSUE TITLE
Outdated bit.ly links in command documentation

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#2401]
### What You Are Seeing?

`https://bit.ly/packages_config` at https://github.com/chocolatey/choco/blob/develop/src/chocolatey/infrastructure.app/commands/ChocolateyInstallCommand.cs#L260

And 

`https://bit.ly/nexus2apikey` at https://github.com/chocolatey/choco/blob/develop/src/chocolatey/infrastructure.app/commands/ChocolateyApiKeyCommand.cs#L112

### What is Expected?

`https://bit.ly/packages_config` is pointing at `https://github.com/chocolatey/choco/wiki/CommandsInstall#packagesconfig`, while it should point at `https://docs.chocolatey.org/en-us/choco/commands/install#packages.config`

and 

`https://bit.ly/nexus2apikey` is pointing at `https://books.sonatype.com/nexus-book/reference/nuget-deploying_packages_to_nuget_hosted_repositories.html` while it should point at
`https://help.sonatype.com/repomanager3/formats/nuget-repositories/deploying-packages-to-nuget-hosted-repositories`

**Comment by Windos** [comment]
In general, my (personal) preference is anything that's a hyperlinked behind display text in the docs should probably just be the full URL. If the URL is displayed raw or we're expecting it to be shared or commonly referred to then it should be a short link.

I'd say any "official" short links should be using `ch0.co` rather than `bit.ly`? @gep13?

**Comment by pauby** [comment]
@Windos Any official shortlinks should be using `ch0.co`.

**Comment by TheCakeIsNaOH** [comment]
> If the URL is displayed raw or we're expecting it to be shared or commonly referred to then it should be a short link.

The url will be displayed raw as part of a help output. 

So using `ch0.co` sounds good to me. Someone with access to that would need to create the links.

**Comment by gep13** [comment]
Agree with @Windos here. Moving to ch0.co links makes sense if they are raw links.

What is the process for creating those links?

**Comment by Windos** [comment]
@gep13, I DMed you the details. If I'm not beaten to it by the time I get back on tomorrow I can generate them.

**Comment by gep13** [comment]
@TheCakeIsNaOH @Windos I have created the following short links:

* https://ch0.co/nexus2apikey
* https://ch0.co/packages_config

Let me know if these work as expected, and make sense.

**Comment by pauby** [comment]
Those links work @gep13. Is there anything else holding up merging #2442?

**Comment by gep13** [comment]
@pauby no reason other than I haven't gotten to it yet. @TheCakeIsNaOH has a couple PR's that I need to review and I was planning on doing them in bulk once I got some free time.
