### ISSUE TITLE
License warning message needs to be updated

### ISSUE THREAD

**Issue by vexx32** [chocolatey/choco#2407]
### What You Are Seeing?

When adding a license to a Chocolatey installation, the following message is emitted when `choco` is invoked:

```code
Error when attempting to load chocolatey licensed assembly. Ensure
 that chocolatey.licensed.dll exists at
 'C:\ProgramData\chocolatey\extensions\chocolatey\chocolatey.licensed.dll'.
 The error message itself may be helpful:
 Could not find file 'C:\ProgramData\chocolatey\extensions\chocolatey\chocolatey.licensed.dll'.
 Install the Chocolatey Licensed Extension package with
 `choco install chocolatey.extension` to remove this license warning.
 TRIALS: If you have a trial license, you cannot use the above command
 as is and be successful. You need to download nupkgs from the links in
 the trial email as your license will not be registered on the licensed
 repository. Please reference
 https://docs.chocolatey.org/en-us/licensed-extension/setup#how-do-i-install-the-trial-edition
 for specific instructions.
```

### What is Expected?

The information around trials not being able to use the licensed repository is outdated and needs to be removed. I would also suggest that some parts of the error are redundant and/or unhelpful. Should we even have an error here, or just a warning? The wording here indicates it's meant to be a warning more than anything.

Maybe we could word it something like this?

```code
A valid Chocolatey license was found, but the chocolatey licensed assembly could not be loaded:
  Could not find file 'C:\ProgramData\chocolatey\extensions\chocolatey\chocolatey.licensed.dll'.
Ensure that the chocolatey.licensed.dll exists at the following path:
 'C:\ProgramData\chocolatey\extensions\chocolatey\chocolatey.licensed.dll'.

To resolve this, install the Chocolatey Licensed Extension package with:
 `choco install chocolatey.extension`
```

Potentially we could have Chocolatey install the extension automatically if it detects it's licensed, but that would be a larger discussion. At the very least we can update the message for now to avoid confusing folks. The documentation linked in the original message has already been updated.

### How Did You Get This To Happen? (Steps to Reproduce)

1. Have Chocolatey installed, without `chocolatey.extension`
2. Add a valid `chocolatey.license.xml` file to the `$env:ChocolateyInstall\license` directory
3. Run `choco` in a command line / powershell

### Output Log

Not really relevant here, I don't think.

**Comment by vexx32** [comment]
@gep13 is this something we want to fix in the near future?

**Comment by gep13** [comment]
@vexx32 I would suggest that this is something that we could/should put into the next release, yes.  However, that is ultimately a @pauby decisions.

**Comment by gep13** [comment]
@vexx32 just chatted with @pauby about this.  Can you get a PR up to alter the wording here so that it makes sense based on the current state of things?  Thanks!
