### ISSUE TITLE
Allow refreshenv to be silent if so desired.

### ISSUE THREAD

**Issue by DanAtkinson** [chocolatey/choco#2408]
Hi there,

I'd really like to be able to execute the [`refreshenv`](https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/redirects/RefreshEnv.cmd) script silently when I open a new command prompt. Currently I always get the same message - `Refreshing environment variables from registry for cmd.exe. Please wait...`.

Would it be possible to pass an argument to stop it being raised, or perhaps change it to something else?

For example `cmd /k "refreshenv --silent"`.

Kind regards
Dan

**Comment by mrx23dot** [comment]
refreshenv > NUL

**Comment by DanAtkinson** [comment]
Thank you.

I found a solution last month to automatically set it on open which is probably the correct answer:

* Navigate to `HKEY_CURRENT_USER\Software\Microsoft\Command Processor`.
  * [`regjump`](https://docs.microsoft.com/en-us/sysinternals/downloads/regjump) is probably the easiest method via `choco install sysinternals`.
* Add String Value of name `AutoRun`.
* Change AutoRun value to `refreshenv > NUL`.

This way, any time I open a command prompt, refreshenv automatically executes. I could change it to HKEY_LOCAL_MACHINE but there's no need to affect other users.

Regarding your comment about not needing to run this from Start > Run: this does not appear to be true for me. I get errors until I run `refreshenv`.

Best regards
Dan

**Comment by mrx23dot** [comment]
I created this ticket https://github.com/chocolatey/choco/issues/2458
so it should automatically do this (like in linux).
