### ISSUE TITLE
Add ability to set packages as not upgradeable and skip on `choco upgrade`

### ISSUE THREAD

**Issue by brentonw** [chocolatey/choco#242]
Having Chocolatey update packages where the apps already update themselves (for example Chrome, Skype etc...) is a little weird.

For example, when attempting to upgrade all installed packages using the command "choco upgrade all", it should really skip any packages that don't need updating, since they manage updates themselves.

"choco pin" can be used to prevent upgrades, but that requires work on behalf of the user. Instead, if a package could be marked as "non-upgradable" or "no need to upgrade" that would be better.

**Comment by ferventcoder** [comment]
Good meeting you! Thanks for following up with an issue on this.

**Comment by brentonw** [comment]
No worries!

**Comment by soredake** [comment]
Any progress on this?

**Comment by pauby** [comment]
The recommendation is to pin the packages (I did not your comment above about this).

> Instead, if a package could be marked as "non-upgradable" or "no need to upgrade" that would be better.

I'm unsure of the difference between marking a package as "no need to upgrade" and pinning it.

If the maintainer has the responsibility of marking their package as "non-upgradeable" (using metadata in the `nuspec` for example) then what do we do if a user _wants_ to upgrade it? Do we add a switch to ignore that? What is the maintainer marks the package as "upgradeable" and the user doesn't want to upgrade it? That functionality exists in the pin command.

The decision as to whether a package should be upgraded or not should always lie with the user. It's their system and their workflow. And in this case, the pin command offers that.

This is over 9 years old at this point with no updates, so I'm going to go ahead and close this as it's not something we'd be looking to add.
