### ISSUE TITLE
Run integration tests on github actions workflow.

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#2432]
Currently, the Appveyor CI is running the integration tests, but the GitHub actions workflow is not. Let's get both running the integration tests.

**Comment by gep13** [comment]
@TheCakeIsNaOH I actually spoke to the team about this this week as I noticed the same thing. This is due to the fact that in the AppVeyor config file some additional test execution is being done, which isn't being done when running the build.bat currently.

**Comment by TheCakeIsNaOH** [comment]
@gep13 Not quite right as far as I know. True, the build.bat by default excludes `Database,Integration,Slow,NotWorking,Ignore` via the uppercut files. But it is actually the appveyor built in testing functionality that is running the integration tests.

https://www.appveyor.com/docs/running-tests/#selecting-assemblies-andor-categories-to-test

The tests to ignore lines in the appveyor file refer to the appveyor built in testing (that finds tests and runs them via nunit), not to the uppercut script.

At least, I'm pretty sure that is what it is doing.
