### ISSUE TITLE
Get integration tests working on non-Windows

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#2434]
It would be good to get some of the integration tests working on non-Windows platforms, specifically the pack scenarios. 

Anything relating to running powershell scripts, shims, or the registry will not work, and so a lot of tests will have to be modified or skipped.

**Comment by gep13** [comment]
@TheCakeIsNaOH I am re-opening this issue, since running the integration tests are currently failing on Mac:

https://github.com/chocolatey/choco/actions/runs/1454752382

**Comment by TheCakeIsNaOH** [comment]
@gep13 I had noticed that, it is slightly odd. https://github.com/chocolatey/choco/pull/2435#issuecomment-962285656

I don't have direct access to any machines running MacOS, so at some point would you be in a position to try debugging the failing tests?

**Comment by gep13** [comment]
@TheCakeIsNaOH not a problem.  I will take a look.  I have ran the test script locally, and I have confirmed that it is happening on my machine as well.  Will let you know what I find.

**Comment by gep13** [comment]
Although, looking at that test class, it does appear that almost all of the tests in that class are excluded from anything but Windows:

![image](https://user-images.githubusercontent.com/1271146/148344586-064ca238-56ba-412b-92ef-7439b2c01515.png)

**Comment by TheCakeIsNaOH** [comment]
> However, I am unclear as to "how" they are getting into there, as it was my understanding that this service was only used while running on Windows machines.

Yup, the entire powershell section should be skipped on non-windows platforms. 
https://github.com/chocolatey/choco/blob/develop/src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs#L348

But I just figured out what is going wrong. That is using `config.Information.PlatformType` not `Platform.get_platform()`. And that is hardcoded in the NUnitSetup.cs to be windows. Must have missed that one.

**Comment by TheCakeIsNaOH** [comment]
@gep13 can you give #2509 a whirl and see if it fixes that issue?

**Comment by gep13** [comment]
@TheCakeIsNaOH while I think that this was a valid change, it hasn't fixed the tests, as they are still failing.  There is another call into the PowerShell service, here:

https://github.com/chocolatey/choco/blob/develop/src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs#L819

Which is causing the same error.  This isn't gated by a check on the Platform that it is executing on, and I am wondering if it should be, but then I am wondering if the check there is the right place to do this, and whether it should be done within the PowerShell service methods themselves.

Thoughts?

This still doesn't explain why these tests are working on Linux?!?

**Comment by TheCakeIsNaOH** [comment]
> Which is causing the same error. This isn't gated by a check on the Platform that it is executing on, and I am wondering if it should be, but then I am wondering if the check there is the right place to do this, and whether it should be done within the PowerShell service methods themselves.

Hmm, I hadn't looked at those calls before. 

It actually probably should be gated in `handle_package_uninstall`, as there is more than one thing to not run. That is where the install script run is gated.

> This still doesn't explain why these tests are working on Linux?!?

Yup, ummmmm. I don't know.

**Comment by TheCakeIsNaOH** [comment]
I've confirmed manually that beforemodify scripts at least sometimes try to run. 

Patch incoming.

**Comment by TheCakeIsNaOH** [comment]
@gep13 can you give #2511 a whirl?

**Comment by gep13** [comment]
@TheCakeIsNaOH it has done something...

There are still 4 tests failing, but now they are different tests:

![image](https://user-images.githubusercontent.com/1271146/148443536-8c7634d8-943f-4899-b414-cb87124a4700.png)

I will try to do some more digging...

**Comment by gep13** [comment]
In this scenario, where the uninstall is expected to happen, I don't think we can run this test on non-Windows platforms, since the uninstall script isn't going to be executed.  Thoughts?

**Comment by TheCakeIsNaOH** [comment]
> In this scenario, where the uninstall is expected to happen, I don't think we can run this test on non-Windows platforms, since the uninstall script isn't going to be executed. Thoughts?

Yup. The install was probably previously failing since the beforemodify script was trying to run, but now that it is disabled, the uninstall works, and the test fails.

**Comment by gep13** [comment]
@TheCakeIsNaOH you want to update your PR, and I will take it for a spin again?

**Comment by TheCakeIsNaOH** [comment]
@gep13 New commit added.

**Comment by gep13** [comment]
Woot! 🎉 

![image](https://user-images.githubusercontent.com/1271146/148446147-ba676c1a-daa4-4fd5-a8b0-00d2f3f7aed2.png)

**Comment by gep13** [comment]
Will need to have a proper look at the PR to ensure that the changes make complete sense, but gut says that these changes are necessary and correct, just need to spend some more time looking at it!

Great catch with all of this!

**Comment by TheCakeIsNaOH** [comment]
So overall, I should be able to renable about half of the disabled tests now.

There are some individual tests that will never work and have to be skipped:
- Shim creation/deletion checks
- Powershell script run checks

And there are some scenarios that will not work (some may never work) and have to be skipped:
- Package errors
- Read and Delete locked files
- Exclusively locked files
- Readonly files

But other than those categories, all the integration test scenarios should be working. See #2512

**Comment by gep13** [comment]
Woot! We got there in the end! @TheCakeIsNaOH great work!
