### ISSUE TITLE
[DOCS] - Should the --source parameter include an '=' sign?

### ISSUE THREAD

**Issue by ChaseFlorell** [chocolatey/choco#244]
In the documentation the --source parameter has an equals sign in one bit, but not in another. This was brought up in discussion today as to how we should structure our internal stuff. I know it's not a big deal, but should we specify one or the other?

https://github.com/chocolatey/choco/wiki/CommandsSources

>choco source add -n=bob -s"https://somewhere/out/there/api/v2/"
>choco source add -n=bob -s"https://somewhere/out/there/api/v2/" -u=bob -p=12345

>-s, --source=VALUE
>  Source - The source. Defaults to empty.

**Comment by ferventcoder** [comment]
It honestly doesn't matter, unless (and here's the fun part) you are going to support both versions of the choco client (0.9.8 and below and 0.9.9 and up), then you should use

`-source "VALUE"`

**Comment by ferventcoder** [comment]
If you are not supporting both, it's my recommendation that you don't need the `=`. It's extra typing.

The second section is auto-generated from the parameters, and `=VALUE` is there to show you that it is not a switch, but an option you pass a value with.

**Comment by ferventcoder** [comment]
@ChaseFlorell would you want us to include the recommendation in the docs/

**Comment by ChaseFlorell** [comment]
oh, I have no idea. I was just asking because I'm writing internal documentation, and I'm a fan of consistency. It's be being OCD, just keep doing the great stuff you're doing :+1:

**Comment by ferventcoder** [comment]
No recommendation for change at this time. Closing pending further followups. :)
