### ISSUE TITLE
Can't run theme watch on a downloaded theme.

### ISSUE THREAD

**Issue by Kypac-Max** [chocolatey/choco#2452]
As the title says, I have tried many times and can't find anything on google or issues.
Even after updating the error does not disappear
![1](https://user-images.githubusercontent.com/54379321/141699957-27e41b85-2c68-4f90-9c58-3014ec06782b.png)
![2](https://user-images.githubusercontent.com/54379321/141699962-79e950c3-8c54-44f7-a524-bda6354a3410.png)
![3](https://user-images.githubusercontent.com/54379321/141699964-85e5efc9-7abb-4797-b429-b4ff4189b1ac.png)

**Comment by corbob** [comment]
Looks like an issue with themekit whatever that is. The update may be failing due to not running as an administrator, but I couldn't say for sure because I have no idea what themekit is or what it's for.

**Comment by Kypac-Max** [comment]
![4](https://user-images.githubusercontent.com/54379321/141700330-84e8d7d4-d231-4f49-923b-cdfa71febee4.png)
Is updated.
I  forgot to post the update command

**Comment by Kypac-Max** [comment]
https://qrolic.com/setting-up-shopify-theme-kit-editor-for-vscode/
The solution is to do this.
