### ISSUE TITLE
Can't install choco on win7sp1

### ISSUE THREAD

**Issue by mrx23dot** [chocolatey/choco#2459]
I open cmd.exe (as admin), pasted:
`@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"`

Then I get this error:
```
Exception setting "SecurityProtocol": "Cannot convert value "3072" to type "System.Net.SecurityProtocolType" due to invalid enumeration values. Specify one o f the following enumeration values and try again. The possible enumeration values are "Ssl3, Tls"."
At line:1 char:35
+ [System.Net.ServicePointManager]:: <<<< SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/in stall.ps1'))
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

Exception calling "DownloadString" with "1" argument(s): "The underlying connection was closed: An unexpected error occurred on a send."
At line:1 char:113
+ [System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString <<<< ('https://community.chocolatey.org/in stall.ps1'))
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException
```

Powershell does start when I only run:
`@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe"`

Why all this needed, isn't there a simple zip file/installer with precompiled exe in it? 
It would be a lot easier to deploy.
Cheers

**Comment by TheCakeIsNaOH** [comment]
> Why all this needed, isn't there a simple zip file/installer with precompiled exe in it?

There is. See the completely offline install instructions:
https://docs.chocolatey.org/en-us/choco/setup#completely-offline-install

For security reasons, the community repository only has TLSv2/v3 enabled currently.
https://blog.chocolatey.org/2020/01/remove-support-for-old-tls-versions/

Thus, to download Chocolatey from the community repository, you would need to upgrade to at least PowerShell v3 and .Net 4.5, or download the chocolatey `.nupkg` another way and install it via the offline installer.

![image](https://user-images.githubusercontent.com/38865330/142289373-f31f59a1-7827-4285-8197-7b46321e21bf.png)

**Comment by mrx23dot** [comment]
Wow even the offline installation is complicated, you need a CS degree to understand this sentence:
`"You can put the chocolatey.nupkg on an internal package repository and then address that full path, similar to how you see in the Puppet provider"`

And the next step basically says figure out what the script does and make it work for you:
`"Then you would run a script similar to the below to address that local install. If it is on a repository somewhere, you will need to enhance the below script to get that file (the Chocolatey Puppet provider install script shows that)."`

Isn't simplicity goal in this project? 
See Chrome installation, download newest button, double click, done.

I have power shell v2, so I guess I cannot use this offline..
So what's wrong with the online installer?

**Comment by corbob** [comment]
> I have power shell v2, so I guess I cannot use this offline..
> So what's wrong with the online installer?

Nothing is wrong with the online installation. What is wrong is that windows 7 is no longer supported by Microsoft, and PowerShell 2 doesn't support the required TLS connection to download from the chocolatey website. That's why the offline install is the only option without upgrading PowerShell. Is there any particular reason that you are trying to freshly install chocolatey on an operating system that's been out of support for two years?

**Comment by mrx23dot** [comment]
Many of my clients still use win7, e.g. in factories, accounting PCs, CNC controllers, many times they are air gaped.
MS forces daily updates to win10, who will pay for the down time, or if it breaks something?

I'm happy with the offline if we can get it working. I managed to install it offline on win10, will try on win7.

My suggestion: 
A big download button on the website pointing to latest version, which is in a zip file (self-extracting or better installer), containing:
- chocolatey.0.11.3.nupkg
- install.ps1   -> preconfigured for v2 api, press any key at the end, right click to install
- how_to_install.txt

This is a lot cleaner than putting a script on a website and saying figure it out how to install it.

**Comment by pauby** [comment]
This isn't more of a question than an issue. I've closed the issue just now, as the way things work at the moment covers what is needed. We outlined in the docs that Windows 7 will need some additional steps to get the installer to be offline, and we also wrote a [blog post](https://blog.chocolatey.org/2020/01/remove-support-for-old-tls-versions) about this. 

We have plans in the future for the installer.

**Comment by mrx23dot** [comment]
Thank you, the concept is great! Microsoft is trying it's own, but only for Win10, using MS Store...  :)
https://github.com/microsoft/winget-cli

So if you could cover the gap for win7 that would be great!

Like is is absolutely necessary to have .NET if you could just include a wget.exe to handle the tls 1.3 download? And only use the cmd.exe to start the installer in the background.

I gave up on win7 after it required .NET 4.5, even though I had 3-4 older versions already installed.
