### ISSUE TITLE
Add deprecation notices for all things that are set to change in v2.0.0

### ISSUE THREAD

**Issue by gep13** [chocolatey/choco#2462]
The following are items that are planned to be completed in v2.0.0 of Chocolatey, we need to add notices, both in code and in the docs, to ensure that these changes are well communicated prior to this change.

* https://github.com/chocolatey/choco/issues/158
* https://github.com/chocolatey/choco/issues/2470 
* https://github.com/chocolatey/choco/issues/339
* https://github.com/chocolatey/choco/issues/2641

**Comment by TheCakeIsNaOH** [comment]
Issue for documenting Get-BinRoot is deprecated: https://github.com/chocolatey/choco/issues/339

**Comment by TheCakeIsNaOH** [comment]
And this issue about it probably should also be closed? https://github.com/chocolatey/choco/issues/65
