### ISSUE TITLE
Remove deprecated Chocolatey aliases

### ISSUE THREAD

**Issue by pauby** [chocolatey/choco#2467]
The following Chocolatey aliases have been deprecated and should be removed in v1.0.0:

* `cpack`
* `cver`

This is related to issue #89

**Comment by gep13** [comment]
I am going to go ahead and close out this issue.  The removal of the cpack alias (as mentioned already) is covered in this issue: https://github.com/chocolatey/choco/issues/89 and the removal of the cver alias is actually covered in this issue: https://github.com/chocolatey/choco/issues/2468 which means that there is nothing left to be done on this issue.
