### ISSUE TITLE
Remove deprecated Chocolatey commands and shims

### ISSUE THREAD

**Issue by pauby** [chocolatey/choco#2468]
The following commands have been marked as deprecated and should be removed in v1.0.0:

* `update` (see [docs](https://docs.chocolatey.org/en-us/choco/commands/update))
* `version` (see [docs](https://docs.chocolatey.org/en-us/choco/commands/version))

As well as removing the Chocolatey commands, i.e. `choco update` and `choco version`, we also need to make sure to remove the shim(s) that are installed.

There is a shim `cver` that executes `choco version` and needs to be removed.

An update to the chocolateyInstall.ps1 will be required to ensure that this is removed after successful installation of 1.0.0.

**NOTE:** The `cup` is not being removed.  This correctly points at `choco upgrade` and will be removed in 2.0.0.

**Comment by gep13** [comment]
This will also mean the shim for cver needs to go away as well.

**Comment by gep13** [comment]
There will need to be changes in chocolatey.extension as well, as these commands are overridden there.
