### ISSUE TITLE
Remove deprecated Chocolatey helper functions

### ISSUE THREAD

**Issue by pauby** [chocolatey/choco#2469]
The following Chocolatey helper functions have been deprecated and should be removed in v1.0.0:

* `Write-FileUpdateLog` (see [docs](https://docs.chocolatey.org/en-us/create/functions/write-fileupdatelog))
* `Write-ChocolateySuccess` (see [docs](https://docs.chocolatey.org/en-us/create/functions/write-chocolateysuccess))
* `Write-ChocolateyFailure` (see [docs](https://docs.chocolatey.org/en-us/create/functions/write-chocolateyfailure))
* `Install-ChocolateyDesktopLink` (see [docs](https://docs.chocolatey.org/en-us/create/functions/install-chocolateydesktoplink))

**Comment by TheCakeIsNaOH** [comment]
This issue probably should be closed as wontfix since Write-FileUpdateLog is going to be removed? https://github.com/chocolatey/choco/issues/156

**Comment by gep13** [comment]
There will need to be some documentation changes to complete this work, but this should happen as a result of running the GenerateDocs.ps1 file, once the v1.0.0 release is completed. So there is no need to re-open this issue as s signal that this needs to be done.
