### ISSUE TITLE
Mark Get-BinRoot Chocolatey helper function as deprecated

### ISSUE THREAD

**Issue by pauby** [chocolatey/choco#2470]
It's suggested that the `Get-BinRoot` Chocolatey helper function [will be deprecated later (closer to v1)](https://github.com/chocolatey/home/issues/112). This isn't noted anywhere else.

We need to mark this Chocolatey helper as deprecated in v1.0.0.

**Comment by TheCakeIsNaOH** [comment]
Issue for documenting Get-BinRoot is deprecated: #339

**Comment by gep13** [comment]
A follow up issue have been created here: https://github.com/chocolatey/choco/issues/2623 under the 2.0.0 milestone, to completely remove this alias.

**Comment by gep13** [comment]
Going to re-open this issue until the docs changes have been merged.  Basically as a reminder that this needs to be done:

https://github.com/chocolatey/docs/pull/401
