### ISSUE TITLE
Multi Threaded/Source Downloading

### ISSUE THREAD

**Issue by B-R-P** [chocolatey/choco#2486]
My internet is slow. So I like to have multi-threaded or multi-source downloading like [IDM](https://www.internetdownloadmanager.com/)
I think choco can use [aria2](https://aria2.github.io/) like [apt-fast](https://github.com/ilikenwf/apt-fast).

**Comment by TheCakeIsNaOH** [comment]
I think this is already covered by #1702.

**Comment by B-R-P** [comment]
OK. I mean the same  #1702
