### ISSUE TITLE
The operation completed successfully on stderr

### ISSUE THREAD

**Issue by dcjulian29** [chocolatey/choco#249]
I have a package that "works" in 0.9.8 and has started to be "unsuccessful" when installed on computers running the new choco 0.9.9. I've run the package on both Windows 8.1 and 10 and get the same:

    [ERROR] -  The operation completed successfully.

and the package fails to install. This specific package changes some registry settings and I've verified that they are indeed changed. I've also updated the install script to output the $LastExitCode after each line in the script and don't see any non-zero exit codes...

Console Output: https://gist.github.com/dcjulian29/e38de448ce54af997137

Chocolatey Log: https://gist.github.com/dcjulian29/7b9deb1be194f4fe7ef6

**Comment by ferventcoder** [comment]
Running this by hand, what is the exit code? 

`reg.exe import C:\ProgramData\chocolatey\lib\mysettings-ntfs\tools\registry.reg /reg:64`

Keep in mind that $lastexitcode may not apply to posh commands - http://joshua.poehls.me/2012/powershell-script-module-boilerplate/ You need `$?`

**Comment by ferventcoder** [comment]
Out of curiousity, did it work in 0.9.8.33? That one was a bit better at detecting errors than it's predecessors.

**Comment by dcjulian29** [comment]
Running from a command shell

     C:\ProgramData\chocolatey\lib\mysettings-ntfs\tools>reg.exe import registry.reg /reg:64
     The operation completed successfully.
     C:\ProgramData\chocolatey\lib\mysettings-ntfs\tools>echo %errorlevel%
     0

Running from a powershell:

     PS C:\Windows\system32> reg.exe import registry.reg /reg:64
     The operation completed successfully.
     PS C:\Windows\system32> $?
     True

Yes, it does work without issue on my systems that are still running 0.9.8.33...

**Comment by ferventcoder** [comment]
Any chance I can get the package in question (or one that has the same issues) for local testing?

**Comment by dcjulian29** [comment]
Yes, you can download it from https://www.myget.org/F/dcjulian29-chocolatey/api/v2/package/mysettings-ntfs/2014.5.17

**Comment by ferventcoder** [comment]
* http://stackoverflow.com/questions/22106446/system-io-ioexception-the-operation-completed-successfully-exception
* http://www.codedisqus.com/0xxVjPVVje/systemioioexception-the-operation-completed-successfully-exception.html
* https://rkeithhill.wordpress.com/2009/08/03/effective-powershell-item-16-dealing-with-errors/

**Comment by ferventcoder** [comment]
This is a tough one. Adding `$ErrorActionPreference = "Stop"` hasn't helped. Wrapping the whole thing in a try catch doesn't trap the error (even with the stop preference). I wonder if it is coming back from one of the commands. I'm going to systematically remove everything and step through each until I find the culprit. Hopefully that will help find the issue.

**Comment by ferventcoder** [comment]
Okay, so 

~~~sh
reg.exe import C:\ProgramData\chocolatey\lib\mysettings-ntfs\tools\registry.reg /reg:64
~~~

Exits with this status:

~~~
The operation completed successfully.
~~~

And an exit code of 0. Why that is getting fed to the error stream in what remains to be seen.

**Comment by ferventcoder** [comment]
* https://rcmtech.wordpress.com/2012/03/06/vbscript-and-reg_binary-registry-values/ | http://www.itninja.com/question/vbs-writing-in-hku-registry

At this reference note this:

~~~vbscript
      If InStr(1,oExec.StdErr.ReadAll,"operation completed successfully",vbTextCompare) Then
             ' Yes the success text IS sent out via StdErr and NOT StdOut
             WScript.Echo "Registry updated sucessfully"
             oFSO.DeleteFile sTempFile
      Else
             WScript.Echo "regWriteBinary: Registry import of " & sTempFile & " failed: " & oExec.StdErr.ReadAll
      End If
~~~

* http://en.community.dell.com/techcenter/powergui/f/4833/t/19570669

>I've found the problem. The main problem is in reg.exe utility.
>Depending on the version reg.exe utility works differently. v5.1.x.x (that I have on my XPSP3) works correctly, but v5.2.x.x does not work as it is expected to work.

>"reg import" command:
>- when v5.1: returns "Operation completed successfully" to standard OUTPUT stream 
>- when v5.2: returns "Operation completed successfully" to standard ERROR stream 

>Moreover, it is probably a problem with PowerShell also :(
>PowerShell treats these streams differently and process ERROR stream messages as errors. Which is correct imho. But for some reason the PowerShell console and PowerShell v2 ISE behavior is different in this case. (ISE shows the error just like the PowerGUI ScriptEditor does).

**Comment by ferventcoder** [comment]
This actually looks like an issue with reg.exe and not with new/old Chocolatey. Or rather the POSH version of choco was maybe forgiving on this.

I did flip over to 0.9.8.33 and it has no issues installing and it appears to return the message back as what looks like no error at all. I'm not quite sure what the correct path forward is.

**Comment by dcjulian29** [comment]
I believe the whole reason I switched to using the reg.exe tool was because sometimes PowerShell gets confused on the "bitness" of the registry if the PowerShell host is running the 32-bit shell on a 64-bit operating system when using the the PowerShell Registry Provider to change the registry...

I think I can work around this by calling out to the underlying .Net API to deal with the registry after determining if the system is 64-bit...

```powershell
$key = [Microsoft.Win32.RegistryKey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::LocalMachine, [Microsoft.Win32.RegistryView]::Registry64)

$subKey =  $key.OpenSubKey("SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", $true)

$subKey.SetValue("DisablePagingExecutive", 1)
```

I believe the path forward is to not fault Choco for _**"doing the right thing"**_ and to possibly submit a bug against the underlying tool being called from the script... Based on your research and discoveries, it doesn't appear to be a **bug** in chocolatey.

**Comment by ferventcoder** [comment]
Unfortunately this is not just local to reg.exe. Perhaps the right thing to do is workaround it. :/

**Comment by ferventcoder** [comment]
Fixed in https://github.com/chocolatey/choco/commit/99368761de360b3f20745995c19b9bddbb1fa51a and will be released with 0.9.9.7.

**Comment by ferventcoder** [comment]
See #445 - the code for this is being reverted with #8 as now by default choco doesn't fail based on stderr being written to and we want both paths to be similar (choco's built-in powershell and system powershell).

**Comment by BrainSlugs83** [comment]
I have no idea what Choco is -- and I apologize for derailing -- but this is the top google search result for `import-reg stderr` (was trying to figure out why a PowerShell script was failing) -- I thought I'd share this in case it helps others (it's a dirty hack, but it works):

```
function Import-Reg($path)
{
    # Some versions of reg.exe return success messages on the error stream! :(
    del .\temp.bat -Force -ErrorAction SilentlyContinue;

    # Encoding as ASCII is important here, or cmd.exe can't run it.
    "@echo off" | Out-File .\temp.bat -Encoding ascii -Force
    [String]::Concat('cmd /c reg import "', $path, '" 2>&1') | Out-File .\temp.bat -Encoding ascii -Append -Force;
    
    $output = $null;
    $output = & .\temp.bat;

    del .\temp.bat -Force -ErrorAction SilentlyContinue;

    if (($output | ? { $_ -ilike "*success*" } | Measure-Object).Count -gt 0) 
    { 
        echo $output;
        return;
    }
    else
    {
        throw $output;
    }
}
```
Hope that's helpful for someone, somewhere. :)

**Comment by travis-dr** [comment]
Thank you @BrainSlugs83  that has come in helpful!
