### ISSUE TITLE
Is there an option to see which packages needs to be upgraded?

### ISSUE THREAD

**Issue by AlvaroFierro** [chocolatey/choco#2490]
Hi, first of all, I have searched for this question in the [FAQ's ](https://docs.chocolatey.org/en-us/faqs)section, on the [official site ](https://docs.chocolatey.org/en-us/choco/commands/upgrade)and in the [issues](https://github.com/chocolatey/choco/issues?q=is%3Aissue+is%3Aopen+upgrade), but I have no answers, it is worth noting that I am new to using Chocolatey.

I have been using a GUI for almost 12 years and when you go into the CLI it's a bit tricky when you try to update your packages, because you don't know what to update. I tend to use the latest versions of various applications, so it would be nice to be able to see what packages need to be updated. Not only for security, but also for new features.

**Yes, I know if you list your apps** with `choco search -l` you can get it, and upgrade 1 by 1 but I prefer to see the current version and the next one and decide if I upgrade or not

**Comment by TheCakeIsNaOH** [comment]
Does `choco outdated` do what you want?

**Comment by AlvaroFierro** [comment]
Thx yes, that's what I wanted, it helped a lot.
