### ISSUE TITLE
'Uninstall-ChocolateyPath' helper function

### ISSUE THREAD

**Issue by Henriquemcc** [chocolatey/choco#2498]
After creating my internal Chocolatey packages and reading [Chocolatey PowerShell Reference](https://docs.chocolatey.org/en-us/create/functions/), I realized that, regarding the 'Install-ChocolateyPath' helper function, a function that does the opposite does not exist.

So I am suggesting that a Chocolatey helper function that does the opposite of 'Install-ChocolateyPath' (removes a directory from the PATH environment variable) should be built. It would be useful for those who build chocolatey packages, especially on the uninstall script.

**Comment by TheCakeIsNaOH** [comment]
This appears to be a duplicate of #310
