### ISSUE TITLE
refreshenv not working

### ISSUE THREAD

**Issue by ahmedmohiduet** [chocolatey/choco#250]
My 'refreshenv' is not working. After I commented out @echo off at the first line of refreshenv.cmd I found this logs on my command prompt.Any ideas why?
![image](https://cloud.githubusercontent.com/assets/3110101/7237035/7fb0310c-e7ba-11e4-9940-6a12534b70f3.png)

**Comment by ferventcoder** [comment]
That's a very interesting issue :/ 

What version, sku, LCID of Windows?

**Comment by ahmedmohiduet** [comment]
Any suggesion how can I get SKU LCID version number?

**Comment by ferventcoder** [comment]
SKU is something like Windows Enterprise.
LCID refers to language pack installed - is it en_us (US English) or something else?
Version is just Windows 2012 R2

**Comment by ahmedmohiduet** [comment]
I think my lcid is "en_us" and my windows version is:
Microsoft Windows 7 Professional
Version	6.1.7600 Build 7600

**Comment by ferventcoder** [comment]
> `call "C:\Users\mohi\AppData\Local\Temp\_env.cmd"

Make sure this file doesn't get deleted. You may want to inspect it for issues, it's likely something coming back from your path has issues.

**Comment by ahmedmohiduet** [comment]
Hi Rob,

I tried the command on my command prompt. But it is giving me this errors:

Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\mohi>call "C:\Users\mohi\AppData\Local\Temp\_env.cmd"
'C:\' is not recognized as an internal or external command,
operable program or batch file.
The following usage of the path operator in batch-parameter
substitution is invalid: %~A" == "Path" (call :SetFromReg "HKLM\System\CurrentCo
ntrolSet\Control\Session Manager\Environment" "%~A" "%~A" ) )


For valid formats type CALL /? or FOR /?
The syntax of the command is incorrect.

**Comment by ferventcoder** [comment]
Again, It's probably something **in** the file. It would help if you would post the contents of the file here.

**Comment by ferventcoder** [comment]
@ahmedmohiduet ping

**Comment by pyhedgehog** [comment]
@ahmedmohiduet Can't letter "C" in "C:\Users\mohi\AppData\Local\Temp\_env.cmd" be something other that english letter? Some local-language letter that looks alike and typed somewhere near. For example on Russian keyboard letter "С" (\u0421) placed on same key that letter "C" (\u0043).

**Comment by ferventcoder** [comment]
I haven't heard from you about this @ahmedmohiduet - either it has fallen off your radar or you figured out the issue. I'm going to close this issue for now. If you want to continue discussion or if it is still an issue, please feel free to comment with answers to my questions and we can reopen the issue and continue triaging. Thanks!
