### ISSUE TITLE
Complete pending Pin Command specs

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#2501]
There are a couple of tests in `ChocolateyPinCommandSpecs` that are marked as pending because the nuget mocking needs to be completed.
https://github.com/chocolatey/choco/blob/d8ca7bad2ad64538a0c1026a9317700dbb7f03db/src/chocolatey.tests/infrastructure.app/commands/ChocolateyPinCommandSpecs.cs#L427-L457

These nuget mocking methods should be completed, and the tests enabled.

**Comment by gep13** [comment]
@AdmiringWorm did you have any thoughts on these pending tests? Anything that you can think about adding here that would help?

**Comment by TheCakeIsNaOH** [comment]
IMHO, this would be best served by waiting for the nuget uplift, and completing these tests after that is merged, because work spent completing these tests now would likely be mostly not be applicable for newer nuget library versions.
