### ISSUE TITLE
Chocolatey isn't installing in Windows 11 suddenly

### ISSUE THREAD

**Issue by FahimFBA** [chocolatey/choco#2515]
I used to use Chocolatey in all of my Windows OS frequently. Suddenly today, after a fresh windows installation, whenever and however I try to install the package manager, it returns an error. I tried deleting the folder and reinstalling also, but that didn't solved the issue.

## Result:

```cmd
PS C:\Windows\system32> Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
Forcing web requests to allow TLS v1.2 (Required for requests to Chocolatey.org)
Getting latest version of the Chocolatey package for download.
Not using proxy.
Exception calling "DownloadString" with "1" argument(s): "The underlying connection was closed: An unexpected error     occurred on a receive."
At line:215 char:5
+     (Get-Downloader $url @ProxyConfiguration).DownloadString($url)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : WebException
Getting Chocolatey from .
Downloading  to C:\Users\FBA_DE~1\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip
Not using proxy.
Exception calling "DownloadFile" with "2" argument(s): "The path is not of a legal form."
At line:257 char:5
+     (Get-Downloader $url @ProxyConfiguration).DownloadFile($url, $fil ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : ArgumentException 
Extracting C:\Users\FBA_DE~1\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip to C:\Users\FBA_DE~1\AppData\Local\Temp\chocolatey\chocoInstall
Microsoft.PowerShell.Archive\Expand-Archive : The path
'C:\Users\FBA_DE~1\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip' either does not exist or is not a valid
file system path.
At line:515 char:5
+     Microsoft.PowerShell.Archive\Expand-Archive -Path $file -Destinat ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (C:\Users\FBA_DE...\chocolatey.zip:String) [Expand-Archive], InvalidOpe
   rationException
    + FullyQualifiedErrorId : ArchiveCmdletPathNotFound,Expand-Archive

Installing Chocolatey on the local machine
& : The term 'C:\Users\FBA_DE~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall.ps1' is not
recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if
a path was included, verify that the path is correct and try again.
At line:526 char:3
+ & $chocoInstallPS1
+   ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\FBA_DE...ateyInstall.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Ensuring Chocolatey commands are on the path
Ensuring chocolatey.nupkg is in the lib folder
```

## Original log posted

<details>
<summary>Full Log Output</summary>

<p>

```cmd
PS C:\Windows\system32> Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))                                                                     Forcing web requests to allow TLS v1.2 (Required for requests to Chocolatey.org)                                        Getting latest version of the Chocolatey package for download.                                                          Not using proxy.                                                                                                        Exception calling "DownloadString" with "1" argument(s): "The underlying connection was closed: An unexpected error     occurred on a receive."                                                                                                 At line:215 char:5                                                                                                      +     (Get-Downloader $url @ProxyConfiguration).DownloadString($url)                                                    +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                        + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException                                               + FullyQualifiedErrorId : WebException                                                                                                                                                                                                      Getting Chocolatey from .                                                                                               Downloading  to C:\Users\FBA_DE~1\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip                             Not using proxy.                                                                                                        Exception calling "DownloadFile" with "2" argument(s): "The path is not of a legal form."                               At line:257 char:5                                                                                                      +     (Get-Downloader $url @ProxyConfiguration).DownloadFile($url, $fil ...                                             +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException                                               + FullyQualifiedErrorId : ArgumentException                                                                                                                                                                                                 Extracting C:\Users\FBA_DE~1\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip to C:\Users\FBA_DE~1\AppData\Local\Temp\chocolatey\chocoInstall                                                                                          Microsoft.PowerShell.Archive\Expand-Archive : The path
'C:\Users\FBA_DE~1\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip' either does not exist or is not a valid
file system path.
At line:515 char:5
+     Microsoft.PowerShell.Archive\Expand-Archive -Path $file -Destinat ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (C:\Users\FBA_DE...\chocolatey.zip:String) [Expand-Archive], InvalidOpe
   rationException
    + FullyQualifiedErrorId : ArchiveCmdletPathNotFound,Expand-Archive

Installing Chocolatey on the local machine
& : The term 'C:\Users\FBA_DE~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall.ps1' is not
recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if
a path was included, verify that the path is correct and try again.
At line:526 char:3
+ & $chocoInstallPS1
+   ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\FBA_DE...ateyInstall.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Ensuring Chocolatey commands are on the path
Ensuring chocolatey.nupkg is in the lib folder
```

</p>

</details>

**Comment by gep13** [comment]
Chocolatey definitely does work on Windows 11. This is something that has come up a couple times, so much so that I created a video about it:

https://youtu.be/lBN1Rn15L2A

Can I get you to have a watch through of that to see if you are doing anything different?

**Comment by TheCakeIsNaOH** [comment]
@gep13 @FahimFBA There is some discussion in discord chat, apparently there are some latency issues on the community repository at the moment.

**Comment by corbob** [comment]
> @gep13 @FahimFBA There is some discussion in discord chat, apparently there are some latency issues on the community repository at the moment.

Pretty sure this is the issue, the first line of the output doesn't seem to have linebreaks, so you can't actually see the error... I'm just working on cleaning it up and will update the original message when that's done.

**Comment by YoraiLevi** [comment]
> @gep13 @FahimFBA There is some discussion in discord chat, apparently there are some latency issues on the community repository at the moment.

I wouldn't say latency issue, I am experiencing multiple blackouts on some packages 
![image](https://user-images.githubusercontent.com/50873841/148656831-f4546de0-8fda-4005-a789-c55bf97b7264.png)

**Comment by nattydreadnatty** [comment]
Experiencing the same problem here!

**Comment by nattydreadnatty** [comment]
`PS C:\Windows\system32> Set-ExecutionPolicy AllSigned; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))                                                                                                                                                                                                                     Modification de la stratégie d'exécution                                                                                La stratégie d’exécution permet de vous prémunir contre les scripts que vous jugez non fiables. En modifiant la         stratégie d’exécution, vous vous exposez aux risques de sécurité décrits dans la rubrique d’aide                        about_Execution_Policies à l’adresse https://go.microsoft.com/fwlink/?LinkID=135170. Voulez-vous modifier la stratégie  d’exécution ?                                                                                                           [O] Oui  [T] Oui pour tout  [N] Non  [U] Non pour tout  [S] Suspendre  [?] Aide (la valeur par défaut est « N ») : o    AVERTISSEMENT : Files from a previous installation of Chocolatey were found at 'C:\ProgramData\chocolatey'.             AVERTISSEMENT : An existing Chocolatey installation was detected. Installation will not continue.                       For security reasons, this script will not overwrite existing installations.                                                                                                                                                                    Please use choco upgrade chocolatey to handle upgrades of Chocolatey itself.                                            PS C:\Windows\system32> Set-ExecutionPolicy AllSigned; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))                                                                                                                                                                                                                     Modification de la stratégie d'exécution                                                                                La stratégie d’exécution permet de vous prémunir contre les scripts que vous jugez non fiables. En modifiant la         stratégie d’exécution, vous vous exposez aux risques de sécurité décrits dans la rubrique d’aide                        about_Execution_Policies à l’adresse https://go.microsoft.com/fwlink/?LinkID=135170. Voulez-vous modifier la stratégie  d’exécution ?                                                                                                           [O] Oui  [T] Oui pour tout  [N] Non  [U] Non pour tout  [S] Suspendre  [?] Aide (la valeur par défaut est « N ») : o    Forcing web requests to allow TLS v1.2 (Required for requests to Chocolatey.org)                                        Getting latest version of the Chocolatey package for download.                                                          Not using proxy.
Exception lors de l'appel de «DownloadString» avec «1» argument(s): «Le délai d'attente de l'opération a expiré.»
Au caractère Ligne:215 : 5
+     (Get-Downloader $url @ProxyConfiguration).DownloadString($url)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Getting Chocolatey from .
Downloading  to C:\Users\Fred\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip
Not using proxy.
Exception lors de l'appel de «DownloadFile» avec «2» argument(s): «Le chemin d'accès n'a pas une forme conforme.»
Au caractère Ligne:257 : 5
+     (Get-Downloader $url @ProxyConfiguration).DownloadFile($url, $fil ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException

Extracting C:\Users\Fred\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip to C:\Users\Fred\AppData\Local\Temp\chocolatey\chocoInstall
Microsoft.PowerShell.Archive\Expand-Archive : Le chemin d'accès
C:\Users\Fred\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip n'existe pas ou n'est pas un chemin d'accès au
système de fichiers valide.
Au caractère Ligne:515 : 5
+     Microsoft.PowerShell.Archive\Expand-Archive -Path $file -Destinat ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument : (C:\Users\Fred\A...\chocolatey.zip:String) [Expand-Archive], InvalidOp
   erationException
    + FullyQualifiedErrorId : ArchiveCmdletPathNotFound,Expand-Archive

Installing Chocolatey on the local machine
& : Le terme «C:\Users\Fred\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall.ps1» n'est pas reconnu
comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, ou
si un chemin d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.
Au caractère Ligne:526 : 3
+ & $chocoInstallPS1
+   ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Fred\A...ateyInstall.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Ensuring Chocolatey commands are on the path
Ensuring chocolatey.nupkg is in the lib folder`

**Comment by mnisius** [comment]
me too. I think the https://community.chocolatey.org/api/v2/ file is broken. It seems to contain zero packages.... 
```xml
<service xml:base="http://community.chocolatey.org/api/v2/">
<workspace>
<atom:title>Default</atom:title>
<collection href="Packages">
<atom:title>Packages</atom:title>
</collection>
</workspace>
</service>
````

**Comment by mattcargile** [comment]
Same. `choco outdated -r` has been failing with the below error for a couple of hours now.

```powershell
Error retrieving packages from source 'https://chocolatey.org/api/v2/':
 Could not connect to the feed specified at 'https://community.chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.
bat|0.18.3|0.18.3|false
```

**Comment by Larswa** [comment]
@TheCakeIsNaOH 

> There is some discussion in discord chat, apparently there are some latency issues on the community repository at the moment.

Hi,  I might be particularly dense, but HOW do I find the chocolatey Discord server?  Is it a public one?   Couldnt find it on the choc site.

**Comment by gep13** [comment]
>@Larswa said...
Hi, I might be particularly dense, but HOW do I find the chocolatey Discord server? Is it a public one? Couldnt find it on the choc site.

You can find the link here:
https://docs.chocolatey.org/en-us/faqs#cant-find-your-answer-here

**Comment by gep13** [comment]
@FahimFBA @YoraiLevi @nattydreadnatty @mnisius @Larswa can you please check again to see if things are now working?

**Comment by YoraiLevi** [comment]
> @FahimFBA @YoraiLevi @nattydreadnatty @mnisius @Larswa can you please check again to see if things are now working?
It started the download for vscode

**Comment by Larswa** [comment]
They are .. .I have just installed a ton of new packages ... got caught in the downtime while repaving my developer machine.  So ... everything seems to be back to normal!

**Comment by nattydreadnatty** [comment]
![image](https://user-images.githubusercontent.com/473300/148661981-77146187-8099-4a78-9d6f-2c0d5cb0dc02.png)

![image](https://user-images.githubusercontent.com/473300/148661991-9620c875-cb2d-4997-836c-6463c36fe8bd.png)

![image](https://user-images.githubusercontent.com/473300/148661998-99f473a3-949f-4858-8bb1-99ecd1390721.png)

**Comment by gep13** [comment]
@nattydreadnatty not that this should make a difference, but can I ask where you got that installation script from?  The recommended installation script is:

```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
```

**Comment by nattydreadnatty** [comment]
from there https://www.numetopia.fr/installation-de-chocolatey-guide-dutilisation/

Tx you I try with your script

**Comment by nattydreadnatty** [comment]
Niceee tx a lot its now working!

**Comment by gep13** [comment]
@nattydreadnatty that is great to hear!  Looking through the article (I don't speak French, so relying on Google translate) it is a much older article.  I would recommend using the official docs.

**Comment by gep13** [comment]
@FahimFBA @YoraiLevi @nattydreadnatty @mnisius @Larswa I am going to go ahead and close this issue.

**Comment by superbonaci** [comment]
@gep13 How can I force reinstall that script? It says I already have it installed.

**Comment by FahimFBA** [comment]
> @FahimFBA @YoraiLevi @nattydreadnatty @mnisius @Larswa can you please check again to see if things are now working?

It's working fine now.

**Comment by superbonaci** [comment]
@FahimFBA much better but still some timeouts:
````
Error retrieving packages from source 'https://chocolatey.org/api/v2/':
 Could not connect to the feed specified at 'https://community.chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

chocolatey-fosshub.extension was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""; Source(s): "https://chocolatey.org/api/v2/"
````

**Comment by Ridd01** [comment]
Force install chocolatey fixed problem for me. Try it.
choco install chocolatey --force

**Comment by superbonaci** [comment]
Works perfect now, server issue solved.

**Comment by gep13** [comment]
I am going to move this issue to the `home` repository, as this isn't, or rather wasn't, an issue directly with choco.exe, but rather with the Chocolatey Community Repository.
