### ISSUE TITLE
Use %systemroot% in place of %windir%. PATH exceed 2048 breaks choco

### ISSUE THREAD

**Issue by davehorner** [chocolatey/choco#252]
Pull request: https://github.com/chocolatey/choco/pull/251

%windir% is broken when %path% exceeds 2048 chars, but %systemroot% continues to work.

I found this issue due to cygwin rewriting my PATH to larger than 2048 I believe...
when I echo %windir%, it just prints %windir%.
when I echo %systemroot%, it prints C:\Windows.

I found this from the superuser ticket.
http://superuser.com/questions/719459/strange-path-issue-in-windows-7-goes-null-after-being-set
http://allgeekallthetime.blogspot.com/2012/01/path-over-2048-chars-kills-windir.html

The user experiences something like this:
XXX not upgraded. An error occurred during installation: Unable to find suitable location for PowerShell. Searched the following locations: '%windir%\SysNative\WindowsPowerShell\v1.0\powershell.exe; %windir%\System32\WindowsPowerShell\v1.0\powershell.exe; powershell.exe'

Which is a little confusing, because running powershell.exe works fine. I leave it to the merger to decide if %systemroot% should replace the %windir%, the fix supplied simply adds %systemroot% in addition to %windir%...this works fine too.

Thanks for choco.
--dave

**Comment by ferventcoder** [comment]
Interesting...

**Comment by davehorner** [comment]
crazy that modern windows OS has a strict limit of 2048 and breaks %windir% which incidentally is just defined as %systemroot% anyways!  frustrating...

I got my %windir% working again by pruning the path.  No reason to use %windir% if it can fail like this.

**Comment by ferventcoder** [comment]
Cygwin can also have issues with several environment variable not being loaded.

**Comment by ferventcoder** [comment]
Fixed in https://github.com/chocolatey/choco/commit/8f9b589af6a246025c41b3df52b363239a87a7e1 and will be released with 0.9.9.7.
