### ISSUE TITLE
Remove ScriptsCheckLastExitCode feature

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#2522]
As noted in these locations:
https://github.com/chocolatey/choco/blob/develop/src/chocolatey/infrastructure.app/builders/ConfigurationBuilder.cs#L311
https://github.com/chocolatey/choco/blob/develop/src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs#L413-L414

The ScriptsCheckLastExitCode feature was slated to be removed in v0.11.0. Since we are now at v0.11.3, that did not happen. Should the removal be retargeted for 1.0.0?

**Comment by pauby** [comment]
As this is a minor change, and we have ['announced' it](https://github.com/chocolatey/choco/blob/develop/src/chocolatey/infrastructure.app/builders/ConfigurationBuilder.cs#L311) this could go into 0.12.0.

@gep13?
