### ISSUE TITLE
sha1 checksum of zip is compared with md5

### ISSUE THREAD

**Issue by epu** [chocolatey/choco#253]
Install-ChocolateyZipPackage fails when passing a valid sha1 checksum with checksumType set to 'sha1', but succeeds with an md5 checksum/checksumType.

The error asserts that an md5 comparison was done, even though I passed in 'sha1' as the checksumType.

Is there a test already covering this case?

See https://github.com/epu/epu-choco-pkg/blob/master/premake.portable/tools/chocolateyinstall.ps1

**Comment by ferventcoder** [comment]
I'm confused. The link you sent shows `checksumType = 'md5'` https://github.com/epu/epu-choco-pkg/blob/master/premake.portable/tools/chocolateyinstall.ps1#L7

Was that after fixing it?

**Comment by epu** [comment]
Yeah, that's my workaround. If you uncomment the sha1 version and comment out the md5 version, it breaks.

**Comment by ferventcoder** [comment]
Ah sorry, glossed right over the commented stuff.

**Comment by epu** [comment]
Oh! I learned a new github link trick! (link to file number). Thanks!

**Comment by ferventcoder** [comment]
Might have found the issue. Was setting checksumType to the 64 bit version, which was empty. All because $url64 defaulted to $url.

**Comment by epu** [comment]
Ah, nice catch.
