### ISSUE TITLE
Publish Docker images to Docker Hub

### ISSUE THREAD

**Issue by gep13** [chocolatey/choco#2534]
# On a posix system

docker login
Put the official strongname key at the root of the repository
docker build -t chocolatey/choco:latest-linux --build-arg buildscript=build.official.sh -f docker/Dockerfile.linux .
docker push chocolatey/choco:latest-linux
#Docker tag adds a new tag to the underlying image (referenced with its hash), a single underlying image can have multiple tags
docker tag chocolatey/choco:latest-linux chocolatey/choco:v0.12.0-linux
docker push chocolatey/choco:v0.12.0-linux

# Then on a windows system

docker login
Build choco on the host, with official key and cert (or drop a prebuilt .nupkg into .\code-drop\nuget)
docker build -t chocolatey/choco:latest-windows -f docker/Dockerfile.windows .
docker push chocolatey/choco:latest-windows
docker tag chocolatey/choco:latest-windows chocolatey/choco:v0.12.0-windows
docker push chocolatey/choco:v0.12.0-windows

# On either system, after pushing the images. This lets latest and v0.12.0 work. 

docker manifest create chocolatey/choco:latest chocolatey/choco:latest-linux chocolatey/choco:latest-windows
docker manifest push chocolatey/choco:latest
docker manifest create chocolatey/choco:v0.12.0 chocolatey/choco:v0.12.0-linux chocolatey/choco:v0.12.0-windows
docker manifest push chocolatey/choco:v0.12.0

**Comment by gep13** [comment]
@TheCakeIsNaOH does the above seem complete to you?  If not, what have I missed.  I believe that we will also want a 0.12.0 tag, right? If so, what is the naming convention here?  `v0.12.0-windows`, `v0.12.0-linux` and then add another `v0.12.0` manifest?

**Comment by gep13** [comment]
Just trying to capture everything that needs to be done, so that I can add this to some release process notes that I have, and this doesn't get missed in future releases.

**Comment by TheCakeIsNaOH** [comment]
For the docker posix it should be:
- `docker build -t chocolatey/choco:latest-linux --build-arg buildscript=build.official.sh -f docker/Dockerfile.linux .`
- `docker push chocolatey/choco:latest-linux`

> I believe that we will also want a 0.12.0 tag, right? If so, what is the naming convention here? v0.12.0-windows, v0.12.0-linux and then add another v0.12.0 manifest?

Yup. https://github.com/chocolatey/choco/issues/1718#issuecomment-941030280

I think this set of steps should work:
```
#On a posix system
docker login
Put the official strongname key at the root of the repository
docker build -t chocolatey/choco:latest-linux --build-arg buildscript=build.official.sh -f docker/Dockerfile.linux .
docker push chocolatey/choco:latest-linux
docker tag chocolatey/choco:latest-linux chocolatey/choco:0.12.0-linux
docker push chocolatey/choco:0.12.0-linux

#Then on a windows system
docker login
Build choco on the host, with official key and cert (or drop a prebuilt .nupkg into .\code-drop\nuget)
docker build -t chocolatey/choco:latest-windows -f docker/Dockerfile.windows .
docker push chocolatey/choco:latest-windows
docker tag chocolatey/choco:latest-windows chocolatey/choco:0.12.0-windows
docker push chocolatey/choco:0.12.0-windows

#On either system, after pushing the images
docker manifest create chocolatey/choco:latest chocolatey/choco:latest-linux chocolatey/choco:latest-windows
docker manifest push chocolatey/choco:latest
docker manifest create chocolatey/choco:0.12.0 chocolatey/choco:0.12.0-linux chocolatey/choco:0.12.0-windows
docker manifest push chocolatey/choco:0.12.0
```

**Comment by TheCakeIsNaOH** [comment]
If you already have the `chocolatey/choco:latest` manifest locally, it needs to be removed with `docker manifest rm chocolatey/choco:latest` before the new manifest can be created.

**Comment by TheCakeIsNaOH** [comment]
v0.12.0-linux and latest-linux appear to both be working.

**Comment by gep13** [comment]
Working on the last one, but running into issues on Windows... :-(

**Comment by TheCakeIsNaOH** [comment]
What are you running into? Container build failing?

**Comment by gep13** [comment]
It was a combination of things, but seems to be all up and running now. Will post back here once latest-windows is pushed.

**Comment by gep13** [comment]
@TheCakeIsNaOH this has now been completed 🎉 

Thank you again for all your hard work on getting us to this point!

**Comment by TheCakeIsNaOH** [comment]
The latest and v0.12.0 tags do appear to work. 🎉

**Comment by gep13** [comment]
@TheCakeIsNaOH thank you for confirming! Will go ahead and close out this issue.
