### ISSUE TITLE
choco.exe v0.12.0 is listed as malicious at VirusTotal

### ISSUE THREAD

**Issue by koolhand** [chocolatey/choco#2537]
### What You Are Seeing?

choco.exe blocked by some antivirus packages

v0.12.0 is listed as malicious at VirusTotal, so it's getting blocked by some antivirus packages: https://www.virustotal.com/gui/file/ca67f6ac596d910c552021d219cc22cd56af40bd07b13d41f38494b6253636fa

These antivirus vendors see it as malicious
* Antiy-AVL
* SecureAge APEX
* PaloAlto Networks Cortex XDR
* Zillya 

### What is Expected?

choco.exe runs

### How Did You Get This To Happen? (Steps to Reproduce)

Any command involving choco.exe after upgrade to 0.12.0

**Comment by pauby** [comment]
Thanks for raising this issue. For reference, the current AV detections on the site are:

![image](https://user-images.githubusercontent.com/12760779/150144665-b478d0d5-889a-48a0-8fea-127621fc3ede.png)

And the detections for `choco.exe` are:

![image](https://user-images.githubusercontent.com/12760779/150145131-4d050531-69bc-4529-8176-7e937e122575.png)

We consider anything less than 5 AV detections in Virus Total to be a false positive. The majority of the executables that are being flagged are for the aliases (`clist.exe`, `chocolatey.exe`, etc.) and also `shimgen.exe`. We'd expect some AV vendors to flag these as they are shortcuts used to run `choco` command (`clist.exe` is a shortcut for `choco list` for example) and in `shimgen.exe`'s case is an executable to create those shimmed shortcuts.

The two for `choco.exe` I mentioned above are from Palo Alto Networks and SecureAge APEX. I will be submitting `choco.exe` as a false positive to the former, and I've never actually heard of the latter.

For future releases, we are going to keep a close eye on this and try to proactively manage it for the popular AV vendors. Any help within the community to submit false positive reports is greatly appreciated.

**Comment by koolhand** [comment]
Thanks for submitting as false positive. I can see the VirusTotal list no longer includes Palo Alto Networks showing it as malicious.
