### ISSUE TITLE
choco template -h references wrong subcommand in usage statement

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/choco#2546]
### What You Are Seeing?

The usage statement for the help of `choco template` is referencing the `choco pin` command.

### What is Expected?

The usage statement should reference `choco template`

### How Did You Get This To Happen? (Steps to Reproduce)

Run `choco template -h`

### Output Log

```
# choco template -h
Chocolatey v0.12.0
Template Command

List information installed templates.

Both manually installed templates and templates installed via
 .template packages are displayed.

NOTE: Available with 0.12.0+.
Usage

    choco pin [list]|info [<options/switches>]
Examples
```

**Comment by TheCakeIsNaOH** [comment]
Whoops, not sure how I missed that.
