### ISSUE TITLE
Uninstaller service should not depend on InstallLocation to be filled out

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#255]
The autoUninstaller looks for the existence of the registry key and the install path. However InstallPath could be empty as it is not required to be filled out. Only check InstallPath if it has a value.

**Comment by masaeedu** [comment]
Is this a fix for the issue discussed in [this thread](https://groups.google.com/forum/#!topic/chocolatey/KmNe0WI-Jv8)? I still can't get notepad++ to uninstall with autouninstaller enabled before installation. This is with Chocolatey 0.9.9.8.

**Comment by ferventcoder** [comment]
@masaeedu I think we should followup with a new issue. It should work if you have enabled autouninstaller before *uninstallation*. The caveat is that if you had NPP already installed and then used choco to reinstall it, it may not have caught a registry snapshot.

**Comment by alyssenko-ssi** [comment]
@ferventcoder "The caveat is that if you had NPP already installed and then used choco to reinstall it, it may not have caught a registry snapshot."

I believe this is what happened to me as I am currently dealing with the same issue. What does one do in this case?

**Comment by aronovgj** [comment]
uninstall and reinstall. also autouninstaller should be on when you install

**Comment by alyssenko-ssi** [comment]
@aronovgj thanks- let me try that.

**Comment by ferventcoder** [comment]
Auto uninstaller doesn't need to be on when you install. It will always capture the snapshot during the install no matter what. It just may not have anything to capture if there is no change to the registry.

**Comment by aronovgj** [comment]
i was so sure...

**Comment by i-give-up** [comment]
>The caveat is that if you had NPP already installed and then used choco to reinstall it, it may not have caught a registry snapshot

My experience is that it doesn't capture the registry snapshot. Is there any Github issue opened to address this?

**Comment by ferventcoder** [comment]
@i-give-up So you don't have NPP already installed and it is installing and doesn't capture a snapshot? And you are on on the latest version of chocolatey (0.9.9.11 as of this question)?

**Comment by ferventcoder** [comment]
No ticket yet filed for that.

**Comment by i-give-up** [comment]
@ferventcoder Yup. I'm using 0.9.9.11

1. Install the software manually.
1. Install the software using `choco install`
1. Uninstall the software using `choco uninstall`

Testing the steps above with packages `vlc` and `notepadplusplus.install`. Both gave me the message

    Skipping the auto uninstaller - No registry snapshot. 

Perhaps I should restart before installing with `choco` or is that supposed to matter.

**Comment by ferventcoder** [comment]
Step 1 is the issue, the snapshot can only detect registry changes. It may
see a change if there is a new version installed (no guarantees though).

You'd need to uninstall manually before the choco install and maybe a
reboot first before step 2.

You can always see the snapshots in
$env:ChocolateyInstall\.chocolatey\pkgname.version\.registry

On Wednesday, October 14, 2015, i-give-up <notifications@github.com> wrote:

> @ferventcoder <https://github.com/ferventcoder> Yup. I'm using 0.9.9.11
>
>    1. Install the software manually.
>    2. Install the software using choco install
>    3. Uninstall the software using choco uninstall
>
> Testing the steps above with packages vlc and notepadplusplus.install.
> Both gave me the message
>
> Skipping the auto uninstaller - No registry snapshot.
>
> Perhaps I should restart before installing with choco or is that supposed
> to matter.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/255#issuecomment-148243588>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by i-give-up** [comment]
Yeah, sorry if I wasn't being clear before. 

What I meant to ask was that: seeing that the Auto Uninstaller doesn't work if you install a package via choco over an existing manual installation, is there any plan to make Auto Uninstaller work in such cases?

**Comment by ferventcoder** [comment]
Yes, but it's based on package opt-in that tells the install where the key is. This also has the nice side effect of not running the installer if it is already installed.
