### ISSUE TITLE
Chocolatey can't handle truncated version numbers

### ISSUE THREAD

**Issue by nascentt** [chocolatey/choco#2552]
Chocolatey can't handle truncated version numbers 
```
choco list notepadplusplus --all
notepadplusplus 8.1.9.2
notepadplusplus 8.1.9
notepadplusplus 8.1.5
notepadplusplus 8.1.4
notepadplusplus 8.1.2
notepadplusplus 8.1.1
notepadplusplus 7.8.6
notepadplusplus 7.5.1
notepadplusplus 8.2
notepadplusplus 8.0
notepadplusplus 7.9
11 packages found.
```
```
choco list notepadplusplus
notepadplusplus 8.1.9.2
1 packages found.
```
```choco upgrade notepadplusplus
Upgrading the following packages:
notepadplusplus
By upgrading, you accept licenses for the packages.
notepadplusplus v8.1.9.2 is the latest version available based on your source(s).
Chocolatey upgraded 0/1 packages.
```

**Comment by nascentt** [comment]
Native powershell has no issue with version comparisons, so unsure why chocolatey struggles.

```
[version]8.2 -gt [version]8.1.9.2
True
```

**Comment by gep13** [comment]
@nascentt what source are you using? Is this an internal repository or the Chocolatey Community Repository?

**Comment by nascentt** [comment]
yes, we use an internal artifactory repo

**Comment by gep13** [comment]
In fact, running the same commands as you have provided against the Chocolatey Community Repository correctly shows the expected version number, so this does point the finger at _something_ from Artifactory being the problem.
