### ISSUE TITLE
ChocolateyTabExpansion.ps1 can cause slow auto-complete in PowerShell

### ISSUE THREAD

**Issue by an0le** [chocolatey/choco#2556]
### What You Are Seeing?
PowerShell autocomplete slows to a crawl when ChocolateyTabExpansion.ps1 is loaded and default "where" alias for Where-Object does not exist.

### What is Expected?
loading of "ChocolateyTabExpansion" should not slow Tab autocomplete (should not rely on alias).

Standard PowerShell programming practices is to not use aliases in code/modules, only on the command line.

### How Did You Get This To Happen? (Steps to Reproduce)

1. Added the following to my PSProfile:

   If (Test-Path Alias:diff ) {Remove-Item Alias:diff -Force}

2. Load PowerShell and try and hit tab to autocomplete

Normal behaviour restored by either commenting out loading of Choco module OR commenting out line to remove where alias.

### Output Log
No Output (problem is not with exe)

I fixed this manually myself by editing "ChocolateyTabExpansion.ps1" and changed all 12 occurences of "| where" to "| Where-Object" and problem was solved.

diff follows below

**Comment by an0le** [comment]
Diff

[diff.txt](https://github.com/chocolatey/choco/files/7986940/diff.txt)

**Comment by TheCakeIsNaOH** [comment]
> Standard PowerShell programming practices is to not use aliases in code/modules, only on the command line.

Yup, here is the associated PSScriptAnalyzer linting rule: https://github.com/PowerShell/PSScriptAnalyzer/blob/master/docs/Rules/AvoidUsingCmdletAliases.md

I'm not sure if checking for this would be part of #13, or if it deserves it's own issue.
