### ISSUE TITLE
Reseal upgrade command and remove virtuals

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#2571]
As noted in a todo comment in this file: https://github.com/chocolatey/choco/blob/develop/src/chocolatey/infrastructure.app/commands/ChocolateyUpgradeCommand.cs

It was added in this commit for more context: https://github.com/chocolatey/choco/commit/6b20a17b5f25a3cf0fc589672370a0061e90ea5a

If I am parsing it correctly, this class can be resealed once the version command goes away. #2468

**Comment by gep13** [comment]
>@TheCakeIsNaOH said...
If I am parsing it correctly, this class can be resealed once the version command goes away.

Yes, I am reading this the same way, and I am wondering whether we should include this work alongside the deprecation of those commands.

**Comment by gep13** [comment]
@pauby I have added this to the v1.0.0 milestone so that we can discuss this during the week.

**Comment by gep13** [comment]
@TheCakeIsNaOH based on a chat with @AdmiringWorm I don't think that we _can_ do this work, as this would prevent things from being overridable in the Chocolatey Licensed Extension.  I suspect that we will just close out this issue, and remove the comment in the code, but leave this one with me.

**Comment by AdmiringWorm** [comment]
As the commands can not be resealed due to how we require the commands to be overridable for us to use them in Chocolatey Licensed Extension, this issue won't be fulfilled.

After talking with @gep13 about this issue, I have removed the TODO comment in #2609 and will be closing this issue now.
