### ISSUE TITLE
Improve multiple side by side package behavior during install

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#2577]
Counterpart to #103
I didn't see an issue for install, only for upgrade.

As noted in a todo comment https://github.com/chocolatey/choco/blob/d8ca7bad2ad64538a0c1026a9317700dbb7f03db/src/chocolatey/infrastructure.app/services/NugetService.cs#L446-L447

**Comment by gep13** [comment]
@TheCakeIsNaOH This one I am not sure about.  Usage of side by side installation argument is not recommended, as it causes known problems during upgrade.  This one will need more discussion before anything can be done on it.

**Comment by TheCakeIsNaOH** [comment]
@gep13 No skin off my nose either way.

**Comment by vexx32** [comment]
Related issues:

- https://github.com/chocolatey/choco/issues/1022
- https://github.com/chocolatey/choco/issues/2788

Given we apparently don't want to have the side-by-side functionality in its current form (per #2788), perhaps we should close this issue?

**Comment by TheCakeIsNaOH** [comment]
As side by side installations have been deprecated, this issue is no longer relevant: https://github.com/chocolatey/choco/issues/2787

**Comment by harpreet20oct** [comment]
As side by side installations have been deprecated, is there any way or work around to do side by side installation.  not sure whether -m switch does the same

**Comment by pauby** [comment]
There are some suggestions over on #2878.
