### ISSUE TITLE
License add warning if expired

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#2584]
As noted in a todo comment in this file: https://github.com/chocolatey/choco/blob/cbba584692e2d02012e3eb03ba366b63d741d110/src/chocolatey/infrastructure/licensing/LicenseValidation.cs#L129-L130

**Comment by vexx32** [comment]
From the comment, the original intention was to give licensed customers approximately a 1-month leeway where the license would still work locally before considering itself expired. I suppose that's still possible, but given how long that comment has been there without action, I wonder if we really need this functionality?

The licensed packages feed also has always considered license expiration dates without leeway as well, so if we do want to add some kind of allowance here to make renewals easier, we might want to add it in both places. 🤔 

That would be a decision for @pauby and @gep13 to weigh on on; whether we still want this, and if so do we want to also include the licensed package feed's license check in this as well.

**Comment by gep13** [comment]
We should remove the todo comment from the code base if we are closing this issue.

**Comment by pauby** [comment]
Good catch. Reopening.

**Comment by pauby** [comment]
PR raised.
