### ISSUE TITLE
Improve handling of old TLS version warning

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#2585]
https://github.com/chocolatey/choco/blob/d8ca7bad2ad64538a0c1026a9317700dbb7f03db/src/chocolatey/infrastructure/registration/SecurityProtocol.cs#L44

**Comment by vexx32** [comment]
Hmm. Interesting. This may become a non-issue when we move away from .NET 4.0, so we might not really need this code path after that anyway. 

Also, I think the Community Repository requires TLS 1.2 at a minimum now, if my memory is correct? (@Windos am I remembering that right, doesn't the community repository require that now?)

So this might be something that most chocolatey users aren't in a position to see anyway.

**Comment by corbob** [comment]
Can confirm, you will **only** see this if you run with `--verbose`. Here's a screenshot to save us having to spin up Windows 7 again to get here:

![image](https://user-images.githubusercontent.com/30301021/161334417-b8b6a1c8-c325-47f3-85d5-238f8372f6c7.png)

**Comment by Windos** [comment]
> Also, I think the Community Repository requires TLS 1.2 at a minimum now, if my memory is correct? (@Windos am I remembering that right, doesn't the community repository require that now?)

That [is correct](https://blog.chocolatey.org/2020/01/remove-support-for-old-tls-versions/).

**Comment by TheCakeIsNaOH** [comment]
This potentially could be fixed as a part of #2902

**Comment by vexx32** [comment]
Going to close this as just a straight duplicate of #2902 tbh, they're both concerning the same code path and the same resolution would be ultimately required for both.

**Comment by gep13** [comment]
Duplicate of #2902

**Comment by gep13** [comment]
@vexx32 one additional follow up here, since this is a duplicate issue, we can remove the milestone, which I have done just now.
