### ISSUE TITLE
Package not found with the sources listed

### ISSUE THREAD

**Issue by SurajGupta** [chocolatey/choco#260]
Hello.  I'm having trouble creating/installing a fairly vanilla Chocolatey package.  

- Using v0.9.9.5.  
- Package source is [here].
- failure regardless of whether I install the package locally or from the [public gallery]

**log**
    2015-04-30 06:39:41,701 [INFO ] - ============================================================
    2015-04-30 06:39:41,732 [INFO ] - Chocolatey v0.9.9.5
    2015-04-30 06:39:41,826 [INFO ] - Installing the following packages:
    2015-04-30 06:39:41,826 [INFO ] - officeproplus2013
    2015-04-30 06:39:41,826 [INFO ] - By installing you accept licenses for the packages.
    2015-04-30 06:39:42,873 [ERROR] - officeproplus2013 not installed. The package was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""
     Source(s): "https://chocolatey.org/api/v2/"
    2015-04-30 06:39:42,889 [WARN ] - 
    Chocolatey installed 0/1 package(s). 1 package(s) failed.
     See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    2015-04-30 06:39:42,889 [ERROR] - Failures:
    2015-04-30 06:39:42,889 [ERROR] -  - officeproplus2013

[here]: https://github.com/SurajGupta/Chocolatey-Packages/tree/Adding-OfficeProPlus2013/OfficeProPlus2013
[public gallery]: https://chocolatey.org/packages/OfficeProPlus2013

**Comment by SurajGupta** [comment]
seems to work from public gallery when BOM is added to ps1 file.  doesn't work locally.  closing out

**Comment by ferventcoder** [comment]
@SurajGupta If you look - https://chocolatey.org/packages/officeproplus2013 is still in moderation. It won't come up in search results and is not installable for the general public. It has to be approved to show up publicly.

**Comment by SurajGupta** [comment]
But shouldn't this work locally?  `choco install path/to/my/package` results in the `Package not found with the source(s) listed` error

**Comment by fschwiet** [comment]
I have the same question.  I am builing a package locally, when I try to install it with "choco install <packageName>" I get error:

    nodist not installed. The package was not found with the source(s) listed.
    If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
    Version: ""

This nuspec I'm using worked in the past.

**Comment by ferventcoder** [comment]
@fschwiet what are you calling exactly?

**Comment by ferventcoder** [comment]
> But shouldn't this work locally? choco install path/to/my/package results in the Package not found with the source(s) listed error

@SurajGupta depends on if it has dependencies that are not met by locally installed items or not. Sometimes you need to use -source with that to include the sources for the dependencies.

**Comment by SurajGupta** [comment]
Do you mean dependencies on other nuget packages?  I can't think of any dependencies that my packages has in general.   It's a fairly vanilla wrapper around a EXE that's downloaded from Microsoft:

Here's the  source:
https://github.com/SurajGupta/Chocolatey-Packages/tree/master/OfficeProPlus2013

**Comment by ferventcoder** [comment]
@SurajGupta can you include a debug verbose log of your attempt with the error?

**Comment by SurajGupta** [comment]
Hmm...can't seem to reproduce the error now.  Not sure what the state of my system was when I was originally trying to get this done.  Let's keep it closed and if it comes up again I'll reopen.

**Comment by ferventcoder** [comment]
Sounds good.

**Comment by bozeyman9000** [comment]
Im using windows 7 home premium with the product key. I just did a reinstall of my windows OS and am having this issue, though i am unsure if i had this issue before the reinstall. I will try updating my windows 7 home premium OS with the official updates and continue trying. If anyone finds a solution please feel free to contact me via telephone. +1 720 483 8663

**Comment by pauby** [comment]
@bozeyman9000 I've removed your phone number from your message. Very bad idea to add that in an open forum!

**Comment by bozeyman9000** [comment]
Lol thanks. I just wanted an immediate response at the time =P
