### ISSUE TITLE
Chocolatey install problem 

### ISSUE THREAD

**Issue by hashisyumy** [chocolatey/choco#2604]
I just try to upgrade node.js and I get that error.
choclatey not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - choclatey - choclatey not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.

**Comment by JPRuskin** [comment]
Can I confirm what you tried to run? It seems like it's attempting to install a package named "choclatey" which probably doesn't exist. It seems like you ran something like `choco install choclatey upgrade nodejs`?

If you were looking to upgrade Node.JS I would expect you to run something like `choco upgrade nodejs`.

**Comment by pauby** [comment]
@hashisyumy Unfortunately we will not be able to progress this issue until the issue template is completed correctly. The information that asks you to provide is very important to help us.

**Comment by hashisyumy** [comment]
I just try to upgrade my node.js and after I get this error.I delete node.js and chocolatey know I don't get this error but I am getting other errors from the node.js

**Comment by JPRuskin** [comment]
You are quite unlikely to get Chocolatey errors after deleting it.

I'm afraid we can't help with Node.js errors. I'm going to close this issue now.

Have a nice day!
