### ISSUE TITLE
Choco 0.12.1 Blocked by Palo Alto

### ISSUE THREAD

**Issue by havedill** [chocolatey/choco#2610]
What You Are Seeing?
Chocolately install/upgrades blocked by palo alto

v0.12.1 is listed as malicious at VirusTotal, so it's getting blocked by some antivirus packages/firewalls: 

Palo Alto firewalls for example are blocking it from downloading

https://www.virustotal.com/gui/file/d82fa394fb45a8766ebc22ea5ec587ebc309c82b9f832c24ffd185478aee054b

What is Expected?
Chocolatey can be downloaded / upgraded

How Did You Get This To Happen? (Steps to Reproduce)

I discovered this when attempting to install chocolatey on a PC. The palo alto firewall cuts the download off half way through. This also occurs if i attempt to run a choco update

**Comment by gep13** [comment]
@havedill this happened recently with the release of 0.12.0:

https://github.com/chocolatey/choco/issues/2537

We submitted a false positive request to the Anti-Virus vendor, and this got fixed, but they must be flagging on the new release.

To the best of our knowledge, there is nothing malicious contained within this release.

**Comment by pauby** [comment]
I'm going to go ahead and close this issue, but we can reopen it if necessary.
