### ISSUE TITLE
parameters not remembered on choco upgrade all

### ISSUE THREAD

**Issue by SlrG** [chocolatey/choco#2631]
**Example:**
When installing the veyon package it can be selected what should be installed. By default its only the client component. (->student pc)
```
choco install veyon
```
When adding the parameter /Master the master control component gets installed, too. (->teacher pc)
```
choco install veyon --params '/Master'
```
When upgrading the teacher pc, the parameter has to be added too, or the master control component will be removed.
```
choco upgrade all -y --params '/Master'
```

**Issue 1:**
If the upgrade command `choco upgrade all -y` is run with no special knowledge, package functionality can be removed/disabled by mistake.

**Potential Issue 2:**
The given parameter is probably passed to each installed package and could be misinterpreted, if there are multiple packages having the same parameter, resulting in unexpected behavior.

**Feature Request:**
It would be great if chocolatey could remember parameters passed on installation of a package and reapply them automatically on upgrading for that package only.

**Comment by gep13** [comment]
@SlrG are you familiar with the `useRememberedArgumentsForUpgrades` feature of Chocolatey?  More information on this here:

https://docs.chocolatey.org/en-us/configuration#general-1

This is disabled by default, but you can turn this on and test it out to see if it does what is needed.

NOTE: You will need to install your package again, after enabling this feature.

**Comment by SlrG** [comment]
@gep13 
That seems to be exactly what I need and it should solve my described issues. Thank you very much! :1st_place_medal: 
I did not know this feature exists already and my google foo was not strong enough to find it myself.
