### ISSUE TITLE
Mark Chocolatey shims (chocolatey. cinst, clist, cpush, cuninst, cup) are deprecated

### ISSUE THREAD

**Issue by gep13** [chocolatey/choco#2641]
Going forward, usage of the shimmed versions of choco commands is not recommended.

i.e. rather than using `clist` the recommendation is to use `choco list`

This is true for all shims/commands:

* chocolatey
* cinst
* clist
* cpush
* cuninst
* cup

Documentation on the site and help documentation should be updated to remove mention of these shims, and any mention of them in the usage sections of help commands should be marked as deprecated.

In addition, the generatedocs.ps1 file should be updated to add a warning message to the top of each command page, indicating that the shim will be removed in 2.0.0.

**Comment by gep13** [comment]
A follow up issue has been created here: https://github.com/chocolatey/choco/issues/2642 in the 2.0.0 milestone to completely remove these shims.

**Comment by sebma** [comment]
@gep13 Hi,

Is it wrong for us chocolatey users to use those shims ?

Isn't it easier to type `cup` than to type `choco upgrade` ?

What are the reasons you want to remove those shims ?

Do you plan to replace those shims by new shims in the near future ?

**Comment by pauby** [comment]
@sebma 

> What are the reasons you want to remove those shims ?

There are various reasons to remove the shims but it is generally due to clashes with other software for some of those. Rather than have some shims and remove others we decided to remove them all.

> Is it wrong for us chocolatey users to use those shims ?

Nothing wrong with using them if you are aware of the consequences (they won't work natively in Chocolatey CLI in future versions and they could clash with other software that you have installed).

> Isn't it easier to type cup than to type choco upgrade ?

It is. But troubleshooting issues caused is problematic. If you want to keep using them, add them as PowerShell (or your shell of choice) aliases.

> Do you plan to replace those shims by new shims in the near future ?

No. If you want to keep using the aliases after they have been removed, use PowerShell (or your shell of choice) aliases.

**Comment by sebma** [comment]
@pauby Hi, you said : 
> they could clash with other software

Do you know which software could clash with those chocolatey shims ?

> No. If you want to keep using the aliases after they have been removed, use PowerShell (or your shell of choice) aliases.

If I create powershell aliases (or functions), wouldn't they clash with the **other software** you're talking about ?

If another software ever creates a command called `choco`, will you also remove or rename the `choco` command ?

**Comment by pauby** [comment]
> Do you know which software could clash with those chocolatey shims ?

`cpack` was one clashing with the cmake software (from memory).

> If I create powershell aliases (or functions), wouldn't they clash with the other software you're talking about ?

Absolutely. That decision would be yours though - if you have the software you wouldn't add those aliases. 

> If another software ever creates a command called choco, will you also remove or rename the choco command ?

No. `choco` is well established as a command.

This is a closed issue so lets leave the discussion here.. If you need to discuss this any further, [Discord](https://ch0.co/community) would be the best place.
