### ISSUE TITLE
Remove deprecated Chocolatey shims (chocolatey. cinst, clist, cpush, cuninst, cup)

### ISSUE THREAD

**Issue by gep13** [chocolatey/choco#2642]
In v1.0.0 we marked the Chocolatey shims as deprecated

* chocolatey
* cinst
* clist
* cpush
* cuninst
* cup

These now need to be removed completely.

Usage of these shims should be removed from the help documentation, and the genaratedocs.ps1 file should be updated to remove the explicit warnings about their removal in 2.0.0.

This is a follow up issue from this one in the 1.0.0 milestone: https://github.com/chocolatey/choco/issues/2641

**Comment by gep13** [comment]
@vexx32 I have a branch in the making that has these changes on it.

**Comment by sebma** [comment]
@gep13 Hi, these shims really came handy.

Do you know any replacement for those ?

**Comment by vexx32** [comment]
@sebma if using PowerShell, you can always define functions to replace them in your profile. For example:

```powershell
function cinst {
    choco install @args
}
```

**Comment by sebma** [comment]
@vexx32 Thanks for the function. I guess I will have to do on every new chocolatay install.

**Comment by gep13** [comment]
Nothing to stop you creating a package with these commands, and installing that package on initial installation.

**Comment by sebma** [comment]
@gep13 You're right. I will have to learn how to do that.

You wrote : 
> These now need to be removed completely.

One last question : Why ?

**Comment by gep13** [comment]
>@sebma said:
One last question : Why ?

This was done for consistency in terms of usage of Chocolatey.

In the 1.0.0 release of Chocolatey, we removed the `cpack` alias due to a conflict with the CMake application.  You can find details about that here:

https://github.com/chocolatey/choco/issues/89

Given that we are not able to have the cpack alias, the decision was taken to defer to default to using the `choco` command everywhere, and being very explicit about its usage.  In addition, it is a simple matter to add the PowerShell aliases for those folks who want to continue to use them.

**Comment by jeremyj563** [comment]
For anyone like myself who wants these shims back: https://community.chocolatey.org/packages/choco-shim-redirects
