### ISSUE TITLE
Bump version of 7za.exe shipped with Chocolatey

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/choco#2650]
The 7za.exe binary and supporting dlls/files we ship with Chocolatey is currently version 18.6.0.0. Can we look to bump this to a later stable version (21.07 appears to be latest as of time of writing this issue).

## References

[ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/13392)

**Comment by pauby** [comment]
As the 7zip bundled with Chocolatey CLI is only used internally, there is no requirement for a new version. In the past, it has usually been updated due to CVE's in 7Zip. However, I think it would make sense to maybe look at it for a future version.
