### ISSUE TITLE
PARSE PACKAGE PARAMETERS

### ISSUE THREAD

**Issue by Manoj496** [chocolatey/choco#2668]
I'm trying use the https://docs.chocolatey.org/en-us/guides/create/parse-packageparameters-argument#core-community-extension and install the package with choco install <pkg_id> --params "'/LICENSE:value'"``. 

Currently we've chocolatey version of "0.11.2", Does the Get-PackageParameters works in this version or Do I've to upgrade to latest to use the package

**Comment by TheCakeIsNaOH** [comment]
`Get-PackageParameters` has been available in Chocolatey CLI since `0.10.8`, so you can use it with Chocolatey `0.11.2` without needing to upgrade.

I've opened an issue here, as the documentation on that page does seem to be out of date.
https://github.com/chocolatey/docs/issues/430

If you have further questions, I'd suggest the Discord server, https://ch0.co/community

**Comment by Manoj496** [comment]
Hi @TheCakeIsNaOH but it's not working in 0.11.2, it's working after upgrading to latest available. It is skipping the installation to the path given choco install <pkg_id> --params "'/LICENSE:value'"``. eg: choco install <pkg_id> --params "'/customlocation:C:/users/somedir'". But when using the command with latest chocolatey I can see the package installed to the given path.

**Comment by TheCakeIsNaOH** [comment]
@Manoj496 

If I am understanding you correctly, package parameters are not working correctly with Chocolatey CLI `0.11.2` installed, but are working with `1.0.1`

If so, can't you just use Chocolatey CLI `1.0.1`?

**Comment by Manoj496** [comment]
Yes I understand that. I've upgraded to 1.0.1. Maybe you should update the docs appropriately.

**Comment by gep13** [comment]
@Manoj496 as @TheCakeIsNaOH mentioned, an issue has been created to update the docs in this area.  If this is something that you can help with, then feel free to raise a PR to address the problem, and we can get this merged in.

Regarding the underlying issue that is mentioned here, if you can provide a reproducible set of steps that demonstrate a problem with the older version of Chocolatey, we would like to know about it, as this cmdlet "should" be working in those older versions as well.
