### ISSUE TITLE
choco -r is generating non-essential output

### ISSUE THREAD

**Issue by mwallner** [chocolatey/choco#2675]
### What You Are Seeing?

`choco -r` is generating additional output.

### What is Expected?

`choco -r` should only display essential information.

### How Did You Get This To Happen? (Steps to Reproduce)

upgrade to choco v1.1 with old licensed extension.

### Output Log

```
 > choco outdated -r
WARNING!

You are running a version of Chocolatey that may not be compatible with
the currently installed version of the chocolatey.extension package.
Running Chocolatey with the current version of the chocolatey.extension
package is an unsupported configuration.

See https://ch0.co/compatibility for more information.

If you are in the process of modifying the chocolatey.extension package,
you can ignore this warning.

Additionally, you can ignore these warnings by either setting the
DisableCompatibilityChecks feature:

choco feature enable --name="'disableCompatibilityChecks'"

Or by passing the --skip-compatibility-checks option when executing a
command.
```

**Comment by mwallner** [comment]
I get it, this warning is pretty much everywhere unless chocolatey.extension is updated or the warning is explicitly disabled by setting the feature `disableCompatibilityChecks`.
Yet imo it should **NOT** break the `-r` switch that's widely used across automation scenarios. (it probably breaks the auto-upgrade of chocolatey.extension in many cases too, if users rely on `-r` actually producing parseable results 😟)

**Comment by gep13** [comment]
@mwallner thank you for taking the time to raise this!

Prior to shipping v1.1.0, we discussed this issue, a LOT!

It has long been the situation that running with the `-r` or `--limit-output` option will only show you the output from the command without any additional warnings/information, to provide a reliable way to parse the output.  However, in this situation, it was felt that leaving this warning in place was warranted.

When in this situation, the end-user is in an unsupported state, and we need to make sure that they are aware of this, and they have opted-in to continue in this state.  That is what the new feature flag, disableCompatibilityChecks, is for.

If, for whatever reason, the end user is not able to downgrade to an earlier version of Chocolatey, or to upgrade to a newer version of Chocolatey Licensed Extension, then they need to knowingly continue, knowing that all things might not work as expected.

Given that it is a simple, one time, command:

```
choco feature enable --name="'disableCompatibilityChecks'"
```

to remove these warnings, once you understand the ramifications of continuing, we felt that this was acceptable.

Based on this, I am going to close out this issue, but I appreciate you taking the time to raise this for discussion.
