### ISSUE TITLE
Run a script before uninstall/upgrade to allow for things like services to shutdown

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#268]
Do not fail if it fails though.

Current proposed name: `chocolateyBeforeRemove.ps1`

Migrated the evolution of the ideas from https://github.com/chocolatey/chocolatey/issues/291

**Comment by ferventcoder** [comment]
This is for you @darrelmiller

**Comment by darrelmiller** [comment]
Awesome.  Will try it out soon!

**Comment by ferventcoder** [comment]
This is only the ticket. A placeholder for the work. ;)

**Comment by darrelmiller** [comment]
Hehe.  I guess I need to read more closely.  Will wait with baited breath!

**Comment by mrdima** [comment]
Run chocolateyBeforeRemove.ps1 when you want to shut down a service before upgrade doesn't sound logical to me, I would expect a chocolateyBeforeUpgrade.ps1.
If you want to stop a service before uninstall, because for whatever reason the msi/exe uninstaller doesn't to that for you, can't you can just put that it in chocolateyUninstall.ps1 (which should always run before the auto-uninstaller if that's enabled?

**Comment by ferventcoder** [comment]
Before remove to signify it is run in upgrades and uninstalls - no reason to write tge same logic twice in your automation scripts.

**Comment by ferventcoder** [comment]
Might need a better name but it needs to signify that by the name that it is done prior to the upgrade/uninstall action and that it is not a script meant for handling the upgrade, only preparing for an upgrade or uninstall.

**Comment by mrdima** [comment]
Any reason why you propose 1 script for both upgrade and uninstall? And if you do an uninstall what can be done extra in chocolateyBeforeUpgrade.ps1 what cannot be done in chocolateyUninstall.ps1?

**Comment by ferventcoder** [comment]
Think of it like this - if you have a service running and you need to shut it down, you need to shut it down before ANY changes can be made.

So the uninstall script is still going to run on uninstalls, we are not replacing that.

Imagine for a second if you needed to shut down a service before upgrade or uninstall, and we only had a beforeUpgrade.ps1.  So now you need to include the exact same logic TWICE in your scripts, once for upgrades and once for uninstalls. Now every time you need to adjust that logic, you have to remember to adjust it in both places. That would not be maintainable and not much fun.

**Comment by mrdima** [comment]
Ok I get it. Would there be an option to know if you're running an upgrade or uninstall if there's things you only want to do during an upgrade? (I don't have a particular use-case at this moment, but I can imagine that you need to do something special only on upgrade)

**Comment by ferventcoder** [comment]
Right now, the thought wasn't there, but it could easily be passed the action that was about to occur. 

In some MSIs, folks want to uninstall before upgrading (mostly because some minor versions of MSIs don't always upgrade at all).

**Comment by RichardJFoster** [comment]
If this script is going to be applicable to both upgrade and uninstall scenarios, might chocolateyBeforeModify.ps be a better name for the script? My justification for the name is that it doesn't make sense to modify something that doesn't exist (the scenario where the package has not yet been installed), but (at least to me) both update and removal are clearly going to result in some sort of modification to the package in question.

**Comment by RichardJFoster** [comment]
Just realized I have another (potentially dumb) question about this. In the case where a package contains this script, which version of the script should be run? I was/am assuming that it would be the version of the script associated with the _currently installed_ version of the package when the update/uninstall operation is triggered. Is this correct, or is there any reason (in the case of an upgrade) why the version included in the update (new) package should be used instead? For example in the case of a forced reinstallation of the same package version I can see an argument for executing the script from the updated package.

**Comment by ferventcoder** [comment]
The script would be run from the currently installed package and if it fails will not cause a package failure (in cases where the script is bad).

**Comment by rhughesjr** [comment]
Until this is implemented, do you have any suggestion for a workaround? 

The package I've authored is internal to my company so I'm thinking about just making a script that will stop the services and then call choco uninstall. But this is definitely not an ideal soultion!

I was doing the service stopping in chocolateyUninstall.ps1, which worked fine in Chocolatey 0.9.8.x but I'm hitting a bit of a roadlock here in 0.9.9

**Comment by ferventcoder** [comment]
@rhughesjr have the folks stop the service prior to upgrade is a current workaround. Not ideal I know.

**Comment by rhughesjr** [comment]
I'm actually having a similar problem after installation too. The chocolateyInstall script has a step where it starts up the services that it installs.

Then, after that script completes, I see some of these errors:
 ```
Error computing hash for 'C:\ProgramData\chocolatey\lib\foo\foo.log'
   Hash will be special code for locked file or file too big instead.
   Captured error:
      The process cannot access the file 'C:\ProgramData\chocolatey\lib\foo\foo.log' because it is being used by another process.
```
So - it might be nice to also have a standard post-install script available.

**Comment by ferventcoder** [comment]
The hash error is really just a warning. I don't think it fails the install.

Post install script as well sounds nice for those that would need it. :)

**Comment by rhughesjr** [comment]
Oh, right, yes, I meant to say that. The install does succeed, but I've found that the users get very put off by warnings like that (even the highly-technical developers who are just unfamiliar with chocolatey).

**Comment by ferventcoder** [comment]
> Side note: Shouldn't the -r option hide warnings?

Interesting question. `-r` is about limiting the output, but not something that should be normally used. It's more for machine parseable output.

But it's still a good question. `-r` doesn't remove errors, but should it remove warnings?

**Comment by ferventcoder** [comment]
Interesting question. `-r` is about limiting the output, but not something that should be normally used. It's more for machine parseable output. Of course everyone uses choco differently and that's why there are options.

**Comment by rhughesjr** [comment]
Ah, I was not aware that it was intended to make it machine parseable. 

If not `-r`, then perhaps some sort of verbosity flag would be nice, akin to the /verbosity flag in [msbuild](https://msdn.microsoft.com/en-us/library/ms164311.aspx).

**Comment by ferventcoder** [comment]
> If not -r, then perhaps some sort of verbosity flag would be nice, akin to the /verbosity flag in msbuild.

That's the plan. Currently they are split.

**Comment by ferventcoder** [comment]
This will also allow for uninstalling MSI's that need it.

**Comment by RichardJFoster** [comment]
I keep getting dragged off to work on other things (no surprise there), so this is going slower than I had hoped. I just pushed my work-in-progress modifications which _appear_ to be functional. Per the discussions in the gitter room, I plan to do some refactoring before making a pull request. Having said that, changesets 932e08e33 and 1f35a818a6 _may_ be worth incorporating.

I still haven't decided on the "best" way to refactor. I am currently leaning towards adding a run_script_set method to the IPowershellService where a "script set" will be an IEnumerable of script information - probably including the path to the script along with a flag to indicate if an error running that script can be ignored or if it should terminate processing of any subsequent scripts. The selection of which scripts get run in each scenario would then get moved into the ChocolateyPackageService. Does this make sense?

**Comment by RichardJFoster** [comment]
Oh... and if anyone has any comments/concerns on the stuff I pushed so far, let me have it. Most of my previous open-source contributions have either been extremely trivial, or documentation related. :-)

**Comment by ferventcoder** [comment]
Refactoring commits are usually not maint commits. Let's try to keep it to the actual issue that this is related to. `(GH-268)` should be the very fist part of every commit message if not a maint. :)

**Comment by ferventcoder** [comment]
The trick to note is *when* and *which* package has the beforeUpgrade script - as in when you are upgrading version `1.0.0` to version `2.0.0`, the beforeUpgrade is run from version `1.0.0`. And if it fails, it is only a warning.

**Comment by ferventcoder** [comment]
That distinction is the most interesting in the design phase.

**Comment by RichardJFoster** [comment]
Yup. That's why changeset aad8ebf26fdb modified UpgradeScenarios.cs in a way that verifies it was the script from the original package. ;-) Good point about the _when_ though. I should probably have automated verification not only that the script is run, but also that it runs before the new version's install script.

**Comment by darrelmiller** [comment]
Really happy to see this feature.  I have big plans for this :-)
