### ISSUE TITLE
Support Semvar2.0.0

### ISSUE THREAD

**Issue by adavis753** [chocolatey/choco#2680]
This would be resolved by #508 

Nuget 4.3.0 support packages with version that meet the [SemVer2.0.0](https://semver.org/spec/v2.0.0.html) standard.  This functionality would be useful in chocolatey.

**Comment by TheCakeIsNaOH** [comment]
Hey, @adavis753 there is already an issue for this: https://github.com/chocolatey/choco/issues/1610
