### ISSUE TITLE
RC file with common switches/arguments

### ISSUE THREAD

**Issue by ghost** [chocolatey/choco#269]
I think it's better set things like custom installation directories on one single file! :)

**Comment by ferventcoder** [comment]
Benefit over a config file?

**Comment by ferventcoder** [comment]
@vyscond following up, have you had an opportunity to review my questions?

**Comment by vyscond** [comment]
The time i tried using choco, i had to pass the custom path on every call :( I'am not using it right, maybe i just missed some other smart way todo that, but the goal to make work like __bower__ does with _bowerrc_ file.

**Comment by ferventcoder** [comment]
What benefit does this have over the existing configuration file?

**Comment by ferventcoder** [comment]
I think I'm starting to understand what it might be, but I'd like to get that solidified.

**Comment by pauby** [comment]
I'm going to go ahead and close this, but we can reopen it if necessary.
