### ISSUE TITLE
Path not updated after choco install via openssh.

### ISSUE THREAD

**Issue by 3735943886** [chocolatey/choco#2694]
### What You Are Seeing?
Path not updated after `choco install` by remote OpenSSH SSH Server.
Even after I logout and reconnect ssh, path still not updated I cannot launch packages installed by chocolatey.
It looks like that refreshenv updates path but for only current session, so path changed back when reconnect ssh.
After restart `sshd` service, path is normally updated and works fine thereafter.

### What is Expected?
Path should be updated after reconnecting ssh session.
(or at least refreshenv should work without restarting sshd service)

### How Did You Get This To Happen? (Steps to Reproduce)
1. `ssh` to connect target windows system.
2. `choco install [package]`
3. cannot launch [package]  since path not updated.
4. log out and reconnect ssh but path still not updated and cannot launch [package]
5. if `refreshenv` to update path, path is updated and `[package]` can be launched, but path changed back when reconnect ssh.

**Comment by corbob** [comment]
That sounds like it's working exactly as I would expect it to. When you connect via SSH, the new shell will inherit the environment of the parent process (ssh service). Until that service is restarted, it won't see the updated path environment variable.

**Comment by 3735943886** [comment]
> That sounds like it's working exactly as I would expect it to. When you connect via SSH, the new shell will inherit the environment of the parent process (ssh service). Until that service is restarted, it won't see the updated path environment variable.

Thank you for prompt answer.
It's a little bit tough to restart service everytime installing something.
Would you please let me know if is there any way to update path of current running sshd service?

**Comment by corbob** [comment]
The only way I know of that might work (although in my experience I haven't seen much other than explorer.exe actually pick up on the changes) is something like this: https://github.com/ambakshi/win32-notifychanges. It is possible to do it from PowerShell/.Net, but I'm not sure of the incantation off the top of my head.

**Comment by pauby** [comment]
I'm going to go ahead and close this issue, but we can reopen it if necessary.

**Comment by 3735943886** [comment]
I took a look of source code, [Get-EnvironmentVariable.ps1](https://github.com/chocolatey/choco/blob/develop/src/chocolatey.resources/helpers/functions/Get-EnvironmentVariable.ps1) and [Set-EnvironmentVariable.ps1](https://github.com/chocolatey/choco/blob/develop/src/chocolatey.resources/helpers/functions/Set-EnvironmentVariable.ps1).
And I guessed that choco updates path by `registry` and `[environment]::SetEnvironmentVariable`.
I tested `[environment]::SetEnvironmentVariable` and it **COULD UPDATE** environment without restarting sshd service.
Therefore, choco also should be able to update path without restarting sshd service.
Screenshots are attached. Thank you.
![session1](https://user-images.githubusercontent.com/9522390/165413701-244b3d16-c76f-4ef3-88d1-2903ff770f7d.png)

![session2](https://user-images.githubusercontent.com/9522390/165413711-d47f3260-d707-442b-af5f-866c01b3da5d.png)
