### ISSUE TITLE
when i try to update my packages: was not found with the source(s) listed.

### ISSUE THREAD

**Issue by jonasmarco** [chocolatey/choco#2695]
Hello everyone,

today i tried to update my packages on windows, and i am getting the following message for all packages:

7zip was not found with the source(s) listed.
  If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
  Version: ""; Source(s): "https://community.chocolatey.org/api/v2/"
  The 'NuGet.ProxyCache' type initializer threw an exception.

![image](https://user-images.githubusercontent.com/19959770/164468975-b0539365-527d-4883-91ff-5aed3b1e1894.png)

![image](https://user-images.githubusercontent.com/19959770/164469047-ac39f9ee-cf02-418f-abd2-fea7ca13a182.png)

**Comment by pauby** [comment]
@jonasmarco Before we can look at this can you go back and complete the issue template?
