### ISSUE TITLE
Replace existing build automation tool (UppercuT) with Cake

### ISSUE THREAD

**Issue by gep13** [chocolatey/choco#2699]
The decision has been taken to switch to using [Cake](https://cakebuild.net) as the build automation tool, rather than UppercuT (which is what is currently being used).

**Comment by TheCakeIsNaOH** [comment]
Related, or perhaps duplicate: https://github.com/chocolatey/choco/issues/2400

**Comment by gep13** [comment]
@TheCakeIsNaOH doh! Thanks for catching that!
