### ISSUE TITLE
Path not updated after choco install via openssh

### ISSUE THREAD

**Issue by 3735943886** [chocolatey/choco#2704]
I reported issue #2694 and it's closed already, but now I have some test results and report issue again.

### What You Are Seeing?
Please note that path not updated even after reconnect ssh normally.

↓ git not launched because path not updated. ↓
![s1_git_install](https://user-images.githubusercontent.com/9522390/165678702-10ee8b14-bfcf-4792-8d64-dda7aefcc1a6.png)

↓ ssh reconected but git still not launched. ↓
![s2_no_path](https://user-images.githubusercontent.com/9522390/165678712-8938e4ce-1e11-4ced-a9f4-503cc1b07fe4.png)

### What is Expected?
I looked up the `choco` source codes and `packages` seem to update their path via internal function [Set-EnvironmentVariable](https://docs.chocolatey.org/en-us/create/functions/set-environmentvariable). (Please understand if I was wrong. I'm not powershell script expert.)
After some researching, `Set-EnvironmentVariable` looks like updating environment variables by `editing registry` and `[environment]::SetEnvironmentVariable`.

I tested `[environment]::SetEnvironmentVariable` and it could update environment without restarting sshd service.
Please refer to screenshots below.

↓ I registered two user scope environment variables via `[environment]::SetEnvironmentVariable` and `$Env`. Please note that `VALUE1` is not accessible by `$Env(current session environment values)` ↓
![s3_set_env](https://user-images.githubusercontent.com/9522390/165679149-24062a79-680c-4a53-ab63-aa7997595ed7.png)

↓ After reconnect ssh, `VALUE1` is now accessible by `$Env` without restarting sshd service. ↓
![s4_get_env](https://user-images.githubusercontent.com/9522390/165679154-ab164510-7692-4d75-b0ab-136c846a693a.png)

So I concluded that there is already a way to update path without restarting sshd service in choco itself, but not just used at this time.
Would you developers please consider this issue?
Thank you.

**Comment by corbob** [comment]
This is interesting, but I'm not sure it's quite an apples to apples comparison. @3735943886 would you be able to use that same method to set `PATH` to something, then see if that variable in particular is updated? I would suspect that PATH is treated differently because it's an amalgamation of both User and System environments.

**Comment by 3735943886** [comment]
My apologies. 
Machine scope path won't be updated without restarting sshd service.
