### ISSUE TITLE
choco install dotnet-5.0-windowshosting gives error

### ISSUE THREAD

**Issue by qamarkhan84** [chocolatey/choco#2717]
Hi there,

Today i found strange issue  when run the command **choco install dotnet-5.0-windowshosting** . I am sure this was working until day before
So tried to run the following command
choco install dotnet-5.0-windowshosting

And i got the error as mentioned in screenshot

ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://download.visualstudio.microsoft.com/download/pr/a0832b5a-6900-442b-af79-6ffddddd6ba4/e2df0b25dd851ee0b38a86947dd0e42e/dotnet-runtime-5.0.17-win-x64.exe'. Exception calling "GetResponse" with "0" argument(s): "The operation has timed out"

![image](https://user-images.githubusercontent.com/98837075/167898424-c636bf9e-988d-4fd9-b7f1-5fc2ee90f688.png)

Few more logs
![image](https://user-images.githubusercontent.com/98837075/167899621-668f4584-028e-4ced-87a7-8f5aa5e19280.png)

i can see it failed  because this link does not work https://download.visualstudio.microsoft.com/download/pr/06ed1d94-3f28-47a5-8025-e7bf9da634da/2ACBFE92157C1CF1A7B524A9325824046D83DBFA3FEB1CBD4DD02A42E020F77C/VC_redist.x86.exe

Any help would be appreciated 
Thanks

**Comment by pauby** [comment]
This isn't a Chocolatey issue or a package issue. This is related to this [Discord comment](https://discord.com/channels/778552361454141460/897088817293574154/973969585101492334) and this [Microsoft issue](https://developercommunity.visualstudio.com/t/Visual-Studio-Installer-Checking-for-up/10037277#T-N10037573).
