### ISSUE TITLE
Odd issue with chocolateyPackageParameters string truncation

### ISSUE THREAD

**Issue by RobBiddle** [chocolatey/choco#2719]
### What You Are Seeing?
For at least a few months now we've been seeing an odd issue related to chocolateyPackageParameters.
The issue is with a custom choco package for Office Deployment Tool that we've been using for 5+ years and only recently started having issues on _some_ systems while it continues to function on others. I'm looking for assistance determining what is causing the difference in behavior.

On some systems the chocolateyPackageParameters seen by chocolateyinstall.ps1 are only partially set in the variable, others are working as expected with the full string. The string passed via choco command is identical in both instances. The string is built as part of PowerShell DSC builds so there should not be any differences. I've confirmed the source data for the configurations are both UTF-8 CRLF formatted so encoding of source data is the same.

Systems are automated builds so they should all be mostly identical, however some have been running for various lengths of time and we do have a few different OS versions in use. 
The issue does not seem to be correlated with any specific Windows version/build.
Most systems are:
Windows 2022 Server Datacenter Edition
```
Version    BuildNumber
-------    -----------
10.0.20348 20348
```
Choco is the same version on all systems
`Chocolatey v1.1.0`

### What is Expected?
`$env:chocolateyPackageParameters` is expected to contain string of parameters passed

### How Did You Get This To Happen? (Steps to Reproduce)
I output the package parameters at the beginning of the install script so that I can verify they are correct, this happens before any parsing/manipulation. e.g **chocolateyinstall.ps1** contains the following:
```PowerShell
$packageParameters = $env:chocolateyPackageParameters
Write-Output "packageParameters are: $packageParameters"
```
CMD run via PowerShell:
```PowerShell
C:\choco\bin\choco.exe upgrade upic-office365-2016-deployment-tool --force --yes --params "'/Download /64bit /Channel:MonthlyEnterprise /ExcludeGroove /ExcludeLync /RDSHCollection:MyDesktop'"
```

### Output Log
On **working** systems the choco output shows:
`packageParameters are: /Download /64bit /Channel:MonthlyEnterprise /ExcludeGroove /ExcludeLync /RDSHCollection:MyDesktop`

On **broken** systems the choco output shows:
`packageParameters are: /Download`

On **BOTH** systems when running the same CMD via PowerShell with `--noop -d` the output is identical. 
I used a text comparison tool to confirm.
```PowerShell
C:\choco\bin\choco.exe upgrade upic-office365-2016-deployment-tool --noop -d --force --yes --params "'/Download /64bit /Channel:MonthlyEnterprise /ExcludeGroove /ExcludeLync /RDSHCollection:MyDesktop'"
```
The choco detailed output makes it seem like the parameters are received.
```
Chocolatey v1.1.0
Chocolatey is running on Windows v 10.0.20348.0
Command line: "C:\choco\choco.exe" upgrade upic-office365-2016-deployment-tool --noop -d --force --yes --params "'/Download /64bit /Channel:MonthlyEnterprise /ExcludeGroove /ExcludeLync /RDSHCollection:MyDesktop'"
Received arguments: upgrade upic-office365-2016-deployment-tool --noop -d --force --yes --params '/Download /64bit /Channel:MonthlyEnterprise /ExcludeGroove /ExcludeLync /RDSHCollection:MyDesktop'

```
AND
```
PackageNames='upic-office365-2016-deployment-tool'|Prerelease='False'|
ForceX86='False'|OverrideArguments='False'|NotSilent='False'|
PackageParameters='/Download /64bit /Channel:MonthlyEnterprise /ExcludeGroove /ExcludeLync /RDSHCollection:MyDesktop'|
```
Since choco seems to have received the parameter string in both cases, I don't know why `$env:chocolateyPackageParameters` would be populated correctly on one system and truncated on another.

**Comment by vexx32** [comment]
Thanks for the report!

Are you able to post the full output log / a link to it, from both a broken run and a run where it works as expected? There definitely seems to be something odd going on here, but reproducing it seems to be difficult. Having the full log output should help us track down exactly where it's going wrong. 🙂

**Comment by pauby** [comment]
Due to this issue being stale, I'm going to go ahead and close it. We can always re-open it again if needed.
