### ISSUE TITLE
`choco feature enable` has non-obvious behavior

### ISSUE THREAD

**Issue by alexchandel** [chocolatey/choco#272]
For example, the command:
```
choco enable -n=allowGlobalConfirmation -n=autoUninstaller
```
will only enable `autoUninstaller`. Is there a reason the features are flags and not arguments, like `choco enable allowGlobalConfirmation autoUninstaller`?

**Comment by ferventcoder** [comment]
Sounds like we need more validation - it's a one at a time kind of command.

Also in choco terminology, flags are switches, if they accept a value they are an option or a parameter

**Comment by ferventcoder** [comment]
@alexchandel apologies, sounds like we need to fix up the help menu - when you ran `choco feature -h` or `choco feature /?`, what example or wording in the documentation lead you to believe that you could pass two features?

**Comment by ferventcoder** [comment]
@alexchandel following up, have you had a chance to review my questions and provide a response?

**Comment by alexchandel** [comment]
@ferventcoder yes, sorry about the delay! Basically, I would never assume that flags can't be passed multiple times. Possibly because of the nature of a `feature` toggling command, using the subcommand `enable` with a flag like `-n` to filter the key to be changed naively implies to me that multiple `-n` flags would work. Or are there plans to make `choco feature enable` toggle the value of every `--name` passed? Alternatively, are there plans to add other filters to `choco feature enable`, allowing features to be specified some way other than by name/`-n`?

To give a counterexample, I would expect a command whose usage was:
```powershell
choco feature list
choco feature enable <name>
choco feature disable <name>
```
to only accept a single feature name to toggle.

**Comment by alexchandel** [comment]
Compare also OS X's `defaults`:
```sh
defaults read com.apple.finder CreateDesktop
defaults write com.apple.finder CreateDesktop -bool false
```

**Comment by ferventcoder** [comment]
I still have to ask, what part of the help menu lead you to believe that you could pass more than one feature? 

> Possibly because of the nature of a feature toggling command, using the subcommand enable with a flag like `-n` to filter the key to be changed naively implies to me that multiple `-n` flags would work. 

So carry this forward across every option in all of choco - do you assume that because you specify an option like `-source` (or for the sake of argument `-s`), that you can pass multiple `-s` arguments? 

Same goes for the following install/upgrade/possibly uninstall args:
* `--installargs`
* `--version`
* `--params`
* `--user` (`-u`)
* `--password` (`-p`)

Same goes for the following `choco source` options:
* `--name` (`-n`)
* `--user` (`-u`)
* `--password` (`-p`)

**Comment by ferventcoder** [comment]
I guess what I'm leading to state here is that the manual doesn't tell you nor does it show you an example where it accepts multiple values:

```sh
Usage

    choco feature [list]|disable|enable [<options/switches>]

Examples

    choco feature
    choco feature list
    choco feature disable -n=bob
    choco feature enable -n=bob
```

Unlike package names as part of choco install/upgrade where it does state that multiple values are accepted:

```sh
Usage

    choco install <pkg|packages.config> [<pkg2> <pkgN>] [<options/switches>]
    cinst <pkg|packages.config> [<pkg2> <pkgN>] [<options/switches>]

NOTE: For packages.config, please see https://bit.ly/packages_config

Examples

    choco install sysinternals
    choco install notepadplusplus googlechrome atom 7zip
    choco install notepadplusplus --force --force-dependencies
    choco install notepadplusplus googlechrome atom 7zip -dvfy
```
(some output that doesn't add or remove from this conversation has been removed)

**Comment by ferventcoder** [comment]
I guess what I'm getting at is if you are asking for the ability to pass multiple values to feature to enable or disable, ask for that as an enhancement. But don't state that the behavior is non-obvious when the documentation is super clear about the behavior.

**Comment by ferventcoder** [comment]
> Basically, I would never assume that flags can't be passed multiple times. 

And this is where the documentation will correct this assumption. It's not possible to pass options multiple times and get the results you would expect, unless the documentation states otherwise.

**Comment by ferventcoder** [comment]
I've added the following to help future folks out - https://github.com/chocolatey/choco/wiki/CommandsReference#how-to-pass-options--switches

* Unless stated otherwise, an option/switch should only be passed one time. Otherwise you may find weird/non-supported behavior.

**Comment by ferventcoder** [comment]
This will also make it's way back into choco.

**Comment by aronovgj** [comment]
I must say that I also tried multiple features in one command and after some googleing I concluded that this is not possible. I guess what @alexchandel is trying to say is that it is unintuitive although the help menu is very clear.

**Comment by ferventcoder** [comment]
That's a fair statement. :)

**Comment by ferventcoder** [comment]
I'm not a huge fan of -n for choco feature or choco pin. Let's file an enhancement to make the command more intuitive. :)

**Comment by ferventcoder** [comment]
@alexchandel @aronovgj I wouldn't assume that the way these things are is in a state of how they should be. :) 

I totally agree with the idea of removing `-n` from the equation, but I see it more as 

`choco feature enable feature1 <feature2 featureN>` - I filed #288 to follow up on this. 

I filed #289 for the pin command enhancements.

**Comment by ferventcoder** [comment]
Apologies - unintuitive to me means something different than non-obvious, even though they are basically the same thing in concept. I didn't mean to come across as rude (if I did).

**Comment by ferventcoder** [comment]
I prefer instead that filed issues address a path forward (or work that is actionable). The question of unintuitive or non-obvious behavior is much better a conversation to be had in gitter or on the mailing list. We try to state as much in the CONTRIBUTING document.

**Comment by ferventcoder** [comment]
Since this has two followups to change the behavior, I'm going to close this.

**Comment by alexchandel** [comment]
I think #288 resolves this well.
