### ISSUE TITLE
Unattended installation of Chocolatey without admin rights aren't possible.

### ISSUE THREAD

**Issue by smspillaz** [chocolatey/choco#274]
`chocoInstall` calls `choco unpackself` which [throws up a prompt if the shell is not elevated or running as an admin user](https://github.com/chocolatey/choco/blob/3f04fc06ecd59948183ebf0e20a6e7abff0007c4/src/chocolatey/infrastructure.app/runners/GenericRunner.cs#L148).

This blocks the installation on user input, which makes unattended installations without admin rights impossible at the moment (which is important for CI like environments or scripts).

**Comment by ferventcoder** [comment]
Darn, there is an issue in here somewhere.

**Comment by ferventcoder** [comment]
Reopening for now while I investigate.

**Comment by smspillaz** [comment]
@ferventcoder thanks :)
