### ISSUE TITLE
Handle if the build fails in the vagrant test environment

### ISSUE THREAD

**Issue by corbob** [chocolatey/choco#2742]
I think this was my contribution... and I'm wondering why I assigned to the variable, but didn't actually use it... It's possible that I wanted to do something with the output inside the if block that's next... but it certainly wasn't to actually output it (because it'll likely cause vagrant errors...) Perhaps output to a file?

I guess my question in all this is: Do we want to put the output somewhere if it fails? And if so, can we put it in a file and tell them they can look in the file for more details?

_Originally posted by @corbob in https://github.com/chocolatey/choco/pull/2706#discussion_r868130888_

**Comment by gep13** [comment]
@corbob can you please get the template for this issue updated?
