### ISSUE TITLE
Simple document update for use of -whatif/-noop

### ISSUE THREAD

**Issue by TwistedDigits** [chocolatey/choco#276]
Spent a while trying to find out how to check to see which packages needed to be updated, it was shown in the command reference but didn't explain what it does.  I've slow internet where I am at the moment so don't always want to upgrade everything and probably something others would want to do.

To check which packages need to be upgraded use the following command:
 choco upgrade all -whatif
or 
 choco upgrade all -noop

**Comment by ferventcoder** [comment]
I'm not completely sure what you are asking for here. You want better documentation surrounding checking for upgrades?

**Comment by TwistedDigits** [comment]
Just thought it would be handy for people if you had an example of how check to see which packages needed to be updated on the Update page of the wiki.  Great app by the way!

**Comment by ferventcoder** [comment]
I see, you are correct. We need to add something there for checking for upgrades. :)

**Comment by pauby** [comment]
> Spent a while trying to find out how to check to see which packages needed to be updated.

The `choco outdated` command will do this.

I'm going to go ahead and close this, but we can reopen it if necessary.
