### ISSUE TITLE
Feature support for Virtual Clone Drive

### ISSUE THREAD

**Issue by xkpx64** [chocolatey/choco#2768]
## Is Your Feature Request Related To A Problem? Please describe.
No.

## Describe The Solution. Why is it needed?
Becouse its good for comminity to have it.

## Additional Context.
Remember old daemon tools without ads. Now you can have it again. 

## Related Issues
No.

==== 
Link https://www.elby.ch/products/vcd.html

**Comment by TheCakeIsNaOH** [comment]
Closing as no response.
