### ISSUE TITLE
`choco config`: Please allow to configure the ToolsLocation

### ISSUE THREAD

**Issue by schittli** [chocolatey/choco#2780]
N/A: Why it's not applicable

## Is Your Feature Request Related To A Problem? Please describe.
It looks like `Get-ToolsLocation` always defaults to `c:\Tools` in a new choco session 😞.
Yes, it's a problem:
- There are reasons, when `c:\Tools` cannot be used, for example:
  - if this Directory is already reserved and used e.g. by a project
  - if the Company policy requests to always install Chocolatey Packages into a specific folder (because e.g. it has higher security risks)
  - …
- it's a problem because choco does not work intuitive / as expected 😞, for example:
  - If the IT sets up a computer and installs all company choco packages into e.g. `c:\bin-choco`
  - Then one expects that every further call of `choco install` will work with the directory again
  - So if a user uses `choco install` again three months after the IT departement, the packages are distributed to `c:\tools` and `c:\bin-choco` 😢 

## Describe The Solution. Why is it needed?

Please:
1. Allow us to use something like: `choco config set --name toolsLocation --value=…` to make this setting persistent
2. Describe how to use the Tools-Location (not only how to read the location, **but also** how to set this config in choco!) [Docs: path-provided-by-the-get-toolslocation-helper](https://docs.chocolatey.org/en-us/create/create-packages#path-provided-by-the-get-toolslocation-helper)
3. Then, `choco install` always uses this configuration until it gets changed (of course 😀) 

## Additional Context.
N/A

## Related Issues
N/A

**Comment by corbob** [comment]
According to the [docs](https://docs.chocolatey.org/en-us/create/functions/get-toolslocation) you can set this in an environment variable. Are you not seeing this environment variable being used by the helper function?

**Comment by TheCakeIsNaOH** [comment]
@schittli did the previous comment provide an answer?

**Comment by pauby** [comment]
As there has been no update to this, I'm going to go ahead and close this issue, but we can reopen it if necessary.
