### ISSUE TITLE
Autocompletion does not work for me

### ISSUE THREAD

**Issue by ireun** [chocolatey/choco#2783]
### What You Are Seeing?
Autocompletion `choco inst>tab>` does not work for me.

### What is Expected?
To work, I've followed steps mentioned in https://docs.chocolatey.org/en-us/troubleshooting#why-does-choco-intab-not-work-for-me my profile looks like this:

```ps1
# Import the Chocolatey Profile that contains the necessary code to enable
# tab-completions to function for `choco`.
# Be aware that if you are missing these lines from your profile, tab completion
# for `choco` will not function.
# See https://ch0.co/tab-completion for details.
$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
if (Test-Path($ChocolateyProfile)) {
  Import-Module "$ChocolateyProfile"
}
Import-Module posh-git
Import-Module -Name Terminal-Icons
oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\M365Princess.omp.json" | Invoke-Expression
```

### How Did You Get This To Happen? (Steps to Reproduce)

1. type `choco inst`
2. press TAB
3. nothing happens

### System Details

* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`): 10.0.19044.0
* Windows PowerShell version (Run: `$PSVersionTable`): 5.1.19041.1682
* Chocolatey version (Run `choco --version`): 1.1.0

**Comment by gep13** [comment]
@ireun just to confirm... have you restarted the PowerShell (or importer the profile again) since you made the change to the file?

**Comment by ireun** [comment]
@gep13 Yes, of course, that did not helped.  I may say though that oh-my-posh and posh-git work correctly..

**Comment by gep13** [comment]
What happens if you remove, temporarily, the other module imports? The reason I ask is that I know this works, as I use it personally.

There is a video of the setup here:

https://youtu.be/jdZrigvxwws

It could be that there is an incompatibility between the modules.

**Comment by ireun** [comment]
Huh, after some tinkering I've ended up with this profile:
```ps1
Import-Module posh-git
Import-Module -Name Terminal-Icons
oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\M365Princess.omp.json" | Invoke-Expression
$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
if (Test-Path($ChocolateyProfile)) {
  Import-Module "$ChocolateyProfile"
}
```

Looks like everything is working now. Thank You very much for Your help. Have a nice day! :)
