### ISSUE TITLE
Deprecate side-by-side installs

### ISSUE THREAD

**Issue by pauby** [chocolatey/choco#2787]
## Is Your Feature Request Related To A Problem? Please describe.

Side-by-side installs are planned to be deprecated in a future (potentially version 2.0) of Chocolatey CLI. We need to ensure we properly deprecate this in the collection.

Note that _before_ this is deprecated, we will have documentation describing the options available to continue to have similar functionality.

## Describe The Solution. Why is it needed?

Side-by-side installs are being deprecated.

## Additional Context.

_Before_ this is deprecated, we will have documentation describing the options available to continue to have similar functionality.

## Related Issues

None.

**Comment by corbob** [comment]
The Licensed Extension extends the Info command. Our current tests expect it to output a deprecation message. We will want to assess if we duplicate that message into the Licensed Extension, or update the test to be FOSSOnly. Added the Upstream Change label for tracking, and will discuss more at planning meeting.

**Comment by pauby** [comment]
This is being reopened as we need to pickup this task:

- [ ] Before this is deprecated, we will have documentation describing the options available to continue to have similar functionality.

What was needed here was documentation that explained the alternative to side-by-side installs and specifically why it needs done. This was envisaged being a page in the docs.

**Comment by AdmiringWorm** [comment]
@pauby I have created an issue on the docs repository to track the progress of this here: https://github.com/chocolatey/docs/issues/581

**Comment by pauby** [comment]
@thoscut The reason this is being removed is that it never worked the way it was intended to, caused us no end of support issues for a very small number of customers who used it.

The intention was to create the document before the release so it was available. That was unfortunately missed and is on me.

**Comment by pauby** [comment]
@viceice This issue is closed. Can you raise a separate issue for this? I'm assuming you didn't install those KB packages as side-by-side installs.

I'm going to lock this issue now to prevent comments that would be missed by the team.
