### ISSUE TITLE
NASM is not added to path when installed

### ISSUE THREAD

**Issue by Stadly** [chocolatey/choco#2794]
### What You Are Seeing?
When installing NASM, it is not added to the path.

### What is Expected?
That NASM is added to the path when installed

### How Did You Get This To Happen? (Steps to Reproduce)

1. choco install --confirm nasm
2. Investigate the path environment variable to see if NASM is there

### System Details

* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`): 10.0.22000.0
* Windows PowerShell version (Run: `$PSVersionTable`):
```
Name                           Value
----                           -----
PSVersion                      5.1.22000.653
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.653
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
* Chocolatey version (Run `choco --version`): 1.1.0

**Comment by pauby** [comment]
This looks to be a package issue. Can you reach out to the package maintainer by using the 'Contact Maintainer' link on the package page?

I'm going to go ahead and close this issue, but we can reopen it if necessary.

**Comment by Stadly** [comment]
This seems to be an old issue: https://bugzilla.nasm.us/show_bug.cgi?id=3392224

**Comment by ZeunO8** [comment]
Any ideas why this is still an issue even today?

**Comment by corbob** [comment]
> Any ideas why this is still an issue even today?

Probably because no one has addressed it from NASM, and no one took the suggestion from pauby to contact the package maintainers.

As this issue is long closed, and is related to a package I'll go ahead and lock it to reduce notifications to any watchers.
