### ISSUE TITLE
update Adobe Acrobat Reader DC

### ISSUE THREAD

**Issue by rajacyber** [chocolatey/choco#2796]
"Error upgrading application Adobe Acrobat Reader DC - \nWARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else

please anyone help me why im getting this error.

**Comment by pauby** [comment]
This is a package issue and not a Chocolatey CLI one.  Please see the Description on the package page or use a search engine to find information about the generic error.

**Comment by rajacyber** [comment]
@pauby how to fix this issues can u pls tell me

**Comment by pauby** [comment]
@rajacyber Please see the comment I left above.
