### ISSUE TITLE
linux mono choco push from github action results in 403

### ISSUE THREAD

**Issue by fbpyr** [chocolatey/choco#2800]
First of: thank you so much for the awesome chocolatey project! 

### What You Are Seeing?
When attempting to push a successfully built package from github action 
to https://push.chocolatey.org/ I get `(403) Forbidden..` .

### What is Expected?
Package should get pushed successfully without 403. 
Ideally the error message could clarify the specific error at hand - currently it just says:  `(403) Forbidden..` 
without giving a hint on why one would not be able to push. (e.g. invalid apikey)

If there is a potential restriction of pushing with the unofficial choco build or pushing directly from github, 
it would be great, if that could be documented in: 
https://docs.chocolatey.org/en-us/create/commands/push

### How Did You Get This To Happen? (Steps to Reproduce)
Used github action: 
https://github.com/fbpyr/IfcOpenShell/blob/v0.7.0/.github/workflows/ci-blenderbim-matrix.yml 
Same commands were used before to successfully push the same package to 
https://community.chocolatey.org/packages/blenderbim-nightly/ 
from Docker image (also Ubuntu 20.04.4 LTS) on local machine - 403 did not show up back then. 
Now I also get 403 on docker on local machine.

### System Details

* OS Build: Ubuntu 20.04.4 LTS docker container in github action
* Windows PowerShell version: not applicable - linux container, commands run in bash version: GNU bash, version 5.0.17
* Chocolatey version : 1.1.0 (built in ubuntu docker container with mono)

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh

...

__choco pack
Chocolatey vfatal: not a git repository (or any of the parent directories): .git


Chocolatey is not an official build (bypassed with --allow-unofficial).
 If you are seeing this message and it is not expected, your system may
 now be in a bad state. Only official builds are to be trusted.

Attempting to build package from 'blenderbim.nuspec'.
Successfully created package '/home/runner/work/IfcOpenShell/IfcOpenShell/choco/blenderbim/blenderbim-nightly.0.0.220819.nupkg'

Did you know Chocolatey goes to eleven? And it turns great developers /
 system admins into something amazing! Singlehandedly solve your
 organization's struggles with software management and save the day!
 https://chocolatey.org/compare
__choco set apiKey
Chocolatey vfatal: not a git repository (or any of the parent directories): .git

Chocolatey is not an official build (bypassed with --allow-unofficial).
 If you are seeing this message and it is not expected, your system may
 now be in a bad state. Only official builds are to be trusted.

Updated ApiKey for https://push.chocolatey.org/
__choco push
Chocolatey vfatal: not a git repository (or any of the parent directories): .git

Chocolatey is not an official build (bypassed with --allow-unofficial).
 If you are seeing this message and it is not expected, your system may
 now be in a bad state. Only official builds are to be trusted.

Attempting to push blenderbim-nightly.0.0.220819.nupkg to https://push.chocolatey.org/
PUT https://push.chocolatey.org/api/v2/package/
Failed to process request. 'Forbidden'.
The remote server returned an error: (403) Forbidden..



~~~

</p>

</details>

**Comment by corbob** [comment]
It looks like that package only has a single version that is still in moderation. My understanding is that the community repository will return 403 on new versions of the package until at least one of them has passed moderation. I've added this to the docs issue for documenting these common errors with the community repository: https://github.com/chocolatey/docs/issues/426

**Comment by fbpyr** [comment]
@corbob thank you so much for the quick response! 🙂 
Indeed it is still in the human moderation phase - makes sense, that it blocks as long as the first moderation is not finished. 
Yes, documentation on that would help a lot!
