### ISSUE TITLE
Add package author to environment variables in powershell session

### ISSUE THREAD

**Issue by we-mi** [chocolatey/choco#2832]
## Is Your Feature Request Related To A Problem? Please describe.

This is not related to a problem. This is just for convenience when automating package creation (see next section)

## Describe The Solution. Why is it needed?

We are heavily internalizing packages in our company and using package templates for different kinds of installers (MSI,EXE,ZIP, etc).  

We are also separating the setup files from the nupkg-files and therefore downloading the setup from an internal server from within `chocolateyInstall.ps1`.  

We currently organize the setups in this folder structure: `<PackageAuthor>\<PackageName>\<PackageVersion>.msi|exe|zip|etc`.  
The `url`-Variable which is passed to `Install-ChocolateyPackage` (or another function which downloads the setup) might look like this for our `firefox` package:  

`https://<InternalServer>/Mozilla/$($env:ChocolateyPackageName)/$($env:ChocolateyPackageVersion).msi`

It would be really nice to implement the Package Author as an environment variable like `$env:ChocolateyPackageAuthor` which can be referred to in the install/uninstall/modify scripts.  
With this we can further simplify our templates.

Is this possible?

## Additional Context.

I took a look into the code (`src/chocolatey/infrastructure.app/services/PowershellService.cs`) and would suggest something like (after line 439)

```C#
Environment.SetEnvironmentVariable("chocolateyPackageAuthor", package.Author);
Environment.SetEnvironmentVariable("packageAuthor", package.Author);
```

But I'm not skilled enough to say if this is enough

## Related Issues

N/A

**Comment by AdmiringWorm** [comment]
Just want to clarify so there is no ambiguity with this enhancement request (it is currently not possible to do).

Exactly which type of author are you after?

The maintainer of the package or the maintainer of the software?

The author is the maintainer of the software, while the owner is the package's maintainer. These can be different.

Do also note that there can be multiple authors and owners, so the variables would probably be in plural, and additional work for anyone making use of the variables (if they are implemented) as typically both owner and author are colon-separated (if I remember correctly).

**Comment by pauby** [comment]
I comma separate mine. My understanding is that there is no strict format?

**Comment by we-mi** [comment]
> Just want to clarify so there is no ambiguity with this enhancement request (it is currently not possible to do).
> 
> Exactly which type of author are you after?
> 
> The maintainer of the package or the maintainer of the software?
> 
> The author is the maintainer of the software, while the owner is the package's maintainer. These can be different.
> 

I was thinking about the software author (creator/developer of the software) and not the package maintainer.

Like `Mozilla` for the `firefox` package or `Google Inc.` for the `googlechrome` package.

> Do also note that there can be multiple authors and owners, so the variables would probably be in plural, and additional work for anyone making use of the variables (if they are implemented) as typically both owner and author are colon-separated (if I remember correctly).

That's a good point. Most of the software we use or internalize does only have one author. But we definitly have to keep this in mind.

The template package (the one you create with `choco new <packageid>`) states this for the `<authors>` field:
```xml
<authors>__REPLACE_AUTHORS_OF_SOFTWARE_COMMA_SEPARATED__</authors>
```

**Comment by we-mi** [comment]
Besides that:

If there is another way of retrieving the software author from within `chocolateyInstall.ps1`, `chocolateyUninstall.ps1` or `chocolateyBeforeModify.ps1` i could live with that.

It does not have to be an environment variable, but my initial thought was that it would be the easiest way.  
If this is too much work i could live with an alternative.

**Comment by AdmiringWorm** [comment]
> I comma separate mine. My understanding is that there is no strict format?

> The template package (the one you create with choco new <packageid>) states this for the <authors> field:

> ```xml
> <authors>__REPLACE_AUTHORS_OF_SOFTWARE_COMMA_SEPARATED__</authors>
> ```

Apologies, I did mean comma-separated, not colon-separated.




> Besides that:
> 
> If there is another way of retrieving the software author from within `chocolateyInstall.ps1`, `chocolateyUninstall.ps1` or `chocolateyBeforeModify.ps1` i could live with that.
> 
> It does not have to be an environment variable, but my initial thought was that it would be the easiest way. If this is too much work i could live with an alternative.

The only way currently to achieve that would be to read the `nuspec` file directly yourself, it is not being included in any other information that I am aware of.

**Comment by we-mi** [comment]
> The only way currently to achieve that would be to read the nuspec file directly yourself, it is not being included in any other information that I am aware of.

That was a great hint!

I ended up extending our extension with a function which reads the nuspec file and filling the variable `$env:ChocolateyPackageAuthor` for the current powershell session.
This is perfectly fine for for us, so there's no need to implement this in any other way right know. At least for our environment, so I'll close this issue.

Thanks!
