### ISSUE TITLE
Replace deprecated tags with newer ones in default

### ISSUE THREAD

**Issue by aaronliu0130** [chocolatey/choco#2858]
## Is Your Feature Request Related To A Problem? Please describe.

I was frustrated when I thought I had to use an URL for common licenses and icons in the file path. The owners tag was also confusing.

## Describe The Solution. Why is it needed?

Deprecate licenseurl, icon url, and <owners> and use license, icon and authors instead in default new package nuspec template. This can ease the creation of new packages and keep us up to code a bit more.

## Additional Context.

These tags are officially deprecated in the nuspec spec. Summary is *being* deprecated but let's not worry about that for now.

The definition for <authors> has been updated to the def of <owners> i.e. the package authors.

**Comment by TheCakeIsNaOH** [comment]
@aaronliu0130 It seems like there is a formatting issue or something else going on in your text, the tags/elements you are talking about seem to be missing.

> These tags are officially deprecated in the nuspec spec. 

Chocolatey is not the same thing as NuGet.
Chocolatey CLI does use a modified version of NuGet for some things. So the `.nuspec` that Chocolatey understands is not the same `.nuspec` as the current version of `nuget.exe` understands. There have been elements added that only Chocolatey understands, and there have been elements added that only newer NuGet versions understand. 

So even if the NuGet team deprecates a nuspec element, that does not mean that it is deprecated for Chocolatey.

**Comment by aaronliu0130** [comment]
The tags issue has been fixed, apparently in markdown surrounding text with `<>` makes it disappear.

> So even if the NuGet team deprecates a nuspec element, that does not mean that it is deprecated for Chocolatey.

Yeah, I know about that. it's why this is just a suggestion.

**Comment by pauby** [comment]
@aaronliu0130 This isn't something we are looking to do at the moment, so I'm going to go ahead and close this.
