### ISSUE TITLE
The Question that Has Probably Been Asked 1000 Times

### ISSUE THREAD

**Issue by dschinkel** [chocolatey/choco#286]
This is extremely annoying to be Frank...which is why I like OS X and Homebrew :P, I don't have this problem.

And yes I've read the docs and it's still confusing as hell.

I realize you have different "types" of installs.  Metadata, yada yada.

So tell me where I'm missing it.  Why when I run this command do I not see Git for Windows installed in Program Files?

https://chocolatey.org/packages/git.install/1.9.5.20150320

**Comment by gep13** [comment]
I have just done a fresh install of this application, on a Windows 8 VM, and I see this:

![image](https://cloud.githubusercontent.com/assets/1271146/7689770/c953fe2c-fda6-11e4-877f-98b9b033c577.png)

Are you not seeing this?

**Comment by dschinkel** [comment]
and you used what command.  I just did the choco install git.install, says it installed successfully and I see nothing like that in Windows 7.  This is a fresh install of Windows 7 on Parallels.

**Comment by gep13** [comment]
Yip, that is the exact command I used.

Let me try on fresh Windows 7 machine...

**Comment by gep13** [comment]
Before...

![image](https://cloud.githubusercontent.com/assets/1271146/7689975/15d3641c-fda8-11e4-9c2a-453c9be812ef.png)

During...

![image](https://cloud.githubusercontent.com/assets/1271146/7689996/3bcc59a8-fda8-11e4-9f5b-e4ec9d400da8.png)

After...

![image](https://cloud.githubusercontent.com/assets/1271146/7690055/b8e42934-fda8-11e4-812e-8e5980648921.png)

**Comment by gep13** [comment]
And then, as per instructions...

![image](https://cloud.githubusercontent.com/assets/1271146/7690077/e1039ddc-fda8-11e4-91b6-83e6e2e04954.png)

After closing and re-opening the shell:

![image](https://cloud.githubusercontent.com/assets/1271146/7690085/ed34c41e-fda8-11e4-8586-23163c736928.png)

**Comment by dschinkel** [comment]
Ok I was confused.  I thought that it would install Git for Widows.  What it's doing is installing the bash shell so you can use it WITHING powershell.  Cool.  Thanks.

**Comment by gep13** [comment]
When you say "Git For Windows" are you referring to "GitHub For Windows": https://windows.github.com/ If so, you will want this package: https://chocolatey.org/packages/GitHub

**Comment by ferventcoder** [comment]
Git For Windows is the name of the one that comes in from the mSysGit project.

**Comment by dschinkel** [comment]
thanks guys, yes the mysisGit is what I'm looking for.

**Comment by dschinkel** [comment]
Probably would be better to call that package "Mysis Git" instead of "GitHub" but whatever.  I just think it would be very obvious it if had a better name for the package.  But thanks regardless of pointing that package out.

**Comment by ferventcoder** [comment]
@dschinkel It's called "Git for Windows", which you correctly identified. Most people are confused because the project that produces "Git for Windows" is the "msysGit" project - http://msysgit.github.io/ and "msysGit" is actually a separate tool.

I know I was confused at one time as well.

**Comment by ferventcoder** [comment]
A couple of things for you to think about - the package page includes parameters you can pass to the installer - `-params '"/GitAndUnixToolsOnPath"'` so that you get the git tools on the path, including bash.

Otherwise you need to use the context menu on folders and choose Git Bash Here.

You should also see the items in the start menu based on the components that we allow to be installed. Take a look at https://chocolatey.org/packages/git.install#files (expand `tools\chocolateyInstall.ps1`, and line 5-6) to see what is allowed to be installed. There is some history with some of the components causing the upgrades to fail - so we've historically let less of the components install.
