### ISSUE TITLE
Add configuration file for GitReleaseManager

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/choco#2863]
## Is Your Feature Request Related To A Problem? Please describe.

During a release of the project, it is currently needed to create a configuration file manually to do the release.

## Describe The Solution. Why is it needed?

To have a common set of a configuration for GitReleaseManager that will be used when we create/publish new releases.

## Additional Context.

N/A

## Related Issues

N/A

**Comment by vexx32** [comment]
This was completed in #2928 (didn't notice we had an issue open at that time, sorry).
