### ISSUE TITLE
pkgconfiglite: Fails to download *sometimes* the package 

### ISSUE THREAD

**Issue by dabrain34** [chocolatey/choco#2866]
### What You Are Seeing?

It fails with the error:

The remote file either doesn't exist ...

### What is Expected?

To be able to download *always* the file.

### System Details

* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`):
* Windows PowerShell version (Run: `$PSVersionTable`): Windows 10
* Chocolatey version (Run `choco --version`): 1.1.0

**Comment by dabrain34** [comment]
Here is the URL http://downloads.sourceforge.net/project/pkgconfiglite/0.28-1/pkg-config-lite-0.28-1_bin-win32.zip. I guess sometimes sourceforge is not answering immediatly, would it be an options to increase the timeout for download or even change the source for this package ?

**Comment by pauby** [comment]
This is a package issue (and a SourceForge one, as downloading installers from there is always problematic). Can you raise this with the maintainer?

**Comment by dabrain34** [comment]
Thanks @pauby for your answer, I sent a message to the maintainer

**Comment by dabrain34** [comment]
I sent another email to @kirkshoop https://github.com/kirkshoop

**Comment by dabrain34** [comment]
ping @kirkshoop

**Comment by pauby** [comment]
@dabrain34 This issue is closed.
