### ISSUE TITLE
Provide ability to navigate directly to online version of help documentation for a command

### ISSUE THREAD

**Issue by gep13** [chocolatey/choco#2867]
## Is Your Feature Request Related To A Problem? Please describe.

I believe that there is a lot of output from the `choco -h` command, and I would like to be able to navigate to the online version of the help documentation, similar to what can be done from PowerShell, for example:

```
Get-Help Get-Command -Online
```
## Describe The Solution. Why is it needed?

This would make it much easier to get the information I need by reading the online version of the documentation, which is also likely to have the most up to date version of the docs, directly from the command line, without the need to navigate to the docs site.

## Additional Context.

N/A

## Related Issues

N/A

**Comment by corbob** [comment]
Hey @gep13 this is a great idea! How would you like to try your hand at this improvement?
