### ISSUE TITLE
Error 404 for every package in Windows 10 VM

### ISSUE THREAD

**Issue by DogeLord081** [chocolatey/choco#2874]
What are you seeing?

Failures
 - wesnoth (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\wesnoth\tools\chocolateyInstall.ps1'.
 See log for details. No matter what I try to install.

What is expected?

For it to install successfully.

Steps to reproduce:

-Install chocolatey on Windows 10 Enterprise Evaluation VirtualBox
-Attempt to install any package with "choco install _____"

System Details

OS Build: 10.0.17763.0
PowerShell version: 5.1.17763.316
Chocolatey version: 1.2.0

Log:

https://gist.github.com/DogeLord081/3eb0d79de06ed7edbb99807860f0586c

**Comment by pauby** [comment]
The problem you are seeing is [highlighted in the log file](https://gist.github.com/DogeLord081/3eb0d79de06ed7edbb99807860f0586c#file-chocolatey-log-L584) and is a package issue.
