### ISSUE TITLE
Side by side installations are deprecated and is pending removal in v2.0.0.

### ISSUE THREAD

**Issue by viceice** [chocolatey/choco#2878]
### What You Are Seeing?

I'm seeing a lot of those messages when updating all packages via `cup all`. I never installed those packages directly and i don't remember which package had installed them via transitive dependencies.

```
KB2533623 2.0.0

KB2919355 has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.
KB2919355 1.0.20160915

KB2919442 has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.
KB2919442 1.0.20160915

KB2999226 has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.
KB2999226 1.0.20181019

KB3033929 has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.
KB3033929 1.0.5

KB3035131 has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.
KB3035131 1.0.3
KB3063858 1.0.0
KB3118401 1.0.5
```

- https://github.com/chocolatey/choco/issues/2787#issuecomment-1295013671

### What is Expected?

Se a link or description for how to fix it.

### System Details

* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`): 10, 11, 2012R2, 2016, 2019, 2022 (latest patches)
* Windows PowerShell version (Run: `$PSVersionTable`): 5.1.14393.5127, 7.2.6
* Chocolatey version (Run `choco --version`): 1.2.0

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
2022-11-01 08:57:27,653 11356 [DEBUG] - Attempting to create directory "C:\Users\xxx\AppData\Local\Temp\2\chocolatey".
2022-11-01 08:57:27,763 11356 [INFO ] - Chocolatey v1.2.0
2022-11-01 08:57:27,778 11356 [DEBUG] - Chocolatey is running on Windows v 6.3.9600.0
2022-11-01 08:57:27,778 11356 [DEBUG] - Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
2022-11-01 08:57:27,778 11356 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
2022-11-01 08:57:27,966 11356 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" upgrade vcredist2015
2022-11-01 08:57:27,982 11356 [DEBUG] - Received arguments: upgrade vcredist2015
2022-11-01 08:57:28,075 11356 [DEBUG] - RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
2022-11-01 08:57:28,075 11356 [DEBUG] - Sending message 'PreRunMessage' out if there are subscribers...
2022-11-01 08:57:28,122 11356 [DEBUG] - [Pending] Removing all pending packages that should not be considered installed...
2022-11-01 08:57:28,185 11356 [DEBUG] - Performing validation checks.
2022-11-01 08:57:28,200 11356 [DEBUG] - Global Configuration Validation Checks:
2022-11-01 08:57:28,200 11356 [DEBUG] -  - Package Exit Code / Exit On Reboot = Checked
2022-11-01 08:57:28,200 11356 [DEBUG] - System State Validation Checks:
2022-11-01 08:57:28,200 11356 [DEBUG] -  Reboot Requirement Checks:
2022-11-01 08:57:28,200 11356 [DEBUG] -  - Pending Computer Rename = Checked
2022-11-01 08:57:28,200 11356 [DEBUG] -  - Pending Component Based Servicing = Checked
2022-11-01 08:57:28,216 11356 [DEBUG] -  - Pending Windows Auto Update = Checked
2022-11-01 08:57:28,216 11356 [DEBUG] -  - Pending File Rename Operations = Checked
2022-11-01 08:57:28,216 11356 [DEBUG] -  - Pending Windows Package Installer = Checked
2022-11-01 08:57:28,216 11356 [DEBUG] -  - Pending Windows Package Installer SysWow64 = Checked
2022-11-01 08:57:28,216 11356 [INFO ] - 2 validations performed. 2 success(es), 0 warning(s), and 0 error(s).
2022-11-01 08:57:28,247 11356 [DEBUG] - The source 'https://chocolatey.org/api/v2/;\\xxx\nuget\v2' evaluated to a 'normal' source type
2022-11-01 08:57:28,247 11356 [DEBUG] - 
NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
2022-11-01 08:57:28,263 11356 [DEBUG] - Configuration: CommandName='upgrade'|
CacheLocation='C:\Users\xxx\AppData\Local\Temp\2\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://chocolatey.org/api/v2/;\\xxx\nuget\v2'|
SourceType='normal'|Debug='False'|Verbose='False'|Trace='False'|
Force='False'|Noop='False'|HelpRequested='False'|
UnsuccessfulParsing='False'|RegularOutput='True'|QuietOutput='False'|
PromptForConfirmation='False'|DisableCompatibilityChecks='False'|
AcceptLicense='False'|AllowUnofficialBuild='False'|
Input='vcredist2015'|
AllVersions='False'|SkipPackageInstallProvider='False'|
SkipHookScripts='False'|PackageNames='vcredist2015'|Prerelease='False'|
ForceX86='False'|OverrideArguments='False'|NotSilent='False'|
ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|PinPackage='False'|
Information.PlatformType='Windows'|
Information.PlatformVersion='6.3.9600.0'|
Information.PlatformName='Windows Server 2012 R2'|
Information.ChocolateyVersion='1.2.0.0'|
Information.ChocolateyProductVersion='1.2.0'|
Information.FullName='choco, Version=1.2.0.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='xxx'|
Information.UserDomainName='xxx'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='True'|Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Information.CurrentDirectory='C:\Users\xxx'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
ListCommand.LocalOnly='False'|ListCommand.IdOnly='False'|
ListCommand.IncludeRegistryPrograms='False'|ListCommand.PageSize='25'|
ListCommand.Exact='False'|ListCommand.ByIdOnly='False'|
ListCommand.ByTagOnly='False'|ListCommand.IdStartsWith='False'|
ListCommand.OrderByPopularity='False'|ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
ApiKeyCommand.Remove='False'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|
ExportCommand.IncludeVersionNumbers='False'|Proxy.BypassOnLocal='True'|
TemplateCommand.Command='unknown'|
2022-11-01 08:57:28,263 11356 [DEBUG] - _ Chocolatey:ChocolateyUpgradeCommand - Normal Run Mode _
2022-11-01 08:57:28,279 11356 [INFO ] - Upgrading the following packages:
2022-11-01 08:57:28,279 11356 [INFO ] - vcredist2015
2022-11-01 08:57:28,279 11356 [INFO ] - By upgrading, you accept licenses for the packages.
2022-11-01 08:57:30,263 11356 [WARN ] - 
vcredist2015 has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.
2022-11-01 08:57:30,325 11356 [DEBUG] - Using 'https://chocolatey.org/api/v2/'.
2022-11-01 08:57:31,169 11356 [DEBUG] - - Supports prereleases? 'True'.
2022-11-01 08:57:31,185 11356 [DEBUG] - - Is ServiceBased? 'True'.
2022-11-01 08:57:31,810 11356 [DEBUG] - Package 'vcredist2015' found on source 'https://chocolatey.org/api/v2/'
2022-11-01 08:57:31,810 11356 [DEBUG] - Using '\\xxx\nuget\v2'.
2022-11-01 08:57:31,810 11356 [DEBUG] - - Supports prereleases? 'True'.
2022-11-01 08:57:31,810 11356 [DEBUG] - - Is ServiceBased? 'False'.
2022-11-01 08:57:37,093 11356 [INFO ] - vcredist2015 v14.0.24215.20170201 is the latest version available based on your source(s).
2022-11-01 08:57:37,108 11356 [WARN ] - 
Chocolatey upgraded 0/1 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2022-11-01 08:57:37,124 11356 [WARN ] - 
Enjoy using Chocolatey? Explore more amazing features to take your
experience to the next level at
 https://chocolatey.org/compare
2022-11-01 08:57:37,124 11356 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2022-11-01 08:57:37,124 11356 [DEBUG] - Exiting with 0
~~~

</p>

</details>

**Comment by pauby** [comment]
I'm not clear on what you're trying to do here or what you want from raising the issue?

**Comment by viceice** [comment]
I want to know how to fix that warning 🤷‍♂️  there should be some documentation on how to fix.

**Comment by viceice** [comment]
```pwsh
> cuninst vcredist2015
Chocolatey v1.2.0
Uninstalling the following packages:
vcredist2015

KB2919355 has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.

KB2919442 has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.

KB2999226 has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.

KB3033929 has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.

KB3035131 has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.

vcredist2015 has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.
vcredist2015 not uninstalled. An error occurred during uninstall:
 Unable to uninstall 'vcredist2015 14.0.24215.20170201' because 'tortoisegit 2.13.0.1' depends on it.

Chocolatey uninstalled 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - vcredist2015 (exited 1) - vcredist2015 not uninstalled. An error occurred during uninstall:
 Unable to uninstall 'vcredist2015 14.0.24215.20170201' because 'tortoisegit 2.13.0.1' depends on it.

If a package uninstall is failing and/or you've already uninstalled the
 software outside of Chocolatey, you can attempt to run the command
 with `-n` to skip running a chocolateyUninstall script, additionally
 adding `--skip-autouninstaller` to skip an attempt to automatically
 remove system-installed software. Only the packaging files are removed
 and not things like software installed to Programs and Features.

If a package is failing because it is a dependency of another package
 or packages, then you may first need to consider if it needs to be
 removed as packages have dependencies for a reason. If
 you decide that you still want to remove it, head into
 `$env:ChocolateyInstall\lib` and find the package folder you want to
 be removed. Then delete the folder for the package. You should use
 this option only as a last resort.
```

```xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>tortoisegit</id>
    <version>2.13.0.1</version>
    <title>TortoiseGit</title>
    <authors>TortoiseGit and contributors</authors>
    <owners>chocolatey-community, dtgm</owners>
    <licenseUrl>http://www.gnu.org/licenses/old-licenses/gpl-2.0.html</licenseUrl>
    <projectUrl>https://tortoisegit.org/</projectUrl>
    <iconUrl>https://cdn.jsdelivr.net/gh/chocolatey-community/chocolatey-packages@25a40985eb12778b130d754058887895f8b1bc40/icons/tortoisegit.png</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>...trimmed...</description>
    <summary>TortoiseGit provides overlay icons showing the file status, a powerful context menu for Git and much more!</summary>
    <releaseNotes>https://tortoisegit.org/docs/releasenotes/#Release_2.13.0.1</releaseNotes>
    <copyright>© TortoiseGit</copyright>
    <tags>git version-control dvcs admin foss</tags>
    <projectSourceUrl>https://gitlab.com/tortoisegit/tortoisegit/</projectSourceUrl>
    <packageSourceUrl>https://github.com/chocolatey-community/chocolatey-packages/tree/master/automatic/tortoisegit</packageSourceUrl>
    <docsUrl>https://tortoisegit.org/docs/</docsUrl>
    <mailingListUrl>https://groups.google.com/forum/#!forum/tortoisegit-dev</mailingListUrl>
    <bugTrackerUrl>https://tortoisegit.org/issues</bugTrackerUrl>
    <dependencies>
      <dependency id="vcredist2015" version="14.0.24215.20170201" />
    </dependencies>
  </metadata>
</package>
```

**Comment by viceice** [comment]
I don't installed `tortoisegit` as side-by-side.  `vcredist2015` seems to be installed on 1.12.2017.

![image](https://user-images.githubusercontent.com/1798109/200349349-fd100a73-2778-4dbe-9480-063e51d2d04b.png)
![image](https://user-images.githubusercontent.com/1798109/200349471-a3e7808d-a30d-40fe-8455-da5cc5fc2754.png)


the arguments files are somehow encrypted, so can't reveal them

**Comment by pauby** [comment]
`tortoisegit` was installed side-by-side which is why the package folder appears with the version number after it. When it was installed side-by-side it also installed `vcredist` and `KB2919442` side-by-side (as they are dependencies of `tortoisegit`).

The best way to do this is to uninstall the versions of `tortoisegit` you have using `choco uninstall tortoisegit --side-by-side` (you may also need to add the `--version <VERSION NUMBER>` on there and uninstall each version. Then uninstall dependencies that are side-by-side installs using the same command.

**Comment by viceice** [comment]
those screen shots are not from the lib folder, they are from the `.chocolatey` folder

here's the lib folder:
![image](https://user-images.githubusercontent.com/1798109/200357798-c415654f-85e1-48e5-9e1d-1550bcbd6494.png)

**Comment by pauby** [comment]
What does `choco list -l` give you as output?

**Comment by viceice** [comment]
```pwsh
> choco list -l
Chocolatey v1.2.0
7zip 22.1
7zip.install 22.1
chocolatey 1.2.0
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-windowsupdate.extension 1.0.5
cmdermini 1.3.20
docfx 2.59.4
dotnet-6.0-sdk 6.0.402
dotnet-6.0-sdk-4xx 6.0.402
dotnet-sdk 6.0.402
DotNet4.5.2 4.5.2.20140902
git 2.38.1
git.install 2.38.1
ikvm 8.1.5717.20170308
ILMerge 2.12.0803
KB2533623 2.0.0

KB2919355 has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.
KB2919355 1.0.20160915

KB2919442 has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.
KB2919442 1.0.20160915

KB2999226 has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.
KB2999226 1.0.20181019

KB3033929 has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.
KB3033929 1.0.5

KB3035131 has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.
KB3035131 1.0.3
KB3063858 1.0.0
KB3118401 1.0.5
nodejs-lts 16.18.0
notepad3 5.21.1129.1
notepad3.install 5.21.1129.1
nuget.commandline 6.3.1
PowerShell 5.1.14409.20180811
powershell-core 7.2.6
processhacker 2.39
processhacker.install 2.39
pwsh 7.2.6
tailblazer 0.9.0.536
Temurin11jre 11.0.16.10100
tortoisegit 2.13.0.1
treesizefree 4.6.1.2
vcredist140 14.32.31332
vcredist2010 10.0.40219.32503

vcredist2015 has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.
vcredist2015 14.0.24215.20170201
xxx1 1.0.0
xxx2 1.0.0
xxx3 1.0.0
xxx4 2.1.0
vswhere 3.0.3
45 packages installed.
```

The `xxx` packages are redacted names

**Comment by ImpatientTurtle** [comment]
I stumbled upon this after just deleting all folders containing an .sxs file by using
`(Get-ChildItem -Path C:\ProgramData\chocolatey\.chocolatey\ -Recurse -File -Filter '.sxs').Directory | Remove-Item -Recurse -Verbose`
and then removing all folders containing a version number next to them in C:\ProgramData\chocolatey\lib followed by reinstalling the removed packages besides the one I wanted to remove with --force parameter. I had previously uninstalled python3 version 3.10.8 using BCUninstaller which was what I originally used the side-by-side parameter for. I do hope I didn't break anything but it did remove the warning.

**Comment by Fooughhy** [comment]
I have the same issue as @viceice, and only those exact packages (the same KB... and vcredist2015) are the only packages that say "side-by-side" according to "choco list -lo".

I am assuming it is some type of package that I have installed side-by-side before, but not uninstalled, which have left these packages on the system, perhaps?

**Comment by viceice** [comment]
removing the `.sxs` files resolved the issue. maybe the was a side by side installation long time ago and through updates it was only partially fixed?

**Comment by Mistuke** [comment]
So I don't really understand why this deprecation is happening.  The solution or alternatives don't make sense to me either.

Atm I maintain the GHC compiler packages, https://community.chocolatey.org/packages/ghc I have 7 years of side by side install-able compilers (where the packages have been designed to be able to run side by side) which will all stop working when this change goes into effect.

The "recommendation" seems very weird to me, why would I need to create multiple packages, one for each version.  It just doesn't make sense.  If I do this, this breaks matrix installs, where you just specify the version of the compiler to install through `--version` without needing a new package name and string manipulation.

The meta-package, well, I don't see how this works.

> Create a [metapackage](https://docs.chocolatey.org/en-us/getting-started#terminology) for the overall product with a package version for each of the versioned packages. In other words, create another package (this time without a version number in the ID), which contains only a nuspec file and add a dependency on the versioned package. Following the above example for Python, we'd create a package with the ID python at version 2.0.0 that takes a dependency on the python2 package.

This seems moot, as without -m the only thing this adds is the ability to install the "latest" package version and doesn't help at all with side-by-side installs.  As I can't use the meta-package version to install side by side packages.  I still have to use the full new package versions.

Third, my packages are currently exempt from moderation, After 7 years I'd certainly hope I built up enough good will not to have to go through moderation for every new version of a package I upload.  This new "plan" means that for every new version I want to upload I'll be stuck in the moderation queue again, waiting for a mod to come along.

Removing this features breaks years of software and github actions workflows and other CI workflows without giving a real solution to the problem.   Why don't you just introduce a flag to allow packages to be marked as side-by-side installable, so you allow maintainers to opt in to this support.

This plan seems frustrating for both users and maintainers. The proposed interface is very confusing for users, and the fact that you're going to break 7 years of back catalog is a very hard pill to swallow.

**Comment by TheCakeIsNaOH** [comment]
> This seems moot, as without -m the only thing this adds is the ability to install the "latest" package version and doesn't help at all with side-by-side installs. 

So in the python example, if you would hypothetically run `choco install python --version 2.0.0`, then it would install the `python 2` package, while the newest version of the `python` package would depend on `python3`

> So I don't really understand why this deprecation is happening. 
> Why don't you just introduce a flag to allow packages to be marked as side-by-side installable, so you allow maintainers to opt in to this support.

The primary reason for the deprecation (and removal) is because the NuGet assemblies that Chocolatey CLI builds on top of are being upgraded (#508). The new assemblies do not allow side by side installations in the same way, and it was not straightforward task to add support back in a way that would not break anything more. 

Additionally, there were a number of longstanding bugs with how side by side installed packages were handled, especially for upgrades and uninstalls. 

So it is not as simple as adding a flag to keep the functionality, as a large part of the code that supported side by side installations is being replaced/upgraded. 

> All previous topics on this have been locked, and no discussion was ever had.

The issues you linked were locked because the work in those issues had been completed, and the Chocolatey team wanted to keep discussion in open issues and/or in discussions.

**Comment by da9l** [comment]
I'm using and recommending the choco side by side installation to keep multiple versions of dotnet-sdk installed.
Any suggestions on how to achieve this after this capability has been deprecated?

```
dotnet --list-sdks
5.0.100 [C:\Program Files\dotnet\sdk]
5.0.203 [C:\Program Files\dotnet\sdk]
5.0.302 [C:\Program Files\dotnet\sdk]
5.0.401 [C:\Program Files\dotnet\sdk]
6.0.100 [C:\Program Files\dotnet\sdk]
6.0.402 [C:\Program Files\dotnet\sdk]
7.0.100 [C:\Program Files\dotnet\sdk]

**Comment by pauby** [comment]
There is [documentation for this](https://docs.chocolatey.org/en-us/create/create-packages#naming-packages-to-allow-for-side-by-side-installation), mentioned in the [comment above](https://github.com/chocolatey/choco/issues/2878#issuecomment-1305695895).

**Comment by gep13** [comment]
@da9l in addition to above comment from @pauby  the maintainers of the dotnet SDK packages have already taken this into consideration.  i.e you can install either:

* https://community.chocolatey.org/packages/dotnet-6.0-sdk-4xx
* https://community.chocolatey.org/packages/dotnet-6.0-sdk-3xx
* https://community.chocolatey.org/packages/dotnet-6.0-sdk-2xx
* https://community.chocolatey.org/packages/dotnet-6.0-sdk-1xx

i.e. each of those could then be installed "side by side" and then `choco upgrade all` would function as expected.

**Comment by Mistuke** [comment]
Are users the thing being trusted or still packages. Otherwise I have to submit 50-60 packages and have to wait for review for all of them.

And now when I just release new versions I again get stuck in moderation queue. :( so has user based exemptions been implemented or is it still package based...

**Comment by gep13** [comment]
@Mistuke your question seems unrelated to the topic being discussed here, but to provide a quick answer, trust is applied at the package level, not at the user level.  Once trusted, new package versions for a package will no longer require human moderation, but they will still go through the automated moderation process and if any fail, it will be pushed back to the maintainer to look into.

What 50-60 packages are you referring to here?

**Comment by Mistuke** [comment]
> @Mistuke your question seems unrelated to the topic being discussed here, but to provide a quick answer, trust is applied at the package level, not at the user level. Once trusted, new package versions for a package will no longer require human moderation, but they will still go through the automated moderation process and if any fail, it will be pushed back to the maintainer to look into.
> 

It most definitely is related? If side by side versions now require a separate package, it means i can never use the same package again aside for the "latest" wrapper pqckage.

I'll have to submit all new versions as separate packages.

> What 50-60 packages are you referring to here?

Well without side by side support I now have to resubmit all ghc and cabal packages. So not sure why it's unrelated.

**Comment by Mistuke** [comment]
In addition to the above, right now there's also a "guarantee" that the packages are produced by the same person. A random person can't submit using a taken package name.

With the new scheme, unless I'm mistaken:
```
https://community.chocolatey.org/packages/dotnet-6.0-sdk-4xx
https://community.chocolatey.org/packages/dotnet-6.0-sdk-3xx
https://community.chocolatey.org/packages/dotnet-6.0-sdk-2xx
https://community.chocolatey.org/packages/dotnet-6.0-sdk-1xx
```
There's no guarantee at all that these were made by the same person, packaged the same way etc right?  So it feels to me like this change needs more changes on the chocolatey infra side for stuff like this.

At least this is what I could find with the little information available, there are documentation for how this effect users but not what maintainers should do.

**Comment by pauby** [comment]
As side-by-side installations have now been deprecated in 2.0.0 of Chocolatey CLI, [documentation has been added](https://docs.chocolatey.org/en-us/create/create-packages#naming-packages-to-allow-for-side-by-side-installation) and there has been no update to this in some time, I'm going to go ahead and close this. We can reopen it if necessary.
