### ISSUE TITLE
how to refresh environment variables in windows 10 (4- simple-step)

### ISSUE THREAD

**Issue by Jafari-Amir** [chocolatey/choco#2892]
if you lost or delete by chance ot advertently your environment variables and have doubts about it,,,SO,,, you are in right place
I suggest following steps
**1- install chocolatey through CMC (admin) and push enter** ([link](https://community.chocolatey.org/packages/nvm#install))
choco install nvm
**2- comment this after that in CMC to Upgrade it** ([link](https://community.chocolatey.org/packages/nvm#upgrade))
choco upgrade nvm
**3- comment in the end this syntax and push enter**
call RefreshEnv.cmd
**4- you will see following result, be happy for it :) AND  check your environment variables** 
Refreshing environment variables from registry for cmd.exe. Please wait...Finished..
C:\Windows\system32>
**I hope this works for you**

**Comment by JPRuskin** [comment]
Is this an issue? An enhancement request? Something else? 

Could you please use one of the templates to better describe your request?

**Comment by Jafari-Amir** [comment]
> Is this an issue? An enhancement request? Something else?
> 
> Could you please use one of the templates to better describe your request?

2 days I was looking for easy way for refreshing (retrieving ) environment variables, finally I saw people had some implications, 
I decided to show how easy is it and make more direct instruction for other less skilled members.
I check it out other places for posting this, but, finally there is more chance to be seen.

**Comment by pauby** [comment]
@Jafari-Amir Thanks for providing that information. We have this covered [in the docs](https://docs.chocolatey.org/en-us/troubleshooting#my-path-is-not-getting-updated). If there is a better place for this, can you raise an issue / PR over at https://github.com/chocolatey/docs ?
