### ISSUE TITLE
Migrate from Should to FluentAssertions

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#2893]
## Is Your Feature Request Related To A Problem? Please describe.

Currently, the integration tests library uses the [Should](https://www.nuget.org/packages/Should) nuget package for assertions in tests.
This package is only build for .Net framework, and not newer Dotnet versions. 
It appears to be abandoned, with the last release to nuget.org pushed what is getting close to a decade ago, and old un-merged pulled requests on the source repository:
https://github.com/erichexter/Should/pull/19

It does not have a complete complement of assertions, there are other libraries with more.

## Describe The Solution. Why is it needed?

So it would be good to switch to another library that is built for .Net Standard, so it can be used with .Net 4.8 and the forthcoming dotnet build. 

There are two popular options for assertion libraries that I am aware of:
https://www.nuget.org/packages/FluentAssertions
And
https://www.nuget.org/packages/Shouldly

As far as I am aware, they should be both good options, and it is up to whatever team members like better, or which is already in use elsewhere. 

## Additional Context.

N/A

## Related Issues
- Issue #2738

**Comment by gep13** [comment]
I had a quick chat with @AdmiringWorm about this today, and we are thinking that FluentAssertions might be the way to go.

@TheCakeIsNaOH thoughts?

**Comment by TheCakeIsNaOH** [comment]
@gep13 sounds good to me.

One additional thing I forgot to mention was that `TinySpec.NUnit` takes a dependency on `Should`, but the TinySpec package is planned to be removed as a part of #2880, so it should not be an issue for much longer.

**Comment by tapika** [comment]
See also:

https://github.com/tapika/swupd/commit/1a243b1efa2398c3099df41b471f986c100068cf
https://github.com/tapika/swupd/commit/76bf87a50ab489ad5f44d0c543323a642de032ef

I have made similar changes before integration tests refactoring. Maybe makes sense to revert back to those commit, then will be easier just to compare & copy. Mostly it's just find / replace with some exceptions.
