### ISSUE TITLE
is there a plan to support .net core

### ISSUE THREAD

**Issue by kenizhou** [chocolatey/choco#2901]
Just wonder is there a plan to support .net core. thanks!

**Comment by TheCakeIsNaOH** [comment]
Yes, it is planned: https://github.com/chocolatey/choco/issues/2436#issuecomment-1300763938

**Comment by anitsch-scs** [comment]
Congrats on the successful update to .NET Framework 4.8!
The linked Issue (and links therein) are all closed issues concerning mostly the 4.8 migration.

Is there a new Issue to track progress of .NET Core/ .NET 6.0/ .NET 7.0 Support? 
That would greatly simplify our CI builds.

**Comment by TheCakeIsNaOH** [comment]
@anitsch-scs The .NET 4.8 uplift still has a few tasks left. It is tracked in #2738

There is not a new issue at this point for .Net 6/7/newer
