### ISSUE TITLE
Update handling of HTTPS security protocols

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#2902]
## Is Your Feature Request Related To A Problem? Please describe.

Now that Chocolatey CLI is moving to .Net 4.8, there is a redundant fallback and warning message in `SecurityProtocol`. Since .Net 4.8 always has TLS v1.2 available, there is no need to continue to have this fallback and warning.

https://github.com/chocolatey/choco/blob/edde97906053fbb3768d18300c2ed3f3716c4a98/src/chocolatey/infrastructure/registration/SecurityProtocol.cs#L43-L56

## Describe The Solution. Why is it needed?

At minimum, this specific warning/fallback should be removed.

But it would be better to have a re-evaluation of the status of SSL/TLS in Chocolatey CLI, and best practices for .Net 4.8 programs. 

This document recommends that the TLS version should not be explicitly set by programs, and use the OS defaults.
https://learn.microsoft.com/en-us/dotnet/framework/network-programming/tls

However, from what I understand, this may mean that on Windows 7, depending on updates/registry settings then .Net apps may not have TLS 1.2 enabled by default. As per:
https://learn.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-#tls-protocol-version-support

So it may make sense to enable TLS 1.1/1.2 if the Windows build/version corresponds to Windows 7/Server 2008 R2, and use the OS default if the OS build is newer?

## Additional Context.

N/A

## Related Issues

- Issue #2738

**Comment by vexx32** [comment]
Tagging this as a potentially breaking change. It shouldn't break a _lot_ of folks, but it could break folks in some older OSes, so it's worth calling out.

**Comment by superbonaci** [comment]
You guys broke my compatibility with Windows 7, now can't update chocolatey to 2.0.0.
