### ISSUE TITLE
Update Minimum Windows Server OS to Server 2008 R2

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#2903]
## Is Your Feature Request Related To A Problem? Please describe.

As per the supported operating systems for .Net 4.8, Windows 7 or newer and Windows Server 2008 R2 or newer are supported.
https://learn.microsoft.com/en-us/dotnet/framework/get-started/system-requirements

Currently, from everywhere I have looked, Windows 7 is listed the minimum support Windows Client OS for Chocolatey CLI so that is good to go.

However, the same does not seem to go for Window Server, as Server 2003 or 2008 seem to be the minimum version listed, so things will have to be updated at or ahead of the 2.0 release.

## Describe The Solution. Why is it needed?

There are a number of locations to update in this repository:
https://github.com/chocolatey/choco/blob/edde97906053fbb3768d18300c2ed3f3716c4a98/src/chocolatey.console/choco.exe.manifest#L53-L54

https://github.com/chocolatey/choco/blob/8c3cdea5077a78a67a5f0a7b2aa29ebd971993a0/README.md?plain=1#L80

https://github.com/chocolatey/choco/blob/8c3cdea5077a78a67a5f0a7b2aa29ebd971993a0/src/chocolatey/infrastructure/platforms/Platform.cs#L137-L148

I think I got them, but I easily could have missed somewhere.

## Additional Context.

Additional issues should be opened for other locations that may have minimum supported OS information:
- Installation page on chocolatey.org
- Installation course on chocolatey.org
- Docs repository
- Internal locations?

## Related Issues

- Issue #2738

**Comment by pauby** [comment]
For clarity, we support Windows Server 2008 R2 **in Azure** as that is what is [currently supported by Microsoft, up to January 2024](https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2008-r2).

**Comment by pauby** [comment]
In the README, we should remove the supported operating systems and point to the docs instead. This gives us one place to update this as it moves forward.

**Comment by vexx32** [comment]
I agree that it's not ideal that we have this documented in multiple places... 

However, if we're going to point folks to a doc page instead of embedding information in the package, we'll need to ensure that the doc page is very explicit about which OSes are supported by which versions of the package, so that folks aren't misled if they're installing a slightly older package and going off the documentation which perhaps might be more recently updated than the package itself.

For example, say in future (choco v3.x?) we dropped support for Windows Server 2008(R2) entirely and then updated our docs to say that. Folks installing v2.x who're looking at that doc might think that also applies to v2.x when that's not the case.

**Comment by pauby** [comment]
If we do that, then we are going to have the issue of what the package supports and what Chocolatey Software supports.

In the example:

> For example, say in future (choco v3.x?) we dropped support for Windows Server 2008(R2) entirely and then updated our docs to say that. Folks installing v2.x who're looking at that doc might think that also applies to v2.x when that's not the case.

We wouldn't support 2.x of Chocolatey CLI for open-source users, even though the software may actually run. In the same way that Chocolatey CLI currently works on Windows 7 (for some users) we do not support it.

**Comment by vexx32** [comment]
That makes sense, I guess I misunderstood a bit what we were talking about here, sorry. 🙂

**Comment by TheCakeIsNaOH** [comment]
> If we do that, then we are going to have the issue of what the package supports and what Chocolatey Software supports.

It may be worth separating out into what is "supported" and what is likely "compatible". That way, people who want to go off and run on unsupported operating systems will have some idea of what is possible.

**Comment by pauby** [comment]
"compatible" says "supported" to me. If something is "compatible" then, it should work. When it doesn't people will understandably ask questions as to why. If we don't support it, what do we say?

I know this sounds like its terminology, but I feel we have to set expectations clearly. There may be a way to do that, providing both.
