### ISSUE TITLE
Choco upgrade succeeds with missing dependencies

### ISSUE THREAD

**Issue by mwisnicki** [chocolatey/choco#2906]
### What You Are Seeing?

After not so successful update of keepass:

```
> choco list --local keepass
Chocolatey v1.2.0
keepass 2.52
keepass-kpentrytemplates 1.8.0.20190608
keepass-plugin-keeautoexec 2.4.0.20200422
keepass-plugin-winkee 2.39.1
4 packages installed.
```

### What is Expected?

keepass is a meta-package that depends on keepass.install therefore if keepass is installed then keepass.install must be installed. 
Missing dependency represents invalid state and indicates bad logic in chocolatey.

"Losing" keepass.install package somewhere along the way of failing upgrade is another choco bug.

I'm holding these assumptions but correct me if I'm wrong:

1. Package update must not succeed if required dependency failed
2. Failed update must not remove existing package

### How Did You Get This To Happen? (Steps to Reproduce)

1. choco install --version=2.51 keepass
1. start keepass
1. choco upgrade keepass

Choco registers update to keepass despite failing a dependency update - this is a bug of chocolatey (this ticket, also #2177)
Keepass.install fails because keepass is running - this is a bug of the package (pauby/ChocoPackages#73, pauby/ChocoPackages#138)

### System Details

* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`): 10.0.22621.0
* Windows PowerShell version (Run: `$PSVersionTable`): 5.1.22621.608
* Chocolatey version (Run `choco --version`): 1.2.0

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
> choco list --local keepass
Chocolatey v1.2.0
keepass 2.51
keepass-kpentrytemplates 1.8.0.20190608
keepass-plugin-keeautoexec 2.4.0.20200422
keepass-plugin-winkee 2.39.1
4 packages installed.
PS C:\Users\mwisn> choco upgrade keepass
Chocolatey v1.2.0
Upgrading the following packages:
keepass
By upgrading, you accept licenses for the packages.

You have keepass v2.51 installed. Version 2.52 is available based on your source(s).
Progress: Downloading keepass 2.52... 100%

keepass.install v2.52 [Approved]
keepass.install package files upgrade completed. Performing other installation steps.
Installing keepass.install...
ERROR: Running ["C:\ProgramData\chocolatey\lib\keepass.install\tools\KeePass-Setup.exe" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- ] was not successful. Exit code was '1'. See log for possible error messages.
The upgrade of keepass.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyInstall.ps1'.
 See log for details.

keepass v2.52 [Approved]
keepass package files upgrade completed. Performing other installation steps.
 The upgrade of keepass was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\keepass'

Chocolatey upgraded 1/2 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - keepass.install (exited 1) - Error while running 'C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyInstall.ps1'.
 See log for details.
~~~

</p>

</details>

**Comment by pauby** [comment]
In the 'Output Log' section above, we are looking for the chocolatey.log. Can you edit your issue and add it above?

**Comment by berlincount** [comment]
I'm running into this kind of issues often.

Metapackage unable to install packages, and never retrying.

**Comment by pauby** [comment]
@berlincount the OP didn't provide any additional information and there is no additional information provided in your comment that helps us troubleshoot this 

As this issue hasn't been updated in 11 months I think we should close it. If you could raise a new issue we can then capture all of the information we need in that, from you.

Thanks.
