### ISSUE TITLE
Rename or migrate away from custom HashCode class

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#2909]
## Is Your Feature Request Related To A Problem? Please describe.

Chocolatey CLI is using a custom HashCode implementation: 
https://github.com/chocolatey/choco/blob/924a785abe806c0a61541b86d273f7643d8ed20e/src/chocolatey/infrastructure.app/utility/HashCode.cs

However, in dotnet core (2.1 I think), a HashCode class was added to dotnet itself. https://learn.microsoft.com/en-us/dotnet/api/system.hashcode

Therefore, once Chocolatey moves to dotnet, these classes will conflict, as they are both named `HashCode`

## Describe The Solution. Why is it needed?

One option would be to rename that class to `chocolatey.infrastructure.app.utility.HashCode` or similar, and keep using it.

Another option would be to remove that class, and add the [Microsoft.Bcl.HashCode](https://www.nuget.org/packages/Microsoft.Bcl.HashCode) package. It is built for netstandard 2.0, and so could be switched to immediately for release with v2.0

Neither of these would need to be done now, they could be done when migrating to dotnet from .Net framework. However, v2.0 may be a good opportunity to make this change.

## Additional Context.

N/A

## Related Issues

- Issue #2436
- Issue #2738

**Comment by gep13** [comment]
@TheCakeIsNaOH thanks for raising this.

As discussed, there would be potentially some related work in CCM, before we could make this change.  As such, although we are updating to .NET 4.8 in the next release, we will hold off on this particular change, until we can guarantee compatibility.

**Comment by gep13** [comment]
After some further investigation, it was found that it was possible to move forward with this change, so the steps have been taken to do this, both here, and in the Commercial components.
