### ISSUE TITLE
Invariant UI Culture causing problems with i18n

### ISSUE THREAD

**Issue by warnergodfrey** [chocolatey/choco#291]
We have some chocolatey packages that use PowerShell DSC to configure IIS during installation. Unfortunately changes to the UI Culture in Chocolatey 0.9.x do not play nicely with PowerShell DSC's i18n.

Normally with  a US English culture DSC would find a resource at: `C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\en-US\PSDesiredStateConfiguration.Resource.psd1`

However, with an invariant culture, DSC attempts to look for a resource that does not exist: `C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.Resource.psd1`

Was there any reason for overriding the UI Culture during the package install? Is there a way of overriding this?

Cheers,
Warner

**Comment by ferventcoder** [comment]
We did this for a few reasons:
* Turkish culture and capital "I" - https://github.com/chocolatey/chocolatey/issues/22
   *  semi-related - https://github.com/chocolatey/chocolatey/issues/152

**Comment by ferventcoder** [comment]
FYI, it's not something new we introduced in 0.9.9.x - it's been in the code base of chocolatey for 3+ years.

**Comment by ferventcoder** [comment]
However, it does appear that the rewrite may be introducing another issue not seen before.

**Comment by ferventcoder** [comment]
@warnergodfrey ping.

**Comment by warnergodfrey** [comment]
Sorry, this slipped off my radar. We have implemented a workaround for the issue by copying the resource to the expected location. It's a nasty hack, but all we have available right now.

I didn't realise that the change to the UI culture was applied a while back. On 0.9.8.x we could run DSC from within a package install script without any errors.

Given DSC applies the configuration as the system user, is it possible that the invariant UI culture is applied to the system user as well as the user performing the install?

**Comment by ferventcoder** [comment]
Hmm. Any new thoughts on this one?

I imagine we could offer some sort of switch to shut it off (and set it as a feature so it doesn't have to be passed every time).

**Comment by ferventcoder** [comment]
#1441

**Comment by pauby** [comment]
Due to this issue being stale, I'm going to go ahead and close it. We can always re-open it again if needed.
