### ISSUE TITLE
Cannot uninstall on windows

### ISSUE THREAD

**Issue by bitsofinfo** [chocolatey/choco#2922]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

I am logged in with a local administrator account

Following the install doc on the choco site I ran this command

```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
```

I installed a few packages OK

Then i tried to uninstall chocolately following this page https://docs.chocolatey.org/en-us/choco/uninstallation

But... i cant delete c:\programdata\chocolately because i get `the action cannot be completed because the file is open in another program` error

When I look at task manager I see several `choco` and `choco shim` related processes. 

I can't end the processes.

How do I remove this? How do i stop those processes? The install/uninstall docs make no mention of this, the only mention is in your "business licensed docs" ... which I am not using.

### What is Expected?

should be able to uninstall per the guide

### How Did You Get This To Happen?

followed instructions

### System Details

windows 10 latest, latest choco

### Installed Packages

```bash
none
```

### Output Log

```bash
none
```

**Comment by bckelley** [comment]
I have this same issue... who makes software without making a way to uninstall it??

**Comment by paulmsullivan** [comment]
> I have this same issue... who makes software without making a way to uninstall it??

If you think this was intentional then it’s not a big right?

**Comment by pauby** [comment]
> But... i cant delete c:\programdata\chocolately because i get the action cannot be completed because the file is open in another program error

> When I look at task manager I see several choco and choco shim related processes.

> I can't end the processes.

> How do I remove this? How do i stop those processes? The install/uninstall docs make no mention of this, the only mention is in your "business licensed docs" ... which I am not using.

Have you tried rebooting your computer?

If files are locked or processes can't be killed this is the first thing to try.

**Comment by pauby** [comment]
> I have this same issue... who makes software without making a way to uninstall it??

There is a way to [remove it](https://docs.chocolatey.org/en-us/choco/uninstallation).

**Comment by bckelley** [comment]
> > I have this same issue... who makes software without making a way to uninstall it??
> 
> There is a way to [remove it](https://docs.chocolatey.org/en-us/choco/uninstallation).

with thoughs warnings that's gonna scare some people I ran them so far seems ok haven't rebooted yet 🤞🏻

**Comment by bitsofinfo** [comment]
@bckelley yes even after a reboot these 2 processes are running

**Comment by bitsofinfo** [comment]
> > @bckelley yes even after a reboot these 2 processes are running
> 
> why tag me in this ... I'm also having this issue
@pauby

**Comment by pauby** [comment]
Can you provide the output of (from an ELEVATED PowerShell session) `Get-Process -Name choco*` and `Stop-Process -Name choco*`?

Note the PowerShell needs to be elevated. Please confirm it is.

**Comment by gep13** [comment]
@bitsofinfo @bckelley We haven't heard from either of you regarding this problem for a while now, and we haven't been able to reproduce the problem internally.

I am going to go ahead and close out this issue.  If you are still having a problem, then please feel free to respond again.
