### ISSUE TITLE
Ability to run "choco upgrade all" ignoring specific packages

### ISSUE THREAD

**Issue by christianrondeau** [chocolatey/choco#293]
Example use cases:

* Every morning I run `cup all -y` using ConEmu. If ConEmu has an update available, it kills the update process as the console restarts. I want to upgrade ConEmu last.
* I'm using Skype with someone and run `cup all`, it closes Skype and stops my call. I want to upgrade Skype later

I suggest adding a new `except` argument to the `choco upgrade` command:

```
cup all -y --except=ConEmu
cup ConEmu -y
```

Even better would be able to provide a list of exceptions, e.g.:

```
cup all -y --except=Conemu,Skype
```

For the original conversation, see https://groups.google.com/forum/#!topic/chocolatey/kh-qq_4o2UA

**Comment by ferventcoder** [comment]
Sorry, needed to change the title. It will continue to run when there are errors (which is closely related to the word exception) and I didn't want to confuse myself.

**Comment by pyhedgehog** [comment]
Can't `choco pin` help you?
I'm using it for this purpose. However I'm running `choco outdated` beforehand.

**Comment by christianrondeau** [comment]
@pyhedgehog It could, but `pin` is "permanent", so here's what I'd have to run for the "sequence" problem:

```
cup pin add -n=ConEmu
cup all -y
cup pin remove -n=ConEmu
cup ConEmu -y
```

Same thing for when I don't want to update on specific software, I could also use `pin` but if I can easily forget to remove it. Also, "pinning" is not the intention here, so it's less obvious.

Otherwise, you are correct that `pin`is the solution until there is a `--expect` parameter.

**Comment by pyhedgehog** [comment]
Should `cup ConEmu -y --force` work in this case?
I've checked it with `--noop` and it doesn't. I think this is a bug,,,

**Comment by ferventcoder** [comment]
If the process is in use, the package is going to fail. It should however not error on --noop. That would be a valid bug.

**Comment by dstj** [comment]
After running `cup all -y` while on Skype today, I had the "issue" where Skype was closed mid-call to update. Having a `cup all -y --except=skype` would have been helpful today.

**Comment by aronovgj** [comment]
even better would be something like
`cup all -y --except=running`

to prevent upgrading all programs which are currently running

**Comment by christianrondeau** [comment]
This would be an entirely new and separate feature however (in this specific feature, we simply have to skip the specified ones, but in your suggestion, we'd have to know which executables are linked to which packages). Also, how do you define "running", if there's a background service, or a tray bar program?

Still not a bad idea, but I would post and discuss the idea on Google Groups (https://groups.google.com/forum/#!forum/chocolatey)
