### ISSUE TITLE
"Package Not Found" errors when version not specified.

### ISSUE THREAD

**Issue by djsdjsgithub** [chocolatey/choco#297]
Observed on "git" package (which has not been updated) on Windows 8, 7 and 2008.
Observed on recently uploaded package (new).

Originally I thought that specifying the version number gets around the error, but it does not do so on PowerShell 2.0.

Sample error:

2015-05-30 15:24:15,029 [ERROR] - nektraspystudio not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"
2015-05-30 15:24:15,056 [WARN ] - 
Chocolatey installed 0/1 package(s). 1 package(s) failed.

**Comment by ferventcoder** [comment]
PowerShell version wouldn't matter for finding the package anymore.

The particular package you are attempting to install has not been approved, therefore would not be installable without a version. It is NOT in the source because it has not been approved, but it IS unlisted, which means you should be able to install it if you specify the right version.

However, if you can't - consider that it is NOT yet approved and you shouldn't be installing it yet anyway. :)

![image](https://cloud.githubusercontent.com/assets/63502/7903976/f18e1f98-07b1-11e5-9c92-21730bc5510b.png)

**Comment by djsdjsgithub** [comment]
I authored that package and was testing it.

However, this also happened with git - which is months old.

Happening on multiple different packages on different versions of PowerShell.  Happens on procmon package as well.  Procmon has a pending moderation release, but git does not.

Not sure what the commonality is - but this is happening on scripts I have been running for quite some time.

D.

**Comment by ferventcoder** [comment]
When it does happen, please open an issue and include the log on one of those that is not under moderation. Also make sure when you do, you have used `-dv` as part of the command to capture verbose and debugging logs. Thanks!

**Comment by ferventcoder** [comment]
And make sure to include the FULL log of that and not just what you might feel is relevant. It helps us to understand what the configuration is reporting.

**Comment by mbirth** [comment]
I have this with these packages:

- autohotkey
- autohotkey.install
- fiddler4
- php
- sqlite

Other packages work fine, e.g. 7zip, golang, gimp and several more.

Installing the "not found" packages by specifying a version number worked.


Verbose debug output only says:
```
[NuGet] Exception has been thrown by the target of an invocation.

autohotkey was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.

 Version: ""; Source(s): "https://chocolatey.org/api/v2/"
[NuGet] Exception has been thrown by the target of an invocation.

autohotkey.install was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.

 Version: ""; Source(s): "https://chocolatey.org/api/v2/"

```


Here's a complete log for the SQLite package: http://pastebin.com/5kUaTbPf

**Comment by ferventcoder** [comment]
This could be related - https://github.com/chocolatey/choco/issues/1082
