### ISSUE TITLE
Make chocolatey installable via winget

### ISSUE THREAD

**Issue by Wallby** [chocolatey/choco#2989]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Describe The Solution. Why is it needed?

I saw that Chocolatey GUI is installable via winget.
I think it would be helpful if Chocolatey could be installed (and updated and removed) via winget instead of requiring executing a Powershell command.
Even just an .msi installer for Chocolatey would be great really.

**Comment by pauby** [comment]
We are working towards releasing an MSI of Chocolatey. See this [discussion](https://github.com/chocolatey/choco/discussions/2686) for more information.

As this will be a natural outcome of that, I will go ahead and close this.
