### ISSUE TITLE
Allow upgrade to always install missing packages

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#300]
The intent behind `choco upgrade git` issued against a machine is that I want the latest version of git installed on that machine. Whether that is upgrade or install doesn't really matter.

On a machine I issue the command `choco install git`, I just want to ensure git is installed. If instead I issue the command `choco upgrade git` on a machine, the end state I want for the machine is to have it installed and up to date on the latest version of git. Whether git was there before or not is not something I'm concerned with. The end state is that I want git on the most up to date version based on Chocolatey.

**Comment by bean5** [comment]
Keep up the good work! Choco is awesome!

**Comment by ssbarnea** [comment]
Does this mean that currently there is no way to quickly assure that latest versions are installed? If upgrade always (re)installs, this may be a very slow operations.

**Comment by ferventcoder** [comment]
@ssbarnea no idea what you mean. 

> Does this mean that currently there is no way to quickly assure that latest versions are installed?

`choco upgrade all`

> If upgrade always (re)installs, this may be a very slow operations.

Upgrade only installs newer versions if they are available, and will only install a missing install if you call upgrade on a non-existing package.

So not really sure what you are stating here.

**Comment by ferventcoder** [comment]
> Does this mean that currently there is no way to quickly assure that latest versions are installed?

Also right now if you call upgrade on an non-existing package, it will warn on a deprecation notice but install it. This issue is about removing the deprecation warning and allowing the behavior
