### ISSUE TITLE
On install of Chocolatey, the chocolatey.nupkpg isn’t copied into lib\chocolatey directory

### ISSUE THREAD

**Issue by ericfrancis** [chocolatey/choco#301]
Installed chocolatey, ran `choco outdated` and saw chocolatey listed as outdated. `choco list -lo` lists two versions of chocolatey.

@ferventcoder pointed me to the issue: on install, the nupkpg isn’t copied into the chocolatey directory

**Comment by ferventcoder** [comment]
Thanks for filing!

**Comment by ferventcoder** [comment]
This would have been a duplicate of #19

**Comment by ferventcoder** [comment]
Actually no, there was another issue somewhere here.

**Comment by ferventcoder** [comment]
Found it - https://github.com/chocolatey/choco/issues/414 and https://github.com/chocolatey/chocolatey.org/issues/225
