### ISSUE TITLE
Choco install hangs after requesting confirmation to continue

### ISSUE THREAD

**Issue by Bobs-code** [chocolatey/choco#3034]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

After confirming to choco to run the installation script, installation hangs. Issue still persists after multiple attempts and even with executionTimeout set to a higher value. 

### What is Expected?

I expected the installation to either complete and a success message to be displayed in the output or for an error message to be displayed in the output. Neither message is displayed. 

### How Did You Get This To Happen?

1. Disabled AV.
2. Did a full uninstall, as per the docs (https://docs.chocolatey.org/en-us/choco/uninstallation)
3. An install again (https://chocolatey.org/install)
4. Ran choco config set --name commandExecutionTimeoutSeconds --value 300
5. Ran  choco install golang --trace --log-file=<PATH TO A LOG FILE> (where <PATH TO A LOG FILE> is the path to a ... log file to capture the output) and let it complete (took about  7 minutes).
6. Ran choco config set --name commandExecutionTimeoutSeconds --value 2700 

### System Details

* Operating System: 10.0.19045.0
* Windows PowerShell version: 5.1
* Chocolatey CLI Version: 1.3.0
* Chocolatey Licensed Extension version: Chocolatey v1.3.0
* Chocolatey License type: Individual
* Terminal/Emulator: Windows PowerShell

### Installed Packages

```bash
n/a
```

### Output Log

```bash
https://gist.github.com/Bobs-code/83fa8bf2919de1f0d6a48ff13b8437b6
```

**Comment by piotr-cz** [comment]
I'm having exactly same issue, including output from chocolatey.log as in provided gist.
I'm using Avast Free Antivirus, but issue remains even when I disable it.

**Comment by pauby** [comment]
@Bobs-code @piotr-cz Are you running Chocolatey CLI from within PowerShell ISE? If not, what terminal are you using?

**Comment by piotr-cz** [comment]
I've tried with PowerShell in Windows Terminal and with standard Command Prompt (from Windows Start menu) with same results.

**Comment by vexx32** [comment]
Is this _only_ happening with the golang package, or are you seeing the same behaviour with other packages as well (and if so, which ones?)

**Comment by piotr-cz** [comment]
This happens whenever I try to update any package, even chocolatey itself.
By thy way, I updated chocolatey manually to 1.3.0 but issue persist

**Comment by vexx32** [comment]
Can I ask y'all to downgrade to v1.2.0 or v1.1.0 to see if those versions are also affected? I've not been able to reproduce this issue myself just yet, still trying to get an environment where I see this issue.

**Comment by Bobs-code** [comment]
Here is a link to an updated log after removing avast:

- https://gist.github.com/Bobs-code/0310189147407913f50bc6652e617521

**Comment by vexx32** [comment]
Removing Avast does seem to fix the immediate problem, huh? Weird.

I can confirm that on my own Win10 Pro system with current updates, I see this issue also with Avast installed specifically, regardless of the settings in Avast itself as far as I can tell.

Removing Avast seems to resolve the issue. I am however able to install `golang` successfully, so I suspect that there is something else going on for you there as well, but I'm not sure what. If you're only seeing it with that one package I would recommend:

- Resetting your network adapter
- `ipconfig /flushdns`
- A system reboot

And then try again, and if it persists for that package and nothing else, it might be worth contacting the package maintainer.

For this issue specifically though, I think it's safe to say it was some strange interaction with a recent Windows update and the Avast Free antivirus solution.

**Comment by kaiserl4961** [comment]
Hello, I have the same problem and still cannot seem to fix it. Here is my Reddit post which pointed me here https://www.reddit.com/r/chocolatey/comments/114b1mf/install_getting_hung_up/

**Comment by notHiks** [comment]
as a work around of sorts, the gui version still works with avast installed.

**Comment by medmedin2014** [comment]
But if it's Avast problem why does other apps work fine with the antivirus and only choco suffers from this kind of bug ? It seems to be related to choco and due to some binary or bad/dangerous library embedded with choco.

**Comment by pauby** [comment]
The same question could be asked 'if Chocolatey CLI is the problem why is no other antivirus product behaving in this way'?

And if Avast was detecting soemthing, what is it detecting? Did you find anything in the logs, notificatins, alerts?

From what we can see, uninstalling Avast is the solution.

I'm going to go ahead and lock this issue now as it has been resolved.
