### ISSUE TITLE
Allow defaulting `choco outdated` to always use --ignore-pinned

### ISSUE THREAD

**Issue by flcdrg** [chocolatey/choco#3039]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

I always run `choco outdated --ignore-pinned`

I never run it without `--ignore-pinned` (or if I did, I didn't mean to!)

### Describe The Solution. Why is it needed?

Make --ignore-pinned the default, or alternatively give me a way to opt in to be the default.

**Comment by gep13** [comment]
@flcdrg I think that this issue is the same as this one https://github.com/chocolatey/choco/issues/580

Thoughts?  This will be a breaking change, so we have opted to delay it until the next major release.

If you agree that this is a duplicate, we can close out this issue.

**Comment by flcdrg** [comment]
I think it probably is. If it was settable by the 'features' thing then you could opt in to the behaviour so it wasn't breaking
