### ISSUE TITLE
autouninstaller can fail when there's also a chocolateyUninstall.ps1

### ISSUE THREAD

**Issue by mrdima** [chocolatey/choco#304]
When chocolateyUninstall.ps1 does an uninstall / cleanup or whatever it needs to do, the autouninstaller kicks in too soon it seems...

For inno setup installers, de uninst000.exe is deleted eventually by the chocolateyUninstall.ps1 kicking off the uninstall, but when the autouninstall is triggered it's still there, but the unins000.dat has already been removed. It's probably something with the windows installer service still finalizing things.
Doing a Start-Sleep -Seconds 10 at the end in the chocolateyUninstall.ps1 can be done as a workaround as the Windows Installer Service has probably finished cleaning up everything which the autouninstall will then notice.

For MSI's we got something similar...the key is still there but already removed when msiexec kicked off from the uninstaller is going to do its thing (but I'm not sure)

VERBOSE: Exporting alias 'Add-BinFile'.
VERBOSE: Exporting alias 'Remove-BinFile'.
Command ['"MsiExec.exe" /X{BA7FB0F2-4B28-444F-8199-CF8402DA342E} /qn /norestart'
] exited with '1605'
Auto uninstaller failed. Please remove machine installation manually.
centerityagent-plugins uninstall not successful.
Auto uninstaller failed. Please remove machine installation manually.
[NuGet] Removed file 'chocolateyinstall.ps1' to folder 'C:\Chocolatey\lib\Whatever\tools'.
[NuGet] Removed file 'chocolateyuninstall.ps1' to folder 'C:\Chocolatey\lib\Whatever\tools'.
[NuGet] Removed folder 'C:

**Comment by ferventcoder** [comment]
1605 is being added as a valid uninstall exit code, since it means the product is not installed

**Comment by ferventcoder** [comment]
Adding that for #305.

**Comment by ferventcoder** [comment]
Why 10 seconds?

**Comment by mrdima** [comment]
No reason, it was arbitrary and proven to be long enough on 1 system I tested, but might not be enough for others. I really hope there's some better way to detect whether the uninstall is truely finished cleaning up...I noticed chocolatey returning on the msi uninstall but the directory were still there for a few seconds (doing just dir c:\install dir after cuninst)...

**Comment by ferventcoder** [comment]
That's fair.

**Comment by ferventcoder** [comment]
This is completed with https://github.com/chocolatey/choco/commit/b82436bff554bc435b2a515cce28a4f561441c35

**Comment by mrdima** [comment]
I'm sorry to say that after re-investigating the reason for the auto-uninstaller to fail is indeed caused by the uninstallers still running which was triggered from chocolateyUninstall.ps1, but this shouldn't normally happen. It happened because I used Invoke-Expression to run the uninstaller which apperently doesn't wait for the proces to exit (at least not for inno setup or msiexec processes). If I modify that (in this case in less pretty Invoke-Expression cmd.exe /c start /w dotheuninstallthing, but could use other Powershell commands to start the proces which includes waits) everything works fine. So the workaround with a sleep timeout wasn't necessary though maybe there's cases where this is convenient to have) but you can reconsider this patch. Great work in #305!

**Comment by ferventcoder** [comment]
Posh v3 has issues with wait - we have bits built in to make the process wait - as long as you are using start-chocolateyprocessasadmin it should block.
