### ISSUE TITLE
Add powershell to linux docker image

### ISSUE THREAD

**Issue by jpatigny** [chocolatey/choco#3056]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

It would be nice to be able to use powershell in the linux docker image.
For example, i'm packing the package with the binary embedded and I need to download this before.
Currently I have to do it bash which I don't have a lot of knowledge of.

### Describe The Solution. Why is it needed?

Install powershell package (available in source packages-microsoft-prod which is already added during image build)
Copy necessary files to final image layer un docker

### Additional Context

I'm willing to help on the one if necessary :- )

**Comment by pauby** [comment]
I don't think this is something we want to add as it's another dependency for the Docker image. So if PowerShell gets an update, do we have to release a new image as people will expect that? Lets say there's a CVE / ciritical bug, are we then forced to release a new version of the image? It puts additional burden on the team to do that when you can already add it to the image. 

Having said all of that, I can see why it would be nice to have.

@gep13 @AdmiringWorm @TheCakeIsNaOH any thoughts on this?

**Comment by TheCakeIsNaOH** [comment]
I would agree with @pauby that it would be an unnecessary item to maintain in the Linux image. It also would increase image size for users that do not need PowerShell.

It is fairly simple to create your own image with PowerShell included. https://blog.chocolatey.org/2022/01/announcing-docker-images/#using-a-container-for-automatic-package-au
