### ISSUE TITLE
Broken version compare for 2 digit versions

### ISSUE THREAD

**Issue by timmjd** [chocolatey/choco#3064]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

It seems the ordering of chocolatey to install the `latest` is broken if the version of a package is only specified by 2 digits.

For a custom made chocolatey package hosted on Artifactory the output is the following:
```
choco search 7zip --all-versions

7zip 9.38
7zip 9.36
...
7zip 3.13
7zip 4.20
7zip 22.01
7zip 22.00
7zip 21.07
...
7zip 15.06
7zip 15.05
```

Installing the `latest` version (`choco install 7zip`) will install version `9.38` instead of `22.01`.

If I rename the version `22.01` to become 3 digits: `22.01.0` the it will be detected as the `latest` package and  the ordering for this particular package is correct. Also the ordering seems to be correct only if 3 digits are provided.

Somehow it seems chocos logic is:
```
9.38 > 22.01
22.01.0 > 9.38
```

### What is Expected?

Version compare operators like < or > should work also for 2 digit versions.

### How Did You Get This To Happen?

1. I created a custom package with only 2 digit versions
2. I uploaded it to my Artifactory instance
3. I installed the packager from Artifactory
4. I don't get the `latest version` but version  `9.38`

### System Details

* Operating System:
* Windows PowerShell version:
* Chocolatey CLI Version:
* Chocolatey Licensed Extension version:
* Chocolatey License type:
* Terminal/Emulator:

### Installed Packages

```bash
chocolatey 1.3.0
```

### Output Log

```bash
.
```

**Comment by gep13** [comment]
@timmjd are you in a position to capture the HTTP requests that are being made between choco.exe and Artifactory?  This would typically be done using something like Fiddler.  This would allow you to "see" the outgoing HTTP request that choco.exe is making, as well as the response that is coming back from Artifactory.

The reason that I ask is that from what you have described, this is an issue with the response coming back from Artifactory.  choco.exe can only act on the information that it is given, and if the response to the `choco install` queries is to install this version, that is what it will do.

Having said that, another thing that would be good to try would be to disable the repository optimizations feature, as this has been known to cause problems with some repository servers.

This can be done using:

```
choco feature disable --name="'usePackageRepositoryOptimizations'"
```

and see if that makes any difference.

**Comment by timmjd** [comment]
Hmmmm - might be an Artifactory issue:
```
https://artifactory.***.de/artifactory/api/nuget/v3/***_nuget_l
https://artifactory.***.de/artifactory/api/nuget/v3/***_nuget_l/$metadata
https://artifactory.***.de/artifactory/api/nuget/v3/***_nuget_l/Search()?$orderby=Id,Version%20desc&$skip=0&$top=30&searchTerm='7zip'&targetFramework=''&includePrerelease=false
https://artifactory.***.de/artifactory/api/nuget/v3/***_nuget_l/Search()?$orderby=Id,Version%20desc&$skip=30&$top=30&searchTerm='7zip'&targetFramework=''&includePrerelease=false
```

* Nuget endpoint is version 3.0
* First reply of the search is version 9.38 and not 22.0
```xml
<?xml version='1.0' encoding='UTF-8'?>
<feed xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom" xml:base="https://artifactory.***.de/artifactory/api/nuget/***_nuget_l/">
  <title type="text"></title>
  <id>http://schemas.datacontract.org/2004/07/</id>
  <updated>2023-03-15T10:47:34Z</updated>
  <link rel="self" title="Search" href="Search"/>
  <entry>
    <id>https://artifactory.***.de/artifactory/api/nuget/***_nuget_l/Packages(Id='7zip',Version='9.38')</id>
    <title type="text">7zip</title>
    ...
  </entry>
</feed>
```

Also another endpoint of Artifactory told has wrong feelding about the upper version:
https://artifactory.***.de/artifactory/api/nuget/v3/***_nuget_l/registration/7zip/index.json
```json
{
  "count":1,
  "items": [{
    "count":12,
    "lower":"15.05",
    "upper":"9.38",
    "@id":"https://artifactory.***.de/artifactory/api/nuget/v3/***_nuget_l/registration/7zip/page/15.05/9.38.json"
  }],
  "@id":"https://artifactory.***.de/artifactory/api/nuget/v3/***_nuget_l/registration/7zip/index.json"
}
```

So due to Artifactorty seems to handle 2 digit versions incorrectly, also the Chocolatey implementation does not do any "reorder" of the incorrect information arriving. So I would assume I need to raise a ticket at Jfrog about this.

**Comment by TheCakeIsNaOH** [comment]
> So I would assume I need to raise a ticket at Jfrog about this.

That probably would be the best course of action, yes. 

It may also be worth checking what the behavior of the new Chocolatey CLI v2.0.0 alpha, if you have a non-production machine to test on. 
https://docs.chocolatey.org/en-us/choco/release-notes#alpha-20230307-march-7-2023
https://github.com/chocolatey/choco/discussions/2995

Also, v2.x of Chocolatey CLI will start to normalize package versions when packing, so two-part versions will be normalized to three part versions, following NuGet behavior.

**Comment by pauby** [comment]
As there isn't anything more for us to do here, I'm going to go ahead and close this, but we can reopen it if necessary.

**Comment by jansohn** [comment]
@timmjd for tracking references, did you open a ticket with JFrog? If yes, what's the ticket number / link?
