### ISSUE TITLE
Values passed as package params/install args may be parsed by the NDeskOptions Parser if not quoted properly

### ISSUE THREAD

**Issue by sitano** [chocolatey/choco#307]
I do:

$> cinst package -s . -y -ia "-dc=vagrant -log-level=debug"

What i've got:

$env:TEMP = /c/ProgramData/chocolatey/=vagrant -log-level=debug

= thats kinda broken. -ia should not touch $env:TEMP any how.

Why is this important?

Helper functions generate invalid temporary paths during various operations like: Install-ChocolateyZipPackage.

Debug output header:

```
Chocolatey v0.9.9.6
Chocolatey is running on Windows v 6.2.9200.0
Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
Command line: "C:\ProgramData\chocolatey\choco.exe" install consul -s . -y -dv -ia "-dc=vagrant -log-level=debug"
Received arguments: install consul -s . -y -dv -ia -dc=vagrant -log-level=debug

NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
Configuration: CommandName='install'|CacheLocation='=vagrant -log-level=debug'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|Sources='.'|Debug='True'|
Verbose='True'|Force='False'|Noop='False'|HelpRequested='False'|
RegularOutput='True'|PromptForConfirmation='False'|
AcceptLicense='True'|
AllowUnofficialBuild='False'|Input='consul'|AllVersions='False'|
SkipPackageInstallProvider='False'|PackageNames='consul'|
Prerelease='False'|ForceX86='False'|
InstallArguments='-dc=vagrant -log-level=debug'|
OverrideArguments='False'|NotSilent='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|ForceDependencies='False'|
Information.PlatformType='Windows'|
Information.PlatformVersion='6.2.9200.0'|
Information.PlatformName='Windows Server 2012'|
Information.ChocolateyVersion='0.9.9.6'|
Information.ChocolateyProductVersion='0.9.9.6'|
Information.FullName='choco, Version=0.9.9.6, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64Bit='True'|Information.IsInteractive='True'|
Information.IsUserAdministrator='True'|
Information.IsProcessElevated='True'|Features.AutoUninstaller='False'|
Features.CheckSumFiles='True'|ListCommand.LocalOnly='False'|
ListCommand.IncludeRegistryPrograms='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
NewCommand.AutomaticPackage='False'|SourceCommand.Command='unknown'|
FeatureCommand.Command='unknown'|PushCommand.TimeoutInSeconds='0'|
PinCommand.Command='unknown'|
_ Chocolatey:ChocolateyInstallCommand - Normal Run Mode _
Installing the following packages:
consul
```

**Comment by ferventcoder** [comment]
Got it - `|CacheLocation='=vagrant -log-level=debug'|`

**Comment by sitano** [comment]
btw, i did wrote PowerShell $env:ChocolateyInstallArguments string parser which can transpose it to [hashtable] in format: -ia '-key=value, -key="value "" value"'. May be you are interesting in merging it into the helpers.

**Comment by ferventcoder** [comment]
@sitano perhaps on that. Let's open a separate issue for that. For this it appears the options parser is incorrectly grabbing -c (as part of -dc):

As a test add `--noop` to your call and run this: 

`choco install consul --noop -ia "-dvy"` and watch how it affects the configuration.

**Comment by ferventcoder** [comment]
Are you stating this messes up $env:TEMP outside of chocolatey? Like when it finishes running $env:TEMP is somehow messed up as well? Or something you are doing in the package?

**Comment by sitano** [comment]
No, it messes up `$env:TEMP` inside and before the chocolateyInstall.ps1 environment.

**Comment by ferventcoder** [comment]
Okay, great, only local to choco. This is still pretty bad.

**Comment by sitano** [comment]
about --noop
```
PS C:\svn\PowershellScripts\Consul\Chocolatey> cinst.exe consul -s . -y --noop -ia "-dva"
Chocolatey v0.9.9.6
_ Chocolatey:ChocolateyInstallCommand - Noop Mode _
Chocolatey would have used NuGet to install packages (if they are not already installed):
consul
consul not installed. An error occurred during installation:
 Unable to resolve dependency 'nssm (≥ 2.24.0)'.
Value cannot be null.
Parameter name: path
```
actually i need to prep some stub package for tests, coz in `--noop` mode it can not resolve a nssm dep.

**Comment by ferventcoder** [comment]
I have a workaround for you - `choco install consul -s . -y -dv -ia "'-dc=vagrant -log-level=debug'"

**Comment by ferventcoder** [comment]
For the noop, since it will attempt to resolve dependencies, just pass `--ignore-dependencies` as well.

**Comment by sitano** [comment]
yeah... actually this will end up args hell, coz sometimes i have inside something like -ia "-join '{""blah"":[1,2,3]}'"

**Comment by ferventcoder** [comment]
Take a look at https://github.com/chocolatey/choco/wiki/CommandsReference#how-to-pass-options--switches (Quote values bit).

**Comment by ferventcoder** [comment]
And for anything where quotes needs to go through, check out pass quotes in arguments (right after quote values).

**Comment by sitano** [comment]
-ia "'...'" working yes

**Comment by sitano** [comment]
thanks for the link on quoting :+1:

**Comment by ferventcoder** [comment]
> sometimes i have inside something like -ia "-join '{""blah"":[1,2,3]}'"

That looks somewhat scary. I wonder if there is a better way to pass those in.

**Comment by sitano** [comment]
It could be: `echo '{"key":[1,2,3]}' | cinst consul -s . -y -ia`, i use `cinst consul -s . -y -ia "{'key':[1,2,3]}"`

**Comment by ferventcoder** [comment]
One thing to consider is that key will be evaluated by PowerShell first, so you could use `` `'key`' ``
