### ISSUE TITLE
Add PowerShell helper function to manage removing paths from $PATH

### ISSUE THREAD

**Issue by mrdima** [chocolatey/choco#310]
There is a useful helper Install-ChocolateyPath which I use to add directories to the PATH variable. I would like to see an Uninstall-ChocolateyPath as well to cleanup those directories from the PATH variable at uninstall time.
I guess this would apply to quite a few other helpers which only have an "Install" part.

**Comment by ferventcoder** [comment]
Yep, we had something logged somewhere for these.

**Comment by tirolo** [comment]
Wanna open it up for grab?

**Comment by ferventcoder** [comment]
@tirolo done.

**Comment by mrdima** [comment]
Just for an idea, wouldn't it be nice if the auto-uninstaller would be able to take care of this as well? Either snapshot the environment before and after the install (or only PATH environment variable) or have Install-Chocolatey log something for the uninstall

**Comment by ferventcoder** [comment]
Sounds nice - keep in mind it should only remove the added values and not
restore the previous version (that would be bad).

On Wednesday, November 25, 2015, mrdima <notifications@github.com> wrote:

> Just for an idea, wouldn't it be nice if the auto-uninstaller would be
> able to take care of this as well? Either snapshot the environment before
> and after the install (or only PATH environment variable) or have
> Install-Chocolatey log something for the uninstall
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/310#issuecomment-159693169>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by tirolo** [comment]
Will start working on this one as soon as I get my read around the docs I have to read before start contributing + learn some github :) (shouldn't take long)

**Comment by tirolo** [comment]
@ferventcoder Should I target master?

**Comment by ferventcoder** [comment]
@tirolo master is set for 0.9.11.x, and stable is set for 0.9.10.x. I'd target stable if you can.

**Comment by sindux** [comment]
There was a PR for this in the old chocolatey repo https://github.com/chocolatey/chocolatey/pull/542

**Comment by ferventcoder** [comment]
@DarwinJS See - #303

**Comment by DarwinJS** [comment]
Not sure if it's still relevant, but here is a link to the code I put together for this today.  The code I did also handles removing duplicates (if the path to remove is in more than once), handles the path whether or not there is a trailing slash versus what is specified on the removal string and it handles removing extra ";' that are found.  The code is *not* generalized to handle both user and machine path.  https://github.com/DarwinJS/ChocoPackages/blob/master/ec2clitools/tools/chocolateyuninstall.ps1
Not sure if it's still relevant, but here is a link to the code I put together for this today.  The code I did also handles removing duplicates (if the path to remove is in more than once), handles the path whether or not there is a trailing slash versus what is specified on the removal string and it handles removing extra ";' that are found.  The code is *not* generalized to handle both user and machine path.  https://github.com/DarwinJS/ChocoPackages/blob/master/ec2clitools/tools/chocolateyuninstall.ps1

**Comment by ferventcoder** [comment]
This is related to https://github.com/chocolatey/choco/issues/303

**Comment by DarwinJS** [comment]
I'll take this one.

**Comment by DarwinJS** [comment]
I am wondering a few things about this code:
*) Does it make sense to remove the requested string from both user and computer path?  On one hand if I was requesting a removal I would just want it gone no matter what paths it appeared on if the software was just removed.  On the other hand it may make uninstalls reach to things that weren't instended.

Hmmm - what if it could take params "user", "machine" and "all" ?  Should it default to "All" if unspecified or just always require the param?

**Comment by DarwinJS** [comment]
PR: https://github.com/chocolatey/choco/pull/1019

**Comment by improbablepiotr** [comment]
Are there any plans to merge the PR fixing this issue? Seems like this is being pushed to next milestones since Mar 22.

**Comment by ferventcoder** [comment]
@improbablepiotr yes, there are plans to merge. We've had a few higher priority things come in during the interim.

**Comment by jnm2** [comment]
@ferventcoder What's the status of that PR, and what's the recommended workaround until it's merged?

**Comment by jnm2** [comment]
@ferventcoder What's the status of that PR, and what's the recommended workaround until it's merged?

(The up-for-grabs label is stale.)

**Comment by Thieum** [comment]
What's the recommended way to remove a path installed with Install-ChocolateyPath?
Not doing so pops a guideline warning when publishing a package.

**Comment by aaccioly** [comment]
Hi guys, do you have an ETA on when you are planing to merge this feature?
I'm currently handling it manually but quite a bit of logic has to go in to make it reasonable robust (expand token, handle duplicated entries, handle empty paths, handle empty semicolons, etc)

**Comment by bazzilic** [comment]
So, 4 years later... still nothing? :)

**Comment by jnm2** [comment]
I have a PR up at https://github.com/chocolatey/choco/pull/1663.

**Comment by bazzilic** [comment]
which was created over a year ago...

**Comment by patmilano** [comment]
Another bump, this addition would be very helpful for package creation.

**Comment by simonewebdesign** [comment]
Just in case it may be helpful to anyone, this is how @DarwinJS did it - posting it here since the original repo was moved to GitLab:
https://gitlab.com/DarwinJS/ChocoPackages/-/blob/master/ec2clitools/tools/chocolateyuninstall.ps1

**Comment by FranklinYu** [comment]
Thanks, but would be nice if #1663 can be merged (or at least reviewed). Currently that PR seems to be simply ignored, I assume because it never got priority.

**Comment by teknowledgist** [comment]
Bumping with my vote for this.  It's in the homestretch; someone just needs to put on the gloves and give it a little polish.

**Comment by jmcker** [comment]
I suggested some changes on #1663 and have been using a [modified version](https://github.com/jmcker/ChocolateyPackages/blob/main/gstreamer/tools/Uninstall-ChocolateyPath-GH1663.ps1) for over a year. Hasn't destroyed anyone's `PATH` as far as I can tell.
