### ISSUE TITLE
Cannot use any builtin source like windowsfeatures

### ISSUE THREAD

**Issue by matteo-mosca** [chocolatey/choco#311]
I have the latest version 0.9.9.6 installed.
When trying to list packages like this:

`choco list --source windowsfeatures`

It says 0 packages found. If I try to install a package from there (like the example in the wiki) it always says the package is not found. The verbose option does not add any extra information.

Same goes for other builtin sources like webpi or ruby.

Listing and installing from default feed works properly.

Is this a bug or I am missing something? I could not find any help or prerequisites on your wiki.

Thanks.

**Comment by ferventcoder** [comment]
They are called alternate sources and they don't work in 0.9.9 series - see #14.
I just finished the last one yesterday #40

**Comment by ferventcoder** [comment]
It's also mentioned in the wiki they don't work right now.

**Comment by matteo-mosca** [comment]
Thank you for your reply. If it's mentioned maybe it's not clear enough though, otherwise I wouldn't have come here to post this.

What should I do then? Install an older version?

**Comment by gep13** [comment]
> What should I do then? Install an older version?

Yes.  If you need this feature right now, then falling back to the latest PowerShell client would be your only route, unless you are happy to wait for this feature to arrive in the C# client.

To install the latest PowerShell client you can use:

```
@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/Install-LastPoshClient.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin
```

Rather than:

```
@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin
```

**Comment by ferventcoder** [comment]
Probably an issue in naming of the source types.

**Comment by dhilgarth** [comment]
As you already implemented all these missing alternate sources can you name a release date for a version that includes them?

**Comment by ferventcoder** [comment]
0.9.10 has the alternate sources in it - there is an alpha version out now to play with. Barring any security issues, there is only one release before this release.

**Comment by dhilgarth** [comment]
Working great as far as I can tell. Thanks!
