### ISSUE TITLE
Sort list of installed/upgraded packages

### ISSUE THREAD

**Issue by Bananeweizen** [chocolatey/choco#3112]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

Consider the following screenshot:
![grafik](https://user-images.githubusercontent.com/406876/231478108-6e922207-9adb-4025-bff1-b0eaf6188400.png)

How many applications have been upgraded? 6? No, 4 only, because of the foo and foo.install package duality.

### Describe The Solution. Why is it needed?

Sorting the installed/upgraded packages would immediately group the foo and foo.install (as well as other "sibling") packages, making it way easier to get an overview of what changed from the _users_ point of view.

**Comment by pauby** [comment]
> How many applications have been upgraded? 6? No, 4 only, because of the foo and foo.install package duality.

While it might be semantics, Chocolatey CLI does not list the upgrade _applications_. It lists the upgraded _packages_. In that context, `foo` and `foo.install` have been upgraded.

What command did you run?

**Comment by Bananeweizen** [comment]
I've run `choco upgrade all` there. You are surely right about the semantics of packages (from the viewpoint of the chocolatey domain), but that is not what this issue is about. It's about mapping that output to the user's mental model. And my hypothesis is that the average user typically doesn't care that much about how the package structure (and dependencies) look like. She probably thinks more in terms of "applications installed with chocolatey", and then a sorted list might be easier to read and understand.

**Comment by pauby** [comment]
> You are surely right about the semantics of packages (from the viewpoint of the chocolatey domain), but that is not what this issue is about.

You said this:

> How many applications have been upgraded? 6? No, 4 only, because of the foo and foo.install package duality.

Which is what I responded to. Chocolatey doesn't manage applications. It manages packages. So, the output is correct as 6 packages were upgraded.

That's all I was clarifying for you.

Can the list of upgraded packages be sorted alphabetically? I'd imagine so.

**Comment by gep13** [comment]
While working on issue #508, specifically, an issue with uninstalling of packages when they are failing dependency resolution, it helped to have the output from `choco uninstall` command ordered alphabetically, to aid with understanding which packages had been removed.  In making this change, it also had the side-effect of fixing this request.  In fact, the change had the effect of ordering the output for the `install`, `upgrade`, and `uninstall` command.

As such, I am going to move this issue into the 2.0.0 milestone, as it will be fixed in that release.
