### ISSUE TITLE
Warn when unable to snapshot locked files

### ISSUE THREAD

**Issue by sitano** [chocolatey/choco#313]
The checksum snapshotting prevents service installation scenarios:

Package installation process looks like:
1) chocolateyInstall.ps1 run
2) download and unzip exe to choco/lib/package/something
3) register service 
4) start service
error here: 5) chocolatey checksum snapshot will fail to read ran exe file (service)

**Comment by ferventcoder** [comment]
This is no bueno. 

I wouldn't want to disable snapshotting, because otherwise it can't uninstall the files.

**Comment by ferventcoder** [comment]
Rather add some fault tolerance around the snapshot and let it continue.

**Comment by sitano** [comment]
yeah, got it. anyway, this pushes developer to keep such files outside of choco package install path.

**Comment by ferventcoder** [comment]
I'll be addressing this quickly, so hopefully you won't need to. 

What I'm stating here is:

1. Snapshotting is important.
2. Ignore the files that won't snapshot correctly.
3. Do not error and move on.

**Comment by sitano** [comment]
fully agree :+1:

**Comment by ferventcoder** [comment]
Yes - although if the files are inside the package, they will be removed by nuget core when uninstalled as long as they have not changed.

**Comment by sitano** [comment]
they actually are downloading during installation from the web by chocolateyInstall.ps1, so they are not there in advance

**Comment by ferventcoder** [comment]
Well darn. That makes it a bit hard to capture. One thing we could do is explore the Volume Shadow Service to get those checksums if it errors. That would be a followup to this though.

**Comment by ferventcoder** [comment]
Any chance you can provide a log so I can see where this happens at?

**Comment by ferventcoder** [comment]
In testing this, I don't see it as an error, just a warning. I've added code to add a special snapshot code for locked files, but without using something like Volume Shadow Copy Service there is no way to snapshot the locked file.

**Comment by ferventcoder** [comment]
Was your package installation failing on this or just giving you a warning?

**Comment by ferventcoder** [comment]
I created #321 to followup on a VSS type of fix to snapshot locked files. It's not the easiest thing to achieve so it's move back. For now this issue is resolved with a special snapshot code and a warning when removing the file.

**Comment by ferventcoder** [comment]
Added messaging in https://github.com/chocolatey/choco/commit/8a283d6162991298ca730306d519fcaf342ef20d
