### ISSUE TITLE
Installation of pip fails on windows 7

### ISSUE THREAD

**Issue by fakedrake** [chocolatey/choco#314]
Looks like python is not a dependency of this package. Not sure if the real problem is easy install but that seems to be an empty package. I am getting this:
<pre>
PS C:\> choco install pip
Chocolatey v0.9.9.6
Installing the following packages:
pip
By installing you accept licenses for the packages.

easy.install v0.6.11.4
The package easy.install wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting
'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
Do you want to run the script?
1) yes
2) no
3) print
1
Get-ChildItem : Cannot find path 'C:\Python27\Python.exe' because it does not exist.
At C:\ProgramData\chocolatey\lib\easy.install\tools\chocolateyInstall.ps1:27 char:26
Installing Python using chocolatey. Wait...
+ $file = Get-ChildItem <<<< $filename
+ CategoryInfo : ObjectNotFound: (C:\Python27\Python.exe:String)

[Get-ChildItem], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

    ildItemCommand
The install of easy.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\easy.install\tools\chocolatey
Install.ps1'.
 See log for details.

pip v1.2.0
The package pip wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting
 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
Do you want to run the script?
 1) yes
 2) no
 3) print
1
 Get-ChildItem : Cannot find path 'C:\Python27\Python.exe' because it does not e

 xist.
 At C:\ProgramData\chocolatey\lib\pip\tools\chocolateyInstall.ps1:18 char:26
 +     $file = Get-ChildItem <<<<  $filename
     + CategoryInfo          : ObjectNotFound: (C:\Python27\Python.exe:String)

    [Get-ChildItem], ItemNotFoundException
     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 Searching for pip
 Best match: pip 6.0.8
 Adding pip 6.0.8 to easy-install.pth file
 Installing pip-script.py script to C:\tools\python\Scripts
 Installing pip.exe script to C:\tools\python\Scripts
 Installing pip3-script.py script to C:\tools\python\Scripts
 Installing pip3.exe script to C:\tools\python\Scripts
 Installing pip3.4-script.py script to C:\tools\python\Scripts
 Installing pip3.4.exe script to C:\tools\python\Scripts
 Using c:\tools\python\lib\site-packages
 Processing dependencies for pip
 Finished processing dependencies for pip
 WARNING: Write-ChocolateySuccess is deprecated. If you are the maintainer,
 please remove it from your package file.
The install of pip was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\pip\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/2 package(s). 2 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
 - pip
 - easy.install
</pre>

**Comment by ferventcoder** [comment]
Package issues, unless an issue with core choco, should be directed at the maintainers through the package page itself. Thanks.
