### ISSUE TITLE
Unexpected invalid version string, `choco pack`

### ISSUE THREAD

**Issue by bdruth** [chocolatey/choco#3145]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

The version string `4.1.1.2100020230503` yields an error on `choco pack`, specifically:

> '4.1.1.2100020230503' is not a valid version string.
>   Parameter name: version

The version string `4.1.1.210001902` does not.

I can't find any reference to a length limitation in the [reference documentation](https://community.chocolatey.org/courses/creating-chocolatey-packages/naming-description-and-versioning).

### What is Expected?

Version string should be accepted as valid as it follows the convention outlined in the documentation:

> Date Package Fix Version Notation is recommended because one can ascertain what it is immediately upon seeing it, where sequential is not obvious on sight whether it is part of the software versioning or something special with the package.

> When the fourth segment is already used, it is recommended to add two zeroes (00) to the end of the version.

The original version is `4.1.1.210`, the date is `20230503`, yielding `4.1.1.2100020230503`

### How Did You Get This To Happen?

1. choco pack with version string `4.1.1.2100020230503`

### System Details

* Operating System: Linux
* Windows PowerShell version: n/a
* Chocolatey CLI Version: whatever's in the chocolatey docker image
* Chocolatey Licensed Extension version: n/a
* Chocolatey License type: n/a
* Terminal/Emulator: docker

### Installed Packages

```bash
N/A
```

### Output Log

```bash
/usr/bin/docker run --rm --env-file /tmp/env.txt --workdir /wksp --volume /home/runner/work/my-private-repo/my-private-repo:/wksp ghcr.io/crazy-max/ghaction-chocolatey pack my-package/my-package.nuspec fix_version=20230503
  Chocolatey v0
  
  Chocolatey is not an official build (bypassed with --allow-unofficial).
   If you are seeing this message and it is not expected, your system may
   now be in a bad state. Only official builds are to be trusted.
  
  '4.1.1.2100020230503' is not a valid version string.
  Parameter name: version
  Error: The process '/usr/bin/docker' failed with exit code 1
```

### Additional Context

Using github action `crazy-max/ghaction-chocolatey@v2`

**Comment by bdruth** [comment]
It would appear that there's an attempt to coerce the final number (or each segment) into an int32, max value would be 2,147,483,647. That's unfortunate.

**Comment by TheCakeIsNaOH** [comment]
@bdruth that Github action is not using an official build of Chocolatey, and it appears like the version number was not specified correctly when the binary was built. Since the logs don't say what version of Chocolatey CLI the image is built on, there is not really too much we can do here to help. I'd suggest asking the maintainer of the Github action to start using official builds of Chocolatey CLI.

> >   When the fourth segment is already used, it is recommended to add two zeroes (00) to the end of the version.

> The original version is 4.1.1.210, the date is 20230503, yielding 4.1.1.2100020230503

The two zeros should only apply when using sequential fix versioning, so with a version of `4.1.1.210` and a date of `20230503` would result in `4.1.1.21020230503`. Granted, that is still too long, but  `4.1.1.210230503` should work.

> It would appear that there's an attempt to coerce the final number (or each segment) into an int32, max value would be 2,147,483,647.

That sounds correct, I believe that System.Version is used for parsing under the hood. 

There are open issues to get the nuspec format documented:
https://github.com/chocolatey/docs/issues/375
https://github.com/chocolatey/docs/issues/374

**Comment by bdruth** [comment]
I noticed that if I add a dash and prefix the subsequent segment with an alpha, it allows that ... e.g. something like `4.1.1.210-a20230503` -- is this OK/legit? If the version bumps to `4.1.1.210-a20230504` will `choco` see that as an updated version? This is being pushed to a private Nexus repo (NuGet v2) if that matters?

**Comment by TheCakeIsNaOH** [comment]
That does work, but the dash makes it into a prerelease version. Prerelease packages will only be installed if the `--prerelease` switch is used when running `choco install`/`choco upgrade`

**Comment by bdruth** [comment]
Ah, gotcha. That won't work as there isn't a way to set that via the MDM. I'll go with your recommendation of shortening the year & removing the `00`. Thx!

**Comment by TheCakeIsNaOH** [comment]
I'll close this issue then, as this ended up being mostly a documentation issue, and the linked docs issues should take care of it.
