### ISSUE TITLE
"choco upgrade" does not know how to upgrade currently running applications

### ISSUE THREAD

**Issue by 40OIL** [chocolatey/choco#3152]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

"choco upgrade" does not know how to upgrade currently running applications.

### Describe The Solution. Why is it needed?

can you add the taskkill of the updated application before updating,
and launch it back after the update

**Comment by TheCakeIsNaOH** [comment]
@40OIL Chocolatey CLI does not upgrade applications, it upgrades packages. The package then upgrades the application. 
So it is the package's responsibility to close (and potentially reopen) applications if that is required.

Many software installers will close the application during the upgrade process, so there is not anything the package needs to do directly. But in the cases that the package needs to close an application, `Remove-Process` can be used. Or if more advanced usage is required, the `chocolatey-core.extension` has a `Remove-Process` function with more features. There is an example of `Remove-Process` here: https://github.com/AdmiringWorm/chocolatey-packages/blob/master/automatic/tablacus/tools/chocolateyBeforeModify.ps1

**Comment by pauby** [comment]
(I typed this earlier and didn't click 'Comment' so some of it duplicates what @TheCakeIsNaOH said). 

Chocolatey CLI manages packages. The package manages software. Chocolatey does not manage software.

It's the responsibility of the package to ensue that anything it needs to upgrade the software (in this case shutting down the currently running application) is performed.

My suggestion would be to reach out to the maintainer of the package you are having trouble with and ask them to add that functionality.

I'm going to go ahead and close this, but we can reopen it if necessary.
