### ISSUE TITLE
Unable to use choco install from mapped CIFS/SMB drive

### ISSUE THREAD

**Issue by koitsu** [chocolatey/choco#3156]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

There are plenty of age-old UNC-related bugs:

* https://github.com/chocolatey/choco/issues/1850
* https://github.com/chocolatey/choco/issues/1781
* https://github.com/chocolatey/choco/issues/1216
* https://github.com/chocolatey/choco/issues/1072 (may or may not be related)
* https://github.com/chocolatey/choco/issues/1055

...but this one seems to be new.

I cannot determine if "new" is due to newer versions of Chocolatey, or because a few months ago I upgraded to Windows 10.  I've been using this approach for testing for quite some time (on Windows 7) without problems.

I've spent literally an entire day on this trying to figure out what the actual problem is.  I went as far as to bust out Process Monitor to try and work out what Win32 calls were being issued, but I was not able to find the answer (likely because PowerShell/.NET is involved).

I happened to come across an old GitHub Issue mentioning the flag `--shimgen-log` -- which does not appear in `--help` output, by the way -- which got me a little closer to the root cause but not entirely.

Q: is a drive-letter-mapped CIFS/SMB share.  Permissions on that share are 100% fine and not the problem.

```
Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck>gsudo choco install keepass-plugin-hibpofflinecheck -dv -s . --shimgen-log
[shim]: Set up Shim to run with the following parameters:
  path to executable: D:\Chocolatey\choco.exe
  working directory: Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck
  is gui? False
  wait for exit? True
  command (optional):
[shim]: Command line '"D:\Chocolatey\bin\choco.EXE" install keepass-plugin-hibpofflinecheck -dv -s . --shimgen-log'
[shim]: Current process '"D:\Chocolatey\bin\choco.EXE"'
[shim]: Command line after removing process ' install keepass-plugin-hibpofflinecheck -dv -s . --shimgen-log'
[shim]: Arguments after removing shimgen args - 'install keepass-plugin-hibpofflinecheck -dv -s .'
[shim]: Arguments are 'install keepass-plugin-hibpofflinecheck -dv -s .'
[shim]: Calling 'D:\Chocolatey\choco.exe install keepass-plugin-hibpofflinecheck -dv -s .'
[shim]: Received error: 'System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at shim.CommandExecutor.execute(String process, String arguments, String working_directory, Boolean is_gui, Boolean wait_for_exit, Boolean requires_elevation)
   at shim.ShimProgram.Main(String[] args)'.

Unhandled Exception: System.ComponentModel.Win32Exception: The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at shim.CommandExecutor.execute(String process, String arguments, String working_directory, Boolean is_gui, Boolean wait_for_exit, Boolean requires_elevation)
   at shim.ShimProgram.Main(String[] args)
```

What is extremely uncomfortable about this problem: when **not** using `gsudo`, I am able to get a lot further with Chocolatey and the errors in that scenario make sense -- such as permission denied when trying to write to C:\Program Files paths (because the process is not running as Administrator).  So then question then becomes what is causing this mayhem?

**Running Command Prompt as Administrator is not an option** as CIFS/SMB-mapped drives are not available to Administrator (i.e. they are "user-mapped" not "system-mapped" like on Windows 7).  Which is too bad because it would act as a great way to determine if this is a gsudo problem or a Chocolatey problem or what.

My underlying suspicion is that there is a broken piece of code deep within something -- gsudo, Chocolatey, PowerShell, .NET, you name it -- that is expanding drive letters to UNC paths and returning that, rather than the drive-letter-mapped path, hence the error.

I need advice from Chocolatey developers on how to debug this, as the problem could be almost anywhere.

P.S. -- You might also find https://github.com/gerardog/gsudo/issues/263 amusing as well.

### What is Expected?

.

### How Did You Get This To Happen?

.

### System Details

* Operating System: Windows 10 22H2 (OS Build 19045.2846)
* Windows PowerShell version: your instructions do not specify what version number you want, so have them all:
```
PS C:\Windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
* Chocolatey CLI Version: 1.4.0
* Chocolatey Licensed Extension version: `choco list chocolatey.extension --local --exact` per the instructions just says 0 packages installed.
* Chocolatey License type: Whatever is free
* Terminal/Emulator: Command Prompt
 

### Installed Packages

```bash
.
```

### Output Log

```bash
.
```

**Comment by TheCakeIsNaOH** [comment]
First, it would be good to get a full output log.

But there are a couple of things to try:
- What happens when running in a PowerShell window, using the same command as in the log? 
- In an administrator command prompt, map the network drive with `net use`, then `cd` to the folder and run the install command (without gsudo)
- In a normal command prompt at your user profile (or any location on a local drive), run `choco install keepass-plugin-hibpofflinecheck -dv --source="Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck" --shimgen-log`

I personally use the `EnableLinkedConnections` registry tweak to make network drives show up under administrator level access, which should be a workaround.

**Comment by pauby** [comment]
Before we can look at this we need all of the fields of the template completed. In particular the complete reproducible steps are required.

**Comment by koitsu** [comment]
1. PowerShell (non-administrator):
 
Same problem, with the added "bonus" that `--shimgen-log` outputs no additional info ;)

```
PS C:\Users\username> Q:
PS Q:\> cd work\chocolatey-packages\keepass-plugin-hibpofflinecheck
PS Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck> choco pack
Chocolatey v1.4.0
Attempting to build package from 'keepass-plugin-hibpofflinecheck.nuspec'.
Successfully created package 'Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck\keepass-plugin-hibpofflinecheck.1.7.10.nupkg'
PS Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck> gsudo choco install keepass-plugin-hibpofflinecheck -dv -s .
The current directory is invalid.
PS Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck> gsudo choco install keepass-plugin-hibpofflinecheck -dv -s . --shimgen-log
The current directory is invalid.
PS Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck>
```

2. Command Prompt as Administrator:

_**This works!**_

```
C:\Windows\system32>net use Q: \\FILER\username XXXXXXXXXXXXX /user:username /persistent:no
The command completed successfully.

C:\Windows\System32>cd /d Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck

Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck>choco install keepass-plugin-hibpofflinecheck -dv -s .

... snipping for brevity ...

Chocolatey installed 1/1 packages.
 See the log for details (D:\Chocolatey\logs\chocolatey.log).
Sending message 'PostRunMessage' out if there are subscribers...
Exiting with 0

Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck>C:

C:\Windows\System32>net use Q: /delete
Q: was deleted successfully.
```

3. Command Prompt as user but leveraging `--source` flag:

This fails with a completely different error, almost implying that `--source` doesn't work as expected.  I tried several variations out of concern the parser was doing the wrong thing -- all failed the same way.

* `gsudo choco install keepass-plugin-hibpofflinecheck -dv --source="Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck" --shimgen-log`
* `gsudo choco install keepass-plugin-hibpofflinecheck -dv --source=Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck --shimgen-log`
* `gsudo choco install keepass-plugin-hibpofflinecheck -dv -s Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck --shimgen-log`

Original invocation:

```
C:\Users\jdc>gsudo choco install keepass-plugin-hibpofflinecheck -dv --source="Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck" --shimgen-log
[shim]: Set up Shim to run with the following parameters:
  path to executable: D:\Chocolatey\choco.exe
  working directory: C:\Users\jdc
  is gui? False
  wait for exit? True
  command (optional):
[shim]: Command line '"D:\Chocolatey\bin\choco.EXE" install keepass-plugin-hibpofflinecheck -dv --source="Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck" --shimgen-log'
[shim]: Current process '"D:\Chocolatey\bin\choco.EXE"'
[shim]: Command line after removing process ' install keepass-plugin-hibpofflinecheck -dv --source="Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck" --shimgen-log'
[shim]: Arguments after removing shimgen args - 'install keepass-plugin-hibpofflinecheck -dv --source="Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck"'
[shim]: Arguments are 'install keepass-plugin-hibpofflinecheck -dv --source="Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck"'
[shim]: Calling 'D:\Chocolatey\choco.exe install keepass-plugin-hibpofflinecheck -dv --source="Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck"'
```
With the rest from chocolatey.log:
```
2023-05-13 02:11:32,188 7328 [INFO ] - Chocolatey v1.4.0
2023-05-13 02:11:32,193 7328 [DEBUG] - Chocolatey is running on Windows v 10.0.19045.0
2023-05-13 02:11:32,195 7328 [DEBUG] - Attempting to delete file "D:/Chocolatey/choco.exe.old".
2023-05-13 02:11:32,195 7328 [DEBUG] - Attempting to delete file "D:\Chocolatey\choco.exe.old".
2023-05-13 02:11:32,199 7328 [DEBUG] - Command line: "D:\Chocolatey\choco.exe" install keepass-plugin-hibpofflinecheck -dv --source="Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck"
2023-05-13 02:11:32,199 7328 [DEBUG] - Received arguments: install keepass-plugin-hibpofflinecheck -dv --source=Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck
2023-05-13 02:11:32,230 7328 [DEBUG] - RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
2023-05-13 02:11:32,235 7328 [DEBUG] - Sending message 'PreRunMessage' out if there are subscribers...
2023-05-13 02:11:32,240 7328 [DEBUG] - [Pending] Removing all pending packages that should not be considered installed...
...
2023-05-13 02:11:32,292 7328 [DEBUG] - The source 'Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck' evaluated to a 'normal' source type
2023-05-13 02:11:32,293 7328 [DEBUG] - 
...
2023-05-13 02:11:32,302 7328 [DEBUG] - _ Chocolatey:ChocolateyInstallCommand - Normal Run Mode _
2023-05-13 02:11:32,306 7328 [INFO ] - Installing the following packages:
2023-05-13 02:11:32,306 7328 [INFO ] - keepass-plugin-hibpofflinecheck
2023-05-13 02:11:32,307 7328 [INFO ] - By installing, you accept licenses for the packages.
2023-05-13 02:11:32,352 7328 [DEBUG] - Using 'Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck'.
2023-05-13 02:11:32,353 7328 [DEBUG] - - Supports prereleases? 'True'.
2023-05-13 02:11:32,357 7328 [DEBUG] - - Is ServiceBased? 'False'.
2023-05-13 02:11:32,362 7328 [ERROR] - keepass-plugin-hibpofflinecheck not installed. The package was not found with the source(s) listed.
 Source(s): 'Q:\work\chocolatey-packages\keepass-plugin-hibpofflinecheck'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.
2023-05-13 02:11:32,368 7328 [WARN ] - 
Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (D:\Chocolatey\logs\chocolatey.log).
```

Use of `--pre` here has no relevancy, since the same command clearly works using a different invocation, so I didn't bother trying it.

So since item 2 works, where's the bug?  Chocolatey? Shimgen? gsudo? Windows?

As for EnableLinkedConnections -- I was not aware of this registry entry, thank you.  It sounds like this might revert behaviour to the Windows 7 Ultimate SP1 way, where drive mappings done in the user space (ex. when logging on) are available to elevated Administrator sessions invoked under that user.  However https://serverfault.com/a/929928 implies there may be some edge cases where this doesn't work, but I can try it if asked.

I would at least like to know where the problem actually lies so I can properly report it to the authors.  **I am not convinced this is a Chocolatey problem, FWIW, but I had to start somewhere.**

**Comment by koitsu** [comment]
Well I sure found an easy way to reproduce this problem:

```
C:\Users\jdc>Q:

Q:\>gsudo
Q:\# gsudo status
The current directory is invalid.

Q:\#
```
I do believe it's a complication with Windows 10 when simultaneously leveraging gsudo.  Now that I've read the docs on EnableLinkedConnections, this problem is starting to make more sense -- the Q: drive map is no longer available once I elevate credentials.  (In my case, UAC is "less involved" since it's set to Never Notify.)  In UNIX terminology, it's kind of like having a shell whose current working directory is /tmp/whatever and then in another shell you rm -fr /tmp/whatever (first shell has no way of knowing you just pulled $cwd out from under it), after which all subsequent cwd commands report various errors.

I'm going to try using EnableLinkedConnections and see if that helps.

**Comment by koitsu** [comment]
I can confirm that using EnableLinkedConnections solves this problem. @TheCakeIsNaOH Thank you very much for this tip!

So root cause seems to be Windows behaviour between 7 and 10, and gsudo "tickles the problem" because of what it's doing (elevating privileges from user to Administrator).

Simple reg.exe invocation for anyone who uses scripts:

```
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v EnableLinkedConnections /t REG_DWORD /d 1 /f
```
