### ISSUE TITLE
Incorrect implementation of the `RuleIdEqualityComparer.Equals` method

### ISSUE THREAD

**Issue by VasilievSerg** [chocolatey/choco#3182]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

It looks like there are 2 errors in the `RuleIdEqualityComparer.Equals` method implementation. 

[Link to the sources](https://github.com/chocolatey/choco/blob/91179e8c8ccfded978fc5c98ba0d68f89399e682/src/chocolatey/infrastructure.app/services/RuleService.cs#L105).

Code fragment:
```
public bool Equals(ImmutableRule x, ImmutableRule y)
{
    return ReferenceEquals(x, y) || x.Id.IsEqualTo(x.Id);
}
``` 

**Issues** 
1. The result of the `ReferenceEquals` call will always be `false`: the type of the `x` and `y` variables is `ImmutableRule` (readonly struct, value type). So, values will be boxed and references to newly created objects will differ.

2. In the `x.Id.IsEqualTo(x.Id)` invocation the `x.Id` expression is compared with itself. It looks like the correct invocation is `x.Id.Equals(y.Id)`.

### What is Expected?

No described flaws in the method implementations. 

### How Did You Get This To Happen?

I've checked the latest sources via the PVS-Studio analyzer.

### System Details

-

### Installed Packages

```bash
-
```

### Output Log

```bash
-
```

**Comment by AdmiringWorm** [comment]
Thank you for reporting this issue. This is indeed an oversight that we need to fix.

It is a minor issue at this moment as the only place that makes use of this `Equals` call is not meant to be used yet, but rather is a placeholder for future development that is intended.
