### ISSUE TITLE
Remove warning message about "smarter than the average bear"

### ISSUE THREAD

**Issue by tranquilcarbon** [chocolatey/choco#3186]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

When i ran choco upgrade all today, i received the following message:
`crystaldiskinfo v9.0.1 is newer than the most recent.
 You must be smarter than the average bear...`

i was initially panicked as i thought the package had been compromised and that it was a message left behind. After completing a full scan of my computer (which returned no infections) When i searched it, i discovered this was a easter egg. 

### Describe The Solution. Why is it needed?

I believe that a option to switch it off is needed, as it may cause panic to users who do not know that it is a easter egg and therefore might cause unnecessary stress to them.

### Related Issues

- issue #1700

**Comment by darksidemilk** [comment]
Can I actually request this be un-done? 
Easter eggs like this are one of my favorite things in our professional world, and if we can't have a little bit of silly in a product named "chocolatey", then just where's the fun in that? It is still a valid concern and maybe there could be an official doc page linked to the message to quell any concerns of it not being an official message rather than just removing it completely?

**Comment by ferdnyc** [comment]
I've gotta side with @tranquilcarbon on this one.

I'm all for whimsey and silliness in **all** parts of life, software included. The VLC traffic cone putting on its Santa hat is one of the highlights of my year. I'm _still_ disappointed the "[You can tune a filesystem, but you can't tune a fish.](https://unixhistory.livejournal.com/1808.html)" message from the BSD `tunefs(8)` man page never made it to Linux's `tune2fs(8)` man page. But like so many things, it's all in the execution.

And that's where this particular message had a lot of strikes against it:

1. Easter eggs should be something you can either _stumble across_, or _intentionally trigger_, **not** something that imposes itself into your normal workflow without warning. That's not an easter egg, that's a jumpscare.
2. The message has no obvious relationship to Chocolatey, so it fails as an in-joke / fanservice.
3. As a cultural reference, it's older than I am, and I am not young. (Heck, it's _almost_ as old as that "...tune a fish" message.) Who is it even _for_?

**Comment by jpluimers** [comment]
What I really miss in the message is that it does not hint at the most likely cause: that the newer version likely has been retracted.

It would be nice if in a future version enough meta-data would become available to better indicate the cause of the message.
