### ISSUE TITLE
Upgrade choco V2.0.0 deleted cup, cinst, clist, ....

### ISSUE THREAD

**Issue by alexetgus** [chocolatey/choco#3198]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

Choco has been updated to version 2.0.0
First of all, "cup" has not been updated. There was a writing problem. (I think it was because I was using "cup" and therefore making it unmodifiable because I was using it).

I then tried to reupgrade Choco v2.0.0 by forcing the installation (this version was already installed).
The installation went very well, but I lost the executables "cup", "cinst", "clist", "cuninst", ....
This is very annoying!

What's happened?

### What is Expected?

We need the "shortened" files!
These shortcuts are so practical...

### How Did You Get This To Happen?

A simple choco update was enough to destroy everything...

### System Details

* Operating System: Win 10 Pro 22H2
* Windows PowerShell version: 5.1.19041.3031
* Chocolatey CLI Version: 2.0.0
* Chocolatey Licensed Extension version:
* Chocolatey License type: Free
* Terminal/Emulator:

### Installed Packages

```bash
"choco list --local-only" doesn't even work any more!

>choco list --local-only
Chocolatey v2.0.0
Invalid argument --local-only. This argument has been removed from the list command and cannot be used.
```

### Output Log

```bash
If I give the logs, I can't post this problem.
They are too long...

Anyway, the logs don't show anything. That's the first thing I looked at.
```

### Additional Context

I'm at a loss.
Apart from installing these executables from a backup, I don't get it.
I'd like to understand!

**Comment by alexetgus** [comment]
I reinstalled version 1.4.0, which works correctly and reinstalled all my shortcuts...

`choco install chocolatey --version 1.4.0 --allow-downgrade -y`

**Comment by pauby** [comment]
Please see the [pinned issue in this repository](https://github.com/chocolatey/choco/issues/3185) and the [upgrade guide](https://docs.chocolatey.org/en-us/guides/upgrading-to-chocolatey-v2-v6) for more information.

In particular, see the sections on [shims being removed](https://docs.chocolatey.org/en-us/guides/upgrading-to-chocolatey-v2-v6#chocolatey-shortcut-shims-removed) and the [list command changing](https://docs.chocolatey.org/en-us/guides/upgrading-to-chocolatey-v2-v6#chocolatey-shortcut-shims-removed).

**Comment by pauby** [comment]
Both the options you are talking about above have been deprecated for since March 2022. If you read the upgrade documentation, it gives you options to put back the shims and the correct command for listing packages. When we remove options, we ensure we do it in a managed way ,giving you plenty of time to update what was needed. As I mentioned above, this was March 2022.

It is best practice never to upgrade software without understanding what has changed. This is particularly important for major releases where breaking changes can and are introduced. This is bes practice on Linux and Windows.
