### ISSUE TITLE
Unable to resolve dependency 'KB2919442' after V2.0.0 upgrade

### ISSUE THREAD

**Issue by Obi96Sy** [chocolatey/choco#3199]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

After the V.2.0.0 upgrade to Chocolatey, any upgrade to a package is failing because of this error:
Failures
 - duck - Unable to resolve dependency 'KB2919442': Unable to find a version of 'KB2919442' that is compatible with 'KB2919355 1.0.20160915 constraint: KB2919442 (>= 1.0.20160915)'.
 - Firefox - Unable to resolve dependency 'KB3063858'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.
 - GoogleChrome - Unable to resolve dependency 'KB3063858'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.
 - internet-download-manager - Unable to resolve dependency: Unable to find a version of 'autohotkey.portable' that is compatible with 'internet-download-manager 6.41.14 constraint: autohotkey.portable (>= 1.1.30.3)', 'msiafterburner 4.6.5.230429 constraint: autohotkey.portable (>= 1.1.30.3)'.
 - mkvtoolnix - Unable to resolve dependency 'KB3063858'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.
 - occt - Unable to resolve dependency 'KB2919442': Unable to find a version of 'KB2919442' that is compatible with 'KB2919355 1.0.20160915 constraint: KB2919442 (>= 1.0.20160915)'.
 - plexmediaserver - Unable to resolve dependency 'KB3063858'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.

### What is Expected?

For the packages to be upgraded successfully.

### How Did You Get This To Happen?

I run this command: choco upgrade all -y
then I recieve this error for all upgrades:
Unable to resolve dependency 'KB2919442': Unable to find a version of 'KB2919442' that is compatible with 'KB2919355 1.0.20160915 constraint: KB2919442 (>= 1.0.20160915)'.

### System Details

* Operating System: Windows 10 v.22H2 (OS Build 19045.3031)
* Windows PowerShell version: 5.1.19041.3031
* Chocolatey CLI Version: 2.0.0
* Chocolatey Licensed Extension version:
* Chocolatey License type: Open Source
* Terminal/Emulator:

### Installed Packages

```bash
Chocolatey v2.0.0
autohotkey.portable 2.0.2
bulkrenameutility 3.4.4
calibre 6.19.1
choco-cleaner 1.0.0
chocolatey 2.0.0
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-dotnetfx.extension 1.0.1
chocolateygui 2.0.0
chocolatey-misc-helpers.extension 0.0.4
chocolatey-windowsupdate.extension 1.0.5
cinebench 23.200.0
coretemp 1.18.0
cpu-z.install 2.6.0
discord 1.0.9006
discord.install 1.0.9006
DotNet4.5 4.5.20120822
DotNet4.6.1 4.6.1055.20170308
dotnet4.6.2 4.6.1590.20190822
dotnet4.7.2 4.7.2.20210903
dotnet-6.0-desktopruntime 6.0.16
dotnetfx 4.8.0.20220524
duck 8.5.9.39636
eac 1.6.0
Firefox 113.0.2
freac 1.1.7
freac.portable 1.1.7
GoogleChrome 113.0.5672.127
handbrake.install 1.6.1
heaven-benchmark 4.0.0.20200922
hwmonitor 1.50.0.20230303
internet-download-manager 6.41.11
iTunes 12.12.9.4
javaruntime 8.0.231
jre8 8.0.371
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
k-litecodecpackmega 17.6.0
lghub 2023.4.7679
mkvtoolnix 76.0.0
mp3tag 3.21.0
msiafterburner 4.6.5.230429
mullvad-app 2023.3.0
netfx-4.6.2 4.6.2.20210905
netfx-4.7.2 4.7.2
notepadplusplus.install 8.5.3
obs-studio.install 29.1.2
occt 12.0.5.99
pandoc 3.1.2
plexmediaserver 1.32.2.7100
python 3.11.3
python3 3.11.3
python311 3.11.3
qbittorrent 4.5.3
spacesniffer 1.3.0.2
vcredist140 14.36.32532
vcredist2005 8.0.50727.619501
vcredist2008 9.0.30729.616104
vcredist2010 10.0.40219.32503
vcredist2012 11.0.61031.20230518
vcredist2013 12.0.40660.20180427
vcredist2015 14.0.24215.20170201
vcredist2017 14.16.27033
vcredist-all 1.0.1
vlc 3.0.18
vlc.install 3.0.18
vscode 1.78.2
vscode.install 1.78.2
winrar 6.21.0
youtube-dl-gui 0.4.0
youtube-dl-gui.install 0.4.0
yubikey-manager 1.2.5
zotero 6.0.26
```

### Output Log

```bash
https://gist.github.com/Obi96Sy/9bbaac6e75b4fc760054893e0236a4ac
```

**Comment by AdmiringWorm** [comment]
Installed packages and their dependencies are more strictly enforced in Chocolatey CLI v2.0.0.
That means that if you have a missing package dependency in your locally installed packages (or a dependency that is out of range), this will prevent any upgrades from happening.

The way to get upgrade work again is to install these missing dependencies, from the look of you log file, and listed packages the dependency is missing is `KB3063858`.

Run `choco install kb3063858` to get it installed (installs and uninstalls should still work fine).

See https://docs.chocolatey.org/en-us/guides/upgrading-to-chocolatey-v2-v6#unresolved-dependency-constraint-warnings for more information about this warning and error.

**Comment by Obi96Sy** [comment]
Thanks! Installing the dependancy worked.

**Comment by Absoblogginlutely** [comment]
I have the same error message on two machines that I have access to. Attempting to choco install kb3063858 as above then states "KB3063858 v1.0.0 already installed" , although attempting to install with a force install generates "Skipping installation because update KB3063858 does not apply to this operating system (Microsoft Windows 11 Enterprise)"
Removing obs.install (which required removing obs-ndi) then allowed the rest of choco upgrade all to work successfully.

**Comment by CritLoren** [comment]
I already have KB2919442 installed but I still get this issue. I have no obs.install package

**Comment by TheCakeIsNaOH** [comment]
@CritLoren there is a documentation page here: https://docs.chocolatey.org/en-us/choco/troubleshooting/dependency-troubles

If you have further issues with dependencies I'd suggest asking on the Community Chat. https://ch0.co/community

**Comment by CritLoren** [comment]
The only useful thing on that page was --ignore-dependencies
