### ISSUE TITLE
Create a simpler Chocolatey installer EXE/MSI

### ISSUE THREAD

**Issue by LazaroOnline** [chocolatey/choco#3213]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

Installing chocolatey is a pain for the users.

### Describe The Solution. Why is it needed?

We want an installer, something the user can just double click, then he is asked to allow elevated privileges, so no need to remember to close it and reopen as admin.
And after a classic loading bar finishes, chocolatey should be installed.

In the "Download" section of Chocolatey.com, it would be great to see a huge button that says "Download" that downloads the "choco-installer.exe" instead of a list of 29 different ways to install using commands.

### Additional Context

-

### Related Issues

-

**Comment by TheCakeIsNaOH** [comment]
There is a Chocolatey CLI MSI installer in progress, the public discussion on it is here: https://github.com/chocolatey/choco/discussions/2686

**Comment by gep13** [comment]
The MSI for Chocolatey CLI is actually now available for usage.  It was recently used to allow the installation of Chocolatey CLI via WinGet: https://github.com/microsoft/winget-pkgs/pull/109065

The MSI itself can be seen as an asset on the GitHub release of Chocolatey CLI v2.0.0:

https://github.com/chocolatey/choco/releases/tag/2.0.0
