### ISSUE TITLE
unable to resolve dependencies for already installed packages

### ISSUE THREAD

**Issue by Triquetra** [chocolatey/choco#3219]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

on choco upgrade all, nothing gets upgraded. errors are thrown suggesting missing dependencies, but the dependencies are already installed

### What is Expected?

successful upgrade of packages

### How Did You Get This To Happen?

choco upgrade all

### System Details

* Operating System: Windows 11
* Windows PowerShell version: 7.3.4
* Chocolatey CLI Version: 2.0.0
* Chocolatey Licensed Extension version: n/a
* Chocolatey License type: Free
* Terminal/Emulator: Windows Terminal

### Installed Packages

```bash
Chocolatey v2.0.0
7zip 22.1.0
7zip.install 22.1.0
audacity 3.3.2
audacity-ffmpeg 2.2.2.20210809
autohotkey 1.1.36.2
autohotkey.install 1.1.36.2
autohotkey.portable 2.0.2
bleachbit 4.4.2
bleachbit.install 4.4.2
bulk-crap-uninstaller 5.6.0
ccenhancer 4.5.7
ccenhancer.install 4.5.7
ccleaner 6.12.10490
chocolatey 2.0.0
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-dotnetfx.extension 1.0.1
chocolatey-font-helpers.extension 0.0.4
chocolatey-windowsupdate.extension 1.0.5
cleanup-desktop-shortcuts.hook 0.1.0-alpha-20221103
crystaldiskinfo 9.0.1
crystaldiskinfo.portable 9.0.1
crystaldiskmark 8.0.4.99
dejavufonts 2.37.0
discord 1.0.9005
discord.install 1.0.9005
diskgenius 5.5.0.1488
DotNet3.5 3.5.20160716
DotNet4.5.2 4.5.2.20140902
dotnet4.7.1 4.7.2558.20190226
dotnet-7.0-desktopruntime 7.0.5
dotnet-desktopruntime 7.0.5
dotnetfx 4.8.0.20220524
f.lux 4.120.0
f.lux.install 4.120.0
ffmpeg 6.0.0
FiraCode 6.2.0
geforce-experience 3.27.0.112
Ghostscript 10.0.0.20230317
Ghostscript.app 10.0.0.20230317
git 2.41.0
git-credential-manager-for-windows 1.20.0
greenshot 1.2.10.6
hackfont 3.3.0
InkScape 1.2.2.20230220
irfanview 4.62.0
irfanviewplugins 4.62.0
javaruntime 8.0.231
jetbrainsmono 2.2.0
jre8 8.0.371
KB2533623 2.0.0
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
KB3063858 1.0.0
kindle 1.40.65535
lockhunter 3.4.3.20220526
msiafterburner 4.6.5.230429
nssm 2.24.101.20180116
nvidia-display-driver 535.98.0
obsidian 1.3.5
pdf24 11.12.1
powertoys 0.70.1
python 3.11.3
python3 3.11.3
python311 3.11.3
qbittorrent 4.5.3
ruby 3.1.3.1
ruby.install 3.1.3.1
sagethumbs 2.0.0.23
sdio 1.12.12.753
snappy-driver-installer-origin 1.0.558
speccy 1.32.803
teracopy 3.26.3.20190627
tortoisegit 2.14.0.1
ultrasearch 3.4.0.1
vcredist140 14.36.32532
vcredist2010 10.0.40219.32503
vcredist2015 14.0.24215.20170201
ventoy 1.0.91
vivaldi 6.0.2979.22
vivaldi.portable 6.0.2979.22
vlc 3.0.18
vlc.install 3.0.18
vscodium 1.78.2.23132
vscodium.install 1.78.2.23132
windowsrepair 4.14.0
windowsrepair.install 4.14.0
winmerge 2.16.30
zotero 6.0.26
92 packages installed.
```

### Output Log

```bash
https://gist.github.com/Triquetra/cb3db919a5f7586fd4ba07fafca8245f
```

### Additional Context

I tried to force reinstall git and KB2919442, but apparently this had no effect

**Comment by AdmiringWorm** [comment]
@Triquetra can you try running `choco install git.install --version 2.41.0`?

You mentioned you tried to reinstall the package `git`, but it is the `git.install` package that is mentioned as missing.

**Comment by Triquetra** [comment]
I tried it, but it seems the installation failed, and had no effect on the errors I'm experiencing. Here's the relevant log section: https://gist.github.com/Triquetra/af0cfc48579033bded689493735c52ae

**Comment by gep13** [comment]
Can you try:

```
choco install git.install --version 2.41.0 -n
```

Which should install the package, but skip the installation of the application, and then try your other command again.

**Comment by Triquetra** [comment]
That seemed to do the trick. Thank you @gep13!
