### ISSUE TITLE
At first, a dependency failure and after working around it, apparently no installation

### ISSUE THREAD

**Issue by epicbugs** [chocolatey/choco#322]
I discovered Chocolatey today and I must say, was quite excited to try it out but when I finally ran "choco install windows-sdk-6.1" things turned ugly.

```
 WARNING: This installer is known to close the explorer process. This means
 you may lose current work.
 If it doesn't automatically restart explorer, type 'explorer' on the
 command shell to restart it.
 Downloading 7zip.install 64 bit
   from 'http://www.7-zip.org/a/7z938-x64.msi'
 Installing 7zip.install...
 [ERROR] Running msiexec with /i "C:\Users\FINEST~1\AppData\Local\Temp\chocolate

 y\7zip.install\7zip.installInstall.msi" /quiet  was not successful. Exit code w

 as '1603' Error Message:
 .
 At C:\ProgramData\chocolatey\helpers\functions\Start-ChocolateyProcessAsAdmin.p

 s1:92 char:10
 +     throw <<<<  $errorMessage
     + CategoryInfo          : OperationStopped: ([ERROR] Running...or Message:

 .:String) [], RuntimeException
     + FullyQualifiedErrorId : [ERROR] Running msiexec with /i "C:\Users\FINEST

    ~1\AppData\Local\Temp\chocolatey\7zip.install\7zip.installInstall.msi" /qu

   iet  was not successful. Exit code was '1603' Error Message:
 .
The install of 7zip.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\7zip.install\tools\chocolatey
Install.ps1'.
 See log for details.
```

Although puzzled at first I then had an idea. I went to "Programs and Features" and uninstalled 7zip already present from previous days. 

After that, "choco install windows-sdk-6.1" at least from the outside succeeded ("The install of windows-sdk-6.1 was successful.") but I have no idea where exactly was it installed.

[Microsoft docs](https://msdn.microsoft.com/en-us/library/ms717328(v=vs.90).aspx) state that "To open the tools documentation, point to All Programs, point to Microsoft Windows SDK, point to Tools, and then click Tools Reference" but there isn't even a "Microsoft Windows SDK" item in the Start Menu. Nor is there currently any reference to Windows SDK or its standard tools neither in "Program Files" nor in "Program Files (x86)" of the machine where I ran the command.

Is this normal and expected behavior?

**Comment by ferventcoder** [comment]
Apologies you had a bad first experience. I do want to mention that both of these appear to be package issues and not issues with core chocolatey. If you want to follow up on the win sdk on the package page, that would be great. I'm the maintainer of 7zip, so I can help you with that.

**Comment by epicbugs** [comment]
You mean if I want to follow up on https://chocolatey.org/packages/windows-sdk-6.1 using Discus? Sure, why not. I'll post a message.

**Comment by epicbugs** [comment]
Done. I hope I posted enough information to get the troubleshooting process started.

**Comment by ferventcoder** [comment]
Awesome. :)

**Comment by ferventcoder** [comment]
@epicbugs I've followed up with https://github.com/ferventcoder/chocolatey-packages/issues/82

**Comment by bc3tech** [comment]
FWIW I get this while trying to update `gitextensions` via `cup`:
```
You have gitextensions v2.48.05 installed. Version 2.48.05.20150903 is available based on your source(s).

gitextensions v2.48.05.20150903 [Approved]
Loading 'chocolatey.licensed' extension.
Virus check: 0/54 scan engines flagged this assembly.
 Due to possible false positives we fail at 5 minimum positives.
 Virus scan engines indicate this file is probably safe. For details see
  https://www.virustotal.com/file/f8541f0e5f60c084778322c7d7014e3e78bc15378ad5d31c231c26229a0c9177/analysis/
Installing GitExtensions-2.48.05-Setup.msi...
ERROR: Running ["C:\WINDOWS\System32\msiexec.exe" /i "d:\users\SYSTEM\AppData\Local\Temp\chocolatey\gitextensions\2.48.0
5.20150903\GitExtensions-2.48.05-Setup.msi" /quiet /norestart] was not successful. Exit code was '1603'. See log for pos
sible error messages.
The upgrade of gitextensions was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\gitextensions\tools\chocolateyInstall.ps1'.
 See log for details.
```
this in Choco 05/31, btw.
