### ISSUE TITLE
Document resources for firewall whitelising

### ISSUE THREAD

**Issue by GreatTeacherBasshead** [chocolatey/choco#3220]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

Would be great to see a list of resources, which should be whitelisted on a firewall, in order to be able to use chocolatey in a "restricted" environment.

### Describe The Solution. Why is it needed?

Would be great to have the list of domain names specified in Chocolatey documentation.
Needed for going thru a firewall, which by default blocks all connections.

**Comment by pauby** [comment]
Thanks for raising this @GreatTeacherBasshead.

One of the questions you had was about packages.chocolatey.org and what that is being used for. I'm going to ask @gep13 to answer that.

**Comment by GreatTeacherBasshead** [comment]
Thats what I need!
Many thanks for such quick reply.
