### ISSUE TITLE
Support url substituting configuration

### ISSUE THREAD

**Issue by PMExtra** [chocolatey/choco#3235]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

We have a strict safety network environment that cannot connect to github.com directly.

So we can't use Chocolatey in most cases although we already built a NuGet mirror of community.chocolatey.org. Because most of the packages have to download the installer from GitHub.

We also have a GitHub mirror in our intranet. So I want a feature to replace the host of all requests from Chocolatey.

### Describe The Solution. Why is it needed?

Just like nixpkgs (a Linux package manager), provides an option named `substituters`.

It can replace the host of all requests.

Reference https://nixos.org/manual/nix/stable/command-ref/conf-file.html

Then we can use something like

```
substituters = https://github.com https://github.mycompany.mirrors
```

### Additional Context

It's also useful for all Chinese users because we cannot connect to GitHub smoothly, it provides an option for us to use something like https://ghproxy.com/ (which is a reverse proxy to speed up GitHub for Chinese).

**Comment by pauby** [comment]
I'm unsure what the use case is for this. Chocolatey CLI doesn't require you to connect to GitHub.

Are you asking for any package binaries that are located on GitHub to allow redirection? So if you download a package that has a binary located on GitHub, the substitute address would be used instead of https://github.com?

**Comment by PMExtra** [comment]
Yes, you're totally right. There are so many packages have to download the installers from github.com

**Comment by pauby** [comment]
There are a couple of ways to deal with that:

* Configure a proxy that would do the redirection and configure that for Chocolatey CLI.
* Do some reconfiguration in your network to redirect those requests.
* Use [Chocolatey For Business and internalize the package](https://docs.chocolatey.org/en-us/features/package-internalizer#mainContent) and host it internally.

I don't see it as Chocolatey CLI's place to do this rewriting, and there are other options above. So this isn't something we would add.

**Comment by PMExtra** [comment]
1 and 2 are not possible because of HTTPS.

I look forward to your reconsidering.

**Comment by PMExtra** [comment]
Package internalizer is a feasible solution but it's more complex to maintain.

**Comment by pauby** [comment]
Setting up an internal repository and internalizing packages is the recommended way to solve the problem with reliability of the software source not being available. I appreciate it's not the ideal solution for you, but it is the recommended solution.

**Comment by PMExtra** [comment]
It's also useful for all Chinese users (maybe also some other regions like Iran or South Korea). Because we cannot connect to GitHub smoothly, it provides an option for us to use something like https://ghproxy.com/ (which is a reverse proxy to speed up GitHub for Chinese).

**Comment by TheCakeIsNaOH** [comment]
> So we can't use Chocolatey in most cases although we already built a NuGet mirror of community.chocolatey.org.

Mirrors/proxies already can be directly used in Chocolatey CLI via adding a different source using the `choco source command`. No need to have a separate configuration/feature for this.

> There are so many packages have to download their installers from github.com

For overriding the url in an install script, there is already an issue here: https://github.com/chocolatey/choco/issues/467
Actually, that issue probably should probably be moved to the licensed issues repository.

**Comment by pauby** [comment]
There is nothing for us to do here, so I'm going to go ahead and close this, but we can reopen it if necessary.

**Comment by PMExtra** [comment]
As a reference, `git` software has a config named `insteadOf` that can rewrite the url. 

Document: 
https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf

Thanks to this mechanism, we can easily replace `github.com` with a self-hosted mirror site in our intranet:
```
git config --global url.https://github.mirrors.mycompany.tld.insteadOf https://github.com
```

I think it's really a common and general requirement and design for the software.

Therefore, I sincerely request you reconsider offering a similar design.
