### ISSUE TITLE
Cache check in get-chocolateywebfile generates false positives

### ISSUE THREAD

**Issue by lewk2** [chocolatey/choco#324]
The algorithm used in the above helper function checks that file size is unchanged in the content-length field. We use an internal nuget server and push builds from TeamCity to this, and it is not unusual that builds do not very in size - causing updates to miss.

If the function was passed some more arguments, we could verify if the URL has changed (we hold version numbers inside the URL), or if we could depend on other headers (like modification dates being greater than the file creation date of the cached file) then this could still work.

Or, if there were some global option to supress use of the cache, that would also work.

I am happy to make any changes and issue a pull request - but i'm not sure what way to go. Add dependencies on more headers? Make the original download store the original URL in a sidecar file to check if the URL moved? Store an etag value in a sidecar, to see if that changed? Implement a global option to suppress caching? Allow the PS1 function to lookup the package (given it knows the packagename) and verify if the passed URL is different to the previously downloaded URL?

All I know for sure is quite frequently builds fail to update because the MSI file size has not varied - and I guess we cannot be the only people that get hit with this.

Thanks for all the great work though!

**Comment by gep13** [comment]
@lewk2 As per this: https://github.com/chocolatey/chocolatey/issues/199 this should have been implemented by the use of the ```--force``` parameter.  Can you give this a try to see if this works for you?

**Comment by ferventcoder** [comment]
Also checksums in the package should always be different. So that should help it download.

**Comment by ferventcoder** [comment]
@lewk2 ping.

**Comment by ferventcoder** [comment]
@lewk2 I haven't heard back on this issue. I'm guessing you either were able to resolve it or you haven't received notifications. I'm going to close this for now, but if you want to continue triaging this issue, please feel free to comment and we can reopen the issue and continue.

We do have upcoming items for checksum enhancements - #112, which may be what you were looking for. Or if you want to have something added to that, feel free to comment.
