### ISSUE TITLE
Chocolatey fails to upgrade/downgrade using local source (from 2.0.0)

### ISSUE THREAD

**Issue by opusforlife2** [chocolatey/choco#3246]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

Trying to upgrade Chocolatey using the `--source=` parameter doesn't work. `choco -v` still shows `2.0.0`.

However, ChocolateyGUI shows the package version as 2.1.0.

Edit: I also tried to downgrade to 1.4.0 using `choco upgrade chocolatey --version 1.4.0 --allow-downgrade --source="'<PACKAGE SOURCE>'"`. This didn't work either.

### What is Expected?

Chocolatey should be updated to 2.1.0. `choco -v` should show `2.1.0`. (Edit: or downgrade to 1.4.0 should work.)

### How Did You Get This To Happen?

1. Have Chocolatey at version 2.0.0
2. Try to upgrade using a local source to 2.1.0. (or downgrade to 1.4.0.)
3. Check the version after the install finishes.

### System Details

* Operating System: Windows 7
* Windows PowerShell version: 5.1.14409.1018
* Chocolatey CLI Version: 2.0.0
* Terminal/Emulator: cmd

### Installed Packages

```bash
N/A
```

### Output Log

```bash
Provided to gep13 in https://github.com/chocolatey/choco/issues/3181#issuecomment-1596149833
```

### Additional Context

Please read from here for the full context: https://github.com/chocolatey/choco/issues/3181#issuecomment-1595800504

**Comment by pauby** [comment]
@opusforlife2 we don't support Windows 7. Can you reproduce this on a supported operating system such as Windows 10?

**Comment by TheCakeIsNaOH** [comment]
> And I'm not sure if running the PS installation script from the website on top of my existing installation will succeed or somehow corrupt it.

The install script now has a check if the Chocolatey install folder already exists, and if it does, it bails out. Rerunning it won't hurt anything, but it also won't actually _do_ anything.

> Meanwhile, could someone help me get out of this predicament? I want to downgrade to 1.4.0, but it isn't working, as I've mentioned above.

Theoretically, I think manually replacing `choco.exe` in `$env:ChocolateyInstall` with the `choco.exe` from inside the v1.4.0 `.nupkg` would allow you to do a force reinstall to get to a normal v1.4.0 installation. I haven't tested this, so it theoretically could break stuff. 

Another option would be to use `choco export` to get a list of your installed packages, then uninstall Chocolatey, then re-install v1.4.0 and re-install your packages with `choco install packages.config`. The downside is that this would lose any saved package parameters, and any configuration stored inside the lib folder. Additionally, there may be some packages that do not properly account for situations where an installer freaks out if the software is already installed. Although, IMHO, that is a bug with the package that should be fixed, and any of these can be re-tried with `--skip-powershell` to just install the package.

**Comment by TheCakeIsNaOH** [comment]
> How do I do this step?

Set `$env:chocolateyVersion = 1.4.0` then run the normal PowerShell installation script.
https://docs.chocolatey.org/en-us/choco/setup#installing-a-particular-version-of-chocolatey

Once Chocolatey CLI is installed, then run `choco install chocolateygui --version=1.1.3` to get the version that is compatible with Chocolatey v1.4.0. If you still have a 2.x version of Chocolatey GUI installed, that would have to be manually removed first, as the installer doesn't allow downgrades.

Then I'd suggest adding pins for both `chocolatey` and `chocolateygui`

**Comment by pauby** [comment]
I'm going to go ahead and close this, but we can reopen it if necessary.

**Comment by sintak123** [comment]
Hi, 

I am having the same issue: No downgrade is possible, wen using local source.
I tried with both, **chocolatey** and my custom build package  **Company.MyApp**, with the same result.

For the update I run the following commands: 
```
choco upgrade chocolatey -y -source $Source --cache $Cache --force --allow-downgrade
choco upgrade Company.MyApp -y -source $Source --cache $Cache --force --allow-downgrade
```
For chocolatey the console log was the following: 
```
PS C:\Users\any-user\Desktop\packages> choco upgrade chocolatey -y -source $Source --cache $Cache --force --allow-downgrade
Chocolatey v2.2.2
Upgrading the following packages:
chocolatey
By upgrading, you accept licenses for the packages.
chocolatey v2.2.2 is newer than the most recent.

Chocolatey upgraded 0/1 packages.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

System Details: 
- Windows Server 2022 Standard
- Running Choco version 2.2.2
- PowerShell version 5.1.20348.2110

Thank you for having a look

**Comment by pauby** [comment]
@sintak123 this issue is closed. Can you open a new issue and ensure you provide **all of the information requested** in the issue template?
