### ISSUE TITLE
Provide full offline chocolatey installer

### ISSUE THREAD

**Issue by superbonaci** [chocolatey/choco#3271]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

I can download any chocolatey version in .nupkg format, but that's not self-installable.
Please provide a way to completely install it offline without any internet connection.

### Describe The Solution. Why is it needed?

Described.

### Related Issues

- https://github.com/chocolatey/choco/issues/3261
- https://github.com/chocolatey/docs/issues/772
- https://github.com/chocolatey/choco/issues/3268
- https://github.com/chocolatey/docs/issues/779

**Comment by JPRuskin** [comment]
The MSI (which is now available in [releases](https://github.com/chocolatey/choco/releases/tag/2.1.0), should work fully offline. I even think I tested it with Windows 7, though that isn't currently a supported operating system.

The nupkg itself is also fully self-installable, as you put it, if you know what to do.

If you're unsure, you can download the latest [install.ps1 script](https://community.chocolatey.org/install.ps1) along with the nupkg file. Set `$env:chocolateyUseWindowsCompression = 'true'` and use the `-ChocolateyDownloadUrl $PathToNupkg` argument, and it should work fully offline.

So, overall, I'd say a fully offline Chocolatey installer is already very much available.
