### ISSUE TITLE
Choco uninstalled unrelated programs

### ISSUE THREAD

**Issue by mio-19** [chocolatey/choco#3277]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Sometimes `uninstall` command uninstalls unrelated packages. Today choco uninstalled GuitarPro (which is not installed by choco) when I am uninstalling Git.

### What is Expected?

-

### How Did You Get This To Happen?

```
choco uninstall git
Chocolatey v2.1.0
Uninstalling the following packages:
git
You are uninstalling git, which is likely a metapackage for an
 *.install/*.portable package that it installed
 (git represents discoverability).
For the question below, you have 20 seconds to make a selection.
Would you like to uninstall git.install as well?([Y]es/[N]o): y


git v2.41.0
 Skipping auto uninstaller - No registry snapshot.
 git has been successfully uninstalled.

git.install v2.41.0
 Running auto uninstaller...
 Auto uninstaller has successfully uninstalled git.install or detected previous uninstall.
 Auto uninstaller has successfully uninstalled git.install or detected previous uninstall.
 Skipping auto uninstaller - The uninstaller file no longer exists. "C:\Program Files\Git\unins000.exe"
 Auto uninstaller has successfully uninstalled git.install or detected previous uninstall.
 Auto uninstaller has successfully uninstalled git.install or detected previous uninstall.
 Auto uninstaller has successfully uninstalled git.install or detected previous uninstall.
 Auto uninstaller has successfully uninstalled git.install or detected previous uninstall.
 Auto uninstaller has successfully uninstalled git.install or detected previous uninstall.
 git.install has been successfully uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).

Chocolatey uninstalled 2/2 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

See GuitarPro uninstaller window poped out

### System Details

* Operating System: 10.0.22621.0
* Windows PowerShell version:
```

Name                           Value
----                           -----
PSVersion                      5.1.22621.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

* Chocolatey CLI Version: 2.1.0
* Chocolatey Licensed Extension version: Chocolatey v2.1.0
0 packages installed.
* Chocolatey License type: Free
* Terminal/Emulator: Terminal
 

### Installed Packages

```bash
Chocolatey v2.1.0
7zip 23.1.0
7zip.install 23.1.0
adb 34.0.1.20230514
autohotkey.portable 2.0.4
blender 3.6.1
calibre 6.23.0
choco-cleaner 1.1.1
chocolatey 2.1.0
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-windowsupdate.extension 1.0.5
dingtalk 5.1.33.13
dotnet-7.0-desktopruntime 7.0.9
elixir 1.14.4
epicgameslauncher 1.3.51
erlang 25.3.2.1
Everything 1.4.11024
FirefoxESR 102.13.0
GoogleChrome 114.0.5735.199
jetbrainstoolbox 1.28.1.15219
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
KB3063858 1.0.0
motrix 1.6.11
musescore 4.1.0.231921402
prismlauncher 7.1.0
python 3.11.4
python2 2.7.18
python3 3.11.4
python311 3.11.4
rpcs3 0.0.28-alpha15368
rufus 4.1.0
ryujinx 1.1.960
sandboxie-plus 1.9.8
sandboxie-plus.install 1.9.8
steam 2.10.91.91221129
Temurin17 17.0.7.700
Temurin17jre 17.0.7.700
Temurin20 20.0.1.900
Temurin8jre 8.372.7
universal-adb-drivers 1.0.4
vcredist140 14.36.32532
vcredist2005 8.0.50727.619501
vcredist2008 9.0.30729.616104
vcredist2010 10.0.40219.32503
vcredist2012 11.0.61031.20230518
vcredist2013 12.0.40660.20180427
vcredist2015 14.0.24215.20170201
vcredist2017 14.16.27033
vcredist-all 1.0.1
vlc 3.0.18
vlc.install 3.0.18
vscode 1.80.1
vscode.install 1.80.1
57 packages installed.
```

### Output Log

```bash
-
```

**Comment by mio-19** [comment]
Today it uninstalled git when I requested choco to uninstall dotnet

```
choco uninstall dotnet-7.0-desktopruntime
Chocolatey v2.1.0
Uninstalling the following packages:
dotnet-7.0-desktopruntime

dotnet-7.0-desktopruntime v7.0.9
 Running auto uninstaller...
 Auto uninstaller has successfully uninstalled dotnet-7.0-desktopruntime or detected previous uninstall.
 Skipping auto uninstaller - 'Microsoft .NET Runtime - 7.0.9 (x64)' appears to have been uninstalled already by other means.
 Skipping auto uninstaller - 'Microsoft Windows Desktop Runtime - 7.0.9 (x64)' appears to have been uninstalled already by other means.
 Skipping auto uninstaller - 'Microsoft .NET Host - 7.0.9 (x64)' appears to have been uninstalled already by other means.
 Skipping auto uninstaller - 'Microsoft .NET Host FX Resolver - 7.0.9 (x64)' appears to have been uninstalled already by other means.
 Auto uninstaller has successfully uninstalled dotnet-7.0-desktopruntime or detected previous uninstall.
 Auto uninstaller has successfully uninstalled dotnet-7.0-desktopruntime or detected previous uninstall.
 Skipping auto uninstaller - 'Microsoft Windows Desktop Runtime - 7.0.9 (x86)' appears to have been uninstalled already by other means.
 Skipping auto uninstaller - 'Microsoft .NET Runtime - 7.0.9 (x86)' appears to have been uninstalled already by other means.
 Skipping auto uninstaller - 'Microsoft Windows Desktop Runtime - 7.0.9 (x64)' appears to have been uninstalled already by other means.
 Skipping auto uninstaller - 'Microsoft .NET Host - 7.0.9 (x86)' appears to have been uninstalled already by other means.
 dotnet-7.0-desktopruntime has been successfully uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).

Chocolatey uninstalled 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

**Comment by mio-19** [comment]
It is possible that dotnet (x64) was uninstalled incorrectly by choco before this happened. I found out that dotnet was only left with x86 on my computer so decided to reinstall it

**Comment by mio-19** [comment]
Choco also uninstalled a number of unrelated programs on my other computer

**Comment by pauby** [comment]
@mio-19 You haven't provided the full log file in the original comment that you used to raise the issue. Without those logs we can't look at this.

**Comment by joel-schaal** [comment]
I don't know if it's exactly the same, but I too have something similar:
I have a package that is installed that way (in `ChocolateyInstall.ps1`):
```
    $packageArgs = @{
        packageName    = "$env:ChocolateyPackageName"
        fileType       = 'exe'
        url64bit       = $url
        silentArgs     = '/S'
        checksum64     = $checksum
        checksumType64 = 'sha256'
    }

    Install-ChocolateyPackage @packageArgs
```

This works fine, but as soon as a I try to uninstall it (with -x, because it has dependencies), I get the following message:
```
vivo-app v3.10.0.1296
 Running auto uninstaller...

  Did you know licensed versions of Chocolatey are 95% effective with
   Automatic Uninstaller due to licensed enhancements and Package
   Synchronizer?

For the question below, you have 30 seconds to make a selection.
Uninstall may not be silent (could not detect). Proceed?([Y]es/[[N]o]): 
```

I understand I can prevent that by using `Uninstall-ChocolateyPackage` (in a `ChocolateyUninstall.ps1`), but I'd rather understand what is so special in my installer that the AutoUninstaller was not able to detect it... (FYI, the installer is NSIS-based, is that an issue?)

**Comment by TheCakeIsNaOH** [comment]
> but I'd rather understand what is so special in my installer that the AutoUninstaller was not able to detect it...

IIRC, it needs a `QuietUninstallString` in the programs and features registry entry, so make sure the installer is creating that.

I'd suggest asking on chat if you need further help, https://ch0.co/community
Or opening a separate discussion.

**Comment by pauby** [comment]
@joel-schaal That isn't the same issue as this one. To avoid polluting this issue, can you use Chat as the @TheCakeIsNaOH suggested, or raise a [Discussion](https://github.com/chocolatey/choco/discussions)?

**Comment by mio-19** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward? This issue will be closed in 14 days if it continues to be inactive.

It is always relevant. But the issue might be hard to reproduce

**Comment by pauby** [comment]
There are insufficient logs for us to reproduce, as mentioned above.

**Comment by MySurmise** [comment]
I have the same issue. It just tried to uninstall nvm and vscode when I wanted to uninstall neovim.

**Comment by smilinger** [comment]
It is insane, today I was uninstalling node.js and use choco uninstall all to remove all that is installed by choco, then my whole visual studio is gone.

**Comment by pauby** [comment]
@smilinger If you run `choco uninstall all` Chocolatey CLI will uninstall `all` packages that it has installed. Including Visual Studio if it installed that. Chocolatey runs the _native_ uninstaller for the software that you installed.

Your comment doesn't provide any information to allow us to help you, determine what happened, or to determine if it's even an issue. For example, running `choco unistall all` has an expectation that it will uninstall all the packages. That's not a bug. That's expected behaviour.

If you have an issue to report, please raise a new issue and provide all the information requested. In the meantime, I am going to lock this issue as it has been closed for approximately 9 months.
