### ISSUE TITLE
Can't find choco.exe from CMD after upgrading Chocolatey with MSI and `/quiet /norestart`

### ISSUE THREAD

**Issue by o-l-a-v** [chocolatey/choco#3286]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Seems upgrading Chocolatey with MSI breaks Chocolatey.

Installing Chocolatey with MSI using Winget => `choco outdated` from CMD works fine.

* `winget install --silent --id Chocolatey.Chocolatey --version 2.1.0`

Upgrading Chocolatey with MSI using Winget => `choco outdated` from CMD gives `Cannot find file at '../choco.exe' (C:\ProgramData\chocolatey\choco.exe). This usually indicates a missing or moved file.`.

* `winget upgrade --silent --id Chocolatey.Chocolatey`

### What is Expected?

Chocolatey example command `choco outdated` should work just fine after upgrading Chocolatey with Winget / MSI.

#### Start fresh

Uninstall Chocolatey if present. Manually remove the directory `%ProgramData%\chocolatey` and environment variable `ChocolateyLastPathUpdate` which the MSI uninstaller leaves behind. And remove `%ProgramData%\chocolatey\bin` from the PATH environment variable.

#### Install a version of Chocolatey that can be upgraded.

```
C:\Windows\System32>winget install --silent --id Chocolatey.Chocolatey --version 2.1.0
Found Chocolatey [Chocolatey.Chocolatey] Version 2.1.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/chocolatey/choco/releases/download/2.1.0/chocolatey-2.1.0.0.msi
  ██████████████████████████████  5.84 MB / 5.84 MB
Successfully verified installer hash
Starting package install...
Successfully installed

C:\Windows\System32>
```

From Winget logs I see that `chocolatey-2.1.0.0.msi` was installed with `/quiet /norestart`.

`%ProgramData%\chocolatey` after installer is done.

![image](https://github.com/chocolatey/choco/assets/6450056/cc4e5103-95d3-48e5-9dac-9b07d39172e9)

#### Test that choco works from CMD

Open a new CMD window, to get the changes in environmental variables after the installer finished.
```
PS C:\Users\olav.birkeland> choco outdated
Chocolatey v2.1.0
2 validations performed. 1 success(es), 1 warning(s), and 0 error(s).

Validation Warnings:
 - A pending system reboot request has been detected, however, this is
   being ignored due to the current command being used 'outdated'.
   It is recommended that you reboot at your earliest convenience.

Outdated Packages
 Output is package name | current version | available version | pinned?

chocolatey|2.1.0|2.2.0|false

Chocolatey has determined 1 package(s) are outdated.
PS C:\Users\olav.birkeland>
```

#### Upgrade Chocolatey with Winget

```
C:\Windows\System32>winget upgrade --silent --id Chocolatey.Chocolatey
Found Chocolatey [Chocolatey.Chocolatey] Version 2.2.0.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/chocolatey/choco/releases/download/2.2.0/chocolatey-2.2.0.0.msi
  ██████████████████████████████  5.85 MB / 5.85 MB
Successfully verified installer hash
Starting package install...
Successfully installed

C:\Windows\System32>
```

From Winget logs I see that `chocolatey-2.2.0.0.msi` was installed with `/quiet /norestart`.

`%ProgramData%\chocolatey` after installer is done:

![image](https://github.com/chocolatey/choco/assets/6450056/f6e7950e-f31c-4622-ac0b-583e7c4f9bdd)

#### Test that choco works from CMD

Open a new CMD

```
PS C:\Users\olav.birkeland> choco outdated
Cannot find file at '../choco.exe' (C:\ProgramData\chocolatey\choco.exe). This usually indicates a missing or moved file.
PS C:\Users\olav.birkeland>
```

### System Details

* Operating System: 10.0.22621.0
* Windows PowerShell version: Not applicable.
* Chocolatey CLI Version: 2.1.0.0 to 2.2.0.0
* Chocolatey Licensed Extension version:
* Chocolatey License type:
* Terminal/Emulator: cmd.exe, powershell.exe

### Installed Packages

```bash
Not relevant.
```

### Output Log

```bash
Not relevant.
```

**Comment by pauby** [comment]
The Chocolatey CLI MSI is for install only. Upgrades are not supported.

The expectation is that you use the MSI to install Chocolatey CLI and then use Chocolatey CLI to upgrade Chocolatey CLI.

**Comment by o-l-a-v** [comment]
> 

Fair enough. But installing v2.2.0.0 over v2.1.0.0 should then either fail (exitcode != 0), or at least not break Chocolatey, don't you agree?

**Comment by pauby** [comment]
I was about to update that previous comment when you replied 😄 

I was going to say 'But those missing files doesn't seem right'.

**Comment by o-l-a-v** [comment]
Ah, yeah I agree. :) It's easy to reproduce, either with Winget or msiexec directly, so it's hopefully possible to figure out what happens.

Winget has no way to tell it that a package is not upgradable (as in a whether a newer version can be installed over an older version), as far as I know. I'll create an issue over at `winget-cli` to discuss that with them.

**Comment by pauby** [comment]
I confirm those files are missing on the upgrade from 2.1.0 to 2.2.0. The problem also appears going from 2.0.0 to 2.1.0 so this isn't new behaviour.
