### ISSUE TITLE
Questions about running the Chocolatey CLI install PowerShell code and install script 

### ISSUE THREAD

**Issue by gistya** [chocolatey/choco#3302]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Installation of Chocolatey feels like installing a virus.

First, you have me use admin privs to run an arcane command, which 99% of people aren't qualified to understand the meaning of, yet is very clearly designed to bypass some security settings on the machine, without fully explaining what this command does or why it's needed, or what kind of lasting effect it might have on the host:

```
Set-ExecutionPolicy AllSigned -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
```

Then, after that, I'm asked:

```
Do you want to run software from this untrusted publisher?
File C:\Users\newma\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall.ps1 is published by
CN="Chocolatey Software, Inc.", O="Chocolatey Software, Inc.", L=Topeka, S=Kansas, C=US and is not trusted on your
system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
```

Why are you not a trusted publisher? Why would I ever say yes to this question in a zero-trust world? 

Ideally you could update your install process to not require bypassing security measures? 

As it stands, not knowing who you are, I would never install this on my computer because it's not signed by a trusted developer. So how do I know the install package wasn't tampered with by a third party who hacked your site?

Note: I don't know that this concern is security-related, or more just a user-experience thing. There was a prior (closed) issue reporting the same thing, which seemed to have been closed with a kind of hand-wave in 2018, so I'm just letting you know this issue still exists and to provide a realistic perspective on what the impact is on folks who might want to use your software. 

### What is Expected?

The installer should work like every other installer ever made, and just work without making me agree to compromise the security of my computer. 

### How Did You Get This To Happen?

Followed the directions from your website.

### System Details

* Operating System: "11" (10.0.22621.0)
* Windows PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

* Chocolatey CLI Version: None installed yet, that's the problem
* Chocolatey Licensed Extension version: n/a
* Chocolatey License type: Individual
* Terminal/Emulator: PowerShell

### Installed Packages

```bash
n/a
```

### Output Log

```bash
n/a
```

**Comment by pauby** [comment]
> First, you have me use admin privs to run an arcane command, which 99% of people aren't qualified to understand the meaning of, 

PowerShell has been around for 16 years now, so I wouldn't call PowerShell commands 'arcane'. The PowerShell command to install Chocolatey CLI has also been around as long as I can remember.

Administrator privileges are required as the installation folder is locked down. To install software on Windows you will need Administrator privileges to use Chocolatey CLI to install, upgrade and uninstall packages. So it makes sense.

I would also dispute your statistic and suggest it's an opinion. But I do agree that if you don't understand what you're being asked to run, don't run it, and we put a large note on the [installation page](https://chocolatey.org/install) to that affect:

![image](https://github.com/chocolatey/choco/assets/12760779/f384ef7b-2fd2-46d1-b08a-1523f9e1cbfb)

> without fully explaining what this command does or why it's needed, or what kind of lasting effect it might have on the host

As I mentioned above, if you do not know what the script is doing or do not want to run it, then you shouldn't do that. We provide a bit more help around that on the [installation page](https://chocolatey.org/install):

![image](https://github.com/chocolatey/choco/assets/12760779/2ea51b88-70d8-496c-8af4-b2b970e01a5c)

There are [many other ways to install Chocolatey CLI](https://docs.chocolatey.org/en-us/choco/setup#more-install-options), which we highlight on the installation page:

![image](https://github.com/chocolatey/choco/assets/12760779/d502a492-4c4c-4fa4-84e3-a53b807991b1)

The 'Read the Installation Docs' button takes you to [this page](https://docs.chocolatey.org/en-us/choco/setup#more-install-options).

> Why would I ever say yes to this question in a zero-trust world?

Unless you know what you are doing and the implications of those options you show, you shouldn't. For _any_ code, script, or program you run. This isn't limited to the installation of Chocolatey CLI.

The [Chocolatey CLI install script is signed](https://community.chocolatey.org/install.ps1). Any unauthorized changes to the script will break the signing. We also have a full page on all aspects of [Security](https://docs.chocolatey.org/en-us/information/security) that might help.

Again, there are [many other installation options available](https://docs.chocolatey.org/en-us/choco/setup#more-install-options).

> Ideally you could update your install process to not require bypassing security measures?

The PowerShell environment is complex and if we left out changing the execution policy for the process the scripts run under, there would be many more support requests from people who could not install Chocolatey CLI from the installation script. By default, PowerShell does not allow the running of scripts.

**Being very clear, the execution policy is NOT changed at the User or the System level, but ONLY for the process that runs the installation script.**

I know I've pointed this out above, but I wanted to highlight again that we talk about the execution policy on the [installation page](https://chocolatey.org/install):

![image](https://github.com/chocolatey/choco/assets/12760779/c15be2a0-2722-459b-967d-62319f1a1e01)

> As it stands, not knowing who you are, I would never install this on my computer because it's not signed by a trusted developer.

Without being flippant, if you do not know who Chocolatey Software is, or what Chocolatey CLI is, then why are you running the code to install it?

As I mentioned above, and I know I'm repeating myself, if you do not understand the code or trust what you are running, do not run it. That is the case for _any_ code _anywhere_. [There are many other ways to install Chocolatey CLI](https://docs.chocolatey.org/en-us/choco/setup#more-install-options).

Also remember that the [Chocolatey CLI install script is signed](https://community.chocolatey.org/install.ps1), as I mentioned above. We also have a full page on all aspects of [Security](https://docs.chocolatey.org/en-us/information/security) that might help.

> I'm just letting you know this issue still exists and to provide a realistic perspective on what the impact is on folks who might want to use your software.

We appreciate you raising this issue again.

The vast majority of people installing Chocolatey CLI use one of the methods [that we make available](https://docs.chocolatey.org/en-us/choco/setup#more-install-options). Some of those use the installation script in one way or another, either directly from the Chocolatey Community Repository or internally within an organization. The majority of people are happy with this installation method that has been in place as long as I can remember.

We look to provide as many ways as we can for the community and customers to install Chocolatey CLI and our other products. To that end, we recently created an [MSI](https://docs.chocolatey.org/en-us/choco/setup#install-using-the-msi) allowing direct installation or installation using [WinGet](https://github.com/microsoft/winget-pkgs/tree/master/manifests/c/Chocolatey/Chocolatey) (which reminds me that I need to add the WinGet installation method to our docs).

On the topic of appreciating the issue, I _personally_, and I would suggest the team as a whole, don't appreciate comments such as:

> Installation of Chocolatey feels like installing a virus.
> which seemed to have been closed with a kind of hand-wave in 2018

Both of them are loaded comments that frustrate, annoy and irritate people. They don't add anything to this issue and are not necessary. If we were 'hand waving' responses, I wouldn't have spent the best part of an hour writing and rewriting this reply to ensure I'm answering your questions and not coming across as 'frustrated, annoyed and irritated'. I hope I've been successful in that.

Before responding, or raising future issues, please read our [Code Of Conduct](https://github.com/chocolatey/.github/blob/main/CODE_OF_CONDUCT.md).
