### ISSUE TITLE
Chocolatey Package Upgrade causes inconsistency state in terminating and upgrading running apps

### ISSUE THREAD

**Issue by WindyNova** [chocolatey/choco#3308]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Hi guys, When i'm trying to upgrade running apps like syncthing, choco couldnt terminate the app and it spits ACCESS DENIED error even though I always run choco as ADMINISTRATOR, whats more, it still count the upgrade as a success and update the manifest, even if upgrade is not success. Making upgrade unavailable until the next version of that app rolling out.

### What is Expected?

running apps terminated and do the upgrade successfully, if failed, dont update manifest

### How Did You Get This To Happen?

just run choco upgrade all

### System Details

* Operating System: Windows 10 19045.3324
* Windows PowerShell version: PS 7.3.6
* Chocolatey CLI Version: 
* Chocolatey Licensed Extension version:
* Chocolatey License type: 
* Terminal/Emulator: Windows Terminal

### Installed Packages

```bash
syncthing
```

### Output Log

```bash
You have syncthing v1.23.6 installed. Version 1.23.7 is available based on your source(s).
WARNING: Syncthing process is running. Shutting it down gracefully.
unexpected HTTP status returned: 403 Forbidden
CSRF Error
Progress: Downloading syncthing 1.23.7... 100%

syncthing v1.23.7 [Approved]
syncthing package files upgrade completed. Performing other installation steps.
Extracting 64-bit C:\ProgramData\chocolatey\lib\syncthing\tools\syncthing-windows-amd64-v1.23.7.zip to C:\ProgramData\chocolatey\lib\syncthing\tools...
C:\ProgramData\chocolatey\lib\syncthing\tools
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 Åtkomst till sökvägen syncthing.exe nekas.
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 Åtkomst till sökvägen syncthing.exe nekas.
Maximum tries of 3 reached. Throwing error.
Attempted to remove 'C:\ProgramData\chocolatey\lib-bkp\syncthing' but had an error::
 Åtkomst till sökvägen syncthing.exe nekas.
 The upgrade of syncthing was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\syncthing\tools'
```

**Comment by pauby** [comment]
There are many issues raised about this in the past, and they have all been down to something holding the files in that folder, open. In all the cases I can think of, it's been anti-virus.

**Comment by WindyNova** [comment]
> There are many issues raised about this in the past, and they have all been down to something holding the files in that folder, open. In all the cases I can think of, it's been anti-virus.

No 3rd party antivirus installed, i do make syncthing run as service under NETWORK SERVICE account, but doesn't choco have the admin rights to terminate the process and continue the upgrade?

**Comment by pauby** [comment]
> No 3rd party antivirus installed,

The issue has been seen with third-party and built-in AV.

> i do make syncthing run as service under NETWORK SERVICE account, but doesn't choco have the admin rights to terminate the process and continue the upgrade?

The issue is here:

```
You have syncthing v1.23.6 installed. Version 1.23.7 is available based on your source(s).
WARNING: Syncthing process is running. Shutting it down gracefully.
unexpected HTTP status returned: 403 Forbidden
CSRF Error
```

The service is not being shut down correctly.

This isn't a Chocolatey CLI issue. I'd inspect why the service isn't shutting down correctly. [This is the command that is run](https://github.com/pauby/ChocoPackages/blob/master/automatic/syncthing/tools/chocolateyBeforeModify.ps1#L6). It could be because of the user you are running it as and that the Administrator user doesn't have permission to do so. My suggestion would be to run the command highlighted in an elevated session.

Note that I'm the maintainer of the `syncthing` package.

As this is not a Chocolatey CLI issue, I'm going to go ahead and close this, but we can always reopen it again if necessary.

**Comment by WindyNova** [comment]
> > No 3rd party antivirus installed,
> 
> The issue has been seen with third-party and built-in AV.
> 
> > i do make syncthing run as service under NETWORK SERVICE account, but doesn't choco have the admin rights to terminate the process and continue the upgrade?
> 
> The issue is here:
> 
> ```
> You have syncthing v1.23.6 installed. Version 1.23.7 is available based on your source(s).
> WARNING: Syncthing process is running. Shutting it down gracefully.
> unexpected HTTP status returned: 403 Forbidden
> CSRF Error
> ```
> 
> The service is not being shut down correctly.
> 
> This isn't a Chocolatey CLI issue. I'd inspect why the service isn't shutting down correctly. [This is the command that is run](https://github.com/pauby/ChocoPackages/blob/master/automatic/syncthing/tools/chocolateyBeforeModify.ps1#L6). It could be because of the user you are running it as and that the Administrator user doesn't have permission to do so. My suggestion would be to run the command highlighted in an elevated session.
> 
> Note that I'm the maintainer of the `syncthing` package.
> 
> As this is not a Chocolatey CLI issue, I'm going to go ahead and close this, but we can always reopen it again if necessary.

OK,thank you for your reply, but how about choco still mark it as a successful upgrade even though failed

**Comment by pauby** [comment]
> but how about choco still mark it as a successful upgrade even though failed

Chocolatey CLI won't treat a failure of any failures from the `chocolateyBeforeModify.ps1` script as a package installation failure.
