### ISSUE TITLE
Remember software installation location

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#3315]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

Currently, Chocolatey CLI does not remember/save the software installation location found during package installation, it just prints the location out to the screen after package install/upgrade, e.g. `Software installed to 'C:\ProgramData\chocolatey\lib\Wget\tools'`

There are a number of issues here and for ChocolateyGUI that would need this information, but it is not currently saved. 

### Describe The Solution. Why is it needed?

Save the software installation path, if the package has one, into a file in `.chocolatey`, so it can be read later. 

### Additional Context

This is intended to be the backend/infrastructure issue, and then the linked issues would be unblocked once this added. 

### Related Issues

- Issue #1901
- Issue #681
- Issue  https://github.com/chocolatey/ChocolateyGUI/issues/597
- Issue https://github.com/chocolatey/ChocolateyGUI/issues/278

**Comment by pauby** [comment]
What needs to be taken into account here is when Chocolatey CLI determines the installation location incorrectly, what is done with the information saved when it could be incorrect, and how it is made clear to the user that the installation location may be incorrect.
