### ISSUE TITLE
Can chocolatey successfully update running applications?

### ISSUE THREAD

**Issue by ayyyiieneheuihues** [chocolatey/choco#3326]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

I haven't seen anything yet as an update to qbittorrent hasn't been released yet while I've had chocolatey, update all packages at startup, and qbittorent opening at startup setup.

### What is Expected?

The update should go through successfully.

### How Did You Get This To Happen?

Nothing yet.

### System Details

* Operating System: Windows 11
* Terminal/Emulator: Powershell

Sorry, I'm not at my computer right now so I can't provide full details.

### Installed Packages

```bash
qbittorrent
Update all packages at startup
```

### Output Log

```bash
N/A
```

### Additional Context

Hi,

I wanted to know whether chocolatey will successfully update a package while it is running. I have qbittorrent installed through chocolatey. I previously only used qbittorrent whenever I needed to download something but now I am running it all the time when my computer is on (I have the setting to launch qbittorrent on startup). I also have the package installed to automatically update all my chocolatey packages on startup. My question is whether chocolatey will be able to update qbittorrent while it is running. From what I recall when I was using Linux this was possible and you just wouldn't see the program being updated until the next time you ran the program. Anyways, I appreciate anyone that can help me.

**Comment by ayyyiieneheuihues** [comment]
I believe this issue should have a "Question" label and not a "Bug" label.

**Comment by steviecoaster** [comment]
This would be better asked on our [Discord](https://ch0.co/community) but I'll answer here for posterity.

It's up to the package maintainer as to what happens. Some applications can updated while they are running, others need closed. The maintainer _should_ have tested these scenarios and accounted for the correct action to take inside the PowerShell code. 

Some packages will prompt you that it needs to close a software, others won't. You'll just have to try it for yourself, and use the contact maintainers link or raise an issue on the source repository for the package requesting changes.
