### ISSUE TITLE
Use certificates from windows built in store

### ISSUE THREAD

**Issue by shooln** [chocolatey/choco#3330]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

Right now certificates have to be exported to disk and then used in chocolatey via the -cert flag. It would be ideal and more secure to pull them directly from the windows certificate store.

### Describe The Solution. Why is it needed?

implement a new flag and method to pull from the windows Machine / user store based on privilege of the chocolatey app

**Comment by steviecoaster** [comment]
related to #1737

**Comment by pauby** [comment]
I'm going to close this as a duplicate of #1737.
