### ISSUE TITLE
kb2919355 error

### ISSUE THREAD

**Issue by PohPunkt** [chocolatey/choco#3339]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

![image](https://github.com/chocolatey/choco/assets/95185796/bd9212d6-62e6-4b04-9c77-f390bed92387)

### What is Expected?

i have this error while install tools for native modules

 - visualstudio2019-workload-vctools - Unable to resolve dependency 'kb2919355': Unable to find a version of 'kb2919355' that is compatible with 'dotnetfx 4.7.2 constraint: kb2919355 (>= 1.0.20160915)', 'KB2999226 1.0.20161023 constraint: kb2919355 (>= 1.0.20160915)', 'vcredist140 14.0.23026 constraint: kb2919355 (>= 1.0.20160915)', 'visualstudio2019buildtools 16.0.0 constraint: kb2919355 (>= 1.0.20160915)'.

how to fix this?

### How Did You Get This To Happen?

1. run node installer
2. Tick Automatically install the neccessary tools. Note that this will also install Chocolatey. The script will pop-up in a new window after the installation completes.

### System Details

* Operating System: newest win 10
* Chocolatey CLI Version: 2.2.2

### Installed Packages

```bash
Chocolatey v2.2.2
chocolatey 2.2.2
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-windowsupdate.extension 1.0.5
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
python 3.11.5
python3 3.11.5
vcredist140 14.36.32532
vcredist2015 14.0.24215.20170201
```

### Output Log

```bash
https://gist.github.com/PohPunkt/78d48f4837569e588e9950e16d251a06
```

**Comment by pauby** [comment]
Please see the [dependency page on the docs](https://docs.chocolatey.org/en-us/choco/troubleshooting/dependency-troubles) that was created to help with this.
