### ISSUE TITLE
Dependecy Issue installing the Chocolatey package manager

### ISSUE THREAD

**Issue by nethbotheju** [chocolatey/choco#3349]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

![aaa](https://github.com/chocolatey/choco/assets/131664638/159cb88b-770a-4084-9033-727d6f03dd87)

### What is Expected?

Successful installation of additional tools for Node.js

### How Did You Get This To Happen?

Downloaded and installed Node.js v20.9.0 installer for Windows users. I clicked the Additional Node.js tools (called Tools for Native Modules on newer versions) when prompted.

### System Details

* Operating System: Windows 10
* Terminal/Emulator: Powershell

### Installed Packages

```bash
Chocolatey v2.2.2
Upgrading the following packages:
python;visualstudio2019-workload-vctools
```

### Output Log

```bash
By upgrading, you accept licenses for the packages.
python v3.12.0 is the latest version available based on your source(s).
visualstudio2019-workload-vctools is not installed. Installing...
[NuGet] One or more unresolved package dependency constraints detected in the Chocolatey lib folder. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'python 3.12.0 constraint: python3 (= 3.12.0)'
Unable to resolve dependency 'kb2919355': Unable to find a version of 'kb2919355' that is compatible with 'dotnetfx 4.7.2 constraint: kb2919355 (>= 1.0.20160915)', 'KB2999226 1.0.20161023 constraint: kb2919355 (>= 1.0.20160915)', 'vcredist140 14.0.23026 constraint: kb2919355 (>= 1.0.20160915)', 'visualstudio2019buildtools 16.0.0 constraint: kb2919355 (>= 1.0.20160915)'.

Chocolatey upgraded 0/2 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - visualstudio2019-workload-vctools - Unable to resolve dependency 'kb2919355': Unable to find a version of 'kb2919355' that is compatible with 'dotnetfx 4.7.2 constraint: kb2919355 (>= 1.0.20160915)', 'KB2999226 1.0.20161023 constraint: kb2919355 (>= 1.0.20160915)', 'vcredist140 14.0.23026 constraint: kb2919355 (>= 1.0.20160915)', 'visualstudio2019buildtools 16.0.0 constraint: kb2919355 (>= 1.0.20160915)'.
```

**Comment by pauby** [comment]
There is a page covering this in the [documentation](https://docs.chocolatey.org/en-us/choco/troubleshooting/dependency-troubles).
