### ISSUE TITLE
ERROR Installing Anything: Requested registry access is not allowed.

### ISSUE THREAD

**Issue by michaelsearcy** [chocolatey/choco#335]
[Gist of my -dv log](https://gist.github.com/michaelsearcy/859893a90ac79a0394da)
Clean install using the code described on the GitHub page for command line installation.

    @powershell -NoProfile -ExecutionPolicy unrestricted -Command "(iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))) >$null 2>&1" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin

Chocolatey is in the PATH and I am admin. I have no idea what this means. 
The full error:

    notepadplusplus v6.7.9 
    notepadplusplus not installed. An error occurred during installation: Requested registry access is not allowed.

I have 0 issues installing the GUI way.

**Comment by ferventcoder** [comment]
@michaelsearcy Did you buy chance not have .NET Framework 4.0 installed before you ran the installer?

From what I'm finding it may be related to the install of the framework, based on setting a permissions key in the registry and may require a reboot.

Some of the references will have you apply some changes, I think it may be simpler to attempt to reboot first and see if it fixes the issues.

References:
* http://forums.yessoftware.com/posts.php?post_id=67135
* http://geekswithblogs.net/TimH/archive/2005/10/05/56029.aspx
* https://support.microsoft.com/en-us/kb/842795

**Comment by ferventcoder** [comment]
The last one mentioned I need to set things up so that choco always runs in admin mode - http://stackoverflow.com/questions/562350/requested-registry-access-is-not-allowed 

I don't want to go that route if I don't have to.

**Comment by ferventcoder** [comment]
I don't want to go the route of requiring admin if I don't have to - we have folks use choco without admin access and this would remove their ability to do so.

**Comment by ferventcoder** [comment]
Quick question, you are admin - are you running an administrative command prompt? Usually choco can detect that (in this case choco thinks all is good) and warn the user, but it's not a 100% detection.

**Comment by michaelsearcy** [comment]
![image](https://cloud.githubusercontent.com/assets/697694/8234670/54ad5010-15ab-11e5-8a5f-43073ab325f5.png)
.Net Framework 4.5 installed. Do I need to also have the older 4.0 (is that even possible).
I have rebooted my machine before opening this issue. 
I have tried 1st reference. Rebooting now.

**Comment by michaelsearcy** [comment]
Admin: Yes

**Comment by ferventcoder** [comment]
4.5 is fine

**Comment by ferventcoder** [comment]
Hmm... Is there a chance this is x64 only? No syswow64 support for 32 bit programs? Just trying to determine if a key is missing...or 32 bit only?

**Comment by michaelsearcy** [comment]
You lost me. How can I answer your last question?

**Comment by ferventcoder** [comment]
Sorry, was asking if this was a 64bit system? 
Then I was asking if you had a 64bit system with no 32-bit app support (this would not be common, most folks have amd64 and not itanium64).

**Comment by ferventcoder** [comment]
Tell me if you have the following [keys](https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/services/RegistryService.cs#L52-L64):

```
HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall
HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall
HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall
HKCU\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall
```

**Comment by ferventcoder** [comment]
Could be that last key is the issue

**Comment by ferventcoder** [comment]
We also attempt to open with read permissions - `RegistryKeyPermissionCheck.ReadSubTree, RegistryRights.ReadKey)`

**Comment by michaelsearcy** [comment]
HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall  - yes in the Uninstall folder is say Name (Default) Type REG_SZ, Data (value not set) there are hundreds of subfolders. None for chocolatey (but many with a GUID or w/e)
HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall - yes in the Uninstall folder is say Name (Default) Type REG_SZ, Data (value not set) there are hundreds of subfolders. None for chocolatey (but many with a GUID or w/e)
HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall yes in the Uninstall folder is say Name (Default) Type REG_SZ, Data (value not set) there are a dozen  subfolders. None for chocolatey (but many with a GUID or w/e)
HKCU\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall - No I get to Microsoft and there is no Windows folder after that.
![image](https://cloud.githubusercontent.com/assets/697694/8247022/066fcbb4-1617-11e5-8751-9030031354c6.png)

**Comment by ferventcoder** [comment]
I'm guessing that is likely the issue. I'm going to have you try something for me.

**Comment by ferventcoder** [comment]
Actually I don't have that key either. Hmmm

**Comment by ferventcoder** [comment]
If you were to create the key structure, I'm guessing you are still going to run into this error.

**Comment by michaelsearcy** [comment]
Why me? I want to use chocolatey. What can I do? What did I do wrong? I'm thinking it must be something else if you also don't have the key.

**Comment by ferventcoder** [comment]
I'm leaning towards permission on a particular key in the registry in the uninstaller group that you don't have access to. I'll work on a way to report if the key is not accessible, but in the meantime you should take a look at all of the uninstaller keys and grab the permissions for evaluation.

I believe setacl will iterate through and tell you the permissions on the registry keys so you can quickly gather all of those. https://helgeklein.com/setacl/

**Comment by michaelsearcy** [comment]
OK I am totally lost. I downloaded and unzipped this SetACL tool what do i do now?

**Comment by ferventcoder** [comment]
@michaelsearcy apologies, I don't know the exact command to inspect the values. You are looking for viewing or auditing the keys and looking for an anomaly. Not the most fun thing in the world to do.

**Comment by michaelsearcy** [comment]
Um...
https://gist.github.com/michaelsearcy/7eb11e38f96f00bc45e3
maybe ?

**Comment by ferventcoder** [comment]
It is likely a subkey. I will have a build out in a bit for you to try

**Comment by ferventcoder** [comment]
Pull down 0.9.9.7 and see if it warns on the error and continues.

**Comment by ferventcoder** [comment]
Then we'll know if that fixes the issue you are running into and we can close this out.

**Comment by ferventcoder** [comment]
@michaelsearcy ping - when you get a chance :)

**Comment by michaelsearcy** [comment]
OK So when you say pull down, I am assuming you mean reinstal with command line like I did @ first or downloading the source and doing my own build. I'm sorry I have limited github exposure.

**Comment by ferventcoder** [comment]
@michaelsearcy sorry, I meant reinstall from the command line.

**Comment by michaelsearcy** [comment]
Yay! 

![image](https://cloud.githubusercontent.com/assets/697694/8288199/a1573d88-18e2-11e5-8fa9-bd456d4eedf0.png)

**Comment by ferventcoder** [comment]
Looks like you are moving forward now. :)

**Comment by ferventcoder** [comment]
Fixed as part of #337

**Comment by michaelsearcy** [comment]
Thanks for working so quick on this btw

**Comment by ferventcoder** [comment]
No worries - thanks for working with me to resolve the issue! :)
