### ISSUE TITLE
Detecting elevated command shell works for PowerShell 7, but not for PowerShell 5 and CMD

### ISSUE THREAD

**Issue by agabrys** [chocolatey/choco#3363]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

I encountered a very strange issue. When I run PowerShell 5 (default version on Windows) or Command Prompt as administrator, chocolatey says I did not run them as admin. When I do the same in PowerShell 7, everything works as it should.

PowerShell 5.X
![PowerShell 5.X](https://github.com/chocolatey/choco/assets/10604335/2a46d8e2-3f05-42c5-bb0a-f569ce7c1bf4)

Command Prompt
![Command Prompt](https://github.com/chocolatey/choco/assets/10604335/ed5cf37f-3680-4a86-8df0-ea2502557ef1)

PowerShell 7.X

![PowerShell 7.X](https://github.com/chocolatey/choco/assets/10604335/61f4ff08-e81b-4f7a-9988-150704af8af6)

### What is Expected?

Every shell run as administrator should be detected as an elevated command shell by chocolatey.

### How Did You Get This To Happen?

Prerequsites:

- chocolatey v2.2.2 package is installed
- powershell-core 7.4.0 package is installed

Steps:

1. Open PowerShell 5.X as administrator and execute command to upgrade all packages
    ```
    choco upgrade all -y -i
    ```
    it fails with a message
    > Chocolatey v2.2.2
    > Chocolatey detected you are not running from an elevated command shell (cmd/powershell).
    >
    > You may experience errors - many functions/packages
    > require admin rights. Only advanced users should run choco w/out an
    > elevated shell. When you open the command shell, you should ensure
    > that you do so with "Run as Administrator" selected. If you are
    > attempting to use Chocolatey in a non-administrator setting, you
    > must select a different location other than the default install
    > location. See
    > https://docs.chocolatey.org/en-us/choco/setup#non-administrative-install
    > for details.
    >
    > For the question below, you have 20 seconds to make a selection.
1. Open Command Prompt as administrator and execute command to upgrade all packages
    ```
    choco upgrade all -y -i
    ```
    it fails with a message
    > Chocolatey v2.2.2
    > Chocolatey detected you are not running from an elevated command shell (cmd/powershell).
    >
    > You may experience errors - many functions/packages
    > require admin rights. Only advanced users should run choco w/out an
    > elevated shell. When you open the command shell, you should ensure
    > that you do so with "Run as Administrator" selected. If you are
    > attempting to use Chocolatey in a non-administrator setting, you
    > must select a different location other than the default install
    > location. See
    > https://docs.chocolatey.org/en-us/choco/setup#non-administrative-install
    > for details.
    >
    > For the question below, you have 20 seconds to make a selection.
1. Open PowerShell 7.X as administrator and execute command to upgrade all packages
    ```
    choco upgrade all -y -i
    ```
    it works
    > Chocolatey v2.2.2
    > Upgrading the following packages:
    > all
    > By upgrading, you accept licenses for the packages.
    > [...]

### System Details

* Operating System: 10.0.22621.0
* Windows PowerShell versions:
  * 7.4.0
  * 5.1
* Chocolatey CLI Version: 2.2.2
* Chocolatey Licensed Extension version: N/A
* Chocolatey License type: Free

### Installed Packages

```bash
7zip.install 23.1.0
base64 1.0.0
chocolatey 2.2.2
chocolatey-core.extension 1.4.0
cloudfoundry-cli 8.7.5
dive 0.11.0
gardenlogin 0.4.0
gawk 5.1.0
git.install 2.43.0
golang 1.21.4
grep 3.7.0
jq 1.7.0
keepass.portable 2.55.0
kubectx 0.9.5
kubens 0.9.5
kubernetes-cli 1.28.2
kubernetes-helm 3.13.1
licecap 1.28.0
make 4.4.1
msys2 20231026.0.0
powershell-core 7.4.0
tortoisegit 2.15.0
yq 4.33.3
```

### Output Log

PowerShell 5.X:
https://gist.github.com/agabrys/f01bfd8b3a3d3ba0c10ef4fc87b014e3

PowerShell 7.X:
https://gist.github.com/agabrys/38ebfa3065a275fa9d7adfc9438e67e6

### Additional Context

I tried to reinstall chocolatey and it did not help. I have a feeling that PowerShell 7.X blocked some files.

**Comment by agabrys** [comment]
It is currently working as expected, though I'm not entirely sure why. It was functioning correctly, then I encountered this strange issue, and now it's working again. I shut down my computer every day, so perhaps that action resolved the problem."

**Comment by corbob** [comment]
Thank you for the update @agabrys. I have briefly looked through the logs, and I too am at a loss for what could have caused it (other than maybe you thought you were elevated but weren't actually, but that feels really odd for seeing it in multiple shells).

Should it happen again, one troubleshooting step might be to check the tokens to determine if you're administrator. You can do that with this snippet from [Sean Wheeler's profile](https://github.com/sdwheeler/tools-by-sean/blob/main/profile/scripts/CurrentUserAllHosts.ps1#L50-L52):
```powershell
$identity = [Security.Principal.WindowsIdentity]::GetCurrent()
$principal = [Security.Principal.WindowsPrincipal] $identity
$principal.IsInRole([Security.Principal.WindowsBuiltInRole] 'Administrator')
```
