### ISSUE TITLE
The choco always prompts for credentials

### ISSUE THREAD

**Issue by Drllap** [chocolatey/choco#3399]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

choco always prompts for credentials. This is something I have never seen before today:

 choco outdated
yields:
```
Chocolatey v2.2.2
Outdated Packages
 Output is package name | current version | available version | pinned?

Invalid credentials specified.
Please provide credentials for: https://chocolatey.org/api/v2/
User name: Password:
```

### What is Expected?

Choco used to just list outdated packages

### How Did You Get This To Happen?

No idea, the behaviour had just changed this morning

### System Details

* Operating System: Windows 10.0.19044.0
* Windows PowerShell version:
echo $PSVersionTable
```
Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
* Chocolatey CLI Version: 2.2.2
* Chocolatey Licensed Extension version: None
* Chocolatey License type: ?
* Terminal/Emulator: WezTerm, Alacritty, Windows Terminal

### Installed Packages

```bash
choco list:

7zip 23.1.0
7zip.install 23.1.0
alacritty 0.13.1
alacritty.install 0.13.1
autohotkey 1.1.37.1
autohotkey.install 1.1.37.1
bat 0.24.0
bottom 0.9.6
chocolatey 2.2.2
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-dotnetfx.extension 1.0.1
chocolatey-visualstudio.extension 1.11.1
chocolatey-windowsupdate.extension 1.0.5
clumsy 0.2.0
cmake 3.28.3
cmake.install 3.28.3
com0com 3.0.0
cports 2.77.0
curl 8.6.0
dbeaver 23.3.4
dependencies 1.11.1
docker-desktop 4.27.2
dotnet-6.0-desktopruntime 6.0.27
dotnet-7.0-desktopruntime 7.0.15
dotnet-8.0-desktopruntime 8.0.1
dotnet-desktopruntime 8.0.1
dotnetfx 4.8.0.20220524
doxygen.install 1.10.0
drawio 23.0.2
fd 9.0.0
ffmpeg 6.1.1
flatc 1.12.0
fzf 0.46.1
gh 2.43.1
git 2.43.0
git.install 2.43.0
gpg4win 4.3.0
gsudo 2.4.2
hxd 2.5.0
jq 1.7.1
KB2533623 2.0.0
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
KB3063858 1.0.0
less 643.0.0
lf 0.26.0
llvm 17.0.6
microsoft-windows-terminal 1.19.10302
miniconda3 4.12.0
mobaxterm 23.6.0
neovide 0.12.1
neovide.install 0.12.1
neovim 0.9.5
netcat 1.12.0
ninja 1.11.1
notepadplusplus 8.6.2
notepadplusplus.install 8.6.2
nushell 0.90.1
nushell.install 0.90.1
oh-my-posh 19.8.3
openvpn 2.6.8.1
pgadmin4 8.2.0
powertoys 0.78.0
procexp 17.5.0.20231021
putty 0.80.0
putty.portable 0.80.0
qbittorrent 4.6.3
rufus 4.4.0
rustup.install 1.25.1
screentogif 2.39.0.20231002
screentogif.portable 2.39.0.20231002
slack 4.36.140
spotify 1.2.30.1135
spotify-tui 0.25.0
sublimemerge 0.0.2083
sublimetext3 3.2.2
sumatrapdf 3.5.2
sumatrapdf.install 3.5.2
sysinternals 2024.2.7
tortoisegit 2.15.0
tree 1.5.2.2
treesizefree 4.7.1.1
unzip 6.0.0
vcredist140 14.38.33135
vcredist2015 14.0.24215.20170201
vifm 0.11.0
vim 9.0.2146
visualstudio-installer 2.0.3
wezterm 20240203.110809.0
wezterm.install 20240203.110809.0
windirstat 1.1.2.20161210
wiztree 4.17.0
zoxide 0.9.2
``
```

### Output Log

```bash
choco outdated --debug --verbose:
[chco-bug.log](https://github.com/chocolatey/choco/files/14330265/chco-bug.log)
```

**Comment by Drllap** [comment]
Appears that the log wasn't attached:
[chco-bug.log](https://github.com/chocolatey/choco/files/14330287/chco-bug.log)

**Comment by jhvissotto** [comment]
I have the same trouble here.

"Please provide credentials for: https://community.chocolatey.org/api/v2/"

![image](https://github.com/chocolatey/choco/assets/19745638/4dcf35d7-8347-42b6-a72a-7594fba7fef6)

**Comment by Ana06** [comment]
Our CI (GH actions) in [VM-Packages](https://github.com/mandiant/VM-Packages) is also affected by this issue. This has started happening today, as it worked fine yesterday. Example:  https://github.com/mandiant/VM-Packages/actions/runs/7958975080/job/21725002532?pr=904#step:4:22

**Comment by yan12125** [comment]
I'm also affected. Probably the issue is related to [Chocolatey Community Repository Performance Degradation](https://status.chocolatey.org/issues/2024-02-19-chocolatey-community-repository-performance-degradation/).

**Comment by derobins** [comment]
Please fix this

**Comment by pauby** [comment]
As highlighted above, the issue can be found on the [status page](https://status.chocolatey.org).
