### ISSUE TITLE
Documentation does not state correct option for "force x86"

### ISSUE THREAD

**Issue by ariofrio** [chocolatey/choco#340]
In [this page](https://github.com/chocolatey/choco/wiki/CommandsInstall#options-and-switches), we are told that we can use --x86 or --forcex86 to install a program using its 32-bit installer. However, only -x86 (with one dash) works:

#### --x86

    $ choco install --x86 activetcl
    Chocolatey (v0.9.8.33) is installing '--x86' and dependencies. By installing you accept the license for '--x86' and each dependency you are installing.
    Unknown option: '--x86'

    Chocolatey (v0.9.8.33) is installing 'activetcl' and dependencies. By installing you accept the license for 'activetcl' and each dependency you are installing.

    ActiveTcl v8.6.4.0
    Downloading activetcl 64 bit from 'http://downloads.activestate.com/ActiveTcl/releases/8.6.4.0/ActiveTcl8.6.4.0.298892-win32-x86_64-threaded.exe'
    Installing activetcl...
    activetcl has been installed.
    activetcl has finished successfully! The chocolatey gods have answered your request!

#### --forcex86

    $ choco install --forcex86 activetcl
    Chocolatey (v0.9.8.33) is installing '--forcex86' and dependencies. By installing you accept the license for '--forcex86' and each dependency you are installing.
    Unknown option: '--forcex86'

    Chocolatey (v0.9.8.33) is installing 'activetcl' and dependencies. By installing you accept the license for 'activetcl' and each dependency you are installing.

    ActiveTcl v8.6.4.0
    Downloading activetcl 64 bit from 'http://downloads.activestate.com/ActiveTcl/releases/8.6.4.0/ActiveTcl8.6.4.0.298892-win32-x86_64-threaded.exe'
    Installing activetcl...
    activetcl has been installed.
    activetcl has finished successfully! The chocolatey gods have answered your request!

#### -x86

    $ choco install -x86 activetcl
    Chocolatey (v0.9.8.33) is installing 'activetcl' and dependencies. By installing you accept the license for 'activetcl' and each dependency you are installing.

    ActiveTcl v8.6.4.0
    Downloading activetcl 32 bit from 'http://downloads.activestate.com/ActiveTcl/releases/8.6.4.0/ActiveTcl8.6.4.0.298892-win32-ix86-threaded.exe'
    Installing activetcl...
    activetcl has been installed.
    activetcl has finished successfully! The chocolatey gods have answered your request!
    Finished installing 'activetcl' and dependencies - if errors not shown in console, none detected. Check log for errors if unsure.

**Comment by ferventcoder** [comment]
Apologies @ariofrio - you are using 0.9.8.33, where this repo is specifically for 0.9.9+

**Comment by ferventcoder** [comment]
To allow you to find what you are looking for, see https://github.com/chocolatey/chocolatey/wiki/CommandsInstall instead.

**Comment by ferventcoder** [comment]
Note we state this at the very top of https://github.com/chocolatey/choco/wiki, but perhaps we need a better way to call that out across every page.

**Comment by ariofrio** [comment]
In my particular case, I did see that notice, but I thought I was running
the latest version of chocolatey.

**Comment by ferventcoder** [comment]
I did add it to the wiki sidebar just now https://github.com/chocolatey/choco/wiki

![image](https://cloud.githubusercontent.com/assets/63502/8319362/99d428c2-19d3-11e5-87d3-aa32fcb8d18d.png)

**Comment by ferventcoder** [comment]
@ariofrio could be you used boxstarter after installing 0.9.9+?

**Comment by ariofrio** [comment]
The main usability problem here might be that 0.9.8.33 and 0.9.9.7 are very similar-looking. It never caught my attention they were different and my version of Chocolatey was outdated. :-) Thanks for the prompt response! Upgrading.

(I did not use boxstarter. But thanks for telling me about it, it looks really useful!)

**Comment by ferventcoder** [comment]
Hmmm, not sure what we can do to adjust that. They should look similar :)
