### ISSUE TITLE
Choco deleted my `oh-my-posh` installation whilst uninstalling `neovim 0.9.5`

### ISSUE THREAD

**Issue by m-ikiara** [chocolatey/choco#3400]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues related to my problem exist.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security-related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What Are You Seeing?

So while uninstalling Neovim installed via `choco`, I found that my `JanDeDobbeleer.OhMyPosh` installed via `winget` got deleted. "Mysteriously".

### What is Expected?

1. The uninstallation scripts run by `choco` should not fail.
2. `choco` should uninstall Neovim without affecting my other installed packages.
3. `choco` is a different package manager from `scoop`, `apt-cyg` and `winget`.

### How Did You Get This To Happen?

1. Ran `choco uninstall neovim`,
4. Saw a warning that one of the uninstall scripts `.ps1` failed,
5. Noticed that `oh-my-posh` got "mysteriously" deleted,
6. Restarted my computer,
7. Listed all existing packages installed via `winget`. Confirmed `oh-my-posh` missing,
8. Listed all existing packages installed via `choco` and confirmed `neovim` was uninstalled,
9. Reinstalled `oh-my-posh` and confirmed no other package was "mysteriously" deleted. 

### System Details

* Operating System: Windows 10 Pro
* Windows PowerShell version: 7.4.1
* Chocolatey CLI Version: 2.2.2
* Chocolatey Licensed Extension version: Chocolatey v2.2.2 Professional
* Chocolatey License type: user-based
* Terminal/Emulator: Microsoft Terminal

### Installed Packages

```bash
chocolatey 2.2.2
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-windowsupdate.extension 1.0.5
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
openjdk 21.0.2
php 8.3.2
vcredist140 14.38.33135
vcredist2015 14.0.24215.20170201
```
### Output Log

I've created a [Gist](https://gist.github.com/m-ikiara/49a6e55d5554ae255f626f8f29f557fd) containing the following files:

1. `chocolatey.log`
2. `choco.summary.log`

### Additional Context

I found my `nvim`, installed via `choco`, had a VirusTotal score of 1/76 from 5th Feb. I can also confirm that it wasn't a false positive. I decided to uninstall it, and the above happened. What puzzles me is why Chocolatey would interfere with packages installed by a different package manager, WinGet. This is concerning! I hope this issue is resolved and will help develop this robust package manager! Cheerio!

**Comment by pauby** [comment]
Can you go back and remove _all_ emojis from your issue? They are not necessary and distract from the issue.

Can you also provide _all_ the logs requested by the issue template, by amending the original comment and adding them in? Please don't add them as a separate comment.

Without this, we will be unable to look further at the issue.

**Comment by m-ikiara** [comment]
Hello there,
At least I got a response from a human! Sorry for all that earlier. I believe that the instructions stated that I could add a link to a [Gist](https://gist.github.com/m-ikiara/0d70c4e0d5a8f2cd119753d3135a9eb8) instead of dumping them all in the issue. I hope the amendments are to your liking. Once more, I'm very sorry for all of that and blessings!

**Comment by pauby** [comment]
The problems appear to be that the [installation of `neovim` was detected in the `oh-my-posh` folder](https://gist.github.com/m-ikiara/49a6e55d5554ae255f626f8f29f557fd#file-env-programdata-chocolatey-logs-choco-summary-log-L3705-L3706). This can happen if two installations are taking place at the same time (one Chocolatey CLI and one Winget in this case). When Chocolatey CLI looks to take a snapshot of the changed files and registry keys, it will see _all_ changed entries.

When you run the uninstall of `neovim` the pertinent log lines are:

```
2024-02-19 13:16:49,652 10028 [DEBUG] -  Preparing uninstall key '"C:\Users\bigboy69\AppData\Local\Programs\oh-my-posh\unins000.exe" /SILENT' for 'Oh My Posh version 19.8.2'
2024-02-19 13:16:49,707 10028 [DEBUG] -  Uninstaller path is 'C:\Users\bigboy69\AppData\Local\Programs\oh-my-posh\unins000.exe'
2024-02-19 13:16:49,707 10028 [DEBUG] -  Installer type is 'InnoSetupInstaller'
2024-02-19 13:16:49,707 10028 [DEBUG] -  Setting up uninstall logging directory at C:\Users\bigboy69\AppData\Local\Temp\chocolatey\neovim\0.9.5
2024-02-19 13:16:49,717 10028 [DEBUG] - Attempting to create directory "C:\Users\bigboy69\AppData\Local\Temp\chocolatey\neovim".
2024-02-19 13:16:49,717 10028 [DEBUG] -  Args are '/SILENT'
2024-02-19 13:16:49,722 10028 [DEBUG] - Calling command ['"C:\Users\bigboy69\AppData\Local\Programs\oh-my-posh\unins000.exe" /SILENT']
2024-02-19 13:16:50,867 10028 [DEBUG] - Command ['"C:\Users\bigboy69\AppData\Local\Programs\oh-my-posh\unins000.exe" /SILENT'] exited with '0'
```

It is actually uninstalling `oh-my-posh`.

> The uninstallation scripts run by choco should not fail.

If the package scripts are failing, that is a package issue and you should contact the maintainer.

> choco is a different package manager from scoop, apt-cyg and winget.

Scoop is not a package manager. Winget is a manifest / software manager. apt-cyg I have no experience with. So Chocolatey CLI _is_ different.

**Comment by m-ikiara** [comment]
Thanks so much for helping out with this issue. This scared me. I'll contact the Maintainer and not run into the same problem later. Till next time...
