### ISSUE TITLE
ChocolateyGUI stuck on "Retrieving installed packages"

### ISSUE THREAD

**Issue by esamo** [chocolatey/choco#342]
Fresh Win8 x64 system, `chocolateygui` worked for a while - two programs installed, then `notepad++` and after gui restart it claims to be `retrieving installed packages`, but no resources or hdd is under load.

---

Regards & respect.

**Comment by RichiCoder1** [comment]
This issue would be better posted over at [Chocolatey GUI](https://github.com/chocolatey/ChocolateyGUI/issues).

**Comment by ADTC** [comment]
For anyone reading this, you can workaround the problem by setting the compatibility mode to 'Windows 7'.

**Comment by ferventcoder** [comment]
This was refiled as https://github.com/chocolatey/ChocolateyGUI/issues/266
