### ISSUE TITLE
Change namespace casing to PascalCase

### ISSUE THREAD

**Issue by vexx32** [chocolatey/choco#3432]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Describe The Solution. Why is it needed?

In order to have our public and internal API be more consistent with the styles of the wider .NET ecosystem, we should adjust our namespaces to use PascalCase instead of lowercase.

### Additional Context

We should update `CONTRIBUTING.MD` when this change is made as well, as it refers to our current lowercase standard for namespaces.

This will be a breaking change for any projects that depend on `chocolatey.dll`, they will have to adjust their code to reflect the new namespace casing as well.

**Comment by TheCakeIsNaOH** [comment]
Is this a dup of https://github.com/chocolatey/choco/issues/3122?

**Comment by vexx32** [comment]
It is, thank you! I don't know why I couldn't find that one when I looked... I'll get that one put into this milestone instead.
