### ISSUE TITLE
Unpack the powershell files just before packaging up the nupkg (Installing chocolatey meta)

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#347]
Right now choco requires a functioning .NET 4+ framework install to even install itself on a machine. During install It will attempt twice to install .NET 4.0 if there isn't a version present, but it may run into errors or require a reboot before it is ready to be used. Because of this folks run into what looks like a missing file `chocolateyInstaller.psm1` during install, when it's actually the former reason. Without .NET 4.0, the files can't be unpacked from choco.

Unpacking those files in the nupkg will allow the errors to be more visible on a non-functioning .NET framework install versus something with a file missing. 

This will technically allow choco to be installed without the framework installed properly, just not useful.

**Comment by ferventcoder** [comment]
https://github.com/ansible/ansible-modules-extras/pull/398

**Comment by elventear** [comment]
@ferventcoder I would like to provide any information that would help debugging the issues that I am seeing on ansible but there are a couple of issues. 

The first is that it seems the error is actually an exception thrown inside your script and it is bubbling up to my powershell context, where I am running the ansible script, which does not allow me to capture the output for the chocolatey installation script.

The second issue is that if I login int the machine and run the same ansible script it succeeds.

Any ideas on what could I do to try to provide more information of my problem?

**Comment by ferventcoder** [comment]
I noticed you mentioned WinRM memory issues. Take a look at https://github.com/chocolatey/choco/issues/277

**Comment by ferventcoder** [comment]
> The first is that it seems the error is actually an exception thrown inside your script and it is bubbling up to my powershell context, where I am running the ansible script, which does not allow me to capture the output for the chocolatey installation script.

@elventear If you are installing to the default folder, go to `c:\programdata\chocolatey\logs` and you should find a log file with the details of the error.
