### ISSUE TITLE
UseEnhancedExitCodes not working (msi installation 2.3.0)

### ISSUE THREAD

**Issue by musklor** [chocolatey/choco#3473]
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

I have set useEnhancedExitCodes to "on" but it doesn't work.

choco config set --name="'UseEnhancedExitCodes'" --value="'on'"

when i use again this command, i have exit code 0 instead of 2.

### What is Expected?

Exit code 2

### How Did You Get This To Happen?

choco config set --name="'UseEnhancedExitCodes'" --value="'on'"

### System Details

No license
Windows 2016
Powershell 5 and 7.2.19

### Installed Packages

```bash
all
```

### Output Log

```bash
No log
```

**Comment by gep13** [comment]
@musklor `useEnhancedExitCodes` is a feature, not a config value.

https://docs.chocolatey.org/en-us/configuration/#useenhancedexitcodes

It would be enabled by doing:

```
choco feature enable --name="useEnhancedExitCodes"
```

Can I ask where you got the idea that this was a config value that needed to be changed?

**Comment by musklor** [comment]
Oh my god, sorry.

**Comment by gep13** [comment]
@musklor no need to apologise!

If this is something that isn't clear in the docs/blog, I would love to know where we can make improvements.
