### ISSUE TITLE
Can't change default choco installation directory

### ISSUE THREAD

**Issue by bharathmuppa** [chocolatey/choco#3474]
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Not able to install choco in AppData or in any other custom location.

### What is Expected?

If i set environment variable CholateyInstall prior to the installation, Choco should be installed in specified location as [official Docs](https://docs.chocolatey.org/en-us/choco/setup/#installing-to-a-different-location)
### How Did You Get This To Happen?

1. I ran the following script as Administrator using `powershell  -NoProfile -InputFormat None -ExecutionPolicy Bypass "C:\Users\****\automation\install-choco-env.ps1"`

```ps
# Install Chocolatey
Write-Host "Installing Chocolatey" -ForegroundColor Cyan
try {
    # Ensure the script uses TLS 1.2 for secure downloads
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
    $chocoPath = [System.Environment]::GetEnvironmentVariable('ChocolateyInstall', [System.EnvironmentVariableTarget]::Machine)
   
    Write-Host "check for chocolatey installation path: $chocoPath"

    # Download and execute the Chocolatey installation script
    Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1')) 
    Write-Host "Chocolatey installed successfully." -ForegroundColor Green
   
} catch {
    Write-Host "Failed to install Chocolatey. Please check your internet connection, firewall settings, and execution policy." -ForegroundColor Red
    exit
}
```
2. Log shows this
```cmd
>  Chocolatey Installation path: C:\Users\****\AppData\Roaming\chocolatey
```
3. But Choco is insalled in c:\ProgramData\chocolatey folder and also after the script i see the install.ps1 updates my environment varibale as well.

### System Details

* Operating System: Windows 10
* Windows PowerShell version: 5.1.22621.3672
* Chocolatey CLI Version: 2.3.0
* Chocolatey Licensed Extension version: 
* Chocolatey License type: Not required(Community)
* Terminal/Emulator: Windows CMD

### Installed Packages

```bash
N/A
```

### Output Log

```bash
Installing Chocolatey
check for chocolatey installation path: C:\Users\****\AppData\Roaming\chocolatey
Forcing web requests to allow TLS v1.2 (Required for requests to Chocolatey.org)
Getting latest version of the Chocolatey package for download.
Not using proxy.
Getting Chocolatey from https://community.chocolatey.org/api/v2/package/chocolatey/2.3.0.
Downloading https://community.chocolatey.org/api/v2/package/chocolatey/2.3.0 to C:\Users\*****\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip
Not using proxy.
Extracting C:\Users\****\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip to C:\Users\****\AppData\Local\Temp\chocolatey\chocoInstall
Installing Chocolatey on the local machine
Creating ChocolateyInstall as an environment variable (targeting 'Machine')
  Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
WARNING: It's very likely you will need to close and reopen your shell
  before you can use choco.
Restricting write permissions to Administrators
We are setting up the Chocolatey package repository.
The packages themselves go to 'C:\ProgramData\chocolatey\lib'
  (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin'
  and points to an executable in 'C:\ProgramData\chocolatey\lib\yourPackageName'.

Creating Chocolatey CLI folders if they do not already exist.

chocolatey.nupkg file not installed in lib.
 Attempting to locate it from bootstrapper.
PATH environment variable does not have C:\ProgramData\chocolatey\bin in it. Adding...
```

**Comment by pauby** [comment]
Did you follow the instructions on [how to install Chocolatey CLI to a different folder](https://docs.chocolatey.org/en-us/choco/setup/#installing-to-a-different-location)?

**Comment by pauby** [comment]
The logs say:

> Creating ChocolateyInstall as an environment variable (targeting 'Machine') Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'

Which indicates it's not finding the environment variable you created.

You didn't mention _how_ you created the `ChocolateyInstall` environment variable and targetting which scope.

The [documentation states](https://docs.chocolatey.org/en-us/choco/setup/#installing-to-a-different-location):

> Create a machine level (user level will also work) environment variable named ChocolateyInstall and set it to the folder you want Chocolatey to install to prior to installation (this environment variable must be set globally or available to PowerShell- it is not enough to simply make it available to your current command prompt session).

**Comment by bharathmuppa** [comment]
> The logs say:
> 
> > Creating ChocolateyInstall as an environment variable (targeting 'Machine') Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
> 
> Which indicates it's not finding the environment variable you created.
> 
> You didn't mention _how_ you created the `ChocolateyInstall` environment variable and targetting which scope.
> 
> The [documentation states](https://docs.chocolatey.org/en-us/choco/setup/#installing-to-a-different-location):
> 
> > Create a machine level (user level will also work) environment variable named ChocolateyInstall and set it to the folder you want Chocolatey to install to prior to installation (this environment variable must be set globally or available to PowerShell- it is not enough to simply make it available to your current command prompt session).

When I started, I created a single script where I changed the environment variables and then ran install.ps1 as you can see in the script. However, after digging deeper, I realized that the environment variable changes were updated in a process other than install.ps1. Therefore, I moved that logic to another file and ran it before executing install.ps1. I ran this new script first and then, after its successful execution, I ran install.ps1.

In point 2, I posted the log of me printing the path in the other PowerShell script before install.ps1 starts executing.

**Comment by corbob** [comment]
@bharathmuppa, I've done some digging on this, and I think I can explain what's happening. It looks like you're setting the `ChocolateyInstall` environment variable at the machine level, which is what the docs suggest. However, it would seem then that you're not loading a new PowerShell process from Windows Explorer, so the environment variable is not being made available to the Chocolatey install script.

What I have done that I can confirm works:

```powershell
$env:ChocolateyInstall = 'C:\ProgramData\choco'
irm chocolatey.org/install.ps1 | iex
```

In your script, if you update your environment variable check to use this: `[System.Environment]::GetEnvironmentVariable('ChocolateyInstall', [System.EnvironmentVariableTarget]::Process)` I suspect that you will not see it set in the process level which is where Chocolatey needs it to be set.

I've opened an issue on the docs repository here: https://github.com/chocolatey/docs/issues/1031 to get the docs updated to be more clear.

**Comment by bharathmuppa** [comment]
> @bharathmuppa, I've done some digging on this, and I think I can explain what's happening. It looks like you're setting the `ChocolateyInstall` environment variable at the machine level, which is what the docs suggest. However, it would seem then that you're not loading a new PowerShell process from Windows Explorer, so the environment variable is not being made available to the Chocolatey install script.
> 
> What I have done that I can confirm works:
> 
> ```powershell
> $env:ChocolateyInstall = 'C:\ProgramData\choco'
> Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
> ```
> 
> In your script, if you update your environment variable check to use this: `[System.Environment]::GetEnvironmentVariable('ChocolateyInstall', [System.EnvironmentVariableTarget]::Process)` I suspect that you will not see it set in the process level which is where Chocolatey needs it to be set.
> 
> I've opened an issue on the docs repository here: [chocolatey/docs#1031](https://github.com/chocolatey/docs/issues/1031) to get the docs updated to be more clear.

Could you please try the same process after thoroughly cleaning all traces of Chocolatey from both machine-level and user-level environments, including the PATH variable? I had tried this method before, and it worked initially. However, after I cleaned up my system and user environment variables completely and tried again, it didn't work.

I read about the issues with process environment variables and syncing environment variables, so I separated the two scripts, thinking that might help. However, the real problem seems to lie within the Chocolatey installation itself.

**Comment by corbob** [comment]
@bharathmuppa, I'm still not able to get it to install to a different location when the `ChocolateyInstall` environment variable is available in the session that the install script is running in. To demonstrate this, I've put together the below Vagrantfile. When run with `vagrant up`, Chocolatey is installed to `C:\ProgramData\CustomChoco`. 

To provide a little bit of information on what the Vagrantfile will do:

1. Stand up a Windows 2022 VM with no Chocolatey on it.
2. Set the `ChocolateyInstall` environment variable in the Machine context via .Net
3. List out the `ChocolateyInstall` environment variable in all of the various contexts (Process via `$env:ChocolateyInstall`, Machine, User, and Process via .Net calls).
4. It will then list out the environment variables stored in the registry.
5. Next it starts a new PowerShell process, where it lists out the same information as above, and runs the Chocolatey install script.
7. Finally, it loads another new PowerShell Process, and lists the same information again.

<details><summary>Vagrantfile</summary>
<p>


```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Set defaults or get information from Environment variables.
$mem = ENV['VM_MEMORY'] ? ENV['VM_MEMORY'].to_i : 4096
$cpu = ENV['VM_CPU'] ? ENV['VM_CPU'].to_i : 2
$showGui = ENV['VM_GUI'] ? ENV['VM_GUI'].to_s.downcase == 'true' : true
$vram = ENV['VM_VRAM'] ? ENV['VM_VRAM'].to_i : 128


Vagrant.configure("2") do |config|
  config.vm.box = "StefanScherer/windows_2022"
  config.vm.boot_timeout = 600
  config.vm.hostname = 'base'

  config.vm.guest = :windows
  config.windows.halt_timeout = 60
  config.windows.set_work_network = true

  # winrm
  config.vm.communicator = 'winrm'
  config.winrm.username = 'vagrant'
  config.winrm.password = 'vagrant'
  config.winrm.retry_limit = 30
  config.winrm.retry_delay = 10

  config.vm.provider :virtualbox do |v, override|
    v.gui = $showGui
    v.memory = $mem
    v.cpus = $cpu
    v.linked_clone = true
    v.customize ['modifyvm', :id, '--vram', "#{$vram}"]
  end

  config.vm.provision 'ListEnvironmentPre', privileged: true, type: 'shell', inline: <<-SHELL
    [System.Environment]::SetEnvironmentVariable('ChocolateyInstall', 'C:\\ProgramData\\CustomChoco', 'Machine')
    "ChocolateyInstall: $($env:ChocolateyInstall)"
    "Machine ChocolateyInstall: $([System.Environment]::GetEnvironmentVariable('ChocolateyInstall', 'Machine'))"
    "User ChocolateyInstall: $([System.Environment]::GetEnvironmentVariable('ChocolateyInstall', 'User'))"
    "Process ChocolateyInstall: $([System.Environment]::GetEnvironmentVariable('ChocolateyInstall', 'Process'))"
    get-item HKCU:\\Environment\\
    get-item 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment\\'
  SHELL

  config.vm.provision 'InstallChocolatey', privileged: true, type: 'shell', inline: <<-SHELL
    "ChocolateyInstall: $($env:ChocolateyInstall)"
    "Machine ChocolateyInstall: $([System.Environment]::GetEnvironmentVariable('ChocolateyInstall', 'Machine'))"
    "User ChocolateyInstall: $([System.Environment]::GetEnvironmentVariable('ChocolateyInstall', 'User'))"
    "Process ChocolateyInstall: $([System.Environment]::GetEnvironmentVariable('ChocolateyInstall', 'Process'))"
    get-item HKCU:\\Environment\\
    get-item 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment\\'
    Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
  SHELL

  config.vm.provision 'ListEnvironmentPost', privileged: true, type: 'shell', inline: <<-SHELL
    "ChocolateyInstall: $($env:ChocolateyInstall)"
    "Machine ChocolateyInstall: $([System.Environment]::GetEnvironmentVariable('ChocolateyInstall', 'Machine'))"
    "User ChocolateyInstall: $([System.Environment]::GetEnvironmentVariable('ChocolateyInstall', 'User'))"
    "Process ChocolateyInstall: $([System.Environment]::GetEnvironmentVariable('ChocolateyInstall', 'Process'))"
    get-item HKCU:\\Environment\\
    get-item 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment\\'
  SHELL
end
```

</p>
</details>

**Comment by bharathmuppa** [comment]
Just wondering why can't install.ps1 accepts named parameters like path or location ?

**Comment by TheCakeIsNaOH** [comment]
> Just wondering why can't install.ps1 accepts named parameters like path or location ?

To my understanding it is because it is generally run with `Invoke-Expression`, instead of generally being run as a normal script/function. This might be a good feature request?

An alternative could be to use the completely offline install if you want more control over the installation process:
https://docs.chocolatey.org/en-us/choco/setup/#completely-offline-install

**Comment by bharathmuppa** [comment]
Is it possible to have it as feature request?

**Comment by pauby** [comment]
As there is already a process for installing to a different directory that works, and has been in place for some time so is tried and tested, this isn't something we would be looking to add. 

To support package parameters for the Chocolatey CLI package, Chocolatey CLI would need to be already installed defeating the purpose.

We will be adding other ways to install Chocolatey CLI in future.
