### ISSUE TITLE
installing from packages.config should be a flag and  not depend on the filename

### ISSUE THREAD

**Issue by jpmorris** [chocolatey/choco#348]
Based on the syntax cinst requires that packages.config have this exact name.  Some people might want a gensetup.xml then a rubydevl.xml, or something else.  It would be better if it was a flag that gook a filename argument.

**Comment by ferventcoder** [comment]
Just needs to end in .config. It's a requirement and can reduce confusion. Is there any reason you don't feel you can meet the requirement of the file name?

**Comment by jpmorris** [comment]
oops...Didn't know that.  Saw the usage:

    choco install <pkg|packages.config> [<pkg2> <pkgN>] [<options/switches>]
    cinst <pkg|packages.config> [<pkg2> <pkgN>] [<options/switches>]

And assumed since it wouldn't take my xml extension that 'packages.config' was the required name.  But if it takes any prefix, that's fine with me.

**Comment by ferventcoder** [comment]
I'm going to close this issue based on your response. Unless you feel we need to address any documentation related to this.

**Comment by jpmorris** [comment]
Up to you.  I thought the documentation was unclear when it says 'packages.config'.  I wouldn't know the best way to rewrite that.  But newbies like me might get tripped up with <pkg|packages.config>.If it does explain somewhere in the docs that only the .config extension matters and I just missed it, then I suppose  there is even less of a need for change.   I leave it to your best judgement.

**Comment by ferventcoder** [comment]
I updated https://github.com/chocolatey/choco/wiki/CommandsInstall#packagesconfig and https://github.com/chocolatey/choco/wiki/CommandsInstall#usage

**Comment by jpmorris** [comment]
Thanks! It will help out the newbies like myself.
