### ISSUE TITLE
Both upgrade and uninstall obs-studio.install fail blocking upgrade nodejs

### ISSUE THREAD

**Issue by theking2** [chocolatey/choco#3480]
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Upgrade
> ERROR: Running ["C:\ProgramData\chocolatey\lib\obs-studio.install\tools\OBS-Studio-30.1.2-Full-Installer-x64_x64.exe" /S] was not successful. Exit code was '6'. Exit code indicates the following: Setup process was forcefully terminated by the debugger..
> The upgrade of obs-studio.install was NOT successful.
> Error while running 'C:\ProgramData\chocolatey\lib\obs-studio.install\tools\chocolateyinstall.ps1'.
>  See log for details.

uninstall
> obs-studio.install is not installed. Cannot uninstall a non-existent package.

upgrade nodejs

> Unable to resolve dependency 'obs-studio.install'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.

### What is Expected?

upgrade of nodejs

### How Did You Get This To Happen?

upgrade all failed as upgrade nodejs fails

### System Details

* Operating System: Windows 10
* Windows PowerShell version: 7
* Chocolatey CLI Version: 2.3.0
* Chocolatey Licensed Extension version:
* Chocolatey License type:
* Terminal/Emulator:

### Installed Packages

```bash
Chocolatey v2.3.0
autohotkey.portable 2.0.17
brave 1.67.123
chocolatey 2.3.0
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-windowsupdate.extension 1.0.5
composer 6.3.0
dart-sdk 3.4.4
directoryopus 13.7.0
dotnet-7.0-runtime 7.0.20
hwinfo.install 8.0.0
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
KB3063858 1.0.0
keepass 2.57.0
keepass.install 2.57.0
keepass-plugin-keetheme 0.10.7
nodejs 22.3.0
nodejs.install 22.3.0
notepadplusplus 8.6.8
notepadplusplus.install 8.6.8
obs 0.659.20200402
obs-studio 30.1.2
php 8.3.8
PowerShell 5.1.14409.20180811
rainmeter 4.3.0.3321
sass 1.77.6
vcredist140 14.40.33810
vcredist2017 14.16.27033
winmerge 2.16.40
```

### Output Log

```bash
<script src="https://gist.github.com/theking2/d9a8715ed1067c88f0f3531da641016f.js"></script>
```

### Additional Context

OBS studio was uninstalled with its own installer

**Comment by pauby** [comment]
You cannot uninstall `obs-studio.install` because it's not installed. Your installed package list and its failure to install confirms that.

Try installing it.

Also see the [docs](https://docs.chocolatey.org/en-us/choco/troubleshooting/dependency-troubles/).

**Comment by theking2** [comment]
I was able to uninstall obs-studio and obs-studio.install from choco with the `-n` option. And as long as obs-studio installation over choco is buggy probably do a manual install for the time being

**Comment by pauby** [comment]
> And as long as obs-studio installation over choco is buggy probably do a manual install for the time being

I just wanted to clear this up. The "installation over choco" is not "buggy", the installer failed to install the software and exited with code 6.

> ERROR: Running ["C:\ProgramData\chocolatey\lib\obs-studio.install\tools\OBS-Studio-30.1.2-Full-Installer-x64_x64.exe" /S] was not successful. Exit code was '6'. Exit code indicates the following: Setup process was forcefully terminated by the debugger..
