### ISSUE TITLE
bind-toolsonly error : parse of C:\WINDOWS\system32\etc\resolv.conf failed

### ISSUE THREAD

**Issue by zod076** [chocolatey/choco#3484]
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

PS C:\Windows\System32> dig www.google.com
C:\ProgramData\chocolatey\lib\bind-toolsonly\tools\content\dig.exe: parse of C:\WINDOWS\system32\etc\resolv.conf failed

### What is Expected?

A working dns resolution

### How Did You Get This To Happen?

PS C:\Windows\System32> dig www.google.com
C:\ProgramData\chocolatey\lib\bind-toolsonly\tools\content\dig.exe: parse of C:\WINDOWS\system32\etc\resolv.conf failed

### System Details

* Operating System: Windows 10 64bit
* Windows PowerShell version: 7.4.1
* Chocolatey CLI Version: 2.3.0
* Chocolatey Licensed Extension version: N/A
* Chocolatey License type: free
* Terminal/Emulator: PowerShell

### Installed Packages

```bash
bind-toolsonly 9.16.28
```

### Output Log

```bash
A non Choco-CLI error
```

### Additional Context

Error occured on an IPv6-only machine.

**Comment by zod076** [comment]
Forgot to add that I created the resolv.conf file with Google IPv6 DNS servers as nameservers and tested the command again and still get the same error message.

**Comment by pauby** [comment]
You ticked this box:

> I have verified this is not an issue for a specific package

And you also said this:

> A non Choco-CLI error

This is not a Chocolatey CLI issue.
