### ISSUE TITLE
Unable to load the service index for source

### ISSUE THREAD

**Issue by zzy444626905** [chocolatey/choco#3492]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

Unable to load the service index for source https://community.chocolatey.org/api/v2/. 由于意外的数据包格式，握手失败。 For more information on this issue and guidance in resolving the problem, see https://ch0.co/t/svcidx Unable to connect to source 'https://community.chocolatey.org/api/v2/':  未将对象引用设置到对象的实例。

### Describe The Solution. Why is it needed?

Unable to load the service index for source https://community.chocolatey.org/api/v2/. 由于意外的数据包格式，握手失败。 For more information on this issue and guidance in resolving the problem, see https://ch0.co/t/svcidx Unable to connect to source 'https://community.chocolatey.org/api/v2/':  未将对象引用设置到对象的实例。

### Additional Context

win10 

### Related Issues

C:\Users\zzy\Desktop>choco install gmp
Chocolatey v2.3.0
Installing the following packages:
gmp
By installing, you accept licenses for the packages.
Unable to load the service index for source https://community.chocolatey.org/api/v2/.
由于意外的数据包格式，握手失败。
For more information on this issue and guidance in resolving the problem, see https://ch0.co/t/svcidx
Unable to connect to source 'https://community.chocolatey.org/api/v2/':
 未将对象引用设置到对象的实例。
gmp not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - gmp - gmp not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.

**Comment by pauby** [comment]
Did you follow the instructions in the error message?
