### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by wederw** [chocolatey/choco#350]
Hi,

i get the following error when i try to install chromium.

PS C:\Windows\system32> choco install chromium
Chocolatey v0.9.9.8
Installing the following packages:
chromium
By installing you accept licenses for the packages.
chromium not installed. An error occurred during installation:
 Der Remoteserver hat einen Fehler zurückgegeben: (403) Unzulässig.
The install of chromium was NOT successful.
chromium not installed. An error occurred during installation:
 Der Remoteserver hat einen Fehler zurückgegeben: (403) Unzulässig.

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details (D:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
 - chromium

The same error occurs when installing other pakages like googlechromme, firefox, notepadplusplus.

I am able to install adobereader, vlc and owncloud-client without this error.

**Comment by ferventcoder** [comment]
Hello. Please provide the information from your log (`D:\ProgramData\chocolatey\logs\chocolatey.log`) so we can get a better idea of what may be causing the issue. Do you have a proxy?

**Comment by ferventcoder** [comment]
Ping @wederw

**Comment by ferventcoder** [comment]
I'm closing this for now due to not hearing back. If you want to continue this discussion, feel free to reply and we can continue.

**Comment by lennartb-** [comment]
I'm having the same issue. It's related to our company firewall that when downloading exe files via browser explicitly askes if you really want to download it. That doesn't work when downloading via command line. I'm not sure if you can bypass that, but it would be cool if there was a solution.

**Comment by ferventcoder** [comment]
@lennartb- Choco has proxy and explicit proxy settings, I'm not sure if that is the same.

**Comment by lennartb-** [comment]
Doesn't seem to be the case. The button that allows you to download itin the browser is essentially something like `http://firewall-adress.com/proceed?extension=exe&url=http://path.com/to/the.exe`. I tried injecting it into the Get-ChocolateyWebFile.ps1 but it only seems to work if you're clicking the button in the browser.

**Comment by ferventcoder** [comment]
@lennartb- sounds like quite a restrictive firewall. I don't think you are going to find a way through with Chocolatey alone.

**Comment by lennartb-** [comment]
Sorry, got to bring that up again. It seems that our firewall only blocks http downloads, https is fine. So several packages download and install without problems (those with a HTTPS link), while those with HTTP fail. I realize that the dl links are dependent on the package maintainer. Since some hosts actually do support HTTPS connections even though the link points to HTTP (e.g. http://download.linqpad.net/public/LINQPad5Setup.exe fails, while https://download.linqpad.net/public/LINQPad5Setup.exe works), would it be maybe possible to retry to download a package via HTTPs - or do so via a flag?

**Comment by ferventcoder** [comment]
You mean automatically attempt https at first? That actually sounds pretty awesome!

**Comment by ferventcoder** [comment]
@lennartb- will you create a new feature for this?

**Comment by lennartb-** [comment]
Will do when I get home.
