### ISSUE TITLE
Same version shown as upgrade

### ISSUE THREAD

**Issue by pyhedgehog** [chocolatey/choco#351]
`choco outdated` lists package that has no updates:
![bug_choco_nodist](https://cloud.githubusercontent.com/assets/1286400/8547171/d467652e-24c5-11e5-9c36-6abad4baa4c4.png)
Also it shows `Warnings: - nodist`, but no warnings was shown even with `choco outdated -pre -dv`.

**Comment by ferventcoder** [comment]
Just beta packages right?

I wonder what the warning is? Perhaps that it can't find the package. I know that's one of the reasons.

**Comment by pyhedgehog** [comment]
Warning, I think is from behind-the-scene `choco upgrade`:
```console
C:\Users\michaeld>choco upgrade -noop nodist
Chocolatey v0.9.9.8
_ Chocolatey:ChocolateyUpgradeCommand - Noop Mode _
nodist was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"

Chocolatey can upgrade 0/1 package(s).
 1 package(s) had warnings.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Warnings:
 - nodist
```
However there are corresponding version:
https://chocolatey.org/packages/nodist/0.4.6-beta

**Comment by pyhedgehog** [comment]
It's really corresponds to `-beta` version parsing.
I've installed another beta package and got:
```Console
C:\>choco outdated
Chocolatey v0.9.9.8
Outdated Packages
 Output is package name | current version | available version | pinned?

firefox-nightly|43.0-alpha1|43.0-alpha1|false
nodist|0.4.6-beta|0.4.6-beta|false
Firefox|39.0.3|40.0.2|false
ConEmu|15.7.28.0|15.8.14.0|false

Chocolatey has determined 2 package(s) are outdated.
 2 package(s) had warnings..
Warnings:
 - firefox-nightly
 - nodist
```

**Comment by ferventcoder** [comment]
What happens if you specify `choco outdated -pre`?

**Comment by pyhedgehog** [comment]
No difference.

**Comment by ferventcoder** [comment]
Going to close this for #843 - the title is more helpful and there is more discussion over there.
