### ISSUE TITLE
Open Source, 100% Free, Trial/Limited flags

### ISSUE THREAD

**Issue by Mugane** [chocolatey/choco#3533]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

It is really tedious to have to install dozens of different applications one by one to evaluate if they are feature limited in some way. Take diff tools for example. `choco find diff` returns over sixty (60) results. 

### Describe The Solution. Why is it needed?

I propose a unique tag (string flag) that can be used in find results to filter out software based on the license/feature category:

1.a. [#OS] Open source
1.b. [#CS] Closed source (proprietary)

and

2.a. [#FFF] Free (fully functional)
2.b. [#FTL] Free (time-limited)
2.c. [#FFL] Free (feature-limited)

Or something like that. The important thing is that they are unique, and appear in terminal search results for grep filtering.

Each package would have a tag for each of 1 and 2 to cover all the combinations of properties. E.g. WinMerge would have #OS #FFF since it's open source and the open source version is fully functional while GitLab CE would have #OS #FFL since even though it claims to be open source, it has only a subset of features of the full GitLab Enterprise version. 

### Additional Context

This would be invaluable in saving time selecting open source tools that always seem to claim that designation these days but are very frequently limited in major ways when there are paid versions available. I don't care about how people collect money, but I do care about having that information up front. What an absurd practice, btw - who would ever start paying for software they thought would be free after they spend hours setting it up to discover such a rug-pull deep in the greyed out settings? But that is the world we live in.

**Comment by pauby** [comment]
The answer to this is very much the same as that in #3497. I don't want to just repeat everything in there so I'm happy to respond to any particular points mentioned in there.

**Comment by Mugane** [comment]
> The answer to this is very much the same as that in [#3497](https://github.com/chocolatey/choco/issues/3497). I don't want to just repeat everything in there so I'm happy to respond to any particular points mentioned in there.

I'm honestly not seeing any correlation whatsoever
