### ISSUE TITLE
`no7zip` build step is ILmerging all the test assemblies into the final choco.exe

### ISSUE THREAD

**Issue by vexx32** [chocolatey/choco#3534]
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

When running the build with the `ReleaseOfficial` configuration to generate the no7zip build artifacts, the resulting .exe is almost twice the size of the normal exe... despite being _supposed_ to contain fewer things than the original build.

In examining what is going on here, we appear to be piping _all_ the build output for this configuration into the same directory and not filtering out any of the test assemblies' output, so we get a lot of extraneous DLLs thrown into the mix.

### What is Expected?

We either need to rework how we're doing the no7zip build entirely, or go through and painstakingly exclude all the test assemblies _and every dependency_ from the ILMerge step. And then keep that up to date every time the dependencies (including transitive dependencies) change for one of the test projects.

### How Did You Get This To Happen?

1. `./build.ps1 -Configuration ReleaseOfficial`
2. Inspect the `code_drop/temp/_PublishedApps/choco-no7zip` folder and note _all of the test assemblies and dependencies in here_, including a bunch of AspNetCore assemblies
3. Look at the packages in the `code_drop` folder and open up the nupkgs for the noz7ip and normal builds. Note the file size of the choco.exe within the `tools/chocolateyInstall` folder in these nupkgs; the no7zip version is almost double the size.

### System Details

N/A, build issue

### Installed Packages

```bash
N/a
```

### Output Log

```bash
N/A
```

**Comment by gep13** [comment]
@vexx32 I have had a quick look at this, and I believe that I can see what is going on here.  I will put up a PR shortly to address this.
