### ISSUE TITLE
Chocolatley uninstalled visual studio from my computer

### ISSUE THREAD

**Issue by Hallilogod** [chocolatey/choco#3548]
### Checklist

- [x] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [x] I have verified this is the correct repository for opening this issue.
- [x] I have verified no other issues exist related to my problem.
- [x] I have verified this is not an issue for a specific package.
- [x] I have verified this issue is not security related.
- [x] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Hello, i installed node js and this crap ended up installing chocolately, of course node js is garbage so i uninstalled it right after trying some shit out and same with chocolately, however CHOCOLATELY UNINSTALLED THE EXISTING VISUAL STUDIO INSTALLATION FROM MY COMPUTER LITERALLY WHAT THE FUCK IS WRONG WITH THIS CRAP SCRIPT???? WHAT THE FUCK IS WRONG WITH YOU

### What is Expected?

I DONT EXPECT THIS CRAP TO UNINSTALL SOFTWARE PREVIOUSLY INSTALLED SOFTWARE

### How Did You Get This To Happen?

choco uninstall all

### System Details

Windows 10 pro x64

### Installed Packages

idfk

### Output Log

no logs

**Comment by Hallilogod** [comment]
Sorry, but if some random shit uninstalls visual studio from my computer i think its a fair reason to get a little mad

**Comment by Hallilogod** [comment]
imagine using javascript

**Comment by WilliamAnimate** [comment]
> Sorry, but if some random shit uninstalls visual studio from my computer i think its a fair reason to get a little mad

wdym? getting visual studio uninstalled is a blessing

**Comment by Hallilogod** [comment]
> > imagine using javascript
> 
> that's you lmao, oh the irony

I think we don't have to discuss the fact that windows is the worst operating system ever created by humanity, just like javascript is an abomination of a programming language, just as a side note i use GNU/Linux and its not a blessed operating system where everything is perfect, operating systems are just like computers and a failure of humanity and should not exist in the first place

**Comment by paulmsullivan** [comment]
Man these responses are so unhelpful and not relevant?

But how is it surprising to run "choco uninstall all" and have software uninstalled?

**Comment by Hallilogod** [comment]
Because i did not install visual studio with chocolately

**Comment by corbob** [comment]
Replying from my phone while out, so pardon any brevity. @Hallilogod, please see the code of conduct linked to the repository for information about expected etiquette. Please go back and edit the description to remove the inflammatory language, and if you are seeking to report a bug, please fill out the sections as best you're able.

At a cursory glance of the reported issue, it sounds like you installed nodejs by running a script without knowing what the script did. It sounds like this script installed chocolatey and possibly a number of packages. You then decided you didn't want this and ran choco uninstall all in an attempt to uninstall everything. It is entirely possible that the script you initially ran installed a visual studio package that then got uninstalled. Of course, this is all conjecture without having the details of what script you may have run, and what packages you might have had installed.

**Comment by pauby** [comment]
@Hallilogod @paulmsullivan as @corbob mentioned we have a Code of Conduct. If you can't adhere to it, don't post. We're not punching bags for your frustration.

I'm going to go ahead and close, and lock, this issue.
