### ISSUE TITLE
Chocolately can permanently corrupt the config file if an operation is interrupted

### ISSUE THREAD

**Issue by alexchandel** [chocolatey/choco#355]
If the `choco` process ends, the following error can occur whenever any `choco` command is run:
```
Error deserializing response of type chocolatey.infrastructure.app.configuration.ConfigFileSettings:
 Root element is missing.
Root element is missing.
```

And the file `chocolatey.config` is blank. It should not be possible for either of these to occur, unless the user manually clears the file.

**Comment by ferventcoder** [comment]
I'm thinking that the file should only be written to if it has changed.

**Comment by ferventcoder** [comment]
And the write should be tighter, like a backup made and then a write. If the write is not successul, rename the backup.

**Comment by pyhedgehog** [comment]
Atomic write (aka write to config.new and then move to config.xml) will help.

**Comment by GuillaumeSmaha** [comment]
I don't know why this happened. The file C:\ProgramData\chocolatey\config\chocolatey.config was empty.
Just delete the file to fix the issue.

**Comment by benh57** [comment]
+1, also encountered this

**Comment by alexchandel** [comment]
@GuillaumeSmaha deleting `chocolatey.config` indeed fixes this, but the point is that that shouldn't be necessary in the first place.

**Comment by malibeg** [comment]
+ 1

**Comment by BeezUPJohnny** [comment]
+1 
choco list -lo
Error serializing type chocolatey.infrastructure.app.configuration.ConfigFileSettings:
 Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config' is denied.
Error updating 'C:\ProgramData\chocolatey\config\chocolatey.config'. Please ensure you have permissions to do so:
 Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config' is denied.
Chocolatey v0.9.9.8

**Comment by ferventcoder** [comment]
@BeezUPJohnny I think you are looking for #364 to plus one.

**Comment by BeezUPJohnny** [comment]
Sorry....
