### ISSUE TITLE
Resolve sources by name

### ISSUE THREAD

**Issue by The1nternet** [chocolatey/choco#356]
When running:

choco install packagename -s=mysourcename

the source is not resolved by name.  Instead, you must use the source url, and pass in the full url of the source, in order to resolve it correctly.

The source should be able to resolve by name, so that the full url is not required on each install command.

**Comment by ferventcoder** [comment]
Thanks for making sure we got that logged.

**Comment by ferventcoder** [comment]
Related to https://github.com/chocolatey/choco/issues/63

**Comment by The1nternet** [comment]
Is there any progress on this issue?  Our company has to remain on the POSH version of chocolatey until this issue is resolved.

**Comment by ferventcoder** [comment]
@The1nternet interesting. I can see if I can get into the impending release at 0.9.10.

**Comment by ferventcoder** [comment]
I didn't realize this ever worked.

**Comment by ferventcoder** [comment]
This is going out in today's beta of 0.9.10.

**Comment by ferventcoder** [comment]
![image](https://cloud.githubusercontent.com/assets/63502/15612488/97ecf594-23f4-11e6-9232-24f535a9576b.png)
