### ISSUE TITLE
Chocolately 2.3.0 should be using Dotnet Core

### ISSUE THREAD

**Issue by genifycom** [chocolatey/choco#3560]
### Checklist

- [x] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [x] I have verified this is the correct repository for opening this issue.
- [x] I have verified no other issues exist related to my problem.
- [x] I have verified this is not an issue for a specific package.
- [x] I have verified this issue is not security related.
- [x] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Just finished setting up several new machines and am frustrated by the fact that Chocolately 2.3.0 STILL requires .Net framework 4.8 from 2019.

The claim for Chocolately is "Modern Software Automation" and yet it does not seem to able to transition to the now 8th version of Dotnet Core.

In the meantime, Microsoft keep pushing us to use Dotnet core and the fact that Chocolately cannot seem to make this transition flies in the face of "eating your own dog food".

WHY is Chocolately not in Dotnet core 8? WHY do I have to keep installing .Net Framework 4.8 on a newer machine just for Chocolately?

### What is Expected?

That a "Modern Software Automation" use a modern version of Dotnet.

### How Did You Get This To Happen?

I installed Chocolately on Windows Server 2019 Standard

### System Details

* Operating System: Windows Server 2019 Standard
* Windows PowerShell version: 5.1.17763.6414
* Chocolatey CLI Version: 2.3.0
* Chocolatey Licensed Extension version:
* Chocolatey License type:
* Terminal/Emulator:

### Installed Packages

```bash
Not related
```

### Output Log

```bash
Not related
```

**Comment by pauby** [comment]
This isn't an issue but a question or discussion. Please raise a discussion for this.
