### ISSUE TITLE
Export a packages.config file

### ISSUE THREAD

**Issue by SeanKilleen** [chocolatey/choco#357]
Leaving this here as a suggested enhancement because I couldn't find it anywhere. If there's support for it, I'll look into whether I could contribute the change myself.
### Use case / story

Sometimes, my whole system will become bricked (such as it did yesterday -- ouch). However, this is a lot less painful because [I export my package list](http://seankilleen.com/2014/01/quick-tip-chocolatey-powershell-dropbox-for-package-management-and-backup/) and restore using that. 

Have I mentioned that Chocolatey is amazing? :)

However, there is still some pain here -- I have to manually concatenate the package names, remove the explicit version numbers, etc. 
### Proposed change
- Add a command, such as `choco export` or `cexp` 
- Allow switches for format -- I suggest the below:
  - list: a list of the package names and their versions
  - conf: a packages.conf file
- Required argument for the path of export file
### Example usage

In a scheduled task, I can see running something along the lines of the following:

`choco export -conf C:\MyBackupLocation\packages_yyyy-mm-dd.conf`

Then, the next time my system gets bricked, it should be as easy as:

`choco install -y C:\MyBackupLocation\packages_yyyy-mm-dd.conf`

Thoughts?

**Comment by SeanKilleen** [comment]
Upon further consideration, I'd probably remove the flags for formatting. Exporting as a list would be the same as running `clist -lo`, so really the main purpose of export would be to get it into a packages.conf format.

**Comment by ferventcoder** [comment]
This is the same as https://github.com/chocolatey/chocolatey/issues/67, which needed migrated over. So thank you.

**Comment by SeanKilleen** [comment]
Great!

In terms of design, it sounds like there are two goals:

* ability to export packages.config at any given time
* exporting a packages.config

**Comment by SeanKilleen** [comment]
Great!

In terms of design, it sounds like there are multiple goals:

* ability to export packages.config at any given time
* exporting a packages.config to the chocolates dir upon changes, to maintain an always-current list.
* potentially using packages.config as a way to install sets of packages.

Is this correct?

**Comment by ferventcoder** [comment]
Sounds about right, but I don't think I would keep around a packages config file all the time to manage state. I would rather capture what args were used to install a package in the package information. This would be especially helpful for building the packages.config, but also for other purposes like knowing what to pass to build upgrade commands.

**Comment by RichiCoder1** [comment]
I know we talked about this a lot over @ chocogui. First class support would be great, def including things like source and args information if necessary.

**Comment by SeanKilleen** [comment]
@RichiCoder1 yeah, I agree it'd be awesome to have this ability at the root.

So, to clarify since I'm newish and dropping in here -- :smile: -- we want to:

* Make a change to capture the install arguments for a package at the time of install
 * E.g. so that they could theoretically be returned when running `clist -lo`
* Perhaps update `clist -lo` to return a table of package / version / Install Args
* Update the `packages.conf` spec to allow for `IA="/blah"` or something along those lines
* Create a `choco export` command or something along those lines, as mentioned above
* Discuss further whether it makes sense to keep the "current state" in a packages.config file at the chocolatey level.
 * I can see why we'd want to avoid this, but I can also see it being a nice touch for non-technical users to add it to their backup processes.

If we agree with the breakdown, I'm assuming we should create separate issues / tasks to support these individual items and reference them as appropriate?

**Comment by ferventcoder** [comment]
That's what we tend to do. Break things down to manageable units and somehow mark things as blocking.

**Comment by SeanKilleen** [comment]
Alright, I'll go ahead and organize them as I've outlined above.

**Comment by gep13** [comment]
As mentioned by @RichiCoder1, the basic export functionality is already included in ChocolateyGUI, as per this screenshot:

https://raw.githubusercontent.com/chocolatey/ChocolateyGUI/develop/docs/Screenshots/Application_Loaded.png

But it would be good to fall back on the functionality which could be included in Chocolatey, rather than re-invent the wheel.

**Comment by Cyber1000** [comment]
Any progress/timeline on this feature?
Thanks!

**Comment by ferventcoder** [comment]
@Cyber1000 note the milestone to the right and the labels. That should give you an idea where this is at. HTH

**Comment by admsteck** [comment]
A couple other options:
Instead of a new command, add an option to "choco list" to format the output in the packages.config xml format so the output can be piped into a file
Update "choco install" to accept a plain text file in the format of the current output from "choco list"

Personally, I'm not really interested in any arguments since I have never used any arguments when installing chocolatey packages.

**Comment by itopiacloud** [comment]
I'd enjoy a choco config export that you could roll into a scheduled task which saves the file to OneDrive/GDrive/wherever. Please and thank you.

**Comment by Cronus89** [comment]
I had a computer die on me after 6 years, I too wish I had an export function so I can save a copy of whats installed onto my Dropbox!

**Comment by dragon788** [comment]
You can also use the ChocolateyGUI package to create an export.

**Comment by Cronus89** [comment]
Yes but I am looking for something automated.  i could not find any command line arguments for the GUI that allow an auto export

**Comment by bcurran3** [comment]
I'm thinking it wouldn't be to hard to create PS script that would get the directory names (thus packages) from \programdata\chocolatey\lib, save it to a file, parse the package names to one line, add a cup in front of it (or cup in front of each line would probably be easier), then check for the existence of DropBox, OneDrive, Gdrive, and save the file in one or all of them.

The script could then just be distributed as a package; backup-choco-package-list or some such.

I might take this on. It would be a small challenge for me but I could learn from forcing my way through it, as I'm bad at parsing arrays. :) I'm willing to take it on in package form as a kludge until it's function is build into choco.

I'm guessing a sequel, restore-choco-package-list would then be in order.

**Comment by itopiacloud** [comment]
@bcurran3 @Cronus89 - please see - https://gist.github.com/stevenringo/5f0f9cc7b329dbaa76f495a6af8241e9

**Comment by bcurran3** [comment]
@itopiacloud 

Thanks for the info. I checked it out and it didn't really do what I wanted, but it did give me some clues how to do what I wanted. 

So until there is an official way to do this with Chocolatey... I did it my way! :)

Done! Off personal TDL:
https://chocolatey.org/packages/choco-package-list-backup

**Comment by youssefabidi** [comment]
I think that this issue is no longer blocked by #360 (if it ever was: I'm not sure I completely understand the discussion on that issue) because the packages.config file now accepts everything that can be passed during the installation of a package.
