### ISSUE TITLE
Output choco list -lo with table formatting

### ISSUE THREAD

**Issue by SeanKilleen** [chocolatey/choco#359]
Per discussion from #357, though not necessarily related.

Submitted for consideration: 

Currently, `clist -lo` outputs a list of strings formatted as `[package name] [version number]`. 

For further parsing, it may be nice to allow for the outputting of this information in a cleanly formatted table, such as:

    | Name          | Version           |
    --------------------------------------
    | MyPackage | 1.0.0

This could be achieved either by making it the default output, or by adding an additional flag for formatting as a table.

**Comment by RichiCoder1** [comment]
Is there a standard *nix way for outputting data in a table format?

**Comment by SeanKilleen** [comment]
@RichiCoder1 a great question (and one that I'll have to leave to someone more experienced than I.)

**Comment by SeanKilleen** [comment]
A quick google turns up the `column` command, which may be helpful here:

http://linux.die.net/man/1/column

**Comment by ferventcoder** [comment]
Seems that column pipes the output of something into it to return output.

Think one may be able to achieve similar in PowerShell without adding this to Chocolatey.

**Comment by ferventcoder** [comment]
I gave it a very fast spike `choco list -lo -r | %{$_.split('|')}` to prove that you could split up the output.

**Comment by ferventcoder** [comment]
By the way, you may want to look at `choco list -lo -r` as it is very similar output to what you are wanting.

**Comment by SeanKilleen** [comment]
@ferventcoder wasn't aware of `-r` -- that's all that would be needed in this case. 

Thanks! Closing.
