### ISSUE TITLE
Check for proper public key

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#36]
The default one in the repository is for building source.  If built in release mode, require a special switch to run `--allow-unofficial-build` or something like that.

When choco.exe detects that it is not using the official
publickeytoken, throw an error requiring an explicit override (this is
already overridden in debug builds). When AllowUnofficialBuild (`--allow-unofficial-build`) flag is
set to true, log a very important warning so that folks can receive
clues that the state of their system may be compromised.

**Comment by gep13** [comment]
Very cool! :+1:

**Comment by smurawski** [comment]
:+1: :+1:   Yay for security and yay for being able to build without the "official" key for testing purposes (without having to do a bunch of modifications that make pull requests suck).

**Comment by ferventcoder** [comment]
most of that brought to you by this - https://github.com/chocolatey/choco/commit/59ba8f6740719ab41e1cd0117d2e6e5fcebc7dc3
