### ISSUE TITLE
Update packages.config format to include Installation arguments

### ISSUE THREAD

**Issue by SeanKilleen** [chocolatey/choco#360]
Per discussion on #357. Would likely be blocked until #358 is complete.

If there's an official spec anywhere, it would have to be updated to include the existence of Installation Arguments. 

Not sure if this is the case, but wanted to add this as a separate issue in case anything downstream would be affected.

**Comment by ferventcoder** [comment]
Already has install args.

**Comment by ferventcoder** [comment]
I think your terminology is what is throwing me off. https://github.com/chocolatey/choco/wiki/CommandsInstall#options-and-switches

Note there is an argument called `installarguments`.

Note everything that can be passed to a packages.config now - https://github.com/chocolatey/choco/wiki/CommandsInstall#packagesconfig

**Comment by youssefabidi** [comment]
I think that this issue can be closed (since the packages.config file can include everything that can be passed during install) and is no longer blocking #357.
