### ISSUE TITLE
Suppress Warnings?

### ISSUE THREAD

**Issue by justinmchase** [chocolatey/choco#362]
There are various warnings being emitted right now, such as:

```
WARNING: You can safely ignore errors related to missing log files when
  upgrading from a version of Chocolatey less than 0.9.9.
  'Batch file could not be found' is also safe to ignore.
  'The system cannot find the file specified' - also safe.
```
and
```
WARNING: Write-ChocolateySuccess is deprecated. If you are the maintainer, 
please remove it from your package file.
```

Is there a way to suppress these? I am running a command from an admin prompt, such as:
```
$ choco install cmder --yes
```

I am not the maintainer and would rather have cleaner output.

**Comment by ferventcoder** [comment]
The first warning is user specific in case something shows up during the choco install. No suppression for that one I'm afraid, if you needed the information, it's good that it is there when things go weird.

The second warning is so folks let the maintainers know they need to update their packages. That's how you get rid of the annoying deprecated warnings.

**Comment by ferventcoder** [comment]
The right question here is how to suppress deprecation warnings, correct?

**Comment by justinmchase** [comment]
Well from my perspective, as a consumer of packages, I would like all warnings gone. If it doesn't work I'll re-run it and look at the details. But in my opinion if the output was extremely terse by default I'd be really happy. For example:

```
$ choco install whatever
[whatever] installing...
[whatever] installed.
```
or
```
$ choco install whatever
[whatever] installing...
[whatever] An unexpected error occurred, see log for details /path/to/log
The short version of the error message
prints here.
```

And then:
```
$ choco install whatever --verbose
<what it does now...>
```

I would settle for a `--no-warn` flag to reduce some of the noise but the more you can pull out of the default output the better, imo.

**Comment by aronovgj** [comment]
i too think the maintainer warning shouldn't be shown to users. so we need a way to inform the maintainer about issues without letting the user know.

how about sending automatic mails to maintainers whenever a package with an unresolved issue is pushed?

**Comment by ferventcoder** [comment]
> how about sending automatic mails to maintainers whenever a package with an unresolved issue is pushed?

We are working on this @aronovgj, but it doesn't answer the problem of letting a maintainer know if they haven't pushed a new version.

**Comment by ferventcoder** [comment]
@justinmchase 

```
  WARNING: You can safely ignore errors related to missing log files when
  upgrading from a version of Chocolatey less than 0.9.9.
  'Batch file could not be found' is also safe to ignore.
  'The system cannot find the file specified' - also safe.
```

Unfortunately these are directly related to folks filing issues or not understanding that there are errors they can safely ignore b/c they are not actually errors. I understand that you would rather not see it, but over the wider group of users this information is actually quite important for folks to see.

**Comment by aronovgj** [comment]
> We are working on this @aronovgj, but it doesn't answer the problem of letting a maintainer know if they haven't pushed a new version.

how about resending such a mail every x weeks?

**Comment by justinmchase** [comment]
@ferventcoder Well just consider it feedback. It works and I'm happy, bonus points if it looks good while doing it.
