### ISSUE TITLE
Show human-readable file sizes when downloading

### ISSUE THREAD

**Issue by KishanBagaria** [chocolatey/choco#363]
Google Groups: https://groups.google.com/forum/#!topic/chocolatey/KIEHvPtVEqs

When downloading any file, Chocolatey shows the size in bytes "Saving 8911368 of 9252864". This is difficult for humans to read and something like "Saving 8.50 MB of 8.82 MB" or "Saving 8.50 MB of 8.82 MB (8911368/9252864)" would be preferred.

Can I submit a PR for this?

If I'm not wrong, this would require including a Format-FileSize helper function and changes in these files:
https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Get-WebFile.ps1
https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Get-FtpFile.ps1
https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/chocolatey.resources.csproj

I just downloaded Chocolatey few hours ago so please let me know if I'm missing anything.

**Comment by ferventcoder** [comment]
No worries. Please read over our CONTRIBUTING document before moving forward - knowing ahead of time whether you can sign the CLA or not is the biggest hurdle for some folks.

**Comment by KishanBagaria** [comment]
Done already, I signed the CLA before posting on Google Groups.

On Saturday, July 25, 2015, Rob Reynolds <notifications@github.com> wrote:

> No worries. Please read over our CONTRIBUTING document before moving
> forward - knowing ahead of time whether you can sign the CLA or not is the
> biggest hurdle for some folks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/363#issuecomment-124726869>.
>


-- 
Kishan Bagaria
kishanbagaria.com
