### ISSUE TITLE
chocolatey.config updated on every command; causing subsequent system configuration issues

### ISSUE THREAD

**Issue by steve-hawkins** [chocolatey/choco#364]
I'm using Puppet to install and configure Chocolatey to point to our internal repositories, I noticed that Puppet was detecting drift on the ```C:\ProgramData\chocolatey\config\chocolatey.config``` file on every run.

I set the ```C:\ProgramData\chocolatey\config\chocolatey.config``` file to read-only and ran the following : -

```
C:\Users\...>choco -v
Error serializing type chocolatey.infrastructure.app.configuration.ConfigFileSettings:
 Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config' is denied.
Error updating 'C:\ProgramData\chocolatey\config\chocolatey.config'. Please ensure you have permissions to do so:
 Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config' is denied.
0.9.9.8
```

I don't see why Chocolatey needs to be updating the config file on every command execution, especially since it doesn't appear to be making any changes?

**Comment by ferventcoder** [comment]
I wonder if we already have an issue related to this. We have plans to not make changes to the file unless there are differences.

**Comment by ferventcoder** [comment]
Related to #355

**Comment by BeezUPJohnny** [comment]
+1
>choco list -lo
Error serializing type chocolatey.infrastructure.app.configuration.ConfigFileSettings:
 Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config' is denied.
Error updating 'C:\ProgramData\chocolatey\config\chocolatey.config'. Please ensure you have permissions to do so:
 Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config' is denied.
Chocolatey v0.9.9.8

**Comment by BeezUPJohnny** [comment]
+1 
choco list -lo
Error serializing type chocolatey.infrastructure.app.configuration.ConfigFileSettings:
Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config' is denied.
Error updating 'C:\ProgramData\chocolatey\config\chocolatey.config'. Please ensure you have permissions to do so:
Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config' is denied.
Chocolatey v0.9.9.8

**Comment by ferventcoder** [comment]
@BeezUPJohnny - as an FYI, run choco in an elevated shell to not see the message ever. :)

**Comment by BeezUPJohnny** [comment]
Works ! Thanks !
