### ISSUE TITLE
Exit with non-zero code if install/upgrade version and a newer version is installed

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#365]
If someone requests a specific version and we already have a newer version installed, choco should exit with a non-zero code as it doesn't actually install the older version.

This is related to https://github.com/chocolatey/puppet-chocolatey/issues/75

**Comment by ferventcoder** [comment]
This can be added as a switch that allows it to exit with non-zero. It depends on what default behavior should be.

**Comment by ferventcoder** [comment]
@steve-hawkins this will be in 0.9.9.9.

**Comment by ferventcoder** [comment]
To use this, it will throw an error on install/upgrade if you ask for an older version than you have installed. If you however want this particular behavior, use `--allow-downgrade` and choco will attempt the downgrade install. You can also use `--allow-multiple-versions` if you are installing multiple versions of a package side by side.

**Comment by steve-hawkins** [comment]
Awesome stuff!

I'll give this a go when 0.9.9.9 is available and let you know how I get on with the Puppet module

**Comment by laurchris** [comment]
Is there a way to use --allow-downgrade with Chocolatey provider in Puppet?

**Comment by ferventcoder** [comment]
@laurchris yes - add it to `install_options`

**Comment by ferventcoder** [comment]
See https://forge.puppetlabs.com/chocolatey/chocolatey#install_options for details

**Comment by laurchris** [comment]
Thank you!
