### ISSUE TITLE
Enhance Templates for 0.9.9.9

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#366]
* Uninstall template requires almost no work on the part of the user.

**Comment by dtgm** [comment]
:+1:

**Comment by ferventcoder** [comment]
Especially the parts for the uninstall being completely setup.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/commit/d45c3edf290e4c2b0cd2d591928d390f46c2b16c#commitcomment-12359514

**Comment by ferventcoder** [comment]
Follow up with https://github.com/chocolatey/choco/commit/d45c3edf290e4c2b0cd2d591928d390f46c2b16c#commitcomment-12359491
