### ISSUE TITLE
Fix file description of ShimGen shims

### ISSUE THREAD

**Issue by alexchandel** [chocolatey/choco#374]
Currently, although ShimGen does (usually) successfully get the icon, the file description is left "ShimGen generated shim" with author "RealDimensions Software, LLC". This is bad, because I can't make shortcuts to these. If I do, and I open a file with them, then Windows Explorer calls every single file of that type "ShimGen generated shim". Which just doesn't work for `.7z` files.

**Comment by ferventcoder** [comment]
Interesting, what makes it weird for 7z?

**Comment by alexchandel** [comment]
@ferventcoder lol only the order of magnitude: I have *lots* of `7z`/LZMA archives. Plus 7zip has all its file associations, so if I right click pretty much any zip or image, I saw the default option is to open it with `ShimGen generated shim`.

This originates from me creating shortcuts for most of the GUI programs in chocolatey/bin and sticking them in `C:\ProgramData\Microsoft\Windows\Start Menu\Programs` for easy access, only to discover that the start menu was full of `ShimGen generated shim`. Which was even more hilarious with Win10's giant tiles.

The workaround is to "shortcut" directly to the binary in chocolatey/lib/foo, but that doesn't always work, since there are a few packages whose subfolders change with versions (e.g. filezilla). And I feel like I'm defeating the purpose of my awesome common bin folder by doing that

**Comment by alexchandel** [comment]
It might be worth it to scrape the "Author"/"File version"/"Product name"/"Product version" keys as well, since those seem to be used in some places, and currently incorrectly refer to ShimGen's details.

If it's possible we could add a custom key like "ShimGen target" for informational purposes, which would also mark the exe as a ShimGen product.

**Comment by ferventcoder** [comment]
@alexchandel you mean pull that information out of the file itself if we find it? Sounds like a good enhancement.

**Comment by alexchandel** [comment]
@ferventcoder How can we go about changing the behavior of shimgen?

**Comment by ferventcoder** [comment]
If you know how to get to the file information, it would be good to note that in this ticket (or shimgen 17).

**Comment by aronovgj** [comment]
https://gallery.technet.microsoft.com/scriptcenter/get-file-meta-data-function-f9e8d804

should be what you are looking for i think

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/shimgen/issues/17

**Comment by ferventcoder** [comment]
This has been completed.

**Comment by ferventcoder** [comment]
Once it gets pulled in I will close this issue.
