### ISSUE TITLE
HKCU may not have Environment (Install of Chocolatey)

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#375]
Trying to install Chocolatey from the install script located here - https://chocolatey.org/install.ps1, and when run it looks like it is erroring out when trying to read and expand properties from the registry key 'HKCU:\Environment'.
This is possibly because I am doing this on a Windows Server 2012 R2 Core install and it does not have the registry key 'HKCU:\Environment'.

https://groups.google.com/d/msgid/chocolatey/e779ca75-3a14-4d61-a575-339802c59d1b%40googlegroups.com

**Comment by Ian2020** [comment]
Seen this on Server 2012 R2 Standard also. Can reproduce if any further information would help. The google groups link doesn't seem to work for me.

**Comment by ferventcoder** [comment]
@Ian2020 the link works after you've signed up for the group. We've had issues with Google not properly masking email addresses in the threads so we require you to join to cut down on spammers.
