### ISSUE TITLE
Typo: Wrong target noted in install - advanced

### ISSUE THREAD

**Issue by S466531257BOSS** [chocolatey/choco#380]
in the last section of your install - advanced advise ( installing by downloading package und unzip it ) you point out to switch to the ' package ' sub-folder and in there to run the powershell-script to install chocolatey .

This is wrong, instead the install-scripts are in the ' tools ' sub-folder .

Please correct that .

THANKS FOR YOUR INTEREST.

S466531257 BOSS
PAETH CLAUDIUSRAPHAEL

**Comment by pauby** [comment]
This was a very long time ago. However, I'm unsure what this issue relates to. I'm going to go ahead and close it but we can always reopen it again if necessary.
