### ISSUE TITLE
Mark packages pending until install completes successfully

### ISSUE THREAD

**Issue by opdude** [chocolatey/choco#383]
If you try and install a package and then you decide to cancel the installation or perhaps it was forced closed i.e process killed. Chocolatey then believes the package is installed when it's probably not. I believe we should only assume the package installed if we get to the end successfully rather than assume it works to begin with.

**Comment by ferventcoder** [comment]
Thinking we need something that tells choco a package was successful because it finished without issues. We can't change the folder unfortunately because nuget won't have the local packages information it needs.

**Comment by ferventcoder** [comment]
I also believe this may have already been suggested in a similar way.

**Comment by et1975** [comment]
+1. Considering most packages download stuff, which could easily fail, this is a problem when trying to automate "package is installed" state.

Can you elaborate on "nuget won't have the local packages information"? 
I might have to fix this and would appreciate any pointers/ideas.

**Comment by ferventcoder** [comment]
This is not marked up for grabs. I would hate for you to put in work we would not accept. I agree that it needs to happen, however the design of how we would do it isn't solid yet.

**Comment by ferventcoder** [comment]
I couldn't find the original "pending" issue, so this is it. This is also related to https://github.com/chocolatey/choco/issues/284

**Comment by ferventcoder** [comment]
Dupe of #198.

**Comment by ferventcoder** [comment]
Going to close this for #198.
