### ISSUE TITLE
Suggestion: order of priority for keeping care (updates, moderation) of packages

### ISSUE THREAD

**Issue by ghost** [chocolatey/choco#388]
Dear all,

I would like to suggest introducing a list of priority order for keeping care (like building and contributing updates, doing and supervising moderation, etc.) of packages.

Based on my (very own) current list of used choco apps this could look like:

```
clist -lo.priority due to security.txt

0 - Essential
-------------
chocolatey



1 - Highest priority (admin tools or security related programs):
----------------------------------------------------------------
7zip
adwcleaner
bdfilehash
bleachbit
boxcryptor
ccenhancer
ccleaner
chocolateyexplorer
dropbox
far
gpg4win
iiscrypto
jre8 --params "both=true"
jrt
keepass
keepass-langfiles
putty
recuva
speccy
sysinternals
teamviewer
testdisk-photorec



2 - High priority (common programs with internet or file access and a great impact):
------------------------------------------------------------------------------------
cyberduck
everything
freefilesync
ghostscript.app
hexedit
irfanview
irfanviewplugins
jitsi
libreoffice-help
libreoffice-oldstable
lili
notepadplusplus
palemoon
pdfcreator
sumatrapdf
thunderbird
vlc
waterfox
yumi



3 - Basic priority (other programms)
------------------------------------
audacity
calibre
cdrtfe
clementine
dia
digikam
docear
doxygen
gimp
hugin
infrarecorder
inkscape
jabref
kid3
languagetool
luminance
maxima
mediathekview
paint.net
prime95
projectlibre
pspp
r.project 
texstudio
```

Any comments, help and work appreciated. :-)

Gunner

**Comment by aronovgj** [comment]
sorry, don't quite get it. 

- either this is for moderation or for maintenance. ferventcoder et al. don't have any influence on maintainers. 

- most packages (at least the most important) are automatic packages. they run once every x hours or once a day or something and push stuff automatically. how would priorities help here? there is nothing to prioritize for the maintenance part.

- there is also a concept of trusted packages which some of the mentioned apps are a part of anyway. 

- why would packages like ccleaner/ccenhancer, dropbox or recuva be of highest priority? i don't see any reason why they couldn't wait for maintenance. 

- who decides which packages belong to which group?

**Comment by aronovgj** [comment]
also one issue would have been enough if you would have stated your proposals more precisely.

**Comment by gunnersson** [comment]
> sorry, don't quite get it.

Well, it was just an idea, just shortly written down. Not meant offensive.

>either this is for moderation or for maintenance. ferventcoder et al. don't have any influence on maintainers.

Could be for maintainers on the one hand or for moderation on the other hand. Depends...

> most packages (at least the most important) are automatic packages. they run once every x hours or once a day or something and push stuff automatically. how would priorities help here? there is nothing to prioritize for the maintenance part.

I'm not sure and haven't looked up exactly what packages are automatic packages. About 1/3 of my packages are not, obviously.

> there is also a concept of trusted packages which some of the mentioned apps are a part of anyway.

What does this mean? Haven't known before, sorry.

> why would packages like ccleaner/ccenhancer, dropbox or recuva be of highest priority? i don't see any reason why they couldn't wait for maintenance.
> who decides which packages belong to which group?

My post was just a suggestion, not a call of rules. It was something like an idea. I have been thinking about repositories of common Linux distributions which divide up to something like "essential/system", "internet and/or multimedia", "other programs", "alpha/beta/testing" for examples. I do know that there are different models of repository structures (like due to security, due to licence, due to purpose of program, due to dependencies, ...). Needs to be discussed.

Well, it needs to be/ could be discussed
* whether in general (is there some need for this priority sorting?)
* details how to (if yes to the upper question)

Sorry for any inconvenience or misunderstanding.

**Comment by aronovgj** [comment]
> Could be for maintainers on the one hand or for moderation on the other hand. Depends...

for moderation this may make sense. but how would this benefit maintainers? and how would you realize this? at the moment maintainers push whatever they want.

> What does this mean? Haven't known before, sorry.

if packages have been approved several times without issues they are approved as trusted packages, meaning they don't go through moderation process.

by the way maintainers can also go to gitter and ask for moderation if it is urgent. this will be handled pretty fast.

> My post was just a suggestion, not a call of rules. It was something like an idea. I have been thinking about repositories of common Linux distributions which divide up to something like "essential/system", "internet and/or multimedia", "other programs", "alpha/beta/testing" for examples. I do know that there are different models of repository structures (like due to security, due to licence, due to purpose of program, due to dependencies, ...). Needs to be discussed.

this absolutely could be useful but i don't see any basis for a discussion if you don't provide specific suggestions for what and how things should be done and reasons for or against them. only then we could really discuss if this even makes sense.

**Comment by gep13** [comment]
Based on the fact that there has been no further discussion on this topic, I am going to go ahead and close it out.  If there is additional conversation, we can open it up again.
