### ISSUE TITLE
Incorrect log4net version in chocolatey.lib dependencies

### ISSUE THREAD

**Issue by mwrock** [chocolatey/choco#390]
I have been building from source while testing usage of chocolatey.dll. I am able to call into it with no issue. Today I updated my build script to pull the dll from nuget.org. My script copies the chocolatey assembly along with the log4net assembly to my app directory. Now trying to instantiate types declared in the chocolatey dll yields exceptions complaining that it cannot find log4net v 1.2.13.0 which is indeed what the chocolatey assembly is compiled with. However, the chocolatey.lib nuspec declares its dependency against 1.2.10.

**Comment by ferventcoder** [comment]
Merged into master, which means 0.9.10. If you want to target 0.9.9 series, submit against stable branch. :)

**Comment by mwrock** [comment]
thats cool. I changed my build script to grab that specific log4net version s oI'm good until 0.9.10. Thanks!!

**Comment by ferventcoder** [comment]
Merged into master at https://github.com/chocolatey/choco/commit/6b63f79a9b410f17e23919db64ecdd88375ee033
