### ISSUE TITLE
Merging assemblies on a machine running .net 4.5 or higher produces binaries incompatible with .net  4.0

### ISSUE THREAD

**Issue by mwrock** [chocolatey/choco#392]
Using either source built binaries on my machine (running 4.5.1) or the binaries provided by nuget result in assembly load errors when executed on a windows 2k8R2 machine after installing .net 4.0.

This can be fixed by either installing .net4.5 on the target machine or, preferably, informing ILMerge of the location of the 4.0 reference assemblies.

**Comment by mwrock** [comment]
See http://www.hurryupandwait.io/blog/what-you-should-know-about-running-ilmerge-on-net-4-5-assemblies-targeting-net-4-0 for far too many details

**Comment by ferventcoder** [comment]
Merged into master at https://github.com/chocolatey/choco/commit/3dcd195b94bf6e6ed9a19b8b3bab8c441cb21dd0.
