### ISSUE TITLE
CLA Link on Wiki Does Not Resolve

### ISSUE THREAD

**Issue by kevindaub** [chocolatey/choco#394]
https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md

Bad Link: https://www.clahub.com/agreements/chocolatey/choco

It looks like CLA Hub might be dying or dead clahub/clahub#111

Suggest moving over to https://cla-assistant.io/

**Comment by ferventcoder** [comment]
Oh no. Thanks for the heads up. I'll need to get the users who have signed out. I have a copy of the agreement so I'm not as worried about recreating that aspect.

**Comment by ferventcoder** [comment]
@kevindaub looks like it is back up again (for now).

**Comment by ferventcoder** [comment]
I am not completely certain we'd go hosted this time, I think we would take the CLA assistant and set it up ourselves on a paid heroku instance - 

The app asks for write permission for gists, I'm not sure I like that.
![image](https://cloud.githubusercontent.com/assets/63502/9443048/9e155e50-4a44-11e5-86a6-eb556d93a6a9.png)


It does appear that the setup is not super difficult. https://github.com/cla-assistant/cla-assistant

**Comment by ferventcoder** [comment]
Also, more information than github user name is required - https://github.com/cla-assistant/cla-assistant/issues/64

**Comment by ferventcoder** [comment]
I also really want the multiple repos, one cla issue to be solved - https://github.com/cla-assistant/cla-assistant/issues/62

**Comment by ferventcoder** [comment]
For the permissions, I followed up with a question at https://github.com/cla-assistant/cla-assistant/issues/65

**Comment by ferventcoder** [comment]
This was resolved awhile ago, closing this on triage.
