### ISSUE TITLE
Be explicit in permissions

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#398]
https://github.com/chocolatey/choco/blob/master/nuget/chocolatey/tools/chocolateysetup.psm1#L174-L186

http://stackoverflow.com/questions/10970957/changing-permissions-with-powershell-doesnt-propogate-to-children

A non-admin can write to the programdata folder, but they cannot modify or append to existing files. They are also not able to delete existing files they did not put there (and possibly not even those files).

Lock down the default folder even more so that by default, non-admins can not even write to the folder.

**Comment by ferventcoder** [comment]
Another place to see some examples of acl setting came in an interesting unrelated search http://blog.enowsoftware.com/solutions-engine/bid/185867/Powershell-Upping-your-Parameter-Validation-Game-with-Dynamic-Parameters-Part-II

**Comment by ferventcoder** [comment]
The install now removes inheritance when installed to the default location and explicitly sets permissions for Administrators/LocalSystem to have Full control, and Users to ReadExecute. Additionally by default it still grants current user Modify rights, but that will be removed in v1.

To restrict to only admins in 0.9.10, set `$env:ChocolateyAdminOnlyInstall="true"` prior to install/upgrade of Chocolatey.

**Comment by ferventcoder** [comment]
Actually switch that - we can break things across boundaries. This is one of them.

**Comment by ferventcoder** [comment]
`$env:ChocolateyInstallAllowCurrentUser="true"` to set current user modify access

**Comment by Justin-dev436** [comment]
``
