### ISSUE TITLE
Support for client certificates

### ISSUE THREAD

**Issue by et1975** [chocolatey/choco#399]
I don't see any way to configure choco with a client certificate for authentication with a server.
Both apt-get and yum support this, so would be nice if choco could do the same.

**Comment by ferventcoder** [comment]
It sounds like something that we could do.

**Comment by ferventcoder** [comment]
Perhaps you can elaborate more in how you would see the user experience of this feature.

**Comment by et1975** [comment]
I'm thinking an attribute for a repo/source that specifies the PFX file:
```
choco source add -n=bob -s"https://somewhere/out/there/api/v2/" -c=\users\bob\client.pfx
```

**Comment by ferventcoder** [comment]
Does the source need to support public / private key auth then as well?

**Comment by et1975** [comment]
Yes, on top of HTTPS the server would be configured to require a client certificate.
I'll see about setting up a Docker container to test against, assuming I can get a self-hosted choco repo going on mono/linux.

**Comment by ferventcoder** [comment]
It all depends on the server - I'm sure something like Nexus or Artifactory probably already support that, but not sure if they do with NuGet packages.

**Comment by ferventcoder** [comment]
Similar to #403.

**Comment by ferventcoder** [comment]
Fixed up and merged into stable at https://github.com/chocolatey/choco/commit/026df767592f253aae0ec2a5fcf0b29c794af693
