### ISSUE TITLE
Choco upgrade not downloading new installer if current installer is the same size.

### ISSUE THREAD

**Issue by timbrown5** [chocolatey/choco#405]
As discussed here:
https://groups.google.com/d/msgid/chocolatey/9159c198-6103-4679-839c-9eb3de639628%40googlegroups.com?utm_medium=email&utm_source=footer

If an already installed chocolatey package is the same size as the one in the cache, chocolatey does not download the new installer, and so the wrong version is installed.

The end result is that chocolatey think it has updated the package, but has just re-installed the version already on the system.

**Comment by ferventcoder** [comment]
This should hopefully be corrected by downloading each installer to a subfolder with the version. And using the original name of the file (I thought we had an issue filed on these, but apparently not over in choco, perhaps still in the older chocolatey repo).
