### ISSUE TITLE
If the package uses $packageParameters instead of $env:PackageParameters, quotes are removed

### ISSUE THREAD

**Issue by dhilgarth** [chocolatey/choco#406]
I am trying to pass quoted values to the `-params` switch, but it looks like it is simply not working.

In a test package, I am simply outputting `$packageParameters` to see what I get.

Here is what I tried:

- `-params '/licenseName:""Daniel Hilgarth""'`
- `-params '"/licenseName:""Daniel Hilgarth"""'`
- `-params '"/licenseName:"Daniel Hilgarth""'`
- `-params '/licenseName:"Daniel Hilgarth"'`
- `-params "/licenseName:""Daniel Hilgarth"""`

Both of them resulted in a `$packageParameters` value fof `/licenseName:Daniel Hilgarth`

Additionally, I tried these:

- `-params '"/licenseName:\"Daniel Hilgarth\""'` -> Resulted in the message that choco wants to install two packages: `<package-name>;Hilgarth`
- ``-params '"/licenseName:`"Daniel Hilgarth`""'`` -> Result: ``/licenseName:`Daniel Hilgarth```

I have the feeling that this is a bug in chocolatey's parameters parsing

**Comment by ferventcoder** [comment]
Did you read the wiki/`choco --help` on how to pass options with quotes?

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/wiki/CommandsReference#how-to-pass-options--switches

**Comment by ferventcoder** [comment]
It's very specific on how to do this:

* **Pass quotes in arguments**: When you need to pass quoted values to
   to something like a native installer, you are in for a world of fun. In
   cmd.exe you must pass it like this: `-ia "/yo=""Spaces spaces"""`. In 
   PowerShell.exe, you must pass it like this: `-ia '/yo=""Spaces spaces""'`.
   No other combination will work. In PowerShell.exe if you are on version 
   v3+, you can try `--%` before `-ia` to just pass the args through as is,
   which means it should not require any special workarounds.

**Comment by ferventcoder** [comment]
The above applies to any option, not just install args.

**Comment by dhilgarth** [comment]
Yes. Did you check the samples I posted? :-) Both of them I have tested and they did not work.

**Comment by ferventcoder** [comment]
I did, I believe you are in PowerShell and you need `-params '/licenseName:""Daniel Hilgarth""'`

I didn't see it in the sample set.

**Comment by dhilgarth** [comment]
It's the very first thing in the list of things I tried :)

**Comment by ferventcoder** [comment]
What version of choco?

**Comment by dhilgarth** [comment]
v0.9.9.8

**Comment by ferventcoder** [comment]
Can you post a gist of the log file (relevant bits)?

**Comment by ferventcoder** [comment]
I'm guessing a bug :)

**Comment by ferventcoder** [comment]
Apologies, I've gotten this question about how to pass arguments quite a few times, I default to passing back the wiki article

**Comment by dhilgarth** [comment]
Don't worry, I understand that you have to process issues very quickly.

Here is the gist:  
https://gist.github.com/dhilgarth/77ce8e452d17375a3bc5

It contains the complete log for the test with `-params '/licenseName:""Daniel Hilgarth""'`

**Comment by ferventcoder** [comment]
You know what - I'm guessing that something in the way this gets passed back to powershell may be doing something weird - look at line 128 https://gist.github.com/dhilgarth/77ce8e452d17375a3bc5#file-chocolatey-log-L128 (it's still passed with quotes).

**Comment by dhilgarth** [comment]
Yes, that is the reason. I built a batch script to automatically pull down my boxstarter configuration etc. from a private git repository and I went nuts figuring out the quote escaping of the `-Command` parameter. Most likely, you need to escape the quotes. Depending on how you actually call the command, either by `\"` or by ```"``.

Here is my batch script as an example:

```
PowerShell -ExecutionPolicy Unrestricted -NoExit -Command $cloneScriptFolder = (join-path (gi $env:temp).FullName \"boxstarter\"); $cloneScript = (join-path $cloneScriptFolder \"clone.ps1\"); md $cloneScriptFolder -Force; wget http://downloads.fire-development.com/clone.ps1 -OutFile $cloneScript; $quotedCloneScript = '\"{0}\"' -f $cloneScript; Start-Process PowerShell -Verb RunAs -ArgumentList \"-ExecutionPolicy Unrestricted -NoExit -File $quotedCloneScript\"
```

**Comment by ferventcoder** [comment]
It looks like the issue is right here - https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/services/PowershellService.cs#L116-L117.

InstallArgs doesn't really suffer because it is also passed as an environment variable and is used later by chocolatey itself.

The package itself should probably be using `$env:PackageParameters` instead of `$packageParameters`. We should still fix this though.

**Comment by ferventcoder** [comment]
@dhilgarth we commented at almost the same time. :)

**Comment by dhilgarth** [comment]
I noticed :) I agree, that is where the quote escaping should happen.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/services/PowershellService.cs#L181

**Comment by ferventcoder** [comment]
@dhilgarth if you feel comfortable providing a PR, I'd accept escaping quotes as `` `" ``

**Comment by dhilgarth** [comment]
Not sure that is correct. Would need to test.

**Comment by ferventcoder** [comment]
But I dropped the priority since the package isn't following the recommendations of what to use. https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/templates/ChocolateyReadMeTemplate.cs#L92

**Comment by dhilgarth** [comment]
Indeed. I missed that - I just copied the code from somewhere, but I forgot from where. Maybe I simply missed that line that assigned the environment variable to the local variable.

**Comment by ferventcoder** [comment]
Looks like the escape needed to be `\"`
