### ISSUE TITLE
Documentation Fixes for 0.9.9

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#41]

**Comment by ferventcoder** [comment]
This is pretty much done besides finishing the release notes. @gep13 Would you mind reviewing the wiki and giving a thumbs up or down?

**Comment by gep13** [comment]
@ferventcoder yip, will do.

**Comment by ferventcoder** [comment]
This should be done.

**Comment by ferventcoder** [comment]
@gep13 if you are happy with it as well, please close this issue.

**Comment by gep13** [comment]
There are still some outstanding formatting issues with the Helper/Function sections of the wiki, but all the content is there, so I have no issue with closing this out.  I have a note to finish up the formatting over the next couple days.
