### ISSUE TITLE
cpack path/to/nuspec not working

### ISSUE THREAD

**Issue by dhilgarth** [chocolatey/choco#411]
Specifying the path to the nuspec file when calling cpack doesn't work.

cpack will report that it can't find the files specified in the nuspec file because it is looking in the current working directory and not in the folder the nuspec file is in.

Examples:

```
c:\packages\automatic\_output>cpack balsamiqmockups3\3.1.9\BalsamiqMockups3.nuspec
Chocolatey v0.9.9.2
Could not find a part of the path 'c:\packages\automatic\_output\tools'.

c:\packages\automatic\_output>cpack c:\packages\automatic\_output\balsamiqmockups3\3.1.9\BalsamiqMockups3.nuspec
Chocolatey v0.9.9.2
Could not find a part of the path 'c:\packages\automatic\_output\tools'.
```

**Comment by dhilgarth** [comment]
Looks like it has been fixed in the meantime. Updating to 0.9.9.8 solved it.

**Comment by ferventcoder** [comment]
Yes, this was fixed awhile ago. :)

**Comment by dhilgarth** [comment]
Sorry about that. I just realized the version number after I posted the issue. Too many machines with Chocolatey... :-)
Is there some way for chocolatey to tell me periodically that there are updates to my installed applications?

**Comment by ferventcoder** [comment]
Duplicate of #232

**Comment by aronovgj** [comment]
@dhilgarth there is `choco outdated` or `cup --noop`. you could schedule one of those in a script to be performed regularly, intercepting the output and notifying you about updates.
