### ISSUE TITLE
Provide PowerShell tab completion for Chocolatey

### ISSUE THREAD

**Issue by dhilgarth** [chocolatey/choco#412]
Please provide PowerShell tab completion for chocolatey

- [x] For package names
- [x] For commands and options
- [x] Need the installer to put in the profile setting.
- [x] Need the profile setting to work appropriately.
- [x] Investigate if setting the profile is something to do in Posh v2 only. If so, set up for adding to PSModulePath.

**Comment by aronovgj** [comment]
https://github.com/chocolatey/chocolatey/issues/645

**Comment by dhilgarth** [comment]
It's a bit confusing with two repositories...

**Comment by ferventcoder** [comment]
Yes, it is a bit confusing - the ones in chocolatey/chocolatey either get fixed just as a result of not being written in PowerShell or get migrated over to here. In this case migrated. :)

**Comment by ferventcoder** [comment]
Well, you may have missed it but - https://twitter.com/ferventcoder/status/711530331879309312.

**Comment by ferventcoder** [comment]
Still need the installer to put in the profile options

**Comment by ferventcoder** [comment]
To play with this, install the latest beta and run `Import-Module “$env:ChocolateyInstall\helpers\chocolateyProfile.psm1” -Force` in the shell you want to try this feature in.

**Comment by ferventcoder** [comment]
Decided to punt on Posh v2 support. This is not a core feature, but an enhancement. So if someone can get this working with POSH v2, I'd accept the PR. I'm just not going to work on making it work.

**Comment by szachara** [comment]
I have installed `Chocolatey v0.10.3` but tab completion doesn't work for me, but I tried import module like is written above `Import-Module “$env:ChocolateyInstall\helpers\chocolateyProfile.psm1” -Force` and it works really good, how to do this permanent?

**Comment by ferventcoder** [comment]
#833, #894, #991 are related. 

@szachara what you are looking for is noted at https://github.com/chocolatey/choco/issues/894#issuecomment-240156742

**Comment by szachara** [comment]
Thx, I try it later and let know at #894
