### ISSUE TITLE
Silent Install

### ISSUE THREAD

**Issue by ggcooper** [chocolatey/choco#413]
In attempting to install chocolatey with powershell DSC, the install failed because install.ps1 uses write-host; which can't be used in background.

There are alternate ways to install, but it would be great if it supported "silent" install.

**Comment by ferventcoder** [comment]
Define silent. :)

**Comment by ferventcoder** [comment]
@ggcooper ping.

**Comment by ggcooper** [comment]
pong

**Comment by ferventcoder** [comment]
@ggcooper Define what you mean by silent here.

**Comment by ggcooper** [comment]
https://en.wikipedia.org/wiki/Installation_(computer_programs)#Silent_installation

https://en.wikipedia.org/wiki/Installation_(computer_programs)#Unattended_installation

https://en.wikipedia.org/wiki/Installation_(computer_programs)#Headless_installation

by calling "write-host", the script assumes a user at a console.  DSC uses WMI to install packages which is independent of "console".  I believe, simply changing instances of Write-Host to Write-Verbose will allow DSC to install with your package.

**Comment by pauby** [comment]
I'm going to go ahead and close this, but we can reopen it if necessary.
