### ISSUE TITLE
Documentation: Implement rules for using the temporary folder

### ISSUE THREAD

**Issue by dhilgarth** [chocolatey/choco#415]
I now have had multiple occasions where an incorrect usage of `$env:TEMP` caused the package installation to fail.

There are two problems associated with directly using `$env:TEMP`:
1. It might contain a space. Oftentimes, a path containing  the value is passed without quotes as a command line argument
2. It might be in 8.3 notation which is apparently not understood by all PowerShell commands and is also causing problems for some installers like the one of MS SQL Server 2014 Management Studio Express.

The documentation should insist on using `(Get-Item $env:TEMP).FullName` instead of simply `$env:TEMP` and it should also remember people to properly quote paths passed as command line arguments.

**Comment by aronovgj** [comment]
path might also have non-latin characters which would cause it to fail. someone reported this after one of my packages couldn't install. now i unpack my stuff in the package folder and not in temp.

**Comment by dhilgarth** [comment]
This just emphasizes the need for documentation on what to use as the temporary path. I think some consistency is needed here.

**Comment by ferventcoder** [comment]
Bug or enhancement?

**Comment by dhilgarth** [comment]
Bug. Packages fail to install because of this

**Comment by ferventcoder** [comment]
This may be fixed now.

**Comment by ferventcoder** [comment]
About to find out.

**Comment by ferventcoder** [comment]
It won't require a documentation change either. Chocolatey tells the executing scripts what the TEMP variable is, so we fix it to providing the full path and things are good. For spaces however, I'm not yet sure how that should be handled.

**Comment by ferventcoder** [comment]
I'm going to create a new issue for not using 8.3 path for temp variable.

**Comment by ferventcoder** [comment]
Also, the temp variable is controlled by the chocolatey cacheLocation setting - it defaults to TEMP when it is not set. You should have folks set that if they have issues with latin characters @aronovgj. I think that this fix I'm about to implement may fix both avenues.

**Comment by ferventcoder** [comment]
This documentation may not be required.

**Comment by ferventcoder** [comment]
I just pushed the latest beta - it should be available within about an hour or so after the verifier and the validator run. If you can give it a shot and see if this is still an issue - I will close this as not needed due to the fixes in #532. 

https://chocolatey.org/packages/chocolatey/0.9.10-beta-20160111

If you find this is still an issue, we can reopen this for documentation purposes (or evaluate our options).

**Comment by dhilgarth** [comment]
Not sure, I understand what happened here? Has some documentation been added to explain how to handle temporary paths? What's with the `cacheLocation` setting? First time I hear about it.

Maybe my issue was unclear? Many script internally use `$env:TEMP` to extract a downloaded zip file to a temporary location. Not sure how the `cacheLocation` command line switch plays into this.

**Comment by ferventcoder** [comment]
> Many script internally use `$env:TEMP` to extract a downloaded zip file to a temporary location. Not sure how the `cacheLocation` command line switch plays into this.

I guess a little explanation is in order. We set the TEMP environment variable before we let a package script run. We either set it to the actual TEMP location, or to `cacheLocation` as specified from the configuration. In #532, I fixed the issue of it using a short 8.3 path.

**Comment by ferventcoder** [comment]
You can see the changes and possibly get a better understanding if you take a look at https://github.com/chocolatey/choco/commit/76ae7e2f77787a85dced1f485fc631459582fc63
