### ISSUE TITLE
ChocoInstaller export cmdlets

### ISSUE THREAD

**Issue by Stevenpc3** [chocolatey/choco#422]
I am trying to add a cmdlet as an extension.  Perhaps I am doing it wrong, but my cmdlet gets imported by chocoInstaller but is never exported.  This line shows that and a run with debug also shows that.

Export-ModuleMember -Function * -Alias *

This should be 

Export-ModuleMember -Function * -Alias * -Cmdlet *

**Comment by ferventcoder** [comment]
You are correct.

**Comment by ferventcoder** [comment]
We can throw that into the upcoming release. It's a tiny fix. If you want to do a PR for it, make sure you target stable branch.

**Comment by ferventcoder** [comment]
:shipit:
