### ISSUE TITLE
Use the actual download file name instead of providing one

### ISSUE THREAD

**Issue by aronovgj** [chocolatey/choco#435]
Installers might not like being renamed to `packagenameInstall.exe` when being downloaded to temporary folder. MiKTeX for example failed to install with a differently named installer.

Migrated from https://github.com/chocolatey/chocolatey/issues/538

**Comment by ferventcoder** [comment]
MSIs also hate it.

**Comment by ferventcoder** [comment]
You and @DarwinJS will be so happy to see this fixed.

**Comment by DarwinJS** [comment]
Awesome!

**Comment by aronovgj** [comment]
I will be happy to see it in the stable so that I can change the miktex package. Or I'll just leave it as it is. Doesn't hurt anyone after all.
