### ISSUE TITLE
MSIexec syntax - auto uninstall

### ISSUE THREAD

**Issue by AeliusSaionji** [chocolatey/choco#438]
Uninstall-ChocolateyPackage calls msiexec in this fashion:
`[ERROR] Running msiexec with /x {DF3A46D9-67B3-44B2-9D01-25C8BA772C8A} /qn /norestart  was not successful. Exit code was '1603'`

On my machine, msiexec will not run with this syntax. Registry entries have shown me the correct UninstallString:
1) There can be no space between /X and the msiguid- on my PC (Windows 10) it needs to be `msiexec "/x{DF3A46D9-67B3-44B2-9D01-25C8BA772C8A}"`
2) The guid must be enclosed in quotations, separate from other switches.

By calling msiexec directly from the command line, I've determined that the full working command is `msiexec "/x{DF3A46D9-67B3-44B2-9D01-25C8BA772C8A}" /qn /norestart`

Here's the relevant error from the log, which indicates this might be related to me running a user account (mentioned here https://github.com/chocolatey/choco/issues/434)

``` powershell
 [ERROR] Running msiexec with /x {DF3A46D9-67B3-44B2-9D01-25C8BA772C8A} /qn /norestart  was not successful. Exit code was '1603' Error Message:
 .
 At C:\ProgramData\chocolatey\helpers\functions\Start-ChocolateyProcessAsAdmin.ps1:92 char:5
 +     throw $errorMessage
 +     ~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : OperationStopped: ([ERROR] Running...or Message:
 .:String) [], RuntimeException
     + FullyQualifiedErrorId : [ERROR] Running msiexec with /x {DF3A46D9-67B3-44B2-9D01-25C8BA772C8A} /qn /norestart  was not successful. Exit code was '1603' Error Message:
paint.net uninstall not successful.
 .
Error while running 'C:\ProgramData\chocolatey\lib\paint.net\tools\chocolateyuninstall.ps1'.
 See log for details.
paint.net not uninstalled. An error occurred during uninstall:
 paint.net uninstall not successful.
```

**Comment by Link-Satonaka** [comment]
OK, I don't know why but 2) is not strictly necessary. In fact, when using Start-Process, if you try 2) it will not work.

**Comment by ferventcoder** [comment]
Windows 10 as well here?

**Comment by Link-Satonaka** [comment]
Yep

**Comment by ferventcoder** [comment]
Do me a favor. Flip on autouninstaller and see if it behaves correctly without an uninstall script.

`choco feature enable -n autouninstaller`

**Comment by Link-Satonaka** [comment]
`Skipping auto uninstaller - No registry snapshot.`
Is there something I can do to get a registry snapshot?

**Comment by ferventcoder** [comment]
Yes, install it with at least it installing a different version that what is already installed. You may need to uninstall it manually first if the versions match.

**Comment by Link-Satonaka** [comment]
```powershell
paint.net v4.0.6
 Running auto uninstaller...
Sleeping for 2 seconds to allow Windows to finish cleaning up.
 Preparing uninstall key 'MsiExec.exe /X{DF3A46D9-67B3-44B2-9D01-25C8BA772C8A}'
 Uninstaller path is 'MsiExec.exe'
 Installer type is 'MsiInstaller'
 Setting up uninstall logging directory at C:\Users\Link\AppData\Local\Temp\chocolatey\paint.net\4.0.6
 Args are ' /X{DF3A46D9-67B3-44B2-9D01-25C8BA772C8A} /qn /norestart '
Calling command ['"MsiExec.exe" /X{DF3A46D9-67B3-44B2-9D01-25C8BA772C8A} /qn /norestart']
Command ['"MsiExec.exe" /X{DF3A46D9-67B3-44B2-9D01-25C8BA772C8A} /qn /norestart'] exited with '1603'
 Auto uninstaller failed. Please remove machine installation manually.
 Exit code was 1603
```

The auto uninstaller works when run from an administrative powershell

**Comment by ferventcoder** [comment]
Interesting. SO quotes are necessary then??!

**Comment by ferventcoder** [comment]
Oh, wait. ALWAYS run choco from administrative command shells. Unless you've installed it somewhere specific that doesn't require admin permissions to write to.

**Comment by Link-Satonaka** [comment]
>ALWAYS run choco from administrative command shells

I've followed this advice and run into a fundamental problem- look at the chromium package. It installs into %APPDATA%, and is therefore entirely inaccessible to my user account.

**Comment by pauby** [comment]
I'm unsure what we need to do here given the [comment above](https://github.com/chocolatey/choco/issues/438#issuecomment-144537872). It feels like Chocolatey CLI is being used in a non-admin context, which is causing the issue.

This is 8 and a half years old at this point but I'll ask - @AeliusSaionji can you provide any more information here?

**Comment by AeliusSaionji** [comment]
I have no memory of this, unfortunately.

Seems possible that this could affect portable choco installs, which are definitionally non-admin.
