### ISSUE TITLE
Allow hashing files for checksums with FIPS compliant algorithms

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#446]
https://groups.google.com/d/msgid/chocolatey/b5ce3f6e-228e-4947-be17-0dd201e05716%40googlegroups.com?utm_medium=email&utm_source=footer

> I'm encountering errors using chocolatey on systems with FIPS Algorithm Policy enabled. The setting can be found in the registry if:
>    HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\fipsalgorithmpolicy
> is set to 1
> 
> It can also be configured via the Policy Editor at:
>    Local Policies > Security Options > System Cryptography: Use FIPS compliant algorithms for encryption, hashing, and signing
> 
> It appears that chocolatey is attempting to use MD5 for some operation which isn't allowed in this configuration.

You may see this with the error: `Error deserializing response of type chocolatey.infrastructure.app.configuration.ConfigFileSettings`.

**Comment by octaviandum** [comment]
Hi there, 

We are having this issue at our organization.  Is there any chance that this will be fixed to be a FIPS compliant hashing algorithm in the future?

**Comment by ferventcoder** [comment]
Note the milestone on the right. Note that is the next version. :)

**Comment by ferventcoder** [comment]
In 0.9.10, set feature flag `useFipsCompliantChecksums`.

`choco config feature enable -n useFipsCompliantChecksums`.

**Comment by ferventcoder** [comment]
This was not made a default as it could have undesirable effects. Since everything choco is doing is related to setting and verifying checksums, it really isn't part of what FIPS was meant to combat and isn't out of compliance by using them. However, it's still a good idea to allow folks to have a stronger checksum algorithm.

**Comment by arinzemomife** [comment]
Please how can I fix this error:    "The registered delegate for type IXmlService threw an exception. The registered delegate for type IHashProvider threw an exce
ption. Exception has been thrown by the target of an invocation."
