### ISSUE TITLE
Add possibility to set a default output folder for choco new

### ISSUE THREAD

**Issue by aronovgj** [chocolatey/choco#448]
Because people may be too lazy to `cd` to their packages folder before doing `choco new`.

**Comment by ferventcoder** [comment]
Perhaps an output path as well?

**Comment by laedit** [comment]
Since I'm adding an outputdirectory option for choco pack (#598), I will add the same for choco new if it's ok for you.

**Comment by ferventcoder** [comment]
It's fine for new as well.
