### ISSUE TITLE
GitHub Org Icon Border

### ISSUE THREAD

**Issue by wjk** [chocolatey/choco#451]
I noticed that the icon for the Chocolatey GitHub org has a black border around it (see attached screenshot). I am using Safari 9.0 on OS X 10.11.

![Chocolatey Org Icon](https://cloud.githubusercontent.com/assets/1915951/10263745/260d9dc6-69c7-11e5-98ab-b1f26ab9eb20.png)

**Comment by ferventcoder** [comment]
Can you explain the issue?

**Comment by wjk** [comment]
Sorry. I just remembered that the icon didn’t have a black border around it before, and that (in my opinion) this black border looks bad. Was this change intentional?

**Comment by aronovgj** [comment]
https://avatars0.githubusercontent.com/u/811025?v=3&s=200
isn't black border how it is supposed to be?

**Comment by ferventcoder** [comment]
Hmm - it was intentional but I can go back to the transparent background

**Comment by ferventcoder** [comment]
Should update soon back to the transparent background image.

**Comment by ferventcoder** [comment]
Thanks @wjk! Next time you run into something similar to this, would you be against starting with a question on gitter or in email? Gitter response time is typically as quick or quicker than github. Plus I don't have a need to triage the issue (e.g. Document why the ticket is closed). :)
