### ISSUE TITLE
Choco list should have exact filter search

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#453]
https://groups.google.com/d/msgid/chocolatey/d2cb4b58-1a0f-4eaf-ba99-e6770a5feb8d%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by RichiCoder1** [comment]
This wouldn't, in theory, be hard to do.

**Comment by epidemicz** [comment]
I have this working at the moment, but I guess I need to make tests for it.. not familiar with that yet, but I'll be looking into it.

Currently looks like this:
`choco list nodejs -me`  

Using -me for "match exact," but open to suggestion if anybody else has a better idea.

**Comment by ferventcoder** [comment]
--exact. For a short name, is -e available?

**Comment by epidemicz** [comment]
Okay, thanks, that does sounds better and `-e` looks like it is available too.

I'm going to try to hook up some tests and hopefully submit a pull request soon.

**Comment by ferventcoder** [comment]
:+1:
