### ISSUE TITLE
Pro+ - Bitrate limit packages and downloads

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#454]

**Comment by DarwinJS** [comment]
This is extremely hard to do if you try to do it in proportion to **percent of current on the wire available bandwidth** - I have some PowerShell code I roughed out once - but handling the issue sufficiently gets deep fast.

One exception - just leverage bits - a known working implementation that services billions with Windows Updates.  There is *NOT* even COM automation over bits - but there are some CMD scrapers written in PSH.

**Comment by ferventcoder** [comment]
I've already done research on this aspect and came to the same conclusion.

**Comment by DarwinJS** [comment]
@ferventcoder - you are the Thor of github responses - lightning fast :+1:

**Comment by ferventcoder** [comment]
only when I'm awake. :)

**Comment by DarwinJS** [comment]
It get's really tough with server memory caching, disk caching and caching appliances to get a true "first pull" bandwidth read on the live wire.  So a first pull "metric" pull directly from the EXACT server you'll pull the rest from *might* give a read on end to end bandwidth - but then the object you did the metric with is cached in many places - complicating testing of accurate bandwidth measuring immensely.

**Comment by ferventcoder** [comment]
This will require changes made in 0.10.4 but will be in licensed editions starting at 1.10.0.
