### ISSUE TITLE
More info in summary after upgrades

### ISSUE THREAD

**Issue by aronovgj** [chocolatey/choco#455]
After `cup all -pre --noop` we get something like this:

    Chocolatey can upgrade 1/139 package(s).
     8 package(s) had warnings.
     See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    Warnings:
     - praatcon
     - chromium
     - hitmanpro
     - pidgin-otr
     - 4t-tray-minimizer
     - powershell
     - github
     - keyboard-layout-creator

I'd like a little more info. Something like this:

    Chocolatey can upgrade 1/139 package(s).
    - javaruntime | 8.0.40 -> 8.0.51
     8 package(s) had warnings.
     See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    Warnings:
     - praatcon | not in source list
     - chromium | pinned; skipped
     - hitmanpro | not in source list
     - pidgin-otr | not in source list
     - 4t-tray-minimizer | not in source list
     - powershell | pinned; skipped
     - github | pinned; skipped
     - keyboard-layout-creator | not in source list

Else I find the summary to be pretty useless.

Probably another issue but there should be a distinction between not actually being in the source list and being in the source list while not yet being moderated the first time.

**Comment by RichiCoder1** [comment]
So an improved version of `choco upgrade all --noop -verbose`?

**Comment by aronovgj** [comment]
`--verbose` does not have any effect on cup as far as I see it (don't have any packages to upgrade at the moment so they might return more info when they're upgraded). I'm concerned with the summary at the end of the output which should be more informative. I actually don't care so much that a hundred packages are `the latest version available based on your source(s).`. I'm interested in which of them are the exception to what *should* be the state of every package (being up to date).

**Comment by ferventcoder** [comment]
This was completed as part of #735.

**Comment by aronovgj** [comment]
No summary showing which packages were upgraded? I still only see warnings (and I like how they look now).

**Comment by ferventcoder** [comment]
@aronovgj I'm not sure what you mean.

Are you saying you want a summary of the packages that were upgraded?

**Comment by aronovgj** [comment]
Yes

**Comment by aronovgj** [comment]
As in
```
Chocolatey can upgrade 1/139 package(s).
- javaruntime | 8.0.40 -> 8.0.51
```

**Comment by ferventcoder** [comment]
I didn't see that in the issue context - however it does sound like a pretty good idea - please file a new ticket. Thanks!

**Comment by ferventcoder** [comment]
clarification - I see it now (I didn't see it originally).
