### ISSUE TITLE
choco install chef issue

### ISSUE THREAD

**Issue by mkianpour** [chocolatey/choco#456]
chocolatey cookbook used to work but since last release it can not install chocolatey on windows 2012 r2. 
this is the error:
==> win2012:       code "    powershell -noprofile -inputformat none -noninteractive -executionpolicy bypass -EncodedCommand IAAgACQAdwBjACAAPQAgAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0AAoAIAAgACQAdwBwAD0AWwBzAHkAcwB0AGUAbQAuAG4AZQB0AC4AVwBlAGIAUAByAG8AeAB5AF0AOgA6AEcAZQB0AEQAZQBmAGEAdQBsAHQAUAByAG8AeAB5ACgAKQAKACAAIAAkAHcAcAAuAFUAcwBlAEQAZQBmAGEAdQBsAHQAQwByAGUAZABlAG4AdABpAGEAbABzAD0AJAB0AHIAdQBlAAoAIAAgACQAdwBjAC4AUAByAG8AeAB5AD0AJAB3AHAACgAgACAASQBuAHYAbwBrAGUALQBFAHgAcAByAGUAcwBzAGkAbwBuACAAKAAkAHcAYwAuAEQAbwB3AG4AbABvAGEAZABTAHQAcgBpAG4AZwAoACcAaAB0AHQAcABzADoALwAvAGMAaABvAGMAbwBsAGEAdABlAHkALgBvAHIAZwAvAGkAbgBzAHQAYQBsAGwALQBsAGEAcwB0AHAAbwBzAGgAYwBsAGkAZQBuAHQALgBwAHMAMQAnACkAKQAKAA==\n"
==> win2012:       interpreter "C:\\windows\\sysnative\\cmd.exe"
==> win2012:       declared_type :batch
==> win2012:       cookbook_name :chocolatey
==> win2012:       recipe_name "default"
==> win2012:       architecture :x86_64
==> win2012:       not_if { #code block }
==> win2012:     end
==> win2012:
==> win2012: [2015-10-09T03:02:27-07:00] INFO: Running queued delayed notifications before re-raising exception
==> win2012:
==> win2012: Running handlers:
==> win2012: [2015-10-09T03:02:27-07:00] ERROR: Running exception handlers
==> win2012: Running handlers complete
==> win2012: [2015-10-09T03:02:27-07:00] ERROR: Exception handlers complete
==> win2012: Chef Client failed. 0 resources updated in 01 minutes 03 seconds
==> win2012: [2015-10-09T03:02:27-07:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
==> win2012: [2015-10-09T03:02:27-07:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: batch[install chocolatey] (chocolatey::default line 48) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> win2012: ---- Begin output of "C:\Windows\system32\C:\windows\sysnative\cmd.exe" /c "C:/Users/vagrant/AppData/Local/Temp/chef-script20151009-2704-eii6yz.bat" ----
==> win2012: STDOUT:
==> win2012: STDERR: The filename, directory name, or volume label syntax is incorrect.
==> win2012: ---- End output of "C:\Windows\system32\C:\windows\sysnative\cmd.exe" /c "C:/Users/vagrant/AppData/Local/Temp/chef-script20151009-2704-eii6yz.bat" ----
==> win2012: Ran "C:\Windows\system32\C:\windows\sysnative\cmd.exe" /c "C:/Users/vagrant/AppData/Local/Temp/chef-script20151009-2704-eii6yz.bat" returned 1

**Comment by ferventcoder** [comment]
Howdy, please file an issue on https://github.com/chocolatey/chocolatey-cookbook. Thanks!
