### ISSUE TITLE
Improve output of choco outdated

### ISSUE THREAD

**Issue by aronovgj** [chocolatey/choco#457]
```
$ choco outdated
Chocolatey v0.9.10-beta1
Outdated Packages
 Output is package name | current version | available version | pinned?

4t-tray-minimizer|5.52|5.52|false
chromium|47.0.2512.0|48.0.2532.0|true
github|2.14.1.2|3.0.5.2|true
hijackthis|2.0.5-beta|2.0.5-beta|false
hitmanpro|3.7.10.250|3.7.10.250|false
keyboard-layout-creator|1.4|1.4|false
pidgin-otr|4.0.1.20150816|4.0.1.20150816|false
praatcon|5.4.22|5.4.22|false

Chocolatey has determined 0 package(s) are outdated.
```

Last sentence is not entirely true, isn't it? `chromium` and `github` are actually outdated but can not be upgraded because they are pinned. I don't know if my suggestions would make it more confusing and/or cluttered.

Maybe `Chocolatey can upgrade 0/139 package(s).` is more appropriate like it is shown after `choco upgrade all --noop`.

Also I don't see any use in the summery of `outdated`:

```
Chocolatey has determined 0 package(s) are outdated.
 8 package(s) had warnings..
Warnings:
 - hijackthis
 - praatcon
 - ...
```

The interesting thing carrying actual useful information is the upper part telling you current version, available version and pinned status. This output might be used as the summary part of  `choco upgrade all --noop`. See https://github.com/chocolatey/choco/issues/455

**Comment by ferventcoder** [comment]
Looks like the counter is not rolling for outdated. Hmmm. I think it's the same issue that you see with the noop upgrade.

**Comment by aronovgj** [comment]
I don't see a particular issue with noop. I just suggest to put more info into the output. The counters of noop make sense to me because it is phrased differently: `Chocolatey *can* upgrade 1/139 package(s).` is entirely true because it can't update pinned packages and it can't update packages which were not moderated yet.

**Comment by ferventcoder** [comment]
Oh. I thought the can upgrade was coming back as 0 as well?

**Comment by aronovgj** [comment]
No, those are outputs of different states.

I think you don't see what I'm driving at. Say this is the state:

     Output is package name | current version | available version | pinned?
    4t-tray-minimizer|5.52|5.52|false
    chromium|48.0.2532.0|48.0.2533.0|true
    github|2.14.1.2|3.0.6.4|true
    hijackthis|2.0.5-beta|2.0.5-beta|false
    hitmanpro|3.7.10.250|3.7.10.250|false
    keyboard-layout-creator|1.4|1.4|false
    pidgin-otr|4.0.1.20150816|4.0.1.20150816|false
    praatcon|5.4.22|5.4.22|false

The statement 
`Chocolatey has determined 0 package(s) are outdated.` 
which you get with `outdated` is wrong because there are outdated packages, like github.

The statement
`Chocolatey can upgrade 0/139 package(s).`
which you get with `-noop` is correct because chocolatey actually can't upgrade packages like github.

Thats for the issue part.

The enhancement part is that just listing the packages for which there were warning at the end of `-noop` and `outdated` is useless and should contain more info.

**Comment by ferventcoder** [comment]
Sorry, I totally get it. I'm just stating there is a bug in the "0" with
outdated.

On Saturday, October 10, 2015, aronovgj <notifications@github.com> wrote:

> No, those are outputs of different states.
>
> I think you don't see what I'm driving at. Say this is the state:
>
>  Output is package name | current version | available version | pinned?
> 4t-tray-minimizer|5.52|5.52|false
> chromium|48.0.2532.0|48.0.2533.0|true
> github|2.14.1.2|3.0.6.4|true
> hijackthis|2.0.5-beta|2.0.5-beta|false
> hitmanpro|3.7.10.250|3.7.10.250|false
> keyboard-layout-creator|1.4|1.4|false
> pidgin-otr|4.0.1.20150816|4.0.1.20150816|false
> praatcon|5.4.22|5.4.22|false
>
> The statement
> Chocolatey has determined 0 package(s) are outdated.
> which you get with outdated is wrong because there are outdated packages,
> like github.
>
> The statement
> Chocolatey can upgrade 0/139 package(s).
> which you get with -noop is correct because chocolatey actually can't
> upgrade packages like github.
>
> Thats for the issue part.
>
> The enhancement part is that just listing the packages for which there
> were warning at the end of -noop and outdated is useless and should
> contain more info.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/457#issuecomment-147122566>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
A few issues have come out that may have addressed or will address this:

* #1222
* #580 
* #994 
* #843 

I think we can close this.
