### ISSUE TITLE
Choco New creates a bad ChocolateyUninstall.ps1 script which does not work.

### ISSUE THREAD

**Issue by pauby** [chocolatey/choco#460]
When using Choco New to create a new ChocolateyInstall.ps1 and ChocolaetyUninstall.ps1 script the uninstall one is bad. See below:

<code>
$key = Get-ItemProperty -Path @($machine_key6432,$machine_key, $local_key) `
                        -ErrorAction SilentlyContinue `
         | ? { $_.DisplayName -like "$softwareName" }

if ($key.Count -eq 1) {
...
</code>

That if statement will never execute as when $key only has one value it's not an Array so doesn't have a Count method. The fix is to force $key to be an array:

<code>
[array]$key = Get-ItemProperty -Path @($machine_key6432,$machine_key, $local_key) `
                        -ErrorAction SilentlyContinue `
         | ? { $_.DisplayName -like "$softwareName" }

if ($key.Count -eq 1) {
</code>

I would just submit a pull request but I have no idea where it gets the script or if it generates it on the fly.

**Comment by ferventcoder** [comment]
That was a late acceptance. I guess we didn't check over that good enough. You can see the script at https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/templates/ChocolateyUninstallTemplate.cs

**Comment by pauby** [comment]
Thanks. I've submitted a pull request for the amendment.

**Comment by Link-Satonaka** [comment]
I've found a case which causes the current template to fail (and is unrelated to the [array])

Pesky UninstallString: `"C:\WINDOWS\SysWOW64\RunDll32.EXE" "C:\Program Files\NVIDIA Corporation\Installer2\InstallerCore\NVI2.DLL",UninstallPackage Display.GFExperience`

`$silentArgs = '-silent'`

Error log
https://gist.github.com/Link-Satonaka/35452023a6f97faae5b3

**Comment by chrsmith** [comment]
For reference, if you are being bitten by this by running `choco new -a ...` the fix can be seen here:
https://github.com/chocolatey/choco/pull/462/files

Specifically, prefix `$key` with `[array]`:

````
[array]$key = Get-ItemProperty -Path @($machine_key6432,$machine_key, $local_key) `
                               -ErrorAction SilentlyContinue `
                | ? { $_.DisplayName -like "$softwareName" }
````

**Comment by ferventcoder** [comment]
Yep, we are working on that one still.
