### ISSUE TITLE
Choco treats the installation as successful even though the user aborts during the installation

### ISSUE THREAD

**Issue by i-give-up** [chocolatey/choco#463]
It seems like if a user aborts an installation by pressing Ctrl+C, Choco will treat the installation as successful. While Choco doesn't print out the "The install of [package] was successful" message, when you run `choco list -l` or `choco install [package]`, you would see that Choco treats the package as installed.

I first discovered this issue when I cancel the download of the atom.io installer.

This is on Choco 0.9.9.11

**Comment by ferventcoder** [comment]
This is a duplicate

**Comment by ferventcoder** [comment]
Duplicate of #198.
