### ISSUE TITLE
Is there any plans to make ChocolateyUninstall.ps1 compulsory?

### ISSUE THREAD

**Issue by i-give-up** [chocolatey/choco#464]
I recently learned that for `choco uninstall` to actually remove a package from your machine, the packager needs to implement ChocolateyUninstall.ps1 correctly. But looking at some of the popular packages, e.g. [Notepad++](https://chocolatey.org/packages/notepadplusplus), [Git (Install)](https://chocolatey.org/packages/git.install), [Firefox](https://chocolatey.org/packages/Firefox), it seems like this script is often not included.

I am aware of `choco feature enable -n AutoUninstaller` but it seems like the uninstaller always runs in non-silent mode. Besides, it is a feature that is disabled by default.

What this means is that Choco by default is not necessarily able to uninstall programs that it installs onto your machine. That doesn't seem like right.

---

On a side note, I find the wording in [the documentation on `choco uninstall`](https://github.com/chocolatey/choco/wiki/CommandsUninstall) is a bit unclear. In particular,

>Automatic Uninstaller (AutoUninstall) is turned off by default. To turn it on, run the following command...

It isn't immediately clear to me that "Automatic Uninstaller" simply means invoking program's own uninstaller with no arguments (correct me if I'm wrong). Instead, I thought "Automatic Uninstaller" was some kind of feature that Chocolatey introduced.

Is it just me that thinks "Automatic Uninstaller" could use additional clarification?

**Comment by aronovgj** [comment]
The autouninstaller is supposed to be turned on by default in later releases. If I may speak for myself, I don't include uninstall scripts in my packages anymore because it feels like wasted time if the AutoUninstaller can handle it and it won't be necessary anyway in the future. Some moderators offer maintainers to include an uninstall script but the maintainers are free to not use it since at the moment this is not obligatory. 
Uninstallation with the AutoUninstaller should work silently in most cases. Not being silent may be due to the uninstaller not offering a switch to uninstall silently or choco not catching the switch. If the installer is a standard installer and supports all the conventional switches, this should be investigated.

**Comment by ferventcoder** [comment]
0.9.10 it will be turned on by default. 0.9.9 series was about getting it more rock solid.

On a side note, it may be helpful when you have questions to jump into the gitter channel. We can answer questions there without needing to then later triage the ticket as invalid. :)

**Comment by i-give-up** [comment]
So, AutoInstaller would be the default mechanism by which packages would be uninstalled, as opposed to ChocolateyUninstall.ps1? If that's the case, does the relevant sections in the Creating Chocolatey Package wiki ([here](https://github.com/chocolatey/choco/wiki/CreatePackages#okay-how-do-i-create-packages) and [here](https://github.com/chocolatey/choco/wiki/CreatePackages#uninstalling)) need to be updated to indicate that autoInstaller would take care of package uninstallation and that the package maintainer (probably) doesn't need to supply chocolateyUninstall.ps1?

**Comment by ferventcoder** [comment]
Yep, but we won't update those until we release 0.9.10. :)

On Wednesday, October 14, 2015, i-give-up <notifications@github.com> wrote:

> So, AutoInstaller would be the default mechanism by which packages would
> be uninstalled, as opposed to ChocolateyUninstall.ps1? If that's the case,
> does the relevant sections in the Creating Chocolatey Package wiki (here
> <https://github.com/chocolatey/choco/wiki/CreatePackages#okay-how-do-i-create-packages>
> and here
> <https://github.com/chocolatey/choco/wiki/CreatePackages#uninstalling>)
> need to be updated to indicate that autoInstaller would take care of
> package uninstallation and that the package maintainer (probably) doesn't
> need to supply chocolateyUninstall.ps1?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/464#issuecomment-148252087>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder
