### ISSUE TITLE
Installdir argument not working

### ISSUE THREAD

**Issue by alyssenko-ssi** [chocolatey/choco#465]
Attempting to install a nuget package into a custom location using INSTALLDIR

ex:

C:\ProgramData\chocolatey\bin\choco.exe upgrade PACKAGE -version 19.1.1.1 -dvy --allow-downgrade -source http://domain.com/nuget -ia "/INSTALLDIR=""C:\\test""" 

results in choco putting the package in the default 'C:\ProgramData\chocolatey\lib' location.

**Comment by ferventcoder** [comment]
"IA" is related to the install arguments for a software installer (MSI, InnoSetup, etc), not for the package itself. You are not able to redirect where packages install.

Curious what the motivation is here.

**Comment by ferventcoder** [comment]
Based on further discussion at https://gitter.im/chocolatey/choco?at=5620fcaaac2de5da02295d48, I think we can close this with these ideas:

>So you can put the software anywhere you want - the pkg has a fixed location under $env:chocolateyInstall\lib, but the packaging contains software and/or instructions on how to install that software (the automation scripts, written in PowerShell).
>If you want to pass where to put the software at runtime, you can pass package parameters to the pkg in the form of `-params`
>Otherwise if you go to the same place all the time (or even have a default), you can build that right into the package.
