### ISSUE TITLE
Package source authentication at http://location/path doesn't also use http://location/ (base url)

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#466]
https://groups.google.com/d/msgid/chocolatey/7cbc7cd6-c16f-4282-a557-d7d464c85e79%40googlegroups.com?utm_medium=email&utm_source=footer

>I'm trying to use chocolatey with a package source that requires HTTP basic authentication.  I'm executing a command similar to the following:

>`choco install -y -version 1.0.0 -source https://source.mydomain.org/nuget/ -u username -p password -d packageName`

>The username and password is sent for the first request (/nuget); however, for subsequent requests I'm prompted for the username/password.  Here is a sample of my output:

>>Installing the following packages:
>>packageName
>>By installing you accept licenses for the packages.
>>Using passed in credentials
>>Please provide credentials for: https://source.mydomain.org/api/v2/package/packageName/1.0.0
>>User name:

>It looks like the code in ChocolateyNugetCredentialProvider.cs (around line 47) is not matching the _config.Sources variable on subsequent requests, so it's prompting me for credentials even though I'm technically using the same package source.  My thought was that the base URL could be used for _config.Sources and then the compare on subsequent requests would also use the base URL, but I'm not sure if that would break anything else.  Thoughts?

**Comment by jabendroth** [comment]
I just retried this using chocolately version 0.9.9.11, but the problem still exists.  Should this bug be fixed in that version?

**Comment by crmckenzie** [comment]
Nuget used to have confusing behavior around sources. It would let you name a source, but would require in some places that you specify the url instead of the source name. I wonder if this is left-over crud from old nuget behavior. I can't wait to see if this fixes my issue :)

**Comment by ferventcoder** [comment]
@crmckenzie yeah, I was just researching there early this morning and found they had some issues still. 

We don't let you specify source by name yet... as an FYI. I think there is another ticket to add that behavior.

**Comment by crmckenzie** [comment]
One of my co-workers thinks it's because choco is still using an old version of the NuGet library. He's attempting a recompile against the new one. He's having some issues getting it to recompile. I'm inviting him to join the conversation as perhaps this is an easy fix!

**Comment by skiplee** [comment]
# 
Chris, thanks for the invite.

The choco solution uses version 2.8.2 of Nuget.Core which is almost 2 years old. When I update the Nuget.Core package to 2.10.1, choco fails to compile here. The .Override method isn't defined.

** NugetCommon.cs line: 70 **
```csharp
var proxy = new WebProxy(configuration.Proxy.Location, true);
....
ProxyCache.Instance.Override(proxy);
```

It's not clear what the intention is, in using the .Override; but I'm hopeful that our issue with choco push is related to the old nuget package.

**Comment by ferventcoder** [comment]
We are using 2.11.

**Comment by ferventcoder** [comment]
Sorry, clarifying. The current release is using 2.8.6. The beta of 0.9.10 and upcoming release of 0.9.10 use 2.11.

**Comment by ferventcoder** [comment]
We don't use the one from NuGet.org. We use a custom compiled version of NuGet - https://github.com/chocolatey/nuget-chocolatey/tree/2.11_adds

and you are correct, it was 2.8.2 that is in the current 0.9.9.11 - https://github.com/chocolatey/nuget-chocolatey/tree/2.8.2_adds

**Comment by ferventcoder** [comment]
I labeled this with security - here's why (also reflected in the commit): 

First atttempt to validate against the exact path for the source Uri,
but when that fails due to subpaths in the source uri string,
also attempt to validate credentials against the host Uri as well.

In most cases this should be fine, however there could be a very slight
security issue if the host domain is tracking calls on the credentials
when the sub path is owned by someone different, such as in shared
hosting where the domain is shared and the subpaths are different for
everyone. The chances of this are extremely slight given that most
hosting for NuGet Servers own the virtual site or are used internally.
In most cases those host domains probably already validate your user
name/password in other places. It is worth noting though. Only use
hosting solutions you trust.

**Comment by ferventcoder** [comment]
A beta just got pushed with these fixes. https://chocolatey.org/packages/chocolatey/0.9.10-beta-20160204
You can install it immediately if you use `-version` in the switches, otherwise it will be available in about an hour with the `-pre` switch.

`choco upgrade chocolatey -version 0.9.10-beta-20160204`

Would love some verification that this works.

**Comment by skiplee** [comment]
My problem (which wasn't the target of this fix) wasn't helped. I'll open a new issue.

**Comment by ferventcoder** [comment]
@skiplee thanks!

**Comment by jabendroth** [comment]
I just tested the version above, but I'm still being prompted the second time.  This doesn't seem to have fixed my issue.  Here is my log:

`PS C:\Users\Administrator>
PS C:\Users\Administrator> C:\ProgramData\chocolatey\bin\choco.exe upgrade -dv -y -source https://myserver.org/nuget/ -u <username> -p "<password>" --allow-unofficial MyPackage
Nothing to change. Config already set.
Chocolatey v0.9.10-beta1-121-g540a6f1
Chocolatey is running on Windows v 6.3.9600.0
Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
Command line: "C:\ProgramData\chocolatey\choco.exe" upgrade -dv -y -source https://myserver.org/nuget/ -u <username> -p <password> --allow-unofficial MyPackage
Received arguments: upgrade -dv -y -source https://myserver.org/nuget/ -u <username> -p <password> --allow-unofficial MyPackage
The source 'https://myserver.org/nuget/' evaluated to a 'normal' source type

NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
Configuration: CommandName='upgrade'|
CacheLocation='C:\Users\Administrator\AppData\Local\Temp\2\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|
Sources='https://myserver.org/nuget/'|
SourceType='normal'|
Debug='True'|Verbose='True'|Force='False'|Noop='False'|
HelpRequested='False'|RegularOutput='True'|QuietOutput='False'|
PromptForConfirmation='False'|AcceptLicense='True'|
AllowUnofficialBuild='True'|Input='MyPackage'|AllVersions='False'|
SkipPackageInstallProvider='False'|PackageNames='MyPackage'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|VirusCheckMinimumPositives='5'|
Information.PlatformType='Windows'|
Information.PlatformVersion='6.3.9600.0'|
Information.PlatformName='Windows Server 2012 R2'|
Information.ChocolateyVersion='0.9.10.0'|
Information.ChocolateyProductVersion='0.9.10-beta1-121-g540a6f1'|
Information.FullName='choco, Version=0.9.10.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64Bit='True'|Information.IsInteractive='True'|
Information.IsUserAdministrator='True'|
Information.IsProcessElevated='True'|
Information.LicenseIsValid='False'|
Features.AutoUninstaller='True'|Features.CheckSumFiles='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.VirusCheck='False'|
ListCommand.LocalOnly='False'|
ListCommand.IncludeRegistryPrograms='False'|ListCommand.PageSize='25'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
NewCommand.AutomaticPackage='False'|SourceCommand.Command='unknown'|
SourceCommand.Username='<username>'|SourceCommand.Priority='0'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
PushCommand.TimeoutInSeconds='0'|PinCommand.Command='unknown'|
_ Chocolatey:ChocolateyUpgradeCommand - Normal Run Mode _
Upgrading the following packages:
MyPackage
By upgrading you accept licenses for the packages.
MyPackage is not installed. Installing...
Using passed in credentials
Please provide credentials for: https://myserver.org/api/v2/package/mypackage/2016.01.19.0001
User name:`

**Comment by ferventcoder** [comment]
@jabendroth The fix was for stored sources. It was suggested from the original bug report (the email) that this was related to how it would look at the credential provider, which caches the stored sources, not the one you provide on the command line at run time. The one you provide gets stored in a different variable. Perhaps we should ***also*** evaluate the host of the provided source? :)

**Comment by ferventcoder** [comment]
Okay, now this is fixed to include passed in credentials. Sorry for the confusion!

**Comment by jabendroth** [comment]
Awesome, thanks Rob!  That worked.  I verified by running the command on a few of my machines.  I was never prompted for credentials.
