### ISSUE TITLE
Chocolatey command help output breaks powershell more function

### ISSUE THREAD

**Issue by jbuedel** [chocolatey/choco#468]
If I issue `choco -h | more` I get paged output, as expected. `choco source -h | more` never pages. That is, all output is dumped to the console immediately. 

This happens with all the subcommands I tried, including 'search', 'list', and 'source'.

**Comment by ferventcoder** [comment]
Hi,
 Choco is not a powershell command, nor does it have powershell output. If
more does not work for stdout, then that is likely the issue.

You may want to use the real more or less commands to get what you desire.

On Friday, October 16, 2015, Josh Buedel <notifications@github.com> wrote:

> If I issue choco -h | more I get paged output, as expected. choco source
> -h | more never pages. That is, all output is dumped to the console
> immediately.
>
> This happens all the subcommands I tried, including 'search', 'list', and
> 'source'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/468>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by jbuedel** [comment]
I'm pretty sure powershell's more works with standard output. `git log | more` does what I expect at least. Git obviously isn't a powershell command either.

Anyway, regardless of what is right, chocolatey is inconsistent in the way it outputs subcommand help versus just `choco help`.

**Comment by ferventcoder** [comment]
> Anyway, regardless of what is right, chocolatey is inconsistent in the way it outputs subcommand help versus just choco help.

It doesn't do anything different from a technical perspective.

**Comment by jbuedel** [comment]
Are you not seeing the behavior I described?

**Comment by ferventcoder** [comment]
I don't see paged output for either.

**Comment by jbuedel** [comment]
Hmm. I've confirmed it on two separate machines now. I suppose it is possible that my powershell is tweaked similarly on both machines, yet different than yours.  I'll see if I can duplicate on other machines.

**Comment by jbuedel** [comment]
I've figured out what is going on. The short explanation is: the option descriptions text that follows "Option and Switches" part of the help text is written to StdErr. The rest of the output goes through the logging system and ultimately comes out of StdOut.

The longer explanation is that the inconsistency I saw with paging was that the 'choco -h' command had enough StdOut text that it would page. 'choco list -h' has very little StdOut output and did not need to page. The tricky bit was that the StdErr output, in both cases, is going directly to the screen. It actually appears *above* the StdOut text in my console. There is enough option description text that it scrolls, giving the appearance that more is not paging. I guess StdErr beats StdOut to the console, probably because StdOut is passing through more.com first, slowing it down.

If you agree that all the help text should be consistently written to StdOut, I suggest that the fix would occur in ConfigurationOptions.show_help(). One solution is to replace Console.Error with Console.Out as the parameter to OptionSet.WriteOptionDescriptions(). Another is to capture the text OptionSet.WriteOptionDecriptions() writes to an in memory stream and then push that text through the logging system. This would be more consistent with how the rest of the help text is written.

If you agree with either of my proposed solutions I'd like to submit a pull request. Just let me know how you'd like it handled.

**Comment by ferventcoder** [comment]
Ah, sweet. Yeah, the options should not be written to stderr. I have a feeling that is either something I was doing or something embedded into NDesk.Options I need to dive in and fix.

**Comment by ferventcoder** [comment]
@jbuedel Yes you may implement a fix. :)

**Comment by ferventcoder** [comment]
Target stable for quickest results.

**Comment by ferventcoder** [comment]
@jbuedel ping - I'm looking for this coming up soon. If you still want to provide a fix let me know, otherwise I will assume you got busy and will handle this. :+1:

**Comment by jbuedel** [comment]
Hi Rob. Yeah unfortunately I've just been too busy to dig into it. I haven't forgotten though. I'll see what I can do over the next few days, but if you beat me to it, no problem.

**Comment by secretGeek** [comment]
I am signing up to help with this as I was "bitten" by this problem today.

**Comment by ferventcoder** [comment]
@secretGeek target stable if you can - otherwise I will rebase onto stable when merging. :+1:

**Comment by secretGeek** [comment]
This is my first public PR. Any problems I'll do my best to resolve ;)

**Comment by gep13** [comment]
>@secretGeek said...
This is my first public PR. Any problems I'll do my best to resolve ;)

Thanks for your contribution! :+1:
