### ISSUE TITLE
choco pack returns zero exit code when Nuget.Core validation errors

### ISSUE THREAD

**Issue by jbuedel** [chocolatey/choco#469]
See below where I have passed an invalid $version$ token.
![](https://cloud.githubusercontent.com/assets/85681/10548068/fbe22a4e-73fd-11e5-8bc9-c2f1053fa16b.png)

I expected $LASTEXITCODE to be non-zero.

**Comment by ferventcoder** [comment]
Thanks - tagged it for vNext.

**Comment by ferventcoder** [comment]
This doesn't seem to be an error in 0.9.10 - not sure if it was cleared by other things or not.

**Comment by ferventcoder** [comment]
![image](https://cloud.githubusercontent.com/assets/63502/14412036/8f39e09c-ff1e-11e5-840b-7284006eedf8.png)

Something else that was done seems to have fixed this issue.
