### ISSUE TITLE
Search fails, but install works.

### ISSUE THREAD

**Issue by flcdrg** [chocolatey/choco#471]
There seems to be an inconsistency between searching for packages and installing/upgrading them. I suspect this is related to case-sensitivity. eg.
```
choco search visualstudiocode
0 packages found.

choco install visualstudiocode
Installing the following packages:
...
```
In this case, the package name according to chocolatey.org is VisualStudioCode

**Comment by gep13** [comment]
I suspect that this is related to this:

https://github.com/chocolatey/chocolatey.org/issues/234

If you do `choco search VisualStudioCode` it will return a single package.

**Comment by ferventcoder** [comment]
Duplicate of https://github.com/chocolatey/chocolatey.org/issues/234

**Comment by gep13** [comment]
@ferventcoder so nothing needs to change in the choco client to fix this, it is working solely on the results from the search query?  **NOTE:** just want to make sure I am not missing anything :smile:

**Comment by ferventcoder** [comment]
Yep, it's entirely a Chocolatey.org issue at the moment.

**Comment by gep13** [comment]
:+1:

**Comment by flcdrg** [comment]
Sorry for the 'noise'. I did a search before posting this issue, but obviously didn't try enough keywords :-(

**Comment by ferventcoder** [comment]
@flcdrg no worries - we're here to make sure things get triaged correctly. :)
