### ISSUE TITLE
choco cli options missing in wiki and help function.

### ISSUE THREAD

**Issue by jgoldsteindev** [chocolatey/choco#472]
had to ask in the chat how to get the chocolatey version number, which is '-v'. This option, and likely others, are not mentioned anywhere in the wiki or cli help function.

**Comment by i-give-up** [comment]
The following outputs chocolatey's version

    choco -v

whereas the following runs the command in verbose mode

    choco 〈command〉 -v

In view of this, how should the `-v` option be explained? Currently when you run `choco -h`, it has this

    -v, --verbose
        Verbose - See verbose messaging

**Comment by TheCakeIsNaOH** [comment]
Duplicate of https://github.com/chocolatey/choco/issues/2049

**Comment by TheCakeIsNaOH** [comment]
Removing from milestone as a duplicate
