### ISSUE TITLE
Suppress verbose output to verbose - like with 7-zip

### ISSUE THREAD

**Issue by MikaelSmith** [chocolatey/choco#476]
For some packages, like mingw, listing all the files extracted is overwhelming. The log in AppVeyor is one instance.

Showing all the 7-Zip output is a recent change. It would be nice to have a way to suppress that output.

**Comment by ferventcoder** [comment]
@MikaelSmith so if they come on with --verbose (aka -v), would you consider turning that off?

**Comment by ferventcoder** [comment]
I would expect to see that in a verbose / debug log, but definitely not during normal operation.

**Comment by MikaelSmith** [comment]
Yeah, I wasn't using verbose output (that I know of) when I tried it out with a recent version of Chocolatey.

**Comment by ferventcoder** [comment]
Should be pretty easy to add. Right now it is letting it use the window, a recent change that fixed other things like powershell interaction #219

**Comment by ferventcoder** [comment]
This was completed with #616.

**Comment by ezyang** [comment]
It's too bad Appveyor's choco doesn't have this fix yet!

**Comment by chrisdembia** [comment]
I also am anticipating when this fix is propagated to AppVeyor. As far as I can, the fix hasn't been put in a released version of chocolately yet.
