### ISSUE TITLE
Do not use NuGet package cache

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#479]
https://github.com/chocolatey/chocolatey/issues/714

From @stift:

I have recently observed that chocolatey uses the same cache as nuget does (c:\users\user1\appdata\local\nuget\cache). Which sounds first like it should not be a problem, they both save files there from different feeds. As there are some packages with the same name, like `nunit` that exist on the chocolatey and on the nuget feed, this leads to some unforeseen behaviour. Depending who comes first, the second one thinks that the package was already downloaded and uses that one. The behaviour afterwards is desastrous and really took me some to figure this out. Therefore I strongly recommend to use some different path for caching the downloaded package files as the feed is also context-wise completely different.

**Comment by ferventcoder** [comment]
We shut it off completely at one point, but must have missed it during the rewrite when we moved to NuGet.Core.

**Comment by ferventcoder** [comment]
Actually it's a bug in NuGet - for some reason it is using the cache repository with the aggregate even though it should not. We don't go down the path that would allow for the cache repository.

What we can do is clean up after the installer/upgrader when it does install packages into the cache.

**Comment by ferventcoder** [comment]
Something to the effect of:

~~~csharp
 var cachePackage = _fileSystem.combine_paths(Environment.GetEnvironmentVariable("LocalAppData"), "NuGet", "Cache", "{0}.{1}.nupkg".format_with(packageId, version.to_string()));
if (_fileSystem.file_exists(cachePackage)) _fileSystem.delete_file(cachePackage);
~~~

**Comment by ferventcoder** [comment]
This is now fixed and will go out in 0.9.10. There is a prerelease going out today that will also include this fix.

**Comment by CollinChaffin** [comment]
@ferventcoder Rob have to ask as old as this issue is, that as of latest version 0.10.13, every chocolatey install's package gets stuffed into `AppData\Local\NuGet\Cache`, and never ever cleaned up.  On multiple systems and those directories are all multiple Gigabytes in size they do not appear to have EVERY choco package ever installed, but many and certainly do have the last ones installed with 0.10.13.  Is this a regression issue or ?

**Comment by bcurran3** [comment]
@CollinChaffin 

Hi again.

Consider: https://chocolatey.org/packages/choco-cleaner

**Comment by ferventcoder** [comment]
@CollinChaffin Let's file a new issue. Chocolatey cleans up the main package that is installed there, however it may not clean up dependencies. I'm not sure I see what you are seeing, so it may be a regression on certain systems. We may go edit nuget-chocolatey not to even store into a local cache (it is annoying).
