### ISSUE TITLE
Allow y/n in stead of 1/2/3 on install

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/choco#482]
Coming from `apt-get`, I always make this mistake where I type `y` first, and then `1` because `y` doesn't mean anything.

In order to keep things uniform, choco should also accept `y` and `n` to approve or reject an action.

Also the command line option `-y` uniformly means _"assume yes to all questions"_ (in Linux at least), effectively making choco unattended.

![image](https://cloud.githubusercontent.com/assets/1702193/11228782/8c1f86d8-8d8f-11e5-9d71-97dd1bc02e56.png)

**Comment by ferventcoder** [comment]
This is a duplicate - don't have issue off hand but will update later

**Comment by ferventcoder** [comment]
There's even a PR already - targeted for 0.9.10

**Comment by Redsandro** [comment]
Oops. Nevermind. Thanks. Closing.

**Comment by ferventcoder** [comment]
Duplicate of #181
