### ISSUE TITLE
Add possibility to have refreshenv called on a package dependency

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/choco#486]
Use case: I have a Chocolatey package which reflects my development environment through dependencies. One of the dependencies is NodeJs, others are npm packages.
The problem is that if I just install my development environment package it installs the NodeJs through the dependency first, but installing any npm packages fail, since the Path environment variable is not refreshed yet.

As a workaround (even though only for cmd shell and not for PowerShell) I can write a script which first installs NodeJs, call `refreshenv` and then install my development environment package. But this means that I need to maintain the node version in two places (script & dependency).

It would be nice if there was either a config option for calling `refreshenv` after installing each dependency or an enhancement to the Syntax in the nuspec file to define that for certain dependencies `refreshenv` should be called after installation and before proceeding with the next installation.

**Comment by ferventcoder** [comment]
I think this may be a duplicate of #439

**Comment by pascalberger** [comment]
Seems so. Sorry my searches didn't brought this up. Closing this one.
