### ISSUE TITLE
Is is possible to lock a specific version of chocolatey?

### ISSUE THREAD

**Issue by lmayorga1980** [chocolatey/choco#489]
Wondering if you can send an argument or just add it to the url

```powershell
 @powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/0.9.9/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin
```

**Comment by ferventcoder** [comment]
Wrong place for discussion, but yes.

**Comment by ferventcoder** [comment]
You should definitely hop in the gitter chat room for quick questions like this

**Comment by ferventcoder** [comment]
To answer your question though, see https://github.com/chocolatey/choco/wiki/Installation#before-you-install
