### ISSUE TITLE
Exception if no source is enabled

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/choco#490]
If I have all my sources disabled and try to install a package a null reference exception is thrown:

```
C:\>choco install nodejs
Installing the following packages:
nodejs
By installing you accept licenses for the packages.
Object reference not set to an instance of an object.
```

Better would be if the exception is handled and instead an error message is displayed informing the user that no source is available.

**Comment by ferventcoder** [comment]
Latest version I assume? I knew about this error, I'm not sure if it is already logged or not.

**Comment by ferventcoder** [comment]
It is not yet logged. Thanks!

**Comment by pascalberger** [comment]
Yes, with 0.9.9.11

**Comment by MikeFoden** [comment]
I would like to tackle this one.

**Comment by ferventcoder** [comment]
@MikeFoden Sweet! Read over the CONTRIBUTING doc to make sure you don't have any issues with the workflow or signing the CLA, then target the stable branch with your changes.

**Comment by MikeFoden** [comment]
@ferventcoder I've put through #547 for this issue.

I didn't do it correctly with #546 so I closed it - sorry! I'm still pretty new at contributing to open source.
