### ISSUE TITLE
Error while running 'C:\ProgramData\chocolatey\lib\npm\tools\chocolateyInstall.ps1'.

### ISSUE THREAD

**Issue by dr-w9999** [chocolatey/choco#495]
I try to install various packages and I  get error:
I use Windows Vista Home Basic" 32-bit.
Chocolatey v0.9.9.11.

 Exception calling "GetResponse" with "0" argument(s): "תם פסק הזמן שהוקצב לפעולה"
 At C:\ProgramData\chocolatey\helpers\functions\Get-WebHeaders.ps1:92 char:37
-     $response = $request.GetResponse <<<< ();
  - CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
  - FullyQualifiedErrorId : DotNetMethodException
    The install of npm was NOT successful.
    Error while running 'C:\ProgramData\chocolatey\lib\npm\tools\chocolateyInstall.ps1'.
    See log for details.

log is here:
https://gist.github.com/dr-w9999/861e01f63f87d261f84f

**Comment by tirolo** [comment]
Bringing a little bit of context from the chat on gitter: 

gep13 12:15
@dr-w9999 can you help, what does this say? תם פסק הזמן שהוקצב לפעול'
dr-w9999 12:17
it's in hebrew: "the time perioed for the action has timed out"

If @dr-w9999 execute on his machine
`powershell -NoProfile -ExecutionPolicy Bypass -noexit -c " . $env:ChocolateyInstall\helpers\functions\Get-WebHeaders.ps1;Get-WebHeaders -url http://nodejs.org/dist/npm/npm-1.4.9.zip`

it fails (same as the logs): 
`
Exception calling "GetResponse" with "0" argument(s): "תם פסק הזמן שהוקצב לפעול
ה"
At C:\ProgramData\chocolatey\helpers\functions\Get-WebHeaders.ps1:92 char:37
$response = $request.GetResponse <<<< ();
CategoryInfo : NotSpecified: (:) [], ParentContainsErrorRecordE
xception
FullyQualifiedErrorId : DotNetMethodException
`

but it works if he just open the `http://nodejs.org/dist/npm/npm-1.4.9.zip` on his web browser, which makes me believe to be a proxy issue, I'm just not sure how to help him to get (if any) his proxy details.

**Comment by tirolo** [comment]
The log shows one successful installation at:
https://gist.github.com/dr-w9999/861e01f63f87d261f84f#file-log-sh-L407

what goes against my theory above :sweat_smile:

**Comment by ferventcoder** [comment]
This is likely an issue with the package itself. It would be a choco issue if you see it with all packages.

**Comment by tirolo** [comment]
@ferventcoder: I managed to find at least three different packages that he tried on the log files: nodejs, nodejs.install and npm. Do you think it may be something with the "http://nodejs.org" ?

**Comment by ferventcoder** [comment]
It could have been, yes.

**Comment by gep13** [comment]
@tirolo bear in mind, nodejs.install is a dependency of nodejs, and that the nodejs package doesn't actually do anything, from a PowerShell standpoint.

**Comment by tirolo** [comment]
Shall we then improve the log verbose so that we know if the failure was due to the script trying to download the software from the vendor web site? (in this case http://nodejs.org/dist/npm/npm-1.4.9.zip)

**Comment by ferventcoder** [comment]
This may have been a dot org issue - we were experiencing some issues around  that time that have since been fixed. I'm going to close this issue. @tirolo if you want, let's file an issue to improve error message reporting.

**Comment by srinivasudadi9000** [comment]
choco install nodejs-lts -y
after running this command i am getting this error 

ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "C:\ProgramData\chocolatey\
lib\nodejs-lts\tools\node-v6.11.0-x64_x64.msi" /qn /norestart /l*v "C:\Users\Adm
inistrator\AppData\Local\Temp\chocolatey\nodejs-lts.6.11.0.MsiInstall.log" ] was
 not successful. Exit code was '1603'. See log for possible error messages.
The install of nodejs-lts was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\nodejs-lts\tools\chocolateyin
stall.ps1'.
 See log for details.

**Comment by ferventcoder** [comment]
@srinivasudadi9000 1603 is a generic error. Please open C:\Users\Administrator\AppData\Local\Temp\chocolatey\nodejs-lts.6.11.0.MsiInstall.log and search for "Return Value 3". That will give you a great idea of what is actually wrong.

**Comment by bcurran3** [comment]
@srinivasudadi9000 a lot of times that happens when there is a pending reboot required

**Comment by lat94** [comment]
the command `choco install mongodb` is somehow pointing to the wrong url, see below:

> Downloading mongodb.install
  from 'https://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-3.6.0-signed.msi'
See the "mongodb.org" domain.
