### ISSUE TITLE
Document the review process / moderation somewhere

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#499]
https://gitter.im/chocolatey/choco?at=565fdbbe19eee17f78e2b3d5

**Comment by gep13** [comment]
:+1: I was literally thinking this as I was reading what you were writing in the Gitter chat.

Agree that this needs to be done, as it being solely in your head, and in parts mine, isn't great :smile:

**Comment by ferventcoder** [comment]
Done - https://github.com/chocolatey/choco/wiki/ChocolateyFAQs#what-is-moderation

**Comment by gep13** [comment]
Nice one! Looks good to me! :smile:
