### ISSUE TITLE
Support no path changes

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#5]
## Is Your Feature Request Related To A Problem? Please describe.

I don't want packages to change my PATH.

## Describe The Solution. Why is it needed?

Packages can change the PATH environment variable that may cause issues for some users. We should provide a way to disable this.

There are three ways that installing a Chocolatey package can change the path:

1. The package code may update the PATH environment variable directly.
  Many packages already update the PATH environment variable directly. The only way to change those would be when a new package version is submitted, and the moderator to flag this up. However, there are potentially Trusted packages, unmaintained packages and packages that are not released frequently. This would still leave a lot of packages with that code change being required.
2. The package may use [`Install-ChocolateyPath`](https://docs.chocolatey.org/en-us/create/functions/install-chocolateypath).
  This is something we could control by checking a feature, for example `disablePATHChanges`.
4. If the package installs software, the installer may amend the path.
  This is not something we can control.

## Additional Context.

If we add this, it should be controlled with a switch and a feature.

## Related Issues

N/A

**Comment by pauby** [comment]
This functionality now exists using package hooks. A hook could be set up to store the `PATH` before a package is installed, and restore it afterwards. If software is installed as part of the package, this may affect how it is intended to work, but that would be a decision for the user.

See the [hooks documentation](https://docs.chocolatey.org/en-us/features/hook) for more information and [this hooks package](https://community.chocolatey.org/packages/cleanup-desktop-shortcuts.hook) as an example.

I'm going to go ahead and close this now, but we can always reopen if necessary.
