### ISSUE TITLE
Sign the powershell scripts and assemblies

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#501]
One of the things we'll want to do for added security and for companies that need all scripts signed is to sign the PowerShell scripts.

https://groups.google.com/d/msgid/chocolatey/a476ca1e-85b0-4c53-816e-5621ef22ca9e%40googlegroups.com

**Comment by lboening** [comment]
:+1: Yes, this is irritating.

**Comment by ferventcoder** [comment]
Related https://github.com/chocolatey/chocolatey.org/issues/374

**Comment by ferventcoder** [comment]
This is shipping in the latest beta for 0.9.10 in a few minutes
