### ISSUE TITLE
NuGet dependency error messages could be better

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#506]
From https://groups.google.com/d/msgid/chocolatey/ad9e0b37-a81d-4c75-98c7-c84c787b8859%40googlegroups.com?utm_medium=email&utm_source=footer

```
xyz-all not installed. An error occurred during installation:
 Already referencing a newer version of 'xyz-bin'.
```

What does that even mean? This is a horrible way to explain an error. There is no hint on how to fix it, no explanation about what is really wrong. I mean, this is just :-1:

**Comment by pauby** [comment]
As we've moved to NuGet v3 the error messages are not the same as listed here and this issue has been superseded by that.

I'm going to go ahead and close this, but we can reopen it if necessary.
