### ISSUE TITLE
NuGet doesn't handle conflicts of versions in an install request when HighestVersion dependency

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#507]
The NuGet dependency walker doesn't seem to be able to handle the scenario where a package has a dependency constraint on a package version and another dependency has a similar, but looser constraint on a package version.

It fails with `Already referencing a newer version of 'x'.`

Related to #227 and #506.

From: https://groups.google.com/d/msgid/chocolatey/ad9e0b37-a81d-4c75-98c7-c84c787b8859%40googlegroups.com?utm_medium=email&utm_source=footer

Hasdependency.nuspec:

``` xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>hasdependency</id>
    <version>1.0.0</version>
    <authors>__REPLACE_AUTHORS_OF_SOFTWARE__</authors>
    <owners>__REPLACE_YOUR_NAME__</owners>
    <description>__REPLACE__</description>
    <dependencies>
      <dependency id="isdependency" version="[1.0.0]" />
      <dependency id="isexactversiondependency" version="[1.0.0]" />
    </dependencies>
  </metadata>
</package>
```

isdependency.nuspec

``` xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>isdependency</id>
    <version>1.0.0</version>
    <authors>__REPLACE_AUTHORS_OF_SOFTWARE__</authors>
    <owners>__REPLACE_YOUR_NAME__</owners>
    <description>__REPLACE__</description>
    <dependencies>
      <dependency id="isexactversiondependency" version="[1.0.0, 2)" />
    </dependencies>
  </metadata>
</package>
```

isexactversiondependency.nuspec (with one file so it will build) - 1.0.0

``` xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>isexactversiondependency</id>
    <version>1.0.0</version>
     <authors>__REPLACE_AUTHORS_OF_SOFTWARE__</authors>
    <owners>__REPLACE_YOUR_NAME__</owners>
    <description>__REPLACE__</description>
  </metadata>
  <files>
    <file src="tools\**" target="tools" />
  </files>
</package>
```

isexactversiondependency.nuspec (with one file so it will build) - 1.1.0

``` xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>isexactversiondependency</id>
    <version>1.1.0</version>
     <authors>__REPLACE_AUTHORS_OF_SOFTWARE__</authors>
    <owners>__REPLACE_YOUR_NAME__</owners>
    <description>__REPLACE__</description>
  </metadata>
  <files>
    <file src="tools\**" target="tools" />
  </files>
</package>
```

**Comment by ferventcoder** [comment]
Similar to #116 (although in this case it does).

**Comment by ferventcoder** [comment]
@timbrown5

**Comment by ferventcoder** [comment]
@maartenba / @xavierdecoster Did NuGet v3 fix this problem? I am working on reproducing it all the way up.

**Comment by ferventcoder** [comment]
Of course I need to install VisualStudio 2015 to verify this as it doesn't seem that the command line version of NuGet (up to 3.3.0) respects the DependencyVersion attribute in the NuGet.config file. I've set it to highest and it ignores it.

![image](https://cloud.githubusercontent.com/assets/63502/11833283/be7b2aee-a386-11e5-81dd-ced05200dabf.png)

**Comment by ferventcoder** [comment]
Here is a reproduction

[repro.zip](https://github.com/chocolatey/choco/files/63606/repro.zip)

**Comment by ferventcoder** [comment]
Here are the failing specs - https://github.com/chocolatey/choco/blob/master/Scenarios.md#when-installing-a-package-with-a-dependent-package-that-also-depdends-on-a-less-constrained-but-still-valid-dependency-of-the-same-package

**Comment by maartenba** [comment]
Best to post an issue at http://github.com/nuget/home

**Comment by ferventcoder** [comment]
@maartenba I am planning on it, but if you had any updates as to whether this was fixed ahead of time, it would be helpful.

**Comment by ferventcoder** [comment]
Hate to post an issue for something that has already been fixed.

**Comment by maartenba** [comment]
No idea personally, maybe @xavierdecoster

**Comment by ferventcoder** [comment]
@maartenba / @xavierdecoster - I followed up with https://github.com/NuGet/Home/issues/1839

**Comment by ferventcoder** [comment]
![image](https://cloud.githubusercontent.com/assets/63502/11834893/fa156a74-a395-11e5-815e-17f6dca0b3b7.png)

@gep13 verified this works properly in v3.

**Comment by ferventcoder** [comment]
This will require .NET 4.5 for the upgrade to a v3 version of NuGet so this will need to move to 0.9.11 where we are eclipsing support for .NET 4 (and Windows 2003).

**Comment by rockobonaparte** [comment]
I just got bit with this again with version 0.10.8. Is it actually still open? The packages I'm using are internal so I can't directly expose them but the dependency chain was basically:

**X 1.1**
(no specific dependencies)
(there is also an X 1.2 and that screws things up)

_this is actually wants being specified to be installed in Chocolatey_
**package X-wrapper 1.1**
needs X, specifically version 1.1
needs X-config 1.0

**X-config 1.0**
needs X, no specific version
needs X-collateral, no specific version

**X-collateral 1.0**
needs X, no specific version


If I install X 1.1 beforehand then we're cool. If I install X-wrapper 1.1 then X-config seems to grab X 1.2, then X-wrapper tries to get X 1.1, and the world explodes.

**Comment by ferventcoder** [comment]
Howdy @rockobonaparte - we are typically quite good at the paperwork aspect of our tickets, so if it is still open, it's likely still an issue. There are sometimes we do have duplicates that are not caught so they get tagged for the release and older issues might be missed in that regard. We are looking to upgrade NuGet coming in the next few months (hopefully completed by mid 2021).

**Comment by TheCakeIsNaOH** [comment]
This issue appears to be fixed as a part of #2740, by enabling/completing the below tests:

https://github.com/chocolatey/choco/blob/c0e2f848df3ba61b3a74504e8650020b588a6b16/src/chocolatey.tests.integration/scenarios/InstallScenarios.cs#L3251-L3459

**Comment by rockobonaparte** [comment]
Do you know how I can mess around with the sum of that and see what's going on? Version resolution came up recently among colleagues so we are actually still motivated over stuff like this.

**Comment by TheCakeIsNaOH** [comment]
@rockobonaparte there is an alpha release available: https://blog.chocolatey.org/2023/01/chocolatey-cli-v2-alpha-release/
