### ISSUE TITLE
Allow choco.exe to return with the same exit code as the package it's installing

### ISSUE THREAD

**Issue by ramiabughazaleh** [chocolatey/choco#512]
I'd like to request allowing choco.exe to return with the same exit code as the package it's installing.

In this way, the calling process can choose how to handle a specific exit code (ex. a reboot).

This request has stemmed from two discussions:
https://github.com/mwrock/Chocolatey-Packages/issues/30
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/boxstarter/Xf0J6eWYI7s

I'm not sure if this should be the default behavior because it may cause unexpected behavior with boxstarter for example, unless boxstarter is also updated accordingly.

Thank you.

**Comment by ferventcoder** [comment]
I like it - some questions. Typically choco installs multiple packages at a time, whether through dependencies, packages.config, ir specifying multiple on the command line. When one of those fails, it is easy to say the exit code could be the same for the one that failed.

What should we do when multiple packages fail?

**Comment by icnocop** [comment]
I think the easiest implementation would be for choco to just return the exit code of the last package that failed.

If/when someone wants to know the exit code of previous package failures, we may want to add a command line parameter that instructs choco to stop immediately when any package fails.
I'm not sure if such a parameter already exists.
But in this way, it's a little more flexible.

Thank you.

**Comment by ferventcoder** [comment]
It still feels like there is an inconsistency, which can lead to weird expectations. For instance, tell me why you want this feature in the first place?

**Comment by ferventcoder** [comment]
@icnocop we do have a stop immediately flag I believe. If not, we may want to add one.

**Comment by icnocop** [comment]
I want this feature so that I could handle the exit codes programmatically myself.

For example, when testing installing a chocolatey package on a VMware virtual machine, there may be a couple of reboots required before the package has successfully been installed.

I expect to programmatically call choco.exe to install one (or more) chocolatey package(s) and wait for it to exit.

If choco.exe returns exit code -2147185721, which means a pending restart is required:
    a. Initiate a reboot of the virtual machine
    b. Wait for the virtual machine to boot and automatically login back into the desktop
    c. Call choco.exe again to continue the installation and wait for it to exit

If choco.exe returns exit code 3010, which means a reboot is required:
    a. Initiate a reboot of the virtual machine
    b. Wait for the virtual machine to boot and automatically login back into the desktop
    c. Call choco.exe again to continue the installation (for any other packages) and wait for it to exit

If choco.exe returns exit code 0, which means that all packages have successfully been installed, then I would take a virtual machine snapshot.

I'm only currently testing choco.exe with one chocolatey package at a time, but I've also included the ability to use this feature with multiple packages in the above scenario.

Thank you.

**Comment by ferventcoder** [comment]
@icnocop I'm sure you've heard of boxstarter?

**Comment by ferventcoder** [comment]
@icnocop would it be more beneficial for choco to return a special exit code for reboot required? Or do you see other use cases?

The reason I ask is that choco is meant as a unification point - instead of having to track two separate (or more) exit codes, you could track one as choco would know when an install requires a reboot.

**Comment by ferventcoder** [comment]
And for anything it didn't recognize, it could pass back that exit code instead

**Comment by icnocop** [comment]
Yes, I tried to use boxstarter.

See the discussion here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/boxstarter/Xf0J6eWYI7s

boxstarter.exe doesn't return with an exit code of the package(s) being installed either.

I'm thinking if/maybe when choco has support for this feature, then boxstarter can also be updated to support it, but I believe choco should be first because boxstarter utilizes choco in the first place.

I don't think choco should translate the exit code because different packages may have different exit codes.

**Comment by ferventcoder** [comment]
I just meant because boxstarter can handle the reboots for you.

**Comment by ferventcoder** [comment]
> I don't think choco should translate the exit code because different packages may have different exit codes.

3010 - always always always a reboot exit code for an MSI package. 

I'm not sure if you are aware of this or not, but Chocolatey is somewhat smart about the different installers and next year once it is implemented, choco will be able to handle quite a bit more automatically if one just tells Choco what type of installer it is.

**Comment by icnocop** [comment]
Yes, I noticed that Install-ChocolateyPackage already accepts an "installerType" parameter.

I just simply would like to get the exit code of the package after running Install-ChocolateyInstallPackage from either `$([System.Environment]::ExitCode` or a custom (global?) variable for example.

Thank you.

**Comment by ferventcoder** [comment]
@icnocop I understand - I'm simply seeing if there is another avenue we are not thinking about here.

**Comment by ferventcoder** [comment]
I know it's hard to see as it's easy to visualize what you already have to deal with and almost impossible to visualize something intangible.

**Comment by icnocop** [comment]
Ok, thank you! :smiley:

**Comment by ferventcoder** [comment]
Let's say we do the simple route for now - per package return

**Comment by ferventcoder** [comment]
This will now exit with the exit code of the installer. It's last in for the case of multiple packages - meaning if you pass `choco install git notepadplusplus 7zip`, the exit code may be related to 7zip. 

If you are using the API, each PackageResult will get an exit code. 

Valid Exit codes are 

 * 0 - most widely used success exit code
 * 1605 - (MSI uninstall) - the product is not found, could have already been uninstalled
 * 1614 (MSI uninstall) - the product is uninstalled
 * 1641 (MSI) - restart initiated
 * 3010 (MSI, InnoSetup can be passed to provide this) - restart required

This means that not just zero is a valid exit code anymore for choco in 0.9.10. This means some changes to providers, modules, etc that integrate with choco

* ChocolateyGUI - @gep13 @RichiCoder1 
* BoxStarter / Chef - @mwrock 
* Puppet - @puppetlabs/windows 
* DSC (cChoco) - @lawrencegripper

I can't remember off hand the Salt and Ansible folks' GitHub accounts to give them a heads up on this.

**Comment by ferventcoder** [comment]
I guess team mentions only work in the organization. 

For Puppet, besides myself - @Iristyle @glennsarti @jpogran @cowofevil @ThoughtCrhyme @kenazk. The rest of the Windows folks are not directly on this one.

**Comment by ferventcoder** [comment]
> This will now exit with the exit code of the installer. It's last in for the case of multiple packages - meaning if you pass `choco install git notepadplusplus 7zip`, the exit code may be related to 7zip.

On further review, the exit code is the last non-zero exit code of the last package that would have passed one. So in the above scenario, if  git (first install specified) returns a `1`, but notepadplusplus and 7zip both return `0`, the exit code is `1`.

**Comment by ferventcoder** [comment]
The above scenario would also hold true for package dependencies.

**Comment by ferventcoder** [comment]
Okay, now it's good to go.

**Comment by ferventcoder** [comment]
cc @elventear

**Comment by elventear** [comment]
In order to make things backwards compatible, I should use version 0.9.10 as a way to discern if this feature is available or not?

**Comment by ferventcoder** [comment]
@elventear great question - that would be one way - but the important thing for making it compatible is to notice that there are more exit codes from Chocolatey now that indicate success - `0, 1605, 1614, 1641, 3010`. If you add the additional ones as acceptable, you will already be backwards compatible as they will always exit 0.

**Comment by elventear** [comment]
What is the release timeframe?

**Comment by ferventcoder** [comment]
May

**Comment by ferventcoder** [comment]
@jfindlay FYI for Salt

**Comment by ferventcoder** [comment]
Or perhaps it is @rallytime ? :)

**Comment by jfindlay** [comment]
@ferventcoder, salted chocolate is surprisingly delicious.

**Comment by ferventcoder** [comment]
FYI @lawrencegripper

**Comment by ferventcoder** [comment]
Oh wait, I got you in the original notification. 👍

**Comment by ferventcoder** [comment]
I just filed all the relevant bug reports. 👍

**Comment by RichiCoder1** [comment]
Somehow I missed this issue. I'll work on making sure ChocolateyGUI recognizes and alerts to non-zero and reboot codes.

**Comment by ferventcoder** [comment]
@RichiCoder1 sorry man! Totally forgot to mention this to you :/

**Comment by RichiCoder1** [comment]
Nah, you mentioned me here https://github.com/chocolatey/choco/issues/512#issuecomment-214284461 hence why I noticed this now :)

**Comment by basictheprogram** [comment]
Attempting to upgrade the chocolatey package called DraftSight

https://chocolatey.org/packages/draftsight

Ansible win_chocolatey throws a 1603 error

Microsoft says, "Windows Installer is attempting to install an app that is already installed on your PC"

https://support.microsoft.com/en-us/help/834484/you-receive-an-error-1603-a-fatal-error-occurred-during-installation-error-message-when-you-try-to-install-a-windows-installer-package

Upgrading with "cup all" works fine.

Putting this here as it looks like 1603 might be another one of these exit codes?

**Comment by ferventcoder** [comment]
@basictheprogram 1603 is a generic error, but rest assured that it is not one of the known good exit codes. Each package can implement their own valid exit codes so if there is a particular exit code an app passes that indicates success that is not one of the defailts, they can passs those in through the package itself.

**Comment by basictheprogram** [comment]
Why doesn't  "cup all" or "choco upgrade draftsight" not error? Only when I try to upgrade the package via win_chocolatey does it error.

Looking at the win_chocolatey code it invokes choco so I'm guessing  cup and choco.exe are less picky about exit codes?

**Comment by ferventcoder** [comment]
@basictheprogram looks like `win_chocolatey` may be coming over WinRm, so you should keep that in mind when using Ansible.

**Comment by ferventcoder** [comment]
Not a ton of info in that response sorry. WinRM may behave differently. Ensure you are on the most up to date version of the Chocolatey module and a very recent version of Ansible as well.

**Comment by basictheprogram** [comment]
I run devel branch from Ansible git repository, updated daily.


--
Bob Tanner <tanner@real-time.com>                                 | Phone : 952-943-8700
http://www.real-time.com, Linux, OSX, VMware, Windows | Fax      : 952-943-8500
Key fingerprint = 9906 320A 8BB6 64AD 96A7  7785 CBFB 10BF 568B F98C
