### ISSUE TITLE
Support for msp files

### ISSUE THREAD

**Issue by tobias-geiser** [chocolatey/choco#518]
Would be great to have an additional filetype in Install-ChocolateyInstallPackage.ps1

  if ($fileType -like 'msp') {
    $msiArgs = "/p `"$file`""
    if ($overrideArguments) {
      $msiArgs = "$msiArgs $additionalInstallArgs";
      write-host "Overriding package arguments with `'$additionalInstallArgs`'";
    } else {
      $msiArgs = "$msiArgs $silentArgs $additionalInstallArgs";
    }

    Start-ChocolateyProcessAsAdmin "$msiArgs" 'msiexec' -validExitCodes $validExitCodes
    #Start-Process -FilePath msiexec -ArgumentList $msiArgs -Wait

**Comment by ferventcoder** [comment]
I'm surprised an issue isn't already logged?

**Comment by ferventcoder** [comment]
Duplicate of #509.
