### ISSUE TITLE
cyg-get fails when cygwin32 and cygwin64 are both installed

### ISSUE THREAD

**Issue by mnuzzolilo** [chocolatey/choco#521]
Traced the issue to cyg-get.ps1, the line below creates an array of two paths when both are found
```
    $cygRoot = @($local_key, $local_key6432) | ?{Test-Path $_} | Get-ItemProperty | Select-Object -ExpandProperty rootdir
```
Then the line here combines the paths for the 32 and 64 bit installations.  
```
$cygwinsetup = "$cygRoot\cygwinsetup.exe"
```

**Comment by ferventcoder** [comment]
Unfortunately this is not a Chocolatey issue. It's an issue with the cyg-get package and should be logged with that. You can do that over at https://github.com/chocolatey/chocolatey-coreteampackages
