### ISSUE TITLE
Add variable substitution to choco pack

### ISSUE THREAD

**Issue by AeliusSaionji** [chocolatey/choco#522]
https://github.com/chocolatey/choco/wiki/AutomaticPackages
Since `choco pack` doesn't support passing any of the variables for automatic packages, it cannot be used on packages configured for automatic use.

I have just been using chocopkgup while testing my packages, but I've just learned that it will stop working when the license expires. However negligible the downtime actually is, imo it's a good idea to not be entirely reliant on a tool that has a built in self destruct :)

Also, chocopkgup pushes by default and I never remember to include the /nopush argument. In that light, having a distinct "local test" and "push finished" (choco pack and choco push) as two separate things makes a lot of sense.

**Comment by ferventcoder** [comment]
chocopkgup has been updated. I forget about the timezone differences sometimes...

**Comment by pauby** [comment]
I'm unsure what this issue is referring to. Adding variable substitution to `choco pack` is not something we are moving towards.

Given it's from 9 years ago, I'm going to go ahead and close it. We can always reopen it again if necessary.
