### ISSUE TITLE
nuspec created by "choco new" command contains UTF-8 BOM

### ISSUE THREAD

**Issue by qzo** [chocolatey/choco#529]
This violates a recommendation here:
https://github.com/chocolatey/choco/wiki/CreatePackages#character-encoding

**Comment by ferventcoder** [comment]
Not sure what this hurts though?

**Comment by ferventcoder** [comment]
Is this a bug?

**Comment by qzo** [comment]
Description added above (BOM in nuspec violates recommendation in the wiki).
