### ISSUE TITLE
install/upgrade/uninstall - allow confirming for remaining installs (aka Yes to All)

### ISSUE THREAD

**Issue by DarwinCSIWindowscom** [chocolatey/choco#53]
Choco seems to want a confirmation for each dependency.  It would be helpful to have an option on each prompt that says "Confirm all subsequent dependencies for package x".  Would be helpful to have this option on every dependency confirm prompt.

Similar to #52

**Comment by ferventcoder** [comment]
No versions. Please ensure you've read our [SUBMITTING ISSUES](https://github.com/chocolatey/choco#submitting-issues) and [CONTRIBUTING](https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md) documents. This clearly falls into the latter. It may be more appropriate for you to jump into gitter and talk through some things you would like to see prior to filing tickets. https://gitter.im/chocolatey/choco

**Comment by ferventcoder** [comment]
How would you have this work when the command line is `choco install packages.config` or `choco install git ruby notepadplusplus`? 

It seems better if you would have the option on the prompt to confirm all future items.

**Comment by DarwinCSIWindowscom** [comment]
Sorry for the wrong submission location.  I know I don't have time to usher this one through some type of acceptance process - not sure if there is a way to drop them somewhere.

With the suggestion I was trying to strike a balance with your new initiative to prompt on packages.  So if the most conservative is to prompt for each dependency and the most permissive is to set a config file to confirm everything - this is a possible middle ground.

So if multiple packages are being installed, either default to one prompt that includes all dependencies or have an option that says "yes and yes to all dependencies"

Maybe the first prompt lists the dependencies so I know what I am accepting with "yes to all dependencies" - This is what YUM on linux does.  It also lists the file sizes.

Prompting for each dependency feels a little too much like UAC prompts when trying to copy files from a network share to the c:\windows folder did under Windows Vista RTM.

**Comment by ferventcoder** [comment]
Yeah, it could get crazy... :/

**Comment by ferventcoder** [comment]
I reworked the ticket up though so no worries :)

**Comment by etiennebr** [comment]
I agree with the *Yes to All* suggestion and would add that looping through all the confirmations before installing any package (not sure if that's possible) would allow to respond yes/no to all packages if you need to cherry pick and then batch install the packages rather then actually confirming one, then installing (can take a while), then asking for another confirmation, etc. First ask for all confirmations, then install; I think it would be easier for the user.

**Comment by ferventcoder** [comment]
This is completed and will be available for v0.10.14.

**Comment by ferventcoder** [comment]
This is not exactly in the format I would have really liked to get to. However to be able to list everything like you see in Yum and then ask you to continue or not, we need to own more of the graph so we can inspect and gather the information ahead of time. This does however allow you to pre-confirm all remaining installs, so there is still value in this getting released in the way it can be implemented for now.
