### ISSUE TITLE
Manage package templates with a specially named package and special package folder

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#542]
Package should be named ".template" - folder name is templates.

**Comment by ferventcoder** [comment]
Related to #76 and #449.

**Comment by gep13** [comment]
@ferventcoder is this referring to a Chocolatey Package?  If so, which one?

**Comment by ferventcoder** [comment]
No packages exist for this yet that I know of.

**Comment by gep13** [comment]
@ferventcoder gotcha, the way I read this issue, the default templates were going to ship as a package as well.  My bad.

**Comment by ferventcoder** [comment]
;)

**Comment by ferventcoder** [comment]
Forgot one little bit - automation scripts under this folder should not be evaluated.

**Comment by ferventcoder** [comment]
Okay, there we go.

**Comment by ferventcoder** [comment]
> Gotcha, the way I read this issue, the default templates were going to ship as a package as well. My bad.

It would be great to fix the default template outside of a Chocolatey release, so I give you https://chocolatey.org/packages/default.template.

**Comment by gep13** [comment]
Woo hoo! :+1:

**Comment by aronovgj** [comment]
That package fails on newest beta

**Comment by ferventcoder** [comment]
Did you miss the comment on the package page? It's expected to fail.

**Comment by ferventcoder** [comment]
@aronovgj see https://github.com/chocolatey/choco/commit/d5f09bf2fff7eef9712751e6b194d815814afe0f

**Comment by aronovgj** [comment]
Thought the validator/verifier were expected to fail...

**Comment by ferventcoder** [comment]
@aronovgj I just pushed a new beta that should not fail on this.

**Comment by ferventcoder** [comment]
It's still under automated review though.

**Comment by aronovgj** [comment]
:+1: worked
