### ISSUE TITLE
New Chocolatey Helper "Pending Reboot"

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#544]
Visual Studio is a package that takes a very long time and then fails when a reboot is pending.

I have a oneliner that is an abbreviated version of: 

https://gallery.technet.microsoft.com/scriptcenter/Get-PendingReboot-Query-bdb79542

that I would like to code up as a helper.

**Comment by ferventcoder** [comment]
@DarwinJS let's discuss what you think this should do first.  What would be the purpose of this helper?

**Comment by DarwinJS** [comment]
It would be handy for:
* Packages like Visual Studio which will fail with a uninformative error message could instead say "This package can't run if a reboot is pending, please reboot and try again."
* After a package runs it could be called to give the warning "This package requires a reboot, please be sure to reboot before using the software it installed"

Actually for the second one I wish choco did that built in after each package has run - something like "Warning: this package or something that ran before it requires a reboot" and also possibly a variable that tracks when a reboot is needed."

I guess if Choco checked at the beginning and end of every package and displayed a warning it would be helpful.

There have been times I have run a TON of automation and no reboot is needed - so it's good to know when one absolutely is.  

Also when non-installation tech people run choco upon my recommendation - they just aren't thinking "Hmmm, I bet choco supresses reboots and I'll generate a lot of unnecessary support calls if I don't reboot before using the items I just installed."

D.

**Comment by DustinVenegas** [comment]
This has definitely been an issue for me since some installs succeed silently if a reboot is necessary. I've had to resort to checking `HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired` before critical sections during automated scripts.

**Comment by DarwinJS** [comment]
With this oneliner I check two other places, but not 
pending computer rename, pending domain join or SCCM reboot.

**Comment by ferventcoder** [comment]
> * After a package runs it could be called to give the warning "This package requires a reboot, please be sure to reboot before using the software it installed"

Chocolatey itself is going to provide this.

**Comment by ferventcoder** [comment]
> Actually for the second one I wish choco did that built in after each package has run - something like "Warning: this package or something that ran before it requires a reboot" and also possibly a variable that tracks when a reboot is needed."

Ha! I hadn't read that far yet!

**Comment by ferventcoder** [comment]
@DarwinJS @DustinVenegas I already know every thing that we'd need to check for whether a reboot is required - we capture all of that - https://github.com/puppetlabs/puppetlabs-reboot/blob/7f0c2bfc84a4bb4c706d79195b6574259a9745bb/lib/puppet/provider/reboot/windows.rb#L73-L199

**Comment by DarwinJS** [comment]
@ferventcoder - Cool!  Will it be exposed as a variable?

So it seems like a helper might still be nice when it is *known* that a setup.exe will self-block if a reboot is pending?

Maybe for now it could be my oneliner and when choco has built-in support the helper is refactored to just check the built-in variable?

**Comment by ferventcoder** [comment]
There are a few steps that need to fall into place first before this - most of that is already in 0.9.10, but the bigger one is getting the install-chocolateyinstallpackage known to Chocolatey C# so it can handle providing more information surrounding the exit code of the software (in addition to making the checks).

**Comment by ferventcoder** [comment]
And possibly a variable - it seems like we'd need something to be provided - so a package can fail until no pending reboot is required.

**Comment by ctmcisco** [comment]
Hello, I am looking creating a Choco package that requires a reboot after install. I assume this is not built in to Choco? I ran the get-pedingreboot function to confirm the pending reboot. The install goes well but Choco gives out an error and does supress the reboot I notice in debug. Is there a work around that can be implemented. Does the paid version handle this? I also may try to couple with Boxstarter and integrate the reboot in the chocoinstall script.

**Comment by DarwinJS** [comment]
@bcurran3 - if you haven't had the chance, you might want to read my blog on this exact topic and steal my code ;) https://cloudywindows.io/post/continue-your-automation-to-run-once-after-restarting-a-headless-windows-system/

**Comment by bcurran3** [comment]
Thanks @DarwinJS. Just read (most of) it and I think Example 3: Oneliner Self-Deleting With No Script File is a great method to accomplish this. You just saved me a lot of time testing/debugging/failing!

**Comment by DarwinJS** [comment]
You'll want to keep in mind that there are a lot of potential State differences in a machine that is running a package in the scheduler versus the wherever it originally ran.  For instance availability of the network due to user proxy settings. Or availability of any network resources due to user authentication requirements. Most systems that support a reboot like you are proposing use a policy of copies of all needed files locally before the reboot. E.g.SCCM is one of these systems.

**Comment by abmoham** [comment]
Agreed, those are the nuances of a software deployment system vs the current ‘client’ feedback to ensure local package installation (wrt: the reboot flag before and/or after installing a package).

**Comment by bcurran3** [comment]
I've opened an issue for myself as a reminder to experiment with this idea, https://github.com/bcurran3/ChocolateyPackages/issues/27.  Any thoughts and feedback are welcome there.

**Comment by bcurran3** [comment]
FYI: I did create a helper extension that checks and warns on pending reboot. It also pauses when the Windows Installer is busy (hopefully heading off a some of those MSIEXEC install errors) as well as when it finds multiple instances of choco.exe running. It's PRE release right now as I'd still like to do some post install handling of errors for possible retry at reboot... if I can figure it out.

Anyone who wants to play guinea pig and provide feedback can look at https://chocolatey.org/packages/chocolatey-preinstaller-checks.extension - I'm pretty confident all the pre-install checking is 100%.

**Comment by DarwinJS** [comment]
I would suggest that this module be passive - only log about possibly concerning situations and set variables to indicate they exist.  Then separately look into which of these might merit building "handlers" - the handlers should be opt-in only - at the package level.  Once their code is working well you could consider global opt in for ones that prove their value and stability.

But I would not mix passive checking with taking actions to resolve conditions.

Also, on reboot pending check report the detailed reason one is pending - just like get-pendingreboot.

**Comment by SwapnilSoni1999** [comment]
I'm still facing this on Windows 11

**Comment by pauby** [comment]
Chocolatey CLI uses [exit codes to indicate if a reboot is required](https://docs.chocolatey.org/en-us/choco/commands/upgrade#exit-codes). This was added in 0.10.14 of Chocolatey CLI initially.

I'm going to go ahead and close this issue, but we can always reopen it again if needed.
