### ISSUE TITLE
Get package dependencies

### ISSUE THREAD

**Issue by gregsdennis** [chocolatey/choco#550]
I'd like to see a feature where I can get dependencies of packages that are currently installed.

I can see this as part of the `list -lo` command (an additional switch) or a new command.  May be simpler to query a single package at a time.

**Comment by wickles** [comment]
I can't find any way to list dependencies now except looking at the listing on <https://community.chocolatey.org>. This should be a basic feature of `choco info <package>`.

Also is this a duplicate? #1276
