### ISSUE TITLE
Unable to install without providing "--version"

### ISSUE THREAD

**Issue by c33s** [chocolatey/choco#553]
Yesterday I tried to install Libre Office

```choco install libreoffice```

which resulted in

```
Installing the following packages:
libreoffice
By installing you accept licenses for the packages.
libreoffice not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
 - libreoffice
```
running it with the version parameter works:

```choco install libreoffice --version=5.0.4```

today i noticed also the update process is also broken
```
--- snip ---
chocolatey was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"
libreoffice was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"
markdown-edit v1.17.1 is the latest version available based on your source(s).
notepadplusplus was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"
notepadplusplus.install was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"
putty v0.66 is the latest version available based on your source(s).
--- snip ---
```
worked without problem before (with my configured proxy)

**Comment by ferventcoder** [comment]
@c33s this looks to be something environmental?

The last part of your message mentions something about a proxy - can you expand on that?

**Comment by ferventcoder** [comment]
Also when submitting issues, please see https://github.com/chocolatey/choco#submitting-issues and provide what is asked for. Thank you!

**Comment by c33s** [comment]
sorry for not reading...

i disabled the proxy, then it works.
it looks like choco doesn't look for the environmental variables `http_proxy` & `https_proxy` it only looks for the proxy setting made in internet explorer (which is a little bit odd).


with the proxy enabled i ran:

powershell version 4
```
$PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1
```

`choco upgrade libreoffice --debug --verbose`

log output: https://gist.github.com/c33s/7f51a12ac561e377d4c3#file-libreoffice-sh

`choco upgrade chocolaty --debug --verbose`
log output: https://gist.github.com/c33s/7f51a12ac561e377d4c3#file-chocolaty-sh


but i don't understand its behavior, other packages install quite fine with the proxy:

`choco upgrade git`

```
...
Using system proxy server 'proxy.provider.com:1080'.
...
The upgrade of git was successful.
...
```
upgrade all partly works (with proxy)
https://gist.github.com/c33s/7f51a12ac561e377d4c3#file-all-sh

is the problem in the protocol (http vs https)? any clues how to debug?

**Comment by ferventcoder** [comment]
I'm just going to leave this here - https://github.com/chocolatey/choco/wiki/Proxy-Settings-for-Chocolatey

**Comment by c33s** [comment]
the mail problem is, that choco work with proxy for some packages but some packages don't work. so its not about getting choco to run with a proxy server, it's about "why don't all packages work with proxy"

my last `choco upgrade all` https://gist.github.com/c33s/7f51a12ac561e377d4c3#file-update_all-sh 

there you can see

```
 - chocolatey
 - notepadplusplus.install
 - libreoffice
 - notepadplusplus
```
failed but
```
 - jre8
- markdown-edit
- PhantomJS
```
worked.

i thought it has something to do with https/http but it was not the problem:

- markdown-edit: https (https://github.com/mike-ward/Markdown-Edit/releases/download/v1.21/MarkdownEditSetup.msi)
- jre8: http://javadl.sun.com/webapps/download/AutoDL?BundleId=114687

**Comment by ferventcoder** [comment]
So the other issue you logged, is that something you believe fixes this issue?

**Comment by c33s** [comment]
no, the other issue is just an enhancement, having the normal behavior of command line tools like lynx, wget, ...

**Comment by ferventcoder** [comment]
Right on.

**Comment by SolykZ** [comment]
Hello there,

I'm having the same issue except that I don't use any proxy. I'm unable to install a custom package without providing a --version parameter.

Would you give me some piece of help to resolve this, please?

Regards,
Chris.

**Comment by ferventcoder** [comment]
@SolykZ url to what you are attempting to install?

**Comment by ferventcoder** [comment]
@SolykZ also include the link to a gist of your install attempt, with `-d -v` added to it.

**Comment by SolykZ** [comment]
The package is a private MS Office 2016 installer for the office I work in.

It worked great when I was installing it with the --version argument. I wanted to show you debug information but...this time the installation went well! I don't really get it. 

I'll repost here if the problem occurs again. Thanks for your help.

**Comment by ferventcoder** [comment]
@SolykZ It may be an issue with your private source.

**Comment by ferventcoder** [comment]
Depends on if it is listed as a prerelease in the version as well. If the version contains any `-` in it, then you also need to pass `-pre`

**Comment by Spitzbub** [comment]
I ran into this issue as well - my version contained a `-` and so I had to pass `--pre` to install it. The only issue is that the error message I got without `--pre` was not at all helpful. I got all the way through to creating a bug report when I found this existing bug. Can we use this bug to improve the error message or shall I open another bug for that?

```
C:\Users\RussellMora\Dropbox (aboutGolf)\Chocolatey\aG Sim Setup\agsimsetup\src\main>choco install agsimsetup.2.2.1.0-b40.nupkg
Installing the following packages:
agsimsetup.2.2.1.0-b40.nupkg
By installing you accept licenses for the packages.
agsimsetup not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "C:\Users\RussellMora\Dropbox (aboutGolf)\Chocolatey\aG Sim Setup\agsimsetup\src\main"

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
 - agsimsetup

C:\Users\RussellMora\Dropbox (aboutGolf)\Chocolatey\aG Sim Setup\agsimsetup\src\main>choco install --pre agsimsetup.2.2.1.0-b40.nupkg
Installing the following packages:
agsimsetup.2.2.1.0-b40.nupkg
By installing you accept licenses for the packages.

agsimsetup v2.2.1.0-b40
The package agsimsetup wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting
 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
Do you want to run the script?
 1) yes
 2) no
 3) print
```

**Comment by ferventcoder** [comment]
@Spitzbub please create a new issue.

**Comment by ferventcoder** [comment]
I'm going to close this as possibly an issue with the community repository that has been fixed since. If you run into this issue again, feel free to comment and we can reopen.

**Comment by vinayakmankal** [comment]
If you have used fiddler it messes with the proxy. Try turning fiddler on and running the commands

**Comment by Zedonboy** [comment]
Wait this is getting serious.......i have no idea the proxy i should use?

**Comment by b47on** [comment]
Just happened to me after fresh install. Choco 0.10.7 on  windows 10 pro, behind proxy (windows authentication) 

C:\Windows\system32>cinst conemu
Chocolatey v0.10.7
Installing the following packages:
conemu
By installing you accept licenses for the packages.
[NuGet] Exception has been thrown by the target of an invocation.
conemu not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"

but 

cinst conemu --version 17.6.5.0

works fine (and report that it is "Using system proxy server '192.168.xx.xx:8080'.")

**Comment by ferventcoder** [comment]
@b47on I'd love to know more about that exception.

**Comment by ferventcoder** [comment]
@b47on Let's move the discussion over to https://github.com/chocolatey/choco/issues/1343
