### ISSUE TITLE
Wiki - Add a vendor intro/landing page that answers questions they may have, including takeover

### ISSUE THREAD

**Issue by jnm2** [chocolatey/choco#555]
The ideal situation is to have vendors maintain their own packages directly.

When members of the community want to facilitate this, encouraging vendors to add their software to Chocolately or to take over an existing package, they often have questions. It would be handy to be able to link a page bringing vendors up to speed on what they can do with Chocolatey: what it's about and steps forward.

**Comment by jnm2** [comment]
Closing due to lack of response.

**Comment by pauby** [comment]
@jnm2 I think this would be a good addition to the site so I'm re-opening it. We'll get to it.

**Comment by TheCakeIsNaOH** [comment]
This exists here: https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#are-you-a-software-vendor

**Comment by gep13** [comment]
@TheCakeIsNaOH agreed, this has been covered in docs, and can be closed.
