### ISSUE TITLE
Placement of the "You have {x} v{y} installed. Version {z} is available based on your source(s)' is wrong.

### ISSUE THREAD

**Issue by cpmcgrath** [chocolatey/choco#557]
When you upgrade multiple items, the transition from one to the next looks like this...
![chocoissue](https://cloud.githubusercontent.com/assets/1791243/12406241/ff06f388-be96-11e5-8f80-271d2996a244.png)

This associates the yellow line with the first block of data. It of course has nothing to do with that block and everything to do with the next block.

A new line should be added before the yellow line, and preferably the new line after it removed.

**Comment by ferventcoder** [comment]
Thanks for logging this!
