### ISSUE TITLE
Register choco uninstall in Programs and Features for appropriate packages

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#566]
This is more for internal packages - not community ones.

For our DevOps I am creating packages for installers that are resistant to automation.  These packages may be "copy a few files, register DLLs, etc"

It would be great if I could call something like:

Add-ChocolateyProgramsandFeatures "displayname", "size", "publisher", "version"

Then the routine creates "uninstallstring" => "choco uninstall packageid -confirm"

If I don't specify version it could use the package version - but I really need a version override because non-chocolatey people who use Add/Remove programs will want to see the _actual_ version number, not my choco version number or they will call me about the discrepancy.

Currently I am constructing my own regkey - but it seems making it a part of choco could benefit others as well.

Having this as an option could also be helpful if a packager chooses to create a Programs and Features item for an install that is actually "portable".

Something to keep in mind - the Uninstall key is accessed by many, many inventory products - not just human eyes.  So this could also give "inventory-ability" to hundreds of commercial management products for portable software installed by chocolatey.

Also - I am not making a case that this be the default behavior of chocolatey - but rather It could be implemented as an opt in helper at the packager's discretion and I'm assuming it would not be used for packages where a native installer already puts a program and features item up.

**Comment by ferventcoder** [comment]
This is a planned feature for the pro version.

**Comment by DarwinJS** [comment]
Excellent - will it have a prompt for "Uninstall" and "Reinstall" (choco install packageid -force) ?

**Comment by ferventcoder** [comment]
This was completed in June 2017 with [Chocolatey Licensed Extension v1.10.0](https://chocolatey.org/docs/release-notes-licensed#june-9-2017).

The feature page is at https://chocolatey.org/docs/features-synchronize#all-packages-in-programs-and-features

It is 100% automatic, just use C4B and run `choco feature enable -n showAllPackagesInProgramsAndFeatures`. Then run choco one time for it to take effect.

![image](https://user-images.githubusercontent.com/63502/30489374-b945e7da-99fc-11e7-9414-86d5131233e2.png)
