### ISSUE TITLE
Sync "choco installed status" with "Windows Installed status"

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#567]
I think it would be great if choco completely relied on Windows built-in "installed" indicators rather than maintaining it's own.

However, if that is not possible it would be great if each time choco ran it checked if the uninstall key of any of it's "installed" packages was still valid.   If any were found to be out of sync, unmark the "choco installed status"

This would likely require tracking the "windows isntalled status" indicators in each package's meta data.

It would be nice if the presence of a file or regkey beside the uninstall key could be used in addition to the uninstall key as it would give further flexibility.

**Comment by ferventcoder** [comment]
This is a planned feature for the pro version.

**Comment by ferventcoder** [comment]
Related to #755

**Comment by ferventcoder** [comment]
This will be available coming up in the Pro / Business versions.

**Comment by gep13** [comment]
AWESOME! :smile:

**Comment by DarwinJS** [comment]
Very cool!

**Comment by ferventcoder** [comment]
![synchronize](https://raw.githubusercontent.com/wiki/chocolatey/choco/images/features/features_synchronize.png)

**Comment by DarwinJS** [comment]
Awesome!
Does the sync only happen upon a listing or upon any choco command?

**Comment by ferventcoder** [comment]
I know the wording is small if you didn't open the image up and look at the full image, but it's written there "any Chocolatey command will trigger synchronization"
