### ISSUE TITLE
Missing part of the error log in Powershell Host

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#569]
https://gist.github.com/choco-bot/ccc42d226087faf5ba33#file-install-txt-L171-L172

**Comment by ferventcoder** [comment]
This is due to the console.write for download overriding the error message.

**Comment by pauby** [comment]
The gist for this is missing and there is not enough information to go on. I'm going to go ahead and close this, but we can always reopen it if necessary.
