### ISSUE TITLE
Explain how to workaround a failing uninstall

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#573]
https://gitter.im/chocolatey/chocolatey.org?at=56a2ba4e6b6468374a090345

**Comment by maxsu** [comment]
I was having trouble uninstalling package with a broken chocolateyUninstall.ps1, and finally came across the -n trick in the chat linked above.

I'd like to modify the [wiki entry](https://github.com/chocolatey/choco/wiki/CommandsUninstall) with a note on how to uninstall failing/manually uninstalled packages. The current document does mentions the consequences of turning off the autouninstaller, but does not frame it in the context of failing uninstalls.

Proposal: Add the following paragraph after the "With auto uninstaller turned off.." paragraph:

To uninstall a package that has been uninstalled manually and chocolatelUnistall.ps is fails, uninstall with the `-n` flag

Is that sufficient?

**Comment by ferventcoder** [comment]
@maxsu are you signing up to take on this task or proposing wording for the change? :)

**Comment by ferventcoder** [comment]
Consider that the wiki is autogenerated from this - https://github.com/chocolatey/choco/blob/dc74d618422df4e533dfa7aaf726ce54bf18ce83/src/chocolatey/infrastructure.app/commands/ChocolateyUninstallCommand.cs#L159-L163

**Comment by maxsu** [comment]
Thanks for pointing to the right location, I wasn't clear on where that documentation lived!

**Comment by ferventcoder** [comment]
@maxsu did you see that you filed the PR against your repository and not this one? Could you file the pull request against this repo so we can get it pulled in? Thanks!

**Comment by maxsu** [comment]
Sorry. I'm a bit new to git/github. First ever pull request! Very embarassing!
