### ISSUE TITLE
Installing python3-3.5.1 generates *.exe.ignore in cwd.

### ISSUE THREAD

**Issue by DHowett** [chocolatey/choco#574]
It looks like `$destinationFolder` (line 25 in python3-3.5.1's chocolateyInstall.ps1) is empty and defaults to cwd. Running this from `%SYSTEMROOT%` proves to be a bad idea.

```
python3 v3.5.1
WARNING: The names of some imported commands from the module 'chocolateyInstaller' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
Downloading python3 64 bit
  from 'https://www.python.org/ftp/python/3.5.1/python-3.5.1-amd64.exe'
Progress: 100% - Saving 28.25 MB of 28.25 MB (29627072/29627072)
Download of python3Install.exe (28.25 MB) completed.
Installing python3...
python3 has been installed.
Access to the path 'C:\WINDOWS\system32\Boot\winload.exe.ignore' is denied.
Access to the path 'C:\WINDOWS\system32\Boot\winresume.exe.ignore' is denied.
Access to the path 'C:\WINDOWS\system32\DriverStore\FileRepository\64dp4256.inf_amd64_9191bdaf5e95d43e\difx64.exe.ignore' is denied.
Access to the path 'C:\WINDOWS\system32\DriverStore\FileRepository\64dp4256.inf_amd64_9191bdaf5e95d43e\DPTopologyApp.exe.ignore' is denied.
Access to the path 'C:\WINDOWS\system32\DriverStore\FileRepository\64dp4256.inf_amd64_9191bdaf5e95d43e\DPTopologyAppv2_0.exe.ignore' is denied.
Access to the path 'C:\WINDOWS\system32\DriverStore\FileRepository\64dp4256.inf_amd64_9191bdaf5e95d43e\GfxUIEx.exe.ignore' is denied.
Access to the path 'C:\WINDOWS\system32\DriverStore\FileRepository\64dp4256.inf_amd64_9191bdaf5e95d43e\Gfxv2_0.exe.ignore' is denied.
Access to the path 'C:\WINDOWS\system32\DriverStore\FileRepository\64dp4256.inf_amd64_9191bdaf5e95d43e\Gfxv4_0.exe.ignore' is denied.
Access to the path 'C:\WINDOWS\system32\DriverStore\FileRepository\64dp4256.inf_amd64_9191bdaf5e95d43e\igfxCUIService.exe.ignore' is denied.
Access to the path 'C:\WINDOWS\system32\DriverStore\FileRepository\64dp4256.inf_amd64_9191bdaf5e95d43e\igfxEM.exe.ignore' is denied.
Access to the path 'C:\WINDOWS\system32\DriverStore\FileRepository\64dp4256.inf_amd64_9191bdaf5e95d43e\igfxext.exe.ignore' is denied.
Access to the path 'C:\WINDOWS\system32\DriverStore\FileRepository\64dp4256.inf_amd64_9191bdaf5e95d43e\igfxHK.exe.ignore' is denied.
```

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco#submitting-issues

**Comment by ferventcoder** [comment]
This appears to be an issue with a package. Please read over https://github.com/chocolatey/choco/wiki/PackageTriageProcess and follow up with the maintainers. Thanks!

**Comment by joelhandwell** [comment]
@DHowett did you get any solution for this?

**Comment by ferventcoder** [comment]
@joelhandwell this needs to go back to the package maintainers to fix in the package. AFAIK, that's really going to be the only solution. Are you running into a similar issue with a package?

**Comment by joelhandwell** [comment]
@ferventcoder I googled for work around and not find, ended up using msi installer downloaded from official python website without this message. So this issue may something related with the way how chocolatey install script handle msi. I reported in python bug tracker: http://bugs.python.org/issue27489

**Comment by ferventcoder** [comment]
@joelhandwell Good, it looks like http://bugs.python.org/issue27489 was closed.

**Comment by DHowett** [comment]
It appears as though it was resolved as "third party", wherein they've
shifted the blame back on chocolatey? It's happening here:
https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/python3/tools/chocolateyInstall.ps1#L29

I'll follow up with a bug filed to the package maintainers.

-- Dustin L. Howett

**Comment by ferventcoder** [comment]
Yes sir. I originally mentioned it was the package itself and not python's installer

**Comment by DHowett** [comment]
Sorry, just closing the loop :)

-- Dustin L. Howett
