### ISSUE TITLE
Uninstalling package failed when manual upgrade was done

### ISSUE THREAD

**Issue by schallm** [chocolatey/choco#577]
I had installed linqpad4 using chocolatey.  When Linqpad 5 came out, I installed the update "manually" using the MSI from Linqpad's site.  Chocolatey now thinks 4.51.03 is installed, but it is not.  Trying to cleanup chocolatey, I tried to uninstall it using:

```
choco uninstall linqpad4
choco uninstall linqpad4 --version 4.51.03
choco uninstall linqpad4 --all-versions
```

they all returned:

```
Uninstalling the following packages:
linqpad4
linqpad4 not uninstalled. An error occurred during uninstall:
 Unable to uninstall 'linqpad4 4.51.03' because 'linqpad 4.51.03' depends on it.
```

--force did resolve the issue...

```
choco uninstall linqpad --force
```

From https://groups.google.com/d/msgid/chocolatey/CALn20hLGXYCuJ9ofjwjwgu%3DxRfgWp4MEoA9a_upNQ738TgiK3Q%40mail.gmail.com?utm_medium=email&utm_source=footer

**Comment by ferventcoder** [comment]
That is the weirdest issue I've seen from NuGet as a reason not to uninstall a package.

**Comment by dragon788** [comment]
I've seen a similar issue with the javaruntime and jre8 and server-jre and server-jre8 though not the same error message. If you mess with the package behind the virtual package it can confuse chocolatey. You can also try the -x (check dependencies and act on them as well) or its inverse that ignores the dependencies.
