### ISSUE TITLE
allow authorized clients to remove packages from a simple server feed.

### ISSUE THREAD

**Issue by christonog** [chocolatey/choco#578]
Referencing this conversation:

![image](https://user-images.githubusercontent.com/12760779/141297179-725793de-7a9e-4311-9f32-9c16a22e19dd.png)

If I am hosting my own Chocolatey feed, I (as an authorized client) would like to remove packages from that feed. This feature might be more suitable for a hosted gallery, where authorization can be added to an issued api key,but I think it can be valuable as well for a simple feed.

UPDATE: As Chocolatey Gitter chat is now unavailable, I've added a screenshot of the Gitter chat.

**Comment by pauby** [comment]
As [Simple Server will be archived](https://github.com/chocolatey-community/simple-server/issues/63), I don't feel this issue is required any more. I'm going to go ahead and close this, but we can reopen it if necessary.
