### ISSUE TITLE
AutoUninstaller config set to enabled but not working

### ISSUE THREAD

**Issue by laurin1** [chocolatey/choco#579]
From https://groups.google.com/d/msgid/chocolatey/CAJ1wz_hOHpULVJY5RjDS1sW-5NLjgdcj-xLXbxNi0dE5L9C6yg%40mail.gmail.com?utm_medium=email&utm_source=footer

**C:\Windows\System32>cuninst javaruntime
Uninstalling the following packages:
javaruntime**

**javaruntime v8.0.60
 Skipping auto uninstaller - AutoUninstaller feature is not enabled.
 javaruntime has been successfully uninstalled.**

But....

**C:\Windows\System32>choco config set --name autoUninstaller --value=Enabled
Nothing to change. Config already set.**

https://gist.github.com/laurin1/d643cddc0946ed2b4c14

**Comment by gep13** [comment]
Should this not be:

`choco feature enable -n=autoUninstaller`

since this is a feature, not a config parameter

`choco feature -h` for more information.

**Comment by ferventcoder** [comment]
@laurin1 can you determine if this is the problem?

**Comment by laurin1** [comment]
Yes, that works.

**Comment by ferventcoder** [comment]
Thanks for letting us know. Apologies for any confusion.
