### ISSUE TITLE
Little command name correction on init.ps1

### ISSUE THREAD

**Issue by RobDesideri** [chocolatey/choco#595]
choco/nuget/chocolatey/tools/init.ps1 row 19: "Init**ilia**ze-Chocolatey" instead "Ini**tiali**ze-Chocolatey".

**Comment by ferventcoder** [comment]
thanks.

**Comment by ferventcoder** [comment]
Thanks for noting that.

**Comment by maharishi** [comment]
Let me know if you want me to pick this up... Not sure how this works... New to open source contribution. Should i just change the file and send a pull request?

**Comment by ferventcoder** [comment]
We talked in Gitter - I mentioned reading both the readme and the contributing document.

**Comment by ferventcoder** [comment]
Usually this would be a maint commit.

**Comment by ferventcoder** [comment]
Merged into stable at https://github.com/chocolatey/choco/commit/fdf3fbf705bb8891ebb7c782d2e97d08039dbd70
