### ISSUE TITLE
pack - Nuspec validation on choco pack

### ISSUE THREAD

**Issue by laedit** [chocolatey/choco#602]
Like discussed in the [mailing list](https://groups.google.com/forum/#!msg/chocolatey/SsxJdcxLxkY/F6E7QP13FAAJ), it would be great if the nuspec validation was done during the choco pack command: it could save time and prevent the submission of incorrect package.

**Comment by ferventcoder** [comment]
Thanks for getting this logged.

**Comment by ferventcoder** [comment]
Some discussion https://gitter.im/chocolatey/choco?at=56fa7f638d2a72471b7b102c

**Comment by TheCakeIsNaOH** [comment]
There is a todo comment for this feature request here: https://github.com/chocolatey/choco/blob/develop/src/chocolatey/infrastructure.app/services/NugetService.cs

**Comment by gep13** [comment]
>@TheCakeIsNaOH said...
I think that should either be disabled by default or possibly toggle-able by a feature switch. This is for anyone building the package inside an offline or locked down environment.

As we discussed, this would indeed make sense to be able to configure this check.

**Comment by pauby** [comment]
I believe this is resolved in part, and will be resolved in full, but the recent release of the [Community Validation Extension](https://github.com/chocolatey-community/chocolatey-community-validation). There was a recent [blog post](https://github.com/chocolatey-community/chocolatey-community-validation) and [live stream](https://www.youtube.com/live/AQTIycbA3Jo?si=820DHpa3CQqlkGpj) around it.
