### ISSUE TITLE
Pro Version Licensing Questions

### ISSUE THREAD

**Issue by wjk** [chocolatey/choco#608]
Hi @ferventcoder! I was browsing the commits in your fork regarding GH-584 and I saw in particular [fbc2b54](https://github.com/ferventcoder/choco/commit/fbc2b5494268cf8f6907c3600fbfc8fca0186269). I take it based on the contents of that commit that if you have a pro license, and if it is expired, the pro features will cease functioning but the FOSS features will work as normal. Is this accurate?

In addition, how will package developers handle targeting pro-only features? I’m not asking for free or discounted licenses for developers creating packages requiring pro-only features; that would be unreasonable — and I wouldn’t mind paying full price for one anyways. :smile:

Instead, will there be documentation for both developers and users regarding the use of packages containing pro-only features? Note that the full feature set for paid Chocolatey licensees has not been announced (at least, in a place where I can see it; I was not a Kickstarter backer). Therefore, I do not know if there will be pro-only features that render a package partially or fully nonfunctional when installed using a FOSS copy. If so, will there be a notice on the package's page that it requires the pro version? If such packages are instead confined to the pro-only Chocolatey sub-gallery, will there be a way for potential (but not current) paying customers to view (but not install) the packages? This would help with marketing Chocolatey to others and in justifying the purchase price to managers.

In all, however — keep up the good work!

**Comment by ferventcoder** [comment]
> I take it based on the contents of that commit that if you have a pro license, and if it is expired, the pro features will cease functioning but the FOSS features will work as normal. Is this accurate?

Yes. The pro module will also perform a license validation check, but the difference it fails hard. So not loading those aliases from the module is super important if the license is not valid.

**Comment by ferventcoder** [comment]
> In addition, how will package developers handle targeting pro-only features?

What did you have in mind?

**Comment by ferventcoder** [comment]
> Instead, will there be documentation for both developers and users regarding the use of packages containing pro-only features?

Absolutely. The first round of licenses have been delivered to Kickstarter users, who get their licenses three months before everyone else is able to.

> Note that the full feature set for paid Chocolatey licensees has not been announced (at least, in a place where I can see it; I was not a Kickstarter backer).

Even if you were not part of the kickstarter, you can still go see what features are expected to land and expected pricing - 
https://www.kickstarter.com/projects/ferventcoder/chocolatey-the-alternative-windows-store-like-yum/description

Scroll down to business license levels and the image below that that talks about a couple of features.

> Therefore, I do not know if there will be pro-only features that render a package partially or fully nonfunctional when installed using a FOSS copy.

We really don't have plans at this time to cause this to happen. If there are packages such as this, they would not be found on any feed besides the Pro/Business Only Feed.  The general idea is that certain features kind of light up when you use pro/business.

> If such packages are instead confined to the pro-only Chocolatey sub-gallery, will there be a way for potential (but not current) paying customers to view (but not install) the packages? This would help with marketing Chocolatey to others and in justifying the purchase price to managers.

Absolutely. We plan to have a read only view of these packages.

**Comment by ferventcoder** [comment]
Let me know if you have any additional questions - and join the newsletter to be the first to know when and what is coming!
