### ISSUE TITLE
LASTEXITCODE set to non-zero when Chocolatey CLI aborts shutdowns

### ISSUE THREAD

**Issue by bill-long** [chocolatey/choco#610]
See mwrock/boxstarter#148.

Short version: Boxstarter checks $LASTEXITCODE, and if that value is nonzero, it gives you a big red error message saying stuff failed. When choco sends a shutdown /a and no shutdown is in progress, that sets $LASTEXITCODE to 1116. This causes Boxstarter to report a failure even though all packages in the Boxstarter script succeeded.

Should choco reset $LASTEXITCODE after sending the shutdown command?

**Comment by ferventcoder** [comment]
Seems reasonable, or at least find the last exit code before that and set it again.

**Comment by erikvanbrakel** [comment]
Boxstarter has a feature which tests for pending reboots. Perhaps it's a better solution to use similar logic to test, and send a shutdown /a when there's actually a pending reboot?
https://github.com/mwrock/boxstarter/blob/master/Boxstarter.Bootstrapper/Get-PendingReboot.ps1
https://github.com/mwrock/boxstarter/blob/master/Boxstarter.Bootstrapper/Test-PendingReboot.ps1

**Comment by djlestephane** [comment]
Can someone help me understand why / when choco invokes shutdown /a, so that I can at least avoid triggering it? Thx

**Comment by ferventcoder** [comment]
@djlestephane it runs every time, it means abort shutdown. So if there is one in progress by an installer that ignores not to do so, it will ensure that it doesn't do it.

**Comment by pauby** [comment]
I've never come across this problem. Is this still an issue?
