### ISSUE TITLE
Enhance Logging: Explicit Reporting of User Name, System Account Context, Admin Rights and Remoting Context

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#615]
**_Let Me Know If You Want This Broken Up and if so, How Many Issues to Break It Into**_

It would be helpful if for each of these choco 
[a] Set a Variable
[b] reported all of these near each other in the log
[c] if each log entry included unique text that could be searched and/or configured in a log highlighter.

**Username**
Variable: $env:username
Log example: Chocolatey is running under account username: <accountname>

**SYSTEM Account Context**
Also would be nice if Choco reported explicitly whether it thinks it is running under SYSTEM.
1) From experience, checking the user name is not a good idea because: it is reported slightly differently depending on context.  Sometimes it is <COMPUTERNAME>$ and sometimes "SYSTEM".
2) Some accounts, like "LocalSystem" may also be considered "SYSTEM" accounts.
I _think_ this API call is the best way - but I have not researched whether it catches alternative SYSTEM accounts:

```
If (([System.Security.Principal.WindowsIdentity]::GetCurrent()).IsSystem)
{$IsSystem = $True} Else {$IsSystem = $True}
```

Log example: Chocolatey is running in SYSTEM account context.  (Also exposed in variable $IsSystem)

PLEASE DO NOT REPOST CONTENT WITHOUT PERMISSION. Training and Tools to Make Apps Run on Win7 and Virtualization => http://CSI-Windows.com

**ELEVATED Administrator Rights**
Reporting System Admin rights or not would also be helpful.
Most reliable way I know is the following - this SID only appears if the current session IS ELEVATED.  So you don't need to goof around with methods that tell you the user is in the admins group - but still not elevated:

```
If ([bool](([System.Security.Principal.WindowsIdentity]::GetCurrent()).groups -match "S-1-5-32-544"))
{$IsElevated = $True} Else {$IsElevated = $False}
```

Log example: Chocolatey is running in an ELEVATED ADMIN context.   (Also exposed in variable $IsElevated)

**REMOTING Context**
Get-host could be helpful here.  I know of one stumbling block.  (Get-Host).Name can contain the string "remote" for some scheduled jobs.  (Get-host).runspace may be more reliable, but I have not tested it in scheduled jobs

```
[bool]((get-host).name -ilike "*remot*")
[bool]((get-host).runspaces -ilike "*remot*")
{$IsRemoting = $True} Else {$IsRemoting = $False}
```

Log example: Chocolatey is running in a REMOTE SESSION.   (Also exposed in variable $IsRemoting)

**Comment by ferventcoder** [comment]
> ELEVATED

We already capture this.

**Comment by DarwinJS** [comment]
> We already capture this.
Ok - is it a variable or just logging?

**Comment by ferventcoder** [comment]
Both.

**Comment by DarwinJS** [comment]
Cool - looking for the same pattern with the others if possible and a bit of choc unique logging text.

**Comment by ferventcoder** [comment]
https://gist.github.com/choco-bot/a4eb1edc297e8da6ce02#file-install-txt-L39-L40

**Comment by DarwinJS** [comment]
Would also be cool to show all the indicator variables choco takes pains to set in the default template from "choco new".  May prevent a lot of packagers taking time to find their own methods - methods which may not cover all use cases their package will end up in.

**Comment by ferventcoder** [comment]
This will be in 0.10.6

**Comment by ferventcoder** [comment]
There is a way to know if choco is running inside of a terminal services (remote desktop context). However it doesn't appear there is a way for anything to know it is being run over PowerShell Remoting (outside of the entered PowerShell session, which will know that it is running something like `ServerRemoteHost`). That information doesn't flow into any environment variables and is not passed down to choco (or any tool) when it runs so there is likely no way to know it is coming over remoting. HTH

**Comment by ferventcoder** [comment]
The one thing it may be able to do is see $env:SESSIONNAME is completely empty and not "Console" and guess it may have something to do with not being a local session... it's not very deterministic though.

**Comment by ferventcoder** [comment]
@DarwinJS probably more deterministic from PowerShell - https://twitter.com/anthonymastrean/status/857399759895744512

**Comment by ferventcoder** [comment]
From @AnthonyMastrean
