### ISSUE TITLE
Ability to specify a default source when doing choco push

### ISSUE THREAD

**Issue by gep13** [chocolatey/choco#62]
Use Case:

Default, out of the box, when you do `choco push` you get a warning about missing source

As a User, I want to be able to specify default source, so I don't have to always do `choco push -source http://chocolatey.org/`

**Comment by ferventcoder** [comment]
Two things here. We start out with chocolatey.org as the default as well?

**Comment by ferventcoder** [comment]
So no default on OOTB. Like it.

**Comment by cwacha** [comment]
+1

and should be very easy to implement

**Comment by julio-92** [comment]
@ferventcoder is anyone working on this? I ran into this as a user and was thinking of giving it a try.
