### ISSUE TITLE
Clean up any temp nuget folder actions after NuGet operations 

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#622]
* %TEMP%\NuGetScratch folder
* %TEMP%\x\nuget folder
* ~~%TEMP%\nuget\packagename~~

**Comment by ferventcoder** [comment]
@mrdima This is now fixed.

**Comment by ferventcoder** [comment]
We already clear the nuget folder with the package name handled in  #479

**Comment by ferventcoder** [comment]
This should help reduce the size when embedding files in the package.

**Comment by dietmarb01** [comment]
The `NuGetScratch` folder is NOT deleted in the following situation:

- Choco packages are deployed through a Windows service (headless operation), running as SYSTEM.
- Choco's `cacheLocation` has been set to `C:\tmp`.

Choco creates and uses `C:\tmp\NuGetScratch` for the installation itself, but leaves it behind after completion. 
Monitoring with `procmon.exe` shows a single attempt to access ` C:\Windows\Temp\NuGetScratch` which fails, as there is no such folder.

**Comment by ferventcoder** [comment]
@dietmarb01 sounds like a possible bug. Would you mind filing a new issue so we can take care of it ? Thanks in advance!
