### ISSUE TITLE
WARNING: Unable to generate 'C:\Users\******\AppData\Local\Temp\office\setup.exe.ignore'

### ISSUE THREAD

**Issue by CerealJunkie** [chocolatey/choco#625]
So I have been trying to debug this issue for a few hours now but have no idea where to end. I have tried everything and the script looks perfect. If someone could help me out here with this problem... that would be great. Thanks

**Comment by CerealJunkie** [comment]
Here is the package btw.

https://chocolatey.org/packages/Office365BusinessRetail16/16.0.6366.2073

**Comment by ferventcoder** [comment]
Is this figured out?

**Comment by CerealJunkie** [comment]
Yes. I had to change around the script a bit but I got it working. I have no idea why it didn't work with variables but it is working fine now.
