### ISSUE TITLE
[Wiki] HelpersReference missing Install-BinFile

### ISSUE THREAD

**Issue by Link-Satonaka** [chocolatey/choco#632]
The function
https://github.com/chocolatey/choco/blob/0ec22c8cfa5d71933fc2a378ddee62d195f8199b/src/chocolatey.resources/helpers/functions/Install-BinFile.ps1

Is not documented in

https://github.com/chocolatey/choco/wiki/HelpersReference

**Comment by ferventcoder** [comment]
We welcome the documentation! https://github.com/chocolatey/choco.wiki

**Comment by ferventcoder** [comment]
Fixed the url

**Comment by ferventcoder** [comment]
This is there now. Added awhile back, but not sure when.
