### ISSUE TITLE
Helper Get-WebHeaders is making GET request instead of HEAD

### ISSUE THREAD

**Issue by Belogron** [chocolatey/choco#637]
When using the `Get-WebHeaders` helper function it does not only download the headers using the HTTP HEAD method as I think it is supposed to do.

The file [`helpers\functions\Get-WebHeaders.ps1`](https://github.com/chocolatey/choco/blob/0ec22c8cfa5d71933fc2a378ddee62d195f8199b/src/chocolatey.resources/helpers/functions/Get-WebHeaders.ps1) has the line 29 commented out, so that the code is 
```powershell
  $request = [System.Net.HttpWebRequest]::Create($url);
  $defaultCreds = [System.Net.CredentialCache]::DefaultCredentials
  if ($defaultCreds -ne $null) {
    $request.Credentials = $defaultCreds
  }

  #$request.Method = "HEAD"
  $client = New-Object System.Net.WebClient
```
In my opinion the `$request.Method = "HEAD"` has to set, otherwise a GET is executed. This is bad in use-cases where a big file could be at multiple locations and it has to be checked which file exists.

When running this method with a 100MB test file the GET request takes ~5sec [see Log] (https://gist.github.com/Belogron/69d8f2132b9d686afe5)
![fiddler-get](https://cloud.githubusercontent.com/assets/3844605/13052067/00f216fc-d3fd-11e5-89ac-b613277117eb.PNG)

When uncommenting the line (thus using a HEAD request) is only takes ~0.15sec [see Log](https://gist.github.com/Belogron/cd0e22a77484b0c0a4ec)
![fiddler-head](https://cloud.githubusercontent.com/assets/3844605/13052081/09584c80-d3fd-11e5-8c71-747527f127ac.PNG)

This is a big performance improvement and makes the method do what the name suggest.
I tested installing a few random packages and this does not seem to break anything.

**Comment by ferventcoder** [comment]
It needs to work across the board. 5 seconds versus not working in some cases, I will take the guarantee. Plus we need to know about the actual file's headers, so take that into account for the HEAD request. It needs to verify the file exists and provide information about the file itself.

**Comment by Belogron** [comment]
> It needs to verify the file exists and provide information about the file itself. 

This would make sense, but doesn't the method simply discard the body anyways? As far as I can see it returns the `$headers` map, which is filled with the `$response.Headers` values. The body is not even used in that method. And according to the [specs](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html) : 
> The HEAD method is identical to GET except that the server MUST NOT return a message-body in the response. The metainformation contained in the HTTP headers in response to a HEAD request SHOULD be identical to the information sent in response to a GET request. This method can be used for obtaining metainformation about the entity implied by the request without transferring the entity-body itself. This method is often used for testing hypertext links for validity, accessibility, and recent modification. 

So does the script do something with the request body that my limited powershell skills missed or is the body simply discarded? If it is, using `HEAD` method should not break anything.

**Comment by Belogron** [comment]
@ferventcoder Is there any progress on this? If you still don't think it would make sense to change this, I would close this issue.

**Comment by ferventcoder** [comment]
We are going to be combining the calls into one so that we will use all of the response. That means we won't need a head request unless we are specifically asking for whether the link is good or not.

**Comment by ferventcoder** [comment]
For that reason, we probably won't switch this up. It's working, even if a bit slower.

**Comment by ferventcoder** [comment]
If we ever come back to adding a check of the url to part of `--noop`, then we may approach doing something with HEAD at that time.
