### ISSUE TITLE
I can create new issues just fine, Rob

### ISSUE THREAD

**Issue by jbogard** [chocolatey/choco#639]
BEFORE YOU SUBMIT AN ISSUE, PLEASE READ https://github.com/chocolatey/choco#submitting-issues

DO NOT CREATE ISSUES FOR PACKAGES. Read https://github.com/chocolatey/choco#submitting-issues

DO NOT CREATE AN ISSUE FOR A QUESTION - questions are better served as email or chat.

* email - http://groups.google.com/group/chocolatey
*  chat - https://gitter.im/chocolatey/choco

## Template for Bug Reports

DELETE EVERYTHING ABOVE THIS LINE AND THE LINE
___

### Your Log With All Ouptput

~~~sh

PLACE LOG CONTENT HERE

Make sure there is no sensitive data shared.

We need ALL output, not just what you may believe is relevant.
If that is hard to reproduce, the log file already logs with
those parameters, just grab the relevant section from the log
file and add it here.

~~~

**Comment by ferventcoder** [comment]
Well, maybe it is something with my browser then. Thanks for verifying!

**Comment by ferventcoder** [comment]
Nevermind, it is working now.

**Comment by gep13** [comment]
>@jbogard said...
I followed Rob on Twitter, likely a mistake

lol :smile_cat:

**Comment by ferventcoder** [comment]
Best issue ever!
