### ISSUE TITLE
Add a `choco info` command to show info for one package

### ISSUE THREAD

**Issue by alexchandel** [chocolatey/choco#644]
For the life of me, I _cannot_ ever remember how to show info for a package with `choco`. We should add an `info` command, analogous to `brew info`, to show info for one package. If we're worried about people relying on it in their tools, we can explicitly mark it as "manual-only" or "user-only" or "forever unstable" or something. But it would be **so** useful.

**Comment by ferventcoder** [comment]
I'm assuming it would be similar to: `choco list packagename -lo -v`?

Is this for locally installed applications?

**Comment by alexchandel** [comment]
In general. The thing is even `choco list packagename -lo -v` can match multiple packages and print tons of information, for example with packagename=git.

**Comment by DarwinJS** [comment]
I would love this too as it is more discoverable by those using our internal repositories which may not have the greatest web gallery support or we may not wish to expose a web gallery at all.

**Comment by ferventcoder** [comment]
Agreed. Choco info - synonymous with `choco search pkgname -ev`.

**Comment by ferventcoder** [comment]
Related to #453

**Comment by drusellers** [comment]
:+1: for `choco info <packagename>`

**Comment by drusellers** [comment]
I'd love it to have some output similar to `brew info <pkgname>`

```
brew info rabbitmq
rabbitmq: stable 3.6.1
Messaging broker
https://www.rabbitmq.com
/usr/local/Cellar/rabbitmq/3.4.4 (1,030 files, 25.3M)
  Poured from bottle
/usr/local/Cellar/rabbitmq/3.5.6 (1,039 files, 25.6M)
  Built from source
/usr/local/Cellar/rabbitmq/3.6.0 (183 files, 5.4M) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/rabbitmq.rb
==> Dependencies
Build: xz ✔
Required: erlang ✔
==> Caveats
Management Plugin enabled by default at http://localhost:15672

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

To have launchd start rabbitmq at login:
  ln -sfv /usr/local/opt/rabbitmq/*.plist ~/Library/LaunchAgents
Then to load rabbitmq now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.rabbitmq.plist
Or, if you don't want/need launchctl, you can just run:
  rabbitmq-server
```

**Comment by ferventcoder** [comment]
So it's not going to be exactly like brew info, but it will provide similar information as you can get with choco search name --exact --detailed.

**Comment by drusellers** [comment]
I don't know if I want search, for instance one of the key pieces of data that I want with `choco info` is to know where stuff was written to

**Comment by DarwinJS** [comment]
Rob - this is exactly what I was asking for.  

Looks like brew outputs the log snippet for a given package if it's already installed?

Apologies if I inadvertently hijacked this issue :(

**Comment by alexchandel** [comment]
@drusellers That probably wouldn't be `choco info` per se. The brew command to show which files are owned by a package is `brew ls <pkgname>` or `brew list <pkgname>` (ls and list are synonymous commands), not `brew info`.

**Comment by drusellers** [comment]
@alexchandel ah, that is cool too! Issue opened. :)
