### ISSUE TITLE
Need Documentation for Chocolatey Bin Root

### ISSUE THREAD

**Issue by hollasch** [chocolatey/choco#65]
The deprecated wiki mentions the environment variable %chocolatey_bin_root%, which is the relative path rooted at the system partition. None of this is mentioned in the new wiki, which instead mentions in passing $env:ChocolateyBinRoot, but not what it should be set to or how to set it (it doesn't appear o be a Windows environment variable). This and likely other variables need to be documented in the wiki.

**Comment by ferventcoder** [comment]
Thanks for this. We should add it. I'm almost sure it doesn't exist on the old wiki either (since we started with that and updated).

**Comment by gep13** [comment]
Given that this is actually going to be deprecated, I don't think there is anything else that is needed to be done here.  Going to close this out.
