### ISSUE TITLE
Update the website, UX design refresh.

### ISSUE THREAD

**Issue by robertbaker** [chocolatey/choco#650]
I believe chocolately would gain a lot more traction of the website had a complete refresh, more succinct. Making it clearer and more inviting.

If I may, I would take this task.
What do you think about converting the pages use angular with typescript instead of Razor?

**Comment by ferventcoder** [comment]
We believe the same. There is already an issue talking about this on the chocolatey/chocolatey.org repository.

Did the issue template not sway you to the proper repo?

**Comment by ferventcoder** [comment]
Closed as this is not related to choco.exe, head over to the other repo and comment on that issue (I can grab that link when I'm at a desktop if you don't find it).
