### ISSUE TITLE
Chocolatey plan for device driver, Is there a plan for having install device driver  - Feature Request

### ISSUE THREAD

**Issue by nepsdotin** [chocolatey/choco#651]
Is there any plan for device driver installation. Becaues that a lot of pain finding the right device driver from n number of websites.

So To Install audio driver, i can install something like 

`sudo apt-get install **audio**`

the system identifies that it uses a particular vendor driver.

install the driver with the current version

restart y/n

**Comment by ferventcoder** [comment]
We already support device driver installs. Here are some examples - https://chocolatey.org/packages?q=geforce

**Comment by ferventcoder** [comment]
What additionally would you add to that?

**Comment by nepsdotin** [comment]
If I would like to add Sound Driver, It should identify the Right Sound
Card on my Computer and Identify the Right Version and install.

Does the Chocolatey Does that. That would be really awesome.

So you should be having all the vendors in packages list, and the system
should identify the vendor and the approp version and install that

**Comment by ferventcoder** [comment]
No, unfortunately it doesn't do that. As a package manager if you have a package for the right drivers, it would be able to install those, but as far as selecting the right one for you automatically, that is out of the realm of the scope of Chocolatey.

**Comment by nepsdotin** [comment]
​Are there any system that does that. I am thinking of to build something
like that. Would that make sense.

Having a system like this

Client (installed on the machine)

apt-get install audio

Should have to read the digitally encoded Name of the Vendor, Version of
the Driver Any other device specific details ( For this to happen the
vendor / device manufacturer should encode this on the driver, I guess its
already happening because only of that Computer shows details in the device
information.)

Download the package and install it

This would solve a big problem of finding manually the device driver, and
its version and where to download

Whats your thought on this ?

​

**Comment by ferventcoder** [comment]
Seems like something you could release as a Chocolatey package. 

But again, the querying of the system to determine the driver information isn't somewhere that Chocolatey would go right now.

**Comment by DarwinJS** [comment]
@nepsdotin - windows has a variety of ways of packaging drivers.

The first recourse is if you place the INF and drivers files in the right windows folders, on the next plug and play detection, windows should install the driver.  This is a bit fussy.

If the driver ships as a file set with a *.INF file you can run it with RunDLL32.

RUNDLL32.EXE SETUPAPI.DLL,InstallHinfSection DefaultInstall 132 path-to-inf\infname.inf

More Info: https://msdn.microsoft.com/en-us/library/windows/hardware/ff557251(v=vs.85).aspx

FYI - it is possible that the driver INF is not well formed to follow best practice and then cannot be installed by this method.

Some packagers for large windows installations (50K+ machines) might use the developer tool to repackage a driver into an automated format: https://msdn.microsoft.com/en-us/library/windows/hardware/ff544838(v=vs.85).aspx

Unfortunately driver installation is the blackest of Windows installation arts if the vendor does not give you an installer that is automation ready.

**Comment by pauby** [comment]
As mentioned in [this comment](https://github.com/chocolatey/choco/issues/651#issuecomment-193654806) it can be done today by the package itself querying the computer for the information to determine which driver to install.

I'm going to go ahead and close this, but we can reopen it if necessary.
