### ISSUE TITLE
MetaData Overrides for Internal / Public Packages

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#652]
The needs expressed in this request are unique to doing chocolatey packaging for internal company packages.  They are not critical for community packages.  As corporate internal packaging starts to increase, the below may help remove friction for a lot of excellent internal packages being made available to the community.

Some of the internal packages I do at my company are suitable to contributing to the community.
I have to package them so they make the most sense for internal use because that is the reason I am creating them.  This means I may include additional tags and possibly extra metadata in the description so that the package metadata is more meaningful when being browsed from within the company.  Some of the differences might not be allowed on Chocolatey.org (our internal tags that mean nothing for public purposes).  Other differences might be disclosing data that my company does not want to see on chocolatey.

At the same time I do not want to maintain two copies of the package.  If there are differences in the actual PowerShell code - then I _would_ maintain separate copies as that is too much difference.

I am mainly concerned with being able to compile the package meta data one way for chocolatey and a different way for internal repositories.

One thought I have of doing this is allowing me to specify a partial .nuspec file and whether I want similar fields to merge or override those in the main packageid.nuspec.

Something like these:

**choco folder contains files: packageid.nuspec, packageid.merge, packageid.override**
choco pack #automatically picks up *.merge and *.override and uses both
choco pack -nomergeoverride

For more control of file names and associated .gitignore rules AND to avoid above auto processing.
choco pack -mergenuspec whateverfilename.iwish, anothermerge.file
choco pack -overridespec whateverfilename.iwish2
choco pack -mergenuspec whateverfilename.iwish -overridespec whateverfilename.iwish2

Some possibly significant implementation details:
- would be cool if I could decide whether the primary packageid.nuspec is the chocolatey one or the corporate one.
- would be cool if the file name extensions for these files caused automatic operation which can be disabled (packageid.merge, packageid.override)
- would be cool if I could fully specify files by using explicit parameters.  (also allowing me to use the feature, but opt out of any auto processing concerns)
- would be cool if all metadata, including packageid and version, could be overridden.
- this approach should be easy to hook into auto packaging.
- this approach can be prototyped with powershell utility scripts before chocolatey creates integrated support.

I had thought of schemes where by data was embedded in the package that told chocolatey to edit certain metadata when it is doing the server side import, but it would [a] seem to be more complex, [b] require server enhancements and [c] it does not cover the scenario where there is data that should not even be sent out of an organization.  By handling it at pack time a careful packager can make sure that the correct data goes the correct places.  If necessary, they could create scripts to do a full compile and push of the package to the proper locations.

**Comment by ferventcoder** [comment]
So merge values would append and override would overwrite? That almost sounds like an implementation detail of the merge file. With the opportunity for multiple merge files it seems like this would be fine. Thoughts?

**Comment by DarwinJS** [comment]
My terms merge and override are probably a bad choice for conveying what I mean.  

Probably a better way to explain what I mean is the ability to "append" to individual .nuspec field contents and the ability to "replace" individual .nuspec field contents to transform the same target .nuspec file.  I guess replaces would need to have precedence if both were specified.

I was thinking maybe using parameters to indicate which operation is desired with which files - then the fragmentary .nuspec would not need additional "instructions" saying to "append this stuff to the tags field" AND "replace the package id with this one."  They would look like any other .nuspec (other than being partial).

Maybe that makes more sense because at the file level they both types of functionality (append / replace) are "merging" into the target file.

**Comment by pauby** [comment]
This is not something I believe should be added to Chocolatey CLI. As has been mentioned, this would be something that a build would take care of by creating the `.nuspec` file and then having Chocolatey CLI pack it.

I'm going to go ahead and close this, but we can reopen it if necessary.
