### ISSUE TITLE
Cmake CPack support for Chocolatey wanted

### ISSUE THREAD

**Issue by dothebart** [chocolatey/choco#655]
cmake.orgs cpack facility is there to aid building packages for all sorts of package managers, linux, mac, freebsd... , even a NSIS backend exists.

It would be nice if there could be a way to generate packages for Chocolatey via CPACK to ease adoption of Chocolatey for vendors that already use cpack for their packages. In my case this would be [ArangoDB](https://arangodb.com/Download/) which already offers an NSIS and an xcopy install for windows.

**Comment by ferventcoder** [comment]
Can you help me understand the context? Right now it seems like this ticket should go to cmake and not to here.

**Comment by gep13** [comment]
Given the lack of response here, I am going to go ahead and close out this issue.  Feel free to respond again if this is something that you want to discuss further.
