### ISSUE TITLE
Chocolatey uses arguments on itself that it recognizes within -installargs (and autouninstall failover failure?)

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#656]
Searched for similar issues before submitting.

Happens with 0.9.9.11 and latest beta.

Used single and double quotes and both together.

The following command does as asked and installs ccleaner to another folder, but it _ALSO_ causes chocolatey to output debug messages:

choco install ccleaner -installargs "/d=c:\users\public\ccleaner"

(Was version 5.15.5513 of the ccleaner package at the time of this ticket submission)

Moving the install folder also causes the built-in chocolateyuninstall.ps1 to fail - but auto uninstall did not come to the rescue - even though it grabbed the reg keys (and the .reg is correct) on the way in it does not seem to execute after the failure.

Autouninstaller testing was done with autoinstaller feature explicitly forced on and using latest beta.

Thought it might be a good use case for testing "autouinstall after failure of chocolateyuninstall.ps1"

**Comment by ferventcoder** [comment]
> Moving the install folder also causes the built-in chocolateyuninstall.ps1 to fail - but auto uninstall did not come to the rescue - even though it grabbed the reg keys (and the .reg is correct) on the way in it does not seem to execute after the failure.

Yeah, we probably need an explicit switch for this. The default behavior is that if the uninstall script passes it will also run, but if the uninstall script fails, everything fails.  You could try it with the switch to not run the uninstall script and see if that works appropriately (`choco uninstall -h` because I always mention the wrong argument). 

Also, let's try to log one issue per ticket. Do you want to log this as a separate issue?

**Comment by ferventcoder** [comment]
`choco install ccleaner -installargs "'/d=c:\users\public\ccleaner'"`

https://github.com/chocolatey/choco/wiki/CommandsReference#how-to-pass-options--switches

The reason we are very specific in the arguments with `" ' some arg ' "` is that works across all shells. It's likely you were using powershell.exe and it will strip those quotes right off.

**Comment by ferventcoder** [comment]
Yes, it appears powershell.exe stripped the quotes off:

~~~sh
C:\ > choco install ccleaner -installargs "/d=c:\users\public\ccleaner"
Chocolatey is running on Windows v 6.1.7601.65536
Command line: "C:\ProgramData\Chocolatey\choco.exe" install ccleaner --noop -installargs /d=c:\users\public\ccleaner
Received arguments: install ccleaner --noop -installargs /d=c:\users\public\ccleaner

NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
CommandName='install'|
CacheLocation='C:\Users\rob\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|
Sources='https://chocolatey.org/api/v2/'|
SourceType='normal'|Debug='True'|Verbose='False'|Force='False'|
Noop='True'|HelpRequested='False'|RegularOutput='True'|
QuietOutput='False'|PromptForConfirmation='True'|AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='ccleaner'|AllVersions='False'|
SkipPackageInstallProvider='False'|PackageNames='ccleaner'|
Prerelease='False'|ForceX86='False'|
InstallArguments='/d=c:\users\public\ccleaner'|
[..snip..]
~~~

Now with the proper way of passing args:

~~~sh
C:\ > choco install ccleaner --noop -installargs "'/d=c:\users\public\ccleaner'" -d
Chocolatey v0.9.10-beta1-168-g74aa4e6 Professional
Chocolatey is running on Windows v 6.1.7601.65536
Command line: "C:\ProgramData\Chocolatey\choco.exe" install ccleaner --noop -installargs '/d=c:\users\public\ccleaner' -d
Received arguments: install ccleaner --noop -installargs '/d=c:\users\public\ccleaner' -d

NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
CommandName='install'|
CacheLocation='C:\Users\rob\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|
Sources='https://chocolatey.org/api/v2/'|
SourceType='normal'|Debug='True'|Verbose='False'|Force='False'|
Noop='True'|HelpRequested='False'|RegularOutput='True'|
QuietOutput='False'|PromptForConfirmation='True'|AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='ccleaner'|AllVersions='False'|
SkipPackageInstallProvider='False'|PackageNames='ccleaner'|
Prerelease='False'|ForceX86='False'|
InstallArguments='/d=c:\users\public\ccleaner'|
[..snip..]
~~~

**Comment by DarwinJS** [comment]
Ok - I tried two sets of quotes, but had them enclosed the other way around.

Will open a second ticket - I wasn't sure if I what I was seeing was actually an issue - so wanted to hear your initial comments first.

**Comment by pauby** [comment]
This feels like it was resolved, and a second issue opened. I'm going to go ahead and close this, but we can reopen it if necessary.
