### ISSUE TITLE
Change auto-uninstaller default to *RUN* if ChocolateyInstall.ps1 fails

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#657]
If I run the following command

choco install ccleaner -installargs "'/d=c:\users\public\ccleaner'"

(Was version 5.15.5513 of the ccleaner package at the time of this ticket submission)

Then ChocolateyUninstall.ps1 fails because it is hard coded to the default install location.

The autoinstaller does not kick in.

The request to make this the default behavior comes from typical automator laziness as it seems the opposite could be likely to cause me more work in many scenarios:

I install ccleaner (or any other package whose chocolateyuninstall.ps1 is destined to eventually fail) on 1000 machines with 0.9.10 with autouninstall enabled.

Months later I schedule a mass automated install that removes that package (maybe in preparation to upgrade).  ChocolateyUninstall.ps1 fails.  The means to automatically recover from this challenge are readily available in chocolatey - if autoinstall simply defaults to pick up the broken pieces it would be likely to remedy this _specific_ type of failure.

Also equally painful scenarios if it fails on 10% of 1000 machines and needs root cause analysis and re-run or if individual end users are trying to self-service uninstall with any type of app store and have failures that they need to log a ticket for.

**Comment by ferventcoder** [comment]
I think we can safely close this as fixed by #198
