### ISSUE TITLE
The underlying connection was closed: An unexpected error occurred on a send.

### ISSUE THREAD

**Issue by jnm2** [chocolatey/choco#662]
Chocolatey will not install properly on Windows Server 2012 R2 using the admin command prompt command. I manually downloaded 7za.exe and chocolatey.zip and tried again and nothing changed. I also tried after using the property pages Unblock button on both files. I eventually decided to extract the zip manually and tried the install command and the first error showed up but the install finished successfully. It was successful enough that all the choco-related commands are available, but `clist -l` shows 0 packages and it normally shows the chocolatey package after install.

However, all choco installs fail with `The underlying connection was closed: An unexpected error occurred on a send.` Wireshark attests to the fact that the downloads and HTTP connections complete successfully, just like with 7za.exe. I'm not sure where it's getting the idea that a failure happened.

It would be nice to be given a list of things to troubleshoot when this happens.

Logs coming if I can uninstall chocolatey.

**Comment by ferventcoder** [comment]
Much appreciated, now I'd like to get more details - I install Chocolatey on Windows Server 2012 R2 regularly.

**Comment by jnm2** [comment]
What details would you like? The command line output is [here](https://gist.github.com/jnm2/de93168688c08e5bf11e), but I wasn't able to locate a log.

This machine is on a network with iPrism filtering and all websites have to be whitelisted. I can tell from Wireshark that all HTTP requests are succeeding, so that shouldn't be the problem.

**Comment by ferventcoder** [comment]
That log is interesting. I wish there were more detail surrounding the specifics of why it was closed. It does seem environmental though, other folks would be reporting this issue otherwise.

Do you think it may have something to do with a trust issue with SNI and CloudFlare?

**Comment by jnm2** [comment]
It may. I would have expected `The underlying connection was closed: Could not establish trust relationship` though. It would be so helpful if the InnerExceptions were recursively printed out.

What's the best course of action for me to debug this? Filtering Wireshark for `http` is about all I know to without further instructions.

**Comment by ferventcoder** [comment]
Try pushing it through a proxy and see if that works appropriately.

**Comment by ferventcoder** [comment]
For debugging purposes I think this is going to be a bit harder. Wireshark and Fiddler are your best weapons to watch and get low level details. Also procmon.

**Comment by jnm2** [comment]
I'm very sad about this, but it started working. :smile: A seemingly unrelated DNS issue was fixed, and not by me (the IPv6 DNS address was set to `::1` for some reason) and the next time I tried chocolatey, it just worked.

**Comment by ferventcoder** [comment]
Thanks for the heads up!

**Comment by ferventcoder** [comment]
I mean followup :)
