### ISSUE TITLE
Unzip specific folder feature is broken after introducing 7zip

### ISSUE THREAD

**Issue by digitalcardboard** [chocolatey/choco#676]
## _Migrating issue # 406 from https://github.com/chocolatey/chocolatey/issues/406_

In short, attempting to use the `specificFolder` parameter for `Install-ChocolateyZipPackage` (and ultimately `Get-ChocolateyUnzip` doesn't work. Regression issue after switching to **7za**.

**Comment by ferventcoder** [comment]
From original issue:

I'm updating a package that downloads an archive with x64 and Win32 subdirectories. I used to extract the entire thing and manually remove the unneeded components. But, I figured I would try the as-yet undocumented `-specificFolder` parameter of `Install-ChocolateyZipPackage`.

```powershell
$name   = "bellavista"
$url    = "http://.../bellavista.zip"
$tools  = Split-Path $MyInvocation.MyCommand.Definition
$folder = if(Get-ProcessorBits 64) { "x64" } else { "Win32" }


Install-ChocolateyZipPackage -PackageName $name -Url $url -UnzipLocation $tools -SpecificFolder $folder
```

But, it didn't work. The first thing I saw was a goofy log message. Look at the "full path" in bold. It contains a non-path

> "Extracting **c:\users\foo\temp\chocolatey\bellavista\bellavistaInstall.zip\x64** to c:\Chocolatey\lib\bellavista.1.0\tools..."

And, digging in [the source][1], I saw a bad 7za command line being constructed

```batch
7za x -o"c:\Chocolatey\lib\bellavista.1.0\tools" -y "c:\users\foo\temp\chocolatey\bellavista\bellavistaInstall.zip\x64"
```

From my reading of [the command line reference][2], and hacking my helper function, the correct command line should be...

```batch
7za x "c:\users\foo\temp\chocolatey\bellavista\bellavistaInstall.zip -o"c:\Chocolatey\lib\bellavista.1.0\tools" "x64" -y
```

And, actually, with this fix, you could supply *any glob pattern* to 7za, not just a specific folder.

 [1]: https://github.com/chocolatey/chocolatey/blob/master/src/helpers/functions/Get-ChocolateyUnzip.ps1#L71
 [2]: http://sevenzip.sourceforge.jp/chm/cmdline/commands/extract_full.htm

**Comment by alexjfisher** [comment]
I've just hit this too.  In my case I wanted to extract a single directory and its contents from a zip.  Changing the command from the broken current form...
```
7z e -aoa -bd --bb1 -o"c:\installdir" -y "C:\ProgramData\chocolatey\lib\my-package\tools\my.zip\some\path\in\zip"
```
to
```
7z e -aoa -bd --bb1 -o"c:\installdir" -y "C:\ProgramData\chocolatey\lib\my-package\tools\my.zip" "some\path\in\zip"
```
is maybe not quite right either.  The files from `some\path\in\zip` are extracted, but not directly into `c:\installdir`, but instead into `c:\installdir\some\path\in\zip`

**Comment by ferventcoder** [comment]
This is open for hacktoberfest, if you want to give it an attempt we'd be open to the contribution!

**Comment by DarwinJS** [comment]
I can give this one a shot.

**Comment by DarwinJS** [comment]
I can't tell under what circumstances this bit of code would be valid - tacking the specific folder directly onto the zip file name?  What am I missing?

https://github.com/darwinjs/choco/blob/master/src/chocolatey.resources/helpers/functions/Get-ChocolateyUnzip.ps1#L91-L93

**Comment by DarwinJS** [comment]
PR: https://github.com/chocolatey/choco/pull/1023
