### ISSUE TITLE
Choco Uri scheme

### ISSUE THREAD

**Issue by stueeey** [chocolatey/choco#684]
**Feature Request**

As suggested here: https://github.com/chocolatey/chocolatey/issues/394 
Why don't we create a URI scheme for chocolatey on install?

**Recommendations**
Uri schemes are a bit of a security concern here since they will need to launch an elevated process to do most chocolatey things. Therefore we should probably limit the sources to only those that are already configured on the user's system. so something like choco://NotepadPlusPlus to install or upgrade notepad++ would be perfect

**Comment by ferventcoder** [comment]
Added as up for grabs. :+1:

**Comment by stueeey** [comment]
I'll code this.

**Comment by ferventcoder** [comment]
Assigning folks requires adding folks to the project - I think you are fine to do this based on commenting. :+1:

**Comment by gep13** [comment]
This issue has been duplicated here: https://github.com/chocolatey/choco/issues/1680 and there is more discussion on that issue than compared to here.  As such, I am going to go ahead and close this issue, and we can continue the discussion over there.
