### ISSUE TITLE
when attempting to use a bogus source, the error message does not say the source is bogus

### ISSUE THREAD

**Issue by killerswan** [chocolatey/choco#685]
When using a nonexistent source, the error message is confusing.  That is, with this setup...

``` batch
C:\code>choco --version
0.9.9.12

C:\code>choco source list
chocolatey - https://chocolatey.org/api/v2/ | Priority 0.
```

When trying to install a package from a bogus source ("canada"), the error only says the package ("polarbear") was not found:

``` batch
C:\code>choco install polarbear -source canada
Installing the following packages:
polarbear
By installing you accept licenses for the packages.
polarbear not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "canada"

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
 - polarbear
```

I think the error message should say that the source is bogus. :sweat_smile:

**Comment by pauby** [comment]
The error message is clear in the latest version of Chocolatey CLI.

![image](https://github.com/user-attachments/assets/9837548b-165d-4dbb-a421-3bcbc1bffb73)

I'm going to go ahead and close this, but we can reopen it if necessary.
