### ISSUE TITLE
Report install location

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#689]
Chocolatey should report where the software from a package installs so that it is not a guessing game after install.

**Comment by ferventcoder** [comment]
Requested by @gpakosz

**Comment by ferventcoder** [comment]
#755

**Comment by ortymd** [comment]
Hello,
Thanks for your efforts with this update. It is really a very handy feature.
However I still cannot figure out how this works on 0.10.15.
Could you please provide some details. I cannot find it anywhere in choco help

**Comment by theShiva** [comment]
How is this issue closed? I still don't see any environment variable or a way to find out the location of a package.

**Comment by pauby** [comment]
The environment variable `$env:ChocolateyToolsLocation` determines where software that would be installed to the `tools` folder would go. See [Advanced Variables](https://chocolatey.org/docs/HelpersReference#advanced-environment-variables).

**Comment by ferventcoder** [comment]
@theShiva Packages are always in `$env:ChocolateyInstall\lib` - I believe you are stating you don't know where the install location of software might always be. Chocolatey reports what it learns, but there are additional issues in here that are looking for a more advanced look to make that determination.
