### ISSUE TITLE
install package with different versions fails if not have the exact structure

### ISSUE THREAD

**Issue by drazul** [chocolatey/choco#704]
I'm using chocolatey 0.9.9.11 on a continuous deployment system.

I install packages with this command:
choco install pkg_name -y --skip-powershell -force --allow-downgrade -version x.y.z -source url_source

The problem is when the structure of the package change with more or less number of files or with different names. In that case chocolatey only replace files than exact match with files from older installed version.

I think the problem is very easy to resolve with automatic deletion of package folder before extract the npkg file.

**Comment by ferventcoder** [comment]
@drazul I'm not entirely sure what you are doing, but I'm going to go from the point of what I'm seeing here and you can tell me the use case I'm not seeing?

You need to run this command instead:

`choco upgrade pkgname -y --version x.y.z --source url_source --allow-downgrade` 

* Don't use `--force`. Force means you know better than Chocolatey and are good with bypassing features.
* Don't use `install --force` - you are bypassing Chocolatey's ability to handle upgrades.
* I'm not following on the use of `--skip-powershell`. `--skip-powershell` is telling it to bypass the automation scripts, or in other words possibly do not run an installer.

**Comment by ferventcoder** [comment]
* Don't mix `-longargs` and `--longargs`. It's `-s` or `--source`. When you combine it with `-y` and then mix the usage of the one dash versus the two on other args, you confuse the parser.

**Comment by ferventcoder** [comment]
If you used the word continuous integration system, like a build box, I would have had a better idea that you were testing the package. But you stated continuous deployment, and what I see is completely wrong here.

**Comment by ferventcoder** [comment]
> The problem is when the structure of the package change with more or less number of files or with different names. In that case chocolatey only replace files than exact match with files from older installed version.

> I think the problem is very easy to resolve with automatic deletion of package folder before extract the npkg file.

This is already done with upgrade and uninstall. Both of which are intelligent. If you use uninstall with `--force`, it is merciless - it will remove everything. Without it, it only removes files that are part of the package and not files you have created or changed.

**Comment by ferventcoder** [comment]
> The problem is when the structure of the package change with more or less number of files or with different names. In that case chocolatey only replace files than exact match with files from older installed version.

It may be an issue that `install --force` doesn't behave like `uninstall --force` in that it is not removing all of the files, but I want to understand this use case a bit better first.

**Comment by ferventcoder** [comment]
Right now it is appears you are using Chocolatey as a fancier xcopy deploy and that is really not how it works best. In that case I would suggest just using xcopy.

**Comment by drazul** [comment]
Well, a lot of things here.

First of all I try with `choco upgrade pkg_name --skip-powershell --allow-downgrade --version x.y.z` and works fine, install correctly on cases when previous command failed. But I still think it is a bug, and if upgrade can install package not previously installed and downgrade version  then I think that do the same thing that install. But that is a another different question...

I think, as you say before, that the problem is on `install --force` that not delete folder before install package.

We use chocolatey on CD system because we use chocolatey on other systems, like developers environments. On CD system we use `--skip-powershell` because we need more control over the install script and set different params, locations and configurations.

Thanks for all :)

**Comment by ferventcoder** [comment]
> We use chocolatey on CD system because we use chocolatey on other systems, like developers environments. On CD system we use --skip-powershell because we need more control over the install script and set different params, locations and configurations.

You do know that you can use package parameters do all of this with choco already right? 

You could add in package parameters to set all of the above. https://github.com/chocolatey/choco/wiki/How-To-Parse-PackageParameters-Argument

**Comment by ferventcoder** [comment]
You could also use the presence of environment variables and their values to light up certain things.

**Comment by ferventcoder** [comment]
I'm going to close this as not an issue since it was more about using Chocolatey in a non-recommended way.

If you run into future issues, please open a new issue or start a conversation on our Gitter channel.

Thanks!
