### ISSUE TITLE
Sources should have explicit priority order

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#71]
Lower number equals a higher priority. By default the priority order is whatever is in the file, but if any of the items have a priority order greater than zero, explicit priority order is then used. 

Once you have any source with a priority number, it will have a higher priority than any source with a priority of 0.

~~Chocolatey should be set at 50 or 100.~~ Maybe move this to v1.

This will keep you from having to actually order them by opening the config file.

**Comment by bc3tech** [comment]
I was just going to put in a request to this effect; enable the ability to re-order sources via command (as opposed to hand-edit or programmatic edit of the config file)

:+1:

**Comment by wparad** [comment]
I think part of the point was that even if you programmatically edit the config file there is no guarantee that the order of the sources is the order that you would want.  Is the order guaranteed?  If there are 5 sources, and I add one, is it the 6th one?  I think I would be okay with one main source, and the rest of them be equally weighted fall-backs in which the order is irrelevant to me.  What configuration should I have to obtain that?

**Comment by ferventcoder** [comment]
@wparad The order is based the same way as NuGet currently. So it is the order of the items in the config file. If you add one, it becomes 6th in priority as it will be sixth in the list.

**Comment by wparad** [comment]
That may be good enough.  I think I will try to generate a sources list on the fly then, in the order I care about, and then use that.  For us chocolatey is mostly being called through another tool, so that behavior is likely as good as we need, and being able to use chocolatey to reorder the sources file is not relevant.  Is the mechanism to do that something like `choco install PackageName -source ''http://sourceurl1.com/chocolateyfeed;http://sourceurl2.com/chocaletyfeed''`?

**Comment by ferventcoder** [comment]
> For us chocolatey is mostly being called through another tool, so that behavior is likely as good as we need, and being able to use chocolatey to reorder the sources file is not relevant. 

If this is true, why are you commenting? ;)

**Comment by ferventcoder** [comment]
> Is the mechanism to do that something like choco install PackageName -source ''http://sourceurl1.com/chocolateyfeed;http://sourceurl2.com/chocaletyfeed''?

When you specify sources, you are telling choco to use only what is specified. The order is the one on the left is first. Same behavior though, highest priority to first specified source.

**Comment by ferventcoder** [comment]
@bc3tech I just updated the description. If you agree with it, :+1:

**Comment by bc3tech** [comment]
rock on. :+1:

**Comment by ferventcoder** [comment]
Looks like https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/configuration/ChocolateySource.cs was missed. Let's get it added here as well.
