### ISSUE TITLE
Install from directory fails due to pre-release flag?

### ISSUE THREAD

**Issue by mattheyan** [chocolatey/choco#718]
When trying to install a package, or list packages, in a directory, the command fails if there is a package with a pre-release flag in the version number.

Steps to reproduce:
1. In a local or network folder, place any number of nupkg files, at least one of which has a pre-releaes flag
2. Attempt to install any of the packages in the folder using the `--source` argument.

PS> choco list --source=C:\Users\matthewb\Share\ChocolateyPackages -pre -dv

Output Log:
https://gist.githubusercontent.com/mattheyan/5b5061b130d928cae4147fc2a06150c6/raw/ce2bace52c18a9462c896f979c71cbff77077732/chocolateInstall.log

I noticed at the bottom there is an error, apparently coming from NuGet, "Item has already been added. Key in dictionary: 'content/package.json'". If I remove all pre-release packages, then the other packages are returned by the list command, and I don't see the error. So, maybe a NuGet problem?

Thanks,
Bryan

**Comment by ferventcoder** [comment]
We use NuGet.Core. I'm not sure why it is having issues though. 

Can you provide more information about what you removed?

**Comment by ferventcoder** [comment]
Do you have any NuGet v3 packages installed?

**Comment by mattheyan** [comment]
My apologies. I think this is a bogie. It looks like the package in question is actually corrupt. Sorry for the trouble.

**Comment by ferventcoder** [comment]
Ah, okay. We'll close it for now. If you run into anything like this in the future, we can reopen this issue or start a new one. Thanks for the heads up!
