### ISSUE TITLE
PowerShell Host - Package scripts setting values can affect packages that depend on them

### ISSUE THREAD

**Issue by digitaldrummerj** [chocolatey/choco#719]
### What You Are Seeing?

For the AndroidStudio package that I own I am getting the following error with the latest chocolatey version (Chocolatey v0.9.10-beta1-289-g589515c) that is used as part of the automated test environment.  

```bash
ERROR: Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: An unexpected error
occurred on a receive."
 at Get-WebHeaders, C:\ProgramData\chocolatey\helpers\functions\Get-WebHeaders.ps1: line 92
at Get-ChocolateyWebFile, C:\ProgramData\chocolatey\helpers\functions\Get-ChocolateyWebFile.ps1: line 158
at Install-ChocolateyPackage, C:\ProgramData\chocolatey\helpers\functions\Install-ChocolateyPackage.ps1: line 111
at <ScriptBlock>, C:\ProgramData\chocolatey\lib\AndroidStudio\tools\chocolateyInstall.ps1: line 28
at <ScriptBlock>, C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1: line 48
at <ScriptBlock>, <No file>: line 1
```

This appears to only happen after installing either the JDK7 (Android Studio 1.5 and below) or JDK8 (Android Studio 2.0.0.20) packages that  are part of the dependency list.  If the correct JDK package is already installed then the AndroidStudio package works just fine.

### What is Expected?

Installer to be downloaded and run successfully.  It works against the current production version that is available on the web site.  

### How Did You Get This To Happen? (Steps to Reproduce)

**Error Repo steps**

Use the vagrant test environment  to install the latest AndroidStudio version.

```bash
choco install -fydv AndroidStudio -version 2.0.0.20
```

After it download and installed the android-sdk and jdk8 dependencies successfully, it should error trying to download the AndroidStudio install.

**How to make it pass**

Either ignore the dependencies or install the JDK8 first with choco install -y jdk8.  Then run the install for AndroidStudio.

### Output Log

Log for failure showing error for install of Android Studio 2.0.0.20 when jdk8 is not already installed.  [https://gist.github.com/digitaldrummerj/ea0a56072b9a92af7d4b71371152cbd4](https://gist.github.com/digitaldrummerj/ea0a56072b9a92af7d4b71371152cbd4)

Log for successful install of Android Studio 2.0.0.20 when android-sdk and jdk8 are already installed.  [https://gist.github.com/digitaldrummerj/29a4194f5705db949d658c34696a91d8](https://gist.github.com/digitaldrummerj/29a4194f5705db949d658c34696a91d8)

Log for successful install of Android Studio 2.0.0.20 using choco 0.9.9.12 without jdk8 or android--sdk installed. [https://gist.github.com/digitaldrummerj/c0995757c2e1f005017b62e318ad2eb3](https://gist.github.com/digitaldrummerj/c0995757c2e1f005017b62e318ad2eb3)

### Package Repo

[https://github.com/digitaldrummerj-chocolatey/ChocolateyPackages/tree/master/AndroidStudio](https://github.com/digitaldrummerj-chocolatey/ChocolateyPackages/tree/master/AndroidStudio)

**Dependencies**

[JDK8 for Android Studio 2.0.0.20](https://chocolatey.org/packages/jdk8) and [JDK8 Package Source](https://github.com/ootaken/chocolatey/tree/master/jdk8)

[JDK 7 for Android Studio 1.5 and below](https://chocolatey.org/packages/jdk7) or [JDK7 Package Source](https://github.com/digitaldrummerj-chocolatey/ChocolateyPackages/tree/master/JDK7)

[android-sdk](https://chocolatey.org/packages/android-sdk) or [android-sdk Package Source](https://github.com/yoshimov/chocolatey-packages/tree/master/automatic/android-sdk)

**Comment by ferventcoder** [comment]
When you say this works against the current production version (0.9.9.12), do you mean that it works with the test environment with the current production version?

**Comment by ferventcoder** [comment]
Or are you seeing these errors completely outside of the test environment?

**Comment by digitaldrummerj** [comment]
for the current prod environment 0.9.9.12 I ran it both on the vagrant test environment as well as a Windows 8.1 machine that I have.  

I have not personally tried the beta version outside of the vagrant test environment.

**Comment by ferventcoder** [comment]
I don't see a log for 0.9.9.12 from above. Do you have that gist as well?

**Comment by digitaldrummerj** [comment]
just added the link to the gist log for choco 0.9.9.12 to the initial comment

**Comment by ferventcoder** [comment]
Thanks!

**Comment by ferventcoder** [comment]
Do you believe that this is a gating issue?

**Comment by digitaldrummerj** [comment]
Since we do not know what is causing it or really how to work around it without manually installing dependencies, then to me it is gating.  I don't know if it is because both JDK7 and 8 use custom download logic to set requires cookies values that is causing the issues or what exactly is causing the issue.

**Comment by ferventcoder** [comment]
I put this on the 0.9.10 release for now so that it is at least evaluated and a reason can be determined.

**Comment by digitaldrummerj** [comment]
Did I see that the new version allows custom cookies/headers to be set when it tries to download a file?  If so, I could try to re-write the JDK7 package to use that and see if it fixes the issue.

**Comment by ferventcoder** [comment]
It's a start, but I'm still concerned the other should work.

**Comment by ferventcoder** [comment]
Do we think this is only when it is a dependency? I just attempted with the latest beta and all was fine.

Then I did it with the dependencies and it broke.

`[System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }` Tell me why you set this.

**Comment by digitaldrummerj** [comment]
The JDK7 package was abandoned and when I took over as maintainer it was already in the install script.  So not sure why it is set.

**Comment by ferventcoder** [comment]
Fair statements. What I've gathered so far - installs work when separate (like you mentioned). Something in the first package script is messing up the second package.

**Comment by ferventcoder** [comment]
bumping the priority on this.

**Comment by digitaldrummerj** [comment]
commenting out the `[System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true } ` line fixes the issues with the dependency.

**Comment by ferventcoder** [comment]
That will save me a bit of time - now I need to adjust scripts for isolation.

**Comment by digitaldrummerj** [comment]
Figure out what that line of code is doing.  It is used to deal with invalid, untrusted or expired SSL certificates.  So not sure why we ever needed it. It only affects the current AppDomain, e.g. the current Powershell process.  Quit powershell and restart it and it is good again.  Supposedly setting the property to $null is suppose to make it work the right way again.  Haven't tried that though.

**Comment by digitaldrummerj** [comment]
just validated that setting `[System.Net.ServicePointManager]::ServerCertificateValidationCallback = $null` after downloading JDK8 installer fixed the issue with the dependencies.

**Comment by ferventcoder** [comment]
@digitaldrummerj it's the AppDomain isolation I'm talking about. Internal Host means everything runs in same AppDomain.

**Comment by ferventcoder** [comment]
I knew what the code was doing, sorry I should have stated what the purpose of it was to save you from having to look it up.

**Comment by digitaldrummerj** [comment]
still was good to figure out what it was actually doing and how to fix it within the package.  I submitted a pull request to JDK8 package and I will be uploading a new JDK7 package soon with the fix of setting it to $null.
