### ISSUE TITLE
Environment Variable Changes Require Reboot

### ISSUE THREAD

**Issue by flcdrg** [chocolatey/choco#728]
### What You Are Seeing?

```
C:\dev\git\chocolatey-beyondcompare-integration [master +0 ~2 -0 !]> choco pack
Error when registering components for 'chocolatey.licensed.infrastructure.app.registration.ContainerBinding':
 Exception has been thrown by the target of an invocation.
Error when setting configuration for 'chocolatey.licensed.infrastructure.app.builders.ConfigurationBuilder':
 Exception has been thrown by the target of an invocation.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config' is denied.
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config' is denied.
Maximum tries of 3 reached. Throwing error.
Error serializing type chocolatey.infrastructure.app.configuration.ConfigFileSettings:
 Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config' is denied.
Error updating 'C:\ProgramData\chocolatey\config\chocolatey.config'. Please ensure you have permissions to do so:
 Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config' is denied.
Chocolatey v0.9.10-beta1-322-g791d56e Professional
Attempting to build package from 'beyondcompare-integration.nuspec'.
Successfully created package 'beyondcompare-integration.1.0.0.nupkg'
```
### How Did You Get This To Happen? (Steps to Reproduce)
Running `choco pack` from non-elevated shell.

I don't remember seeing these errors with the previous chocolatey.extension (assuming that is involved)

**Comment by ferventcoder** [comment]
Upgrade to the latest prerelease and let me know if you are still seeing this issue. This is fallout from #724.

**Comment by ferventcoder** [comment]
What happens is that the install tries to remove the user environment variable for "ChocolateyInstall" but due to the bug in #724 it was actually creating an empty one. 

The extension starts failing because it can't find the path to itself anymore. Possibly we need a secondary way for it to validate its location.

**Comment by ferventcoder** [comment]
If that is not what you are seeing (the empty environment variable in user), then it's the other fallout from #303 - which is that we need a way to trigger the system to see that the environment variables have updated and it should respond accordingly.

`refreshenv` is a way to trigger that locally, but if you close and reopen your shell and it comes back (and you don't have the empty environment variable), then a reboot will resolve it until we add more fixes to trigger the update.

**Comment by ferventcoder** [comment]
Let me know which of the above apply. Thanks!

**Comment by flcdrg** [comment]
I thought I'd checked and was running the latest preview. I'll double check just to be sure.

Sent from my Windows Phone
________________________________

**Comment by flcdrg** [comment]
I'm using 0.9.10-beta-20160506 with v1.3.0 of chocolatey.extension.

I have a 'ChocolateyInstall' environment variable set as a system variable, but nothing as a user variable.

**Comment by ferventcoder** [comment]
And when you open a new shell and type `$env:ChocolateyInstall` (posh) or `%ChocolateyInstall%` (cmd.exe), what do you get?

If it is empty, call `refreshenv`. Then see if the value is set. If it is not empty and it was before, you will need a reboot or run `setx trigger 1` to jumpstart explorer.exe.

**Comment by ferventcoder** [comment]
Of course this assumes you are seeing the issues still.

**Comment by flcdrg** [comment]
Yes, still seeing that error.

$env:ChocolateyInstall gives `C:\ProgramData\chocolatey`

**Comment by ferventcoder** [comment]
That is strange that you are still seeing this error. Does it persist after reboot?

**Comment by ferventcoder** [comment]
I should have what I believe is a fix for this soon.

**Comment by ferventcoder** [comment]
This has been released in https://chocolatey.org/packages/chocolatey/0.9.10-beta-20160509

You can upgrade to it with `choco upgrade chocolatey --version 0.9.10-beta-20160509` or after another hour or so you can use `choco upgrade chocolatey -pre`.

**Comment by warpdesign** [comment]
I am getting the same error, just installed chocolatey using an elevated prompt (as suggested) and I get the same error as @flcdrg when running choco from a non-elevated prompt.

**Comment by warpdesign** [comment]
After a reboot it works, but the installation scripts advices to restart any prompt, not to restart the computer: maybe it could be more precise ?

**Comment by ferventcoder** [comment]
@warpdesign I'm not sure what you are running into is quite the same. This issue was about trying to use Chocolatey licensed edition with Chocolatey immediately after install. Perhaps you can expand on what you are running into as part of a new issue? Thanks!
