### ISSUE TITLE
RefreshEnv breaks execution in a bat file

### ISSUE THREAD

**Issue by robertbaker** [chocolatey/choco#731]
I am using RefreshEnv in a install.bat. My bat will install choco and then install packages. I need to call RefreshEnv so the npm commands do not fail after Node is installed.

But RefreshEnv stops the bat execution. It does not execute any commands after RefreshEnv.

```
@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin
@powershell Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
choco feature enable -n allowGlobalConfirmation
choco install git nodejs sourcetree
refreshenv
npm i -g --production npm-windows-upgrade
npm-windows-upgrade -p -v 3.9.0
npm i -g npm-check-updates gulpjs/gulp-cli jasmine karma-cli
echo NodeJS NPM, Git, SourceTree, Gulp, Jasmine, and Karma should now be installed.
pause
```

**Comment by ferventcoder** [comment]
Use `call refreshenv`. Let me know if that works. Otherwise I'm not sure if it will work in a .bat file.

**Comment by robertbaker** [comment]
Think it may have worked but I ran into a similar issue with npm i -g.
