### ISSUE TITLE
Ensure Web Requests and Responses Do Not Timeout - make configurable

### ISSUE THREAD

**Issue by frederic-leger-FR** [chocolatey/choco#732]
Context : Chocolatey v0.9.9.12, with windows 7 and 10.

Cause : Exception occur during package installation with low speed internet access: 

Error message: "Exception calling 'GetResponse' with '0' arguments...". GetResponse timeout in chocolatey\helpers\functions\Get-WebHeaders.ps1.

Workaround : change the "$request.Timeout = xxx" in Get-WebHeaders.ps1:70.

Request solution : add variable in the configuration settings for the timeout. Example:
"choco config set URLTimeout 360000".

Best regards.
F.Leger.

**Comment by ferventcoder** [comment]
👍

**Comment by ferventcoder** [comment]
In fixing this up, both Request and ReadWriteTimeout need adjusted. Both will be adjustable, ReadWriteTimeout will be set to the same value as `--execution-timeout`.

References:

* https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.readwritetimeout(v=vs.80).aspx
* https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.timeout(v=vs.80).aspx

**Comment by ferventcoder** [comment]
Default timeout for requests has been bumped to 45 seconds instead of 20. 

Now configurable through `choco config set webRequestTimeoutSeconds ##`
