### ISSUE TITLE
Package params are also applied to dependent package

### ISSUE THREAD

**Issue by flyonawindshield** [chocolatey/choco#733]
### What You Are Seeing?
If I install a package with install parameters, the parameters are also applied on a dependent package. In this case I'm trying to install a Tomcat instance, which has jdk8 as a dependency. command:

```sh
choco upgrade tomcat -dvy -m -params " INSTALLDIR=C:\Programs\tomcat "
```

Chocolatey fails on `-params " INSTALLDIR=C:\Programs\tomcat "` while installing jdk8, although the parameter wasn't intended for jdk8 at all.

### What is Expected?
It is expected that `-params " INSTALLDIR=C:\Programs\tomcat "` isn't applied on jdk8 while installing tomcat, but only on tomcat.

### How Did You Get This To Happen? (Steps to Reproduce)
Running `choco upgrade tomcat -dvy -m -params " INSTALLDIR=C:\Programs\tomcat "`. However, tomcat and jdk8 packages have been adjusted, so I don't know whether the problem can be reproduced easily. I don't think however that mixing the `-params` in between the two packages is a resultant of the install scripts, because those scripts have as far as I know no role in setting install parameters.

### Output Log
GIST LINK - https://gist.github.com/flyonawindshield/81aaaa430b3119bee112a584ddfdd0ca

**Comment by ferventcoder** [comment]
While I will state that we've documented that this is the case, this scenario is not one you can easily control - you'd have to know to install the dependencies ahead of time or call this with `--ignore-dependencies`.  Neither of those is an optimal scenario. 

Side note - `choco install tomcat --dir c:\Programs\tomcat` will only ever apply to tomcat in Chocolatey Professional / Chocolatey for Business. The ubiquitous install directory switch for all your packages feature is already done and this exact scenario was accounted for already there. https://www.kickstarter.com/projects/ferventcoder/chocolatey-the-alternative-windows-store-like-yum/posts/1565222

Sounds like we need to do something similar for the selectors here.

**Comment by flyonawindshield** [comment]
Thanks for the quick reply! Installing the dependency ahead of time is the solution I'll go for now, although it is a bit more cumbersome as I'm working in the context of Puppet and I normally wouldn't want package-dependency-logic in my modules/profiles.

**Comment by ferventcoder** [comment]
At any rate it is logged as a bug/enhancement and I've marked it for the next release.
