### ISSUE TITLE
Getting LCID doesn't work properly with the built-in PowerShell Host

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#741]
`$LCID = (Get-Culture).LCID` does not appear to produce the proper LCID for a package when running under the PowerShell Internal Host.

* Reference: https://groups.google.com/d/msgid/chocolatey/cb1837ff-7df4-4e5e-8d48-291c18221272%40googlegroups.com

The BeyondCompare package is a good one to test.

**Comment by flcdrg** [comment]
FYI @shiftkey

**Comment by ferventcoder** [comment]
I think I know what this is.

**Comment by ferventcoder** [comment]
I think I have this fixed, but I'm going to need some help getting it validated.

**Comment by shiftkey** [comment]
@ferventcoder is there anything I can help with?

**Comment by ferventcoder** [comment]
Possibly - I think I have a way to verify this though, I spoke a little too soon! I will keep you in the loop if I run into issues!

**Comment by ferventcoder** [comment]
Yup, good to go.

**Comment by ferventcoder** [comment]
Pushed a new version of the beta with just this change - should be available in the next two hours - if you need to get it before then, use `choco upgrade chocolatey -version 0.9.10-beta-20160524`
