### ISSUE TITLE
Attempt to download packages via HTTPS connection

### ISSUE THREAD

**Issue by lennartb-** [chocolatey/choco#746]
Split from #350 

Trying to download certain packages with a HTTP-URL may fail in certain circumstances where for example a firewall blocks download of "insecure" files. Downloading a file via a HTTPS link however may work in that case. While the package URLs are of course dependent on the package maintainer, some server actually also serve via HTTPS besides HTTP.
Besides that HTTPS is more secure (though I can can't say whether this is interesting for choco), it would be convenient to either first try a HTTPS connection before HTTP, or add a flag (e.g. --TryHttps) which tries to force a download via HTTPS.

**Comment by ferventcoder** [comment]
@lennartb-  one thing we've enforced is package checksum now for HTTP. I think we can also attempt to do this as well, which will make things better.

**Comment by ferventcoder** [comment]
This will ease things up a bit for some existing packages. It will attempt to determine if HTTPS is available and then use it to download instead.
