### ISSUE TITLE
[feature] RFP for Chocolatey

### ISSUE THREAD

**Issue by kwill** [chocolatey/choco#783]
The Debian packaging community have <a href="https://wiki.debian.org/RFP">Request for Package</a> as a mechanism to suggest and collaborate on applications not-yet-packaged in the distro. (See also <a href="https://www.debian.org/devel/wnpp/">WNPP</a>.) I could not find an existing location that lists Chocolatey packaging opportunities. Sometimes application maintainers respond to requests for Chocolatey packages, but don't have someone with Chocolatey/Windows experience on the team. [1]

Assuming I haven't missed it, it would be great to have a place to post Chocolately RFPs and be able to see their status.

[1] Self-interested examples https://github.com/quodlibet/quodlibet/issues/1883 and https://github.com/mattermost/desktop/issues/124

**Comment by ferventcoder** [comment]
@kwill out of curiosity, I think this is probably different than what we've documented currently - https://chocolatey.org/docs/package-triage-process#package-request-package-missing. 

I agree it is something we could get better at - having an official way to request packages for folks that are not technically savvy enough to create packages. Of course, our process for creating packages is much, much simpler than creating a Debian package. :)

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/chocolatey-package-requests - DONE

**Comment by ferventcoder** [comment]
Now we just need a way to determine Packages needing adoption

**Comment by 07416** [comment]
Is this the thread for Chocolatey support or: https://github.com/quodlibet/quodlibet/issues/1883

**Comment by 07416** [comment]
@ferventcoder How long does that generally take?

**Comment by ferventcoder** [comment]
@07416 how long does what generally take?

**Comment by 07416** [comment]
I misread your message, I thought that the most important packages are added first. Sorry, I assume "soon".
