### ISSUE TITLE
install - pin package during installation

### ISSUE THREAD

**Issue by CWempe** [chocolatey/choco#798]
I just found out about chocolately and I think this is a great project!

Reading the issues here, I thought of a feature request.

I think it would be great if you could "pin" a package directly during (after) the installation.

Instead of 

```
choco install googlechrome
choco pin googlechrome
```

something like this
`choco install googlechrome --pin`

This would especialy come in handy when installing a list of packages via package.conf.

```
    <?xml version="1.0" encoding="utf-8"?>
    <packages>
      <package id="googlechrome" pin="true" />
    </packages>
```

Then again this might be obsolet (in some cases) when https://github.com/chocolatey/choco/issues/242 gets implemented.

**Comment by ferventcoder** [comment]
@CWempe I believe this has been discussed before and it's a pretty great idea! I'm surprised that there wasn't already an existing ticket (I searched), perhaps from the prior discussions one was not created.

**Comment by gep13** [comment]
Any change in this area will require an upstream change in the chocolatey.extension to ensure that any and all new logic is respected there.

**Comment by gep13** [comment]
A follow up spike task has been created to confirm that this functionality continues to work as expected when the Chocolatey Licensed Extension is installed: https://gitlab.com/chocolatey/collaborators/choco-licensed/-/issues/631
