### ISSUE TITLE
30s hang attempting to perform "InitializeDefaultDrives" when a network drive is disconnected

### ISSUE THREAD

**Issue by alexchandel** [chocolatey/choco#804]
When running `choco upgrade all` on a machine with at least one outdated package, and a network drive that's disconnected and unreachable (and also several physical disconnected drives), chocolatey hangs at every package that needs upgrading for at least 30s after printed "You have x installed. Version..." but before printing anything else.

After the hang, it prints the error message "Attempting to perform the InitializeDefaultDrives operation on the 'FileSystem' provider failed." and continues as normal.

**Comment by ferventcoder** [comment]
That is a PowerShell issue. You likely have PowerShell v3 installed as this is a known bug in that version.

**Comment by ferventcoder** [comment]
If it does not, you will still need to upgrade PowerShell to a version that is not known to have this issue - such as PowerShell 4/5.

HTH
