### ISSUE TITLE
Get-Processorbits function seems to be broken

### ISSUE THREAD

**Issue by sippi90** [chocolatey/choco#809]
Hi there,

since I updated MPC-BE package and did a bit of testing on Win10 x64/x86 VMs I noticed that the Get-Processorbits function seems to be broken.

Code:
$bits = Get-ProcessorBits
if ($bits -eq '64')
{
Install-ChocolateyPath 'C:\Program Files\MPC-BE x64'
}
else
{
Install-ChocolateyPath 'C:\Program Files\MPC-BE'
}

This should install shims on 32-Bit machines to path 'C:\Program Files\MPC-BE' but it doesn't.
It's creating shims for 'C:\Program Files\MPC-BE x64'

**Comment by jberezanski** [comment]
As I wrote on the mailing list, the strictly correct comparison code should be:

    if ($bits -eq 64)

because Get-ProcessorBits returns an int.

However, both variants work correctly on my Windows 10 x64 (build 10586), using [the latest code](https://github.com/chocolatey/choco/blob/f7a2fc93fb489661d470321e53f7120ba72b2f96/src/chocolatey.resources/helpers/functions/Get-OSArchitectureWidth.ps1):

````
C:\> $bits = Get-ProcessorBits
C:\> $bits -eq '64'
True
C:\> $bits -eq 64
True
C:\> $bits -eq '32'
False
C:\> $bits -eq 32
False
````

**Comment by jberezanski** [comment]
Ah, I just realized you were reporting invalid behavior on x86, not x64. Here is a test on Windows 7 x86:

````
PS C:\> $Env:PROCESSOR_ARCHITECTURE
x86
PS C:\> $bits = Get-ProcessorBits
PS C:\> $bits
32
PS C:\> $bits -eq 64
False
PS C:\> $bits -eq '64'
False
````

**Comment by jberezanski** [comment]
I just installed mpc-be on that Windows 7 system (.NET 4.0, PowerShell 2.0) and the path addition was correct:

````
PS C:\> cinst -dvy mpc-be -version 1.4.6
(...)
Chocolatey v0.9.10
Chocolatey is running on Windows v 6.1.7601.65536
(...)
Running 'Get-OSArchitectureWidth'
CPU is 32 bit
(...)
mpc-be has been installed.
Running 'Get-OSArchitectureWidth'
Running 'Install-ChocolateyPath' with pathToInstall:'C:\Program Files\MPC-BE'
````

One more issue with your code: there is no guarantee that Program Files is on C: drive (or, in fact, that it is named Program Files!). You should use `$Env:ProgramFiles` instead of hardcoding `C:\Program Files`.

**Comment by ferventcoder** [comment]
@jberezanski Inside the PowerShell host - this could be an issue. Better to create a package that does this. Let me post one.

**Comment by ferventcoder** [comment]
[test-environment.1.0.0.nupkg.zip](https://github.com/chocolatey/choco/files/321425/test-environment.1.0.0.nupkg.zip)

**Comment by ferventcoder** [comment]
Try this in 0.9.10 and see what it reports.

**Comment by ferventcoder** [comment]
@sippi90 Thanks for finding the bug - I do agree with @jberezanski that you are not going about finding the install directory correctly. A much more deterministic way to get this is to get the install location from the uninstaller registry key - https://gist.github.com/choco-bot/cc2a1764e8fc24943d1391979847a7f3#file-1-registrysnapshot-xml-L1-L9. You want to follow the code example from https://chocolatey.org/docs/helpers-get-uninstall-registry-key (source code is https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Get-UninstallRegistryKey.ps1).

**Comment by jberezanski** [comment]
````
Running 'C:\ProgramData\chocolatey\lib\test-environment\tools\chocolateyinstall.ps1'
TEMP=C:\Users\W732\AppData\Local\Temp\chocolatey
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\W732\AppData\Roaming
CHOCOLATEY_VERSION=0.9.10.0
CHOCOLATEY_VERSION_PRODUCT=0.9.10
ChocolateyEnvironmentDebug=true
ChocolateyEnvironmentVerbose=true
ChocolateyInstall=C:\ProgramData\chocolatey
ChocolateyLastPathUpdate=Sat Jun 18 01:17:17 2016
chocolateyPackageFolder=C:\ProgramData\chocolatey\lib\test-environment
chocolateyPackageName=test-environment
chocolateyPackageVersion=1.0.0
ChocolateyPowerShellHost=true
chocolateyRequestTimeout=30000
chocolateyResponseTimeout=2700000
CommonProgramFiles=C:\Program Files\Common Files
COMPUTERNAME=W732-PC
ComSpec=C:\Windows\system32\cmd.exe
FP_NO_HOST_CHECK=NO
HOMEDRIVE=C:
HOMEPATH=\Users\W732
IS_ADMIN=true
IS_PROCESSELEVATED=true
LOCALAPPDATA=C:\Users\W732\AppData\Local
LOGONSERVER=\\W732-PC
NUMBER_OF_PROCESSORS=2
OS=Windows_NT
OS_IS64BIT=false
OS_NAME=Windows 7
OS_PLATFORM=Windows
OS_VERSION=6.1.7601.65536
packageFolder=C:\ProgramData\chocolatey\lib\test-environment
packageName=test-environment
packageVersion=1.0.0
Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\
chocolatey\bin;;C:\Program Files\MPC-BE;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;
PROCESSOR_ARCHITECTURE=x86
PROCESSOR_IDENTIFIER=x86 Family 6 Model 23 Stepping 10, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=170a
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
PSModulePath=;C:\Windows\system32\WindowsPowerShell\v1.0\Modules\;C:\Users\W732\Documents\WindowsPowerShell\Modules;
PUBLIC=C:\Users\Public
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\W732\AppData\Local\Temp\chocolatey
TMP=C:\Users\W732\AppData\Local\Temp
USERDOMAIN=W732-PC
USERNAME=W732
USERPROFILE=C:\Users\W732
windir=C:\Windows
windows_tracing_flags=3
windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log
Running 'Get-OSArchitectureWidth'
Get-ProcessorBits = 32
$bits -eq '64' = False
$bits -eq 64 = False
$bits -eq '32' = True
$bits -eq 32 = True
ERROR: Cannot bind argument to parameter 'exitCode' because it is null.
    at System.Management.Automation.ParameterBinderBase.ValidateNullOrEmptyArgument(CommandParameterInternal parameter,
CompiledCommandParameter parameterMetadata, Type argumentType, Object parameterValue, Boolean recurseIntoCollections)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommand
Parameter parameterMetadata, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, Merg
edCompiledCommandParameter parameter, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterI
nternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
   at System.Management.Automation.ParameterBinderController.BindPositionalParametersInSet(UInt32 validParameterSets, Di
ctionary`2 nextPositionalParameters, CommandParameterInternal argument, ParameterBindingFlags flags, ParameterBindingExc
eption& bindingException)
   at System.Management.Automation.ParameterBinderController.BindPositionalParameters(Collection`1 unboundArguments, UIn
t32 validParameterSets, UInt32 defaultParameterSet, Boolean ignoreArgumentsThatLookLikeParameters, ParameterBindingExcep
tion& outgoingBindingException)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 ar
guments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters(CommandParameterInternal[] parameters)
   at System.Management.Automation.CommandProcessor.Prepare(CommandParameterInternal[] parameters)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(CommandParameterInternal[] parameters)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorR
esults, Boolean enumerate)
Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Th
read]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller
.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\t
est-environment\tools\chocolateyinstall.ps1' -installArguments '' -packageParameters '''] exited with '-1'.
````
[full console output](https://gist.github.com/jberezanski/dee68713aea76e84f99727201187a6a5)

**Comment by ferventcoder** [comment]
@jberezanski I'm assuming you scrubbed the environment variables prior to posting.

Also, what is that last thing there and how did you get that to happen?

**Comment by jberezanski** [comment]
I did not alter the output in any way; this is one of my test VMs, no sensitive data there.

No idea why the package installation failed. Perhaps because it did not invoke Start-ChocolateyProcessAsAdmin (or any other install helper) and so $env:ChocolateyExitCode was never populated?

What I did, step by step, after booting the VM:

1. Installed Chocolatey from elevated PowerShell:

````
Set-ExecutionPolicy RemoteSigned -Force
iex (New-Object Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')
````

2. In a new elevated PowerShell:

````
  Id CommandLine
  -- -----------
   1 cd \
   2 cinst -dvy mpc-be
   3 cinst -dvy mpc-be -version 1.4.6
   4 $env:path
````

3. Downloaded your test package to C:\Users\W732\Downloads

4. In the same elevated PowerShell as in step 2:

````
   5 cinst -dvy -source C:\Users\W732\Downloads test-environment
````

Additional environment information: the OS is an almost completely unpatched (only 9 patches from 2013.12) Win7 Professional SP1 with only .NET 4.6.1 installed (I wrote ".NET 4.0" by mistake in a previous comment). Polish language.

**Comment by ferventcoder** [comment]
Just filed #810. It's supposed to be looking at lastexitcode, but that looks like it may not return correctly in all cases. Not sure if that is a culture specific thing or not yet.

**Comment by sippi90** [comment]
1. I've now clean reverted a snapshot of my Win10 32-bit VM.
2. Removed the ' ' from ($bits -eq '64') -> ($bits -eq 64).
3. And I'm parsing Installpath from uninstallcode as suggested.
Profit: Now everything is working!
Many Thanks guys!

**Comment by ferventcoder** [comment]
Thanks.
