### ISSUE TITLE
Get-UninstallRegistryKey fixes/improvements

### ISSUE THREAD

**Issue by dtgm** [chocolatey/choco#815]
##### Fixes
- [x] 1. Not building array properly; fails if more than one bad key
- [x] 2. Not reporting correct key
##### Changes -- proposed
- [x] 1. (logic) Remove limit on bad keys, but 
- [x] 2. (reporting) ^^^ add warning about possibly corrupted registry if many are found.
- [x] 3. (reporting) write-verbose if no registry keys matched SoftwareName

**Comment by gep13** [comment]
I have just merged this into the repository, and am away to push the new version of the package.

**Comment by gep13** [comment]
And pushed...
