### ISSUE TITLE
0.9.10 breaks Install-ChocolateyZipPackage (PSWindowsUpdate)

### ISSUE THREAD

**Issue by Workshop2** [chocolatey/choco#818]
### What You Are Seeing?
Since 0.9.10.1 has been released this package no longer installs (even though everything is said to be working). This package seems to use `Install-ChocolateyZipPackage`

### What is Expected?
I expected to see the the PS files to be installed to `(Join-Path $PSHome "Modules\PSWindowsUpdate")` but nothing gets copied

### How Did You Get This To Happen? (Steps to Reproduce)
Run this script on a 2008R2 machine

### Output Log
Broken log:
![image](https://cloud.githubusercontent.com/assets/1476513/16213426/2847b952-3747-11e6-8e17-00096383af72.png)

Working log from 0.9.9.12
![image](https://cloud.githubusercontent.com/assets/1476513/16213447/61bec2b6-3747-11e6-8ca5-201eb353f7fb.png)

**Comment by ferventcoder** [comment]
#812

**Comment by ferventcoder** [comment]
Updated last comment

**Comment by ferventcoder** [comment]
Looking at this closer, it appears that the extraction doesn't wait for the exit code, which means the process is returning before it is fully closed.

**Comment by ferventcoder** [comment]
Take a look at the debug output in your log file, you will see "7z exit code: " and no exit code.

**Comment by ferventcoder** [comment]
@Workshop2 can you provide log output here? You will find it in c:\programdata\chocolatey\logs (just grab from where you ran the command and down to the end result). If you can paste that to a gist and then link that here, that would be helpful to know what the error was (in your case it was silent) but I can not reproduce it yet.

**Comment by ferventcoder** [comment]
#830 appears to be related. 

I believe this is good to go with the switch to 7zip full in 0.9.10.3. As a note, I was not able to reproduce this issue exactly, so please comment if you are still seeing this issue.
