### ISSUE TITLE
NotSilent fails with - Cannot bind argument to parameter statements because it is an empty string

### ISSUE THREAD

**Issue by SecTec** [chocolatey/choco#819]
Hi,
I'm running choco v 0.9.10.2.
Since the upgrade to 0.9.10.2 I can't update any installed package.
I don't know if its a problem with the package or chocolaty (sorry if I'm writing to the wrong people).

Every package fails its upgrade with
`Cannot bind argument to parameter 'statements' because it is an empty string`

The command used to upgrade is:

`choco upgrade all -y --notsilent`

I use the package sandboxie as an example. The log says:
`[INFO ] - Download of SandboxieInstall64-512.exe (5.23 MB) completed.
[INFO ] - 
[DEBUG] - No virus checking built into FOSS Chocolatey. Check out Pro or Business if you need this. https://chocolatey.org/compare
[DEBUG] - Checking that 'C:\Users\user\AppData\Local\Temp\chocolatey\sandboxie.install\5.12\SandboxieInstall64-512.exe' is the size we expect it to be.
[DEBUG] - Verifying package provided checksum of 'd3b0e9dbda7a503103f5398e2b84694b24752d80' for 'C:\Users\user\AppData\Local\Temp\chocolatey\sandboxie.install\5.12\SandboxieInstall64-512.exe'.
[DEBUG] - Running 'Get-ChecksumValid' with file:'C:\Users\user\AppData\Local\Temp\chocolatey\sandboxie.install\5.12\SandboxieInstall64-512.exe', checksum: 'd3b0e9dbda7a503103f5398e2b84694b24752d80', checksumType: 'sha1'
[DEBUG] - checksum.exe found at 'C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe'
[DEBUG] - Executing command ['C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe' -c="d3b0e9dbda7a503103f5398e2b84694b24752d80" -t="sha1" -f="C:\Users\user\AppData\Local\Temp\chocolatey\sandboxie.install\5.12\SandboxieInstall64-512.exe"]
[DEBUG] - Command ['C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe' -c="d3b0e9dbda7a503103f5398e2b84694b24752d80" -t="sha1" -f="C:\Users\user\AppData\Local\Temp\chocolatey\sandboxie.install\5.12\SandboxieInstall64-512.exe"] exited with '0'.
[DEBUG] - Running 'Install-ChocolateyInstallPackage' for sandboxie.install with file:'C:\Users\user\AppData\Local\Temp\chocolatey\sandboxie.install\5.12\SandboxieInstall64-512.exe', args: '/S /upgrade', fileType: 'exe', validExitCodes: '0', useOnlyPackageSilentArguments: 'False'
[INFO ] - Installing sandboxie.install...
[INFO ] - 
[ERROR] - ERROR: Cannot bind argument to parameter 'statements' because it is an empty string.
[DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\sandboxie.install\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters '''] exited with '-1'.
[DEBUG] - Calling command ['"C:\Windows\System32\shutdown.exe" /a']
[DEBUG] - Command ['"C:\Windows\System32\shutdown.exe" /a'] exited with '1116'
[DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\sandboxie.install'`

**Comment by ferventcoder** [comment]
Chocolatey - let's update this to say NotSilent is broken. As a workaround
leave off notsilent for now.

On Tuesday, June 21, 2016, SecTec <notifications@github.com> wrote:

> Hi,
> I'm running choco v 0.9.10.2.
> Since the upgrade to 0.9.10.2 I can't update any installed package.
> I don't know if its a problem with the package or chocolaty (sorry if I'm
> writing to the wrong people).
>
> Every package fails its upgrade with
> Cannot bind argument to parameter 'statements' because it is an empty
> string
>
> The command used to upgrade is:
>
> choco upgrade all -y --notsilent
>
> I use the package sandboxie as an example. The log says:
> [INFO ] - Download of SandboxieInstall64-512.exe (5.23 MB) completed.
> [INFO ] -
> [DEBUG] - No virus checking built into FOSS Chocolatey. Check out Pro or
> Business if you need this. https://chocolatey.org/compare
> [DEBUG] - Checking that
> 'C:\Users\user\AppData\Local\Temp\chocolatey\sandboxie.install\5.12\SandboxieInstall64-512.exe'
> is the size we expect it to be.
> [DEBUG] - Verifying package provided checksum of
> 'd3b0e9dbda7a503103f5398e2b84694b24752d80' for
> 'C:\Users\user\AppData\Local\Temp\chocolatey\sandboxie.install\5.12\SandboxieInstall64-512.exe'.
> [DEBUG] - Running 'Get-ChecksumValid' with
> file:'C:\Users\user\AppData\Local\Temp\chocolatey\sandboxie.install\5.12\SandboxieInstall64-512.exe',
> checksum: 'd3b0e9dbda7a503103f5398e2b84694b24752d80', checksumType: 'sha1'
> [DEBUG] - checksum.exe found at
> 'C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe'
> [DEBUG] - Executing command
> ['C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe'
> -c="d3b0e9dbda7a503103f5398e2b84694b24752d80" -t="sha1"
> -f="C:\Users\user\AppData\Local\Temp\chocolatey\sandboxie.install\5.12\SandboxieInstall64-512.exe"]
> [DEBUG] - Command
> ['C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe'
> -c="d3b0e9dbda7a503103f5398e2b84694b24752d80" -t="sha1"
> -f="C:\Users\user\AppData\Local\Temp\chocolatey\sandboxie.install\5.12\SandboxieInstall64-512.exe"]
> exited with '0'.
> [DEBUG] - Running 'Install-ChocolateyInstallPackage' for sandboxie.install
> with
> file:'C:\Users\user\AppData\Local\Temp\chocolatey\sandboxie.install\5.12\SandboxieInstall64-512.exe',
> args: '/S /upgrade', fileType: 'exe', validExitCodes: '0',
> useOnlyPackageSilentArguments: 'False'
> [INFO ] - Installing sandboxie.install...
> [INFO ] -
> [ERROR] - ERROR: Cannot bind argument to parameter 'statements' because it
> is an empty string.
> [DEBUG] - Built-in PowerShell host called with
> ['[System.Threading.Thread]::CurrentThread.CurrentCulture =
> '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; &
> import-module -name
> 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; &
> 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1'
> -packageScript
> 'C:\ProgramData\chocolatey\lib\sandboxie.install\tools\chocolateyInstall.ps1'
> -installArguments '' -packageParameters '''] exited with '-1'.
> [DEBUG] - Calling command ['"C:\Windows\System32\shutdown.exe" /a']
> [DEBUG] - Command ['"C:\Windows\System32\shutdown.exe" /a'] exited with
> '1116'
> [DEBUG] - Capturing package files in
> 'C:\ProgramData\chocolatey\lib\sandboxie.install'
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/chocolatey/choco/issues/819>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAD4DmCr5lOSGWfNEHuba4L-F1RK3H1hks5qN_BZgaJpZM4I6xpL>
> .
>


-- 

Rob
"Be passionate in all you do"

http://codebetter.com/robreynolds
http://ferventcoder.com
https://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
Another fallout from #697.

**Comment by ferventcoder** [comment]
This will be out in 0.9.10.3
