### ISSUE TITLE
Ignore ValidPackage Exit Codes For Real

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#827]
@mwrock discovered that attempting to ignore package exit codes still returns the exit codes.

**Comment by mwrock** [comment]
Here is a transcript of an install with `--debug` https://gist.github.com/mwrock/00161c222cce9a0efd222c5eb8f38604

**Comment by ferventcoder** [comment]
And this will be out in a little while.

**Comment by ferventcoder** [comment]
Today likely, possibly tomorrow

**Comment by ferventcoder** [comment]
@mwrock Just pushed. Should be live within two hours. You can upgrade to it by specifying `choco upgrade chocolatey --version 0.9.10.3`
