### ISSUE TITLE
Get-OSArchitectureWidth doesn't do what it says it does

### ISSUE THREAD

**Issue by dtgm** [chocolatey/choco#828]
Ref: #713 Rename Get-ProcessorBits as a more appropriately named Get-OSArchitectureWidth

`Get-OSArchitectureWidth` returns the current *process* bit-width regardless of OS arch. So in 32-bit powershell running on 64-bit windows, it returns `32` because `[System.IntPtr]::Size` returns `4` in 32-bit process regardless of OS architecture (32 or 64)

The helper should be replaced by testing whether process is running on 64-bit OS if the intent is to return what the helper says it will.

So if `[System.IntPtr]::Size` returns `4`, also do `test-path env:\PROCESSOR_ARCHITEW6432`

```
if ([IntPtr]::size -eq 8) {
  $bits = 64
} elseif (([IntPtr]::size -eq 4) -and (test-path env:\PROCESSOR_ARCHITEW6432)) {
  $bits = 64
} else {
  $bits = 32
}
```

**Comment by dtgm** [comment]
Current script should be changed from

```
  $bits = 64
  if ([System.IntPtr]::Size -eq 4) {
    $bits = 32
  }
```
to
```
  $bits = 64
  if (([IntPtr]::Size -eq 4) -and (test-path env:\PROCESSOR_ARCHITEW6432)) {
    $bits = 64
  } elseif ([IntPtr]::Size -eq 4) {
    $bits = 32
  }
```

**Comment by ferventcoder** [comment]
Looks good

**Comment by dtgm** [comment]
How about adding parameter switches to this helper? so

`Get-OSArchitectureWidth` alias:`Get-ProcessorBits`
* `-System` (default) and 
* `-Process` to return memory addressing bit width of posh we are working in.

or would `Get-ProcessorBits -Process` be too confusing?

If I had a blank slate to work with, I would do `Get-BitWidth` because that seems most intuitive (and I'm too lazy to type Architecture)
`Get-BitWidth -OS`
`Get-BitWidth -Process`

**Comment by dtgm** [comment]
Checking process is simply `if ([System.IntPtr]::Size -eq 4) {"32 bit posh"}`

It is currently being used in 2 helpers:

[Install-ChocolateyVsixPackage.ps1#L113](https://github.com/chocolatey/choco/blob/1889f7e87c902174e31f4ae855e03be149f0a340/src/chocolatey.resources/helpers/functions/Install-ChocolateyVsixPackage.ps1#L113)
[Install-ChocolateyVsixPackage.ps1#L129](https://github.com/chocolatey/choco/blob/1889f7e87c902174e31f4ae855e03be149f0a340/src/chocolatey.resources/helpers/functions/Install-ChocolateyVsixPackage.ps1#L129)
[Get-ChocolateyUnzip.ps1#L115](https://github.com/chocolatey/choco/blob/40f3066af2bd4916d1ba05480d975955d43f0864/src/chocolatey.resources/helpers/functions/Get-ChocolateyUnzip.ps1#L115)

I can't think of any packages that were using `Get-ProcessorBits` to detect bit of posh it is running in tho, but may be good to have a simple way of providing that if maintainers were with minimal change on their end?

**Comment by jberezanski** [comment]
I'd vote for Get-OSBitness and Get-ProcessBitness, personally.
The term "bitness" seems more intuitive for me, besides, "bit width" sounds technically incorrect, as a bit is always a bit and it is the pointer length / address bus width that varies.
The latter cmdlet name would also tie in nicely with Test-ProcessAdminRights.

**Comment by ferventcoder** [comment]
Merged into stable at https://github.com/chocolatey/choco/commit/45ccd77a0b73a0d0c92f0c3ffbeed0172d4f4f6b
