### ISSUE TITLE
Do not install tab completion (edit of profile) under certain conditions

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#833]
During install, do not try to update/create the profile if an environment variable exists.

We may want to look at the execution policy for the machine and respond accordingly to not automatically installing the profile unless it meets a minimum level to reduce issues with running PowerShell later.
- [x] Do not create profile if it doesn't already exist.
- [x] Do not set profile if user is SYSTEM.
- [x] Do not create set profile if `$env:ChocolateyNoProfile` exists.
- [x] Don't edit the profile if it is authenticode signed.

**Comment by RedBaron2** [comment]
@ferventcoder Wouldn't something like this work the best.

`Install-ChocolateyEnvironmentVariable -variableName "ChocolateyProfile" -variableValue {true/false}`

This is then checked by `function Add-ChocolateyProfile` for {true/false}

The only thing I see as an issue will be those that had the profile installed previously without the environment variable. I might suggest they add the variable to windows manually ( I know not exactly automated )

The alternative is to just add a chocolatey cmd line switch when installing chocolatey.

**Comment by dragon788** [comment]
As in the above referenced issue, this is causing "failures" in the vagrant-dsc plugin due to an extra "Preparing modules for first use" message that appears if the Chocolatey created profile exists, but only with PowerShell 5.

**Comment by ferventcoder** [comment]
I think we are just going to pull this from the installer and move to an additional command to install/uninstall the profile.
