### ISSUE TITLE
Wrong Windows version reported for Windows 8.1/Server 2012 R2 and newer

### ISSUE THREAD

**Issue by chucker** [chocolatey/choco#84]
If you run `choco -debug`, it will report the Windows version it's running on, like this:

    Chocolatey is running on Windows v 6.2.9200.0

Starting with Windows 8.1 or Server 2012 R2, this will (deliberately) return the incorrect result for compatibility reasons. `choco.exe` needs to ship with an appropriate manifest to explicitly declare compatibility for recent and upcoming Windows versions, e.g.:

    <?xml version="1.0" encoding="utf-8"?>
    <asmv1:assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1" xmlns:asmv1="urn:schemas-microsoft-com:asm.v1" xmlns:asmv2="urn:schemas-microsoft-com:asm.v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    [..]
      <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
        <application>
          
          <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" />
          
          <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}" />
          <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}" />
          <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}" />
          <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}" />
        </application>
      </compatibility>
    </asmv1:assembly>

The `GetVersionEx` API will check for the `supportedOS` values in the manifest; thus, with such a manifest present, the version will be reported correctly again.

References: https://msdn.microsoft.com/en-us/library/windows/desktop/ms724451(v=vs.85).aspx, http://blogs.msdn.com/b/chuckw/archive/2013/09/10/manifest-madness.aspx

**Comment by ferventcoder** [comment]
This links to #77
