### ISSUE TITLE
Ensure environment variables are set/updated prior to calling alternative sources

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#840]
Related to #532 and #826.

It appears that there are issues with the TEMP environment variable when using alternative sources. Ensure that environment variables are set appropriately before calling alternative sources like WindowsFeatures.

- [x] ensure items are set prior to calling alternative sources 
- [x] Set the TMP variable to config.CacheLocation as well
- [x] Do not set user variables for SYSTEM user

**Comment by Q2-Azure-Infrastructure** [comment]
Rob, do you know of any workaround I could put in my PS script?  I tried both refreshenv after installing choco and manually setting the $env:TEMP folder before installing the dism package but no go in either case.

**Comment by ferventcoder** [comment]
@Q2-Azure-Infrastructure I've marked the priority high on this. I think you could just use DISM directly and get around this for now. That or create a junction/symlink from the folder it wants back to C:\Windows\TEMP for now.

**Comment by ferventcoder** [comment]
@eric-swann-q2 so wait, 0.9.10.2 does not have this issue but 0.9.10.3 does? I'm not sure what would have changed to cause it versus fixing it...

**Comment by eric-swann-q2** [comment]
Yes, correct...I remembered it working for me in 0.9.10.2, so I dialed back and manually put in the cache location (to account for the fix you added in 0.9.10.3) and it now successfully installs windows features.  Perhaps the cache fix (or some other) inadvertently caused this.  Not really sure, but yes it definitely doesn't install windows features in 10.3 and definitely does in 10.2
