### ISSUE TITLE
Please name serialized logs to end with ".log"

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#845]
Searched and couldn't find a similar issue.

Currently the chocolatey log name serializes as such:

..\logs\chocolatey.log
..\logs\chocolatey.log.1
..\logs\chocolatey.log.2

This means that any application I have mapped to open *.log has to be fussed with each time I open a serialized log file.

Would be helpful if the serialized logs still ended in .log.

**Comment by ferventcoder** [comment]
This one is pretty easy (I think). Let's see if we can squeeze this into next release

**Comment by ferventcoder** [comment]
Merged into stable at https://github.com/chocolatey/choco/commit/19957f894b68a002bb2fff58b1f338004258259a
