### ISSUE TITLE
Some packages can not be installed without explicit version within company.

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/choco#846]
This happens only within my company and on all types of Windows OS: 7 - 10.

Some packages can never be installed unless `-version` is set to the latest one. This can happen with any package in dependency hierarchy in which case, to install the package, you must manually install all dependencies with explicit version set. 

It seems random and doesn't depend on a package age. Its random in a sense that package that doesn't work, always doesn't work on particular computer (it might work on another one which has the different set of unworking packages or none at all) but why specific packages fail is unknown.

This happens for a duration of year or so.

Here is the systemexplorer installation log that I encountered today around 16:15h.
The transcript is available as gist: https://gist.github.com/anonymous/6061e7b5c4b13d6f96f555e16aa0bcf8 

Previously failed packages included well known and used ones such as ruby, syinternals etc.

Choco 0.9.10.3.

**Comment by ferventcoder** [comment]
This looks to me to be due to the heavy load. You have seen our messaging about intermittent failures?

**Comment by dtgm** [comment]
Definitely looks like a network connectivity issue:

https://gist.github.com/anonymous/6061e7b5c4b13d6f96f555e16aa0bcf8#file-choco_error-log-L76
>[NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

I've never seen that error from anyone so I am inclined it is more an issue on your company's end.

What does your network path to the api resource look like? 
Is your company distributed so the network path differs in some way?
Have you experienced any other network access issues with your ISP to other resources?

**Comment by ferventcoder** [comment]
I've seen it in the past. I think things are starting to clear up now so you shouldn't run into this much.

**Comment by majkinetor** [comment]
@dtgm 
> Definitely looks like a network connectivity issue

It looks like one but it NEVER passes without version and it ALWAYS passes with version so that kinda doesn't look like a network error.

> What does your network path to the api resource look like? 

Do you mean ` tracert chocolatey.org` ?

> Is your company distributed so the network path differs in some way?

No

> Have you experienced any other network access issues with your ISP to other resources?

No

@ferventcoder 
>I've seen it in the past. I think things are starting to clear up now so you shouldn't run into this much.

Define 'past'. This happens for over a year without any change in frequency. You previously stated that it is something with new packages and elasticsearch but that obviously isn't that issue.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/chocolatey.org/issues/397

**Comment by majkinetor** [comment]
Irrelevant to this issue.

**Comment by ferventcoder** [comment]
Based on the log you posted, it was 397. It was having issues with connecting. Whether your log is the same as the other issues you have been seeing or not is what we are attempting to figure out.

**Comment by majkinetor** [comment]
Most definitely related to #1004

**Comment by majkinetor** [comment]
This is resolved with #1004

**Comment by majkinetor** [comment]
This is still not resolved.

**Comment by donbecker** [comment]
Just experienced this issue. 
Chocolatey v0.10.8 on Windows 10.
`cinst -y golang`

**Comment by majkinetor** [comment]
@donbecker, are you behind the proxy ?

**Comment by donbecker** [comment]
@majkinetor Nope. The status page for Chocolatey just went orange, so I would guess that is the cause. 

Rereading this GH issue I wasn't able to get the package to install with explicit version either, my mistake.

**Comment by Bonnev** [comment]
@majkinetor I'm using v0.10.15 and the behavior is the same:
"Error retrieving packages from source 'http://chocolatey.org/api/v2/':

- "choco install ditto --pre" on powershell with admin rights
-  Error "Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity."
- I tried changing https to http in chocolatey.config but still the same.
- Adding -version installs successfully

I'd say the issue persists...
