### ISSUE TITLE
Can't upgrade packages.

### ISSUE THREAD

**Issue by imkebe** [chocolatey/choco#848]
Just typing :-1: 

```#> choco upgrade all```

and choco says:

```
Upgrading the following packages:
all
By upgrading you accept licenses for the packages.
adb v1.0.32.230 is the latest version available based on your source(s).
autohotkey.install v1.1.24.00 is the latest version available based on your source(s).
autohotkey.portable v1.1.24.00 is the latest version available based on your source(s).

binroot was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""; Source(s): "https://chocolatey.org/api/v2/"
btsync v2.3.6 is the latest version available based on your source(s).

You have chocolatey v0.9.10.2 installed. Version 0.9.10.3 is available based on your source(s).

chocolatey v0.9.10.3 [Approved]
chocolatey not upgraded. An error occurred during installation:
 Długość ciągu nie może wynosić zero.
Nazwa parametru: variable
The upgrade of chocolatey was NOT successful.
chocolatey not upgraded. An error occurred during installation:
 Długość ciągu nie może wynosić zero.
Nazwa parametru: variable
```
It doesn't matter if I upgrade all or simply one package. It used to work some time ago but i didn't realized when it stooped 

Translation:
PL  ``` Długość ciągu nie może wynosić zero. Nazwa parametru: variable ``` 
EN ``` String cannot be of zero length. Parameter name: variable```

Detailed debug : https://gist.github.com/imkebe/c445679f163deb86c285136112186e63

**Comment by ferventcoder** [comment]
There was an issue in 0.9.10.2 that you may be seeing here.

**Comment by imkebe** [comment]
I've updated Chocolatey to 0.9.10.3. Same problem.

**Comment by ferventcoder** [comment]
This is really strange. But that you are seeing it with every package makes me think the problem may be in pending check.

**Comment by ferventcoder** [comment]
@imkebe that doesn't appear to be 0.9.10.3. Still reporting 0.9.10.2

**Comment by ferventcoder** [comment]
This looks like an issue in NuGet.Core on further review :/

**Comment by ferventcoder** [comment]
Let's see if we can fix that.

**Comment by imkebe** [comment]
@ferventcoder filer provided gist with 2016-07-05 date. I updated choco.

**Comment by ferventcoder** [comment]
Unrelated: You are seeing the message to use choco upgrade instead of choco update, right? 👍

**Comment by ferventcoder** [comment]
It's an interesting issue for sure. I'm not yet even sure what is causing it for you.

**Comment by ferventcoder** [comment]
It never makes it to running powershell.

**Comment by imkebe** [comment]
Strangely it started to work... I think it was related with 0.9.10.2  version. I updated to 0.9.10.3 but probably i didn't restarted command line ant it was using old environment variables. choco was newer binary and could be run since it was already installed

**Comment by ferventcoder** [comment]
If we find this comes back, we will definitely want to fix that.
