### ISSUE TITLE
unable to call packages from network share which is added as source

### ISSUE THREAD

**Issue by sschlabs** [chocolatey/choco#851]
I'm having trouble with adding a network share as source to chocolatey. After having added it with "choco source add -n networkshare -s \\Remote-IP\path\to" i run into the error "The package was not found with the source(s) listed". Do i have to consider something? With a local path it works like a charm. Thanks in advance!

**Comment by ferventcoder** [comment]
What version of Chocolatey?

What user does Chocolatey run under where you see this issue?

**Comment by sschlabs** [comment]
Hi ferventcoder, 

i'm using the very latest version 0.9.10.3 from Chocolatey. I'm running it with admin privileges as an local administrator account in order to install software on brand new machines. 

Cheers,
Sebastian

**Comment by ferventcoder** [comment]
And that Local Administrator account, it would not happen to be `SYSTEM` would it?

**Comment by sschlabs** [comment]
No. It is just the default account requested to be created during the windows installation.

**Comment by ferventcoder** [comment]
You have verified it is not a permissions issue?

**Comment by sschlabs** [comment]
The access for the share through windows explorer is granted without any authentication because the permissions on the target folder is set to everyone full control.

**Comment by ferventcoder** [comment]
From what I understand about UNC shares is that you need to check both sets of permissions. Can you get to the location with `dir \\Remote-IP\path\to` from the account?

**Comment by sschlabs** [comment]
Somehow it's working now :+1: I just adjusted the required package. However i want to thank you very much for your effort and your wonderful product :) Have a great day!

**Comment by ferventcoder** [comment]
No problem. Let me know if you run across this again. Thanks!
