### ISSUE TITLE
Larger default log file size and retention

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#852]
We are starting to use Chocolatey for code deployment due to the limitations of NuGet (mainly to call a script from inside the package when processing OUTSIDE of Visual Studio).

This allows our code deploy packages to be called where we have no orchestration to trigger the install script (e.g. our developer workstations do not have Chef nor octopus installed).

I am making sure each and every file copy gets logged so that root cause is easy if a code deploy in production goes wrong.

In one of my packages there are so many files that this overflows all 11 chocolatey log files and I can't see the beginning of the log.

I understand that this is not necessarily a use case that chocolatey was designed around - but Chocolatey is very useful for code deploys for us and I think others may find the same.

It would be helpful if the size limit on each log file were higher by default.  1 MB is a pretty small limit.

If the default size of each could be, say, 100 MB, then I may not need any additional configuration controls.  I think this would be the preferred option as I would not have to reconfigure the default chocolatey install.

If the size must remain 1MB, it would be helpful to have configuration control over how many old versions are kept.

**Comment by ferventcoder** [comment]
Let's go with larger defaults of 10MB and allow it to be configurable on config settings. Sound good?

**Comment by ferventcoder** [comment]
10MB default and 50 files kept around

**Comment by DarwinJS** [comment]
Sure - if you're going to bother exposing a config setting, maybe also expose both values?

Some regulated environments *might* have need to keep a ridiculous amount of history around - not my scenario - what you have proposed it perfectly fine for my current scenario.

**Comment by ferventcoder** [comment]
> Sure - if you're going to bother exposing a config setting, maybe also expose both values?

That was the plan. That's why I used the term "setting**s**" ;)

**Comment by ferventcoder** [comment]
Just typing too fast and didn't get the number of files into the first reponse.

**Comment by DarwinJS** [comment]
Cool - all sounds good.

**Comment by ferventcoder** [comment]
@DarwinJS I pushed the pulling values from configuration to #890. I didn't want to lose track of the latter part but it is a bit more involved than I will be able to tackle in the timeframe for 0.9.10.4 release.

**Comment by DarwinJS** [comment]
Thanks!
