### ISSUE TITLE
Illegal characters in path

### ISSUE THREAD

**Issue by aronovgj** [chocolatey/choco#857]
When using autouninstaller I get this error with chocolatey 0.9.10.3

https://gist.github.com/aronovgj/2632b60b24f30c5736076523c3f69e2b

**Comment by ferventcoder** [comment]
Not AutoUninstaller in this case. It's in the PowerShell helpers.

**Comment by ferventcoder** [comment]
In this case it looks like it did not remove the double quotes surrounding the path.

**Comment by ferventcoder** [comment]
Likely this is related to a null character that is not showing up.
