### ISSUE TITLE
Install / Upgrade clarification

### ISSUE THREAD

**Issue by CADbloke** [chocolatey/choco#86]
Greetings.

Choco is awse. Yes, I RTFMed but the wiki wasn't shiny crystal-clear on this point for me...

Question: I have an installation script which has many `choco install` lines, can/should I continue to use the same script throughout the life of the machine(s) I set up with it to keep the packages up to date or do I need a different script that runs `choco upgrade` on the same packages? 

ie. If an already-installed package is updated, does running `choco install` always install the latest version of the app in place of the old version or could I end up with a plethora of side-by-side versions?

cheers
Ewen

**Comment by ferventcoder** [comment]
If you are using choco, install will do nothing if you have the package already installed. Install with `-force` will only reinstall the exact same version.

**Comment by ferventcoder** [comment]
This is a change in behavior from the prior PowerShell chocolatey client (0.9.8.32 and below)

**Comment by ferventcoder** [comment]
You can continue to use the same script if you add one line to the very bottom

```
choco upgrade all
```

**Comment by ferventcoder** [comment]
Also worth noting, choco 0.9.9+ requires conformation -y and no longer has folders worth version numbers on the end.

**Comment by ferventcoder** [comment]
If you've been in the release notes we try to clarify.

**Comment by CADbloke** [comment]
Thanks for the clarifications, @ferventcoder. 

I saw  the [Release Notes](https://github.com/chocolatey/choco/wiki/ReleaseNotes) regarding the `-y` switch. To set the global confirm, is the syntax `choco feature enable allowInsecureConfirmation` , somewhere near the top of the file? ... (even if it is a set once thing).

> If you are using choco, install will do nothing if you have the package already installed.

...this is implied in the wiki / Release Notes but I didn't see it stated explicitly (although I often read like a LUser so maybe PEBKAC). I'm new to Chocolatey (better late than never!) so I'm not familiar with how it used to work, as such.

**Comment by dtgm** [comment]
@CADbloke The correct syntax is:

choco feature enable -n=allowInsecureConfirmation

This toggles the line in C:\ProgramData\chocolatey\config\chocolatey.config
<feature name="allowInsecureConfirmation" enabled="false" setExplicitly="false" />
to
<feature name="allowInsecureConfirmation" enabled="true" setExplicitly="true" />

Alternatively, you may want to create your own function to bypass the security without turning it off:
PS C:\> function choc { choco $args -y }
Then you can run choco/cinst/cuninst with the normal confirmation request, or without confirmation with
PS C:\> choc install fooapp

**Comment by ferventcoder** [comment]
@dtgm and @CADbloke note I just switched the terminology on this to `allowGlobalConfirmation`. This will be reflected in the next RC and will need to be set again.

**Comment by ferventcoder** [comment]
@CADbloke 

> I saw the Release Notes regarding the -y switch. To set the global confirm, is the syntax choco feature enable allowInsecureConfirmation , somewhere near the top of the file? ... (even if it is a set once thing).

There is a link directly to it at the end of the note with the -y switch. I did just make it bolder so hopefully it sticks out more for you.

**Comment by CADbloke** [comment]
> I did just make it bolder so hopefully it sticks out more for you.

Yes but I was (quite unclearly, I must say because `Luser == true;`) asking for the correct Syntax which is explained at https://github.com/chocolatey/choco/wiki/CommandsFeature (although the examples need re-formatting).

If you need a dunce to foolproof your Wiki, looks like I'm the fool. :/

Sorry & Thanks @ferventcoder & also thanks @dgtm

**Comment by ferventcoder** [comment]
Whoops. Reformatted examples. Thanks for pointing that out.

On Wednesday, February 18, 2015, Ewen <notifications@github.com> wrote:

> I did just make it bolder so hopefully it sticks out more for you.
>
> Yes but I was (quite unclearly, I must say because Luser == true;) asking
> for the correct Syntax which is explained at
> https://github.com/chocolatey/choco/wiki/CommandsFeature (although the
> examples need re-formatting).
>
> If you need a dunce to foolproof your Wiki, looks like I'm the fool. :/
>
> Sorry & Thanks @ferventcoder <https://github.com/ferventcoder> & also
> thanks @dgtm <https://github.com/dgtm>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/86#issuecomment-74982026>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
Is this still valid? I'm just coming back to this one.

**Comment by CADbloke** [comment]
All looks great to me. Closing. Thanks again for your help and attention.
