### ISSUE TITLE
Package Backup Improvements

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#87]
- [x] Do not fail when backup fails, detect errors
- [x] Move the directory, then copy back. This will allow running applications/services to continue functioning during upgrade.
- [x] When backing up, split into phases and if Move fails, attempt to copy those files back and fail a second time.
- [x] FileSystem move_directory should use built-in Directory.Move and fail back to the old method.
- [x] Shorten rollback suffix to handle longer path issues

Original error reported:
```
"C:\ProgramData\chocolatey\lib\nodejs.commandline.0.10.36\tools\node_modules\bower\node_module
s\insight\node_modules\inquirer\node_modules\cli-color\node_modules\memoizee\node_modules\es6-weak-map\node_modules\es
6-iterator\valid-iterable.js" to "C:\ProgramData\chocolatey\lib\nodejs.commandline.0.10.36._.previous\tools\node_modul
es\bower\node_modules\insight\node_modules\inquirer\node_modules\cli-color\node_modules\memoizee\node_modules\es6-weak
-map\node_modules\es6-iterator\valid-iterable.js".
```

results in 
```
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, a
nd the directory name must be less than 248 characters.
Exiting with 1
```

Reference: https://gist.github.com/rpavlik/3f399974d9e1f9455f1e

**Comment by ferventcoder** [comment]
@rpavlik Did I capture this sufficiently?

**Comment by rpavlik** [comment]
Wow, that was quick, I was just doing the same. Yeah, I think that pretty much handles it, though I'd like the ability to choose if a backup failure is an upgrade failure. For instance, I really don't care if I have a backup of the globally-installed node modules, I can install them again anyway.

`<backseatcoder>`Is there a reason the files are being copied individually by name vs. moving the tree?`</backseatcoder>`

**Comment by ferventcoder** [comment]
@rpavlik for individual versus moving the tree, Probably a limit of C# or something I don't know about. If the question is why copy over move, we need a copy of the files b/c in place upgrade and there may be existing files that the user has created that should continue to exist.

**Comment by ferventcoder** [comment]
However, I did find Directory.Move so using that definitely for the move phase. :+1:
