### ISSUE TITLE
Deprecated links inserted in .nuspec files created by `choco new ...`

### ISSUE THREAD

**Issue by KurtPfeifle** [chocolatey/choco#870]
Running `choco new dummy -a --version 1.1.1_1 maintainername="'myname'"  installertype=exe url="'http://example.com/downloads/dummy.exe'"` creates the *`dummy.nuspec`* and *`Readme.md`* files in the newly-created local *`dummy`* directory.

So far, so good.

However, the first line of `dummy.nuspec` contains a hint to  
* https://github.com/chocolatey/chocolatey/wiki/CreatePackages ,
* which (when visited) redirects to https://github.com/chocolatey/chocolatey ,
*  which states *"THIS REPOSITORY IS DEPRECATED"* and tells to go to https://github.com/chocolatey/choco instead...

**Comment by ferventcoder** [comment]
Thanks for catching that. Definitely should fix that.
