### ISSUE TITLE
NuGet XSD Validation Failure On Install

### ISSUE THREAD

**Issue by normanhh3** [chocolatey/choco#874]
### What You Are Seeing?

```choco install git``` running as Administrator is failing due to a NuGet XSD validation error.

### What is Expected?

That the git package would be installed correctly.

### How Did You Get This To Happen? (Steps to Reproduce)

```choco install git``` as Administrator on Windows 7

### Output Log
Output available [in the gist](https://gist.github.com/normanhh3/645c4d0b1b0593c0ceb4c3af5e9a2a83)

I believe this to be an issue with Chocolatey simply because of the use of an internal path to NuGet.  I am open to being wrong however.

It appears that the XSD changes in NuGet's nuspec definition are hitting [others as well](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/59).

**Comment by ferventcoder** [comment]
What version of Chocolatey are you running?

**Comment by ferventcoder** [comment]
Oh wait - 0.9.8.23 from [November 11, 2013](https://chocolatey.org/packages/chocolatey#versionhistory). That is almost three years old. It's probably a safe assumption to say that version is no longer supported. Please upgrade.

**Comment by ferventcoder** [comment]
You may also want to have a read through https://github.com/chocolatey/choco/blob/master/CHANGELOG.md to see all of the things that have changed over the last almost three years.

**Comment by normanhh3** [comment]
I specifically did ```choco upgrade -self``` before this and it seemed to work correctly, sorry for not checking the releases against the version I had. :-/

**Comment by ferventcoder** [comment]
Not sure `upgrade -self` would have done anything at all in that older version. We don't even have a `-self` command for upgrade. `choco upgrade chocolatey`, although in your version I would suggest `choco update chocolatey` or for all `cup chocolatey`.
