### ISSUE TITLE
Progress of download does not clear the whole output line

### ISSUE THREAD

**Issue by batzen** [chocolatey/choco#875]
### What You Are Seeing?
Progress of download does not clear the whole output line. This results in artifacts being displayed if the reported progress gets shorter. This happens, for example, when download progress switches from formatted MB to formatted GB. 

### What is Expected?
Progress being displayed without artifacts.

### How Did You Get This To Happen? (Steps to Reproduce)
Upgrading or installing a package which downloads files larger or equal to 1 GB.

### Output Log
Log won't help much here. Attaching screenshot instead.
The last part " 4)" in the screenshot is the artifact i am talking about.
![screenshot 5](https://cloud.githubusercontent.com/assets/1971030/17140478/e559aeca-5348-11e6-9dcc-dc4fed373205.png)
On 100% this changes to "Progress: 100% - Saving 6.77 GB of 6.81 GB (7272877423/7309161064) )" where the artifact is just " )".

**Comment by ferventcoder** [comment]
I wonder if the fixes for #872 (in PR #873) fix this or not.

**Comment by ferventcoder** [comment]
It doesn't appear so.

**Comment by ferventcoder** [comment]
Fixed in 0.9.10.4. Thanks @bill-long!
