### ISSUE TITLE
Installing from packages.config should support windowsfeatures (and other metapackages)

### ISSUE THREAD

**Issue by chrispellett** [chocolatey/choco#877]
_(I did some digging for an issue or mention of this behaviour and could not find anything; my apologies if something does exist. Many thanks for your help)_
### What You Are Seeing?

I have a packages.config with the following entry:
`<package id="IIS-WebServerRole" source="windowsfeatures" />`
and it fails to install with the error: "**The package was not found with the source(s) listed**"
### What is Expected?

Anything that can be installed via "choco install" (which the above can) should be supported in the packages.config. E.g. `choco install IIS-WebServerRole -s windowsfeatures` succeeds on the same machine.
### How Did You Get This To Happen? (Steps to Reproduce)
- Create a packages.config with the above entry (I also had a "notepadplusplus" entry but I don't think that changes the result).
- Run choco install packages.config
### Output Log

https://gist.github.com/chrispellett/af88b0b4eb1969e783e9a87c300d6b9e

**Comment by ferventcoder** [comment]
This looks like either a bug or an enhancement. I think we want to support doing this but I don't think it is supported currently. Let's call it an enhancement.

**Comment by jberezanski** [comment]
#40 has "packages.config can work with alternate sources" ticked off in its description, so perhaps this is a regression after all?

**Comment by ferventcoder** [comment]
Sounds like regression.

**Comment by dragon788** [comment]
@ferventcoder is there a reason you guys are using the DISM module names instead of PowerShell and the ServerManager module to install these?

Perhaps the PowerShell/ServerManager is only a newer feature in 2012 R2 or IIS 8.5, but I found this page pretty helpful for figuring out the dependencies of the different pieces of IIS. http://www.iis.net/learn/install/installing-iis-85/installing-iis-85-on-windows-server-2012-r2#ModulesinIIS85 Scrolling back up a little from this shows the DISM and pure PowerShell CLI install options.

**Comment by ferventcoder** [comment]
@dragon788 Typically because we support PowerShell v2+ / Windows 2003+.

**Comment by jberezanski** [comment]
Besides, the ServerManager module is not present on client editions of Windows.

**Comment by makaanneo** [comment]
I have the same issue

**Comment by ajklotz** [comment]
Would like to see progress on this. I want to make a packages.config that sets up IIS in preparation of a chocolatey package that installs a website with web deploy.

**Comment by bcurran3** [comment]
Klude or not, isn't it just as easy to create a package with IIS-WebServerRole -s windowsfeatures in it and then just put that package in the packages.conf?

**Comment by ramlongcat** [comment]
why is this closed ? problems still exists

**Comment by AdmiringWorm** [comment]
@ramlongcat it isn't closed, it is still open

**Comment by ramlongcat** [comment]
oh my bad !

**Comment by junalmeida** [comment]
As a workaround, you can have a separate `.config` file with only the special source `windowsfeatures` and call `choco install --yes "$PSScriptRoot\windowsfeatures.config" -s windowsfeatures`

**Comment by peterbarendse** [comment]
Any progress on this? We are bumping into the exact same issue and it's 2020 by now. A fix would be greatly appreciated.

**Comment by ferventcoder** [comment]
Hi Peter, 
If you don't see any code linked up, then assume little to no progress. As it is on the backlog and not in Triage, it means we plan to do it. It all comes down to a matter of when. Seems like there is a workaround that can be accomplished right now though. And b/c you can simply write powershell scripts to point to those sources, the are ways to handle this outside of a packages.config.

**Comment by anouarprima** [comment]
Workarrond with PS :
[xml]$PackagesFile = Get-Content /packages.config; foreach($package in $PackagesFile.Packages.Package){choco install -y $package.id --version $package.version --source windowsfeatures}

**Comment by StefanoFrazzetto** [comment]
Hi there! It might be worth adding this to the [documentation](https://docs.chocolatey.org/en-us/choco/commands/search#windows-features) until the bug is resolved, e.g.
> Currently Chocolatey doesn't support _windowsfeatures_ as a source when specified in `packages.conf`. As a workoround, you can create a separate `packages.conf` file and directly specify the sources in the `choco install` command. See https://github.com/chocolatey/choco/issues/877 for more information.

**Comment by pauby** [comment]
@StefanoFrazzetto Can you raise an issue and PR for that over at the [docs repository](https://github.com/chocolatey/docs/)?

**Comment by StefanoFrazzetto** [comment]
Hi @pauby, I just opened an issue here https://github.com/chocolatey/docs/issues/184. I'll try to get a PR in as soon as I have a moment.
