### ISSUE TITLE
Packages.config should include all options (including ignorechecksums)

### ISSUE THREAD

**Issue by cori** [chocolatey/choco#886]
### What You Are Seeing?

cinst on command-line using a .config file disregards ignorechecksum for specific packages.
### What is Expected?

an entry in a .config file that includes `ignorechecksums="true" or another of the aliases from https://github.com/chocolatey/choco/wiki/CommandsInstall#options-and-switches should honor the ignorechecksums directive and allow, for that specific package,an installer that fails the checksums verification to be installed.
### How Did You Get This To Happen? (Steps to Reproduce)

ran `cinst rt.config -y` using the attached rt.config.txt file.
[rt.config.txt](https://github.com/chocolatey/choco/files/394245/rt.config.txt)
### Output Log

chocolatey.log: https://gist.github.com/cori/01ff60e1638b75f38a25cbe41e7a0a16
choco.summary.log: https://gist.github.com/cori/b51791c5e22e19180d1e31e0eee717f1

**Comment by cori** [comment]
On a side note, running `cinst rt.config -y --ignore-checksums` with a .config file with checksum-failing packages *does* enable them to be installed,but in a scripted install environment that's unsatisfactory - I need to be able to control when to ignore checksums on a package-by-package basis so that I'm only ignoring them in cases that I've investigated, not for all the packages I'm installing arbitrarily,which would be pretty insecure.

**Comment by cori** [comment]
I guess I wouldn't have thought of this as an enhancement, but maybe the problem is that https://github.com/chocolatey/choco/wiki/CommandsInstall#packagesconfigdoesn't call out which options work in a .config file and which ones don't - without some clarity there it seems like a sensible assumption that all of the options listed in the following section should be expected to work as advertised.

Obviously, though, you need to manage your workload as you see fit. Thanks for the swift attention.

**Comment by ferventcoder** [comment]
@cori As I mentioned over in the disqus notes, I think this should include all options that can be passed.

**Comment by ferventcoder** [comment]
> I guess I wouldn't have thought of this as an enhancement

@cori I could go either way. Unexpected behavior could make it a bug, but as we did not add that functionality yet I think of it as an enhancement. Forgotten functionality could make it a bug. Like I said, I could go either way. 👍

**Comment by cori** [comment]
don't see a note on the disqus thread, but probably more important to get it here!

**Comment by ferventcoder** [comment]
yes, more important to get it here. Perhaps it wasn't on disqus. Where did we talk about this already?

**Comment by cori** [comment]
Found it - you replied to a stackoverflow comment: http://stackoverflow.com/questions/34106680/how-to-use-custom-parameters-in-chocolatey-config-file/34111537?noredirect=1#comment64776855_34111537

**Comment by ferventcoder** [comment]
Would be nice to include options that come in from business editions as well here.

**Comment by lackovic** [comment]
Is there a way to ignore the checksum in the config file?

I checked [the documentation](https://chocolatey.org/docs/commands-install) and the [StackOverflow thread](https://stackoverflow.com/questions/34106680/how-to-use-custom-parameters-in-chocolatey-config-file/34111537) but didn't find an answer to this.

I did a few experiments using `packageParameters`:

- `packageParameters="IgnoreChecksum"`
- `packageParameters="/IgnoreChecksum"`
- `packageParameters="--ignorechecksum"`

also tried with:

- `ignoreChecksum="true"`

but none of them worked.

<packages>
    <package id="bulkrenameutility"  />
</packages>

**Comment by gep13** [comment]
@TheCakeIsNaOH would you be able to break this out into a new issue:

> Would be nice to include options that come in from business editions as well here.

This doesn't belong as part of this issue, but we should likely do this at some point.

**Comment by TheCakeIsNaOH** [comment]
@gep13 added an issue here: https://github.com/chocolatey/chocolatey-licensed-issues/issues/317

**Comment by TheCakeIsNaOH** [comment]
@AdmiringWorm this still needs documentation. See https://github.com/chocolatey/docs/issues/403
