### ISSUE TITLE
cls

### ISSUE THREAD

**Issue by ozmartian** [chocolatey/choco#887]
### Output Log

GIST LINK - Please create a gist and link to that gist here

OR

~~~sh
PLACE LOG CONTENT HERE
~~~

**Comment by ferventcoder** [comment]
@ozmartian Was this an accident?

**Comment by ferventcoder** [comment]
Feel free to comment again if you want.

**Comment by ozmartian** [comment]
a little late to the party here  :-) and a big wtf? must have been a typo that somehow evolved into valid syntax.. apologies for wasting your time

**Comment by ferventcoder** [comment]
@ozmartian the above is what happens when you create a new issue without typing anything (that output is the github issue template).
