### ISSUE TITLE
Remove the `cpack` command alias

### ISSUE THREAD

**Issue by rpavlik** [chocolatey/choco#89]
`cpack` is the command used by CMake to invoke its package generator. Not sure the polite way to resolve this.

And for reference, it also uses `cmake` and `ctest`.

(And apparently Microsoft is using CMake to build their open-source .NET on other platforms now...)

**Comment by ferventcoder** [comment]
Aware of this. One reason we are moving away from the shorter ones (at least cpush and cpack).

**Comment by dothebart** [comment]
Chocolatey should either prefix its binary or setup the path environment in a way that it doesn't disturb the packages it installed.

**Comment by ferventcoder** [comment]
@dothebart Chocolatey itself does prefix the binary shortcuts with `c`. So it already does this. This is the only known case where that presents an issue.

**Comment by solvingJ** [comment]
Just tried to use Cpack for Cmake on windows, chocolatey getting in the way.  What's the status of this?  Looks like a PR was merged 2 years ago?

**Comment by ferventcoder** [comment]
@solvingJ Do you have a link to a PR?

**Comment by ferventcoder** [comment]
@solvingJ If you are talking about https://github.com/chocolatey/choco/commit/e9dcb0cc12d49791511e8456b6e94438b81c369c,

deprecation != removal - deprecations keep functionality but announce it is being removed in the future. HTH

**Comment by dothebart** [comment]
Maybe once the user installs cmake it could be clear, that he doesn't want a cpack alias and it could be removed then?

**Comment by ferventcoder** [comment]
If you install CMake through Chocolatey using the portable version, it will overwrite cpack. However any actions to install packages or outside of Chocolatey's control, it becomes hard to know when those kind of occurrences happen. It's probably best to ensure there is documentation in troubleshooting about this, but over that, it's unknown what we can do until `cpack` is removed. We must follow a transition (deprecation) in removing things.

**Comment by dothebart** [comment]
one sure thing is, that you usually would call the cmake - cpack with `-G <packageformat>` - maybe even inside of scrips. Unless you handle `-G` as a valid parameter in chocolateys cpack its a safe bet to search for cpack in the rest of the given paths and call that with $@ - or error out with a clear error message to the user that this is _not_ cmake cpack which he probably desired to invoke, and how he can remove the unwanted cpack with `del ...cpack.exe`

**Comment by ferventcoder** [comment]
@dothebart you mean pass this on to a different cpack based on arguments. That is actually a really good idea!

**Comment by ferventcoder** [comment]
See https://github.com/chocolatey/choco/issues/1317

**Comment by native-api** [comment]
Suggesting more options:
* not have Chocolatey's executables except `choco` on `PATH`
* use dashed prefixes and/or subcommands like Apt: `choco-pack` or `choco pack` (the latter could be used in conjunction with the previous one)

**Comment by solvingj** [comment]
@ferventcoder an easy way to move forward on this (by that I mean, help all the people it annoys) is to implement one or more environment variables which toggle the behavior. 

`CHOCO_ENABLE_ALIASES=True`

or if you want to get more granular: 

`CHOCO_ENABLE_ALIAS_CPACK=True`

If the value is `False`, you can choose to punt the command back to the shell so that CMake's cpack could pick it up, and if `True` (the default), you can actually handle it in chocolatey the way you do today.  

You could also make it an install-time variable which prevents the aliases from ever being installed. As a user, I do not have a preference at this time.

**Comment by native-api** [comment]
Per #431 and https://github.com/chocolatey/choco/blob/master/docs/generated/CommandsReference.md#scripting--integration---best-practices--style-guide, the aliases are deprecated since 2015. So this can be used as an opportunity to remove them altogether.

**Comment by ferventcoder** [comment]
@native-api per my previous comments - deprecated is not removed. It's something you have to plan for and give folks plenty of time. Deprecated is a warning in the SHIM stating it is going to be removed as of version x - that hasn't been put in yet. So we won't be removing the shims yet. Note the removal is planned for v1 as per the milestone here.

**Comment by bowie7070** [comment]
I need to have cpack resolve to the cpack that comes with CMake and I don't have a lot of control over path and things like that. I do however have the power to delete cpack from the chocolatey installation. Will this cause subtle problems? Or is this a reasonable resolution given that I only found out that chocolatey has a cpack command when I wanted to call the CMake one?

**Comment by vexx32** [comment]
From memory, if you remove `cpack` from the chocolatey installation there should be no issues with using regular `choco` commands; `cpack` essentially more or less just calls `choco pack` transparently. Just remember that `cpack` will not be using choco from that point forward.

Which makes me think -- maybe supplying the aliases/shims should be something folks can opt out of in the install.ps1 script for Chocolatey?

**Comment by droidmonkey** [comment]
Just installed a fresh chocolately install and ran into this issue, deprecated since 2015 yet still installed in 2021. This is a major breaker when using Visual Studio tools, vcpkg, and a build pipeline. What's up guys?

**Comment by IohannRabeson** [comment]
Is there any way to be able to run cpack.exe without uninstalling chocolatey?
I was about to ask what's up but since its there since 2015 I guess

**Comment by TheCakeIsNaOH** [comment]
> Where this cpack alias is defined?

Run `where.exe cpack` to see all of the `cpack` commands on your path.

The Chocolatey cpack alias should be in `$env:ChocolateyInstall\bin\cpack.exe`

**Comment by dothebart** [comment]
Thanks for getting this finally resolved.

**Comment by gep13** [comment]
@dothebart while this has been merged, it won't be live until the next release of Chocolatey, but it _will_ go out in the next release 😄
