### ISSUE TITLE
dism /all is never running -- no dependencies get installed.

### ISSUE THREAD

**Issue by jrkd** [chocolatey/choco#897]
Running choco on windows 10.0.x with source windowsfeatures, there's a problem with installing dependencies to a particular feature. 

Looks like the issue is in /src/chocolatey/infrastructure.app/services/WindowsFeatureService.cs Line 230, where the condition to add the all argument requires the minor version of windows to always be greater than 2, no matter the major version. 

Will add a pull request with a suggested fix to this issue.

**Comment by ferventcoder** [comment]
Merged into stable at https://github.com/chocolatey/choco/commit/e428c85d0537cfb618c534eacf1aaaca174a010b
