### ISSUE TITLE
Configurable "Additional Logs To Grab" for Verification Testing on Chocolatey.org

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#899]
It would be great to be able to register additional log files for the automated testing process to turn into gists.

This would allow much better analysis without requiring test instances be kept for review and later garbage collected.

Maybe optional .nuspec items (that are ignored by the processing that imports .nuspec data into chocolatey.org's site)?

Would be good if the testing automation checked if the file existed and noted it's non-existence in the test log file so that packagers can tell when they don't have the pathing correct.

**Comment by ferventcoder** [comment]
Wrong repo - https://github.com/chocolatey/package-verifier/issues please.
