### ISSUE TITLE
When installing with *.nupkg, need to get package name from package, not file name

### ISSUE THREAD

**Issue by bdukes** [chocolatey/choco#90]
When issuing a command like `choco install hg.3.3.nupkg`, choco tries to find a package named "hg.3.3" (based on the passed in file name), rather the reading the manifest of the nupkg and finding the actual package name to install.  See https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/services/NugetService.cs#L233

**Comment by zl4bv** [comment]
Is there an alternative method of installing *.nupkg files from the local file system?

**Comment by ferventcoder** [comment]
@zl4bv Yes, and that is why the priority is low. The method detailed in the wiki that has been the way to do it since day one `-source "%cd%"` or `-source '$pwd'` (or point to the folder of the package if it is not the current directory).

**Comment by ferventcoder** [comment]
You can also point to the nuspec and it will work properly.

**Comment by ferventcoder** [comment]
This is a bug on a new feature of choco, and it has a workaround, that's why the priority is low.

**Comment by zl4bv** [comment]
> The method detailed in the wiki that has been the way to do it since day one `-source "%cd%"` or `-source '$pwd'` (or point to the folder of the package if it is not the current directory).

Thanks - that's the way I've been installing packages. Wasn't sure if (ignoring the bug) Chocolatey behaves any differently by installing it this way.

**Comment by ferventcoder** [comment]
This has been implemented in https://github.com/chocolatey/choco/commit/4e392135fd645a63ac929d14ca59f13fcd1e11dd and will be released with 0.9.9.7. Thanks!
