### ISSUE TITLE
Support exit codes bigger than Int32.MaxValue

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/choco#900]
### What You Are Seeing?
ERROR: Cannot bind parameter 'ValidExitCodes'. Cannot convert value "2147781575" to type "System.Int32". Error: "Value was either too large or too small for an Int32."
The install of visualstudio2015enterprise was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\VisualStudio2015Enterprise\Tools\ChocolateyInstall.ps1'.
See log for details.

### What is Expected?
Chocolatey should be able to handle error codes > Int32.MaxValue

### How Did You Get This To Happen? (Steps to Reproduce)
Install [Visual Studio 2015 Enterprise](https://chocolatey.org/packages/VisualStudio2015Enterprise) while a reboot is pending.

Possible exit code from Visual Studio installer are defined [here](https://github.com/KennethB/Chocolatey-Packages/blob/master/VisualStudio2015Enterprise/Tools/VSModules.psm1#L153).

**Comment by pascalberger** [comment]
The same package seems to work though on other machines. So seems to be related to the system configuration.

**Comment by ferventcoder** [comment]
@pascalberger the package works on machines that maybe don't use the pro version?

**Comment by pascalberger** [comment]
Probably needs more investigation. On the machine it fails there is Pro installed. It works on two other machines without Pro. But there are also different OS (Win 10 where it fails, Win Server 2012 R2 where it works).

**Comment by ferventcoder** [comment]
It's likely Pro, there is a specific int. I'm changing it to long now.

**Comment by ferventcoder** [comment]
This will be out in 1.5.1 of the extension in less than an hour.
