### ISSUE TITLE
RefreshEnv / Update-SessionEnvironment changes current user to SYSTEM

### ISSUE THREAD

**Issue by gunnarvelle** [chocolatey/choco#902]
### What You Are Seeing?

If I run RefreshEnv.cmd in a ConEmu cmd-shell the current user is changed to SYSTEM in the environment variable USERNAME. This leads to the PATH to be broken.
### What is Expected?

I'd expect the USERNAME to remain unchanged.
### How Did You Get This To Happen? (Steps to Reproduce)

Ran RefreshEnv, both in regular cmd and in elevated cmd.
### Output Log

My prompt shows the current user, so thats why I noticed.

gv@GVPC C:\Users\gv
> RefreshEnv.cmd
Reading environment variables from registry. Please wait... Done.

SYSTEM@GVPC C:\Users\gv
>

**Comment by ferventcoder** [comment]
What version of Chocolatey here?

**Comment by ferventcoder** [comment]
Actually, I do think this is likely an issue. I know that it is one thing we've dealt with in the c# code that does the same, and we need to add those changes to both the powershell and batch versions

**Comment by gunnarvelle** [comment]
Choco versjon is 0.9.10.3.

**Comment by rmlephiew** [comment]
I'd like to work on this one

**Comment by ferventcoder** [comment]
@rmlephiew go for it - read over the entire CONTRIBUTING doc first and ensure you can sign the CLA. We get somewhat picky about git commit message formatting, but that is covered in the doc. So as long as you follow the format you should be good to go.

**Comment by splatteredbits** [comment]
I'm having a similar issue with the Chocolatey installer. If I install chocolatey, the USERNAME environment variable gets changed to SYSTEM. Is this the same underlying cause? Or should I enter another issue?

Steps to Reproduce:

1. Boot a computer that doesn't have Chocolatey installed.
2. Open a PowerShell prompt
3. Inspect USERNAME environment varaible: `> $env:USERNAME`
4. Install chocolatey: `Invoke-WebRequest -Uri 'https://chocolatey.org/install.ps1' -UseBasicParsing | Invoke-Expression`
5. Inspect USERNAME environment variable and note that it is now SYSTEM: `> $env:USERNAME`.

**Comment by splatteredbits** [comment]
Update: turns out, it isn't the Chocolatey installer. I'm running `Update-SessionEnvironment` after the install. So, I am having this same problem.

**Comment by ferventcoder** [comment]
Recent conversation at https://gitter.im/chocolatey/choco?at=5893a086fba5bfea06c00636

**Comment by ferventcoder** [comment]
Completed for 0.10.4.
