### ISSUE TITLE
Local Package Dependency

### ISSUE THREAD

**Issue by priceflex** [chocolatey/choco#904]
Hello,

I have a question regarding dependencies.  If I have a local package I want to include as a dependency how would I point the location of the package? I looked at the Nuget package spec and found that only ID and Version are the only parameters I can pass in. Is there a way to include a location for example: 

~~~xml
<dependency id="superawesomelocalpackage" version="1.0" location="c:\local_choco_packages\superawesomelocalpackage">
~~~

Let me know. Thanks in advanced.

Steve

**Comment by ferventcoder** [comment]
If you can, questions are best asked in Gitter or in the Google Group forum. See https://github.com/chocolatey/choco/blob/master/README.md#submitting-issues for details.

**Comment by ferventcoder** [comment]
@priceflex dependencies are based on runtime sources. Unfortunately there is not a way to specify a local dependency at build time.

So if you wanted to use a local package, you would need to run `choco install -s "'.;source2;source3'"

The other thing you can do is 

`choco source add -n localsource -s c:\local_choco_packages`

**Comment by ferventcoder** [comment]
I won't close this yet, let me know if this answers your question.

**Comment by priceflex** [comment]
Thank you for your answer. I will now post in the Google Group from now on.
