### ISSUE TITLE
choco install relativepath/to/some.nuspec fails

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#906]
For installs directly against a .nuspec, it appears that the .nupkg is runtime compiled into the working folder, but then when the call to 'install' is passed internally in choco, the source folder is given as the same folder as the .nuspec.

So if do this:
c:\somefolder> cinst -y subfolder\my.nuspec

The .nupkg ends up in "somefolder" but choco errors out that it can't find the package in c:\somefolder\subfolder.

choco version 0.10.0.

**Comment by woodburysoft** [comment]
I'm happy to take a look at this if nobody objects

**Comment by ferventcoder** [comment]
Fixed for 0.10.4
