### ISSUE TITLE
choco install <nupkg file name> - continue to process even if file extension is not .nupkg

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#907]
Scenario:
Octopus uses it's tentacle communications to move .nupkg files into a client cache.  We like this because we can open one port to production machines from CI/CD environment and _nothing else_ (least privilege).

Octopus randomizes the names by adding unique characters after the extension like this "Somepackage.nupkgahjadfhlasd"

I believe it does this to offset the problem of the same package version having different content - an artifact of using CI to control version numbers.

Sometimes these are chocolatey packages and I want to use choco to run them.  However, I have to write crafty code and deobfuscate the file name back to a .nupkg.  Aside from extra steps it takes extra time and disk space.

Would be very helpful if I give choco a file name that does not end in .nuspec, that it assumes it is a .nupkg and tries to run it as such.  If it is not a .nupkg - then the error could say something like "since that file extension is .nupkg;akdjfa8asd87adf, please make sure that is actually a nupkg internally"

**Comment by ferventcoder** [comment]
This is an interesting scenario. I'd almost consider this an edge case. The issue here is that we need NuGet.Core to get more familiar with this scenario.

**Comment by DarwinJS** [comment]
Definitely an "edge case" - but an important one having to do with choco's roadmap toward clean integration with CI and CD.  If chocolatey is ahead of the game in integrating with popular products in CI/CD it will be positioned for rapid adoption when people start playing with it there.  Eventually it might be nice to have guide pages for products like Octopus that explain the "obscure" features of choco and how to implement them as "steps" in various CI/CD tools.

**Comment by ferventcoder** [comment]
What is meant by "obscure"? Things that are not as well known?

**Comment by DarwinJS** [comment]
Obscure is not meant derogatorily.  If you added a feature that chocolatey could install a .nupkg whose filename did not end in .nupkg for the purposes of octopus integration - it could be *very hard* for a new or even moderately proficient chocolatey implementer to find this and determine it was relevant to their needs.

If, however, there was a "Integrating Chocolatey and Octopus" guide page it could explain:
*) How the existing feature of installing from a .nuspec can be used in conjunction with Octopus to accomplish "octopus transformed" chocolatey packages.
*) How the feature (if implemented) of installing from a .nupkg with an alternate extension could be used to allow octopus to do it's native "transport the .nupkg to the end node", but "install with chocolatey" without a bunch of custom code each implementer has to devise, create and test.

So then the value of implementing a feature like this one increases dramatically when people see it mapped to their use cases.  Otherwise the original justification use case get's lost and then the work to implement the feature only benefits the original requester.

**Comment by ferventcoder** [comment]
@DarwinJS I didn't think it was negative. Was just trying to determine what was meant in this context. :D

**Comment by TheCakeIsNaOH** [comment]
@pauby after some discussion with @gep13, we think this is a feature that should not be added due to the likelihood of additional issues being introduced if this is added.

**Comment by DarwinJS** [comment]
I'm fine with that as my need was two employers ago :)

**Comment by TheCakeIsNaOH** [comment]
Closing this then.
