### ISSUE TITLE
Chocolatey-InstallChocolateyPackage fix for double chocolatey folder name is not also applied to the passed in file name.

### ISSUE THREAD

**Issue by ingramc** [chocolatey/choco#908]
### What You Are Seeing?
Value passed in to $silentArgs is corrected to change chocolatey\chocolatey (issue #813) to chocolatey
Value passed in to $file is not corrected to fix chocolatey\chocolatey

### What is Expected?
both variable when passed $env:TEMP\chocolatey should be evaluated to $env:TEMP

### How Did You Get This To Happen? (Steps to Reproduce)
# Extracting contents out of EXE to temp folder
$chocTempDir = Join-Path $env:TEMP 'chocolatey'
$tempDir = Join-Path $chocTempDir 'Package'
Install-ChocolateyInstallPackage 'package' 'exe' "/Q /T:$tempDir" "$fileSetupExe"
# Installing software from extracted folder
$packageExe = Join-Path $tempDir 'PackageName.exe'
Install-ChocolateyInstallPackage 'package' 'exe' '/silent' "$packageExe"

### Output Log
I Apologize for not having direct logs (deleted VM after passing relevant info to relevant users at the organization).

Windows 10
All Windows Updates applied
Choco 0.10.0
Debug and Verbose output displayed that extraction was to $env:TEMP\Package folder while the subsequent call passing in the full path in the file name showed ..AppDate\Local\Temp\chocolatey\chocolatey\Package\PackageName.exe resulting in the exe being reported as missing.

**Comment by ferventcoder** [comment]
This looks like a definite issue - it does have some workarounds for you at the moment though, so I didn't mark it high priority.

The most significant and easy workaround is to set the cacheLocation 

`choco config set cacheLocation somedirectory` - this is what `$env:TEMP` gets set to, so you will not see the double chocolatey.

**Comment by ferventcoder** [comment]
Fixed in 602fd0f5b
