### ISSUE TITLE
Log Errors are Subject to Terminating When Upgrading

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#91]
Due to #48 - when upgrading, all errors are now treated as terminating, including log errors during upgrade. :/

Dies right after the first unpack.

```
Creating ChocolateyInstall as an environment variable (targeting 'Machine')
  Setting ChocolateyInstall to 'C:\Documents and Settings\All Users\Application
 Data\chocolatey'
WARNING: It's very likely you will need to close and reopen your shell
  before you can use choco.
We are setting up the Chocolatey package repository.
The packages themselves go to 'C:\Documents and Settings\All Users\Application
Data\chocolatey\lib'
  (i.e. C:\Documents and Settings\All Users\Application Data\chocolatey\lib\you
rPackageName).
A shim file for the command line goes to 'C:\Documents and Settings\All Users\A
pplication Data\chocolatey\bin'
  and points to an executable in 'C:\Documents and Settings\All Users\Applicati
on Data\chocolatey\lib\yourPackageName'.

Creating Chocolatey folders if they do not already exist.

WARNING: You can safely ignore errors related to missing log files when
  upgrading from a version of Chocolatey less than 0.9.9.
  'Batch file could not be found' is also safe to ignore.
  'The system cannot find the file specified' - also safe.
Out-File : Could not find a part of the path 'C:\Documents and Settings\All Use
rs\Application Data\chocolatey\chocolateyinstall\chocolateyInstall.log'.
At C:\Documents and Settings\All Users\Application Data\chocolatey\chocolateyin
stall\helpers\functions\Write-Host.ps1:12 char:70
+   "$(get-date -format 'yyyyMMdd-HH:mm:ss') [CHOCO] $Object"| Out-File <<<<  -
FilePath $chocoInstallLog -Force -Append
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundExce
   ption
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.Ou
   tFileCommand

Out-File : Could not find a part of the path 'C:\Documents and Settings\All Use
rs\Application Data\chocolatey\chocolateyinstall\chocolateyInstall.log'.
At C:\Documents and Settings\All Users\Application Data\chocolatey\chocolateyin
stall\helpers\functions\Write-Host.ps1:12 char:70
+   "$(get-date -format 'yyyyMMdd-HH:mm:ss') [CHOCO] $Object"| Out-File <<<<  -
FilePath $chocoInstallLog -Force -Append
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundExce
   ption
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.Ou
   tFileCommand

Out-File : Could not find a part of the path 'C:\Documents and Settings\All Use
rs\Application Data\chocolatey\chocolateyinstall\chocolateyInstall.log'.
At C:\Documents and Settings\All Users\Application Data\chocolatey\chocolateyin
stall\helpers\functions\Write-Debug.ps1:12 char:72
+   "$(get-date -format 'yyyyMMdd-HH:mm:ss') [DEBUG] $Message" | Out-File <<<<
 -FilePath $chocoInstallLog -Force -Append
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundExce
   ption
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.Ou
   tFileCommand

The system cannot find the path specified.
```

**Comment by ianchanning** [comment]
Is there a work around to get choco working again?

**Comment by ferventcoder** [comment]
I'm going to release an RC for this over the next hour.

**Comment by ferventcoder** [comment]
Took a little longer than an hour but hopefully you saw that RC6 went out earlier this morning

**Comment by ianchanning** [comment]
Unfortunately, when I tried with RC6 just now I got the same problem. 
I'm on Windows 7 64-bit. I'd done a fresh install of chocolatey v0.9.8.32.

```
C:\windows\system32>choco install chocolatey -pre
!!ATTENTION!!
The next version of Chocolatey (v0.9.9) will require -y to perform
   behaviors that change state without prompting for confirmation. Start
   using it now in your automated scripts.

   For details on the all new Chocolatey, visit http://bit.ly/new_choco
Chocolatey (v0.9.8.33) is installing 'chocolatey' and dependencies. By 
installing you accept the license for 'chocolatey' and each dependency 
you are installing.

chocolatey v0.9.9-rc6
Chocolatey v0.9.9-rc6
Chocolatey is unpacking required files for use. Overwriting? True
Creating ChocolateyInstall as an environment variable (targeting 'Machine')
   Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
WARNING: It's very likely you will need to close and reopen your shell
   before you can use choco.
Adding Modify permission for BUSTER\ian to 'C:\ProgramData\chocolatey'
We are setting up the Chocolatey package repository.
The packages themselves go to 'C:\ProgramData\chocolatey\lib'
   (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin'
   and points to an executable in 
'C:\ProgramData\chocolatey\lib\yourPackageName'.

Creating Chocolatey folders if they do not already exist.

WARNING: You can safely ignore errors related to missing log files when
   upgrading from a version of Chocolatey less than 0.9.9.
   'Batch file could not be found' is also safe to ignore.
   'The system cannot find the file specified' - also safe.
Out-File : Could not find a part of the path 
'C:\ProgramData\chocolatey\chocolateyinstall\chocolateyInstall.log'.
At 
C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-Host.ps1:12 
char:70
+   "$(get-date -format 'yyyyMMdd-HH:mm:ss') [CHOCO] $Object"| Out-File 
<<<<  -FilePath $chocoInstallLog -Force -Append
     + CategoryInfo          : OpenError: (:) [Out-File], 
DirectoryNotFoundException
     + FullyQualifiedErrorId : 
FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

Out-File : Could not find a part of the path 
'C:\ProgramData\chocolatey\chocolateyinstall\chocolateyInstall.log'.
At 
C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-Debug.ps1:12 
char:72
+   "$(get-date -format 'yyyyMMdd-HH:mm:ss') [DEBUG] $Message" | 
Out-File <<<<  -FilePath $chocoInstallLog -Force -Append
     + CategoryInfo          : OpenError: (:) [Out-File], 
DirectoryNotFoundException
     + FullyQualifiedErrorId : 
FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

The system cannot find the path specified.

C:\windows\system32>choco install chocolatey -pre
Cannot find file at '../chocolateyInstall/chocolatey.cmd' 
(C:\ProgramData\chocolatey\chocolateyInstall\chocolatey.cmd). This 
usually indicates a missing or moved file.
```

**Comment by ferventcoder** [comment]
Ah! That's expected. The last upgrade likely have you a very large warning
that you would need to close and reopen your shell.

You should do that. Also ensure that c:\programdata\chocolatey now exists
with a good structure. If it does, you should be able to delete the final
remnant in c:\chocolatey.


On Friday, February 13, 2015, Ian Channing <notifications@github.com> wrote:

> Unfortunately, when I tried with RC6 just now I got the same problem.
> I'm on Windows 7 64-bit. I'd done a fresh install of chocolatey v0.9.8.32.
>
> ```
> C:\windows\system32>choco install chocolatey -pre
> !!ATTENTION!!
> The next version of Chocolatey (v0.9.9) will require -y to perform
> behaviors that change state without prompting for confirmation. Start
> using it now in your automated scripts.
>
> For details on the all new Chocolatey, visit http://bit.ly/new_choco
> Chocolatey (v0.9.8.33) is installing 'chocolatey' and dependencies. By
> installing you accept the license for 'chocolatey' and each dependency
> you are installing.
>
> chocolatey v0.9.9-rc6
> Chocolatey v0.9.9-rc6
> Chocolatey is unpacking required files for use. Overwriting? True
> Creating ChocolateyInstall as an environment variable (targeting 'Machine')
> Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
> WARNING: It's very likely you will need to close and reopen your shell
> before you can use choco.
> Adding Modify permission for BUSTER\ian to 'C:\ProgramData\chocolatey'
> We are setting up the Chocolatey package repository.
> The packages themselves go to 'C:\ProgramData\chocolatey\lib'
> (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
> A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin'
> and points to an executable in
> 'C:\ProgramData\chocolatey\lib\yourPackageName'.
>
> Creating Chocolatey folders if they do not already exist.
>
> WARNING: You can safely ignore errors related to missing log files when
> upgrading from a version of Chocolatey less than 0.9.9.
> 'Batch file could not be found' is also safe to ignore.
> 'The system cannot find the file specified' - also safe.
> Out-File : Could not find a part of the path
> 'C:\ProgramData\chocolatey\chocolateyinstall\chocolateyInstall.log'.
> At
> C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-Host.ps1:12
>
> char:70
> + "$(get-date -format 'yyyyMMdd-HH:mm:ss') [CHOCO] $Object"| Out-File
> <<<< -FilePath $chocoInstallLog -Force -Append
> + CategoryInfo : OpenError: (:) [Out-File],
> DirectoryNotFoundException
> + FullyQualifiedErrorId :
> FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
>
> Out-File : Could not find a part of the path
> 'C:\ProgramData\chocolatey\chocolateyinstall\chocolateyInstall.log'.
> At
> C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-Debug.ps1:12
>
> char:72
> + "$(get-date -format 'yyyyMMdd-HH:mm:ss') [DEBUG] $Message" |
> Out-File <<<< -FilePath $chocoInstallLog -Force -Append
> + CategoryInfo : OpenError: (:) [Out-File],
> DirectoryNotFoundException
> + FullyQualifiedErrorId :
> FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
>
> The system cannot find the path specified.
>
> C:\windows\system32>choco install chocolatey -pre
> Cannot find file at '../chocolateyInstall/chocolatey.cmd'
> (C:\ProgramData\chocolatey\chocolateyInstall\chocolatey.cmd). This
> usually indicates a missing or moved file.
> ```
> On 13/02/2015 03:37, Rob Reynolds wrote:
> >
> > Took a little longer than an hour but hopefully you saw that RC6 went
> > out earlier this morning
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/chocolatey/choco/issues/91#issuecomment-74195570>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/91#issuecomment-74231167>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
Maybe... Rereading.....hmmmm

On Friday, February 13, 2015, Rob Reynolds <ferventcoder@gmail.com> wrote:

> Ah! That's expected. The last upgrade likely have you a very large warning
> that you would need to close and reopen your shell.
>
> You should do that. Also ensure that c:\programdata\chocolatey now exists
> with a good structure. If it does, you should be able to delete the final
> remnant in c:\chocolatey.
>
>
> On Friday, February 13, 2015, Ian Channing <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Unfortunately, when I tried with RC6 just now I got the same problem.
>> I'm on Windows 7 64-bit. I'd done a fresh install of chocolatey v0.9.8.32.
>>
>> ```
>> C:\windows\system32>choco install chocolatey -pre
>> !!ATTENTION!!
>> The next version of Chocolatey (v0.9.9) will require -y to perform
>> behaviors that change state without prompting for confirmation. Start
>> using it now in your automated scripts.
>>
>> For details on the all new Chocolatey, visit http://bit.ly/new_choco
>> Chocolatey (v0.9.8.33) is installing 'chocolatey' and dependencies. By
>> installing you accept the license for 'chocolatey' and each dependency
>> you are installing.
>>
>> chocolatey v0.9.9-rc6
>> Chocolatey v0.9.9-rc6
>> Chocolatey is unpacking required files for use. Overwriting? True
>> Creating ChocolateyInstall as an environment variable (targeting
>> 'Machine')
>> Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
>> WARNING: It's very likely you will need to close and reopen your shell
>> before you can use choco.
>> Adding Modify permission for BUSTER\ian to 'C:\ProgramData\chocolatey'
>> We are setting up the Chocolatey package repository.
>> The packages themselves go to 'C:\ProgramData\chocolatey\lib'
>> (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
>> A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin'
>> and points to an executable in
>> 'C:\ProgramData\chocolatey\lib\yourPackageName'.
>>
>> Creating Chocolatey folders if they do not already exist.
>>
>> WARNING: You can safely ignore errors related to missing log files when
>> upgrading from a version of Chocolatey less than 0.9.9.
>> 'Batch file could not be found' is also safe to ignore.
>> 'The system cannot find the file specified' - also safe.
>> Out-File : Could not find a part of the path
>> 'C:\ProgramData\chocolatey\chocolateyinstall\chocolateyInstall.log'.
>> At
>> C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-Host.ps1:12
>>
>> char:70
>> + "$(get-date -format 'yyyyMMdd-HH:mm:ss') [CHOCO] $Object"| Out-File
>> <<<< -FilePath $chocoInstallLog -Force -Append
>> + CategoryInfo : OpenError: (:) [Out-File],
>> DirectoryNotFoundException
>> + FullyQualifiedErrorId :
>> FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
>>
>> Out-File : Could not find a part of the path
>> 'C:\ProgramData\chocolatey\chocolateyinstall\chocolateyInstall.log'.
>> At
>> C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-Debug.ps1:12
>>
>> char:72
>> + "$(get-date -format 'yyyyMMdd-HH:mm:ss') [DEBUG] $Message" |
>> Out-File <<<< -FilePath $chocoInstallLog -Force -Append
>> + CategoryInfo : OpenError: (:) [Out-File],
>> DirectoryNotFoundException
>> + FullyQualifiedErrorId :
>> FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
>>
>> The system cannot find the path specified.
>>
>> C:\windows\system32>choco install chocolatey -pre
>> Cannot find file at '../chocolateyInstall/chocolatey.cmd'
>> (C:\ProgramData\chocolatey\chocolateyInstall\chocolatey.cmd). This
>> usually indicates a missing or moved file.
>> ```
>> On 13/02/2015 03:37, Rob Reynolds wrote:
>> >
>> > Took a little longer than an hour but hopefully you saw that RC6 went
>> > out earlier this morning
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/chocolatey/choco/issues/91#issuecomment-74195570>.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/chocolatey/choco/issues/91#issuecomment-74231167>.
>>
>
>
> --
>
> Rob
> "Be passionate in all you do"
>
> http://devlicio.us/blogs/rob_reynolds
> http://ferventcoder.com
> http://twitter.com/ferventcoder
>
>

-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
@ianchanning as a workaround for now while I try to see why this is happening, head into C:\ProgramData\chocolatey
and call 
```sh
.\choco.exe unpackself -fdv
```

**Comment by ferventcoder** [comment]
@ianchanning what version of powershell are you running? v2? 

Here's the output I get on a Win2012 server (POSH v4): https://gist.github.com/ferventcoder/672c4688d9155ab450a7

**Comment by ianchanning** [comment]
Yes, v2:

```
PS C:\Users\ian> $PSVersionTable

Name                           Value
----                           -----
CLRVersion                     2.0.50727.5485
BuildVersion                   6.1.7601.17514
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1
```

**Comment by ferventcoder** [comment]
Pull up a Win2003 box right now to see if the behavior is different. My primary box is WIn7x64, but it has been following the upgrade track so it didn't run into issues.

**Comment by ianchanning** [comment]
I noticed that at the point when mine fails `The system cannot find the path specified.` your code calls `choco.exe` but not in the `bin` directory (line 277 in your Gist).

```
Command line: "C:\ProgramData\chocolatey\choco.exe"  unpackself -fdv
```

My debug command output: https://gist.github.com/ianchanning/5488e94275d6de030e84

**Comment by ferventcoder** [comment]
Would you mind dropping into gitter? https://gitter.im/chocolatey/choco

**Comment by ianchanning** [comment]
I've confirmed that on my other Window 7 64-bit machine with POSH 2 it also fails in the same way.

**Comment by ferventcoder** [comment]
I think I have a fix ....

**Comment by ianchanning** [comment]
yep - RC7 works on my machine now
