### ISSUE TITLE
Get-FtpFile error when file is missing (called through Get-ChocolateyWebFile)

### ISSUE THREAD

**Issue by ComFreek** [chocolatey/choco#920]
### What You Are Seeing?
A syntax error when using `Get-ChocolateyWebFile` and the server responds with an error code (e.g. 550 in my case):
> 'env:DownloadCacheAvailable' is not recognized as a cmdlet, function, operable program, or script file. Verify the term and try again.

### What is Expected?
No syntax error :)
### How Did You Get This To Happen? (Steps to Reproduce)
1. Call `Get-ChocolateyWebFile` with a missing file on the server

**Comment by ferventcoder** [comment]
Will be released in 0.10.1.
