### ISSUE TITLE
Powershell functions: Allow access to package title, not only ID

### ISSUE THREAD

**Issue by andmos** [chocolatey/choco#925]
Small issue, but here goes: 
In the [environment variables](https://github.com/chocolatey/choco/wiki/HelpersReference) available from the `ChocolateyInstall.ps1` scripts we get access to the package ID and version. In some cases the title of the package is also usefull - especially if it will be presented a little nicer for the user. 

**Example:**
When adding packages to the registry to uninstall from "Add / Remove programs" - dialogue in Windows is best to give the title of the package, not just the id. It looks better for the user.

I propose a chocolateyPackageTitle variable or similar. 
Any thoughts?

**Comment by ferventcoder** [comment]
Sure, sounds good. Perhaps make other items available as well?

**Comment by jberezanski** [comment]
Could it be a PowerShell variable, not an environment variable? Adding more and more env vars pollutes the environment and increases memory consumption of every proces started by choco during package installation (and on Windows XP there is a limit for the size of the environment block).

**Comment by jberezanski** [comment]
Additionally, one PowerShell variable could store an object with several properties describing the package, making the interface cleaner (one variable instead of many) and easier to extend (just add a property to the object).

**Comment by andmos** [comment]
Yeah the thought has struck me that environment variables might not be the most effective way here. Rewriting it will take some more effort and knowledge about the code, so I will leave that to @ferventcoder!

**Comment by jberezanski** [comment]
I'm concerned because once something is added and documented as public interface it is most likely to stick forever, as changing it will break packages that started depending on it. That's why I'd like to see it done the more desired way from the beginning.

**Comment by andmos** [comment]
Yeah, I am just "adding to the pattern" if you will, but that is how I found the code. We have already used some of these variables in a lot of packages, so it would be a breaking change. Doesn't mean that it should not be done, but a rewrite should be signaled with a obsolete-tag or something like that. Again, I leave this for @ferventcoder!

**Comment by ferventcoder** [comment]
This will be released with 0.10.1. Thanks!
