### ISSUE TITLE
choco help should run the default help command

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#944]
This takes one off of my reminders list to add as an issue.

Also mentioned in #938

**Comment by corbob** [comment]
I think I was supposed to post that I'd like to take a stab at this issue. However I didn't want to post until I had some familiarity with the codebase and how to add to it. I've got a PR I'll be adding to for this.

Currently I'm not confident in the tests being there, or even that it's the best way to do it. I'll be looking at the tests in the next few days to grok what the setup of the current tests is and how I can borrow from them for this one.
