### ISSUE TITLE
Get-ChocolateyUnzip failure for big files

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#95]
Try installing cmake 3.0.1

**Comment by austinsc** [comment]
I'm the maintainer of the cmake package and I made a mistake when I grabbed the update file- I should have grabbed the zip but instead I used the .exe which caused the problem.

**Comment by ferventcoder** [comment]
If you push an update there, just use the fourth version segment as the
date e.g. 20150213.

On Friday, February 13, 2015, Stephen Austin <notifications@github.com>
wrote:

> I'm the maintainer of the cmake package and I made a mistake when I
> grabbed the update file- I should have grabbed the zip but instead I used
> the .exe which caused the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/95#issuecomment-74358784>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
Okay, this is fixed.
