### ISSUE TITLE
"source add -s [url]-u [user] -p [pass]" puts clear text password in chocolatey log file

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#953]
It appears that the default chocolatey logging (debug?) captures the password for a source in the log.

I have worked hard to eliminate the password being recorded on the clients I build using packer and chocolatey, but I can't fix this one.

Even for debug logs I think that secrets should not be recordable in the log.

**Comment by ferventcoder** [comment]
We are addressing things similar to this in 0.10.1
