### ISSUE TITLE
"choco upgrade chocolatey" fails

### ISSUE THREAD

**Issue by nicoddemus** [chocolatey/choco#970]
Hello,

First of all thanks for the excellent tool! It is a time-saver for Windows automation.

We are sometimes experiencing an error when trying to upgrade some packages on our C.I. workers, including `chocolatey` itself. 
### What You Are Seeing?

Here's a sample output:

```
$ choco upgrade chocolatey   || goto :EOF
Chocolatey v0.10.0
Upgrading the following packages:
chocolatey
By upgrading you accept licenses for the packages.

You have chocolatey v0.10.0 installed. Version 0.10.1 is available based on your source(s).
chocolatey not upgraded. An error occurred during installation:
 Could not find a part of the path '\\ci-cache-server\cacheinstall\chocolatey\NuGetScratch\de0623e8-4d97-4a0d-b79e-939c8f94e97a\em2dsfhg.iay\tools\chocolateyInstall\helpers\functions\Format-FileSize.ps1'.
The upgrade of chocolatey was NOT successful.
chocolatey not upgraded. An error occurred during installation:
 Could not find a part of the path '\\ci-cache-server\cacheinstall\chocolatey\NuGetScratch\de0623e8-4d97-4a0d-b79e-939c8f94e97a\em2dsfhg.iay\tools\chocolateyInstall\helpers\functions\Format-FileSize.ps1'.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```
### What is Expected?

We expected no errors when trying to upgrade packages or chocolatey.
### How Did You Get This To Happen? (Steps to Reproduce)

Here is some information about our setup which might be relevant to the problem at hand:
1. We have around 8 Windows C.I. servers, mostly running Windows 10 64bits;
2. At a specific time (1pm), all our Windows C.I. servers start a "provisioning" job which ensures `chocolatey` is running the latest version and other packages are installed and up-to-date (such as `miniconda`).
3. All slaves have the following configuration:
   
   ```
   choco feature enable -n allowGlobalConfirmation
   choco feature enable -n autoUninstaller
   choco config set cacheLocation \\ci-cache-server\cacheinstall\chocolatey
   choco feature enable -n allowEmptyChecksums
   ```
4. One of the first commands executed by the provisioning job is the `choco upgrade chocolatey` above;
5. If we execute the provisioning job sequentially, they complete normally;

We suspect the problem might be the shared cache location and the fact that all slaves start the provisioning job at the same time. We also noticed this problem started recently, but we can't pinpoint an exact version.

Any tips here? Perhaps a shared cache location is not supported in the free version?

cc @gqmelo

**Comment by nicoddemus** [comment]
cc @prusse-martin

**Comment by ferventcoder** [comment]
@nicoddemus When you run the upgrade for chocolatey, it may be better to point it to a local folder as it could be one is deleting a file when it unpacks 

So in other words - `choco upgrade chocolatey --cache-location c:\somelocation`

**Comment by nicoddemus** [comment]
@ferventcoder thanks for the tip! 

We will update our scripts with your tip, but I remember facing the same problem when upgrading other packages as well (`miniconda` if I remember correctly).

**Comment by ferventcoder** [comment]
It's possible a shared cache being accessed concurrently could cause issues. It's not something that is really supported out of the box in any edition of Chocolatey. However it is something that could be enhanced - we would just need to determine where to implement.

**Comment by nicoddemus** [comment]
@ferventcoder thanks for the info, that was our initial suspicion.

**Comment by tradstone** [comment]
Chocolatey v0.10.5
Installing the following packages:
vlc
By installing you accept licenses for the packages.
Progress: Downloading vlc 2.2.6... 99%                                                             vlc not installed. An error occurred during installation:
 Received an unexpected EOF or 0 bytes from the transport stream.
vlc package files install completed. Performing other installation steps.
The install of vlc was NOT successful.
vlc not installed. An error occurred during installation:
 Received an unexpected EOF or 0 bytes from the transport stream.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - vlc (exited 1) - vlc not installed. An error occurred during installation:
 Received an unexpected EOF or 0 bytes from the transport stream.

**Comment by ferventcoder** [comment]
@tradstone please log another issue after you see if it is still occurring in 0.10.7 (or whatever is latest). Thanks!
