### ISSUE TITLE
one zero byte *.nupkg in \lib causes clist -lo to show no packages

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#974]
My use case it to delete large *.nupkg files and retain chocolatey inventory.

So I tried replacing just  one *.nupkg with a zero byte file.

Then "clist -lo" shows "0 packages installed."

I am NOT reporting this bug to ask for my use case to be fixed..

I am thinking that if the code is this sensitive to a single zero byte file when searching for *.nupkgs, it might also report 0 packages for other situations as well.

**Comment by ferventcoder** [comment]
I think this is a duplicate - https://github.com/chocolatey/choco/issues/717

**Comment by ferventcoder** [comment]
> My use case it to delete large *.nupkg files and retain chocolatey inventory.

This you can not do. You must keep the nupkg around, it is what is used by `choco list -lo` to determine if a package is installed.
