### ISSUE TITLE
Don't suggest installing separate "checksum" tool

### ISSUE THREAD

**Issue by Daniel15** [chocolatey/choco#981]
When installing a package without a checksum, this message is displayed:

> If you are a maintainer attempting to determine the checksum for packaging purposes, please run
> 'choco install checksum' and run 'checksum -t sha256 -f $file'

Installing a separate tool is unnecessary as you can simply use PowerShell to accomplish the same thing:

```
(Get-FileHash -Path $file -Algorithm SHA256).Hash
```

**Comment by ferventcoder** [comment]
Unfortunately you know this but you may have missed this was first added in either PowerShell 4 or 5. I believe it was the latter.

**Comment by ferventcoder** [comment]
So we suggest tools that have the greatest compatibility. Plus it is the tool that choco uses.
HTH

**Comment by Daniel15** [comment]
Looks like it was added in PowerShell 4.0 according to MSDN.

It would be nice if Chocolatey checked the user's PowerShell version and suggested `Get-FileHash` if they're on PowerShell 4.0 or higher. No point installing an external tool if the user has a modern PowerShell version 😄

**Comment by ferventcoder** [comment]
That is something we could possibly do. Thanks for the suggestion!

**Comment by ferventcoder** [comment]
Thank you @SeanKilleen for putting that together. This will be released in 0.10.12.
