### ISSUE TITLE
Note that chocolateyUninstall.ps1 may no longer required in template

### ISSUE THREAD

**Issue by Daniel15** [chocolatey/choco#982]
After running `choco new`, it creates a fairly large `chocolateyUninstall.ps1`. However, reading https://github.com/chocolatey/choco/wiki/HelpersUninstallChocolateyPackage, it seems like this is no longer required for MSI installers. Maybe there should be a comment at the top of the file explaining that?

**Comment by ferventcoder** [comment]
Ah, good point - in 80-90% of the cases it is no longer required. In licensed versions there are additional enhancements and Package Synchronizer that bump that up to almost 100%. A comment as to such is a good idea.
