### ISSUE TITLE
Automatic confirm note appears even when option is enabled

### ISSUE THREAD

**Issue by ZviRackover** [chocolatey/choco#993]
Reproducible by:
`choco upgrade -y all`

Below is the interesting part of the output:
```
...
You have Graphviz v2.38 installed. Version 2.38.0.1 is available based on your source(s).

Graphviz v2.38.0.1 [Approved]
graphviz package files upgrade is complete. Performing other installation steps.
The package Graphviz wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting 
 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
```

The last Note: is redundant (and maybe confusing?) because the the '-y' flag was already passed.

**Comment by ferventcoder** [comment]
It's definitely a bug. That note doesn't show up for me and should not show up at all.

What version of choco do you have installed?

Can you provide the log output showing this with --debug --verbose (as requested when you created the issue)?

**Comment by ferventcoder** [comment]
None of this should show up - 

~~~
The package Graphviz wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting 
 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
~~~

https://github.com/chocolatey/choco/blob/2c4dc5b48128309b38565ad26cc66db37c207ab1/src/chocolatey/infrastructure.app/services/PowershellService.cs#L203-L242

**Comment by ZviRackover** [comment]
Thanks for responding.
The version is v0.10.2 which is what choco upgraded itself to at some point.
Can you please suggest a way to reproduce this? I need to install a package at a not-most-recent version, and then run a 'chocho upgrade -y  --debug --verbose all'.
Is there a known package that i can 'install --version <oldversion>'? I couldn't find any.

**Comment by ferventcoder** [comment]
Head into your logs folder and it should have already captured the output as debug/verbose. You can just send it over.

When it gave out those messages, did it pause and wait for an answer or just pass the message?

**Comment by ZviRackover** [comment]
I run another upgrade -y today and one of the packages got upgraded, but this issue did not reproduce.
I am closing this bug and will reopen if ever happens again. Thanks.

**Comment by iqbal-vijeta** [comment]
choco install themekit
Chocolatey v0.10.15
Installing the following packages:
themekit
By installing you accept licenses for the packages.

Progress: Downloading themekit 1.0.0... 18%
Progress: Downloading themekit 1.0.0... 100%

themekit v1.0.0 [Approved]
themekit package files install completed. Performing other installation steps.
The package themekit wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation

I get this message. Plz help me.

**Comment by niclaslindstedt** [comment]
Bumping into this too when installing nvm using choco.

I have run `choco feature enable -n allowGlobalConfirmation` but still getting the prompt.

```
Chocolatey v0.10.15
[Pending] Removing incomplete install for 'nvm.portable'
Installing the following packages:
nvm
By installing you accept licenses for the packages.

nvm.portable v1.1.7 [Approved]
nvm.portable package files install completed. Performing other installation steps.
The package nvm.portable wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint):
```
