### ISSUE TITLE
choco outdated should list pinned packages separate from non-pinned ones.

### ISSUE THREAD

**Issue by mattslay** [chocolatey/choco#994]
### What You Are Seeing?

When issuing "choco outdated", it lists packages that I have previously added to the pinned list.
### What is Expected?

I would prefer to see the pinned packages listed separately from the other ones that are not pinned. Or, add a command line switch to have pinned packages NOT included in the list.
### How Did You Get This To Happen? (Steps to Reproduce)

Pin a package that has an upgrade that I have not pulled down locally. Issue "choco outdated" and it lists the pinned package right along with all the other ones. This makes it hard to see the ones I may want to upgrade from the ones I do not.

**Comment by mattslay** [comment]
Ahah!  I've learned that I can use piping and the "findstr" command to filter the list.  It's a little crude, but it works great:

To see non-pinned ones that are outdated:
`choco outdated | findstr "false" `

To see pinned ones that are outdated:
`choco outdated | findstr "true" `

**Comment by ferventcoder** [comment]
Good point, perhaps a switch to ignore all the pinned ones?

**Comment by ferventcoder** [comment]
This will be in 0.10.6. Thanks!

**Comment by ferventcoder** [comment]
#580
