### ISSUE TITLE
The refreshenv command throws an error about Write-FunctionCallLogMessage when ran in powershell on 0.10.2.

### ISSUE THREAD

**Issue by jesseconnr** [chocolatey/choco#996]
### What You Are Seeing?

In release 0.10.2 when running refreshenv from powershell, several errors are output.

### What is Expected?

The expected result would be that no errors are output.

### How Did You Get This To Happen? (Steps to Reproduce)

Upgrade to chocolatey 0.10.2 and run refreshenv from powershell.

### The Reason

The chocolateyProfile.psm1 uses the function Get-EnvironmentVariable. This function in turn uses Write-FunctionCallLogMessage, but Write-FunctionCallLogMessage.psm1 is not imported in the profile and therefore errors occur.

[chocolateyProfile.psm1#L20](https://github.com/chocolatey/choco/blob/0.10.2/src/chocolatey.resources/helpers/chocolateyProfile.psm1#L20)

[Get-EnvironmentVariable.ps1#L65](https://github.com/chocolatey/choco/blob/0.10.2/src/chocolatey.resources/helpers/functions/Get-EnvironmentVariable.ps1#L65)

[Write-FunctionCallLogMessage.ps1](https://github.com/chocolatey/choco/blob/0.10.2/src/chocolatey.resources/helpers/functions/Write-FunctionCallLogMessage.ps1)

### Output Log

There is no log generated with the refreshenv command, but here is the console output.

Chocolatey Veriosn: 0.10.2
OS: Windows 10 Enterprise x64
PS Version: 5.1.14393.206

 [https://gist.github.com/jesseconnr/37e5d78d008fd5bb9fa8b9dbb6e5f08c](https://gist.github.com/jesseconnr/37e5d78d008fd5bb9fa8b9dbb6e5f08c)

**Comment by ferventcoder** [comment]
Fixed for 0.10.3. Thanks for reporting!
