### ISSUE TITLE
unzip issue for install.ps1 on Windows Server 2012 R2 Core machines

### ISSUE THREAD

**Issue by JoshuaToth** [chocolatey/choco#997]
### What You Are Seeing?
Now when installing via powershell on a Windows Server 2012 R2 Core "headless" environment chocolatey fails to unzip using the using built-in compression. It must use 7zip, which can be enabled with the environment variable, yes, but it does not work without it. 

### What is Expected?
The install.ps1 script is able to install without the use of 7zip in a Windows Server 2012 R2 Core environment. This was working previously and has stopped working very recently (03 - Oct - 2016).

### How Did You Get This To Happen? (Steps to Reproduce)
Run the install.ps1 script in an Windows Server 2012 R2 Core environment without the 7zip flag.  (like ami-e28fa681 for example in AWS)

### Output Log

~~~sh
.\install.ps1 --debug --verbose
Getting latest version of the Chocolatey package for download.
Downloading https://chocolatey.org/api/v2/package/chocolatey/0.10.2 to C:\Users\ADMINI~1\AppData\Local\Temp\2\chocolatey\chocInstall\chocolatey.zip
Extracting C:\Users\ADMINI~1\AppData\Local\Temp\2\chocolatey\chocInstall\chocolatey.zip to C:\Users\ADMINI~1\AppData\Local\Temp\2\chocolatey\chocInstall...
Unable to unzip package using built-in compression. Set $env:chocolateyUseWindowsCompression = 'false' and call install again to use 7zip to unzip. Error: Exception calling "NameSpace" with "1" argument(s): "Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))" At C:\Users\Administrator\install.ps1:185 char:5
+     throw "Unable to unzip package using built-in compression. Set`$env:chocola ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Unable to unzip...4005 (E_FAIL))":String) [], RuntimeException
+ FullyQualifiedErrorId : Unable to unzip package using built-in compression. Set $env:chocolateyUseWindowsCompression = 'false' and call install again to use 7zip to unzip. Error: Exception calling "NameSpace" with "1" argument(s): "Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))"
~~~

**Comment by ferventcoder** [comment]
Howdy - wrong repository. This is related to the website. Please file over at https://github.com/chocolatey/chocolatey.org/issues.
Thanks!

**Comment by ferventcoder** [comment]
Once you file over there, we'll discuss why the changes and that the workaround/fix is provided in the error because we knew it would break some folks.
