### ISSUE TITLE
Possible bug related to search path when running `choco install`

### ISSUE THREAD

**Issue by metalseargolid** [chocolatey/choco#999]
Chocolatey Version: 0.10.1

First off, I love Chocolatey and I think your team has resolved one of the biggest letdowns of Windows: no CLI package management. Thank you for all of the time put into this project!

I believe I have run into a bug when running `choco install`. While developing several custom packages for a private repository, I had used an incorrect relative $url path in the chocolateyInstall.ps1 script for ~50 packages (in our repo all packages have the sources pre-cached and packaged inside of the nupkg). However, these paths were valid from my current working directory when invoking `choco install package-name` while testing, so testing the installation of each package seemed to work fine. The issue was discovered when I tried installing each package from a different directory where the relative paths would no longer resolve.

While I did fix the path issue in each of my scripts, it concerns me that Chocolatey was attempting to resolve paths in my CWD by default when installing a package file (this behavior occurs whether i'm installing a package via name or using a path to a nupkg file). As a user, I would expect that installing a package would only concern the files contained in the nupkg, and that any other required files or directories would be passed in as parameters.

**Comment by ferventcoder** [comment]
@metalseargolid perhaps you can elaborate a bit?

When you run `choco new`, Chocolatey provides you with a `$toolsDir` set to the proper path of the root of the package directory.

My first question, did you use `choco new` to create the packages?

**Comment by ferventcoder** [comment]
Second, url is technically incorrect and tells me that you are likely using `Install-ChocolateyPackage` instead of what you would have seen with `choco new` - documentation in the chocolateyInstall.ps1 leading you to use `Install-ChocolateyInstallPackage` - we also have documentation at https://chocolatey.org/docs/helpers-reference for using the different functions. 

See 

* https://chocolatey.org/docs/helpers-install-chocolatey-package
* https://chocolatey.org/docs/helpers-install-chocolatey-install-package

**Comment by ferventcoder** [comment]
Choco new produces what we call just in time documentation, and we have quite a default template. I would recommend trying `choco new test` just to see what it produces and if that alleviates some of your recent confusion?

**Comment by metalseargolid** [comment]
I did not generate the package using `choco new`. However, it does look like $toolsDir is being used as a parameter all over the place, and my scripts have another variable that serves a similar purpose (it was this variable that was incorrectly set in the first place). If this behavior is by design, I'll concede that it's not a bug and something I must be mindful of moving forward, the behavior just seemed incorrect to me.

You are correct in that we are using Install-ChocolateyPackage, based on a previously existing template of ours (which is probably outdated if there is another function we should be using).

At a first glance, Install-ChocolateyPackageInstall looks to be better for installing from a local path, so I'll look into using that moving forward.

**Comment by ferventcoder** [comment]
I am not sure if or how we could ensure that relative paths in scripts could apply to the powershell file directory, so we've always preferred a much more deterministic approach - starting from the folder root of where the script is with `$toolsDir`.

**Comment by metalseargolid** [comment]
The way you guys do it by setting a variable (in this case, `$toolsdir = [System.IO.Path]::GetDirectoryName($myInvocation.MyCommand.Definition)` is how I believe you're using it in the generated template) and working with that as the root of all expected "relative" paths in the script is the only way to make it work. Powershell 3 lets you use the $PSScriptRoot variable which should (in theory, I haven't tested this yet) equal `[System.IO.Path]::GetDirectoryName($myInvocation.MyCommand.Definition)`.

In doing some of my own research on the subject, it doesn't look like PS offers a graceful mechanism for running a script using an alternate working directory. As far as applying paths relative to the working directory, the use of `Set-Location $PSScriptRoot` comes to mind,, but that would fall on the installation script maintainer to implement. Use of the `START "" /d DIRPATH COMMAND [ARGS] PARAMETERS` command from within Chocolatey.exe (or whichever process starts the install script) would probably work, but that's not very Powershell-y :) (and `START` can be very frustrating to use in its own right).

It's looking more like my gripe is an issue with the inner workings of Powershell and not so much with Chocolatey. I could go on all day about hokey things that grind my gears about Powershell, but I won't go into all of that here.

**Comment by ferventcoder** [comment]
> Powershell 3 lets you use the `$PSScriptRoot` variable which should (in theory, I haven't tested this yet) equal `[System.IO.Path]::GetDirectoryName($myInvocation.MyCommand.Definition)`.

It's `"$(Split-Path -parent $MyInvocation.MyCommand.Definition)"`, and yes it is a PowerShell v2+ way of stating the same thing as  `$PSScriptRoot`.

> It's looking more like my gripe is an issue with the inner workings of Powershell and not so much with Chocolatey. I could go on all day about hokey things that grind my gears about Powershell, but I won't go into all of that here.

If we ever meet up in person, we can talk at length about PowerShell over drinks! I feel your pain. 👍
